### ISSUE TITLE
Zero copy serialization raises assert

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1001]
Using zero copy serialization over the wire raises this assert: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/parcelset/server/tcp/parcelport_server_connection.hpp#L263.

**Comment by sithhell** [comment]
This test is still failing occasionally. See for example here:
http://hermione.cct.lsu.edu/builders/hpx_clang_3_4_boost_1_55_debian_x86_64_release/builds/290/steps/run_regression_tests/logs/tests.regressions.util.distributed.tcp.zero_copy_parcels_1001_no_zero_copy_optimization%20%280.36%20sec%29

**Comment by hkaiser** [comment]
I have not seen failing this test for a long time. So I'll go ahead and close this ticket. Please reopen, if necessary.
