### ISSUE TITLE
Decrease in application performance overtime; occasional spikes of major slowdown

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/hpx#1008]
HPX applications running with the MPI parcelport in distributed at scale experience a linear degradation in performance as application runtime increases. Also, periodically, there are spikes of massive slowdown.

This can be demonstrated by running the [future_hang_on_get_629](https://github.com/STEllAR-GROUP/hpx/blob/master/tests/regressions/lcos/future_hang_on_get_629.cpp) regression test with the MPI parcelport like so:

```
mpirun -x LD_LIBRARY_PATH="$LD_LIBRARY_PATH" -machinefile machinefile -bynode -np 16 /home/wash/install/octopus/intel-13.0.1-release/bin/future_hang_on_get_629_test --verbose --depth=5 --test-runs=0
```

This regression test spawns a recursive tree (with a certain number of children per node, in this case, we use the default of 8), and calls the standard busy work null_function on each node of the tree. The depth of the tree is, in this case, 5 levels deep (analogous to 5 levels of refinement). We run this test for a certain number of iterations (e.g. timesteps)

The behavior demonstrated by this test case is very similar to the performance issues that the Octopus 3D torus simulation encounters. Here are some graphs demonstrating the problem. They plot the timestep speed (e.g. timesteps/second) for each timestep; e.g. instantaneous speed. Note that the first two graphs are logscaled.

[629 regresison test, logscaled](http://www.cct.lsu.edu/~blelbach/images/629_ts_speed_logscaled.png)
[Octopus, logscaled](http://www.cct.lsu.edu/~blelbach/images/octopus_ts_speed_logscaled.png)
[629 regression test](http://www.cct.lsu.edu/~blelbach/images/629_ts_speed.png)
[Octopus](http://www.cct.lsu.edu/~blelbach/images/octopus_ts_speed.png)

**Comment by sithhell** [comment]
Do we still have this problem?

**Comment by hkaiser** [comment]
I'm pretty sure this is caused by memory fragmentation increasing overtime. I don't have any other explanation. So I'm not sure we can do anything about this.

**Comment by hkaiser** [comment]
This has been fixed. Please reopen if appropriate (see #1753)
