### ISSUE TITLE
Replace startup and shutdown barriers with broadcasts

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1085]
Replacing the barriers used during startup and shutdown with broadcast actions will speed up those operations for larger runs.

**Comment by hkaiser** [comment]
I'm inclined to close this ticket. Most of the work has been done. I'm not sure whether it is possible at all to replace the current Dijkstra termination detection with a faster version (see the reasons outlined above).

**Comment by sithhell** [comment]
I agree, this ticket can be closed. Startup/shutdown seems to be quite fast at the moment, even at larger scales.
