### ISSUE TITLE
Warning C4005: _WIN32_WINNT: Macro redefinition

### ISSUE THREAD

**Issue by Syntaf** [STEllAR-GROUP/hpx#1095]
When building on VS2012 4.5 using HPX I am receiving a number of warnings/errors pertaining to winstock and winstock2.h, the entire list below:

`1>C:\Program Files\hpx\include\hpx/config/defines.hpp(63): warning C4005: '_WIN32_WINNT' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\shared\sdkddkver.h(196) : see previous definition of '_WIN32_WINNT'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(96): warning C4005: 'AF_IPX' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(452) : see previous definition of 'AF_IPX'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(136): warning C4005: 'AF_MAX' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(471) : see previous definition of 'AF_MAX'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(173): warning C4005: 'SO_DONTLINGER' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(394) : see previous definition of 'SO_DONTLINGER'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(217): error C2011: 'sockaddr' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(477) : see declaration of 'sockaddr'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(414): error C2059: syntax error : 'constant'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(414): error C3805: 'constant': unexpected token, expected either '}' or a ','
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(549): warning C4005: 'IN_CLASSA' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(279) : see previous definition of 'IN_CLASSA'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(555): warning C4005: 'IN_CLASSB' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(285) : see previous definition of 'IN_CLASSB'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(561): warning C4005: 'IN_CLASSC' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(291) : see previous definition of 'IN_CLASSC'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(572): warning C4005: 'INADDR_ANY' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(296) : see previous definition of 'INADDR_ANY'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(574): warning C4005: 'INADDR_BROADCAST' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(298) : see previous definition of 'INADDR_BROADCAST'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\shared\ws2def.h(608): error C2011: 'sockaddr_in' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(304) : see declaration of 'sockaddr_in'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(125): error C2011: 'fd_set' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(60) : see declaration of 'fd_set'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(145): warning C4005: 'FD_CLR' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(89) : see previous definition of 'FD_CLR'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(160): warning C4005: 'FD_SET' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(94) : see previous definition of 'FD_SET'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(169): error C2011: 'timeval' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(103) : see declaration of 'timeval'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(225): error C2011: 'hostent' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(159) : see declaration of 'hostent'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(238): error C2011: 'netent' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(172) : see declaration of 'netent'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(245): error C2011: 'servent' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(179) : see declaration of 'servent'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(257): error C2011: 'protoent' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(191) : see declaration of 'protoent'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(353): error C2011: 'WSAData' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(314) : see declaration of 'WSAData'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(451): error C2011: 'sockproto' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(486) : see declaration of 'sockproto'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(493): error C2011: 'linger' : 'struct' type redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(523) : see declaration of 'linger'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(506): warning C4005: 'SOMAXCONN' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(536) : see previous definition of 'SOMAXCONN'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(536): warning C4005: 'FD_READ' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(554) : see previous definition of 'FD_READ'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(539): warning C4005: 'FD_WRITE' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(555) : see previous definition of 'FD_WRITE'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(542): warning C4005: 'FD_OOB' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(556) : see previous definition of 'FD_OOB'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(545): warning C4005: 'FD_ACCEPT' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(557) : see previous definition of 'FD_ACCEPT'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(548): warning C4005: 'FD_CONNECT' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(558) : see previous definition of 'FD_CONNECT'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(551): warning C4005: 'FD_CLOSE' : macro redefinition
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(559) : see previous definition of 'FD_CLOSE'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1577): error C2375: 'accept' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(734) : see declaration of 'accept'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1599): error C2375: 'bind' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(739) : see declaration of 'bind'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1618): error C2375: 'closesocket' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(744) : see declaration of 'closesocket'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1637): error C2375: 'connect' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(746) : see declaration of 'connect'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1658): error C2375: 'ioctlsocket' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(751) : see declaration of 'ioctlsocket'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1679): error C2375: 'getpeername' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(756) : see declaration of 'getpeername'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1700): error C2375: 'getsockname' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(761) : see declaration of 'getsockname'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1723): error C2375: 'getsockopt' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(766) : see declaration of 'getsockopt'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1744): error C2375: 'htonl' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(773) : see declaration of 'htonl'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1761): error C2375: 'htons' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(775) : see declaration of 'htons'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1778): error C2375: 'inet_addr' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(777) : see declaration of 'inet_addr'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1795): error C2375: 'inet_ntoa' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(779) : see declaration of 'inet_ntoa'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1896): error C2375: 'listen' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(781) : see declaration of 'listen'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1914): error C2375: 'ntohl' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(785) : see declaration of 'ntohl'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1931): error C2375: 'ntohs' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(787) : see declaration of 'ntohs'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1951): error C2375: 'recv' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(789) : see declaration of 'recv'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(1976): error C2375: 'recvfrom' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(795) : see declaration of 'recvfrom'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2002): error C2375: 'select' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(803) : see declaration of 'select'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2026): error C2375: 'send' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(810) : see declaration of 'send'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2051): error C2375: 'sendto' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(816) : see declaration of 'sendto'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2077): error C2375: 'setsockopt' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(824) : see declaration of 'setsockopt'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2099): error C2375: 'shutdown' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(831) : see declaration of 'shutdown'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2120): error C2375: 'socket' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(835) : see declaration of 'socket'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2144): error C2375: 'gethostbyaddr' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(842) : see declaration of 'gethostbyaddr'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2163): error C2375: 'gethostbyname' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(847) : see declaration of 'gethostbyname'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2181): error C2375: 'gethostname' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(849) : see declaration of 'gethostname'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2221): error C2375: 'getservbyport' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(853) : see declaration of 'getservbyport'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2240): error C2375: 'getservbyname' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(857) : see declaration of 'getservbyname'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2258): error C2375: 'getprotobynumber' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(861) : see declaration of 'getprotobynumber'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2275): error C2375: 'getprotobyname' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(863) : see declaration of 'getprotobyname'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2296): error C2375: 'WSAStartup' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(867) : see declaration of 'WSAStartup'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2315): error C2375: 'WSACleanup' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(871) : see declaration of 'WSACleanup'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2332): error C2375: 'WSASetLastError' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(873) : see declaration of 'WSASetLastError'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2349): error C2375: 'WSAGetLastError' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(875) : see declaration of 'WSAGetLastError'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2366): error C2375: 'WSAIsBlocking' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(877) : see declaration of 'WSAIsBlocking'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2383): error C2375: 'WSAUnhookBlockingHook' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(879) : see declaration of 'WSAUnhookBlockingHook'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2400): error C2375: 'WSASetBlockingHook' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(881) : see declaration of 'WSASetBlockingHook'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2417): error C2375: 'WSACancelBlockingCall' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(883) : see declaration of 'WSACancelBlockingCall'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2439): error C2375: 'WSAAsyncGetServByName' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(885) : see declaration of 'WSAAsyncGetServByName'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2466): error C2375: 'WSAAsyncGetServByPort' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(893) : see declaration of 'WSAAsyncGetServByPort'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2492): error C2375: 'WSAAsyncGetProtoByName' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(901) : see declaration of 'WSAAsyncGetProtoByName'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2517): error C2375: 'WSAAsyncGetProtoByNumber' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(908) : see declaration of 'WSAAsyncGetProtoByNumber'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2542): error C2375: 'WSAAsyncGetHostByName' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(915) : see declaration of 'WSAAsyncGetHostByName'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2569): error C2375: 'WSAAsyncGetHostByAddr' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(922) : see declaration of 'WSAAsyncGetHostByAddr'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2592): error C2375: 'WSACancelAsyncRequest' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(931) : see declaration of 'WSACancelAsyncRequest'
1>C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock2.h(2612): error C2375: 'WSAAsyncSelect' : redefinition; different linkage
1>          C:\Program Files (x86)\Windows Kits\8.0\Include\um\winsock.h(933) : see declaration of 'WSAAsyncSelect'`

Notes about the project being built:

SFML x64
Latest HPX github build
v110 Platform toolkit

**Comment by brandon-kohn** [comment]
I get this issue when compiling hpx as per the build for windows instructions. The solutions put forth here don't make sense in this context as I would have to edit the hpx project to get it to build. Am I missing something?

Thanks

**Comment by brandon-kohn** [comment]
Note that Hartmut's suggestion to add hpx/hpx_fwd.hpp fixes this. The file I added it to is hpx/src/runtims/agas/response.cpp just after the hpx/config.hpp include. Perhaps this should be added to the codebase.

**Comment by hkaiser** [comment]
@brandon-kohn: I meant that you should add `hpx/hpx_fwd.hpp` to your compilation units, not to anything in HPX.

**Comment by brandon-kohn** [comment]
Yes, but I'm trying to compile HPX. There is no code of mine to which I could add it.

**Comment by hkaiser** [comment]
Sorry, I misunderstood! What compiler do you use? What file is failing to compile? Could you please upload your file `CMakeCache.txt` and link it here?

**Comment by brandon-kohn** [comment]
I'm using vc12 both 64 and 32 bit with the current boost master (1.58) and hwloc 1.10.1 on windows 8.1 64-bit.

Here's a link: https://gist.github.com/brandon-kohn/fbf740f7cb4f2f12a80d#file-hpx-64bit-cmakecache-txt

Note it does compile when I add that forward include as you suggested.
