### ISSUE TITLE
Implement 'migration' to and from disk

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1163]
Implement an alternative backend for migration which stores the byte stream to disk and retrieves it back from disk.

**Comment by hkaiser** [comment]
This has been implemented by merging #1375: Fixing 1163

**Comment by sithhell** [comment]
While merging #1375 is the first into that direction, it hasn't implemented disk storage. reopening.

**Comment by hkaiser** [comment]
The first steps have been implemented, moving the rest to the next milestone...
