### ISSUE TITLE
Starting HPX on Cray machines using aprun isn't working correctly

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1168]
In order to use HPX applications on Cray machines you currently have to explicitly pass ```-Ihpx.parcel.bootstrap=mpi -Ihpx.parcel.tcp.enable=0``` as command line parameters. If the explicit disabling of the TCP parcelport is omitted, the MPI parcelport throws this error: https://github.com/STEllAR-GROUP/hpx/blob/master/src/runtime/parcelset/policies/mpi/connection_handler_mpi.cpp#L60

In order to fix this, we need to:
  - [x] Detect the usage of the MPI parcelport automatically when using aprun
  - [x] Fix the bug which is leading to that erroneous error message

**Comment by hkaiser** [comment]
What's missing here? Should we move that to the next milestone?

**Comment by sithhell** [comment]
Moving it to the next milestone. The workaround is to disable the tcp parcelport.

**Comment by hkaiser** [comment]
Could you describe what is causing the problem, actually?

**Comment by sithhell** [comment]
Hmmm, looking at the initial post again, the wrong error message might have been fixed already. The only remaining missing part is to automatically detect the MPI parcelport. Or better yet ... have a native GNI parcelport implementation ...

**Comment by hkaiser** [comment]
Detecting MPI properly should be doable, the GNI parcel port however is not for this release...

**Comment by sithhell** [comment]
Moving back to 0.9.10 as it is currently not possible to run on cray systems at all.

**Comment by hkaiser** [comment]
[Mar 9, 08:52]	hkaiser: heller: what's still to be done for #1168?
[Mar 9, 08:52]	heller: hkaiser: nothing. forgot to close
