### ISSUE TITLE
NUMA aware allocators

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1236]
In order to efficiently use ``std::vector`` and friends, a NUMA aware allocator needs to be written.
This work needs to be complemented with a proper NUMA aware executor to allow to iterate over vectors or similar in a memory efficient manner.

**Comment by hkaiser** [comment]
Moving this to the next milestone.

**Comment by hkaiser** [comment]
There is currently some work being done on the branch os_executors (particularily this commit: bc4153914014dc5a0e741793cde4d1fe85eb87da)

**Comment by hkaiser** [comment]
We have added `parallel::util::numa_allocator` (see [here](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/parallel/util/numa_allocator.hpp)), which uses an executor to perform first-touch on the allocated data.
