### ISSUE TITLE
The parcelport implementation is non-optimal

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1275]
Our current implementation of the parcelport does not properly keep the underlying network interfaces busy enough to reach peak bandwidth.
In order to solve this we need to:
- Decouple the parcel encoding from the connections
- Have the connections send encoded parcels continously

This will also fix #1217

**Comment by hkaiser** [comment]
Can we close this now (after merging #1361)?

**Comment by sithhell** [comment]
Yes, this is resolved now. However, the resolution to this problem was different than initially thought.
The answer to the sub-optimal parcelport performance was to encode and send the parcels synchronously while allowing other HPX threads to send and encode as well. This has been demonstrated with the rewrite of the MPI parcelport.
As we know how to generically write fast parcelports, this ticket can be closed.
