### ISSUE TITLE
HDF5 build error

### ISSUE THREAD

**Issue by Titzi90** [STEllAR-GROUP/hpx#1294]
HPX will note build (error in cmake configure phase) if HDF5 is installed on the system but just withe the fortran interface (no cpp).
The following two examples run into this issue:
- interpolate1d
- sheneos

cmake output:

...
-- Found HDF5: HDF5_hdf5_cpp_LIBRARY-NOTFOUND;/usr/lib64/libhdf5.so 
...
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDF5_hdf5_cpp_LIBRARY
    linked by target "create_1d_testdata_exe" in directory /home/titzi/hpx/hpx/repo_origin/examples/interpolate1d
    linked by target "interpolate1d_component" in directory /home/titzi/hpx/hpx/repo_origin/examples/interpolate1d/interpolate1d
    linked by target "sheneos_component" in directory /home/titzi/hpx/hpx/repo_origin/examples/sheneos/sheneos

**Comment by hkaiser** [comment]
Is this still a problem?

**Comment by sithhell** [comment]
Yes. Fix incoming in a second...
