### ISSUE TITLE
Crashing in hpx::parcelset::policies::mpi::connection_handler::handle_messages() on SuperMIC

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1310]
I am getting crashes when I run my fmmx code on SuperMIC on more than one node. This is using only host processors. The last HPX call on the stack (that I can tell) is hpx::parcelset::policies::mpi::connection_handler::handle_messages(). The stack trace is here:
https://gist.github.com/dmarce1/fc69d303159b2744115a

The code I am running is here:
https://github.com/dmarce1/xtree

**Comment by dmarce1** [comment]
I am still getting this same error, even after a near complete re-write of my code. The new version, here: https://github.com/dmarce1/fmmx, crashes with the same error https://gist.github.com/dmarce1/99ef347a60a4243e7962. This is with 64 nodes running a single MPI process per node and -t20. Boost 1.57. (My latest pull from HPX is less than 2 days old)

**Comment by sithhell** [comment]
Does the same happen with a debug build?
How does it behave on less nodes?
Could you try to reduce your problem to a minimum so it's easier to identify where exactly the problem occurs?
Could you provide a CMakeLists.txt please so I can try myself?

**Comment by hkaiser** [comment]
Does this still happen on master (after merging #1361)?

**Comment by dmarce1** [comment]
It hasn't happened with the tests I've run so far. However, I'm still getting a hang on start up quite frequently for larger runs (128 nodes)

**Comment by sithhell** [comment]
Is this with latest master? I made some minor enhancements this morning.
Which configuration (mpi version, compiler, boost etc) still on supermic?

**Comment by hkaiser** [comment]
This can be closed now. @dmarce1 reported that this was fixed by the latest parcelport patches.
