### ISSUE TITLE
Errors while running performance tests

### ISSUE THREAD

**Issue by thejkane** [STEllAR-GROUP/hpx#1315]
Hello,

When running performance tests (in IU BR2) I faced 3 issues. I am not sure whether these are actual issues or whether i can resolve them by changing hpx runtime parameters. Therefore I am stating all 3 issues in this ticket. But if they are unrelated I can create different issues.

1. When I run application with default "hpx.parcel.max_message_size", I get following error;
"terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hpx::exception> >'
  what():  The size of this message exceeds the maximum inbound data size: HPX(unknown_error)
_pmiu_daemon(SIGCHLD): [NID 00445] [c8-0c1s1n3] [Wed Nov 12 21:45:48 2014] PE RANK 0 exit signal Aborted
[NID 00445] 2014-11-12 21:45:48 Apid 3943743: initiated application termination
Application 3943743 exit codes: 134"

2. To overcome above error, we double the message size (hpx.parcel.max_message_size). Then we got following error;
"terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hpx::exception> >'
  what():  new allocator failed to allocate memory: HPX(out_of_memory)
_pmiu_daemon(SIGCHLD): [NID 00849] [c5-0c2s7n3] [Wed Nov 12 22:48:32 2014] PE RANK 1 exit signal Aborted
[NID 00849] 2014-11-12 22:48:32 Apid 3943887: initiated application termination"

3. The third issue is related to MPI. When running application with doubled message size (sometimes) we got following error;

Running distributed control for scale : 25, num_queues : 40, yield count : 100000, max_weight : 100, source : 28018238, iteration : 3
Rank 0 [Wed Nov 12 23:02:23 2014] [c5-0c1s3n2] Fatal error in PMPI_Test: Message truncated, error stack:
PMPI_Test(170)....................: MPI_Test(request=0x2aab7846acd0, flag=0x2aab75dff4ac, status=0x2aab75dff4b0) failed
MPIR_Test_impl(65)................:
MPIDI_CH3U_Receive_data_found(144): Message from rank 1 and tag 2732 truncated; 4 bytes received but buffer size is 1
_pmiu_daemon(SIGCHLD): [NID 00824] [c5-0c1s3n2] [Wed Nov 12 23:02:24 2014] PE RANK 0 exit signal Aborted
[NID 00824] 2014-11-12 23:02:24 Apid 3943913: initiated application termination
Application 3943913 exit codes: 134
Application 3943913 exit signals: Killed
Application 3943913 resources: utime ~6867s, stime ~88s, Rss ~13000116, inblocks ~182893, outblocks ~3138
Job Cleanup ran on Wed Nov 12 23:02:24 EST 2014

All those issues are "not" consistently reproducible. I am running application in 20 nodes with 32 OS threads in each node. The exact command looks as follows;

aprun -b -n 20 -d 16 -N 1 ./dc_sssp --num_sources 30 --scale 25 --queues 40 --yield_count 100000 --hpx:threads 16 -Ihpx.parcel.tcp.enable=0 -Ihpx.parcel.bootstrap=mpi -Ihpx.parcel.max_message_size=2000000000

You may also find dumped configurations in [1] (values maybe duplicated as i ran dum_config on 2 nodes)

Seems like issues 1 and 2 are related and I believe tweaking runtime parameters we can overcome these errors. But I dont have a very clear idea what runtime parameters should be used and with what values. Could you please elaborate on what runtime parameters I should try out and what sort of values they should hold ? But I dont have an idea about issue 3. What could be the reason ?

[1] http://pastebin.com/jkKPC9Ny

Thank you
Regards
Thejaka Amila

**Comment by hkaiser** [comment]
@thejkane: we fixed a lot of issues (bugs and performance related) by merging #1361. It might make sense for you to try again now.

**Comment by thejkane** [comment]
Hello Hkaiser,

Thank you. Sorry, I was away and was in my home country to get some errands done. Today only I returned to IU. I will try latest trunk code with the algorithm.

Regards
Thejaka

**Comment by hkaiser** [comment]
@thejkane: do you have any update on this? We're trying to get a release candidate prepared and would like to know which tickets need attention, still.

**Comment by hkaiser** [comment]
Moving this to the next milestone (at least until we hear back from @thejkane).

**Comment by hkaiser** [comment]
I'll go ahead an close this as we have not heart back from @thejkane for a long time. Feel free to reopen, if necessary.
