### ISSUE TITLE
Exceptions thrown during parcel handling are not handled correctly

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1325]
Currently, exceptions thrown during sending a parcel (``put_parcel``) or receiving is not properly propagated to the user code. This might lead to non obvious hangs in the user code and prohibits proper fault handling in the network layer.

**Comment by sithhell** [comment]
hmm, what if there are no more calls into the parcel handler after a erronous apply? I think the default should be to call terminate there as well.

**Comment by hkaiser** [comment]
Huh? I removed storing exception and call terminate by default now (see #1384)

**Comment by sithhell** [comment]
Ok, I am confused as the ticket says that apply should do nothing by default ... after looking throught the code of the PR, my question is resolved.
