### ISSUE TITLE
Warning on uninitialized member

### ISSUE THREAD

**Issue by oblitum** [STEllAR-GROUP/hpx#1376]
Clang trunk (3.7) is giving the following warning for any code that I try using HPX:

```
/opt/local/include/hpx/util/coroutine/detail/context_generic_context.hpp:188:32: 
    warning: field 'alloc_' is uninitialized when used here
      [-Wuninitialized]
              , stack_pointer_(alloc_.allocate(stack_size_))
                               ^
1 warning generated.
```

I've checked code at [line 188 of context_generic_context.hpp](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/util/coroutine/detail/context_generic_context.hpp#L188) and, even though it's not going to produce any effect (since the `allocate` member function doesn't use any state of its class for my build) it does look like a case of pre-c++11 rules where POD members being default-initialized (not present in the initializer list) are not initialized at all.

I got dozens of such warnings while building HPX (I'm on OS X using clang trunk), all of them pointing the same line, I didn't care but then I noticed it would show up anytime when including HPX headers.

I'm on 0.9.9, but I guess the issue still applies on master.

**Comment by hkaiser** [comment]
Do you have suggestions about how to fix this, could you submit a patch?

**Comment by oblitum** [comment]
@hkaiser My local fix was just to add a member initializer:

```diff
diff --git a/hpx/util/coroutine/detail/context_generic_context.hpp b/hpx/util/coroutine/detail/context_generic_context.hpp
index 306c53d..11c1e2e 100644
--- a/hpx/util/coroutine/detail/context_generic_context.hpp
+++ b/hpx/util/coroutine/detail/context_generic_context.hpp
@@ -181,6 +181,7 @@ namespace hpx { namespace util { namespace coroutines
             template <typename Functor>
             explicit fcontext_context_impl(Functor& cb, std::ptrdiff_t stack_size)
               : cb_(reinterpret_cast<intptr_t>(&cb))
+              , alloc_()
               , stack_size_(
                     (stack_size == -1) ?
                     alloc_.minimum_stacksize() : std::size_t(stack_size)
```

but as `stack_allocator`, the type for `alloc_`, may contain an array or not based on an `#ifdef`, I'm not sure it's correct to assume the array should be zero-initialized.

**Comment by oblitum** [comment]
@hkaiser notice that, this is not just a compatibility issue, gcc should just be missing a diagnostic for this.

**Comment by hkaiser** [comment]
@oblitum: please reopen if the patch does not really solve things, I'm not able to verify the fix.

**Comment by oblitum** [comment]
@hkaiser yeah that warning has gone... (but now I got a bunch of other ones by using master :unamused:)

**Comment by oblitum** [comment]
@hkaiser ah, nevermind, these new ones are showing up solely on `-Wall` compilations. The one of this issue was showing up always.
