### ISSUE TITLE
Move semantic checks shouldn't be based on ranges

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1388]
Our move semantics tests should check for a fixed number of copies instead of ranges for known compilers.

**Comment by K-ballo** [comment]
It was noted that the use of `void_guard` inhibits elision in MSVC.

**Comment by K-ballo** [comment]
Probably wise to wait until #1474 (Remove `serialize_as_future` and `invoke_when_ready`) happens

**Comment by hkaiser** [comment]
FWIW, #1474 has long been closed now.
