### ISSUE TITLE
Parallel algorithms relying on scan partitioner break for small number of elements

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1389]
This assertion fires: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/parallel/util/scan_partitioner.hpp#L54

**Comment by hkaiser** [comment]
This was fixed by merging #1391: Parallel Algorithms for scan partitioner for small number of elements

**Comment by sithhell** [comment]
The tests still fail occasionally.

**Comment by sithhell** [comment]
One example of a failing test is here:
http://hermione.cct.lsu.edu/builders/hpx_gcc_4_9_boost_1_56_debian_x86_64_release/builds/290/steps/run_regression_tests/logs/stdio

**Comment by sithhell** [comment]
http://hermione.cct.lsu.edu/builders/hpx_gcc_4_8_boost_1_53_debian_x86_64_release/builds/309/steps/run_regression_tests/logs/tests.regressions.parallel.scan_shortlength%20%280.48%20sec%29

**Comment by hkaiser** [comment]
I think that we can fix this by not using `std::initializer_list`. This is the only difference to other tests I can see.

**Comment by sithhell** [comment]
On 03/13/2015 03:40 PM, Hartmut Kaiser wrote:
> I think that we can fix this by not using |std::initializer_list|. This
> is the only difference to other tests I can see.

Shouldn't it work with |std::initilizer_list| as well?

**Comment by hkaiser** [comment]
If the compiler can handle it, sure.

**Comment by sithhell** [comment]
GCC 4.9 and 4.8 have `std::initializer_list`, as far as I can tell.

**Comment by hkaiser** [comment]
This has been fixed by ac229f45c63264cd6edab6765024da4f798a4024
