### ISSUE TITLE
Tests using the scan partitioner are broken on at least gcc 4.7 and intel compiler

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1398]
See buildbot for more detail:
http://hermione.cct.lsu.edu/builders/hpx_gcc_4_7_boost_1_51_debian_x86_64_release/builds/301/steps/run_unit_tests/logs/stdio
and
http://hermione.cct.lsu.edu/builders/hpx_intel_13_boost_1_54_debian_x86_64_release/builds/300/steps/run_unit_tests/logs/stdio

**Comment by hkaiser** [comment]
This was fixed by dc37df32d2faac3665f087d6cc06f8d11561cac8
