### ISSUE TITLE
hpx::util::unwrapped doesn't work with non-future types

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1400]
Making an `unwrapped` call in dataflow when one of the arguments isn't a future, we currently get a compile error.
Example:

```
void f(int i, int i) {}
void f2(int i, hpx::future<int> i) {}

// Fails:
hpx::lcos::local::dataflow(
    hpx::util::unwrapped(f), 8, hpx::make_ready_future(9)); 
// Succeeds:
hpx::lcos::local::dataflow(
    hpx::util::unwrapped(f), hpx::make_ready_future(8), hpx::make_ready_future(9)); 

// Succeeds:
hpx::lcos::local::dataflow(
    f2, 8, hpx::make_ready_future(9)); 
```

IMHO, all three examples above should work.

**Comment by AntonBikineev** [comment]
We just ran into this with Zahra. Would it be correct for non-future params to wrap them into futures underneath?

**Comment by hkaiser** [comment]
> We just ran into this with Zahra. Would it be correct for non-future params to just wrap them into futures with  make_ready_future  underneath?

I'd rather pass through non-future parameters unchanged, if possible.
