### ISSUE TITLE
Make std::tuple tuple-like for HPX

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1403]
This would enable seamless use of std::tuple with all HPX API functions which expect or return a hpx::util::tuple.

**Comment by sithhell** [comment]
markComment: false

**Comment by sithhell** [comment]
closeComment: false

**Comment by hkaiser** [comment]
@sithhell `closeComment: false` will not do anything; just attach the `pinned` label to the tickets you would like to keep open.
