### ISSUE TITLE
The Intel 13 compiler has failing unit tests

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1407]
The unit test that fails are:
 - [x] tests.unit.components.distributed.mpi.get_ptr
 - [x] tests.unit.components.distributed.tcp.get_ptr
 - [x] tests.unit.performance_counters.path_elements
 - [x] tests.unit.threads.distributed.mpi.thread_stacksize
 - [x] tests.unit.threads.distributed.tcp.thread_stacksize
 - [x] tests.unit.util.distributed.mpi.serialize_buffer
 - [x] tests.unit.util.distributed.tcp.serialize_buffer
 - [x] tests.unit.util.parse_affinity_options
 - [ ] tests.unit.parallel.uninitialized_copy
 - [ ] tests.unit.parallel.uninitialized_copyn
 - [ ] tests.unit.parallel.uninitialized_fill
 - [ ] tests.unit.parallel.uninitialized_filln

See here for example:
http://hermione.cct.lsu.edu/builders/hpx_intel_13_boost_1_54_debian_x86_64_release/builds/310/steps/run_unit_tests/logs/stdio

**Comment by sithhell** [comment]
Intel13 has been broken for some time now. Do we want to deprecate it?

**Comment by sithhell** [comment]
I think it is feasible to stop supporting it since all major HPC platforms have at least intel14 installed nowadays. The intel compiler suite version 13 was released 2012 (similar to gcc 4.4. which we stopped supporting a while back) and received its last update september 2014.

**Comment by hkaiser** [comment]
@sithhell Ok, let's drop it. We should start looking into Intel V16, though.

**Comment by sithhell** [comment]
On 02/25/2016 01:48 PM, Hartmut Kaiser wrote:
> @sithhell <https://github.com/sithhell> Ok, let's drop it. We should
> start looking into Intel V16, though.

Good. I agree wrt Intel V16!

**Comment by sithhell** [comment]
I think we can close this now as we don't support intel13 anymore.
