### ISSUE TITLE
Intel 15 fails to compile parallel algorithms that rely on the scan partitioner

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1408]
Tests that fail:
- [ ] scan_shortlength
- [ ] scan_different_inits
- [ ] generate

The compiliation of those tests has been disabled to not nuke machines that try to compile them. The effect of the compilation problem is total memory exhaustion leading to eventually crash the system.

**Comment by hkaiser** [comment]
This shows that it does compile the file just fine: http://hermione.cct.lsu.edu/builders/hpx_intel_15_boost_1_55_debian_x86_64_debug/builds/19/steps/build_regression_tests_errors/logs/stdio.

**Comment by sithhell** [comment]
Am 13.03.2015 13:24 schrieb "Hartmut Kaiser" <notifications@github.com>:
>
> This shows that it does compile the file just fine:
http://hermione.cct.lsu.edu/builders/hpx_intel_15_boost_1_55_debian_x86_64_debug/builds/19/steps/build_regression_tests_errors/logs/stdio
.

Because I disabled the test for that compiler in one of the commits I
tested.

**Comment by hkaiser** [comment]
Well, that's not too helpful :/

**Comment by sithhell** [comment]
the scan_different_inits test is failing to compile too.

**Comment by sithhell** [comment]
It's easy enough to re-enable them when trying to fix that issue. The problem is that if someone compiles these tests, the machine used to compile it will be completely nuked, that is running out of memory.
