### ISSUE TITLE
Inconsistent CMake option names

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1430]
#1429 raised the awareness about inconsistent cmake option names. We currently have three sets of different options:
 - `HPX_XXX`
 - `HPX_HAVE_XXX` 
 - `HPX_WITH_XXX`

The question is: Should those be unified? What should the unified name be? What do people expect?

**Comment by eschnett** [comment]
I expect `--enable-mpi-parcelport` (or `HPX_ENABLE_MPI_PARCELPORT`).

**Comment by hkaiser** [comment]
We agreed to use `HPX_WITH_...` for specifying what the user would like to enable and `HPX_HAVE_...` for the generated options. That is still a fine compromise, I believe. the only thing which should change are those `HPX_...` cmake options (like `HPX_PARCELPORT_MPI`).

**Comment by parsa** [comment]
If we're to follow the convention used for `configure` scripts we'd use `WITH` for library paths and `ENABLE` for features. People use that all the time and it's likely more intuitive.

**Comment by gentryx** [comment]
I prefer -DWITH_FOO=bar, but I'm fine with any of these.

A convention certainly would streamline things. Note that subtle differences (e.g. ENABLE for features or HAVE for generated options) are easily ignored by users or new developers.

**Comment by mcopik** [comment]
I would say that `HPX_HAVE...` specifies features and libraries existing in the environment and `HPX_WITH... `is used to list options enabled for compilation (default, demanded by user etc.)

For me, it's quite intuitive and similar to other libraries.

**Comment by hkaiser** [comment]
This has been fixed by merging #1461
