### ISSUE TITLE
Add strong scaling option to htts 

### ISSUE THREAD

**Issue by pagrubel** [STEllAR-GROUP/hpx#1436]

**Comment by hkaiser** [comment]
@pagrubel: could you elaborate on what you had in mind with this request, please?

**Comment by pagrubel** [comment]
This is already in timed_task_spawn.  Right now in hits_hpx the number of tasks are per core (weak scaling).
In timed_task_spawn there is a command line option for strong scaling (i.e. use the tasks as the total number of tasks divided by OS_threads)
There is an error check to make sure the number is equally divided.


On Mar 30, 2015, at 4:37 PM, Hartmut Kaiser <notifications@github.com<mailto:notifications@github.com>> wrote:


@pagrubel<https://github.com/pagrubel>: could you elaborate on what you had in mind with this request, please?

**Comment by hkaiser** [comment]
@brycelelbach: Bryce, are you planning to implement this? How involved is this?

**Comment by pagrubel** [comment]
We could close this as I've decided the use of timed_task_spawn will suffice for my needs
