### ISSUE TITLE
pkgconfig does not include compilation flags necessary for a compatible build

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/hpx#1441]
The new CMake system does not generate pkgconfig files with the all the necessary build flags.

If you selected a non-default memory allocator and are using GCC, the flags to weaken the allocator symbols will not be specified in pkgconfig, which will prevent symbol overloading from working properly and cause your externally built applications to use the system allocator.

If you build for the Xeon Phi, the pkgconfig file will not specify -mmic.

The -rdynamic flag is not passed. This flag tells the linker to export all symbols, not just the symbols used in the library. This is necessary to make dlopen calls function properly with HPX components.

The -fPIC flag is not passed in the components pkgconfig file; position independent code generation is necessary for components to successfully compile.

**Comment by sithhell** [comment]
> If you selected a non-default memory allocator and are using GCC, the flags to weaken the allocator symbols will not be specified in pkgconfig, which will prevent symbol overloading from working properly and cause your externally built applications to use the system allocator.

Those flags are actually not really necessary. It's perfectly fine to just link against the malloc implementation (or just LD_PRELOAD it). Checking with the documentation of tcmalloc or jemalloc, none of them even mention those flags. I think they should go entirely.

> If you build for the Xeon Phi, the pkgconfig file will not specify -mmic.

Indeed, that's a bug.

> The -rdynamic flag is not passed. This flag tells the linker to export all symbols, not just the symbols used in the library. This is necessary to make dlopen calls function properly with HPX components.

-rdynamic isn't passed in for cmake either and everything works jolly good. In fact, passing in -rdynamic unconditionally is problematic on some platforms (Cray and BGQ come to my mind here).

> The -fPIC flag is not passed in the components pkgconfig file; position independent code generation is necessary for components to successfully compile.

I am not sure if that should be considered a bug or that the build system using those pkgconfig files should handle. CMake does this correctly automatically for example, not sure about autotools or other systems.

**Comment by sithhell** [comment]
For XeonPhi builds with the MPI parcelport enabled, it also misses the necessary flags to link against the appropriate Intel MPI libraries.

**Comment by hkaiser** [comment]
@sithhell What's the status of this. Can we close it?

**Comment by msimberg** [comment]
@sithhell Is this still a problem?
