### ISSUE TITLE
Implement N4392: C++ Latches and Barriers

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1457]
See: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4392.pdf

**Comment by sithhell** [comment]
`latch` has been implemented by merging #1476.

**Comment by hkaiser** [comment]
It looks like that we can't implement barriers as specified by the Concurrency TS (recent version: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0159r0.html). The TS specifies a barrier as "a thread coordination mechanism that allow a set of participating threads to block until an operation is completed". A barrier relies on being (repeatedly) invoked by the same threads. In HPX this is not possible as (especially in the remote case) new threads are constantly created. For this reason the barrier functionality can only be approximated in HPX.
