### ISSUE TITLE
Make cmake configure step fail explicitly if compiler version is not supported

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1459]
Currently, cmake does not fail completely when gcc 4.4.x is used, it will still generate (a non-functional) set of makefiles. We should explicitly bail out for unsupported (too old) compilers.

**Comment by K-ballo** [comment]
> CMake Error at cmake/HPX_Message.cmake:43 (message):
>   ERROR: HPX needs support for C++11 range-based for-loop

**Comment by K-ballo** [comment]
The recently required C++11 features make GCC4.4 be rejected with a fatal error (lack of range-based for-loop)

**Comment by hkaiser** [comment]
Thanks - I forgot to mention, the problem happens with the V0.9.10 release.
