### ISSUE TITLE
Which malloc is actually used? or at least which one is HPX built with

### ISSUE THREAD

**Issue by pagrubel** [STEllAR-GROUP/hpx#1460]
While trying to build HPX for the Xeon Phi using TBBMALLOC I got confusing messages, which made me wonder what malloc HPX was actually built with. I think this would be a good information to include when invoking the --version flag.

Here is my cmake command (on hermione):

cmake -DCMAKE_INSTALL_PREFIX=~/build/hpx_buildmic_release       \
      -DCMAKE_BUILD_TYPE=Release                 \
      -DCMAKE_TOOLCHAIN_FILE=$HOME/hpx/cmake/toolchains/XeonPhi.cmake \
      -DBOOST_ROOT=~/boost/boost_1_55_0_mic     \
      -DHWLOC_ROOT=/opt/hwloc/1.7-k1om-release   \
      -DHPX_MALLOC=tbbmalloc                     \
      -DTBBMALLOC_ROOT=/opt/intel/tbb/   \
      -DHPX_THREAD_GUARD_PAGE=OFF                                    \
      -DHPX_BUILD_EXAMPLES=ON                                        \
      -DHPX_BUILD_TESTS=ON                                        \
      ~/hpx

These lines from the output confuse me:
-- Found TBBmalloc: /opt/intel/tbb/lib/mic/libtbbmalloc.so  
-- Using tbbmalloc allocator.
-- Could NOT find TBBmalloc (missing:  TBB_LIBRARY TBB_PROXY_LIBRARY TBB_INCLUDE_DIR) 

Complete output:

-- The CXX compiler identification is Intel 15.0.0.20150121
-- The C compiler identification is Intel 15.0.0.20150121
-- Check for working CXX compiler: /opt/intel/composer_xe_2015.2.164/bin/intel64/icpc
-- Check for working CXX compiler: /opt/intel/composer_xe_2015.2.164/bin/intel64/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /opt/intel/composer_xe_2015.2.164/bin/intel64/icc
-- Check for working C compiler: /opt/intel/composer_xe_2015.2.164/bin/intel64/icc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- The Fortran compiler identification is unknown
-- Fortran support is disabled
-- Native TLS is enabled.
-- Stack traces are enabled.
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   chrono
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
--   context
--   atomic
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Found TBBmalloc: /opt/intel/tbb/lib/mic/libtbbmalloc.so  
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_CFREE
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_CFREE - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_CFREE
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_CFREE - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_PVALLOC
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_PVALLOC - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_PVALLOC
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_PVALLOC - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_MALLOC
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_MALLOC - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_MALLOC
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_MALLOC - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_FREE
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_FREE - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_FREE
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_FREE - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_CALLOC
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_CALLOC - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_CALLOC
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_CALLOC - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_REALLOC
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_REALLOC - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_REALLOC
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_REALLOC - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_VALLOC
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_VALLOC - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_VALLOC
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_VALLOC - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_MEMALIGN
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_MEMALIGN - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_MEMALIGN
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_MEMALIGN - Success
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_POSIX_MEMALIGN
-- Performing Test HPX_WITH_CXX_FLAG_FNO_BUILTIN_POSIX_MEMALIGN - Success
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_POSIX_MEMALIGN
-- Performing Test HPX_WITH_C_FLAG_FNO_BUILTIN_POSIX_MEMALIGN - Success
-- Using tbbmalloc allocator.
-- Found Hwloc: /opt/hwloc/1.7-k1om-release/lib/libhwloc.so  
-- Compiling for Intel Xeon Phi devices
-- Performing Test HPX_WITH_CXX14
-- Performing Test HPX_WITH_CXX14 - Success
-- Performing Test HPX_WITH_CXX11_ALIAS_TEMPLATES - Success
-- Performing Test HPX_WITH_CXX11_AUTO - Success
-- Performing Test HPX_WITH_CXX11_CONSTEXPR - Success
-- Performing Test HPX_WITH_CXX11_DECLTYPE - Success
-- Performing Test HPX_WITH_CXX11_DEFAULTED_FUNCTIONS - Success
-- Performing Test HPX_WITH_CXX11_DELETED_FUNCTIONS - Success
-- Performing Test HPX_WITH_CXX11_EXPLICIT_CONVERSION_OPERATORS - Success
-- Performing Test HPX_WITH_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS - Success
-- Performing Test HPX_WITH_CXX11_INLINE_NAMESPACES - Success
-- Performing Test HPX_WITH_CXX11_LAMBDAS - Success
-- Performing Test HPX_WITH_CXX11_NOEXCEPT - Success
-- Performing Test HPX_WITH_CXX11_NULLPTR - Success
-- Performing Test HPX_WITH_CXX11_RANGE_BASED_FOR - Success
-- Performing Test HPX_WITH_CXX11_RVALUE_REFERENCES - Success
-- Performing Test HPX_WITH_CXX11_SCOPED_ENUMS - Success
-- Performing Test HPX_WITH_CXX11_STATIC_ASSERT - Success
-- Performing Test HPX_WITH_CXX11_VARIADIC_MACROS - Success
-- Performing Test HPX_WITH_CXX11_VARIADIC_TEMPLATES - Success
-- Performing Test HPX_WITH_CXX11_CHRONO - Success
-- Performing Test HPX_WITH_CXX11_STD_INITIALIZER_LIST - Success
-- Performing Test HPX_WITH_CXX11_IS_FINAL - Failed
-- Performing Test HPX_WITH_CXX11_IS_NULL_POINTER - Failed
-- Performing Test HPX_WITH_CXX11_UNIQUE_PTR - Success
-- Performing Test HPX_WITH_CXX11_TYPE_TRAITS - Success
-- Performing Test HPX_WITH_CXX14_CONSTEXPR - Failed
-- Performing Test HPX_WITH_CXX14_LAMBDAS - Failed
-- Performing Test HPX_WITH_CXX14_INTEGER_SEQUENCE - Failed
-- Performing Test HPX_WITH_CXX14_RESULT_OF_SFINAE - Failed
-- Performing Test HPX_WITH_CXX_FLAG_WALL
-- Performing Test HPX_WITH_CXX_FLAG_WALL - Success
-- Performing Test HPX_WITH_C_FLAG_WALL
-- Performing Test HPX_WITH_C_FLAG_WALL - Success
-- Performing Test HPX_WITH_Fortran_FLAG_WALL
-- Performing Test HPX_WITH_Fortran_FLAG_WALL - Success
-- Performing Test HPX_WITH_CXX_FLAG_WEXTRA
-- Performing Test HPX_WITH_CXX_FLAG_WEXTRA - Success
-- Performing Test HPX_WITH_C_FLAG_WEXTRA
-- Performing Test HPX_WITH_C_FLAG_WEXTRA - Success
-- Performing Test HPX_WITH_Fortran_FLAG_WEXTRA
-- Performing Test HPX_WITH_Fortran_FLAG_WEXTRA - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS - Failed
-- "-Wno-unused-local-typedefs" not available for language CXX.
-- Performing Test HPX_WITH_C_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HPX_WITH_C_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS - Failed
-- "-Wno-unused-local-typedefs" not available for language C.
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS - Failed
-- "-Wno-unused-local-typedefs" not available for language Fortran.
-- Performing Test HPX_WITH_CXX_FLAG_WNO_STRICT_ALIASING
-- Performing Test HPX_WITH_CXX_FLAG_WNO_STRICT_ALIASING - Success
-- Performing Test HPX_WITH_C_FLAG_WNO_STRICT_ALIASING
-- Performing Test HPX_WITH_C_FLAG_WNO_STRICT_ALIASING - Success
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_STRICT_ALIASING
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_STRICT_ALIASING - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SIGN_PROMO
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SIGN_PROMO - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_ATTRIBUTES
-- Performing Test HPX_WITH_CXX_FLAG_WNO_ATTRIBUTES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_CAST_ALIGN
-- Performing Test HPX_WITH_CXX_FLAG_WNO_CAST_ALIGN - Failed
-- "-Wno-cast-align" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_PARAMETER
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_PARAMETER - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_IGNORED_QUALIFIERS
-- Performing Test HPX_WITH_CXX_FLAG_WNO_IGNORED_QUALIFIERS - Failed
-- "-Wno-ignored-qualifiers" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WFORMAT_2
-- Performing Test HPX_WITH_CXX_FLAG_WFORMAT_2 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_FORMAT_NONLITERAL
-- Performing Test HPX_WITH_CXX_FLAG_WNO_FORMAT_NONLITERAL - Failed
-- "-Wno-format-nonliteral" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WINIT_SELF
-- Performing Test HPX_WITH_CXX_FLAG_WINIT_SELF - Success
-- Performing Test HPX_WITH_CXX_FLAG_WDOUBLE_PROMOTION
-- Performing Test HPX_WITH_CXX_FLAG_WDOUBLE_PROMOTION - Failed
-- "-Wdouble-promotion" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WCAST_QUAL
-- Performing Test HPX_WITH_CXX_FLAG_WCAST_QUAL - Success
-- Performing Test HPX_WITH_CXX_FLAG_WCAST_ALIGN
-- Performing Test HPX_WITH_CXX_FLAG_WCAST_ALIGN - Failed
-- "-Wcast-align" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_TRAMPOLINES
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_TRAMPOLINES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_PARENTHESES
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_PARENTHESES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_REORDER
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_REORDER - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_RETURN_TYPE
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_RETURN_TYPE - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SEQUENCE_POINT
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SEQUENCE_POINT - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_FORMAT
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_FORMAT - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_MISSING_BRACES
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_MISSING_BRACES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SIGN_COMPARE
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SIGN_COMPARE - Success
-- Performing Test HPX_WITH_CXX_FLAG_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HPX_WITH_CXX_FLAG_FDIAGNOSTICS_SHOW_OPTION - Failed
-- "-fdiagnostics-show-option" not available for language CXX.
-- Performing Test HPX_WITH_C_FLAG_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HPX_WITH_C_FLAG_FDIAGNOSTICS_SHOW_OPTION - Failed
-- "-fdiagnostics-show-option" not available for language C.
-- Performing Test HPX_WITH_Fortran_FLAG_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HPX_WITH_Fortran_FLAG_FDIAGNOSTICS_SHOW_OPTION - Failed
-- "-fdiagnostics-show-option" not available for language Fortran.
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_VLA
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_VLA - Success
-- Performing Test HPX_WITH_C_FLAG_WERROR_RETURN_TYPE
-- Performing Test HPX_WITH_C_FLAG_WERROR_RETURN_TYPE - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SYNC_NAND
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SYNC_NAND - Failed
-- "-Wno-sync-nand" not available for language CXX.
-- Performing Test HPX_WITH_C_FLAG_WNO_SYNC_NAND
-- Performing Test HPX_WITH_C_FLAG_WNO_SYNC_NAND - Failed
-- "-Wno-sync-nand" not available for language C.
-- Performing Test WITH_LINKER_FLAG_WL__Z_DEFS
-- Performing Test WITH_LINKER_FLAG_WL__Z_DEFS - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD1170
-- Performing Test HPX_WITH_CXX_FLAG_WD1170 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD858
-- Performing Test HPX_WITH_CXX_FLAG_WD858 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD1098
-- Performing Test HPX_WITH_CXX_FLAG_WD1098 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD488
-- Performing Test HPX_WITH_CXX_FLAG_WD488 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD2203
-- Performing Test HPX_WITH_CXX_FLAG_WD2203 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD2536
-- Performing Test HPX_WITH_CXX_FLAG_WD2536 - Success
-- Performing Test HPX_WITH_RDTSC - Success
-- Found Git: /usr/bin/git (found version "2.0.0") 
-- GIT commit is 17d772171dbf472f1b4a16394dd0f92391b562fe.
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -openmp  
-- Found unsuitable Qt version "" from NOTFOUND
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
-- Could NOT find OrangeFS (missing:  ORANGEFS_LIBRARY ORANGEFS_INCLUDE_DIR) 
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Could NOT find QThreads (missing:  QTHREADS_LIBRARY QTHREADS_INCLUDE_DIR) 
-- Could NOT find TBBmalloc (missing:  TBB_LIBRARY TBB_PROXY_LIBRARY TBB_INCLUDE_DIR) 
-- Could NOT find SWARM (missing:  SWARM_LIBRARY SWARM_INCLUDE_DIR) 

HPX will be installed to /home/pagrubel/build/hpx_buildmic_release

-- Configuring done
-- Generating done
-- Build files have been written to: /home/pagrubel/build/hpx_buildmic_release

**Comment by pagrubel** [comment]
OOPS the complete output is incorrect

**Comment by hkaiser** [comment]
The commit 285009f15d091e90108f524585cb01a7f7aff0fe add the requested output to `-v` and `--hpx:info`

**Comment by sithhell** [comment]
Can this be closed now?

**Comment by pagrubel** [comment]
yes
