### ISSUE TITLE
Move external/boost/endian into hpx/util

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1480]
Boost V1.58 has accepted Boost.Endian. In order to avoid naming conflicts we should move the endian library we use from `external/boost/endian` into `hpx/util`.

**Comment by sithhell** [comment]
Am 27.04.2015 3:29 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> Boost V1.58 has accepted Boost.Endian. In order to avoid naming conflicts
we should move the endian library we use from external/boost/endian into
hpx/util.

Would it make sense to update our external to the boost version and use it
instead?
