### ISSUE TITLE
Fix bad iterator comparison in MPI parcelport

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1490]
This commit removes obviously bad code which compares iterators from different containers: 0714bc41c86a3819cf97331799a956847e7f702c. The code requires proper fixing as it breaks MPI runs on WIndows (for debug builds).

**Comment by sithhell** [comment]
As mentioned in the comment of the said commit, I'm not able to spot the
cause of the bug. Could you please point me to it?

**Comment by hkaiser** [comment]
Thomas, all I know is that the comparison of the two iterators raises the error in the runtime library (it uses checked iterators in debug builds). Sorry, I can't say more at this point.

**Comment by hkaiser** [comment]
Thomas, all I know is that the comparison of the two iterators raises the error in the runtime library (it uses checked iterators in debug builds). Sorry, I can't say more at this point.

**Comment by sithhell** [comment]
`header_handle` is initialized here: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/plugins/parcelport/mpi/receiver.hpp#L48
or here: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/plugins/parcelport/mpi/receiver.hpp#L56
It comes from `receiver_.handles_header_`.
This iterator is then used again in the dtor of the `handle_header` class:
https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/plugins/parcelport/mpi/receiver.hpp#L77
https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/plugins/parcelport/mpi/receiver.hpp#L79
https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/plugins/parcelport/mpi/receiver.hpp#L84

It is not really obvious to me where there is bad code. If it was bad code, all three lines should be affected by that. I have no ways to further debug this issue. My point still stands, the commit removing the "bad" code should be reverted and a proper fix should be worked on. It looks like the problem at hand is more substantial and only manifests itself in the code that checks for the invariant, which means it already fulfilled it's purpose.

**Comment by K-ballo** [comment]
Tag `worksforme`? Why does that even exist?

**Comment by hkaiser** [comment]
LOL. It sure works for @sithhell as the gcc runtime library is not performing those iterator checks by default. @sithhell you might see it if you enable the iterator checking.

The error is caused by moving away the container into a new instance of the handle type. You also move the iterator. Now, the iterator still refers to the container you moved away from, while the check is performed against the container you moved to. This is not legal.

**Comment by sithhell** [comment]
Please read the source again. The container isn't moved. The container belongs to the surrounding class, which the object in question holds per reference.

**Comment by sithhell** [comment]
Maybe MSVC has a bug there? What does this code print:
http://melpon.org/wandbox/permlink/BlnANNkd3fdnboEY
?

**Comment by K-ballo** [comment]
This [line](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/plugins/parcelport/mpi/receiver.hpp#L63) moves an iterator, leaving it in an unspecified yet valid state. A default constructed iterator is a singular iterator, one that does not belong to any container. It's possible that this move leaves us with a singular iterator for the `handles_ == false` case. A singular iterator can only be assigned to or destroyed, anything else is undefined behavior (even comparing it to another singular iterator until very recently).

**Comment by sithhell** [comment]
@K-ballo, the move constructor actually doesn't move anything for exactly the reason to check for invariant.

**Comment by K-ballo** [comment]
Let's say that you do indeed want to copy iterators in a move constructor, then you end with several `handle_header` instances with the same iterator in them. When one (and only one) of them is destroyed, it will remove from the container the element that iterator points to, effectively invalidating all iterators pointing to it (its own copy as well as everyone else's). This destructor has to be the last one to run, or otherwise the moved-from instances will trigger undefined behavior while comparing an invalidated iterator.

@sithell: I couldn't find anything that would explicitly guarantee the destruction order, could you add comments indicating how that guarantee is achieved? That would help us diagnose the issue today, and move away from this brittle design in the future.

**Comment by sithhell** [comment]
On Tuesday, May 05, 2015 05:13:09 Agustín Bergé wrote:
> @sithell: I couldn't find anything that would explicitly guarantee the
> destruction order, could you add comments indicating how that guarantee is
> achieved? That would help us diagnose the issue today, and move away from
> this brittle design in the future.

After thinking about this a bit more, I guess the best way to solve this issue 
would be to just move the iterators properly and check the `if(!handles_)` 
invariant in a different manner. After going through the code endless times 
now, I think this check might also be subject to a race condition, but that's 
unrelated to the issue at hand. Nevertheless having a proper move constructor 
is probably the best solution here.

**Comment by sithhell** [comment]
#1674 should take care of this.

**Comment by sithhell** [comment]
That has been fixed by merging #1674.
