### ISSUE TITLE
add an "hpx_" prefix to libraries and components to avoid name conflicts

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#1493]

**Comment by hkaiser** [comment]
Allmost all of the work has been done on the branch fixing_1493. One test is still failing (see: https://circleci.com/gh/STEllAR-GROUP/hpx/346)

**Comment by biddisco** [comment]
I am not able to reproduce this error locally and I suspect that the -liostreams was somehow caused by a stale cache entry - though I'm not sure how this would happen if each build is done from a clean dir.

**Comment by hkaiser** [comment]
@biddisco do I understand correctly that this PR does actually work for you?

**Comment by biddisco** [comment]
yes, I'm just waiting for a full rebuild to complete and I started a couple of builds on hermione to see if they also produced the link error. I'll know for sure when they all complete.

**Comment by biddisco** [comment]
OK, I have reproduced the error (but on a different target than the one detected in the original error log). Im looking into it now.

**Comment by biddisco** [comment]
I've pushed a fix to fixing_1493 which I believe now resolves this. if circle ci gives an all clear, then this is good to go.

**Comment by hkaiser** [comment]
Thanks! Unfortunately now inspect is complaining about your file you added to that branch earlier: https://circle-artifacts.com/gh/STEllAR-GROUP/hpx/667/artifacts/0/tmp/circle-artifacts.WeCx8nK/hpx_inspect_report.html

**Comment by biddisco** [comment]
Fixed the remaining refs to iostreams and merged PR

**Comment by biddisco** [comment]
Just a heads up that this branch has been merged and it modifies HPX_SetupTarget.cmake so that libraries and components have “hpx_" prefixed to the name.

It does not affect the target name in cmake, so you can still say
target_link_libraries(myapp iostreams)
But the name of the library iostreams on disk changes to hpx_iostreams.
This will also affect custom components and libraries which users create – it should not affect cmake generated projects, but If you have non cmake generated projects which use hardcoded library names, these will break and will need to be adjusted.

For reasons of caution, it would be a good idea to wipe any libraries in your build dir so that you don’t inadvertently link to them when you really want the newer ones that are generated but with a different name.

JB

**Comment by hkaiser** [comment]
We should send a mail to hpx-users describing the breaking change. We should also update the whats_new.qbk to mention this breaking change. 

Thanks for your work on this!

**Comment by biddisco** [comment]
I did sent a warning message to the list, but I don’t see it in my mailbox. Did it not arrive?
