### ISSUE TITLE
hwloc configuration options are wrong for MIC

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1501]
The documentation for building HPX for the XeonPhi is outdated. The options to configure hwloc to build for the XeonPhi has changed from `--host=k1om` to `--host=x86_64-k1om-linux`.

**Comment by hkaiser** [comment]
Is this true for all versions of hwloc?

**Comment by sithhell** [comment]
That is something that needs to be investigated. Unfortunately, the documentation on that issue is very sparse.

**Comment by hkaiser** [comment]
As it looks like, this switch was required for a long time (see https://www.open-mpi.org/community/lists/hwloc-devel/2013/06/3809.php). This message was sent mid-2013 at which point they released V1.6. I'd suggest we require HWLOC V1.6 on the Phi and change the flag unconditionally.
