### ISSUE TITLE
Incorrect cpuid config tests

### ISSUE THREAD

**Issue by K-ballo** [STEllAR-GROUP/hpx#1537]
Since db4a72216c3a6e408af4a30d8abe421d942003ac, we do not execute our config tests anymore. This is causing all `cpuid` related config tests to return `TRUE`, as compilation always succeeds for them. This in turn causes `RDSTCP` to be always detected as supported, so we end up issuing a call to it for certain performance counters, which raises `SIGILL`.

We don't seem to have a documented rationale for disabling execution of config tests (@sithhell do you remember the motivation for that change?), but I think that at least for the `cpuid` related tests we would want to either execute them or fall back to `false` (for instance if cross-compiling). Our config tests infrastructure needs some changes in order to accommodate for that. Other config tests have to be checked to see they have not became useless/dangerous by disabling execution. I've looked at the `cxx` which are the ones I am familiarized with and those look fine.

Note this is currently stopping us from using the idle-rate counter on the old Sun machines.

**Comment by hkaiser** [comment]
I'd venture a guess and say that this change was accidental. @sithhell ?
