### ISSUE TITLE
Passing plain identifier inside HPX_DEFINE_PLAIN_ACTION_1

### ISSUE THREAD

**Issue by AntonBikineev** [STEllAR-GROUP/hpx#1550]
`HPX_DEFINE_PLAIN_ACTION_1` and `HPX_DEFINE_PLAIN_DIRECT_ACTION_1` pass plain "name" as an identifier for action name, which may cause class redefinition.

It might be reasonable to pass `BOOST_PP_CAT(func, _action)` like it's done for `HPX_PLAIN_ACTION` or just to remove these macros.

**Comment by K-ballo** [comment]
Introduced by https://github.com/STEllAR-GROUP/hpx/commit/eb93bb0de108a07da6c656090d91a2428ea8e556

**Comment by hkaiser** [comment]
Tis was fixed by 2bdf6a58fa4c10d404663f47aafd2f523808a52f

**Comment by K-ballo** [comment]
That commit looks like a functional change. Does it require documentation changes to follow? What about announcing the breakage on the mailing list? Where are the basic unit tests to catch this kind of bug?

This kind of change should have gone through a pull request.

**Comment by AntonBikineev** [comment]
@K-ballo I don't think it's functional, because it doesn't break usage of macro and any existing code. Documentation defines it exactly as it is now. Sorry for committing directly to master.

**Comment by K-ballo** [comment]
Whether the change breaks out-of-tree builds depends only on what's documented. The current documentation for [`HPX_DEFINE_PLAIN_ACTION`](http://stellar-group.github.io/hpx/docs/html/hpx.html#HPX_DEFINE_PLAIN_ACTION) depicts it as a variadic macro. It looks suspiciously underdocumented. Do we want it to diverge from `HPX_PLAIN_ACTION` and `HPX_REGISTER_ACTION`? Do we want it to diverge from `HPX_DEFINE_COMPONENT_ACTION`?

**Comment by hkaiser** [comment]
k

**Comment by hkaiser** [comment]
@K-ballo you're probably right, we should leave it as an variadic macro and try to implement the one argument version analogously to the existing macros. Let's move this to a PR as well.

**Comment by hkaiser** [comment]
A proper fix has been added to the branch [fixing_1550](https://github.com/STEllAR-GROUP/hpx/tree/fixing_1550).

**Comment by hkaiser** [comment]
Fixed by merging #1553
