### ISSUE TITLE
Leftover HPX_REGISTER_ACTION_DECLARATION_2

### ISSUE THREAD

**Issue by AntonBikineev** [STEllAR-GROUP/hpx#1560]
After moving action serialization to new library we don't need to have this macro anymore.
https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/actions/basic_action.hpp#L504-L505

**Comment by hkaiser** [comment]
What about `HPX_REGISTER_ACTION_DECLARATION_`, `HPX_REGISTER_ACTION_DECLARATION_1` and possibly others?

**Comment by hkaiser** [comment]
The actual question is: should we completely remove the two-argument version of `HPX_REGISTER_ACTION_DECLARATION`? This would be a breaking change and would require modification of a lot of code out there.

**Comment by sithhell** [comment]
I actually like the binary version. It creates a nice symmetry between the
declaration and definition, even though the name is not used when the macro
is expanded, it serves as a nice documentation.

**Comment by hkaiser** [comment]
I'll close this for now as the consensus seems to be to leave the macro in place. Please reopen if there are concerns.
