### ISSUE TITLE
CMake fails when CMAKE_BINARY_DIR contains '+'.

### ISSUE THREAD

**Issue by ibbles** [STEllAR-GROUP/hpx#1590]
Getting the following error message:

```
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
CMake Error at cmake/HPX_GeneratePackage.cmake:56 (if):
  if given arguments:

    "(" "NOT" "dir" "MATCHES" "^/home/ibbles/mirrored/programmering/others/c++/hpx/hpx_0.9.10_build.*" ")" "AND" "(" "NOT" "dir" "MATCHES" "^/home/ibbles/mirrored/programmering/others/c++/hpx/hpx_0.9.10_repo.*" ")"

  Regular expression
  "^/home/ibbles/mirrored/programmering/others/c++/hpx/hpx_0.9.10_repo.*"
  cannot compile
Call Stack (most recent call first):
  CMakeLists.txt:1350 (include)


-- Configuring incomplete, errors occurred!
```

Renaming the folder 'c++' to 'cpp' will let CMake run successfully.

**Comment by hkaiser** [comment]
That's a bummer. I wouldn't even know how to fix this at this point. But I'm no cmake guru to begin with...

**Comment by sithhell** [comment]
Is this a cmake problem or a problem on our side? Do other projects work
living under the `c++` directory using cmake?

**Comment by biddisco** [comment]
The problem is that the CMAKE_BINARY_DIR is used as the match in a regex and as it contains a "++" cmake (correctly) thinks that this is part of the regex control sequence. Applying a string replace of "++" with "\\+\\+" before the regex test fixes it. I am applying a patch direct to the master branch as the fix is small addition to the cmake script.
If the develpoer is working on the 0.9.10 branch (as his/her path indicates), then the commit 4b4a1e2d903ac8824fc2fd1e6a9976218affc149  can be cherry picked to solve the immediate problem

**Comment by hkaiser** [comment]
> The problem is that the CMAKE_BINARY_DIR is used as the match in a regex and as it contains a "++" cmake (correctly) thinks that this is part of the regex control sequence. Applying a string replace of "++" with "\+\+" before the regex test fixes it. I am applying a patch direct to the master branch as the fix is small addition to the cmake script.

Wouldn't other special regex characters cause the same issues?

**Comment by biddisco** [comment]
> Wouldn't other special regex characters cause the same issues?

Yes, the '.' and '$' are most likely to be encountered in path names. The '.' will match itself and if a problem is reported with another char, we can look again at a more general fix.

excerpt from cmake docs 
^         Matches at beginning of input
$         Matches at end of input
.         Matches any single character
[ ]       Matches any character(s) inside the brackets
[^ ]      Matches any character(s) not inside the brackets
 -        Inside brackets, specifies an inclusive range ...
*         Matches preceding pattern zero or more times
+         Matches preceding pattern one or more times
?         Matches preceding pattern zero or once only
|         Matches a pattern on either side of the |
()        Saves a matched subexpression ...

**Comment by hkaiser** [comment]
We should probably create a ticket for this. While you nicely 'unbroke' the users code, your patch has not really 'fixed' the issue.

**Comment by biddisco** [comment]
I'll fix it properly when I have a spare moment.
