### ISSUE TITLE
Error (typo) in the docs

### ISSUE THREAD

**Issue by ilyapopov** [STEllAR-GROUP/hpx#1592]
In the documentation here http://stellar.cct.lsu.edu/files/hpx-0.9.10/html/hpx/manual/build_system/building_hpx/cmake_variables.html in the section "Additional Tools and Libraries", the links to NACL and PAPI are swapped.

**Comment by hkaiser** [comment]
This will be fixed [here}(http://stellar-group.github.io/hpx/docs/html/hpx/manual/build_system/building_hpx/cmake_variables.html#hpx.manual.build_system.building_hpx.cmake_variables.cmake_additional_tools) after the doc builder has run.

Thanks!
