### ISSUE TITLE
hpx cmake not working when run as a subproject

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#1617]
if hpx is cloned into a subdirectory and then used with cmake code as follows
```
project(x)
...
add_subdir(hpx)
```
then the cmake configuration step fails as some vars use variables such as CMAKE_SOURCE_DIR which generate paths relative to the project x root and not the hpx subdirectory project root.

Some trivial cmake fixes can solve the initial problem, but some more work might be required to ensure install rules function as expected.

**Comment by hkaiser** [comment]
What should be used instead of `CMAKE_SOURCE_DIR` to make this work as expected?

**Comment by biddisco** [comment]
if you have project(A) and inside a subdirectory Project(B), then CMAKE_SOURCE_DIR is relative to A, to be relative to B, you want PROJECT_SOURCE_DIR (the nearest project() statement), or even hpx_SOURCE_DIR, it's usually ok to use CMAKE_CURRENT_SOURCE_DIR. In hpx there are a few uses before the project(hpx). I've already fixed this on my branch, but I'm also adjusting a couple of things and doing some more tests.

**Comment by hkaiser** [comment]
@biddisco could you submit that separately as a PR? It will become more and more difficult to review your work once its finished if it's intermingled with a bunch of unrelated changes.

**Comment by biddisco** [comment]
I'll do a PR when I'm done with it. I anted to check the install rules work correctly. The "also adjusting a couple of things and doing some more tests" is exactly that. I'm back from a short vacation tomorrow so will resume work properly.

**Comment by biddisco** [comment]
clicked the close instead of comment button. oops.

**Comment by hkaiser** [comment]
This has been addressed by merging #1653
