### ISSUE TITLE
Lifetime issue

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1624]
The testcase here:
https://gist.github.com/sithhell/c0b639f86730a392555f
fails due to some lifetime issues. The problem occurs with one locality and one thread.

**Comment by sithhell** [comment]
The component gets destroyed on line 183.

**Comment by sithhell** [comment]
The problem with that code is the call to `this->get_gid()` here:
https://gist.github.com/sithhell/c0b639f86730a392555f#file-send_gid_keep_component-cpp-L98
which returns a unmanaged gid, which doesn't keep the component alive.
In the case of this simple testcase, the easiest fix would be to do the registration inside of the `Viewer` client directly. Otherwise, you need to explicitly turn the unmanaged gid into a managed gid by calling incref.

@koonschi, this fix your issue?

**Comment by koonschi** [comment]
I'm not sure I understand. How would I do the registration in the viewer
client directly? The server::viewer class has to exist as a component
because it will later on receive remote procedure calls from other classes.
How do I know if a gid is managed?

2015-06-22 20:51 GMT+02:00 Thomas Heller <notifications@github.com>:

**Comment by hkaiser** [comment]
My suggestion is to remove the function `get_gid()` from the component base classes. It should be replaced by 2 new functions `get_id()` and `get_unmanaged_id()`. 

This solves your issue by making the type of the returned id explicit and gets rid of the misnomer of calling a function `get_gid`, whereas it returns an id. This would be an interface breaking change, but it would improve the consistency and usability of the exposed API.

**Comment by hkaiser** [comment]
@koonschi does #1626 solve your issue?

**Comment by koonschi** [comment]
Sorry for the late response, this does solve my issue. Many thanks.

2015-06-25 18:35 GMT+02:00 Hartmut Kaiser <notifications@github.com>:

**Comment by hkaiser** [comment]
That was fixed by merging #1626
