### ISSUE TITLE
Inspect trailing whitespace checker problem

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1629]
The trailing whitespace checker of the inspect tool does not flag empty line with whitespace only as problems.

**Comment by hkaiser** [comment]
@Bcorde5 This is something you might want to look into

**Comment by Bcorde5** [comment]
Do you remember which file was used to discover this error?

**Comment by hkaiser** [comment]
> Do you want the checker to detect text files as well?

Would be nice to check all files in our repo for this.

**Comment by hkaiser** [comment]
This has been fixed by merging #1630
