### ISSUE TITLE
hpx::partitioned_vector is not serializable

### ISSUE THREAD

**Issue by XML4ever** [STEllAR-GROUP/hpx#1645]
hpx::vector is not serializable despite being meant to.
Example: http://pastebin.com/1FytwhNA

**Comment by hkaiser** [comment]
The actual question is: 'should it be serializable'? I'm open to suggestions here.

**Comment by TheConstructor** [comment]
It would make handling vectors easier as you could use it as argument to actions. After all a distributed storage is usually created to be used from multiple locations.

**Comment by hkaiser** [comment]
> It would make handling vectors easier as you could use it as argument to actions. After all a distributed storage is usually created to be used from multiple locations.

Sure, but all you need is to register the vector using a unique name and send that name over the wire. This allows to access the distributed data from there as well:

    /////////////
    // node 1:
    /////////////
    partitioned_vector v(...);
    v.register_as("some_unique_name");

    // send "some_unique_name" to node 2 here...

    /////////////
    // node2
    /////////////
    std::string name;

    // receive the name from node1 here...
    name = ...;

    // establish a connection to the distributed data
    partitioned_vector v;
    v.connect_to(name);

**Comment by TheConstructor** [comment]
What about type-safety? Will `connect_to` refuse to connect to a differently typed vector?

**Comment by hkaiser** [comment]
> What about type-safety? Will  connect_to  refuse to connect to a differently typed vector?

No :/ You have to be careful to maintain consistency yourself.

**Comment by msimberg** [comment]
@hkaiser Can this be closed now that #2762 is closed?
