### ISSUE TITLE
1d_stencil codes all have wrong factor

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/hpx#1656]
All the 1d_stencil codes have a line that looks like this:
``` return middle + (k * dt/dx * dx) * (left - 2*middle + right); ```
The code should look like this:
``` return middle + (k * dt/(dx * dx)) * (left - 2*middle + right); ```

Because the example codes all have dx set to 1, fixing the
expressions won't make any difference for output. However,
if dx is set to any other value the results will be wrong.

**Comment by Titzi90** [comment]
You are absolutely right
