### ISSUE TITLE
Inspect tool found incorrect endline whitespace

### ISSUE THREAD

**Issue by dcbdan** [STEllAR-GROUP/hpx#1664]
The Inspect tool flagged endline whitespaces in tests/unit/parallel/algorithms/adjacentdifference.cpp at lines 42, 101, 185, 239 from pull request #1659 but no whitespace was found at or near those lines.

**Comment by K-ballo** [comment]
The offending lines are actually 54, 124, 227, 294. Seems inspect is getting confused about line numbers.

**Comment by Bcorde5** [comment]
So far, what it looks like is that the inspect tool doesn't consider empty lines as lines, so there might be 12 lines ahead of line 54 that are empty, so the tool does not count them.  I will do more tests, but I believe if I can get the tool to detect empty lines, it should work like a charm.

**Comment by hkaiser** [comment]
Other inspector sub-tools do report the correct line numbers. It has to be an issue with the new end-of-line-whitespace detector.

**Comment by Bcorde5** [comment]
My mistake, I meant just the whitespace detector, not the entirety.
