### ISSUE TITLE
Add timer counters for tfunc_total and exec_total 

### ISSUE THREAD

**Issue by pagrubel** [STEllAR-GROUP/hpx#1688]
This timers might be useful by themselves and are the factors used to compute idle rate

**Comment by hkaiser** [comment]
@pagrubel Any ideas how to call those counters?

**Comment by pagrubel** [comment]
so tfunc is total execution time  and exec_times the computation time
tfunc  /threadss/time/functions   exec/threads/time/function_computations

I don't know what do you think?

**Comment by pagrubel** [comment]
While you are at it I still don't understand how that assert works correctly it seems it should be the opposite since tfunc_total should be larger than exec_total. tfunk includes overheads. Am I thinking wrong???

**Comment by hkaiser** [comment]
The assert is correct (see https://github.com/STEllAR-GROUP/hpx/blob/master/src/runtime/threads/detail/thread_pool.cpp#L758):
```
HPX_ASSERT(tfunc_time > exec_time);
```
it makes sure that `tfunc_time` is always larger than `exec_time`. One reason for this to fail would be for the two to be equal, but this is highly unlikely for any clock with reasonable resolution. Otherwise its a bug somewhere.

**Comment by biddisco** [comment]
I pushed a ">=" fix for the case when the times are the same - which seems to happen to me, possibly because the counter has not yet registered any real 'work' when I query it on a new node.

**Comment by pagrubel** [comment]
Guess i was thinking backwards about this

**Comment by hkaiser** [comment]
@pagrubel pls see #1694. This adds two new counter:

- `/threads/time/cumulative`: returns the overall time spent executing HPX threads (`exec_time`)
- `/threads/time/cumulative-overheads`: return overall time incurred by thread execution overheads (`tfunc_time - exec_time`)

**Comment by pagrubel** [comment]
These counters should be in seconds since they are cumulative time for all threads
