### ISSUE TITLE
Use after move of thread_init_data

### ISSUE THREAD

**Issue by AntonBikineev** [STEllAR-GROUP/hpx#1730]
Here https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/detail/create_thread.hpp#L88 the data is used after being moved from here https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/policies/thread_queue.hpp#L756

Just need to save num_os_thread into temporary var.

**Comment by hkaiser** [comment]
Excellent catch!
