### ISSUE TITLE
Error in AGAS

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1752]
I am getting an internal error in the AGAS server when running Octo-Tiger on 128 SuperMIC nodes.

"{what}: primary_namespace::resolve_free_list, failed to resolve gid, gid({0000003c00000001, 0000000002dc13f6}): HPX(internal_server_error)"

The full error output is here:

https://gist.github.com/dmarce1/b25f80106be451972158

This was with the most recent master version of HPX (at least, as of yesterday), Intel 15, MVAPICH2, and boost 1.59, GCC 4.9 headers, tbbmalloc

I will post a version of the code that does not have external library dependencies and which reproduces the error later today. 

Could  this have anything to do with setting the hpx.parcel.max_connections or hpx.parcel.max_connections_per_locality too low?

**Comment by sithhell** [comment]
> Could this have anything to do with setting the hpx.parcel.max_connections or hpx.parcel.max_connections_per_locality too low?

It is very unlikely that this leads to that error. The only thing that might happen is that your program is getting slower when those numbers aren't high enough. A good indicator for that are the parcelport cache performance counters.

**Comment by dmarce1** [comment]
This octotiger commit: https://github.com/dmarce1/octotiger/commit/f43a020fd3e6f0562ea316a18ee5ceadf3cf43cc reproduces the error about 1/2 to 2/3's of the time when run on SuperMIC with 100 nodes. When it happens, the error occurs during oct-tree formation, before the fluid evolution starts.

I have also been getting random freeze ups when the code does run. I have replaced future::get() calls with a trap (octotiger file ./src/future.hpp) that prints a message when a future does not return after 30 seconds (they all should in this case) - I've tested the trap and it works but of course when I run octotiger with traps enabled - the freeze ups do not happen. I'm unsure as to how to tell which future the code is freezing on.

**Comment by dmarce1** [comment]
Now when I run with check-pointing enabled (this commit https://github.com/dmarce1/octotiger/commit/d211bab6fb98e550ff18aa4b686484575d84a066) on 100 nodes I get a slightly different parcelport error, 

 negative entry in reference count table, raw({0000004700000001, 0000000000b013ec}), refcount(-1073741824): HPX(invalid_data)


gist: https://gist.github.com/dmarce1/bb074097594fdc6b86bb

**Comment by dmarce1** [comment]
....and here (same interactive session and executable as last post) - a different error, after grid formation and initial checkpointing,  just as the fluid evolution starts up - hpx is causing a seg fault in MPI_Test:

https://gist.github.com/dmarce1/ac22dbf4d651b1764ec2

**Comment by sithhell** [comment]
I am able to "run" your code now, however, it hangs during `node_server::timestep_driver`.

**Comment by dmarce1** [comment]
I think I *may* know what has been causing my code some problems. The implementation of "channel" I am using:
https://github.com/dmarce1/octotiger/blob/d211bab6fb98e550ff18aa4b686484575d84a066/src/channel.hpp
has a potential bug in it. The way I'm using it, calling "set_value" can cause the promise to be destroyed before the call to "set_value" completes. (set_value causes get() to return on the waiting thread, which then immediately destroys and replaces the promise) Apparently the standard does not allow this usage, I'm not sure if it applies to HPX or not. I'll fix it either way.

**Comment by sithhell** [comment]
I have a fixed version of your channel relying on hpx::lcos::local::receive_buffer. I will create a PR along with my other fixes to octotiger later today.

On a related note, I could reproduce the MPI_Test segfaults. I am not sure why they occur, however, they can be silenced once the file operations in node_server::save are commented out. Still investigating...

**Comment by sithhell** [comment]
Please see https://github.com/dmarce1/octotiger/pull/1 for my fixes.
