### ISSUE TITLE
 assertion 'action_.get()' failed: HPX(assertion_failure) when running Octotiger with  pull request 1786

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1790]
I'm getting an assertion failure when running the merged pull request of Octotiger, https://github.com/dmarce1/octotiger/commit/89201c83ea44ec09b87081297f4efe05c3d90cb2 using the fixing_1008 branch of HPX

The full output is here: https://gist.github.com/dmarce1/b665632ad0ab1939ebb6

This is with 64 nodes on SuperMIC.

I also continue to get random freeze ups.

**Comment by hkaiser** [comment]
@sithhell Why do we need that assert ([parcel.hpp:220](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/parcelset/parcel.hpp#L220))?

**Comment by sithhell** [comment]
While merging #1792 is probably getting rid of that firing assert, I believe that there is a more fundamental underlying error here. Please open a new issue with an updated problem description if you run into new failures.
