### ISSUE TITLE
Access Violation when exiting hello_world

### ISSUE THREAD

**Issue by ericLemanissier** [STEllAR-GROUP/hpx#1802]
I am facing an Access Violation error when exiting the hello_world example. It happens when several localities are run, and is reproducible for (nearly) all the unit tests involving distributed.tcp
I am using boost 1.58, and MinGW compiler ( https://github.com/STEllAR-GROUP/hpx/pull/1773 )
post mortem using i686-5.1.0-posix-dwarf-rt_v4-rev0 : https://gist.github.com/ericLemanissier/01e93763f678f839a0fc
post mortem using x86_64-5.1.0-posix-seh-rt_v4-rev0 : https://gist.github.com/ericLemanissier/15b176518c202a5498d3

I don't know if it is of any use, but I noticed the access violation seems to always be writing at address 0000000000000024 when compiling x86_64, and 0000000000000014 in i686

**Comment by hkaiser** [comment]
I have seen this kind of error on and off on Windows for years but have never been able to pinpoint it. As far as I remember, it is caused by a race during ASIO termination. We somehow perform this in a wrong sequence.

**Comment by ericLemanissier** [comment]
Could it be linked to https://sourceforge.net/p/mingw-w64/bugs/527/# ?

**Comment by hkaiser** [comment]
This could be related to #866
