### ISSUE TITLE
Spinlock no longer movable and deletes operator '=', breaks MiniGhost

### ISSUE THREAD

**Issue by Syntaf** [STEllAR-GROUP/hpx#1806]
While looking through the ported MiniGhost app, I began updating the code and fixing errors caused by old API calls that were either removed or changed. I've reached a point however that I don't know how to get past, in MiniGhost [global_sum.hpp l39](https://github.com/STEllAR-GROUP/miniapps/blob/master/MiniGhost/src/global_sum.hpp#L39) the code block reads:

```
if(this != &other) {
    mtx_        = std::move(other.mtx_);           // breaking change
    value_      = std::move(other.value_);
    generation_ = other.generation_;
    gate_       = std::move(other.gate_);
}
return *this;
```

In this context, `mtx_` is a `hpx::lcos::local::spinlock`. Previously spinlock was *movable* but not copyable [here](https://github.com/STEllAR-GROUP/hpx/commit/1a9ecfe20f60f5d3a63f25e266767d9322700247#diff-256968806cb9d5b51de83a246dc0e4a4L48) and also implemented the operator *=*. A commit on may 19th changed spinlock significantly, breaking MiniGhost. The the new version of spinlock, `operator=` no longer eixsts and it not movable at all [source](https://github.com/STEllAR-GROUP/hpx/commit/1a9ecfe20f60f5d3a63f25e266767d9322700247#diff-256968806cb9d5b51de83a246dc0e4a4L128)

To fix MiniGhost, how would I now perform the operation on line 39? Is it possible to do this anymore?

**Comment by K-ballo** [comment]
Simply don't move the mutex, it does not make any sense to move synchronization primitives. Depending on the application, you might also need to assert that the mutex is not locked during a move, or enforce that it is.

**Comment by hkaiser** [comment]
@Syntaf This is an issue related to the MiniGhost example. Could you please create a ticket and/or PR there? I'll go ahead and close the ticket here.
