### ISSUE TITLE
seg fault in AGAS

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1815]
I got a seg fault in agas running Octotiger. 

Here is the program output : 
https://gist.github.com/dmarce1/04e1ef7b722d4b1a117e

This is using the merged pull request from Thomas version of Octotiger, and the commit of HPX as of Thursday morning, cd5490fcda3db6eadb2c2e5bf7a547796661fff7.

**Comment by hkaiser** [comment]
@dmarce1 You don't need the commit from Thomas anymore as the slowdown problem should have been solved (at least massively relaxed) on master (as of b6385e04786778b85af947f9707343ea2dc8bb84 or later).

**Comment by hkaiser** [comment]
> @dmarce1 You don't need the commit from Thomas anymore as the slowdown problem should have been solved (at least massively relaxed) on master (as of b6385e04786778b85af947f9707343ea2dc8bb84 or later).

Well, actually, make that 92606587212dad97ec7b327e32b41d5f2effc9ba or later.
