### ISSUE TITLE
Unable to compile Octotiger using HPX and Intel MPI on SuperMIC

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1881]
I am getting linker errors when attempting to compile OctoTiger on SuperMIC using Intel MPI.

The HPX version is the master as of about an hour ago.
The octotiger version is the latest one, https://github.com/dmarce1/octotiger

I am using Intel15 with Intel MPI.

I get the following errors:
https://gist.github.com/dmarce1/bd78e47b4798f9ecd532

Output of cmake for HPX:
https://gist.github.com/dmarce1/300e23ec3f83dc6995db

CMakeOutput.log for both HPX and octotiger
https://drive.google.com/file/d/0BwEcPGZ9k2kmc1h1N0NkenRGU2s/view

**Comment by hkaiser** [comment]
@dmarce1: Please give us the cmake logs as well.

**Comment by dmarce1** [comment]
Added logs to original post.

**Comment by K-ballo** [comment]
Looks like you pulled from `master` fairly recently but did not rebuild HPX. Could that be the case?

**Comment by dmarce1** [comment]
I'm pretty sure it was rebuilt - to verify this, since the last comment I have deleted the HPX installation, cloned from the repository, rebuilt and reinstalled - and gotten the same results.

**Comment by K-ballo** [comment]
All those linker errors you are getting mention either `function` or ` unique_function`, which where modified fairly recently. As a consequence of some of those changes, their mangled name is now different than what it used to be. That means that if you were to try to link against an older build or version nothing would be found under the new names, and the errors you would be seeing are exactly the ones you are getting. It could still be just a coincidence, or something else completely unrelated, but are you sure that the linker is using the freshly built binaries? Could it be attempting to link against some older binaries installed in the system instead?

**Comment by parsa** [comment]
@dmarce1 do a `make VERBOSE=1` and you'll probably see this Octotiger build is HPX binaries other than the one you specified. If this was the case then try dmarce1/octotiger#2 and that should take care of the problem.

**Comment by dmarce1** [comment]
OK, I've got it working now. I was using the 'Release' version on octotiger but the 'Debug' version of HPX.
