### ISSUE TITLE
Accessing component from locality where it was not created segfaults

### ISSUE THREAD

**Issue by ltroska** [STEllAR-GROUP/hpx#1898]
The following minimal example http://pastebin.com/RmNccZX6 segfaults if using >= 2 localities on v0.9.11 release.
Output when using hpxrun.py -l  2 ./a.out
> num locs 3
invoked get_data  on 0 getting size 4
applying from 0 on {0000000200000000, 0000000000000000}
applying from 0 on {0000000300000000, 0000000000000000}
received on 1: 
Process 0 failed with an unexpected error code of -11 (expected 0)
Process 1 failed with an unexpected error code of -15 (expected 0)

running it individually I get on locality 0:
> num locs 2
invoked get_data  on 0 getting size 4 
applying from 0 on {0000000200000000, 0000000000000000}
 received on 1:
 Segmentation fault

**Comment by hkaiser** [comment]
Initial investigation shows that this test reveals two issues:

- [ ] `struct cell {}` is missing a serialization function, the code should not compile, but does (@AntonBikineev could you please look into this?)
- [ ] future<id_type> does not always perform proper id-splitting when being serialized (this has been addressed by #1899)
