### ISSUE TITLE
Two possible issues with std::list serialization

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1900]
I was tracking down a bug in Octotiger related to serialization of std::list.  When I replaced my std::lists with std::vectors, the problem went away, and I figured the std::lists being passed to remote localities were somehow losing elements.

1) I noticed that line 22 in the list serialization:
https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/serialization/list.hpp
would cause a bug if the argument "ls" is not already an empty list.

2) I figured out 1) was not  causing the error with my program -  turns out out hpx/runtime/serialization/list.hpp wasn't being included in the compile. I can't figure out how list was getting serialized without including the list.hpp header, but when I included the proper header the bug was fixed. I wasn't including the boost::serialization version anywhere in my source. Is the boost version of std::list serialization somewhere in the hpx headers, or is it possible the std::list was being automatically converted to another container improperly?

**Comment by hkaiser** [comment]
@AntonBikineev is that something you can answer?

**Comment by hkaiser** [comment]
@dmarce1 The problem 1) you listed is a genuine bug. I'll fix this asap.

**Comment by hkaiser** [comment]
Issue 1) has been fixed by 9d604e4de143f592a84ce86081218750de9e24a8 (see #1904)
Issue 2) will be fixed by merging #1901
