### ISSUE TITLE
Immediate crash when running hpx/octotiger with _GLIBCXX_DEBUG defined.

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1902]
I have built Boost, HPX, and Octo-tiger all in debug mode and with the flag "-D_GLIBCXX_DEBUG". It crashes immediately, even with one thread on one core. 

The stack trace is here: 
https://gist.github.com/dmarce1/5cb302574b90c239fc0d

The particular version of octotiger is here: https://github.com/dmarce1/octotiger/commit/03ef5bebd1cd362f25672cf73b19702795575c1f

**Comment by hkaiser** [comment]
Are you sure that you linked with the correct (debug) libstdc version? Using this compilation flag changes the ABI of the standard library, so using the 'normal' version will not work.

**Comment by dmarce1** [comment]
That's probably it. I will check and reopen if that is not the case.
