### ISSUE TITLE
When running octotiger, I get: assertion '(*new_gids_)[gid].size() == 1' failed: HPX(assertion_failure)

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1903]
When running octotiger, I get: assertion '(*new_gids_)[gid].size() == 1' failed: HPX(assertion_failure), from line 18 of hpx/src/runtime/serialization/output_archive.cpp.

The full output is here: https://gist.github.com/dmarce1/cd3d837b592fbbd54363

The is with 64 nodes on SuperMIC, using the latest commit of HPX (https://github.com/STEllAR-GROUP/hpx/commit/6354a203bd173a9d4fcac7e9f5134301e126c13e), and this commit of octotiger: https://github.com/dmarce1/octotiger/commit/8d5669f4622162fea8931afb91a5cef456d93741.

**Comment by sithhell** [comment]
Thanks for reporting, this should be fixed once #1905 is merged.

**Comment by sithhell** [comment]
NB: I tested octotiger on supermic on 128 nodes for a total of 4 hours and it seems to operate fine (in release mode)

**Comment by dmarce1** [comment]
Did you test it with the 1905 fix or are you saying it is working fine for you without the fix?

**Comment by sithhell** [comment]
Am 10.12.2015 4:10 nachm. schrieb "Dominic Marcello" <
notifications@github.com>:
>
> Did you test it with the 1905 fix or are you saying it is working fine
for you without the fix?

The fixing_1903 (#1905) should work fine, yes.

**Comment by dmarce1** [comment]
It freezes up on me part way through the initial model part of the computation (though I am using debug mode). Which MPI are you using? I am using Intel MPI.

**Comment by sithhell** [comment]
Am 10.12.2015 5:26 nachm. schrieb "Dominic Marcello" <
notifications@github.com>:
>
> It freezes up on me part way through the initial model part of the
computation (though I am using debug mode). Which MPI are you using? I am
using Intel MPI.

I think I use mvapich. Did you recompile both octotiger and HPX or just HPX?

**Comment by dmarce1** [comment]
Both. I will try with mvapich. You are using the commit of octotiger at the top of this page?

**Comment by neutrino504** [comment]
I am still getting random freeze ups with mvapich.  I am not sure what I'm doing differently from you other than running in debug mode.

I am using boost 1.59, mvapich2 (or intel mpi before this point), intel 15 compiler, gcc 4.9 headers. In HPX I build with hwloc=on and with the custom memory allocator option. 

It may not make a difference, but should I compile HPX with the mpi wrappers or with the intel compiler?

**Comment by dmarce1** [comment]
I am still getting random freeze ups with mvapich. I am not sure what I'm doing differently from you other than running in debug mode.

I am using boost 1.59, mvapich2 (or intel mpi before this point), intel 15 compiler, gcc 4.9 headers. In HPX I build with hwloc=on and with the custom memory allocator option.

It may not make a difference, but should I compile HPX with the mpi wrappers or with the intel compiler directly?

**Comment by hkaiser** [comment]
@dmarce1 One of the differences is that you're building your application with your own build system. That might or might not be the reason, though.
