### ISSUE TITLE
Intel 15 compiler bug preventing HPX build

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1919]
An Intel 15 compiler bug is popping up when I try to build the latest commit: 

[ 57%] /home/dmarce1/debug/include/boost/fusion/iterator/mpl/convert_iterator.hpp(57): internal error: assertion failed at: "shared/cfe/edgcpfe/lower_il.c", line 18968

              return call(x, is_fusion_iterator<T>());
              ^

This is using hpx commit:
https://github.com/STEllAR-GROUP/hpx/commit/0dfb8ee81d881d62e53e492b27b997e569d5837b

here is the full output:
https://gist.github.com/dmarce1/19f2fa73d8bfba7e7e9d

**Comment by hkaiser** [comment]
@dmarce1 Do you know which change to HPX has triggered this compiler bug?

**Comment by dmarce1** [comment]
My last build was December 15th, so it could be any changes made from that day until https://github.com/STEllAR-GROUP/hpx/commit/0dfb8ee81d881d62e53e492b27b997e569d5837b.

**Comment by dmarce1** [comment]
This is the offending commit:

https://github.com/STEllAR-GROUP/hpx/commit/9dd8fc3565aabc951c4d2229ba7bb27b15323eec

**Comment by hkaiser** [comment]
@dmarce1 I doubt 9dd8fc3565aabc951c4d2229ba7bb27b15323eec is the first non-working commit. But I assume it's something in its proximity. @sithhell: could it be that the configuration changes (5b4e47df5df055c670b292f19b0c58882357ebac) broke octotiger?

**Comment by sithhell** [comment]
Am 20.12.2015 5:03 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> @dmarce1 I doubt 9dd8fc3 is the first non-working commit. But I assume
it's something in its proximity. @sithhell: could it be that the
configuration changes (5b4e47d) broke octotiger?

Yes. It looks like they broke all Intel compiler builds. I'm working on
that.
