### ISSUE TITLE
serialization of std::array appears broken in latest commit

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1923]
When compiling octotiger https://github.com/dmarce1/octotiger/commit/049ee7ef2b59dedb138f33a39ed9c220204a3096 with HPX 1e542601410af93b9dab3af7d085bcfffa4f6a35, I get the error messages here: https://gist.github.com/dmarce1/cda50131e87350e34f29, which seem to indicate a problem with std::array serialization.

**Comment by AntonBikineev** [comment]
let me look into that at night

**Comment by hkaiser** [comment]
@dmarce1 Are you sure you have `#include <hpx/includes/serialization.hpp>` in the source files in question?

**Comment by AntonBikineev** [comment]
or at some point in your sources you should include <hpx/runtime/serialization/array.hpp>

**Comment by dmarce1** [comment]
I do not have  hpx/includes/serialization.hpp included, but I do have hpx/runtime/serialization/serialize.hpp and hpx/runtime/serialization/array.hpp.

**Comment by hkaiser** [comment]
AFAICS, the file [grid.hpp](https://github.com/dmarce1/octotiger/blob/master/src/grid.hpp) does not include any of the HPX serialization headers.

**Comment by dmarce1** [comment]
The headers are in defs.hpp

**Comment by hkaiser** [comment]
From the fix (#1926) we can see that serializing `std::array` has never worked :/ - isn't that amazing?

**Comment by AntonBikineev** [comment]
@hkaiser, it's just my bad

**Comment by hkaiser** [comment]
@AntonBikineev please don't worry about this.
