### ISSUE TITLE
Issues with static HPX libraries

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1925]
> I am linking against a static build of HPX on Titan. I’m having issues
> with FIND_PACKAGE in CMake and the HPXConfig.cmake created by the hpx
> configure. I have attached what I am getting on Titan from this.
> 
> You’ll notice that hpx.a is not included in the HPX_LIBRARIES variable and
> therefore I am finding that I am missing those symbols in the link. If I
> force hpx on the link line then things get out of order and it can’t find
> the boost symbols it needs. Should the hpx library be added to the front
> of this variable? HPX_LIBRARY_DIR is empty as well. There seems to be
> nothing in HPXConfig.cmake that FIND_PACKAGE would use to actually link
> against hpx.
> 
> So far my local builds have been working but that is because I have been
> doing shared builds. Pre-compiled dependencies on Titan do not have -fPIC
> and shared builds are typically discouraged.

**Comment by sithhell** [comment]
This issue is superseeded by #1950.
