### ISSUE TITLE
Floating point exception in statistics_counter<boost::accumulators::tag::mean>::get_counter_value

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#1933]
I am using performance counters to investigate https://github.com/STEllAR-GROUP/hpx/issues/1753 . I get the following output, ending with a floating point exception caused termination in

    hpx::performance_counters::server::statistics_counter<
        boost::accumulators::tag::mean
    >::get_counter_value(bool) 

see: https://gist.github.com/dmarce1/14f30c0d2ed8fc0f2c2f

This is with HPX https://github.com/STEllAR-GROUP/hpx/commit/4645f1275997c772baec21bb679b615cbb29c3d4 and the current octo-tiger in debug mode using 64 nodes on SuperMIC.

I also cannot make sense of the counter output. Its suppose to be outputting average thread count but the number it outputs is way too big and negative.

**Comment by pagrubel** [comment]
why are you averaging a total count?

On Dec 28, 2015, at 10:02 AM, Dominic Marcello <notifications@github.com<mailto:notifications@github.com>> wrote:


I am using performance counters to investigate #1753<https://github.com/STEllAR-GROUP/hpx/issues/1753> . I get the following output, ending with a floating point exception caused termination in hpx::performance_counters::server::statistics_counterboost::accumulators::tag::mean::get_counter_value(bool): https://gist.github.com/dmarce1/14f30c0d2ed8fc0f2c2f

This is with HPX 4645f12<https://github.com/STEllAR-GROUP/hpx/commit/4645f1275997c772baec21bb679b615cbb29c3d4> and the current octo-tiger in debug mode using 64 nodes on SuperMIC.

I also cannot make sense of the counter output. Its suppose to be outputting average thread count but the number it outputs is way too big and negative.

**Comment by hkaiser** [comment]
@dmarce1 The easiest way to investigate things like #1753 is to insert a call to `hpx::evalueate_active_counters()` after each time step (this will evaluate all performance counters which were specified on the command line), run the code with `--hpx:print-counter=*` and `--hpx:print-counter-format=csv`. After the run, use this script: [plot.py](https://github.com/sithhell/sithhell.github.io/blob/master/perf_counters_plot/plot.py) to generate plots from all counters. The generated html page will show the current counter values and the increments. Pay attention to those counters where the increments increase over time.
