### ISSUE TITLE
Simplify external builds

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1950]
Upon closer investigation of #1925, we came to the conclusion that building applications against HPX needs to be simplified. In order to achieve that, the following items need to be implemented:
  - [ ] properly export `HPX_LIBRARIES` in HPXConfig.cmake
  - [ ] Make sure that applications build correctly without the need to set the `HPX_APPLICATION_NAME` and `HPX_COMPONENT_NAME` macros.
  - [ ] Better document CMake usage, in particular how to enforce a specific C++ Language Standard, for example C++11

**Comment by gentryx** [comment]
Doesn't HPX automatically set the language standard in CMAKE_CXX_FLAGS?

**Comment by sithhell** [comment]
Not anymore with this patch

**Comment by gentryx** [comment]
But... why?

**Comment by sithhell** [comment]
Am 10.01.2016 1:10 vorm. schrieb "Andreas Schäfer" <notifications@github.com
>:
>
> But... why?

Short answer: to only get what you need. With that change, only
applications that build against HPX will have the flags necessary to build
against HPX. There is no pollution of the global CMAKE_CXX_FLAGS anymore
which can be easily overridden by third party projects and might lead to
subtitle failures. The target properties used in this patch are also
transitive, such that those flags will get inherited downstream if the
downstream package exports its library targets in the same way. For
example, lgd applications don't need to call hpx_setup_target anymore if
they want to use the HPX backend of lgd.

**Comment by gentryx** [comment]
@sithhell I don't know what changed your mind about global C++ flags pollution, but I'm happy that it happened.

**Comment by sithhell** [comment]
Am 10.01.2016 7:57 nachm. schrieb "Andreas Schäfer" <
notifications@github.com>:
>
> @sithhell I don't know what changed your mind about global C++ flags
pollution, but I'm happy that it happened.

Ooh, i was never opposed. The only thing missing was a way to implement
what we want. That's what we have now, I guess.
