### ISSUE TITLE
HPX releases should not use -Werror

### ISSUE THREAD

**Issue by eschnett** [STEllAR-GROUP/hpx#1954]
While building HPX 0.9.11 on a Linux workstation, I encountered this error:
```
/home/eschnett/src/spack/opt/spack/linux-x86_64/gcc-5.3.0-gcc-5.2.0/boost-1.59.0-rkrov6sq3ob4r4qrhqe4az6w3e5dxsyz/include/boost/spirit/home/qi/numeric/detail/numeric_utils.hpp:319:66: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
                 while (it != last && *it == '0' && leading_zeros < MaxDigits)
                                                                  ^
```

I understand that -Werror makes sense during development, but you will agree that this error is harmless in most cases. I suggest to disable -Werror in HPX releases.

**Comment by hkaiser** [comment]
I wouldn't object to this change. @sithhell What do you think?

**Comment by hkaiser** [comment]
@eschnett As it turns out you can easily disable this warning/error by configuring HPX using the `-DHPX_WITH_COMPILER_WARNINGS=OFF` option. Also, newer versions of HPX treat Boost header files as system headers, so the particular warning/error you're seeing should be gone as well.
