### ISSUE TITLE
Papi counters don't reset

### ISSUE THREAD

**Issue by pagrubel** [STEllAR-GROUP/hpx#1960]
Papi counters do not reset when using  hpx::evaluate_active_counters(true);

**Comment by hkaiser** [comment]
@maciekab Is that something you could look into? Is it possible to reset the counters in the first place?

**Comment by pagrubel** [comment]
If its not possible we should probably document it. I just plan on taking care of it when processing them

On Jan 14, 2016, at 12:13 PM, Hartmut Kaiser <notifications@github.com<mailto:notifications@github.com>> wrote:


@maciekab<https://github.com/maciekab> Is that something you could look into? Is it possible to reset the counters in the first place?

**Comment by maciekab** [comment]
The test in "tests/regressions/performance_counters/*" uses reset function and it was working before. I won't have time to look at this before Monday, though (proposals!).

**Comment by pagrubel** [comment]
Checked out great!  Thanks @maciekab
