### ISSUE TITLE
parallel:copy_if has race condition when used on in place arrays

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#1962]
Consider the following sequence being operated on in chunks with a copy_if predicate that returns true for even, false for odd. The || symbol represents the task chunk boundaries
```
input seq : 0 1 2 3 || 4 5 6 7 || 8 9 10 11.......
expected  : 0 2 4 6 8 10
actual    : 0 4 4 6 8 10 ... 
```
The problem is that the second task acting on {4 5 6 7} may copy the 4 into the output at position 2 before the first task has read it and hence a duplicate symbol is produced on the output.

When used in parallel on an output that is the same as the input, copy_if should either 
* revert back to serial operation (or serialize the tasks)
* use an intermediate array to copy into before finally copying to the output.
* does an alternative copy_if algorithm exist that does not suffer from this problem?

**Comment by hkaiser** [comment]
No other `copy_if` algorithm is necessary. The problem is apparently caused by a missing dependency between segment one being done with reading and segment 2 starting to copy data.

**Comment by hkaiser** [comment]
Ahh, I take that back. The problem is that `copy_if` applied to overlapping sequences invokes undefined behavior (see 25.3.1 [alg.copy]). Should we close this ticket?

**Comment by biddisco** [comment]
Rats. I didn't see the part about UB. In that case. all is fine and I shall close the ticket.

**Comment by hkaiser** [comment]
Well, it does not say anything about UB, it says 'the sequences shall not overlap'.

**Comment by K-ballo** [comment]
Violation of a _Requires_ yields UB unless _Throws_ says otherwise, or a diagnostic is mandated.
