### ISSUE TITLE
Automatic plotting of benchmark times for certain tests

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#1965]
We have discovered recently that a test run with CTest and submitted to a dashboard running CDash can export a DartMeasurement tag which is picked up by CDash and allows one to plot the time produced over a period (days/weeks/months) and track the performance of a test.
Note that CDash already plots the execution time of a test, but this time includes overheads such as startup and initialization and does not necessarily reflect the true time of an individual algorithm which we can now time individually and more accurately. Note that we can in fact export multiple time tags from a test if there is a need for multiple mini performance tests.

I would like to propose that certain tests (particularly `tests.unit.parallel.*`) be improved as follows.
- add a benchmark option to the command line  
  `desc_commandline.add_options() ("benchmark", "run a timing benchmark only");`
- modify the test so that when it receives the benchmark option, it executes a single test, chosen to be representative of the runtime of the algorithm, when the option is not present, run the standard unit test.

```
    if (vm.count("benchmark")) {
        sort_benchmark();
    }
    else {
        test_sort1();
        test_sort2();
    }
```
- output a time from the benchmark - using the CDash DartMeasurement tag and a name chosen to reflect the test  
  `<DartMeasurement name="SortDoublesTime" type="numeric/double">0.260961</DartMeasurement>`
- in CMake, add an additional test (a macro shall be provided to make it easy) that runs the same exe as the normal unit test, but with the extra `--benchmark` option appended. 
- a name such as `tests.benchmark.parallel.*` or `tests.timing.parallel.*` should be used for the test name so that we can 
  - enable them in one go in CMake
  - run them in one CTest command

Using the existing tests (with an extra option) rather than adding new test exe's is suggested because it will not significantly affect the build time or footprint of hpx.

If this is a good idea, then please suggest a suitable name for the benchmark/regression/performance tests so that we can start implementing them and begin collecting timing to track how algorithms evolve as changes are made. I have tested the above with sort and will add the same to sort_by_key, scan, and other scan related algorithms if this is approved.

**Comment by hkaiser** [comment]
I like all of what you suggested. We could start implementing this based on the existing performance tests which are currently run by the performance-test-buildbot.

**Comment by biddisco** [comment]
Having spent some time implementing this for a few tests and playing with it - I'm now thinking that there is actually no need to bother with the `--benchmark` option and the extra tests in cmake (or having a `make tests.timing.parallel` rule. It is simple enough to just add a `benchmark();`function to an existing unit test, where it will dump out the time and appear in the CDash plots when you want it. Existing tests will just take slightly longer, dump out a couple of lines of extra text, but apart from that there's no real impact and it's very easy to add it to an existing test and start getting timing info collected.

**Comment by hkaiser** [comment]
How would that interact with other output tests might generate (some do)? 

Also, the benchmarks should be run for release builds only, so wrapping the call with an `#ifdef HPX_DEBUG` should be mandatory.

**Comment by biddisco** [comment]
The output from a test would essentially gain one or more strings of the form
```<DartMeasurement name="MyTimeName" type="numeric/double">0.260961</DartMeasurement>``` 
If this affects any tests, then it would be a problem, but I am not aware of any (unit) tests that this additional text would trigger a failure for. CircleCi will catch any new test failures before a merge if this is the case.

The point about `#ifdef HPX_DEBUG` is a good one and I'll make sure I adhere to that.

**Comment by biddisco** [comment]
Just as a followup on this, I would like to draw one's attention to one of the tests for which I enabled timing output in ctest/cdash compatible form
http://cdash.cscs.ch/testDetails.php?test=5513945&build=44608
if you select SortByKeyTime (in the plot option) and then `zoom out`, you will see a noticable drop in performance around mid july (ignore the flat region in june, I was testing a new sort algorithm which had bettter performance, but turned ut to be buggy).

**Comment by biddisco** [comment]
Some work on this is now being added in #3421
