### ISSUE TITLE
reset seems to still be incorrect especially for the sort benchmark

### ISSUE THREAD

**Issue by pagrubel** [STEllAR-GROUP/hpx#1988]
For the sort benchmarks we get overheads and cumulative times that are greater than execution time when we divide them by the number of cores
I performed a git bisect and verified that the values were more reasonable before this commit:
fb588d701e588fa5d16f722674b1825081a19545
Here are results before and after the change for both sort and uts
I also show some results when only querying one counter since we had trouble before with mutliple counters:

[sort.txt](https://github.com/STEllAR-GROUP/hpx/files/131632/sort.txt)

for comparison here are some results from uts

[uts.txt](https://github.com/STEllAR-GROUP/hpx/files/131650/uts.txt)

**Comment by pagrubel** [comment]
@hkaiser can you look at this before Mar 4?

**Comment by msimberg** [comment]
@pagrubel Is this still a problem?

**Comment by pagrubel** [comment]
I have no idea
