### ISSUE TITLE
Command line handling does not produce error

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1995]
We have decided a while back that we will not report unknown command line options for applications which use `hpx_main.hpp` (i.e. which emulate `main()`). The rationale was that those applications may want to do their own command line handling and reporting unknown options would be undesireable.

Now, as it turns out this has a downside. As described in a question on stackoverflow (http://stackoverflow.com/questions/35367816/hpx-minimal-two-node-example-set-up) a user was not able to make an HPX application work because of a typo in one of the command line options. The user wrote `--hpx.hpx` instead of `--hpx:hpx`. The application was `hello_world` which relies on emulating `main()`.

If HPX was reporting this as an error the user would have had a lot less problems in the first place. 

It is unclear at this point how this could be resolved. Some heuristic might help.

**Comment by biddisco** [comment]
Would it be feasible to parse the options and print out a warning that "the following options were not recognized by hpx" - if the user sees on with hpx.blah in it, they'll probably realize something went wrong.
adding the option hpx:no-option-warn, would suppress it (or something similar)

**Comment by hkaiser** [comment]
@biddisco I think I found a reasonable solution - see #1998.
