### ISSUE TITLE
Undefined reference to hpx::assertion_failed

### ISSUE THREAD

**Issue by chinz07** [STEllAR-GROUP/hpx#2000]
Building commit 6c08935c5d9158031bbdee01872283e2dd8b0ceb with GCC 5.3 and RelWithDebInfo as the build type fails due to an undefined reference to `hpx::assertion_failed`.

After examining the compiler output, it seems that all calls of assertion_failed are inlined. Afterwards the dead function is eliminated by the compiler and the reference in assert.hpp can not subsequently be resolved by the linker.

The reason for this behavior seems to be the contradicting declaration of this function in exception.hpp (as an inline function) and in assert.hpp (as a non-inline function).

As far as I know an inline function must be defined in every translation unit where it is called. In addition, an inline function with external linkage must be declared inline in every translation unit. Both rules are (possibly) violated in this case.

I was able to fix the issue by moving the definition into exception.cpp

assertion_failed_msg should be affected by the same issue.

**Comment by hkaiser** [comment]
@chinz07 Would you be able to create a pull request fixing this? We'd be more than happy to accept such a patch.

**Comment by chinz07** [comment]
@hkaiser Sure! I will submit a pull request as soon as possible.
