### ISSUE TITLE
Compilation error while running sample hello_world_component code

### ISSUE THREAD

**Issue by satyaki3794** [STEllAR-GROUP/hpx#2011]
Multiple compilation errors while running the code for example in the documentation. (http://stellar-group.github.io/hpx/docs/html/hpx/manual/build_system/using_hpx/pkgconfig.html)
Code located at hpx/examples/hello_world_component.

**Comment by K-ballo** [comment]
What are the multiple errors? What is the compiler output?

**Comment by satyaki3794** [comment]
Exact commands to be run are in hello.sh. On running the script, I get the following output on the terminal (including notes and warnings).

[http://pastebin.com/z6N2TnWV](url)
