### ISSUE TITLE
Make errors related to init_globally.cpp example while building HPX out of the box

### ISSUE THREAD

**Issue by satyaki3794** [STEllAR-GROUP/hpx#2020]
After the latest commit (https://github.com/STEllAR-GROUP/hpx/pull/2005/files), I am not being able to build HPX out-of-the-box. I get make errors related to init_globally.cpp. Gist file is here: https://gist.github.com/satyaki3794/a7bf80a8678c55433065

**Comment by hkaiser** [comment]
For now I have disabled the failing example. I'll leave this ticket open as a reminder that it still needs to be fixed properly.

**Comment by hkaiser** [comment]
Some background: the example fails to compile on different platforms for different reasons. The first reason is that Boost V 1.55 and below don't support `optional<>::emplace`. The second reason is that older versions of gcc (and other compilers) don't support expanding template parameter packs inside a lambda expression where the pack is captured from the outer context (see for instance here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47226)..

**Comment by satyaki3794** [comment]
I am using Boost V 1.59 and gcc 4.8.2 (stock gcc with Ubuntu 14.04). Yes, older version of gcc may be the reason (I can see an error related to no support for expanding template parameter).

**Comment by hkaiser** [comment]
[07:07]	hkaiser: satyaki3794: do you think you'd be able to fix #2020?
[07:08]	hkaiser: satyaki3794: I think it's fairly easy
[07:08]	hkaiser: the boost version could be handled like here: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/parallel/executors/executor_traits.hpp#L166, the lambda/parameter pack issue could be worked around by replacing the lambdas with hpx::util::bind
[07:09]	satyaki3794: hkaiser: okay, i'll try it
[07:09]	hkaiser: great!

**Comment by hkaiser** [comment]
This was fixed by merging #2023
