### ISSUE TITLE
Compilation error when compiling with thread queue waittime performance counter

### ISSUE THREAD

**Issue by ltroska** [STEllAR-GROUP/hpx#2033]
When compiling the latest master ( c12a53b6a49e2e8ab922dc3608c93e81adebeea1 ) with gcc 5.3 and the flag HPX_WITH_THREAD_QUEUE_WAITTIME=ON, I get the following error: https://gist.github.com/ltroska/a5cadeb17eda50578d81 .

**Comment by hkaiser** [comment]
This was fixed by merging #2034
