### ISSUE TITLE
Use a less restrictive iterator definition in hpx::lcos::detail::future_iterator_traits

### ISSUE THREAD

**Issue by HadrienG2** [STEllAR-GROUP/hpx#2035]
Currently, HPX defines future iterators as something which has an iterator_category member type. See hpx/lcos/future.hpp:293...

    template <typename Iter, typename Enable = void>
    struct future_iterator_traits
    {};

    template <typename Iterator>
    struct future_iterator_traits<Iterator,
        typename hpx::util::always_void<
            typename Iterator::iterator_category
        >::type>
    {
        typedef
            typename std::iterator_traits<Iterator>::value_type
            type;

        typedef hpx::traits::future_traits<type> traits_type;
    };

This definition is too restrictive as it discards the single most common type of C++ iterator: pointers. Which means, for example, that wait_all cannot operate on an std::array of futures, ie `hpx::wait_all(array.cbegin(), array.cend())` will turn into a long trail of compiler vomit.

I think that this should be corrected by using std::iterator_traits all the way up instead. Here is a proposal:

    template <typename Iterator>
    struct future_iterator_traits<Iterator,
        typename hpx::util::always_void<
            typename std::iterator_traits<Iterator>::value_type
        >::type>
    {
        typedef
            typename std::iterator_traits<Iterator>::value_type
            type;

        typedef hpx::traits::future_traits<type> traits_type;
    };

**Comment by hkaiser** [comment]
@Neolander: Could you create a small test case reproducing the issue, please? I'd like to use that to add it to the test suite once we fixed the issue.

**Comment by Neolander** [comment]
My pleasure!

This code should probably compile, but doesn't (on GCC 4.8, Linux x86_64):

```
#include <array>

#include <hpx/hpx_main.hpp>
#include <hpx/include/future.hpp>
#include <hpx/lcos/wait_all.hpp>

int main() {
   std::array<hpx::shared_future<int>, 1> future_array { hpx::make_ready_future(0) };
   hpx::wait_all(future_array.cbegin(), future_array.cend());
}
```

Relevant compiler output:

```
In file included from /usr/local/include/hpx/traits/acquire_shared_state.hpp:11:0,
                 from /usr/local/include/hpx/lcos/future.hpp:13,
                 from /usr/local/include/hpx/include/future.hpp:9,
                 from /home/hadrien/Bureau/Programmation/HPX/Tests/Futurization/future_iterator_crasher.cpp:3:
/usr/local/include/hpx/traits/future_access.hpp: In instantiation of ‘struct hpx::traits::detail::shared_state_ptr_for<const hpx::lcos::shared_future<int>*>’:
/usr/local/include/hpx/lcos/wait_all.hpp:396:15:   required from ‘void hpx::lcos::wait_all(Ts&& ...) [with Ts = const hpx::lcos::shared_future<int>*, const hpx::lcos::shared_future<int>*]’
/home/hadrien/Bureau/Programmation/HPX/Tests/Futurization/future_iterator_crasher.cpp:8:60:   required from here
/usr/local/include/hpx/traits/future_access.hpp:42:16: error: no type named ‘type’ in ‘struct hpx::traits::future_traits<const hpx::lcos::shared_future<int>*, void>’
         struct shared_state_ptr_for
                ^
In file included from /home/hadrien/Bureau/Programmation/HPX/Tests/Futurization/future_iterator_crasher.cpp:4:0:
/usr/local/include/hpx/lcos/wait_all.hpp: In instantiation of ‘void hpx::lcos::wait_all(Ts&& ...) [with Ts = const hpx::lcos::shared_future<int>*, const hpx::lcos::shared_future<int>*]’:
/home/hadrien/Bureau/Programmation/HPX/Tests/Futurization/future_iterator_crasher.cpp:8:60:   required from here
/usr/local/include/hpx/lcos/wait_all.hpp:396:15: error: no type named ‘type’ in ‘struct hpx::traits::detail::shared_state_ptr_for<const hpx::lcos::shared_future<int>*>’
             > result_type;
               ^
/usr/local/include/hpx/lcos/wait_all.hpp:397:53: error: no type named ‘type’ in ‘struct hpx::traits::detail::shared_state_ptr_for<const hpx::lcos::shared_future<int>*>’
         typedef detail::wait_all_frame<result_type> frame_type;
                                                     ^
```

**Comment by hkaiser** [comment]
@Neolander I added the branch fixing_2035. Could you please verify whether this fixes your problem (and whether all the other tests still pass)?

**Comment by HadrienG2** [comment]
Trying this branch as-is, the test failed with this GCC warning, which was promoted into an error by Werror:

```
/home/hadrien/Bureau/Programmation/HPX/hpx/tests/regressions/lcos/wait_all_std_array_2035.cpp: In function ‘int hpx_startup::user_main()’:
/home/hadrien/Bureau/Programmation/HPX/hpx/tests/regressions/lcos/wait_all_std_array_2035.cpp:19:89: error: missing braces around initializer for ‘std::__array_traits<hpx::lcos::shared_future<int>, 1ul>::_Type {aka hpx::lcos::shared_future<int> [1]}’ [-Werror=missing-braces]
    std::array<hpx::shared_future<int>, 1> future_array { hpx::make_ready_future(0) };
                                                                                         ^
```

Investigation suggests that there might be a [bug in this GCC warning](http://stackoverflow.com/questions/11551986/gcc-missing-braces-around-initializer/). Anyhow, after applying this patch...

```diff
--- a/tests/regressions/lcos/wait_all_std_array_2035.cpp
+++ b/tests/regressions/lcos/wait_all_std_array_2035.cpp
@@ -16,7 +16,7 @@
 
 int main()
 {
-   std::array<hpx::shared_future<int>, 1> future_array { hpx::make_ready_future(0) };
+   std::array<hpx::shared_future<int>, 1> future_array {{ hpx::make_ready_future(0) }};
    hpx::wait_all(future_array.cbegin(), future_array.cend());
 
    return 0;
```

...the test now passes.

Adding extra braces alters a

**Comment by hkaiser** [comment]
That should be fixed now, thanks.
