### ISSUE TITLE
Support component templates

### ISSUE THREAD

**Issue by HadrienG2** [STEllAR-GROUP/hpx#2062]
HPX components are a beautiful distributed computing abstraction. However, as far as I understand, their greatness does not currently extend to class templates. If I attempt to write a toy templated component like this...

```c++
template<class T>
class Broadcast :
   public hpx::components::simple_component_base<Broadcast<T>>
{
   public:
      void set(const T & new_value) { m_value = new_value; }

      T get() const { return m_value; }
      HPX_DEFINE_COMPONENT_ACTION(Broadcast, get, get_action);

   private:
      T m_value;
}
```

...then I will be unable to proceed further with the HPX_REGISTER_ACTION_DECLARATION, HPX_REGISTER_COMPONENT and HPX_REGISTER_ACTION macros, because C++ templates and C-style preprocessor macros and unique identifiers do not mix well at all.

In some cases, it is possible to work around this issue by using dynamic polymorphism instead of static polymorphism, i.e. using an abstract base class instead of a template type parameter. However, considering the very widespread use of class templates in idiomatic C++ programs, I think this is a use case that HPX might want to support in the long run.

May be somewhat related to #449, although that issue focuses more on the genericity of actions rather than that of components.

**Comment by hkaiser** [comment]
This is more of a documentation issue as we know that it can be made to work.

**Comment by HadrienG2** [comment]
Ah, interesting! Just out of curiosity, do relevant macros already exist for this use case, hidden somewhere in the codebase, or does it entail diving into the internals of HPX and doing a lot of things by hand ?

**Comment by hkaiser** [comment]
No diving should be necessary. I'll create a small example demonstrating what needs to be done.

**Comment by hkaiser** [comment]
Please see #2063 for an example demonstrating on how template components could be implemented and used (examples/accumulators/template_acumulator.*)

**Comment by HadrienG2** [comment]
Thank you! I would have a couple of questions about that example:

- Is the separate REGISTER_TEMPLATE_ACCUMULATOR_DECLARATION macro needed ? No one seems to call it in the pull request. Since clients need to call REGISTER_TEMPLATE_ACCUMULATOR anyway, a separate declaration step might be superfluous... or not.
- What does the HPX_REGISTER_COMPONENT_MODULE macro do ?

**Comment by hkaiser** [comment]
`REGISTER_TEMPLATE_ACCUMULATOR_DECLARATION` is only needed if you have to access the actions from several translation units. In this case you place the declaration macro into the header and the definition macro into one of the source files.

`HPX_REGISTER_COMPONENT_MODULE` is generating all boilerplate for a shared library which exports components. This is needed exactly once per shared library. I thought we would have some docs for it, but those are missing... Note to self: add docs!
