### ISSUE TITLE
More verbose output from cmake configuration

### ISSUE THREAD

**Issue by mcopik** [STEllAR-GROUP/hpx#2088]
Hi,

Recently I have spent a lot of time to find a simple error in compiler configuration. Unfortunately, the only output is the information that a one particular test has failed. It takes too much time to manually modify cmake files to obtain either command used to compile and execute test or error message.

My proposal: extend current configuration to print out:

- details of all tests in debug log level

- details of failed tests as warnings

Unfortunately, cmake itself doesn't have any "verbose" option for the configuration phase; --debug-output doesn't provide such information.

**Comment by hkaiser** [comment]
I'd suggest adding `hpx_debug()` statements in [HPX_AddConfigTest.cmake](https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/HPX_AddConfigTest.cmake) for the case when things fail.

**Comment by mcopik** [comment]
@hkaiser Yes, please see pull request #2089
