### ISSUE TITLE
make tests should just build the tests

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2092]
CMake has a built in **test** target which will run ctest to check that the tests pass in the normal way - it is invoked by using `make test` and it does not build the tests first.

HPX has a target **tests**, which will build regression, unit, etc tests, but it also runs them afterwards.
This means that one cannot just `make tests` and build them without running unless you explicitly use

```
make tests.unit tests.regression tests.performance ...
```

The tests target is bound to the build process using a couple of lines here https://github.com/STEllAR-GROUP/hpx/blob/ea2cee1ae236decf03de2bd40e58113472d8e534/CMakeLists.txt#L1444-L1447 that trigger ctest after the tests target has compiled.

I believe that 'make tests' should _only_ build them and make test should _only_ run them.

Do we need a target that build and runs all tests?

**Comment by sithhell** [comment]
I agree. This target is a relic from older non ctest times.
Am 14.04.2016 3:48 nachm. schrieb "John Biddiscombe" <
notifications@github.com>:

**Comment by msimberg** [comment]
@biddisco @sithhell @hkaiser Is there something blocking this? It's a small change... I guess the key question is:
> Do we need a target that build and runs all tests?

**Comment by sithhell** [comment]
Yeah, let's just remove the coupling of running in the tests target and add
a "how to run the tests" section in the docs.
