### ISSUE TITLE
/work/dmarce1/debug/include/hpx/external/boost/cache/local_cache.hpp(89): error #303: explicit type is missing ("int" assumed)           HPX_MOVABLE_ONLY(local_cache);

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#2093]
I am getting this error:

/work/dmarce1/debug/include/hpx/external/boost/cache/local_cache.hpp(89): error #303: explicit type is missing ("int" assumed)
          HPX_MOVABLE_ONLY(local_cache);

when I attempt to build octotiger on queenbee. Using the exact same builds script, .modules, and .bashrc files I do not get this error on SuperMIC. Its not a result of a recent  HPX commit, I checked out an older commit from a few weeks ago and got the same problem.

Does anyone have any idea what this means?

**Comment by K-ballo** [comment]
Is that the entire error message? Which compiler is giving it?

**Comment by hkaiser** [comment]
Looks like a missing #include. I'll handle it (I wanted to move the cache to util anyways...)
