### ISSUE TITLE
Build error with octotiger and hpx commit e657426d

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#2103]
I get the following error when building octotiger on queenbee:

https://gist.github.com/dmarce1/de23f7f02f3fb4c63815b05d0b4a07c8

Here is the script I used to build it:

https://gist.github.com/dmarce1/a729adb59de81201ec4566db97e3419a

**Comment by K-ballo** [comment]
External `boost/cache` moved to `hpx/util/cache` in #2096

**Comment by hkaiser** [comment]
The cache has been moved and the `addressing_service.hpp` does not refer to the old position anymore. Please check that you have a consistent checkout.

**Comment by dmarce1** [comment]
You are right, somehow I had an HPX installation where I didn't expect it.
