### ISSUE TITLE
coalescing plugin handler is not optional any more

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2105]
If you compile a simple test app without building hpx-plugins first (only linking against libhpx and libhpx_iostreams for example), then the application will fail at runtime with an exception

    {what}: attempt to create message handler plugin instance of invalid/unknown type: \
        coalescing_message_handler: HPX(bad_plugin_type)

It seems that the attempt to load the plugin should fail gracefully, but instead triggers an abort.

**Comment by biddisco** [comment]
After doing some more experiments, it appears to be a problem with release builds that come from external applications built against the hpx tree. I'm a bit confused, but I can delete the parcel_coalescing plugin from the build tree and debug works fine, but release it broken, whether it is present or not.
I will continue to experiment.

**Comment by hkaiser** [comment]
@biddisco I have it reproduced locally, even in a debug build. Will investgate...

**Comment by zao** [comment]
On this subject, last I tried building HPX the parcel plugins were not in the dependency chain of `make tests`, which led to an 86% test failure rate. Did that get resolved and might the lack of a suitable dependency be part of this?
