### ISSUE TITLE
Stack trace of last bug causing issues with octotiger

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#2108]
Here is a stack trace of the last bug that I am having problems with 

```
> 0x2ae1bc9710ab  : hpx::components::server::destroy_base_lco(hpx::naming::gid_type const&, hpx::naming::address const&, hpx::util::one_size_heap_list_base*, int, hpx::error_code&) + 0xab in /work/dmarce1/release/lib/libhpx.so.0
> 0x2ae1bc97e113  : hpx::components::server::runtime_support::free_component(hpx::agas::gva const&, hpx::naming::gid_type const&, unsigned long) + 0x1253 in /work/dmarce1/release/lib/libhpx.so.0
> 0x2ae1bcdce26e  : hpx::agas::server::primary_namespace::free_components_sync(std::list<hpx::agas::server::primary_namespace::free_entry, std::allocator<hpx::agas::server::primary_namespace::free_entry> >&, hpx::naming::gid_type const&, hpx::naming::gid_type const&, hpx::error_code&) + 0x85e in /work/dmarce1/release/lib/libhpx.so.0
> 0x2ae1bcdd971f  : hpx::agas::server::primary_namespace::decrement_credit(hpx::agas::request const&, hpx::error_code&) + 0xbaf in /work/dmarce1/release/lib/libhpx.so.0
> 0x2ae1bcde36a3  : hpx::agas::server::primary_namespace::service(hpx::agas::request const&, hpx::error_code&) + 0x453 in /work/dmarce1/release/lib/libhpx.so.0
> 0x2ae1bcde2ef6  : hpx::agas::server::primary_namespace::bulk_service(std::vector<hpx::agas::request, std::allocator<hpx::agas::request> > const&, hpx::error_code&) + 0x86 in /work/dmarce1/release/lib/libhpx.so.0
> 0x2ae1bcc258fa  : ??? + 0x2ae1bcc258fa in /work/dmarce1/release/lib/libhpx.so.0
> 0x2ae1bcf5c536  : hpx::threads::coroutines::detail::coroutine_impl::operator()() + 0x196 in /work/dmarce1/release/lib/libhpx.so.0
> 0x2ae1bc2ec446  : ??? + 0x2ae1bc2ec446 in /work/dmarce1/release/lib/libhpx.so.0
```

This full output is here:
https://gist.github.com/dmarce1/7e7fc4567e6a512d872e0b332bde7412

I am working on getting this traced with line numbers and a core dump.

**Comment by dmarce1** [comment]
The core dump and executable from a recent crash of this type is available at /project/dmarce1/core_dump/core_dump.tar.gz on SuperMIC.

**Comment by dmarce1** [comment]
Her is  stack trace with line numbers:
#0  0x0000003b98232625 in raise () from /lib64/libc.so.6
#1  0x0000003b98233e05 in abort () from /lib64/libc.so.6
#2  0x00002b86cebb203f in hpx::termination_handler (signum=122447) at /work/dmarce1/hpx_build/hpx/src/runtime.cpp:130
#3  <signal handler called>
#4  0x00002b86ceea5ea5 in ~managed_promise (gid=..., addr=..., heap=0x5, type=5, ec=...) at /work/dmarce1/hpx_build/hpx/hpx/lcos/promise.hpp:407
#5  hpx::components::server::destroy_base_lco (gid=..., addr=..., heap=0x5, type=5, ec=...) at /work/dmarce1/hpx_build/hpx/src/runtime/components/server/destroy_component.cpp:56
#6  0x00002b86ceeb2632 in hpx::components::server::runtime_support::free_component (this=0x3c760417b1f56800, g=..., gid=..., count=5)
    at /work/dmarce1/hpx_build/hpx/src/runtime/components/server/runtime_support_server.cpp:494
#7  0x00002b86cf52760e in hpx::agas::server::primary_namespace::free_components_sync (this=0x3c760417b1f56800, free_list=..., lower=..., upper=..., ec=...)
    at /work/dmarce1/hpx_build/hpx/src/runtime/agas/server/primary_namespace_server.cpp:1264
#8  0x00002b86cf532e3f in hpx::agas::server::primary_namespace::decrement_credit (this=0x0, req=..., ec=...) at /work/dmarce1/hpx_build/hpx/src/runtime/agas/server/primary_namespace_server.cpp:807
#9  0x00002b86cf53ccb3 in hpx::agas::server::primary_namespace::service (this=0x0, req=..., ec=...) at /work/dmarce1/hpx_build/hpx/src/runtime/agas/server/primary_namespace_server.cpp:102
#10 0x00002b86cf53c506 in hpx::agas::server::primary_namespace::bulk_service (this=0x0, reqs=..., ec=...) at /work/dmarce1/hpx_build/hpx/src/runtime/agas/server/primary_namespace_server.cpp:360
#11 0x00002b86cf67941a in hpx::util::detail::callable_vtable<hpx::threads::thread_state_enum (hpx::threads::thread_state_ex_enum)>::invoke(void **, enum hpx::threads::thread_state_ex_enum &) (
    f=0x3c760417b1f56800, vs=@0x0) at /work/dmarce1/hpx_build/hpx/hpx/runtime/actions/component_action.hpp:63
#12 0x00002b86cee7462a in operator() (this=0x2b887bb2afe0) at /work/dmarce1/hpx_build/hpx/hpx/util/detail/basic_function.hpp:254
#13 hpx::threads::coroutines::detail::coroutine_impl::operator() (this=0x2b887bb2afe0) at /work/dmarce1/hpx_build/hpx/src/runtime/threads/coroutines/detail/coroutine_impl.cpp:95
#14 0x00002b86ceac6c36 in hpx::threads::coroutines::detail::lx::trampoline (fun=0x3c760417b1f56800) at /work/dmarce1/hpx_build/hpx/hpx/runtime/threads/coroutines/detail/context_linux_x86.hpp:88
#15 0x0000000000000000 in ?? ()

Here is the core dump and executable.
 /project/dmarce1/dump2.tar.gz

When I trace all threads (thread apply bt all), it looks like most of the threads have stack traces like the one above.

**Comment by hkaiser** [comment]
Yet another instance of a spurious 'duplicate delete'... *sigh*

**Comment by sithhell** [comment]
We can close this once #2223 is merged.

**Comment by hkaiser** [comment]
#2223 has been merged. This should be fixed, pleasse reopen if necessary.
