### ISSUE TITLE
Compilation error when passing non-future argument to unwrapped continuation in dataflow

### ISSUE THREAD

**Issue by ltroska** [STEllAR-GROUP/hpx#2110]
When trying to pass a non-future parameter to an unwrapped continuation in dataflow, [this code](https://gist.github.com/ltroska/88187b034f1b336c461eba67f1a20df2) fails to compile, giving [this error](https://gist.github.com/ltroska/b94d9f1115c0da1e47903b006a75f85a).

**Comment by hkaiser** [comment]
This is a duplicate of #1400
