### ISSUE TITLE
Compilation error with gcc version 4.9.3 (MacPorts gcc49 4.9.3_0) 

### ISSUE THREAD

**Issue by gbibek** [STEllAR-GROUP/hpx#2113]
Compilation Log is attached here : https://gist.github.com/gbibek/f0ba7d7ecdd9cd615a8e58d971aa4abb

Boost Version : 1.59

gcc -v 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin15/4.9.3/lto-wrapper
Target: x86_64-apple-darwin15
Configured with: /opt/local/var/macports/build/_opt_mports_dports_lang_gcc49/gcc49/work/gcc-4.9.3/configure --prefix=/opt/local --build=x86_64-apple-darwin15 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc49 --includedir=/opt/local/include/gcc49 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-4.9 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-4.9 --with-gxx-include-dir=/opt/local/include/gcc49/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --disable-isl-version-check --with-cloog=/opt/local --disable-cloog-version-check --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --with-pkgversion='MacPorts gcc49 4.9.3_0' --with-build-config=bootstrap-debug
Thread model: posix
gcc version 4.9.3 (MacPorts gcc49 4.9.3_0)

**Comment by hkaiser** [comment]
This looks like a linker problem. I'm not sure if we can do anything about it.

**Comment by AntonBikineev** [comment]
The problem may be related to use of clang's linker (not that of gcc). You may try compiling hpx with apple-clang.

**Comment by gbibek** [comment]
The error went away when I compiled HPX with 

clang version 3.9.0 (trunk 266579)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-3.9/bin
