### ISSUE TITLE
Possible memory leak in 1d_stencil_8

### ISSUE THREAD

**Issue by markusobi** [STEllAR-GROUP/hpx#2121]
The example 1d_stencil_8 uses a custom allocator (partition_allocator) for the serialize_buffer inside the partition_data. The custom deleter is passed to the underlying boost::shared_array.

The problem:
The custom deleter is not called at all allocated memory. The reference count of the boost::shared_array is 3 before the last partition_data goes out of scope. There are still 2 references somewhere which lifetimes exceed the hpx_main. When the static allocator is destroyed the `heap_` is empty for `nt=0`. For any `nt` the `heap_` contains less elements than allocated via` new T[n]`. The `heap_` should contain all.

1d_stencil_8_1.cpp: output with arguments --nt 0 --np 1:
> allocate called
> ~partition_data(): use_count before destruction = 4
> leaving hpx_main
> ~partition_data(): use_count before destruction = 3
> hpx_main finished
> ~partition_allocator(): new_counter = 1
> ~partition_allocator(): heap_.size() = 0

The problem is not that the wrong deleter is called. When I added a static shared_array (tracker) in 1d_stencil_8_2.cpp to the allocator, to keep track of the use_count, I found out, that there is still **one** reference left (not including the static one) when the allocator is destroyed.

1d_stencil_8_2.cpp: output with arguments --nt 0 --np 1:
> allocate called
> ~partition_data(): use_count before destruction = 4
> ~partition_data(): use_count before destruction = 5
> leaving hpx_main
> ~partition_data(): use_count before destruction = 4
> hpx_main finished
> ~partition_allocator(): tracker.use_count() = 2
> ~partition_allocator(): new_counter = 1
> ~partition_allocator(): heap_.size() = 0

The printed use count should be 1 not 2, since "tracker" is the only reference left.

Summary: The custom deleter of partition_allocator is not called often enough, thus the `heap_` does not contain all pointers.
The reference count of the boost::shared_array is **2** after hpx_main finished and when the static allocator gets destroyed it is still **1**. Maybe some cyclic references going on?

Files: [1d_stencil_8_X.zip](https://github.com/STEllAR-GROUP/hpx/files/236676/1d_stencil_8_X.zip)
OS: Linux Mint 17 Qiana 64 bit
HPX revision: 1c4416c9b2f9ae9fa8339713cb122396d1bd2315
Boost version: 1.58

**Comment by hkaiser** [comment]
Do you have an idea how to fix it? Or at least what's wrong?

**Comment by markusobi** [comment]
The partitions are created in line 519 (`U_[0][i] = partition(here, nx, double(i));`) (1d_stencil_8_1.cpp).
If added after line 519 the following snippet prints: 

> use_count directly after creation = 2

```
boost::shared_array<double> arr;
{
    arr = U_[0][0].get_data(partition_server::middle_partition).get().data_array();
}
std::cout << "use_count directly after creation = " << arr.use_count() - 1 << std::endl;
```
Immediately after creation the use_count is already 2 (not including my test-tracker). Why is it two and not one?

The references are not visible in the code. I don't really know what the inheritance `struct partition : hpx::components::client_base<partition, partition_server>` really does. Same goes with `struct partition_server : hpx::components::component_base<partition_server>`.

The hpx_main only contains a stepper object. Inside the stepper class there are no `base` members at all. Without digging deep into `hpx::components::client_base` and `hpx::components::component_base` I can't tell you.

Or is it the dependency chain created with dataflow the one that keeps the partition alive?

**Comment by markusobi** [comment]
I reduced the code for the special case `nl=1, np=1, nt=0`
Output is the same:
> allocate called
> ~partition_data(): use_count before destruction = 4
> ~partition_data(): use_count before destruction = 5
> use_count directly after creation (not including tempory) = 2
> ~partition_data(): use_count before destruction = 3
> ~partition_data(): use_count before destruction = 4
> ~partition_data(): use_count before destruction = 5
> leaving hpx_main
> ~partition_data(): use_count before destruction = 4
> hpx_main finished
> ~partition_allocator(): tracker.use_count() = 2
> ~partition_allocator(): new_counter = 1
> ~partition_allocator(): heap_.size() = 0


[1d_stencil_8.cpp.zip](https://github.com/STEllAR-GROUP/hpx/files/237188/1d_stencil_8.cpp.zip)
