### ISSUE TITLE
hpx/hpx/runtime/applier_fwd.hpp - Multiple defined types

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#2123]
from /home/diehl/workspaceLSU/workspace/HPXExamples/src/full/Main_ratio.cpp:15:
/home/diehl/git/hpx/hpx/runtime/applier_fwd.hpp:24:30: warning: type attributes ignored after type is already defined [-Wattributes]
         class HPX_API_EXPORT applier;

**Comment by K-ballo** [comment]
Duplicate of #2109
