### ISSUE TITLE
Hpx does not compile over osx

### ISSUE THREAD

**Issue by AALEKH** [STEllAR-GROUP/hpx#2137]
On Executing make -jN , I receive following error's:

1) /usr/local/include/boost/context/execution_context.ipp:61:5: error: thread-local storage is not supported for the current target
    thread_local static ptr_t   current_rec;

This is probably due to lack of Thread local storage implementation over Clang (here: http://stackoverflow.com/a/29929949 )

PS: I am using boost-1.60.0_1

**Comment by sithhell** [comment]
On 05/02/2016 12:29 PM, Aalekh Nigam wrote:
> On Executing make -jN , I receive following error's:
> 
> 1) /usr/local/include/boost/context/execution_context.ipp:61:5: error:
> thread-local storage is not supported for the current target
> thread_local static ptr_t current_rec;
> 
> This is probably due to lack of Thread local storage implementation over
> Clang (here: http://stackoverflow.com/a/29929949 )

That's actually a bug in boost. Which boost version are you using? We
had this issue popping on IRC recently, I don't remember which version
exactly, but 1.59 is supposedly good (with -DHPX_WITH_NATIVE_TLS:BOOL=OFF).

**Comment by AALEKH** [comment]
@sithhell I am using boost version 1.60.
I am going to give it a try with boost 1.59 and update if things work out fine.

**Comment by hkaiser** [comment]
@aalekh Please prepare a PR for the docs (around here: https://github.com/STEllAR-GROUP/hpx/blob/master/docs/manual/build_system/prerequisites.qbk#L72-L84) describing which versions don't work. 

@zao I think you did a sweep over boost versions etc. Do you remember the outcome?

**Comment by zao** [comment]
If I read my logs right: 1.58 and 1.60 were unsuitable, <=1.57, 1.59 and current Boost master were fine.

**Comment by K-ballo** [comment]
Could/should we catch this in `config.hpp`?

**Comment by hkaiser** [comment]
> Could/should we catch this in  config.hpp ?

Yes, good thinking!

**Comment by hkaiser** [comment]
... or even better, in cmake at configure time.

**Comment by hkaiser** [comment]
A documentation note was added by #2143

**Comment by ktf** [comment]
indeed a note in the requirements and a find_boost required version would be nice. Thank you for the quick feedback.

**Comment by sithhell** [comment]
On 05/20/2016 08:02 AM, Giulio Eulisse wrote:
> indeed a note in the requirements and a find_boost required version
> would be nice. Thank you for the quick feedback.

There is a note in the documentation here:
http://stellar-group.github.io/hpx/docs/html/hpx/manual/build_system/prerequisites.html

I agree that giving an error when finding boost would be appropriate, 
however, it is hard to distinguish and figure out if you really have a 
problem. What you can detect is:
1) Are we running on OSX?
2) Which compiler
3) Which Boost version

The problematic part is 2). thread local works if you have your own 
vanilla clang version instead of the one that comes with xcode. That's 
why we didn't want to give an error in that case.

**Comment by ktf** [comment]
IMHO, you could simply ask for boost >= 1.61 on OSX and that's it. What made me miss the warning is that in the page you point to it says:

```
See below for an important limitation when using Boost V1.54.0.
```

which made me overlook the other rest of the page.

**Comment by sithhell** [comment]
Am 20.05.2016 10:20 vorm. schrieb "Giulio Eulisse" <notifications@github.com
>:
>
> IMHO, you could simply ask for boost >= 1.61 on OSX and that's it. What
made me miss the warning is that in the page you point to it says:

1.61 was only released very recently...

>
> See below for an important limitation when using Boost V1.54.0.

... I agree, the wording here is poor.

**Comment by K-ballo** [comment]
Wouldn't it suffice to check Boost version and lack of `thread_local` support?

**Comment by ktf** [comment]
Yes, I agree. A simple test for thread_local is probably the best.

**Comment by sithhell** [comment]
Good point! That's the solution, Thanks!
