### ISSUE TITLE
Simple receive_buffer example.

### ISSUE THREAD

**Issue by rasolca** [STEllAR-GROUP/hpx#2166]
Hi!
Is it possible to have a small example on how does the receive_buffer work?

**Comment by biddisco** [comment]
Raffaele, the main example is this one https://github.com/STEllAR-GROUP/hpx/blob/424334a0a36a56cbc2d9cd0a6db67030928d789d/examples/1d_stencil/1d_stencil_8.cpp but I'll create a simpler one. What is the data structure that you exchange between nodes - just a simple array of doubles, or is there a more complex type wrapped around it?

**Comment by biddisco** [comment]
Raffaele, the main example is this one https://github.com/STEllAR-GROUP/hpx/blob/424334a0a36a56cbc2d9cd0a6db67030928d789d/examples/1d_stencil/1d_stencil_8.cpp but I'll create a simpler one. What is the data structure that you exchange between nodes - just a simple array of doubles, or is there a more complex type wrapped around it?

**Comment by rasolca** [comment]
I exchange just a simple array of double or complex (which is also an array of doubles).

**Comment by hkaiser** [comment]
@rasolca Please see #2188 for the example you asked for. Please let us know if that resolves you issue.

**Comment by rasolca** [comment]
Yes, the example is what I was asking for. Thanks.
