### ISSUE TITLE
Fork Boost.Context

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2178]
Repeated problems with Boost.Context from various versions of Boost (notably 1.58, 1.60, and 1.61) are preventing HPX from being used on OSX. We should fork this library from Boost. V1.59 and integrate it with our build system and code infrastructure to avoid those issues and make HPX usable on OSX for all versions of Boost again.

**Comment by biddisco** [comment]
Might be of interest? https://github.com/septag/deboost.context
