### ISSUE TITLE
HPX MPI use incorrect

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2215]
In the CMakeLists for the MPI parcelport, variables such as MPI_CXX_LIBRARIES are used.
HPX does not use the C++ interface to MPI and therefore linking to MPI_CXX_LIBRARIES is incorrect.
It is sufficient to use the MPI_C_LIBRARIES and MPI_C_INCLUDE_PATH etc etc

**Comment by sithhell** [comment]
On 06/14/2016 12:46 PM, John Biddiscombe wrote:
> In the CMakeLists for the MP parcelport, variables such as
> MPI_CXX_LIBRARIES are used.
> HPX does not use the C++ interface to MPI and therefore linking to
> MPI_CXX_LIBRARIES is incorrect.
> It is sufficient to use the MPI_C_LIBRARIES and MPI_C_INCLUDE_PATH etc etc

Without linking against the CXX libraries, I got linker errors, that's
why I added it.

**Comment by hkaiser** [comment]
@biddisco What should we do about this? Is that still an issue?

**Comment by biddisco** [comment]
Linking the CXX_LIBRARIES is incorrect, so if @sithhell had errors it is most probably a problem with find_package(MPI) rather than anything we have done. It is also probable that more recent versions of cmake are less lilkely to exhibit this problem. 
I would suggest that we leave things alone until after a 1.0 release (unless we have additional bug reports prior to then) and then reassess the situation and possibly bump our cmake minimum requirement post 1.0
