### ISSUE TITLE
Extend migration to be usable with targets

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2233]
The concept of migration is currently limited to moving global objects between nodes. The same concept should be extended to be usable for moving global objects between targets (in the context of HPX.Compute). This - for instance - would enable moving global objects up and down the memory hierarchy, between NUMA domains, or from and to accelerator devices.

**Comment by msimberg** [comment]
Is this being worked on currently? Is this likely to be done for the next release?
