### ISSUE TITLE
Compilation error for partitioned vector in hpx_compute branch

### ISSUE THREAD

**Issue by atrantan** [STEllAR-GROUP/hpx#2241]
I get a compilation error when trying to build examples.compute.cuda.partitioned_vector. It seems to be in the case when HPX_HAVE_CXX11_STD_IS_TRIVIALLY_COPYABLE is not defined.

hpx/compute/cuda/transfer.hpp(161): error: namespace "hpx::traits" has no member "trivially_cuda_copyable_pointer_tag"

**Comment by hkaiser** [comment]
@atrantan This has been fixed (see 5a529a61538633bd92b1684b3c6859cb27a998ea).
