### ISSUE TITLE
hpx_0.9.99 make tests fail

### ISSUE THREAD

**Issue by buildhour** [STEllAR-GROUP/hpx#2266]
1. env
   - linux (kernel 4.1.15)
   - glibc 2.19
   - clang 3.7.1 + libstdc++ (gcc 4.9.3)
2. library
   - hwloc 1.11.3
   - gperftools 2.5  (--enable-minimal --enable-sized-delete --enable-dynamic-sized-delete-support)
   - openmpi 1.10.3 (--enable-cxx-exceptions --enable-ipv6 --enable-hwloc-pci)
   - hpx 0.9.99
3. test result
   99% tests passed, 2 tests failed out of 485
   The following tests FAILED:
         157 - tests.unit.components.launch_process (Timeout)
         410 - tests.unit.parallel.reduce_by_key (Failed)

**Comment by hkaiser** [comment]
@buildhour Thanks! These are know issues, we will fix them for the next release (in fact, the launch_process error was already fixed on master, iirc).  The test failures should not cause any problems in your code.

**Comment by hkaiser** [comment]
Those tests have been fixed for V1.0
