### ISSUE TITLE
Add inspect support to deprecate Boost.TypeTraits

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#2267]
We should deprecate the use of Boost.TypeTraits in favor of the facilities defined in the standard `type_traits` header. A proper inspect check needs to be implemented for that.

**Comment by K-ballo** [comment]
While doing so, it would be a good idea to update the `cxx11_std_type_traits` feature test accordingly.

**Comment by hkaiser** [comment]
> While doing so, it would be a good idea to update the  cxx11_std_type_traits  feature test accordingly.

What concretely did you have in mind for this?

**Comment by K-ballo** [comment]
> > While doing so, it would be a good idea to update the cxx11_std_type_traits feature test accordingly.
>
> What concretely did you have in mind for this?

For each trait flagged by the inspect check, or at least those used by HPX, add a corresponding entry to [cxx11_std_type_traits](https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/tests/cxx11_std_type_traits.cpp).
