### ISSUE TITLE
Arithmetic exception in executor static chunker

### ISSUE THREAD

**Issue by mcopik** [STEllAR-GROUP/hpx#2282]
While trying to reproduce the issue #2281 I've found another problem, an integer division by zero for static chunk size when called from a parallel fill.
Source code: https://gist.github.com/mcopik/d34318766bb8dc8404255026c47a28c1
CMake script: https://gist.github.com/mcopik/7515e467cbb97b8a6ea983167f305a62
GDB backtrace with the exception:
https://gist.github.com/mcopik/b8e0e0f3b1137a4d46b7015fc8ed255c

Am I doing something wrong? Built and executed with current master.

**Comment by sithhell** [comment]
On Freitag, 5. August 2016 10:57:21 CEST Marcin Copik wrote:
> While trying to reproduce the issue #2281 I've found another problem, an
> integer division by zero for static chunk size when called from a parallel
> fill. Source code:
> https://gist.github.com/mcopik/d34318766bb8dc8404255026c47a28c1 CMake
> script: https://gist.github.com/mcopik/7515e467cbb97b8a6ea983167f305a62 GDB
> backtrace with the exception:
> https://gist.github.com/mcopik/b8e0e0f3b1137a4d46b7015fc8ed255c
> 
> Am I doing something wrong?

How do I reproduce it? How did you run this code?

**Comment by mcopik** [comment]
Configure with cmake, build and execute on one thread (--hpx:threads=1) on my machine with 2 Xeon CPUs.
I've overriden CMAKE_PREFIX_PATH in CMakeLists to locate HPX's master build, provided in HPX_LOCATION.

**Comment by hkaiser** [comment]
The problem with your code is that you're trying to run HPX code without initializing the HPX runtime. I will make sure the corresponding functions in HPX will throw an exception in this case instead of silently ignoring this.
