### ISSUE TITLE
adjustments to parcel handling to support parcelports that do not need a connection cache

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2286]
This is a placeholder issue that I'm adding as I have a bunch of changes on the verbs PP branch I'm working on, that I'd like to merge into master first as they affect the layer above the PP itself.

The verbs PP does not need to have a connection cache, so in the parcelport_impl class we can bypass the get connection and queuing/dequeuing of some parcels and send them without certain checks.

**Comment by hkaiser** [comment]
This was fixed by merging #2291
