### ISSUE TITLE
Documentation for accumulator example is out of sync with changes to api

### ISSUE THREAD

**Issue by ShmuelLevine** [STEllAR-GROUP/hpx#2307]
While re-reading through the latest documentation, I came across the following excerpt in the Accumulator Example (http://stellar-group.github.io/hpx/docs/html/hpx/tutorial/examples/accumulator.html)

Synchronous: To invoke an action in a fully synchronous manner, we can simply call hpx::async<>().get() (e.g., create a future and immediately wait on it to be ready). Here's an example from the accumulator client class:

```
void add(argument_type arg)
{
    HPX_ASSERT(this->get_id());

    typedef server::accumulator::add_action action_type;
    action_type()(this->get_id(), arg);
}
```

There is no call here to the hpx::future member function .get().  This code has changed since the last time I remember seeing it (somewhere around 0.9.11).

**Comment by hkaiser** [comment]
@ShmuelLevine Was this fixed by merging #2309?

**Comment by ShmuelLevine** [comment]
Unfortunately not.  That PR was intended to fix some basic spelling errors and grammatical errors in the documentation itself -- I did not take on myself to correct any errors such as this in the code.

As to this issue itself - I'd be happy to help with the documentation if you could help me to better understand why code has changed from the older versions (around 0.9.11) to the present form.  I'd thought it might be related to the addition/integration of executors into the codebase.  Calling action_type()(args...) defaults to a synchronous/blocking executor -- which was not necessarily the case in earlier versions of the code.  

If you could help me to better understand the underlying design, I would be happy to do what I can to improve the documentation.

**Comment by hkaiser** [comment]
We have changed this construct:

    async(action_type(), id, ...).get();

to 

    action_type()(id, ...);

The latter is just a bit more readable, otherwise they are equivalent. 
If you however think that the former is ok as well (or even better), we can certainly change it back.

**Comment by msimberg** [comment]
Is this only a question of changing the description of the synchronous case in the example (not mentioning `async().get`)? Or has the API changed again in the meantime? If the former I can clean it up.
