### ISSUE TITLE
--hpx:print-bind doesn't work with --hpx:pu-step

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/hpx#2313]
--hpx:print-bind does not work with --hpx:pu-step. It would be nice if we had a diagnostic option to validate affinity settings that worked with --hpx:pu-step.

For reference, src/hpx_init.cpp line 602 is where we disable --hpx:print-bind for --hpx:pu-step (and I did try just disabling that error to confirm that --hpx:print-bind does not in fact work with --hpx:pu-step).

**Comment by hkaiser** [comment]
This problem has been introduced at the point when we made `--hpx:bind=balanced`  the default (#2180). This was done by defining a implied value for this command line option, essentially making it present always.
This leads to the issue that now `--hpx:pu-step` is unusable as it is not allowed to be used together with `--hpx:bind`.

The easiest workaround for now would be to revert the patch related to `--hpx:bind=balanced`.

**Comment by hkaiser** [comment]
@brycelelbach I think I know how to fix this and will try to get a PR ready asap.
