### ISSUE TITLE
Warning for requested/allocated thread discrepancy is printed twice.

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/hpx#2314]
E.g.

```
$ bin/future_overhead --futures=6400000 -t64
hpx::init: command line warning: --hpx:threads used when running with SLURM, requesting a larger number of threads (64) than cores have been assigned by SLURM (4), the application might not run properly.
hpx::init: command line warning: --hpx:threads used when running with SLURM, requesting a larger number of threads (64) than cores have been assigned by SLURM (4), the application might not run properly.
...
```

This happens because  handle_arguments() gets called twice in command_line_handling.cpp, once on the initial command line (before aliases) and once after aliases, etc have been processed. It's probably somewhat annoying to fix, but it would be nice to do so.

P.S. It would also be nice to have a way to disable this flag. On some systems I can't avoid triggering this error due to odd SLURM configurations, and it makes collecting data annoying because I have to filter those warnings out of my batch script outputs.

**Comment by hkaiser** [comment]
This shouldn't be difficult to fix. We solved similar issues in the past.

> P.S. It would also be nice to have a way to disable this flag. On some systems I can't avoid triggering this error due to odd SLURM configurations, and it makes collecting data annoying because I have to filter those warnings out of my batch script outputs.

We could use `std::cerr` instead...

**Comment by sithhell** [comment]
>
> P.S. It would also be nice to have a way to disable this flag. On some
systems I can't avoid triggering this error due to odd SLURM
configurations, and it makes collecting data annoying because I have to
filter those warnings out of my batch script outputs.

This is already possible with the `--hpx:ignore-batch-env` command line
switch.

**Comment by hkaiser** [comment]
> This is already possible with the `--hpx:ignore-batch-env` command line switch.

Not sure if this is what @brycelelbach is after.
