### ISSUE TITLE
Create generic histogram performance counter

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2327]
This could be done similarily to the statistics counter which calculates the mean of the values periodically extracted from any other counter.

**Comment by diehlpk** [comment]
@hkaiser  Could you please add a project description here https://github.com/STEllAR-GROUP/hpx/wiki/GSoC-2017-Project-Ideas#create-generic-histogram-performance-counter

**Comment by Sumit2318** [comment]
I have build HPX on my system.How to build the performance counter? Could you please help me how to start ?What should be my approach?

**Comment by hkaiser** [comment]
@Sumit2318 could we please continue this discussion on our mailing list (`hpx-users@stellar.cct.lsu.edu`)?

Once you have built HPX, all the performance counters are in place - those are part of HPX itself. Have you read the corresponding documentation about how to use them? If not, it might be a good idea to do that (see: http://stellar-group.github.io/hpx/docs/html/hpx/manual/performance_counters.html and all sub-sections of this).

**Comment by victor-ludorum** [comment]
Hello @hkaiser Sir, I am working on this issue and combining this project with **"Add more Arithmetic Performance Counters"** for the coming GSOC 2018. So, during the work, I have found a [histogram implementation](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/util/histogram.hpp) in the HPX. Hence, I am thinking to take the help of this code to implement **Histogram performance counter**. 
Thus, I have some confusion about this code. Hope you clear it.

1. First thing which I want to ask is about the insertion of values for bins. Is this [loop](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/util/histogram.hpp#L97) help to enter the data in the bins of the histogram.
2. Second thing What is this _extractor_ [here](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/util/histogram.hpp#L196) . Do we have to return this as a result after constructing histogram?
3. Third thing is [result](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/util/histogram.hpp#L137) , here we are getting the result in a pair of values. Do, I have to return the result in the same way ??

Please suggest !!
Thanks!!

**Comment by hkaiser** [comment]
> First thing which I want to ask is about the insertion of values for bins. Is this loop help to enter the data in the bins of the histogram.

The data is entered by invoking the operator()() on the histogram object (https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/util/histogram.hpp#L107)

> Second thing What is this extractor here . Do we have to return this as a result after constructing histogram?

You might want to familiarize yourself with the Boost.Accumulators library (http://www.boost.org/doc/libs/1_66_0/doc/html/accumulators.html). The extractor is the facility used by this library to access the data in a generic way.

> Third thing is result , here we are getting the result in a pair of values. Do, I have to return the result in the same way 

In order to represent values collected as a histogram you need two values for each of the histogram bins: the position of the bin and the number of values in that bin. 

We have created one histogram counter in HPX to collect various timings from the parcel coalescing module (`/coalescing/time/parcel-arrival-histogram`). The code for this counter is here: https://github.com/STEllAR-GROUP/hpx/blob/master/plugins/parcel/coalescing/coalescing_message_handler.cpp#L368 and here: https://github.com/STEllAR-GROUP/hpx/blob/master/plugins/parcel/coalescing/performance_counters.cpp.
This counter returns an array of values, where the first three values represent the three parameters used for the histogram followed by one value for each of the histogram buckets (see https://stellar-group.github.io/hpx/docs/html/hpx/manual/performance_counters/counters.html, at the very end).

The idea for the generic histogram counter would be to to collect histograms on top of an any other counter, very much like the other statistics counters. This histogram counter should expose the collected data in the same way as the existing `parcel-arrival-histogram` counter.

**Comment by victor-ludorum** [comment]
Thanks a lot @hkaiser sir!! I will study those files and then communicate with you if I got any problem.

**Comment by hkaiser** [comment]
Sounds like a plan to me.

**Comment by victor-ludorum** [comment]
@hkaiser Hello Sir!! I want to ask one thing, is there anything in HPX which has visual or pictorial representation. Actually, I am thinking (_for future plan_ ) that if it is possible to implement histogram pictorially so that it would be much easier to gather information from it. Also if it is possible Can you suggest some ideas to add in histogram performance counter .
Please suggest!!
Thanks!! 😊

**Comment by hkaiser** [comment]
> is there anything in HPX which has visual or pictorial representation. Actually, I am thinking (for future plan ) that if it is possible to implement histogram pictorially so that it would be much easier to gather information from it.

There is no pictorial representation for the histograms yet, at least nothing coherent. We've been using some python scripts to parse the generated output. Such a script would be a nice addition to your GSoC plan, I think.

>  Can you suggest some ideas to add in histogram performance counter . Please suggest!!

I'm not sure what you're looking for. The idea is to create a performance counter that produces a histogram from the results returned by invoking any other counter several times. The naming scheme for this counter would be similar to that of the other statistics counters., The histogram counter would invoke any other given counter at a predefined time interval, collect the data retrieved and expose it as its result (the histogram).

**Comment by victor-ludorum** [comment]
@hkaiser Hello Sir!! 
I have some doubts. 
How can I add a test to show the working of new **Histogram Performance counter**? Actually, in the **Arithmetic Performance Counter** implementation, I haven't seen any test file regarding that. Therefore, I have confusion. I have also searched for the other performance counters. But I haven't found much relevant just one or two like this [statistics_2666.cpp](https://github.com/STEllAR-GROUP/hpx/blob/master/tests/regressions/performance_counters/statistics_2666.cpp). 

One more thing as you have suggested that I have to implement it like ```/coalescing/time/parcel-arrival-histogram```. Can I use the idea or implementation strategy to implement it in the same way in Histogram Performance counter or I have to go with some new strategy. 
Sir, I have **done some work.** This is the link (https://github.com/victor-ludorum/hpx/pull/2). Please review it so that I can remove my some silly mistake. Then I will open a PR for the main HPX branch.

**Comment by hkaiser** [comment]
> ...  I haven't seen any test file regarding that

@victor-ludorum you're right, we don't have extensive tests for our performance counters. Feel free to come up with a new scheme to test those. 

> Can I use the idea or implementation strategy to implement it in the same way in Histogram Performance counter or I have to go with some new strategy.

Feel free to use what you see. Most probably you will have to modify things here and there to make it fit into your plans, however.

**Comment by victor-ludorum** [comment]
@hkaiser Thanks, Sir!! I have done some work. Please have a review if you got some time.  This is the link (https://github.com/victor-ludorum/hpx/pull/2).

**Comment by hkaiser** [comment]
@victor-ludorum yes, I have seen this. I think @msimberg has done a nice review and has put together a comprehensive list of comments for you to work on.

**Comment by victor-ludorum** [comment]
@hkaiser Okay Sir!! Thanks a lot!! I will follow yours and Simberg Sir advice.
Thanks once again!!
