### ISSUE TITLE
Enabling APEX causes link errors

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2342]
I get errors of this kind related to boost regex when I turn on APEX support in HPX

https://gist.githubusercontent.com/biddisco/5e081113df14bc76ed61afdfd47ebae7/raw/745baf6ddada9e71757a304bdac87282d4a025f1/gistfile1.txt

I suspect @khuck is the person to ask about this.

**Comment by khuck** [comment]
John -  Can you post the Cmake options you used? I haven't seen this problem. 

Also, are you using the latest HPX? There was a recent change to pull the most recent code from APEX that includes OTF2 support, which has been tested with HPX - but without the communication events.

**Comment by biddisco** [comment]
I'm using master from today. Rechecking everything because I turned off APEX and the link errors didn't go away, so maybe some other option I used is the problem.

**Comment by hkaiser** [comment]
@biddisco Please verify that libhpx.so is being linked against the correct version of the Boost.Regex library.

**Comment by biddisco** [comment]
Please accept my apologies - it turns out to be a problem that is caused when you allow HPX to set the build flags, if I explicity force CMAKE_CXX_FLAGS=-std=c++11 then things build ok, but if I do not use that flag, HPX must set some c++14 flags and the link problems appear - I would guess that there is some #define in boost that is causing problems because I tried building boost with c++14 and hpx with c++14, but that didn't work.

I will investigate this further when I have more time, for now I will close this issue.
