### ISSUE TITLE
Compile errors when using intel 17 beta (for KNL) on edison

### ISSUE THREAD

**Issue by pagrubel** [STEllAR-GROUP/hpx#2352]
compiler modules loaded: 
 intel/2017.beta.up2
gcc/4.9.3

output from cmake:
-- The CXX compiler identification is Intel 17.0.0.20160517
-- The C compiler identification is Intel 17.0.0.20160517
-- Check for working CXX compiler: /usr/common/software/intel/compilers_and_libraries_2017.0.064/linux/bin/intel64/icpc
-- Check for working CXX compiler: /usr/common/software/intel/compilers_and_libraries_2017.0.064/linux/bin/intel64/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working C compiler: /usr/common/software/intel/compilers_and_libraries_2017.0.064/linux/bin/intel64/icc
-- Check for working C compiler: /usr/common/software/intel/compilers_and_libraries_2017.0.064/linux/bin/intel64/icc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Native TLS is enabled.
-- Stack traces are enabled.
-- Compiling with the native toolset
-- Performing Test HPX_WITH_CXX11
-- Performing Test HPX_WITH_CXX11 - Success
-- Performing Test HPX_WITH_CXX11_ALIAS_TEMPLATES - Success
-- Performing Test HPX_WITH_CXX11_AUTO - Success
-- Performing Test HPX_WITH_CXX11_CONSTEXPR - Success
-- Performing Test HPX_WITH_CXX11_DECLTYPE - Success
-- Performing Test HPX_WITH_CXX11_DECLTYPE_N3276 - Success
-- Performing Test HPX_WITH_CXX11_SFINAE_EXPRESSION - Success
-- Performing Test HPX_WITH_CXX11_DEFAULTED_FUNCTIONS - Success
-- Performing Test HPX_WITH_CXX11_DELETED_FUNCTIONS - Success
-- Performing Test HPX_WITH_CXX11_EXPLICIT_CONVERSION_OPERATORS - Success
-- Performing Test HPX_WITH_CXX11_EXPLICIT_VARIADIC_TEMPLATES - Success
-- Performing Test HPX_WITH_CXX11_EXTENDED_FRIEND_DECLARATIONS - Success
-- Performing Test HPX_WITH_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS - Success
-- Performing Test HPX_WITH_CXX11_INLINE_NAMESPACES - Success
-- Performing Test HPX_WITH_CXX11_LAMBDAS - Success
-- Performing Test HPX_WITH_CXX11_NOEXCEPT - Success
-- Performing Test HPX_WITH_CXX11_NULLPTR - Success
-- Performing Test HPX_WITH_CXX11_RANGE_BASED_FOR - Success
-- Performing Test HPX_WITH_CXX11_RVALUE_REFERENCES - Success
-- Performing Test HPX_WITH_CXX11_SCOPED_ENUMS - Success
-- Performing Test HPX_WITH_CXX11_STATIC_ASSERT - Success
-- Performing Test HPX_WITH_CXX11_VARIADIC_MACROS - Success
-- Performing Test HPX_WITH_CXX11_VARIADIC_TEMPLATES - Success
-- Performing Test HPX_WITH_CXX11_ARRAY - Success
-- Performing Test HPX_WITH_CXX11_CHRONO - Success
-- Performing Test HPX_WITH_CXX11_CSTDINT - Success
-- Performing Test HPX_WITH_CXX11_STD_INITIALIZER_LIST - Success
-- Performing Test HPX_WITH_CXX11_IS_BIND_EXPRESSION - Success
-- Performing Test HPX_WITH_CXX11_IS_PLACEHOLDER - Success
-- Performing Test HPX_WITH_CXX11_IS_TRIVIALLY_COPYABLE - Failed
-- Performing Test HPX_WITH_CXX11_LOCK_GUARD - Success
-- Performing Test HPX_WITH_CXX11_REFERENCE_WRAPPER - Success
-- Performing Test HPX_WITH_CXX11_SHARED_PTR - Success
-- Performing Test HPX_WITH_CXX11_TO_STRING - Success
-- Performing Test HPX_WITH_CXX11_UNIQUE_LOCK - Success
-- Performing Test HPX_WITH_CXX11_UNIQUE_PTR - Success
-- Performing Test HPX_WITH_CXX11_UNORDERED_MAP - Success
-- Performing Test HPX_WITH_CXX11_UNORDERED_SET - Success
-- Performing Test HPX_WITH_CXX11_TYPE_TRAITS - Failed
-- Performing Test HPX_WITH_CXX14_CONSTEXPR - Failed
-- Performing Test HPX_WITH_CXX14_LAMBDAS - Failed
-- Performing Test HPX_WITH_CXX14_INTEGER_SEQUENCE - Failed
-- Performing Test HPX_WITH_CXX14_IS_FINAL - Failed
-- Performing Test HPX_WITH_CXX14_IS_NULL_POINTER - Success
-- Performing Test HPX_WITH_CXX14_RESULT_OF_SFINAE - Success
-- Performing Test HPX_WITH_CXX1Y_EXPERIMENTAL_OPTIONAL - Failed
-- Performing Test HPX_WITH_MM_PREFECTH - Success
-- Performing Test HPX_WITH_UNISTD_H - Success
-- Performing Test HPX_WITH_CXX_FLAG_WALL
-- Performing Test HPX_WITH_CXX_FLAG_WALL - Success
-- Performing Test HPX_WITH_C_FLAG_WALL
-- Performing Test HPX_WITH_C_FLAG_WALL - Success
-- Performing Test HPX_WITH_Fortran_FLAG_WALL
-- Performing Test HPX_WITH_Fortran_FLAG_WALL - Success
-- Performing Test HPX_WITH_CXX_FLAG_WEXTRA
-- Performing Test HPX_WITH_CXX_FLAG_WEXTRA - Success
-- Performing Test HPX_WITH_C_FLAG_WEXTRA
-- Performing Test HPX_WITH_C_FLAG_WEXTRA - Success
-- Performing Test HPX_WITH_Fortran_FLAG_WEXTRA
-- Performing Test HPX_WITH_Fortran_FLAG_WEXTRA - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS - Failed
-- "-Wno-unused-local-typedefs" not available for language CXX.
-- Performing Test HPX_WITH_C_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HPX_WITH_C_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS - Failed
-- "-Wno-unused-local-typedefs" not available for language C.
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_UNUSED_LOCAL_TYPEDEFS - Failed
-- "-Wno-unused-local-typedefs" not available for language Fortran.
-- Performing Test HPX_WITH_CXX_FLAG_WNO_STRICT_ALIASING
-- Performing Test HPX_WITH_CXX_FLAG_WNO_STRICT_ALIASING - Success
-- Performing Test HPX_WITH_C_FLAG_WNO_STRICT_ALIASING
-- Performing Test HPX_WITH_C_FLAG_WNO_STRICT_ALIASING - Success
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_STRICT_ALIASING
-- Performing Test HPX_WITH_Fortran_FLAG_WNO_STRICT_ALIASING - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SIGN_PROMO
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SIGN_PROMO - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_ATTRIBUTES
-- Performing Test HPX_WITH_CXX_FLAG_WNO_ATTRIBUTES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_CAST_ALIGN
-- Performing Test HPX_WITH_CXX_FLAG_WNO_CAST_ALIGN - Failed
-- "-Wno-cast-align" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_PARAMETER
-- Performing Test HPX_WITH_CXX_FLAG_WNO_UNUSED_PARAMETER - Success
-- Performing Test HPX_WITH_CXX_FLAG_WFORMAT_2
-- Performing Test HPX_WITH_CXX_FLAG_WFORMAT_2 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_FORMAT_NONLITERAL
-- Performing Test HPX_WITH_CXX_FLAG_WNO_FORMAT_NONLITERAL - Failed
-- "-Wno-format-nonliteral" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WINIT_SELF
-- Performing Test HPX_WITH_CXX_FLAG_WINIT_SELF - Success
-- Performing Test HPX_WITH_CXX_FLAG_WDOUBLE_PROMOTION
-- Performing Test HPX_WITH_CXX_FLAG_WDOUBLE_PROMOTION - Failed
-- "-Wdouble-promotion" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WCAST_QUAL
-- Performing Test HPX_WITH_CXX_FLAG_WCAST_QUAL - Success
-- Performing Test HPX_WITH_CXX_FLAG_WCAST_ALIGN
-- Performing Test HPX_WITH_CXX_FLAG_WCAST_ALIGN - Failed
-- "-Wcast-align" not available for language CXX.
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_TRAMPOLINES
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_TRAMPOLINES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_PARENTHESES
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_PARENTHESES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_REORDER
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_REORDER - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_RETURN_TYPE
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_RETURN_TYPE - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SEQUENCE_POINT
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SEQUENCE_POINT - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_UNINITIALIZED
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_UNINITIALIZED - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_FORMAT
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_FORMAT - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_MISSING_BRACES
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_MISSING_BRACES - Success
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SIGN_COMPARE
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_SIGN_COMPARE - Success
-- Performing Test HPX_WITH_CXX_FLAG_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HPX_WITH_CXX_FLAG_FDIAGNOSTICS_SHOW_OPTION - Failed
-- "-fdiagnostics-show-option" not available for language CXX.
-- Performing Test HPX_WITH_C_FLAG_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HPX_WITH_C_FLAG_FDIAGNOSTICS_SHOW_OPTION - Failed
-- "-fdiagnostics-show-option" not available for language C.
-- Performing Test HPX_WITH_Fortran_FLAG_FDIAGNOSTICS_SHOW_OPTION
-- Performing Test HPX_WITH_Fortran_FLAG_FDIAGNOSTICS_SHOW_OPTION - Failed
-- "-fdiagnostics-show-option" not available for language Fortran.
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_VLA
-- Performing Test HPX_WITH_CXX_FLAG_WERROR_VLA - Success
-- Performing Test HPX_WITH_C_FLAG_WERROR_RETURN_TYPE
-- Performing Test HPX_WITH_C_FLAG_WERROR_RETURN_TYPE - Success
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SYNC_NAND
-- Performing Test HPX_WITH_CXX_FLAG_WNO_SYNC_NAND - Failed
-- "-Wno-sync-nand" not available for language CXX.
-- Performing Test HPX_WITH_C_FLAG_WNO_SYNC_NAND
-- Performing Test HPX_WITH_C_FLAG_WNO_SYNC_NAND - Failed
-- "-Wno-sync-nand" not available for language C.
-- Performing Test WITH_LINKER_FLAG_WL__Z_DEFS
-- Performing Test WITH_LINKER_FLAG_WL__Z_DEFS - Success
-- Performing Test HPX_WITH_CXX_FLAG_FVISIBILITY_HIDDEN
-- Performing Test HPX_WITH_CXX_FLAG_FVISIBILITY_HIDDEN - Success
-- Performing Test HPX_WITH_C_FLAG_FVISIBILITY_HIDDEN
-- Performing Test HPX_WITH_C_FLAG_FVISIBILITY_HIDDEN - Success
-- Performing Test HPX_WITH_Fortran_FLAG_FVISIBILITY_HIDDEN
-- Performing Test HPX_WITH_Fortran_FLAG_FVISIBILITY_HIDDEN - Success
-- Performing Test WITH_LINKER_FLAG_FVISIBILITY_HIDDEN
-- Performing Test WITH_LINKER_FLAG_FVISIBILITY_HIDDEN - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD1170
-- Performing Test HPX_WITH_CXX_FLAG_WD1170 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD858
-- Performing Test HPX_WITH_CXX_FLAG_WD858 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD1098
-- Performing Test HPX_WITH_CXX_FLAG_WD1098 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD488
-- Performing Test HPX_WITH_CXX_FLAG_WD488 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD2203
-- Performing Test HPX_WITH_CXX_FLAG_WD2203 - Success
-- Performing Test HPX_WITH_CXX_FLAG_WD2536
-- Performing Test HPX_WITH_CXX_FLAG_WD2536 - Success
-- Performing Test HPX_WITH_RDTSC - Failed
-- Performing Test HPX_WITH_RDTSCP - pre-set to ON
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   chrono
--   date_time
--   filesystem
--   program_options
--   regex
--   system
--   thread
--   context
--   random
--   atomic
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Found TCMalloc: /project/projectdirs/m888/wash/development/gperftools-2.5/INSTALL_ALL/lib/libtcmalloc_minimal.so  
-- Using tcmalloc allocator.
-- Found Hwloc: /global/homes/w/wash/install/lib/libhwloc.so  
-- Found Git: /usr/common/software/git/2.4.6/bin/git (found version "2.4.6") 
-- GIT commit is 57abda091cdeccf2d81154cc1a74664bf83f979d.
-- Found PythonInterp: /usr/common/software/python/2.7.9/bin/python (found version "2.7.9") 

compile errors for make core (abbreviated):
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[ 84%] Building CXX object src/CMakeFiles/hpx.dir/hpx_main_argc_argv.cpp.o
[ 84%] Building CXX object src/CMakeFiles/hpx.dir/hpx_main_variables_map.cpp.o
[ 84%] Building CXX object src/CMakeFiles/hpx.dir/hpx_user_main.cpp.o
[ 84%] Building CXX object src/CMakeFiles/hpx.dir/hpx_user_main_argc_argv.cpp.o
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
[ 84%] Building CXX object src/CMakeFiles/hpx.dir/hpx_main_winsocket.cpp.o
[ 84%] Building CXX object src/CMakeFiles/hpx.dir/util/lightweight_test.cpp.o
[ 84%] Building CXX object src/CMakeFiles/hpx.dir/main.cpp.o
remark #11074: Inlining inhibited by limit max-size 
remark #11074: Inlining inhibited by limit max-total-size 
remark #11076: To get full report use -qopt-report=4 -qopt-report-phase ipo
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/access.hpp(33): error: no instance of overloaded function "hpx::serialization::serialize" matches the argument list
            argument types are: (hpx::serialization::input_archive, hpx::threads::mask_type, int)
              serialize(ar, t, 0);
              ^
/global/homes/p/pagrubel/hpx/hpx/util/bind_action.hpp(342): note: this candidate was rejected because function is not visible
      void serialize(
           ^
/global/homes/p/pagrubel/hpx/hpx/util/bind_action.hpp(333): note: this candidate was rejected because function is not visible
      void serialize(
           ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/map.hpp(116): note: this candidate was rejected because function is not visible
          void serialize(output_archive& ar,
               ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/map.hpp(98): note: this candidate was rejected because function is not visible
          void serialize(input_archive& ar, std::map<Key, Value, Comp, Alloc>& t, unsigned)
               ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/map.hpp(88): note: this candidate was rejected because function is not visible
          void serialize(output_archive& ar, const std::pair<Key, Value>& t, unsigned)
               ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/map.hpp(78): note: this candidate was rejected because function is not visible
          void serialize(input_archive& ar, std::pair<Key, Value>& t, unsigned)
               ^
/global/homes/p/pagrubel/hpx/hpx/runtime/actions/basic_action.hpp(762): note: this candidate was rejected because function is not visible
      void serialize(
           ^
/global/homes/p/pagrubel/hpx/hpx/util/serialize_exception.hpp(54): note: this candidate was rejected because function is not visible
      HPX_SERIALIZATION_SPLIT_FREE(boost::exception_ptr);
      ^
/global/homes/p/pagrubel/hpx/hpx/util/serialize_exception.hpp(54): note: this candidate was rejected because function is not visible
      HPX_SERIALIZATION_SPLIT_FREE(boost::exception_ptr);
      ^
/global/homes/p/pagrubel/hpx/hpx/runtime/components/client_base.hpp(694): note: this candidate was rejected because function is not visible
      void serialize(Archive& ar,
           ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/vector.hpp(141): note: this candidate was rejected because function is not visible
      void serialize(output_archive & ar, const std::vector<T, Allocator> & v,
           ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/vector.hpp(126): note: this candidate was rejected because function is not visible
      void serialize(output_archive & ar, const std::vector<bool, Allocator> & v,
           ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/vector.hpp(83): note: this candidate was rejected because function is not visible
      void serialize(input_archive & ar, std::vector<T, Allocator> & v, unsigned)
           ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/vector.hpp(63): note: this candidate was rejected because function is not visible
      void serialize(input_archive & ar, std::vector<bool, Allocator> & v, unsigned)
           ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/array.hpp(105): note: this candidate was rejected because function is not visible
      void serialize(Archive& ar, std::array<T,N>& a, const unsigned int /* version */)
           ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/array.hpp(97): note: this candidate was rejected because function is not visible
      void serialize(Archive& ar, boost::array<T,N>& a, const unsigned int /* version */)
           ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/string.hpp(35): note: this candidate was rejected because function is not visible
      void serialize(output_archive & ar, const std::basic_string<Char, CharTraits,
           ^
/global/homes/p/pagrubel/hpx/hpx/runtime/serialization/string.hpp(19): note: this candidate was rejected because function is not visible
      void serialize(input_archive & ar, std::basic_string<Char, CharTraits,
           ^
/global/homes/p/pagrubel/hpx/hpx/lcos/future.hpp(1362): note: this candidate was rejected because at least one template argument could not be deduced
      void serialize(Archive& ar, ::hpx::lcos::shared_future<T>& f, unsigned version)
           ^
/global/homes/p/pagrubel/hpx/hpx/lcos/future.hpp(1355): note: this candidate was rejected because at least one template argument could not be deduced

**Comment by hkaiser** [comment]
This is (indirectly) caused by the `-DHPX_WITH_MAX_CPU_COUNT=N`, where N > 64. In this case the `mask_type` is not a `uint64_t` anymore, but either a `std::bitset` or a `boost::dynamic_bitmask`. These types require to include the corresponding serialization support, which apparently is currently missing.
