### ISSUE TITLE
failed to insert console_print_action into typename_to_id_t registry

### ISSUE THREAD

**Issue by timbiedert** [STEllAR-GROUP/hpx#2357]
Just did a fresh compile of the current master branch on Arch Linux (default settings in CMake + MPI parcelport enabled).  

When running my application (or hello_world or fibonacci example), I get the following error:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hpx::exception> >'
  what():  failed to insert console_print_action into typename_to_id_t registry: HPX(invalid_status)
```

Interestingly, my previously installed version (also built from master branch,  maybe 1-2 months ago) worked fine.

**Comment by sithhell** [comment]
I'll look into it. None of our tests show that failure. Could you check
with ldd if you didn't accidentally picked up the wrong library?

**Comment by hkaiser** [comment]
This sounds like as if there was a stale binary found somewhere during startup. This error means that an id is registered twice which can happen only if a module is loaded twice.

**Comment by timbiedert** [comment]
It seems like this was indeed the problem. I cleared everything HPX-related from /usr/local and did a fresh compile and install. Now it works, thank you!

My original goal was to have both a release and a debug installation in /usr/local. So this is not recommended?

**Comment by hkaiser** [comment]
> My original goal was to have both a release and a debug installation in /usr/local. So this is not recommended? 

I thought it was possible to have both in the same spot. Looks like we introduced a regression here. So for now, please try to avoid installing several versions of HPX in the same location. 

See #2358 to track the status of this.

**Comment by timbiedert** [comment]
I can confirm this seems to be the case. 
Again, I also compiled release mode and installed to /usr/local next to the previous debug installation.  Now I get the `failed to insert console_print_action into typename_to_id_t registry` again.
