### ISSUE TITLE
Make all of HPX ABI stable

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2371]
Mixing build types between applications and HPX currently causes strange errors. We should make HPX itself ABI stable to avoid these issues.

 Here is a list of places to look at:
- [ ] `threads::thread_init_data`
- [ ] types and functions related to the lock verification
- [ ] thread local data (see `HPX_WITH_THREAD_LOCAL_STORAGE`) (see #2375)

**Comment by dhollman** [comment]
Or just an error other than a segfault would be fine 👍 :-)

**Comment by K-ballo** [comment]
It'd be enough to make the ABI consistent across build types, making it stable seems overkill at this point.

**Comment by sithhell** [comment]
One big problem is also that `HPX_DEBUG` defines end up in the API.

**Comment by biddisco** [comment]
just fyi. for the tutorial examples I put this in the cmake 
https://github.com/STEllAR-GROUP/tutorials/blob/master/examples/CMakeLists.txt#L50-L58
