### ISSUE TITLE
BOOST_ROOT paths are not used at link time

### ISSUE THREAD

**Issue by BryantLam** [STEllAR-GROUP/hpx#2396]
This issue was observed with HPX release 0.9.99 and git commit 88af985.

On my system, there are some older Boost libraries installed in /usr/lib64, so I built Boost 1.61.0 in my home directory and used `BOOST_ROOT` at cmake-time to reference it.

At compile time, the `BOOST_ROOT` path is correctly used as `-isystem $BOOST_ROOT/include`. However, at link time, the Boost libraries are referenced (e.g., `-lboost_system`) but the path is not used at all.

The end result creates cryptic undefined-reference linking errors because the older Boost libraries are being used from /usr/lib64. Setting `LIBRARY_PATH=$BOOST_PATH/lib` does not get around this issue because /usr/lib64 is searched before `LIBRARY_PATH` is:
```
gcc --print-search-dirs | tr ':' '\n'
```

I would have expected something like ~~`-L$BOOST_ROOT/lib`~~ an absolute path to the `$BOOST_PATH/lib/<lib.so>` at link time.

**Comment by BryantLam** [comment]
This issue does not occur when `HPX_WITH_STATIC_LINKING=ON`.

**Comment by hkaiser** [comment]
Adding `-DBOOST_LIBRARYDIR=<your_boost_library_dir>` to the cmake command line should fix the issue.

**Comment by BryantLam** [comment]
Unfortunately, setting `BOOST_LIBRARYDIR` did not work. Using `-DBoost_DEBUG:BOOL=ON`, I was able to verify Boost paths were detected correctly.

I noticed that during link time, the last argument is an `-rpath` list that includes jemalloc (so at least that one was detected correctly), but Boost is not in the list. Setting `-DBoost_NO_SYSTEM_PATHS:BOOL=ON` at cmake-time did not help.

This issue may be a problem with cmake/HPX_SetupBoost.cmake. Even if it is not, the general guidance is to not use `LINK_DIRECTORIES()` anymore [[1]](http://cmake.3232098.n2.nabble.com/LINK-DIRECTORIES-td3389697.html)[[2]](http://cmake.3232098.n2.nabble.com/Problem-with-LINK-DIRECTORIES-td6992023.html).

**Comment by sithhell** [comment]
We use target link libraries, which should do the job just fine.
Do you have the environment variables CPATH or CPLUS_INCLUDE_PATH set? If
yes, for some reason, the FindBoost.cmake script doesn't set the path to
the libraries correctly which leads to the link failures you mentioned.
I believe the modulefiles from easybuild do this. There is not a lot we can
do about it there. I don't remember if adding the correct path to
LIBRARY_PATH solves the problem.

**Comment by BryantLam** [comment]
Thanks for pointing me in the right direction. It turns out LIBRARY_PATH is the problem. I tested by setting CPATH but omitting to set LIBRARY_PATH.

My best-effort explanation is that CMake asks the compiler for system library paths (the compiler will then check LIBRARY_PATH) and CMake will strip the absolute path off of the libraries that the compiler can find in a "system path".

References
- [CMake mailing-list thread](https://cmake.org/pipermail/cmake/2011-June/044828.html)
- [CMake 2.6 wiki: Linking to System Libraries](https://cmake.org/Wiki/CMake_2.6_Notes#Linking_to_System_Libraries)
- [CMake 3.0 doc: Imported Targets](https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#imported-targets)

The resolution from the references is to use imported targets for `target_link_libraries()` on all external libraries from the project. This forces CMake to use an absolute path for the libraries in the event that the user has a configuration where there are conflicting libraries in a system path and a custom path and LIBRARY_PATH is set.

**Comment by hkaiser** [comment]
I assume we can close this now. Thanks for your analysis!

**Comment by BryantLam** [comment]
More information here: [CMP0060](https://cmake.org/cmake/help/v3.3/policy/CMP0060.html)

I don't think this issue should be closed. The CMake files in HPX should change to handle this case.

Specifically going forward, CMP0060=NEW seems like an easy fix, but I'm unsure of what impact it has to HPX's backwards compatibility. Also, it does not solve the issue for users using CMake versions less than 3.3, but that problem will solve itself over time.

**Comment by hkaiser** [comment]
Would you have a suggestion on how this could be 'fixed'. The investigations we have done so far all pointed into the direction of a problem in cmake itself. So, any ideas or PRs would be more than welcome.

**Comment by BryantLam** [comment]
Continuing discussion in PR #2400 and PR #2401. Thanks!

**Comment by biddisco** [comment]
With newer versions of hpx/boost, the correct settings should be
```
 -DBOOST_ROOT=${HOME}/apps/santis/boost-1_59_0 \
 -DBoost_INCLUDE_DIR=${HOME}/apps/santis/boost-1_59_0/include/boost-1_59 \
 -DBoost_LIBRARY_DIR=${HOME}/apps/santis/boost-1_59_0/lib \
```
With paths adjusted to match the correct location for the boost install.

could @BryantLam try these and see if the original problem goes away?

**Comment by BryantLam** [comment]
Respectfully, `Boost_INCLUDE_DIR` and `Boost_LIBRARY_DIR` should not be set by the user. Those are return variables set by the FindBoost.cmake package script included with CMake.

I did give it a shot though and set these variables:
```
-DBOOST_ROOT=<root>
-DBOOST_INCLUDEDIR=<root>/include \
-DBOOST_LIBRARYDIR=<root>/lib \
-DBoost_INCLUDE_DIR=<root>/include \
-DBoost_LIBRARY_DIR=<root>/lib
```
The result was the same; HPX fails to link. The `hpx` target (libhpx.so) is trying to link implicitly.

**Comment by biddisco** [comment]
My bad. I was looking through some of my scripts for different machines and found those in there for one of them.
