### ISSUE TITLE
gcc + nvcc fails to compile code that uses partitioned_vector 

### ISSUE THREAD

**Issue by atrantan** [STEllAR-GROUP/hpx#2418]
Got a strange error when trying to compile the example partitioned_vector.cu

> /usr/include/c++/4.9/bits/stl_pair.h(128) (col. 17): error: calling a __host__ function("boost::intrusive_ptr< ::hpx::threads::thread_data> ::intrusive_ptr") from a __device__ function("std::pair< ::hpx::threads::thread_state_enum,  ::boost::intrusive_ptr< ::hpx::threads::thread_data> > ::pair") is not allowed

Apparently the error points to the move constructor of std::pair that is defined like here:
`constexpr pair(pair&&) = default;`
nvcc seems to consider this constructor as a `__device__` constructor and not `__host__` or `__host__ __device__`

**Comment by hkaiser** [comment]
@atrantan Is this still a problem?

**Comment by atrantan** [comment]
Yes

**Comment by hkaiser** [comment]
This has been resolved on master
