### ISSUE TITLE
Seg fault running octo-tiger with latest HPX commit

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#2427]
When running Octotiger with the current master, 4007f0619c33ecd2c1ffa5282d1444ab1bd3bb3e, I get the following error: https://gist.github.com/dmarce1/ea432fb28773e590950e90b136ce1e78

And the following stack trace: https://gist.github.com/dmarce1/6feca10a46d4cdd6602133a98ad4364a

**Comment by hkaiser** [comment]
@dmarce1 I'm not able to reproduce this. Could you please be more specific on how you built HPX and OctoTiger, and how you ran the application?

**Comment by dmarce1** [comment]
For both HPX and Octotiger I am using GNU C++ 5.4.0

I built HPX using:
cmake    -DCMAKE_BUILD_TYPE=release                                                                                                             \
      -DHPX_WITH_PARCELPORT_MPI=ON  -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ \
      -DCMAKE_INSTALL_PREFIX="/usr/local/packages/hpx/"                                   \
      -DHPX_WITH_MALLOC=custom \
      -DHPX_WITH_HWLOC=ON                                                \
      -DHPX_WITH_EXAMPLES=OFF \
      -DHPX_WITH_TESTS=OFF -DHPX_WITH_DATAPAR_VC=Off -DVc_ROOT=/opt/Vc/\
      ~/code/hpx

I build octotiger using:
cmake -DCMAKE_PREFIX_PATH=/usr/local/packages/hpx/ $1  \
      -DCMAKE_CXX_COMPILER="g++"                                              \
      -DCMAKE_C_COMPILER="gcc"                                                 \
      -DCMAKE_C_FLAGS="-O2 -g"                                \
      -DCMAKE_CXX_FLAGS="-O2 -g"  \
      -DOCTOTIGER_WITH_GRAV_PAR=OFF

**Comment by dmarce1** [comment]
I am not getting the seg fault now. Only difference I can think of is I removed the HPX install entirely before building. Must have been a stale binary?
