### ISSUE TITLE
Buildbot display inadequate

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2428]
By default, I open the console view of buildbot http://rostam.cct.lsu.edu/console and see an overview of the build status, unfortunately, what I do not see is the true state of the repository. The cdash dashboard http://cdash.cscs.ch/index.php?project=HPX&date=2016-12-14 shows me very clearly (and instantly) that nearly all tests are failing. To find this information in the buildbot display requires quite a lot of clicking (the waterfall view has the essentials, but it is so big you cannot see it without scrolling through all the results).

Since sunday/monday, nearly all tests are failing and the buildbot display shows 'warnings' as the status for most. If tests fail, then in my view buildbot should show red and display a state of fail.

I would like to see build/update status submitted to cdash as well as tests results because it presents the data in a much more easy to scan format.

I believe the buildbot console is contributing to a persistent 'bad perception' of the state of HPX. My reason being that when I see 'warnings' I am not very concerned and pay small attention to it (and allow myself to pull/merge into my local work), when I see fail, I am concerned and might spend time trying to fix or at least investigate the tests before merging master into my work.

Looking back through dashboard results, I have to go back to June before I can find a green status where all machines passed their tests. The current state of HPX is shocking, I believe buidbot is contributing to this problem by being
a) Not very good at displaying results
b) not accepting contributions from machines outside LSU, so when rostam/hermione has problems, the repo is effectively 'untested'

(A nice daily status ought to look something like https://open.cdash.org/index.php?project=VTK&date=2016-12-14 it is very clear when things go wrong)

**Comment by hkaiser** [comment]
@biddisco I couldn't agree more. 

AFAIK, our buildbot setup already submits the results to some dashboard (http://cdash.cscs.ch/submit.php?project=HPX") . Not sure whether that works or not, I have never checked.

**Comment by biddisco** [comment]
@hkaiser yes it does, (the correct link is in my previous comment). It is because I was looking at the CSCS dashboard and seeing all the test fails that I wanted to draw attention to the inadequacies of the buildbot display.

**Comment by msimberg** [comment]
I'm going to go ahead and close this as we have a lot our testing now on cdash/pycicle.

However, I remember seeing a discussion about the colors used on buildbot. Would it be possible to change the colors to red on failed unit tests (compile and runtime)?
