### ISSUE TITLE
Mismatch between #if/#endif and namespace scope brackets in this_thread_executers.hpp

### ISSUE THREAD

**Issue by brandon-kohn** [STEllAR-GROUP/hpx#2442]
https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/executors/this_thread_executors.hpp

Note that the namespaces are declared inside a #if/#endif construct but the closing brackets are outside any such preprocessor scope.

**Comment by hkaiser** [comment]
Thanks! Would you mind preparing a patch for this?

**Comment by brandon-kohn** [comment]
Sure :), I'll push the namespaces into #if/#endif scope.

**Comment by brandon-kohn** [comment]
Here's a (hastily put together and untested) patch.
[issue_2442.zip](https://github.com/STEllAR-GROUP/hpx/files/685274/issue_2442.zip)

**Comment by hkaiser** [comment]
@brandon-kohn Thanks for this. Could you turn that into a 'real' pull request here on github, please? Also, I think it would be sufficient to move the `#endif` [here](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/executors/this_thread_executors.hpp#L133) to the end of the file.

**Comment by brandon-kohn** [comment]
Done and done, hopefully I got the pull request correct. This is my first time collaborating through github in this way; so please bear with me.

**Comment by hkaiser** [comment]
Yes, all is well. For the requested changes, just keep pushing commits to the same branch it will show up on the pull request. Thanks!

**Comment by hkaiser** [comment]
This has been fixed by merging #2443
