### ISSUE TITLE
Re-implement hpx::util::unwrapped

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2456]
Our helper facility `hpx::util::unwrapped` exposes a couple of undesired problems (see for instance #1404, #1400). A (partial) re-implementation/refactoring could help solving these issues.

**Comment by diehlpk** [comment]
@hkaiser Could you please add a project description here https://github.com/STEllAR-GROUP/hpx/wiki/GSoC-2017-Project-Ideas
