### ISSUE TITLE
nvcc issue because -std=c++11 appears twice

### ISSUE THREAD

**Issue by atrantan** [STEllAR-GROUP/hpx#2489]
Got this compilation error `nvcc fatal   : redefinition of argument 'std'` when compiling cuda examples with nvcc. I think it is related to that commit 11e29e0f98dc776fb3d2babc3ebd269974b55a9f

**Comment by biddisco** [comment]
hpx adds -std=c++11 to your flags, so you must not manully add it anywhere. The commit 11e29e0f98dc776fb3d2babc3ebd269974b55a9f does the same for the installed version, so if you have added -std=c++11 anywhere, then you should remove it. The c++ compiler doesn't mind if you add it twice, but nvcc does. it's very annoying. I think the commit is correct, but if you've got problems then please suggest a fix.

**Comment by atrantan** [comment]
I'm not sure but when you are in the hpx build tree`hpx_add_target_compile_option(${CXX_FLAG})` in file https://github.com/STEllAR-GROUP/hpx/blob/master/CMakeLists.txt line 945 is already putting the flag. Out of the hpx build tree (ex : when using an installed hpx), this flag disappears. Was the reason why ${CXX_FLAG} has been added in https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/templates/HPXConfig.cmake.in and without disturbing the C++ compilation as it only touches nvcc flags

**Comment by atrantan** [comment]
@biddisco Convinced?
