### ISSUE TITLE
nvcc / cuda clang issue due to a missing -DHPX_WITH_CUDA flag 

### ISSUE THREAD

**Issue by atrantan** [STEllAR-GROUP/hpx#2500]
Got a error due to empty definitions of `HPX_HOST`, `HPX_DEVICE`, and `HPX_HOST_DEVICE` when compiling example cuda codes that are in the build tree. The reason is a missing flag `-DHPX_WITH_CUDA` that is now required since commit 80277b9c3db29f5ff2bdfa7bac2196baf0b33876

**Comment by hkaiser** [comment]
@atrantan What do you suggest?

**Comment by atrantan** [comment]
My suggestion is just to use `add_hpx_target_compile_option()`. Done in 5fa209426f48c0672be5d81052806cd866718a74

**Comment by hkaiser** [comment]
This has been resolved on master (see #2549 et.al.)
