### ISSUE TITLE
Linking errors in hwloc_topology

### ISSUE THREAD

**Issue by mcopik** [STEllAR-GROUP/hpx#2509]
I have been able to repeat issue #2410. Although the fix proposed there by @hkaiser allows to build library but example transpose_block_numa fails due to missing references to `hpx::threads::hwloc_topology` ctor and dtor. The problem can be reproduced on OpenMPI full installation where all hwloc headers are present. The bug is caused by their lowercase rename macro `hwloc_topology`, as described [here](https://github.com/open-mpi/hwloc/issues/229). I have confirmed it with:

```
nm -gC lib/libhpx.so | grep hwloc_topology
0000000000752d90 T hpx::threads::opal_hwloc191_hwloc_topology::opal_hwloc191_hwloc_topology()
```

Right now I have solved the problem by manually undefining the macro after each inclusion of hwloc.h. I doubt they're going to fix it, hwloc has dozens of lowercase macros defining their API. If current solution is not reliable enough, I can rename the class and open a pull request.

**Comment by hkaiser** [comment]
I think the best would be to rename our type `hpx::threads::hwloc_topology` to something not conflicting with any of the macros used by the hwloc library (for instance: `hpx::threads::hwloc_topology_info`).

**Comment by mcopik** [comment]
Hartmut, I got a response from OpenMPI devs and according to them, those headers should never leak into libraries using hwloc. In their opinion, it is a bug in their build system or an improper installation of OpenMPI. I just opened a ticket at my local IT department and I'm going wait and see what happens.

It may not be necessary to rename anything. However, if it's not a bug but a human mistake then #2410 suggests that it may be a recurring problem, we don't know how many German HPC clusters have an incorrectly installed OpenMPI. In this case renaming may be a better option.

**Comment by hkaiser** [comment]
Let's rename our type anyways. Even if they fix it, this is something we can't avoid to see out in the wild.

**Comment by hkaiser** [comment]
@mcopik Do you still plan to provide a PR renaming the symbol in HPX?

**Comment by mcopik** [comment]
@hkaiser Yes, though it was a low priority issue for me (the problem has been partially fixed by IT team). I should fix it soon.
