### ISSUE TITLE
error: Install cannot find "/lib/hpx/libparcel_coalescing.so.0.9.99" but I can see that file

### ISSUE THREAD

**Issue by GuSuku** [STEllAR-GROUP/hpx#2515]
Almost same as [this error](https://github.com/STEllAR-GROUP/hpx/issues/1529), with an earlier version, only now that file is not missing - I can see that file in the same directory ($INSTALL_PREFIX/lib/hpx) )that it says it cannot find.

I tried to install HPX locally on a Ubuntu 16.04 system using (all with no root privilege):

```
cmake -DBOOST_ROOT=/usr -DHWLOC_ROOT=/usr -DCMAKE_INSTALL_PREFIX=/home/g/Applications/hpx -DHPX_WITH_GOOGLE_PERFTOOLS=ON -DHPX_WITH_VALGRIND=ON DHPX_WITH_PARCELPORT_TCP=ON -DHPX_WITH_PARCELPORT_MPI=ON /home/g/Downloads/hpx_0.9.99

make

checkinstall --pkgname=hpx --pkgversion=0.9.99  (this calls 'make install')
```

and I get:

```
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:48 (file):
  file INSTALL cannot find
  "/home/g/Applications/hpx/lib/hpx/libhpx_parcel_coalescing.so.0.9.99".


Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1
```

But then:
```

g@ubuntuinspiron:~/Applications/hpx/lib/hpx$ ls -a
.                      libhpx_io_counters.so.0       libhpx_memory.so.0           libhpx_parcel_coalescing.so.0       libhpx_sine.so.0
..                     libhpx_io_counters.so.0.9.99  libhpx_memory.so.0.9.99      libhpx_parcel_coalescing.so.0.9.99  libhpx_sine.so.0.9.99
libhpx_io_counters.so  libhpx_memory.so              libhpx_parcel_coalescing.so  libhpx_sine.so
```

**Comment by hkaiser** [comment]
We have had reports about this before (see #1529, #1842), but we have not been able to reproduce this. Any insights on how to reproduce this would be highly appreciated. My assumption would be that `libhpx_parcel_coalescing.so.0.9.99` is actually a link to a not existing while, causing cmake to fail.

**Comment by GuSuku** [comment]
I rebuilt the same way and it is working now.

But on the non-existent link, `libhpx_parcel_coalescing.so.0.9.99` is actually the end of a chain of links:
libhpx_parcel_coalescing.so -> libhpx_parcel_coalescing.so.0
libhpx_parcel_coalescing.so.0 -> libhpx_parcel_coalescing.so.0.9.99
libhpx_parcel_coalescing.so.0.9.99

**Comment by hkaiser** [comment]
@GuSuku Thanks for this clarification. Even if we can't get to understand what's going on this time either... Please keep an eye on this and let us know. I'll close this ticket for now. Feel free to reopen, if necessary.
