### ISSUE TITLE
HPX locks up when using at least 256 localities

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#2516]
The barrier implementation using an hierarchical tree currently is leading to a deadlock. This has been observed by trying to run an HPX application on 256 nodes. When setting `hpx.lcos.collectives.cut_off` to a very high value, the hang disappears.

**Comment by biddisco** [comment]
Now I know why my infiniband tests stopped at 128 nodes

**Comment by diehlpk** [comment]
@sithhell What is a really high value?
