### ISSUE TITLE
Race condition during Parcel Coalescing Handler creation

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#2517]
The message handler creation functions currently unlock the lock when creating a new message handler. This might lead to a race condition when constructing coalescing handlers concurrently due to multiple insertions of the same counter functions as well as when adding the callbacks for the runtime config

**Comment by hkaiser** [comment]
@sithhell I thought this was handled by this code: https://github.com/STEllAR-GROUP/hpx/blob/master/src/runtime/parcelset/parcelhandler.cpp#L708-L718. Did you have something else in mind?

**Comment by sithhell** [comment]
Unfortunately not. This is not about the insertion into the map. The problem is here:
https://github.com/STEllAR-GROUP/hpx/blob/master/src/runtime/parcelset/parcelhandler.cpp#L702
In the case of parcel coalescing, we eventually end up calling this: https://github.com/STEllAR-GROUP/hpx/blob/master/plugins/parcel/coalescing/coalescing_counter_registry.cpp#L45-L77
which is then not protected by any lock.

**Comment by sithhell** [comment]
In addition, even if the code shown was protected by a lock, we might end up with stale callbacks if the message handler was constructed twice due to a race.

**Comment by hkaiser** [comment]
Right, good catch. I think I know how to fix this.
