### ISSUE TITLE
 No valid parcelport configured

### ISSUE THREAD

**Issue by quantomb** [STEllAR-GROUP/hpx#2555]
This is an error that is produced on  #2554  when running on QB. Running a distributed application crashes almost immediately in the pre_main state.

Running hello_world on 4 nodes with 2 localities per node caused the following error message:

https://gist.github.com/quantomb/d47df1353aeac50153d750fd0c41d7d0

@sithhell suggested reverting #2533 I will update this issue when I have a report on whether that fixes the issue

To add further difficulty I have once seen a distributed application run to completion without error but it appears to be the exception rather than the rule

Note no error has been observed when running on a single node even with multiple localities present on that node.

**Comment by quantomb** [comment]
I should have noted the command used to run hello_world

uniq $PBS_NODEFILE > actual.nodes
mpirun -np 8 -machinefile actual.nodes /work/quantomb/release/hpx/build/bin/hello_world --hpx:print-bind -t10 --hpx:cores=10 --hpx:list-parcel-ports

The first line is a way of forcing mpirun to assign the localities as a round-robin format to the nodes as otherwise it assigns each locality to an individual core

An interesting note is that I have not observed the error if only one locality per node is present.

**Comment by hkaiser** [comment]
@quantomb I have added even more diagnostics and improved on error handling. Would you be able to retry using #2554?

**Comment by quantomb** [comment]
@hkaiser I have retried using these additions and I have been unable to reproduce the error in any test. For sanity sake I checked out the previous commit and the error was in fact still present.

I think we can mark this as closed?

**Comment by hkaiser** [comment]
@quantomb Thanks, this will close automatically once we merge #2554

**Comment by hkaiser** [comment]
This should have been resolved on master, please re-open, if necessary.
