### ISSUE TITLE
octo-tiger crash with commit 6e921495ff6c26f125d62629cbaad0525f14f7ab 

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#2561]
I get a crash on startup when running octo-tiger on 2 queenbee nodes, starting with HPX 6e921495ff6c26f125d62629cbaad0525f14f7ab Here is the error output:

https://gist.github.com/dmarce1/9d90ac92bc03050048ac5e60032843bc

**Comment by sithhell** [comment]
One workaround for now is to enable the mpi pp explicitly until a proper
fix is pushed:
-Ihpx.parcel.mpi.enable=1

Am 23.03.2017 4:39 nachm. schrieb "Dominic Marcello" <
notifications@github.com>:
