### ISSUE TITLE
Add an inline versioning namespace before 1.0 release

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/hpx#2566]
We don't have an inline versioning namespace like all the cool kids (libc++, Vc, Ranges V3, etc):

```
#define HPX_BEGIN_NAMESPACE namespace hpx { inline namespace HPX_VERSION_NAMESPACE {
#define HPX_END_NAMESPACE }}
```

I'd like to do this before v1. I'll assign myself.

**Comment by hkaiser** [comment]
@brycelelbach please note that we have a compatibility macro for the inline part of the namespaces to allow older compiler to do the right thing. We use that for the parallel algorithms and such:

```
#include <hpx/parallel/config/inline_namespace.hpp> // this is where the macro is defined
namespace hpx { HPX_INLINE_NAMESPACE(v1)
{
    ...
}}
```
Also, the inline namespace needs to be pre-declared in the header file for the older compilers.

**Comment by hkaiser** [comment]
I'll go ahead and close this as the release is out for quite some time now.
