### ISSUE TITLE
Missing documentation for hpx::util::annotated_function

### ISSUE THREAD

**Issue by shoshijak** [STEllAR-GROUP/hpx#2590]
hpx::util::annotated_function is completely absent from the documentation (http://stellar-group.github.io/hpx/docs/html/) and the examples.

**Comment by hkaiser** [comment]
We'd be happy to accept a patch adding this missing documentation.

**Comment by victor-ludorum** [comment]
@hkaiser Hello I am new to STELLAR-GROUP and I want to start working on this issue . Please guide me how to start ..

**Comment by hkaiser** [comment]
@victor-ludorum This is a documentation task. We'd very much appreciate it if you worked on this. 

I think for you to start working on this issue you should first do two things: a) understand what is the functionality of `hpx::util::annotated_function`, and b) familiarize yourself with the documentation toolchain we use for HPX. The first can be done by looking at the source code (naturally there is no documentation for `hpx::util::annotated_function`). For the second you may want to start installing things as described here: https://stellar-group.github.io/hpx/docs/html/hpx/manual/build_system/building_hpx/doc_tools.html and make sure that you can build the existing docs. Then you might want to browse the quickbook documentation (http://www.boost.org/doc/libs/1_66_0/doc/html/quickbook.html), as this is the tool used to parse our .qbk files.

Once those tasks are accomplished it shouldn't be difficult to extend the existing docs by adding text describing what you've learnt.

**Comment by victor-ludorum** [comment]
@hkaiser Okay sir thanks for the reply . I will do as you have mentioned .
