### ISSUE TITLE
parallel algorithm called inside annotated function throws exception

### ISSUE THREAD

**Issue by shoshijak** [STEllAR-GROUP/hpx#2593]
The following code is broken by 

> commit a238b890d3bd0b4bde1bb49eb8b5bc84472d644c
> Merge: 5da331d 6c9af5e
> Author: Hartmut Kaiser <hartmut.kaiser@gmail.com>
> Date:   Sun Apr 16 09:08:13 2017 -0500
> 
>     Merge pull request #2581 from STEllAR-GROUP/annotate_parallel_algorithms
>     
>     Enable annotated function for parallel algorithms
> 

Code: 
```

#include <hpx/hpx.hpp>
#include <hpx/hpx_init.hpp>
#include <hpx/include/iostreams.hpp>
#include <hpx/parallel/algorithms/minmax.hpp>
#include <hpx/parallel/executor_parameters.hpp>
#include <vector>

double compute_minmax(const std::vector<double> v){

    hpx::parallel::static_chunk_size param;
    hpx::parallel::execution::parallel_task_policy par_policy;
    auto policy = par_policy.with(param);

    hpx::cout << "in compute_minmax: about to launch minmax element search." << std::endl;

    auto minmaxX_ = hpx::parallel::minmax_element(policy, v.begin(), v.end());
    auto minmaxX= minmaxX_.get();
    return *minmaxX.second - *minmaxX.first;
}

int hpx_main()
{
    std::vector<double> vec = {1.2, 3.4, 2.3, 77.8};
    double extent;

    hpx::async(hpx::launch::sync,
               hpx::util::annotated_function([&]() {
                   extent = compute_minmax(vec);
               }, "compute_minmax")

    );
    hpx::cout << "extent = " << extent << "\n";

    return hpx::finalize();
}

int main(int argc, char* argv[])
{
    return hpx::init(argc, argv);  // pass along command line arguments
}
```

Error message: 

> {version}: V1.0.0-trunk (AGAS: V3.0), Git: 521967cdba
> {boost}: V1.63.0
> {build-type}: release
> {date}: Apr  5 2017 14:01:22
> {platform}: linux
> {compiler}: GNU C++ version 5.4.0 20160609
> {stdlib}: GNU libstdc++ version 20160609
> {what}: data has already been set for this future: HPX(promise_already_satisfied)
> 
> terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<hpx::exception> >'
>   what():  data has already been set for this future: HPX(promise_already_satisfied)
> 
> Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
>

**Comment by hkaiser** [comment]
@shoshijak I'm not able to reproduce this problem. Could you provide more information about how you built HPX (cmake log, build log) and how you executed the test?

**Comment by shoshijak** [comment]
I'm sorry, I cannot reproduce anymore either ... 
It could be that I was building the test in a different build type than I had built HPX or something like that.
