### ISSUE TITLE
FindOpenCL.cmake mismatch with the official cmake module

### ISSUE THREAD

**Issue by ddemidov** [STEllAR-GROUP/hpx#2594]
CMake since v3.1 includes [FindOpenCL.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindOpenCL.cmake).

The problem with [the one](https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/FindOpenCL.cmake) that is included with HPX is that the official module exports `OpenCL_INCLUDE_DIRS` and `OpenCL_LIBRARIES`, while HPX one exports `OPENCL_INCLUDE_DIRS` and `OPENCL_LIBRARIES` (note the difference in capitalization). Both modules export `OpenCL_FOUND` though, so, when a project depends both on OpenCL and HPX, different set of variables will be available, depending on which comes first in `CMakeLists.txt`: `find_package(OpenCL)` or `find_package(HPX)`. This may lead to interesting results when one expects one or the other naming convention.

I could try and replace `OPENCL_*` variable names with `OpenCL_*` ones throughout HPX cmake files. Would that be acceptable?

**Comment by ddemidov** [comment]
Less intrusive option would be to just export both sets of variables from HPX `FindOpenCL` module.

**Comment by hkaiser** [comment]
Currently, non of the code in HPX depends on OpenCL. This file is an artifact, afaics. @mcopik Is that correct?

**Comment by hkaiser** [comment]
Moreover, none of the HPX cmake build system imports the FindOpenCL file. So I think it is safe to simply remove the file from HPX.

**Comment by hkaiser** [comment]
This was fixed by merging #2595

**Comment by ddemidov** [comment]
Thanks!

**Comment by mcopik** [comment]
@hkaiser Everything should be fine, CMake and SYCL have their own scripts for OpenCL.
