### ISSUE TITLE
High priority tasks are not executed first

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2601]
![1sm3oyuty](https://cloud.githubusercontent.com/assets/941548/25521828/604dcbf2-2c01-11e7-8e0a-3e1a41aa13c3.png)
The image attached shows that the red tasks (which are high priority ones) are not being run before the green ones submitted at the same time.

Some modifications to the scheduler produce a much better output and 10-20% improvement in time to solution for our matrix operation code.
![1rvsiudku](https://cloud.githubusercontent.com/assets/941548/25521912/a0e69ee6-2c01-11e7-8042-29d46aa80351.png)

I will submit a PR to stimulate further discussion

**Comment by hkaiser** [comment]
I think this has been fixed by merging #2602. Please reopen if appropriate.
