### ISSUE TITLE
Documentation: Linking functions is broken

### ISSUE THREAD

**Issue by Naios** [STEllAR-GROUP/hpx#2615]
8024b0f22cba4f337a9d

**Description:**

Due to #2611 I discovered that linking functions isn't possible from inside the doxygen documentation in-source comments. This includes autolinking (function names are converted into links) as well as copying the documentation of another function into the current type (`\copydoc`) - the reference stays unresolved in general.

By default this should work in doxygen (there is no config entry set which disables autolinking), linking class names however works.

**How-to reproduce**:

Build the documentation after inserting the following lines into a header (which is parsed by doxygen) of your choice:

```c++
    /// This is my type
    struct MyType { };

    /// \copydoc MyType 
    ///
    /// here I reference MyType 
    struct MyOtherType { }; // Works

    /// This is my function
    inline void my_function() { };

    /// \copydoc my_function 
    ///
    /// here I reference my_function 
    inline void my_other_function() { }; // Doesn't work
```

And you will see that the links to classes/structs are referenced correctly whereas linking functions is broken

**Comment by hkaiser** [comment]
Not sure if that's what you would like to achieve, but we link functions from inside our docs alright (see for instance: http://stellar-group.github.io/hpx/docs/html/hpx/manual/parallel/parallel_algorithms.html#hpx.manual.parallel.parallel_algorithms.parallel_algorithms).

**Comment by hkaiser** [comment]
Also, the doxygen documentation suggest, that you need to specify the full function declaration when using `\copydoc`:

    /// This is my function
    inline void my_function() { };

    /// \copydoc my_function()
    ///
    /// here I reference my_function 
    inline void my_other_function() { }; 

Does this work?

**Comment by Naios** [comment]
Thank you for your suggestion, but ít doesn't work.

Through a default doxygen project I figured out that the snipped below is the correct way for auto referencing a function in an arbitrary namespace:

```c++

namespace my_namespace {
/// This is my function
inline void my_function() { };

/// \copydoc my_namespace::my_function()
///
/// here I reference my_namespace::my_function()
inline void my_other_function() { }; 
}
```

![screenshot_1](https://cloud.githubusercontent.com/assets/1146834/25828066/80735a46-344e-11e7-8622-22d90de6afac.png)

The issue persists when using the snipped above inside a hpx header file parsed with doxygen.
