### ISSUE TITLE
Invalid return type ‘void’ of constexpr function

### ISSUE THREAD

**Issue by atrantan** [STEllAR-GROUP/hpx#2638]
Got an issue because my gcc version is 4.9. Here is a snippet of what I'm getting when building hpx:

> ../hpx/runtime/serialization/output_container.hpp:106:39: error: invalid return type ‘void’ of constexpr function ‘static constexpr void hpx::serialization::detail::basic_chunker::set_chunk_size(std::size_t)’
>              HPX_CONSTEXPR static void set_chunk_size(std::size_t)

**Comment by hkaiser** [comment]
@atrantan: what workaround would you suggest we apply?

**Comment by atrantan** [comment]
Honestly, got no idea except considering gcc 4.9 as obsolete

**Comment by hkaiser** [comment]
@atrantran Those functions don't _have_ to be `constexpr` to begin with. The optimizer should be able to get rid of those in any case. Could you prepare a patch please which removes the `constexpr` from the offending functions?

**Comment by atrantan** [comment]
Sure. Done in PR #2642
