### ISSUE TITLE
hpx::parcelset::detail::parcel_data::has_continuation_ is unitialized

### ISSUE THREAD

**Issue by robstewart57** [STEllAR-GROUP/hpx#2647]
I'm HPX version da3fd176cd28e9d1fc9bfb47b70a6333d531f517 compiling with GCC 7.1.1 . I am getting this error:

```
hpx/src/runtime/parcelset/parcel.cpp:96:37: error: ‘<anonymous>.hpx::parcelset::detail::parcel_data::has_continuation_’ is used uninitialized in this function [-Werror=uninitialized]
             has_continuation_ = rhs.has_continuation_;
                                 ~~~~^~~~~~~~~~~~~~~~~
```

The line in question is the last line of:

```
source_id_ = std::move(rhs.source_id_);
dest_ = std::move(rhs.dest_);
addr_ = std::move(rhs.addr_);
has_continuation_ = rhs.has_continuation_;
```

Is this known? Is GCC 7.1.1 supported by HPX? How could I suppress this error?

**Comment by hkaiser** [comment]
@robstewart57 I've not seen this before, will investigate.

**Comment by hkaiser** [comment]
@robstewart57 this has already been fixed on master (see https://github.com/STEllAR-GROUP/hpx/commit/cc15d1c67144200f070e74d80b6d840df0a16ee3). I'll go ahead and close this, feel free to reopen, if needed.
