### ISSUE TITLE
libfabric support for passive endpoints

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/hpx#2650]
libfabric passive endpoint support is missing, specifically a function with the following signature "bind_endpoint_to_queues(struct fid_pep *endpoint)". Also, cmake instructions break when compiling against libfabric using passive endpoints.

**Comment by ct-clmsn** [comment]
Wanted to mention, the macros for controlling passive support create a couple of small issues in  `plugins/parcelport/libfabric/libfabric_controller.hpp`

The function `locality create_local_endpoint()` needs to have the variable 'int ret' defined above the #ifdef HPX_PARCELPORT_LIBFABRIC_ENDPOINT_RDM macro call (line 490). This will impact the call to `ret = fi_getname(id, local_addr.data(), &addrlen);` on line 507.

**Comment by biddisco** [comment]
@ct-clmsn When you say "cmake instructions break when compiling against libfabric using passive endpoints" could you tell me what you are doing? (what cmake invocation is failing).

the libfabric support is ongoing and still only supports a very limited range of providers (so far only cray gni is actually working correctly). and we are only supporting the RDM endpoint type. 
The code does compile against the PSM provider (omnipath), but has not yet been tested properly.

The passive endpoint code was originally working with the verbs provider, but we made soe many changes to the code around it when adding support for the gni provider, that it should now be deprecated and removed. The passive endpoint support requires connection oriented endpoints and it is so much easier to use connectionless endpoints that it is unlikely we'll ever add connection oritned endpoint back into the code.

Can you tell me what machine/platform/provider you are trying to use? if it's an infiniband based machine, then we should fix the verbs parcelport and use that (I did previously say I'd look at it, so I'll do so this week).

**Comment by ct-clmsn** [comment]
@biddisco I'll start off by professing a general lack of experience programming or building against OFI and libfabric.  With that understanding, I attempted a very naive build using the cmake flags for HPX that should bake-in libfabric. The bit about cmake being broken was to see if there is an ability to detect what type of providers (ugni, omnipath, passive endpoints, etc) are available? I'm currently building against a mellanox ib cluster.
