### ISSUE TITLE
Crash in managed_component::get_base_gid due to problem with util::reinitializable_static.

### ISSUE THREAD

**Issue by neutrino504** [STEllAR-GROUP/hpx#2662]
I get a crash when running octo-tiger on supermic (compiled with gcc).
It is a seg fault in managed_component::get_base_gid, the output is here:
https://gist.github.com/neutrino504/6aee4c053de21d78a6b27a765c177b08

The problem went away when I modified "get_heap" (line 294) in hpx/runtime/components/server/managed_component_base.hpp by adding a lock so the body of get_heap is executed atomically. So it looks like there is a problem with util::reinitializable_static (which is used in get_heap).

**Comment by hkaiser** [comment]
Could you show us what you changed, please?

**Comment by hkaiser** [comment]
Duplicate to #2663
