### ISSUE TITLE
Statistics Performance counter is not working 

### ISSUE THREAD

**Issue by justwagle** [STEllAR-GROUP/hpx#2666]
The statistics performance counters are not working. They do not print any values and  the application does not terminate. 

Sample command line to reproduce:
srun -p ariel -N 1 -n 1  ./1d_stencil_8 --nx=100 --nt=100000  --hpx:threads=16  --hpx:cores=16  --hpx:print-counter=/statistics{/runtime{locality#0/total}/io/write_bytes_cancelled}/average@2000

Localities,OS_Threads,Execution_Time_sec,Points_per_Partition,Partitions,Time_Steps
1,     16,    20.521090545, 100,                  10,                   100000
 (This does not terminate and we do not see any output from the statistics performance counter)

HPX was compiled with the following flags:
  cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo                           \
        -DCMAKE_CXX_COMPILER=icpc \
        -DCMAKE_CXX_FLAGS='-w'  \
        -DCMAKE_C_COMPILER=icc \
        -DMPI_CXX_COMPILER=mpiicpc     \
        -DMPI_C_COMPILER=mpiicc \
        -DHPX_WITH_THREAD_IDLE_RATES=ON \
        -DHPX_WITH_MALLOC="jemalloc" \
        -DHPX_WITH_HWLOC=ON \
        -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH \
        -DHPX_WITH_PARCELPORT_MPI=ON \
        -DBOOST_ROOT=/home/bwagle/Packages/boost/install \
        -DHPX_WITH_PARCELPORT_MPI_MULTITHREADED=ON \
        -DHPX_WITH_ITTNOTIFY=ON \
        -DAMPLIFIER_ROOT=/opt/eb/software/VTune/2017_update1/vtune_amplifier_xe \
        -DHPX_WITH_GOOGLE_PERFTOOLS=ON                       \
        -DHPX_WITH_EXAMPLES=ON  \
        -DHPX_WITH_DATAPAR_VC_NO_LIBRARY=ON \
        -DVc_ROOT=/home/bwagle/Packages/vcmaster/install \
        -DHPX_WITH_DATAPAR_VC=ON \

**Comment by pagrubel** [comment]
Do you have the syntax correct. I haven’t done this in quite a while but my past scripts have something of the form:
/arithmetics/add@/{papi …

so I’m thinking it should be /statistics/average{

but then you should have gotten an error.

Pat
On May 31, 2017, at 8:50 AM, Bibek Wagle <notifications@github.com<mailto:notifications@github.com>> wrote:


The statistics performance counters are not working. They do not print any values and the application does not terminate.

Sample command line to reproduce:
srun -p ariel -N 1 -n 1 ./1d_stencil_8 --nx=100 --nt=100000 --hpx:threads=16 --hpx:cores=16 --hpx:print-counter=/statistics{/runtime{locality#0/total}/io/write_bytes_cancelled}/average@2000

Localities,OS_Threads,Execution_Time_sec,Points_per_Partition,Partitions,Time_Steps
1, 16, 20.521090545, 100, 10, 100000
(This does not terminate and we do not see any output from the statistics performance counter)

HPX was compiled with the following flags:
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo
-DCMAKE_CXX_COMPILER=icpc
-DCMAKE_CXX_FLAGS='-w'
-DCMAKE_C_COMPILER=icc
-DMPI_CXX_COMPILER=mpiicpc
-DMPI_C_COMPILER=mpiicc
-DHPX_WITH_THREAD_IDLE_RATES=ON
-DHPX_WITH_MALLOC="jemalloc"
-DHPX_WITH_HWLOC=ON
-DCMAKE_INSTALL_PREFIX=$INSTALL_PATH
-DHPX_WITH_PARCELPORT_MPI=ON
-DBOOST_ROOT=/home/bwagle/Packages/boost/install
-DHPX_WITH_PARCELPORT_MPI_MULTITHREADED=ON
-DHPX_WITH_ITTNOTIFY=ON
-DAMPLIFIER_ROOT=/opt/eb/software/VTune/2017_update1/vtune_amplifier_xe
-DHPX_WITH_GOOGLE_PERFTOOLS=ON
-DHPX_WITH_EXAMPLES=ON
-DHPX_WITH_DATAPAR_VC_NO_LIBRARY=ON
-DVc_ROOT=/home/bwagle/Packages/vcmaster/install
-DHPX_WITH_DATAPAR_VC=ON \

**Comment by hkaiser** [comment]
@pagrubel the syntax is correct for this counter.

**Comment by pagrubel** [comment]
Nice to know

On May 31, 2017, at 7:18 PM, Hartmut Kaiser <notifications@github.com<mailto:notifications@github.com>> wrote:


@pagrubel<https://github.com/pagrubel> the syntax is correct for this counter.
