### ISSUE TITLE
In parallel algorithm, other tasks are executed to the end even if an exception occurs in any task.

### ISSUE THREAD

**Issue by taeguk** [STEllAR-GROUP/hpx#2678]
Currently, other tasks are executed to the end even if an exception occurs in any task.
Ideally, it seems better that all other tasks are stopped immediately when an exception occurs in any task.
But I think it is ideal. Actually, for this, unnecessary overheads are needed in normal cases where an exception does not occur.
I would like to find out if there is a way to solve this problem while minimizing the overhead.
How do you think about it?

 - https://github.com/STEllAR-GROUP/hpx/blob/4bb8a22/hpx/parallel/util/detail/handle_local_exceptions.hpp#L118
 - https://github.com/STEllAR-GROUP/hpx/blob/4bb8a22/hpx/parallel/util/partitioner.hpp#L230-L234

**Comment by hkaiser** [comment]
We usually don't let all partitions run to completion. The `cancellation_token` is accessed by all partitions, such that they can stop running once one of the partitions throws an exception. Do I miss something?

**Comment by taeguk** [comment]
@hkaiser There are things that don't use ```cancellation_token``` like ```partitioner```.
 (https://github.com/STEllAR-GROUP/hpx/blob/4bb8a22/hpx/parallel/util/partitioner.hpp#L230-L234)
In these cases, other tasks(partitions) are executed to the end even if an exception occurs in any task(partition).

**Comment by hkaiser** [comment]
@taeguk We would have to make sure that using a `cancellation_token` for all the other algorithms (which don't use it right now) wouldn't cause additional overheads for the non-exceptional case. 

In general, I think we shouldn't try to optimize the exceptional code path as error handling is costly anyways and normally nobody cares about how 'slow' error handling is.

**Comment by hkaiser** [comment]
@taeguk: what should we do with this ticket? Can we close this? Do you plan to work on this?

**Comment by taeguk** [comment]
@hkaiser I think that efficiency of exceptional code is not such important at now. So, I close this issue for now without fixing.
