### ISSUE TITLE
Mismatch between size of archive and container

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2679]
This line
https://github.com/STEllAR-GROUP/hpx/blob/c24d02101fe6c9a58a5d46d1781b1c481c4e0d48/hpx/runtime/serialization/output_archive.hpp#L360
increments the size of the archive even when a pointer chunk is added. This causes a mismatch between the size of the container and the size of the archive. After preprocess, this causes excessive memory allocation when the container buffer is allocated/reserved to a much larger size than necessary.

**Comment by hkaiser** [comment]
@biddisco Was this resolved by now?

**Comment by biddisco** [comment]
this was resolved by #2680
