### ISSUE TITLE
HPX does not compile with HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=OFF

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#2682]
Compiling with GCC on QB2, HPX does not compile when HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=OFF. I get this error:

https://gist.github.com/dmarce1/7b91834298f021e0b78854d484df5f74

**Comment by hkaiser** [comment]
@KhalidHasanov, @sithhell  Could you please look into this? This problem seems to be related to the new throttling scheduler.
