### ISSUE TITLE
Naming inconsistency in parallel algorithms.

### ISSUE THREAD

**Issue by taeguk** [STEllAR-GROUP/hpx#2700]
There are naming inconsistencies in parallel algorithms.

```F``` vs ```Pred```
------------------------
```F``` - https://github.com/STEllAR-GROUP/hpx/blob/0f16de3bdd0d71f051cab644268901a4b08b19e1/hpx/parallel/algorithms/copy.hpp#L563
```Pred``` - https://github.com/STEllAR-GROUP/hpx/blob/0f16de3bdd0d71f051cab644268901a4b08b19e1/hpx/parallel/algorithms/copy.hpp#L354

My opinion - In many places, two namings are mixed and used. It seems better to using ```Pred``` consistently.

**Comment by hkaiser** [comment]
I'd be glad to accept a corresponding PR

**Comment by taeguk** [comment]
@hkaiser Okay, I'll do that in July.

**Comment by taeguk** [comment]
@hkaiser I have more confusions about naming.
```RandomIt``` vs ```RandIter```
```ForwardIt``` vs ```FwdIter```
```Compare``` vs ```Comp```

Even though this is trivial thing, it seems better that there is one consistent naming.
How do you think about it?

**Comment by hkaiser** [comment]
> Even though this is trivial thing, it seems better that there is one consistent naming.
 How do you think about it?

By all means, go for it. Thanks!

**Comment by taeguk** [comment]
Which naming is better as you think?
RandomIt vs RandIter
Compare vs Comp

**Comment by hkaiser** [comment]
> Which naming is better as you think?

FWIW, we've mostly been using `InIter`, `FwdIter`, `BidirIter`, `RanIter`, `OutIter`, and `Comp`. In other places we've used `Op` or `Pred`. In the end it doesn't matter as long as it is consistent.

**Comment by hkaiser** [comment]
I think we can close this now. Feel free to reopen if there are still places where the names are inconsistent.
