### ISSUE TITLE
Multiple defined symbols for task_block.hpp in VS2015

### ISSUE THREAD

**Issue by woodmeister123** [STEllAR-GROUP/hpx#2707]
Using VS2015 UD3, I get a multiple defined symbol error for the handle_task_block_exceptions free function in parallel/task_block.hpp, whenever this file gets included in multiple translation units.

If I add the inline keyword to this function it compiles ok. 

Am I missing something here?

**Comment by sithhell** [comment]
Sounds like a genuine bug to me. Thanks for reporting! Since you already
did the work, do you mind submitting a pr with the mentioned changes?

Am 21.06.2017 6:31 nachm. schrieb "woodmeister123" <notifications@github.com

**Comment by woodmeister123** [comment]
Yep, will do
