### ISSUE TITLE
Some forward declarations in execution_fwd.hpp aren't C++11-compatible

### ISSUE THREAD

**Issue by gentryx** [STEllAR-GROUP/hpx#2718]
Hoi,

my C++11-only builds of LGD with HPX are failing because return types are given as auto without a resolution of that type, e.g. https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/parallel/executors/execution_fwd.hpp#L76

I'm not sure how to resolve this as the forward declarations seem to be a hornets' nest. Ideas? Thanks!

**Comment by hkaiser** [comment]
Doh'! I'm not sure how to resolve this :/

**Comment by gentryx** [comment]
Or to ask the question differently: how do you build CUDA-enabled HPX apps on Rostam?

**Comment by gentryx** [comment]
I think I got it, will file PR tomorrow. :-)
