### ISSUE TITLE
Why Projection is needed in parallel algorithms?

### ISSUE THREAD

**Issue by taeguk** [STEllAR-GROUP/hpx#2728]
Why projection is needed in interface of parallel algorithms?
https://github.com/STEllAR-GROUP/hpx/blob/383eab90cad8a29dfd66f930d97bd50c77569689/hpx/parallel/algorithms/partition.hpp#L271

I know that it is for invoking some procedure before invoking predicate.
But, I can't understand if we really need it.
Is there anyone to demonstrate the reason for me?

I didn't use ```Proj``` when I implemented ```is_heap``` and ```is_heap_until```.
Should I use ```Proj```?
https://github.com/STEllAR-GROUP/hpx/blob/383eab90cad8a29dfd66f930d97bd50c77569689/hpx/parallel/algorithms/is_heap.hpp#L176

I'm confused because some algorithms use ```Proj```` and others don't.
https://github.com/STEllAR-GROUP/hpx/blob/383eab90cad8a29dfd66f930d97bd50c77569689/hpx/parallel/algorithms/equal.hpp#L403

**Comment by hkaiser** [comment]
> Why projection is needed in interface of parallel algorithms?

Projections are a very powerful means of extending the algorithms. For instance see our implementation of `sort_by_key` which is using a special projection function allowing for it to be implemented using a straight `sort` (see https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/parallel/algorithms/sort_by_key.hpp). See also Eric Nieblers original paper giving a motivation and examples: https://ericniebler.github.io/std/wg21/D4128.html#algorithms-should-take-invokable-projections.

> I didn't use Proj when I implemented is_heap and is_heap_until. Should I use Proj?

Yes, see here: [N4651](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4651.pdf)

> I'm confused because some algorithms use ```Proj```` and others don't.

We're slowly migrating to the newer algorithm specifications (as per [N4651](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4651.pdf)). Not all algorithms have been adapted yet. see also https://github.com/STEllAR-GROUP/hpx/issues/1668 for a list of algorithms we already have adapted.

**Comment by hkaiser** [comment]
Can we close this now?
