### ISSUE TITLE
HPX segfaulting with valgrind

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [STEllAR-GROUP/hpx#2746]
I'm trying to debug an octotiger problem with valgrind. I compiled hpx with `-DHPX_WITH_VALGRIND=ON` (also tried it without). Unfortunately, the application immediately crashes as soon as I prefix my call with `valgrind`.

```
valgrind ./build_with_symbols/octotiger -t1 -Problem=moving_star -Max_level=3 -Odt=0.3 -Stoptime=0.2 -Xscale=20.0 -Omega=0.1  -Stopstep=9
```

Output log:
[with_valgrind.txt](https://github.com/STEllAR-GROUP/hpx/files/1130440/with_valgrind.txt)

The application runs flawlessly without valgrind. AND: A few month ago debugging with valgrind still worked fine.

What can I do to debug memory errors in HPX applications? Note that I strongly prefer to not recompile to catch memory errors (compilation duration; having to ensure to recompile my whole application + dependencies with additional/different flags consistently).

Update: I actually tried building HPX and octotiger with sanitizers, that fails within boost. Just to highlight that it is non-trivial to get a build with sanitizers going.

Output with sanitizers log:
[with_sanitizers.txt](https://github.com/STEllAR-GROUP/hpx/files/1130538/with_sanitizers.txt)

**Comment by DavidPfander-UniStuttgart** [comment]
Would be nice if someone could have a look at this. This is still a blocking issue for me.

And as I mentioned, this functionality was working (for me) a few months ago...

**Comment by aserio** [comment]
@khuck , Were you looking into this?

**Comment by DavidPfander-UniStuttgart** [comment]
@aserio No, he wasn't. He was proposing a different tool, which doesn't have the features valgrind has.

BTW, this still is very annoying issue for me. Any help would still be greatly appreciated.

**Comment by DavidPfander-UniStuttgart** [comment]
Turns out this was an alignment issue stemming from a missing C++ feature (Dynamic memory allocation for over-aligned data, P0035R4, introduced in C++17). Now using Vc macros that implement a workaround. This problem should no longer occur with gcc 7 and newer.
