### ISSUE TITLE
infinite loop in `make install`: include/hpx/install/include/hpx/..

### ISSUE THREAD

**Issue by robstewart57** [STEllAR-GROUP/hpx#2759]
Here is my cmake and gmake commands:

    cd ~/sw/
    git clone git@github.com:STEllAR-GROUP/hpx.git
    cd hpx
    mkdir hpx_build
    cd hpx_build
    cmake -DHPX_WITH_MALLOC=jemalloc -DHPX_WITH_PARCELPORT_MPI=On -DCMAKE_INSTALL_PREFIX=/home/rstewart/sw/hpx/hpx-install/ -DCMAKE_BUILD_TYPE=Debug -DJEMALLOC_LIBRARY=~/sw/jemalloc/jemalloc-build/lib/ -DJEMALLOC_INCLUDE_DIR=~/sw/jemalloc/jemalloc-build/include/ -DBOOST_ROOT=~/sw/boost/boost_1_64_0/ -DHWLOC_ROOT=/home/rstewart/sw/hwloc/hwloc-build/ ~/sw/hpx/
    gmake -j16
    gmake install

The `gmake install` command infinitely recurses into `include/hpx/install/include/hpx/..`, and continues to recursively expand into this directory name structure, e.g.

    Installing: /home/rstewart/sw/hpx/hpx-install/include/hpx/install/include/hpx/install/include/hpx/install/include/hpx/install/include/hpx/install/include/hpx/install/include/hpx/install/include/hpx/include/plain_actions.hpp

What have I done wrong?

**Comment by sithhell** [comment]
Which CMake version are you using? Our testers do not reproduce that problem, my guess would be that our CMake scripts behave badly with some newer, or older CMake version. Is this with the current HEAD of master?

**Comment by robstewart57** [comment]
3.4.0-rc1

Is that too old? Which cmake versions are compatible? I am using the current HEAD of master of hpx.

**Comment by sithhell** [comment]
Our CI system is currently using 3.8.1. I'll try to reproduce the issue with 3.4.

**Comment by robstewart57** [comment]
@hkaiser @sithhell are you able to reproduce the issue with cmake 3.4 ?

**Comment by hkaiser** [comment]
Rob, could you please try to delete the build directory and start over? Do you see this problem in this case as well?
