### ISSUE TITLE
 Compilation fails with parcelport based on libfabric or verbs

### ISSUE THREAD

**Issue by manzali** [STEllAR-GROUP/hpx#2766]
I tried to compile HPX with the support for libfabric and verbs libraries. I checked out the master branch and the compilation fails in both the cases (verbs and libfabric):

1) with -DHPX_WITH_PARCELPORT_VERBS=ON :

/hpx/hpx/plugins/parcelport/verbs/rdma/rdma_controller.cpp:10:51: fatal error: hpx/config/parcelport_verbs_defines.hpp: No such file or directory
 #include <hpx/config/parcelport_verbs_defines.hpp>

/hpx/hpx/runtime/parcelset/parcelport_impl.hpp:513:52: error: ‘struct hpx::parcelset::policies::verbs::parcelport’ has no member named ‘reclaim_connection’; did you mean ‘create_connection’?

2) with -DHPX_WITH_PARCELPORT_LIBFABRIC=ON :

/hpx/plugins/parcelport/libfabric/libfabric_controller.hpp:413:48 error: no matching function for call to ‘hpx::parcelset::policies::libfabric::libfabric_controller::bind_endpoint_to_queues(fid_pep*&)’
             bind_endpoint_to_queues(ep_passive_);

/hpx/plugins/parcelport/libfabric/libfabric_controller.hpp:497:13: error: ‘ret’ was not declared in this scope
             ret = fi_passive_ep(fabric_, fabric_info_, &ep_passive_, nullptr);
             ^~~
/hpx/plugins/parcelport/libfabric/libfabric_controller.hpp: In member function ‘int hpx::parcelset::policies::libfabric::libfabric_controller::poll_event_queue(bool)’:
/hpx/plugins/parcelport/libfabric/libfabric_controller.hpp:907:22: error: ‘FI_JOIN_COMPLETE’ was not declared in this scope
                 case FI_JOIN_COMPLETE:

**Comment by hkaiser** [comment]
@manzali: @sithhell promised to look into this over the next couple of days.
