### ISSUE TITLE
Is there iterator tag for HPX?

### ISSUE THREAD

**Issue by taeguk** [STEllAR-GROUP/hpx#2768]
There are several HPX traits for checking iterator tag. (https://github.com/STEllAR-GROUP/hpx/blob/607dd9e5c6e0b3815236f95bf81fa76949f40b71/hpx/traits/is_iterator.hpp#L107-L160)

They check not only iterator tag but also iterator traversal.
If I want to overload several functions though iterator tag, maybe I will do like below:
```c++
void func(std::forward_iterator)
{ ... }
void func(std::bidirectional_iterator)
{ ... }
```
But, this way is incorrect because iterator traversal is not considered.
So, I think that iterator tag for HPX is needed.
Maybe naming will be like ```hpx::traits::forward_iterator```.

How do you think about it?
If I can do that overloading without adding iterator tag for HPX, please tell me how to do.

**Comment by hkaiser** [comment]
@taeguk: I don't think you need to take the boost iterator traversal categories into account into any way. Our iterator traits support them in order for the Boost iterators to work properly, especially those from older Boost versions. In short, we can assume that our implementation has to deal with the standard iterator categories only.

**Comment by hkaiser** [comment]
Can we close this now?
