### ISSUE TITLE
New Launch Policy: async_if

### ISSUE THREAD

**Issue by aserio** [STEllAR-GROUP/hpx#2800]
I am noting this here so we don't forget to do this at some point

Currently dataflow will launch on the same thread as it is invoked with if all of the arguments it is supplied with are ready. If some of the arguments are not ready the dataflow is invoked with the continuation of the thread of the last future which is now made ready. If the user uses `hpx::launch::async` the dataflow will be launched on another thread regardless of whether it is invoked by the main thread or a continuation.

`async_if` would allow the dataflow to be spawned on a new thread only if dataflow was invoked with the original thread that created it. If dataflow is invoked by a continuation it would instead continue on the same thread.

P.S. I am not tied to the name. It just was the first thing that popped in my head

**Comment by hkaiser** [comment]
`async_if` could take a predicate function which returns `true` if the continuation should be launched asynchronously:

     auto this_id = this_thread::get_id();
     dataflow(
        launch::async_if([&]() { return this_thread::get_id() == this_id; }),
        [](...) {},
        ...);

where the predicate is invoked in the context of the thread about to run the continuation.
