### ISSUE TITLE
Difficulty building with `HPX_WITH_HWLOC=Off`

### ISSUE THREAD

**Issue by bremerm31** [STEllAR-GROUP/hpx#2807]
I was trying to build HPX with `HPX_WITH_HWLOC=Off`

However, I get the following [make error](https://gist.github.com/bremerm31/f673068d51e088a24539526920a19de2)

zao in the IRC channel recommended just building with hwloc, which I will do. However, it might be nice to either deprecate the flag (if hwloc is truly a required dependency) or fix the include.

**Comment by hkaiser** [comment]
Will fix asap
