### ISSUE TITLE
Compilation fails with gcc 7.1.1

### ISSUE THREAD

**Issue by G-071** [STEllAR-GROUP/hpx#2812]
I tried to compile HPX using the current gcc from the arch linux repository (GNU 7.1.1). However, this caused a compilation error (see attached make log) which is not present when using the older gcc 6.3.1.

For compilation I used the following commands in the build directory:
cmake -DCMAKE_INSTALL_PREFIX=.  ../
make -j5
The output of cmake and make:
[make-log-gcc71.txt](https://github.com/STEllAR-GROUP/hpx/files/1213394/make-log-gcc71.txt)
[cmake-log-gcc71.txt](https://github.com/STEllAR-GROUP/hpx/files/1213395/cmake-log-gcc71.txt)

Compilation works fine when using an older version of gcc (tested with GNU 6.3.1)!

**Comment by hkaiser** [comment]
Does it work if you force C++14 mode: `cmake -DHPX_WITH_CXX14=ON ...` ? I believe this is a known problem in Boost, not sure if this is fixed there yet.

**Comment by G-071** [comment]
Yes. With this flag I can compile HPX with gcc 7.1.1 without further problems.
