### ISSUE TITLE
HPX fails to compile with HPX_WITH_CUDA=ON and the new CUDA 9.0 RC.

### ISSUE THREAD

**Issue by Element-126** [STEllAR-GROUP/hpx#2815]
Hi,

I was trying to compile HPX with the brand new CUDA 9.0 release candidate, in order to take advantage of the C++14 support in NVCC.

The HPX version used corresponds to commit `0b269d1ff6b4e2550839086c50edb10806ab3121`.

I configured HPX with the following CMake command:

    cmake -D CMAKE_INSTALL_PREFIX=/home/jtastet/.local/stow/hpx_cuda-9.0 \
          -D HPX_WITH_MALLOC=jemalloc \
          -D HPX_WITH_PARCELPORT_MPI=ON \
          -D HPX_WITH_CXX14=ON \
          -D HPX_WITH_CUDA=ON \
          -D HPX_WITH_CUDA_ARCH=sm_61 \
          ..

and then tried to build it using GCC 6.3 (now supported by CUDA 9.0).

Compilation fails with the following error (see the attached build log for the full output):

    Scanning dependencies of target transpose_serial_vector_exe
                 from /usr/local/cuda-9.0/include/cuda_runtime.h:115,
                 from <command-line>:0:
    /usr/local/cuda-9.0/include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
     #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
    /usr/local/cuda-9.0/include/crt/common_functions.h:64:24: note: in definition of macro '__CUDACC_VER__'
     #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/local/cuda-9.0/include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
     #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
    /usr/local/cuda-9.0/include/crt/common_functions.h:64:24: note: in definition of macro '__CUDACC_VER__'
     #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[hpx_build_log.txt](https://github.com/STEllAR-GROUP/hpx/files/1217916/hpx_build_log.txt)

The error appears to be triggered by the following constant definition in `/usr/local/cuda-9.0/include/crt/common_functions.h`:

    #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."

Previously, `__CUDACC_VER__` was an integer literal representing the version number of the CUDA Toolkit (defined by the compiler ? I cannot find it in the headers). It has been deprecated in CUDA 9.0 and overridden by this message, effectively breaking all preprocessor expressions relying on it.

I have grepped the HPX source code for `__CUDACC_VER__`, and found nothing, so I am not sure whether the bug is in HPX or in CUDA 9.0.

Nevertheless, I think this issue is worth investigating, since the C++14 support in CUDA 9.0 makes it an attractive option to anyone trying to use HPX with CUDA.

Feel free to ask me if you need any extra information.

**Comment by hkaiser** [comment]
@Element-126: Thanks for reporting this issue. Would you be able to provide a possible fix for this?

**Comment by Element-126** [comment]
Ok. The situation is clearer now.

I have grepped the entire code base, including all the dependencies of HPX, and the `__CUDACC_VER__` macro is used several times by Boost for conditional compilation depending of the version of the CUDA Toolkit:

    [jtastet@felk40 software]$ grep -inr __CUDACC_VER__ .
    ./boost/boost_1_64_0/libs/config/test/config_info.cpp:339:  PRINT_MACRO(__CUDACC_VER__);
    ./boost/boost_1_64_0/boost/config/compiler/nvcc.hpp:22:#if !defined(__CUDACC_VER__) || (__CUDACC_VER__ < 70500)
    ./boost/boost_1_64_0/boost/config/compiler/nvcc.hpp:26:#if (__CUDACC_VER__ > 80000) && (__CUDACC_VER__ < 80100)

So this is definitely an upstream bug. I will checkout the Boost master branch and see if the problem is still here. If yes, then I will report it to the Boost developers.

I guess you can close this issue and/or tag it as `upstream`.

**Comment by hkaiser** [comment]
As a stop-gap measure we could `-D__CUDACC_VER__=...` on the compiler command line ourselves. That should take care of this problem.

**Comment by Element-126** [comment]
Just for the record, ticket [`#13152`](https://svn.boost.org/trac10/ticket/13152) has been opened in the Boost bug tracker.

They consider it a CUDA issue, since the `__CUDACC_VER__` macro was removed without being properly deprecated first.
