### ISSUE TITLE
The std::bad_alloc is not handled correctly in parallel::sort.

### ISSUE THREAD

**Issue by taeguk** [STEllAR-GROUP/hpx#2816]
The ```std::bad_alloc``` seems be not handled correctly in parallel::sort.

https://github.com/STEllAR-GROUP/hpx/blob/130deb29bd90bc263a8cb17713d7027818fd5ce1/hpx/parallel/algorithms/sort.hpp#L153-L169

As I know, ```std::bad_alloc``` should be thrown itself. But, by above codes, ```std::bad_alloc``` is wrapped into ```exception_list```.

As I think, using ```util::detail::handle_local_exception``` is better way like this:
https://github.com/STEllAR-GROUP/hpx/blob/130deb29bd90bc263a8cb17713d7027818fd5ce1/hpx/parallel/algorithms/partition.hpp#L868-L871

Maybe there are same problems in other parallel algorithms.

**Comment by hkaiser** [comment]
@taeguk: please construct a test exposing the issue. We'll take it from there.

**Comment by taeguk** [comment]
@hkaiser Below, Can this be an evidence for this issue?
https://github.com/taeguk/hpx/commit/b846ca777544338ce30639386d8e166c6aa93cb4

**Comment by hkaiser** [comment]
@taeguk, looks good, could you separate this into a separate test [here](https://github.com/STEllAR-GROUP/hpx/tree/master/tests/regressions/parallel), please?

**Comment by taeguk** [comment]
@hkaiser As I think, adding my test code to there is strange because it is the code which has a bug on purpose. My test code will always fails. But normally, test is for not failing but success. So, inserting failed code to test folder can be confusing. The person who sees the test can misthink the test code doesn't have a bug.

**Comment by hkaiser** [comment]
@taeguk I really believe that having a test verifying that we have fixed the issue is needed. It will just force us to come up with a fix if we add it now and it fails. For each (significant) fix we usually add a corresponding test which makes sure that the problem is gone and stays gone.

**Comment by taeguk** [comment]
@hkaiser Yes, you're right. But the problem is that test code will always fail without modification of test code itself.

**Comment by hkaiser** [comment]
@taeguk I think this can be closed now, is that correct?

**Comment by taeguk** [comment]
@hkaiser No, it is not resolved yet.
