### ISSUE TITLE
Nested exception_list in parallel algorithm.

### ISSUE THREAD

**Issue by taeguk** [STEllAR-GROUP/hpx#2817]
Is nested ```exception_list``` admitted in parallel algorithm?

https://github.com/STEllAR-GROUP/hpx/blob/130deb29bd90bc263a8cb17713d7027818fd5ce1/hpx/parallel/algorithms/sort.hpp#L153-L169

For example, in case of ```parallel::sort```, there is nested ```exception_list```.
Because of recursive implementation of the algorithm, ```exception_list```s are inside of an ```exception_list``` and this structure is repeated and nested.
Is this okay? Or is this problem?

**Comment by hkaiser** [comment]
This shouldn't be an issue. Our `exception_list` was designed to support that. Could you try to construct a test which verifies this?

**Comment by taeguk** [comment]
@hkaiser I mean that currently nested ```exception_list``` seems to be not useful.
For example, when I call ```exception_list::get_message()```, it seems to 'just' iterate to exceptions that the exception_list has.
I think that traversal to nested exception_list is correct.
In fact, I don't know exactly what is right.
Is there no mention about this in p0322r0?

**Comment by hkaiser** [comment]
> For example, when I call `exception_list::get_message()`, it seems to 'just' iterate to exceptions that the `exception_list` has.

What else would you like to see?

> Is there no mention about this in p0322r0?

They ditched exception handling altogether. Any exception thrown will cause `std::terminate` to be called (for the `std` execution policies, other execution policies are free to do whatever they want).

**Comment by taeguk** [comment]
@hkaiser 
![image](https://user-images.githubusercontent.com/9107889/29235697-2ac282c8-7f3c-11e7-8472-be2c8cc8c568.png)
Like above, utilizing nested exception_list is difficult because of its tree structure.
So, I think avoiding nested exception_list may be better.
And currently, ```exception_list::get_message()``` can't process nested exception_list exactly because ```exception_list::get_message()``` just iterates in only first level of that tree structure.
In fact, this problem from nested exception_list can be not such important. I wanted to just reveal the issue to public space because an user can misunderstand like exception_list is not nested.
How do you think about it? Should this be resolved? Or is leaving this okay?

> They ditched exception handling altogether. Any exception thrown will cause std::terminate to be called (for the std execution policies, other execution policies are free to do whatever they want).

What plan do you have about it? Will you follow their way? Or Will you keep our way?

**Comment by hkaiser** [comment]
> What plan do you have about it? Will you follow their way? Or Will you keep our way?

For now I'd like to keep it as we have it as calling `std::terminate` just because of an exception being thrown is not an option, in my opinion.

**Comment by hkaiser** [comment]
> And currently,  exception_list::get_message()  can't process nested exception_list exactly because  exception_list::get_message()  just iterates in only first level of that tree structure.

That's correct. The user however can easily iterate over the tree using the public interface.
