### ISSUE TITLE
A strange thing in parallel::util::detail::handle_local_exceptions.

### ISSUE THREAD

**Issue by taeguk** [STEllAR-GROUP/hpx#2818]
https://github.com/STEllAR-GROUP/hpx/blob/76f7c3bc8eac51d73be7de4146b729335ce03c3f/hpx/parallel/util/detail/handle_local_exceptions.hpp#L29-L40

Does 'Line 38' make sense?
That function seems to just rethrow ```exception_ptr```.
As I think, 'Line 38' should be changed to
```cpp 
throw exception_list(std::current_exception());
```

**Comment by hkaiser** [comment]
@taeguk please construct a test which exposes the problem you believe we have.

**Comment by taeguk** [comment]
@hkaiser This is not bug which can be tested. This is the problem about intention of that function. And I want to just question about it.
I want to know what is the meaning of that function.
Is it intended that function just rethrows ```std::exception_ptr```?

https://github.com/STEllAR-GROUP/hpx/blob/76f7c3bc8eac51d73be7de4146b729335ce03c3f/hpx/parallel/util/detail/handle_local_exceptions.hpp#L56-L68
Like above, other overloaded functions of that function are related to ```exception_list```.
So, I guess that 'Line 38' is an mistake and changing to ```throw exception_list(std::current_exception());``` may be reasonable.
I can't determine whether my guessing is correct because that code is not written by me.

**Comment by hkaiser** [comment]
@taeguk you're right, this is a nice catch. I agree this has to be changed as you suggest. But a test would be nice anyways, mostly to ensure that those functions throw an `exception_list` under any circumstances.

**Comment by taeguk** [comment]
@hkaiser I want to change 'Line 38' to what I said.

**Comment by taeguk** [comment]
@hkaiser Do you agree that I change that?
With changing, handling exception for parallel algorithms can be abstracted as a function than explicitly coded. (https://github.com/taeguk/hpx/blob/f2d9cf60f692b50e81a69e78a93c54d0596a3294/hpx/parallel/algorithms/merge.hpp#L296-L304)

**Comment by hkaiser** [comment]
@taeguk, yes, please go ahead.
