### ISSUE TITLE
Yet another issue with wait_for similar to #2796

### ISSUE THREAD

**Issue by KADichev** [STEllAR-GROUP/hpx#2822]
I'm experiencing similar issues to the ones from #2796 . The fix #2797 resolved #2796, but the below example using BROADCAST_ACTION shows the same problem -- wait_for does not set the future state to "ready", even though it is ready:

**Comment by KADichev** [comment]
`#include <hpx/hpx_init.hpp>
#include <hpx/include/lcos.hpp>
#include <hpx/lcos/broadcast.hpp>
#include <hpx/util/lightweight_test.hpp>

#include
#include
#include

#include <signal.h>

const std::size_t N = 1024;
std::vector buffer(N);
using std::chrono::milliseconds;

void vector_bcast(std::vector bcast)
{
buffer = bcast;
}

HPX_PLAIN_ACTION(vector_bcast);

HPX_REGISTER_BROADCAST_ACTION_DECLARATION(vector_bcast_action)
HPX_REGISTER_BROADCAST_ACTION(vector_bcast_action)

int hpx_main()
{
hpx::id_type here = hpx::find_here();
hpx::id_type there = here;
std::vectorhpx::id_type localities = hpx::find_all_localities();
std::vector bcast_array(N);
for (std::size_t i=0; i<N; i++)
bcast_array[i] = 3.14;

for (std::size_t i = 0; i<5; i++) {
        auto f = hpx::lcos::broadcast<vector_bcast_action>(localities, bcast_array);
        //f.wait(); <- if we wait, it takes less than 1 sec and state is properly set
        if (f.wait_for(milliseconds(1000)) != hpx::lcos::future_status::ready)
                std::cout << "Loc: " << hpx::get_locality_id() << " Broadcast:" << i << " taking too long ...\n";
}
}`

**Comment by KADichev** [comment]
A side comment here: I am not entirely sure if the future state being "ready" at the root process (once this issue is resolved) means that the root has completed the broadcast, or that all localities have completed the broadcast?

**Comment by hkaiser** [comment]
> A side comment here: I am not entirely sure if the future state being "ready" at the root process (once this issue is resolved) means that the root (here: locality 0) has completed the broadcast, or that all localities have completed the broadcast?

The returned future becomes ready whenever all localities have finished responding.
