### ISSUE TITLE
failure to compile hello_world example with -Werror

### ISSUE THREAD

**Issue by Dekken** [STEllAR-GROUP/hpx#2827]
compiler: gcc 7.1.0
system: debian 9 (stretch)
kernel: 4.11

[link](https://gist.github.com/Dekken/04b3a8aba30dc339e8b66fd69898b60b)

no worries if it's to be ignored etc.

**Comment by hkaiser** [comment]
Please configure HPX with `cmake -DHPX_WITH_CXX14=ON ...`. This is a known issue in Boost caused by it being released before gcc 7.

**Comment by hkaiser** [comment]
We will fix the warnings as much as we can, but we have no way of fixing the warning in Boost. Thanks for reporting!

**Comment by hkaiser** [comment]
The aliasing (type punning) warning has been acknowledged to be a gcc bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80593) and will be fixed in gcc 7.2.

**Comment by Dekken** [comment]
yeah it was more the punning one,  cheers HK

**Comment by Dekken** [comment]
will give it a go so now that 7.2 is out

https://gcc.gnu.org/ml/gcc/2017-08/msg00129.html

**Comment by Dekken** [comment]
Indeed the type punned alerts are gone, only thing left other than boost issues is 

```
include/hpx/runtime/serialization/string.hpp:23:64: error: typedef ‘string_type’ locally defined but not used [-Werror=unused-local-typedefs]
         typedef std::basic_string<Char, CharTraits, Allocator> string_type;
```

**Comment by hkaiser** [comment]
> Indeed the type punned alerts are gone, only thing left other than boost issues is 
>
> ```
> include/hpx/runtime/serialization/string.hpp:23:64: error: typedef ‘string_type’ locally defined but not > used [-Werror=unused-local-typedefs]
>          typedef std::basic_string<Char, CharTraits, Allocator> string_type;
> ```

@Dekken that's fixed on master: https://github.com/STEllAR-GROUP/hpx/commit/ed3066225e72c9f751bc9ea9e85939e23759e0ff

Thanks!
