### ISSUE TITLE
`parallel/executors/execution_fwd.hpp` causes compilation failure in C++11 mode.

### ISSUE THREAD

**Issue by Element-126** [STEllAR-GROUP/hpx#2831]
cmake -D CMAKE_INSTALL_PREFIX=/home/jtastet/.local/stow/hpx-c++11_gcc-5.3 \
          -D HPX_WITH_MALLOC=jemalloc \
          -D HPX_WITH_PARCELPORT_MPI=ON \
          -D HPX_WITH_CXX11=ON \
          -D HPX_WITH_CXX14=OFF \
          -D HPX_WITH_CXX0Y=OFF ..

Revision: `2b2d3a0321b30b143c2483be316ca2ba5630e8f5`
Compiler: g++ 5.3.0
See the CMake output for the detailed version info of the dependencies.

Relevant part of the build output ([full log attached](https://github.com/STEllAR-GROUP/hpx/files/1221701/build_log_c.11.txt)):

    ...
    -- C++ mode enforced: C++11
    ...

    ...
    [  7%] Building CXX object src/CMakeFiles/hpx.dir/runtime/actions/detail/action_factory.cpp.o
    In file included from /home/jtastet/software/hpx/hpx/parallel/executors/execution.hpp:13:0,
                 from /home/jtastet/software/hpx/hpx/lcos/local/packaged_continuation.hpp:27,
                 from /home/jtastet/software/hpx/hpx/lcos/future.hpp:1485,
                 from /home/jtastet/software/hpx/hpx/runtime/basename_registration.hpp:14,
                 from /home/jtastet/software/hpx/hpx/runtime_fwd.hpp:14,
                 from /home/jtastet/software/hpx/hpx/runtime.hpp:21,
                 from /home/jtastet/software/hpx/src/state.cpp:10:
    /home/jtastet/software/hpx/hpx/parallel/executors/execution_fwd.hpp:83:68: error: 'operator()' function uses 'auto' type specifier without trailing return type
             auto operator()(Executor && exec, F && f, Ts &&... ts) const;
                                                                    ^
    /home/jtastet/software/hpx/hpx/parallel/executors/execution_fwd.hpp:83:68: note: deduced return type only available with -std=c++14 or -std=gnu++14
    /home/jtastet/software/hpx/hpx/parallel/executors/execution_fwd.hpp:91:68: error: 'operator()' function uses 'auto' type specifier without trailing return type
             auto operator()(Executor && exec, F && f, Ts &&... ts) const;
                                                                    ^
    /home/jtastet/software/hpx/hpx/parallel/executors/execution_fwd.hpp:91:68: note: deduced return type only available with -std=c++14 or -std=gnu++14
    /home/jtastet/software/hpx/hpx/parallel/executors/execution_fwd.hpp:99:68: error: 'operator()' function uses 'auto' type specifier without trailing return type
             auto operator()(Executor && exec, F && f, Ts &&... ts) const;
    ...

There are a few dozen similar errors, all complaining about the use of the `auto` specifier without trailing return type.

**Comment by taeguk** [comment]
@Element-126 This was fixed in #2821 .
That PR will be merged soon.

**Comment by Element-126** [comment]
Oh, I missed it when looking at the current issues ! Sorry for the spam then. I'm closing the issue.
