### ISSUE TITLE
`constexpr` functions with `void` return type break compilation with CUDA 8.0.

### ISSUE THREAD

**Issue by Element-126** [STEllAR-GROUP/hpx#2835]
Hi, I'm your new build bot ;-)

    cmake -D CMAKE_INSTALL_PREFIX=/home/jtastet/.local/stow/hpx_cuda-8.0 \
          -D HPX_WITH_MALLOC=jemalloc \
          -D HPX_WITH_PARCELPORT_MPI=ON \
          -D HPX_WITH_CXX14=OFF \
          -D HPX_WITH_CUDA=ON \
          -D HPX_WITH_CUDA_ARCH=sm_61 \
          ..

    -- The CXX compiler identification is GNU 5.3.0
    -- The C compiler identification is GNU 5.3.0
    ...
    -- Found CUDA: /usr/local/cuda-8.0 (found version "8.0")
    ...
    -- C++ mode used: C++11
    ...

    
with revision `188c202298d590e5b646ced2d57477a83949d772`, results in:

    /home/jtastet/software/hpx/hpx/util/detail/pack_traversal_impl.hpp(370): error: a constexpr function cannot have a nonliteral return type "void"

[Full build log attached.](https://github.com/STEllAR-GROUP/hpx/files/1224780/hpx-cuda8_build_log.txt)

This is due to the `constexpr` function `reserve_if_possible()` in `pack_traversal_impl.hpp` returning `void`, which is not valid C++11. It was introduced in C++14.

I must admit I don't quite get why it does not break the build when compiling in C++11 mode _without_ CUDA.

I tried the following patch, which is arguably overkill since it amounts to disabling `constexpr` altogether when NVCC is used:

```diff
diff --git a/hpx/config/constexpr.hpp b/hpx/config/constexpr.hpp
index d98a208..5e49e69 100644
--- a/hpx/config/constexpr.hpp
+++ b/hpx/config/constexpr.hpp
@@ -9,7 +9,7 @@
 
 #include <hpx/config/defines.hpp>
 
-#if defined(HPX_HAVE_CXX11_CONSTEXPR) && !defined(HPX_MSVC_NVCC)
+#if defined(HPX_HAVE_CXX11_CONSTEXPR) && !defined(__NVCC__)
 #   define HPX_CONSTEXPR constexpr
 #   define HPX_CONSTEXPR_OR_CONST constexpr
 #else
```

It does indeed fix the HPX build, but then the test suite fails to compile due to #2825 ([full log attached](https://github.com/STEllAR-GROUP/hpx/files/1224805/hpx_fix-cuda8-void-constexpr_build_log.txt.zip)).

**Comment by hkaiser** [comment]
@AntonBikineev could you change the `void` functions to not be `constexpr`, please?

**Comment by hkaiser** [comment]
@Element-126 The test failures have already been reported here #2825. We have no solution to this yet, sorry. The issues are caused by NVCC being a fairly brain-dead compiler...

**Comment by AntonBikineev** [comment]
@hkaiser: sorry, I missed the message. Do you want me to change those functions to not be constexpr or we shouldn't do anything?

**Comment by hkaiser** [comment]
@AntonBikineev let's make those functions non-constexpr for now.

**Comment by Naios** [comment]
-> #2840
