### ISSUE TITLE
Calling a __host__ function from a (__host__) __device__ function breaks HPX build with NVCC 9 in C++14 mode

### ISSUE THREAD

**Issue by JLTastet** [STEllAR-GROUP/hpx#2838]
Since I don't know when Nvidia will fix the issue regarding `__CUDACC_VER__`, responsible for #2815, I manually modified the relevant header to define it to a meaningful value:
```diff
diff a/usr/local/cuda-9.0/include/crt/common_functions.h b/usr/local/cuda-9.0/include/crt/common_functions.h
-#define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
+#define __CUDACC_VER__ 90000
```

This allows the HPX build to progress slightly further, but then we encounter another issue, which seems to be on our side this time.

Compiling HPX with the following configuration:
```cmake
cmake -D CMAKE_INSTALL_PREFIX=/home/jtastet/.local/stow/hpx_cuda-9.0 \
      -D HPX_WITH_CUDA=ON \
      -D HPX_WITH_CXX14=ON \
      -D HPX_WITH_MALLOC=jemalloc \
      -D HPX_WITH_PARCELPORT_MPI=ON \
      -D HPX_WITH_CUDA_ARCH="sm_35;sm_61" \
      ..
```
results in a whopping [1.2MB of compiler output](https://github.com/STEllAR-GROUP/hpx/files/1228475/hpx_cuda-9.0_build_log.txt), mostly consisting of errors similar to the following one:
```
/afs/cern.ch/sw/lcg/contrib/gcc/6.3.0/x86_64-centos7/include/c++/6.3.0/bits/basic_string.h(2406): error: calling a __host__ function("std::char_traits<char> ::compare") from a __device__ function("s
td::less< ::std::__cxx11::basic_string<char,  ::std::char_traits<char> , std::allocator<char> > > ::operator () const") is not allowed

/afs/cern.ch/sw/lcg/contrib/gcc/6.3.0/x86_64-centos7/include/c++/6.3.0/bits/basic_string.h(2406): error: identifier "std::char_traits<char> ::compare" is undefined in device code

/afs/cern.ch/sw/lcg/contrib/gcc/6.3.0/x86_64-centos7/include/c++/6.3.0/bits/basic_string.h(2408): error: calling a __host__ function("std::__cxx11::basic_string<char,  ::std::char_traits<char> , std
::allocator<char> > ::_S_compare") from a __device__ function("std::less< ::std::__cxx11::basic_string<char,  ::std::char_traits<char> , std::allocator<char> > > ::operator () const") is not allowed

/afs/cern.ch/sw/lcg/contrib/gcc/6.3.0/x86_64-centos7/include/c++/6.3.0/bits/basic_string.h(2408): error: identifier "std::__cxx11::basic_string<char,  ::std::char_traits<char> , std::allocator<char>
 > ::_S_compare" is undefined in device code
```
i.e. STL functions not marked with `__host__ __device__` are not available in device code.

Since the errors occur in heavily templated code, the compiler warnings might be more helpful. I believe that the following one, which appears 224 times (out of 247 total warnings) in the build output, is the most relevant:
```
warning: calling a __host__ function from a __host__ __device__ function is not allowed
```

So it seems that we are calling lots of STL functions (which are only `__host__` by default) from generic `__host__ __device__` functions. But calling `__host__` functions from `__device__` code makes NVCC pretty angry (although it is perfectly legal in the Clang CUDA dialect ; see table 1 in [this article](https://research.google.com/pubs/pub45226.html)).

**Comment by hkaiser** [comment]
FWIW, I'd be fine with not supporting NVCC if we can get Clang to work properly.

**Comment by Element-126** [comment]
@hkaiser I will try to conduct some benchmarks of NVCC vs. Clang on some (optimized) internal code relevant for my current project. If the performance when compiling with Clang roughly matches or exceeds the one with NVCC, then I will probably focus my efforts on getting HPX to work flawlessly with Clang. Otherwise it will be much harder to justify using it to the people who pay the lab's bills :-)

Additionally, documentation about CUDA Clang is quite scarce and I don't really know how actively it is being developed, besides the initial contribution by Google.

On the other hand, if the Clang developers are committed to maintaining the CUDA support and if the performance is good, then having a full fledged, C++17 conformant compiler could significantly ease the development of new features dedicated to GPU support, and it would save us some manpower.

I will take a look at their mailing list to try to take the pulse of the CUDA Clang development.

**Comment by hkaiser** [comment]
@Element-126 FWIW, I have been approached by the people at google developing the CUDA support offering help and support whenever we need it. Just let me know and I'll put you in contact.

**Comment by sithhell** [comment]
The warnings you are seeing can be ignored. They are benign in the sense that if a `__host__ __device__` indeed calls a `__host__` function when being compiled in device mode, you will get a hard error. the [cuda_clang](https://github.com/STEllAR-GROUP/hpx/tree/cuda_clang) has this warning turned of. Would you mind retrying with this branch?
