### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by Dekken** [STEllAR-GROUP/hpx#2852]
Hi there,

I tried to build this on an ARM64 board but couldn't get it building due to "unsupported platform" within the coroutines section. [link](https://github.com/STEllAR-GROUP/hpx/blob/master/src/runtime/threads/coroutines/swapcontext.cpp)

I've done some tinkering with boost context on ARM64 and it seems to work, is there a possibility of using that or something else?

**Comment by hkaiser** [comment]
On ARM/ARM64 you need to build HPX using Boost.Context. Please add `-DHPX_WITH_GENERIC_CONTEXT_COROUTINES=ON` to the cmake command line.

**Comment by Dekken** [comment]
oh that's convenient ^_^

**Comment by Dekken** [comment]
issue with timestamps too
