### ISSUE TITLE
sched_getcpu not available on MacOS

### ISSUE THREAD

**Issue by kleinhenz** [STEllAR-GROUP/hpx#2862]
On MacOS `hpx/examples/resource_partitioner/simple_resource_partitioner.cpp` fails to compile on the current master because `hpx/examples/resource_partitioner/shared_priority_scheduler.hpp` includes `parcelport_logging.hpp` which uses the `sched_getcpu` system call which is not part of `sched.h` on MacOS. This include is currently protected by a `#if !defined(HPX_MSVC)` which should probably be expanded to check for MacOS as well or else implemented in a more portable way. The `sched_getcpu` call was added in ecb798fff31c0aa729626f0bbc6281dfa4683a8b.

**Comment by hkaiser** [comment]
@biddisco Could you take care of this, please?
