### ISSUE TITLE
The chunk_size_iterator violates multipass guarantee.

### ISSUE THREAD

**Issue by taeguk** [STEllAR-GROUP/hpx#2866]
https://github.com/STEllAR-GROUP/hpx/blob/e0f0ed18af6a5dd90c9bbc209fb59b7d87b15f64/hpx/parallel/util/detail/chunk_size_iterator.hpp#L23-L85
The ```chunk_size_iterator``` has forward iterator tag. But, it violates multipass guarantee.
```c++
// The 'iter' is chunk_size_iterator.
auto const& elem = *iter++;
...(usage of elem)...
```
Above code has a bug because the data which ```elem``` referenced is changed when ```iter``` is incremented.
Really, I encounted that bug, I consumed my much time for finding bug and fixing it.

http://en.cppreference.com/w/cpp/concept/ForwardIterator
As you can see from the link above, forward iterator tag must satisfy multipass guarantee.
But, the ```chunk_size_iterator``` isn't.
So, I think that the ```chunk_size_iterator``` should be classified to input iterator tag.

**Comment by hkaiser** [comment]
Excellent catch! please prepare a PR for this.
