### ISSUE TITLE
linking `-latomic` is not portable

### ISSUE THREAD

**Issue by kleinhenz** [STEllAR-GROUP/hpx#2884]
This [commit](https://github.com/STEllAR-GROUP/hpx/commit/e40a003720c0ef95d5f0cebd51a484f12dd43861) which replaces boost atomic with std::atomic automatically links `-latomic` when testing for std::atomic support and in the main CMake script. Unfortunately this is in general not completely portable and in particular breaks compilation on macos with Clang where there is no `libatomic`. As I understand it for reasons that are unclear to me gcc chose to implement fallbacks for lock free routines in `libatomic` instead of of `libstdc++` but this is not standardized across compilers. It seems that something like [this](https://github.com/llvm-mirror/llvm/blob/master/cmake/modules/CheckAtomic.cmake) is necessary to do this portably.

**Comment by hkaiser** [comment]
@K-ballo what's your take on this?

**Comment by K-ballo** [comment]
Let's add the check.

**Comment by K-ballo** [comment]
Added the check to `libatomic-check` branch. Local builds and CI look ok, but I do not have access to macos to test.

@kleinhenz could you give it a try and report whether it works as needed?

**Comment by kleinhenz** [comment]
Works for me. Thanks!
