### ISSUE TITLE
collecting idle-rate performance counters on multiple localities produces an error

### ISSUE THREAD

**Issue by zbyerly** [STEllAR-GROUP/hpx#2905]
collecting idle-rate performance counters (on hello_world) on multiple localities produces the error:
pool 1 (zero-based index) requested out of bounds. The partitioner owns only 1 pools: HPX(bad_parameter)

running this sbatch script on Rostam:
https://gist.github.com/zbyerly/b06bfd32567c677e15c4483f76819c89

produces this:
https://gist.github.com/zbyerly/8fed68788ff317590f242e46905d6f44

**Comment by hkaiser** [comment]
Thanks for reporting. This is a genuine bug introduced by the recent introduction of the resource-partitioner and the related changes to the performance counters
