### ISSUE TITLE
--hpx:help triggers unusual error with clang build

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2931]
hello world gives error when `--hpx:help` is used and when hpx is compiled with clang.
most unusual.
 
```sh
bin/hello_world --hpx:help
... usual help output is dumped here ...
terminating with uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument
Aborted (core dumped)
```

**Comment by kleinhenz** [comment]
I am also getting this error on macOS with clang 5.0.0

**Comment by hkaiser** [comment]
Does this happen in Debug as well? Would it be possible to pinpoint the `recursive_mutex` instance it's complaining about?

**Comment by kleinhenz** [comment]
I get the same error in the Debug build of hpx but unfortunately the error does not appear when run in lldb so I wasn't able to get a backtrace.
