### ISSUE TITLE
hpx.ini is not used correctly at initialization

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#2947]
Using an `hpx.ini` file to set the number of threads for hpx does not work, i.e. a file `hpx.ini`:
```
[hpx]
os_threads = n
```
which is loaded with `--hpx:config=hpx.ini` (same directory as executable) does not change `os_threads` (confirmed with `--hpx:dump-config`).

Changing the number of threads with `--hpx:ini=hpx.os_threads=n` or `--hpx:threads=n` works correctly.

This does not affect all config values. I was able to change for example the stack sizes.

**Comment by hkaiser** [comment]
Confirmed - will fix.

**Comment by hkaiser** [comment]
@msimberg please verify whether #2953 is fixing your problem.

**Comment by msimberg** [comment]
@hkaiser Thanks, this mostly fixes the problem. It seems like it sets the default number of threads to 1 though rather than the number of cores.

It also seems like it doesn't pick up any of the other ways of setting the ini file (HPX_INI, PWD, HOME etc.). If I set *any* valid path with --hpx:config it does load an ini file from those locations as well. Not sure if this is related or not. Should I open a separate issue for that?

**Comment by hkaiser** [comment]
> It seems like it sets the default number of threads to 1 though rather than the number of cores.

Confirmed, thanks for noticing this. Should be fixed now.

> It also seems like it doesn't pick up any of the other ways of setting the ini file (HPX_INI, PWD, HOME etc.). If I set any valid path with --hpx:config it does load an ini file from those locations as well. Not sure if this is related or not. 

Could it be a matter of which file takes precedence? OTO, it might be fixed by the change I made.

> Should I open a separate issue for that?

No need, I think.

**Comment by msimberg** [comment]
The original issue is solved now, thank you! The additional issue of loading from HPX_INI etc. still remains though.

**Comment by hkaiser** [comment]
@msimberg Could you explain one more time how to reproduce the issue you're trying to report, please? I'm not sure I understood what you're after.

**Comment by msimberg** [comment]
All good now, thank you!

(For the record, the second issue was that an ini file gets loaded automatically from `PWD`, `HOME` etc. only when the `--hpx:config` option is set.)
