### ISSUE TITLE
Fix OS-Thread throttling

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#2955]
The current behavior of attempting to shut down an entire OS thread when dynamically removing a PU from a thread pool seems to be not a good idea.

We should rather add a condition variable which checks if the OS thread is enabled or not and waits for the proper condition. This will be a clean solution and will not meddle with the shutdown procedure.

**Comment by hkaiser** [comment]
We already have this condition-variable: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/policies/scheduler_base.hpp#L360

**Comment by hkaiser** [comment]
@sithhell can this be closed now?

**Comment by msimberg** [comment]
I think this can be closed now. @sithhell please reopen if you disagree.
