### ISSUE TITLE
Instantiation of local_priority_queue_os_executor always fails

### ISSUE THREAD

**Issue by chinz07** [STEllAR-GROUP/hpx#2960]
During the initialization, the executor tries to access a pool with the ID "local_priority_queue_scheduler#1" which does not exist and subsequently throws an exception. If I use HPX 1.0.0 the failure disappears.

The following example reproduces the problem:
``` C++
#include <hpx/hpx_main.hpp>

#include <hpx/include/thread_executors.hpp>

int main()
{
    hpx::threads::executors::local_priority_queue_os_executor exec(1);

    return 0;
}
```

**Comment by hkaiser** [comment]
The whole threading subsystem is currently in a state of flux. We have not gotten back to the higher-levels (i.e. executors) yet.

**Comment by chinz07** [comment]
Since I have migrated my code to pool_executor anyway, fixing this is not a priority for me. I just wanted to make sure that this bug will not be overlooked after the threading subsystem has settled down.

**Comment by Praveenv98** [comment]
@chinz07 I think HPX 1.1.0 still has this problem though

**Comment by chinz07** [comment]
@Praveenv98 Yes. I just wanted to point out that I agree that it might not make sense to fix this bug just yet but to wait until the underlying system is stable again. I don't wanted to imply that this issue should be closed. Sorry for the confusion.

**Comment by hkaiser** [comment]
A first analysis shows that the executors of this type (i.e. the ones spawning new 'real' threads) have to be significantly adapted to the changes introduced by the resource partitioner. I'm not 100% sure how to proceed.

These schedulers currently attempt to access a pool from the resource partitioner which does not exist. Thus the user either has to explicitly create such a pool upfront (before launching HPX) or we have to add functionalities to the resource partitioner allowing to add pools later on (after HPX has been started).

**Comment by biddisco** [comment]
What is the use case for executors spawning "real threads"? 
(If the user is writing code that requires the spawning tasks on 'extra' threads that were not part of the original allocation at startup, then it does not seem unreasonable to expect them to reserve some resources for their use with the resource partitioner at startup).

**Comment by biddisco** [comment]
If the use case is that the runs with one or more pools and at some point wants to create an extra thread (oversubscription) on the fly, put some tasks on it, then the obvious way to proceed to to create a dynamic pool at startup that has no threads assigned initially, and have these OS thread executors use the add_pu type functionality that we planned fot the resource partitioner, to create threads in that oversubscription pool and for them to delete themselves when the executor responsible for their creation goes out of scope and all tasks that were spawned on the thread have completed.
