### ISSUE TITLE
Make hwloc compulsory instead of optional

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2977]
As suggested in #2923 - we should make hwloc a requirement rather than an optional dependency.

Things to do

- Remove abstract topology class and virtual interface to hwloc_topology
- upgrade to hwloc 2.0 API (Due for release end Nov 2017)
- Improve CMake integration to allow hwloc 2.0 to be downloaded and built as part of the hpx compilation step if it is not found on the system. This may not be possible on _all_ platforms, but should be done where supported/possible.

**Comment by hkaiser** [comment]
Thanks John, this is the right step. I would however advise against integrating downloading/building of hwloc into our build system. Our build system is sufficiently complex as it is without that. If we followed that route we would need to do the same with Boost.

Let's rather create proper documentation on how to install hwloc if it's not available (or provide a separate (python) script for this).
