### ISSUE TITLE
Executor consolidation and clarification/documentation

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2997]
Documentation for the following is incomplete/scarce and some executors may no longer be required.
As part of the ongoing cleaning up caused by the introduction of the resource_partitioner, and with a potential 1.1 release planned, the following executors need to be documented and/or deprecated.

The following exist in the runtime/threads or parallel namespaces
- pool_executor
creates tasks that are scheduled on the named thread pool. The thread pool is created at startup by the resource manager and may be customized by the user.
- thread_pool_executor
- thread_pool_attached_executor
- thread_pool_os_executor
- this_thread_executor
- thread_executor
- current_executor
- default_executor
creates tasks by default on the same pool as the parent task. I believe that this executor should be a subclass of pool_executor and should have an additional default-policy constructor option that allows the user to select between
    - running the task on the same pool as the previous/parent task
    - running the task on the "default pool" 
- distribution_policy_executor
creates executors using any of the existing distribution policies (like hpx::components::colocating_distribution_policy et.al.).
- rebind_executor
- sequenced_executor
creates groups of sequential execution agents which execute in the calling thread. The sequential order is given by the lexicographical order of indices in the index space.
- parallel_executor
creates groups of parallel execution agents which execute in threads implicitly created by the executor. This executor uses a given launch policy.
- service_executor
creates groups of parallel execution agents which execute in one of the kernel threads associated with a given pool category (I/O, parcel, or timer pool, or on the main thread of the application).
- timed_executor

Additional executors exist in the compute:: namespace 
- block_executor
Spawns tasks on a vector of target resources (such as numa domains). Needs work to be integrated into the numa domain definitions provided by the resource_manager. 
- concurrent_executor
- default_executor

Additional executors exist for specific scheduler types, these create executors on top of the corresponding HPX schedulers.
- local_priority_queue_executor, 
- local_queue_executor 
- static_priority_queue_executor 
And with an os_ prefix
- local_queue_os_executor
- static_queue_os_executor
- local_priority_queue_os_executor
- static_priority_queue_os_executor
- local_queue_os_executor

Please add a short description to this issue for each of the executor names describing what they do and if they can be removed, please state so. if duplicates or errors exist, please say so. Once all executors have been described or obsoleted, I will produce some documentation and start cleaning up where applicable.

**Comment by biddisco** [comment]
This issue attracted remarkably little attention, so I'm just adding this comment to draw attention to it, now that the dashboard is getting greener.

**Comment by biddisco** [comment]
Reopening this because I'd like to document the executors better (and clean them up) eventually.

**Comment by msimberg** [comment]
There are a number of executors that are based on (as far as I can tell) the very old executor interface (with `add`, `add_at`, `add_after`) that I think we should seriously consider removing or rewriting:

- `pool_executor` and `service_executor`: These are essentially (useful) wrapper executors for thread pools that already exist, and could be rewritten using the `post/async_execute/...` interface (with `thread_pool_executor`). Is it worth it to wait for the newer executor interface before rewriting?
- `thread_pool_embedded_executor`: Is there real value in changing the scheduler in an embedded thread pool? Is anyone actually using these? For the use case of restricting execution to a subset of PUs I think the `block_executor` is a valid replacement as `thread_pool_embedded_executor` can't actually guarantee that the embedded scheduler worker threads don't get stolen.
- `thread_pool_os_executor`: This can be replaced by `thread_pool_executor`. If the convenience of creating a thread pool in the executor constructor is worth it we can provide that.
- `this_thread_executor`: Replaced by scheduling hints.
- `thread_pool_attached_executor`: Replaced by `block_executor`.
- `current_executor`: Replace with `thread_pool_executor` and supply the current scheduler.
- `default_executor`: This one doesn't have a direct replacement yet, but we can make `parallel_executor` and `sequenced_executor` take priority, scheduling hint, and stacksize as constructor parameters. And then typedef `default_executor` to `parallel_executor`.

It seems to me that the main value of the interface are the timed `add` member functions, but is someone using them directly (certainly not through `async`/`apply`/`then`...)?
