### ISSUE TITLE
Change thread scheduling use of size_t for thread indexing

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#2999]
Currently, the main thread_init_data structures and create_thread, register_thread (&etc) API, make use of a std::size_t parameter that is used to represent the thread number that a task should be assigned to.

In the majority of cases, the thread_num used is std::size_t(-1) and the assignment of task->thread is made by the scheduler based on a round robin assignment, or some other criteria which may be scheduler dependent.

In some limited cases, such as background_thread_create, the thread_num is used for a valid index based on the number of threads in a certain pool.

I would like to replace the use of std::size_t with a thread_schedule_hint struct type that can hold a thread number (when necessary) and a numa_domain, to make it posible to pass information from executors to schedulers to schedule a task on either a core/pu or a numa domain.  Current experiments are using a structure of this kind with success
```
struct thread_schedule_hint {
    uint16_t thread_num; 
    uint16_t numa_domain;
};
```
A value of uint16_t(-1) for thread_num or numa_domain indicates that the value should be ignored, allowing {-1,2} to specify any thread on numa_domain 2 and {1,1} to specify thread 1 on numa_domain 1. etc...

Changing to a schedule_hint type will allow for future expansion to handle other 'hint' types by adding fields to the struct as needed.

Some executors do not make use of schedulers (true?) and some do not have a concept of numa_domains - and therefore a more suitable name or structure than thread_schedule_hint might be appropriate - suggestions welcome.

**Comment by msimberg** [comment]
Closing because of #3415.
