### ISSUE TITLE
Resource partitioner documentation

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3002]
Currently the resource partitioner lacks any kind of documentation except examples. It would be good to have some documentation before the next release.

**Comment by tapaswenipathak** [comment]
I think this ticket can be closed https://github.com/STEllAR-GROUP/hpx/blob/master/docs/sphinx/manual/hpx_runtime_and_resources.rst#the-hpx-resource-partitioner?

**Comment by msimberg** [comment]
@tapaswenipathak yep. There could be more documentation on it, but I think it's enough to close this.

**Comment by tapaswenipathak** [comment]
🆗 🎉
