### ISSUE TITLE
Proposing " Async Graph's and its Dataflow operators to HPX  using RDD's " 

### ISSUE THREAD

**Issue by preejackie** [STEllAR-GROUP/hpx#3005]
Hi 
This is basic idea for implementing Distributed Graphs in HPX runtime system. I have attached the link to google docs and 2 apache spark papers which present this idea. I hope implementing this will not disobey any of HPX laws (slow). It will be useful for Large scale applications (BIG DATA) where mutating data is not encouraged and needed such as data analytics, scientific applications etc. 
Please have a look @ [https://docs.google.com/document/d/1zH1PUhy37QsvzjoA8BPlvIqlUqFozJaPsePQ0Zo_3m0/edit?usp=sharing](url)

Graphx Paper : https://amplab.cs.berkeley.edu/wp-content/uploads/2014/09/graphx.pdf
RDD     Paper : http://people.csail.mit.edu/matei/papers/2012/nsdi_spark.pdf

Any comments and ideas are highly welcome : ) 
@hkaiser @sithhell @biddisco

**Comment by pree-jackie** [comment]
please copy and paste the link below 
https://docs.google.com/document/d/1zH1PUhy37QsvzjoA8BPlvIqlUqFozJaPsePQ0Zo_3m0/edit?usp=sharing

**Comment by hkaiser** [comment]
@pree-jackie have you seen this: https://github.com/STEllAR-GROUP/hpxflow?

**Comment by pree-jackie** [comment]
@hkaiser 
Have you read the google docs ? I think hpx-flow is more specific for stream processing. But the above specified Resilient Distributed Datasets gives the abstraction over distributed memory, and HPX-FLOW is not for Distributed Graph & its parallel algorithms as far as I know.
Above papers present some good way for representing Distributed Graphs.
Thanks
pree

**Comment by pree-jackie** [comment]
This represents a possible way for having Graph component in HPX like partitioned vector, unorder map, and co-arrays. But I didn't think HPX-flow helps in creating distributed graphs for me. 
@hkaiser  If you require some more explanation please let me know
