### ISSUE TITLE
HPX does not compile on POWER8 with gcc 5.4

### ISSUE THREAD

**Issue by teonnik** [STEllAR-GROUP/hpx#3014]
I encountered an issue building HPX on a POWER8 machine with gcc 5.4. Attached below are the `cmake` and `make` outputs. `cmake` runs without problems, `make` however fails.

System information

```shell
Linux juron1-adm 3.10.0-514.26.2.el7.ppc64le #1 SMP Mon Jul 10 02:18:17 GMT 2017 ppc64le ppc64le ppc64le GNU/Linux
```

[hpx-make.txt](https://github.com/STEllAR-GROUP/hpx/files/1484013/hpx-make.txt)
[hpx-cmake.txt](https://github.com/STEllAR-GROUP/hpx/files/1484014/hpx-cmake.txt)

**Comment by sithhell** [comment]
Hi,

This is a known issue with 1.0 and has been fixed already on master. We are
planning on having a new release soon.

**Comment by msimberg** [comment]
Closing as this is fixed in master.
