### ISSUE TITLE
Fix partitioner arg copy found in #2982

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3032]
The clang tidy fixes highlit a fix here https://github.com/STEllAR-GROUP/hpx/pull/2982/files/69463c83e47825205fbb10147b2d97b6726e1242#diff-f3b3662ac867dc1cda39d2ac7ce31ff2
that need to be addressed in a separate PR.

**Comment by hkaiser** [comment]
That links goes into nowhere, could you be a bit more specific, please?

**Comment by biddisco** [comment]
It looks as though @sithhell pushed a new commit that addresses the issue (and invalidates the link). If that is the case, then this issue can be closed immediately.

**Comment by sithhell** [comment]
Yes, this issue is resolved within #2982.
