### ISSUE TITLE
Use C++17 structured bindings for serialization

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#3034]
In addition to the HPX serialization allowing to automatically serialize empty structs without explicit serialization functions we should add support for serializing brace-initializable types using structured bindings available in C++17 (see here for some examples: http://playfulprogramming.blogspot.com/2016/12/serializing-structs-with-c17-structured.html).

**Comment by raymonwhite42** [comment]
I'll work on this soon.

**Comment by hkaiser** [comment]
FWIW, serialization of empty types is handled here: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/serialization/access.hpp#L101.

**Comment by shantanudwvd** [comment]
hi,
i would like to work on this. Can anyone guide me?

**Comment by hkaiser** [comment]
@shantanudwvd have you read the article linked above?

**Comment by shantanudwvd** [comment]
Yes I have read it. 




Get Outlook for Android







On Thu, Mar 22, 2018 at 10:13 PM +0530, "Hartmut Kaiser" <notifications@github.com> wrote:












@shantanudwvd have you read the article linked above?

**Comment by hkaiser** [comment]
> Yes I have read it.

Good, so what's you question? Also, I think we might be better off discussing this either on IRC or on the mailing list.

**Comment by shantanudwvd** [comment]
i'm quite comfortable with c++ but i'm new to this. So can you please guide me?

**Comment by hkaiser** [comment]
FWIW, here is an example where this technique was used: https://cista.rocks/.

**Comment by hkaiser** [comment]
This can be closed as #3625 was merged
