### ISSUE TITLE
Make building of distributed containers optional

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#3037]
One of the reasons our Circle-CI is taking so long is due to compiling the distributed container test cases.
I propose to make building the containers optional (defaulting to on), so that we have a chance to disable them for Circle-CI to have faster build round trips.
So the distributed containers would only be tested on rostam until the compile time and memory problems have been fixed.

What's the general opinion here?

**Comment by hkaiser** [comment]
We could enable them for the master branch only, avoiding to build them by default for PRs.

**Comment by msimberg** [comment]
@hkaiser please see #3265.
