### ISSUE TITLE
Fix/remove failing or outdated examples

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3049]
Broken examples:
- [x] `nqueen` (#3048)
- [x] `quickstart` (#3013)
- [x] `qt` (#3051)
- [ ] `jacobi`
- [ ] `jacobi_smp`
- [X] `quicksort` (#3226, #3236)
- [x] `init_globally` (#3211)

Examples to be removed:
- [x] `allgather`

Please update or comment if you know of examples that fail or should be removed.

**Comment by sithhell** [comment]
Outdated candidates are:
[ ] `sheneos`
[ ] `interpolate1d`
[ ] `allgather`

**Comment by hkaiser** [comment]
I'd agree for allgather to be outdated, sheneos/interpolated1d are not

**Comment by msimberg** [comment]
Closing this in favor of individual tickets for remaining failures (and milestones)
