### ISSUE TITLE
Remove thread_pool_executors

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3077]
The `thread_pool_executor`s are currently broken (and have been for a while - the `thread_pool_executors` test hangs occasionally) and serve no real purpose now that one can suspend threads. It does not seem worth the effort to fix them.

**Comment by hkaiser** [comment]
I agree. We should provide alternatives for this when removing them, however. In the end it boils down to providing proper documentation explaining how to replace them.

**Comment by biddisco** [comment]
As per #2997  - if soome can tell me what these executors are for, I will have a go at doing some replacement/cleanup.
