### ISSUE TITLE
Combine namespaces hpx::agas and hpx::naming

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/hpx#313]
**[reported by hkaiser]** _[Trac time Thu Feb 16 22:32:50 2012]_ The namespaces hpx::agas and hpx::naming should be combined. The combined namespace will have more functionality than just AGAS, thus I personally prefer to stick with hpx::naming as it is a more general term.

**Comment by biddisco** [comment]
if this hasn't been done, then it might be a good one to fix during modularization
