### ISSUE TITLE
Application (Octotiger) gets stuck on hpx::finalize when only using one thread

### ISSUE THREAD

**Issue by G-071** [STEllAR-GROUP/hpx#3166]
## Expected Behavior

I am currently trying to move the changes I made in Octotiger to the master branch. Therefore I am moving away from HPX 1.0.0 to a more recent version. Expected behaviour: hpx::finalize still works as before for one or more threads.

## Actual Behavior

Octotiger (current master branch) itself compiles with a recent(ish) commit of HPX and also works as intended - unless I only uses a single thread. In this case Octotiger still produces the the right result but gets stuck on hpx::finalize. This problem did not occur with HPX 1.0.0.

See inital issue: STEllAR-GROUP/octotiger#61

## Steps to Reproduce the Problem

  1. Run octotiger -t1 -Problem=moving_star -Max_level=3 -Odt=0.3 -Stoptime=0.2 -Xscale=20.0 -Omega=0.1 -Stopstep=9 -Disableoutput

## Specifications

  - HPX Version:  STEllAR-GROUP/hpx@29da281b87cfa1171b42f5e2f22caa29b3c4be2d 
  - Octotiger Version: STEllAR-GROUP/octotiger@afef65c6aa09785ff33b01ca8254b25a98f08faf
  - Vc Version: STEllAR-GROUP/Vc@157026d3adf3494922269d11a2e4dede09bf867c 
  - gcc 5.4.0, boost 1.63

**Comment by msimberg** [comment]
@G-071 There was a problem like this earlier which should already be fixed in master. Could you try again with 0867f8aa21796812fbd834188a7687616e555dc3 or newer (i.e. anything after #3110 was merged)?

**Comment by G-071** [comment]
By now, I have a workaround for STEllAR-GROUP/octotiger#60 so I rebuilt everything with the current HPX master ( ef7360bf21cabe9ccc813e9d757746ec44feaa5a ) - The problem still persists!

**Comment by msimberg** [comment]
@G-071 Thanks for testing. Seeing as you already had the problem with c9f2c09d9378d920f7d68ce857ca3729014fc601 it is most certainly not what I suspected, as you've just confirmed as well.

I will try to get octotiger running to reproduce the problem. I assume you're on Linux? Does debug or release make a difference?

**Comment by msimberg** [comment]
Update: Would you mind trying to run with a different scheduler? Most probably you want to try `local-priority-fifo` or `abp-priority`. I was able to get `octotiger` to finish with those schedulers, and it consistently hangs with `local-priority-lifo`. Are you actually able to run `octotiger` successfully with HPX 1.0, one thread and `local-priority-lifo`?

I think I know what's causing the lifo scheduler to hang and I'll try to get a fix done for 1.1.

**Comment by msimberg** [comment]
There is now #3172 which should fix `local-priority-lifo`.

**Comment by G-071** [comment]
I just tested your branch in #3172. Octotiger no longer gets stuck upon hpx::finalize when using it with: 

>  octotiger -t1 -Problem=moving_star -Max_level=3 -Odt=0.3 -Stoptime=0.2 -Xscale=20.0 -Omega=0.1 -Stopstep=9 -Disableoutput

This seems to have fixed the issue!

**Comment by msimberg** [comment]
Good to hear!
