### ISSUE TITLE
Update GSoC projects

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#3167]
![klaus-01](https://user-images.githubusercontent.com/3922435/36112956-26bd721e-1023-11e8-97a9-21038f5a2f58.png)

**Comment by diehlpk** [comment]
![6722ace35608528b1c2128bbba68d6ca](https://user-images.githubusercontent.com/3922435/36113109-a331b08a-1023-11e8-8797-a2db97784d9b.png)

**Comment by diehlpk** [comment]
![07454c4741c855faa93d6fe9ec97632a](https://user-images.githubusercontent.com/3922435/36113174-e1dd72a6-1023-11e8-964d-9752cfdf5ffa.png)

**Comment by hkaiser** [comment]
@diehlpk what is the purpose of this ticket?

**Comment by diehlpk** [comment]
it is for adding new e-mail addresses for new mentors to the wiki page. I asked how we did it in the previous years and this is how we did it.

**Comment by hkaiser** [comment]
@diehlpk we've never used the ticket system to add email addresses. The wiki is here, however: https://github.com/STEllAR-GROUP/hpx/wiki
