### ISSUE TITLE
Some failed tests, hoping you can tell me what went wrong

### ISSUE THREAD

**Issue by Geof23** [STEllAR-GROUP/hpx#3173]
## Expected Behavior
I expected the 'make tests' suite to pass

## Actual Behavior

16 of 634 failed 

## Steps to Reproduce the Problem

Well, just run 'make tests' on my system

## Specifications

... Please describe your environment

HPX commit 3e63f6a73114dc923028851d622db902a6473819
Ubuntu 16.04
Cuda 9 (V9.0.176)
gcc 7.2.0
slurm 17.11
MVAPICH2 gdr 2.3a

[cmakeCache_patch_lastTest.zip](https://github.com/STEllAR-GROUP/hpx/files/1722438/cmakeCache_patch_lastTest.zip)

**Comment by hkaiser** [comment]
Most (if not all) of the 'failing' tests are supposed to fail. Those are 'must-fail' tests. It looks like that 2 tests failed because of actual problems, one of which was addressed just yesterday. We're currently working on fixing the remaining issues.

It might be helpful if you could list the tests that you believe actually failed for you in a comment to this ticket..

**Comment by Geof23** [comment]
OK, good to hear.  I'm really excited about your work on this -- I'm
wanting to put it through some paces on some interesting hardware.

I'm pasting this into the issue area:  [thanks Harmut]


grep -B 5 'Test Failed' LastTest.log
Process 1 failed with an unexpected error code of -6 (expected 0)
Process 0 failed with an unexpected error code of -15 (expected 0)
<end of output>
Test time =   0.23 sec
----------------------------------------------------------
Test Failed.
--
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/broadcast_wait_for_2822_test
--hpx:ini=hpx.parcel.tcp.enable=1 --hpx:threads=4 --hpx:localities=2
--hpx:node=1
Process 1 failed with an unexpected error code of -6 (expected 0)
<end of output>
Test time =   0.13 sec
----------------------------------------------------------
Test Failed.
--
Executing command: /mnt/orrl/cluster_sw/hpx/hpx/build/bin/lifetime_588_test
--hpx:ini=hpx.parcel.tcp.enable=1 --hpx:threads=2 --hpx:localities=2
--hpx:node=1
Process 1 failed with an unexpected error code of -6 (expected 0)
<end of output>
Test time =   0.14 sec
----------------------------------------------------------
Test Failed.
--
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/lifetime_588_1_test
--hpx:ini=hpx.parcel.tcp.enable=1 --hpx:threads=2 --hpx:localities=2
--hpx:node=1
Process 1 failed with an unexpected error code of -6 (expected 0)
<end of output>
Test time =   0.23 sec
----------------------------------------------------------
Test Failed.
--
Base command is
"/mnt/orrl/cluster_sw/hpx/hpx/build/bin/command_line_required_arguments_2990_test
--hpx:threads=1 --hpx:localities=1"
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/command_line_required_arguments_2990_test
--hpx:threads=1 --hpx:localities=1 --hpx:node=0
<end of output>
Test time =   0.08 sec
----------------------------------------------------------
Test Failed.
--
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/credit_exhaustion_test
--hpx:ini=hpx.parcel.tcp.enable=1 --hpx:threads=2 --hpx:localities=2
--hpx:node=1
Process 1 failed with an unexpected error code of -6 (expected 0)
<end of output>
Test time =   2.25 sec
----------------------------------------------------------
Test Failed.
--
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/remote_embedded_ref_to_remote_object_test
--hpx:ini=hpx.parcel.tcp.enable=1 --hpx:threads=2 --hpx:localities=2
--hpx:node=1
Process 1 failed with an unexpected error code of -6 (expected 0)
<end of output>
Test time =   8.25 sec
----------------------------------------------------------
Test Failed.
--
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/refcnted_symbol_to_remote_object_test
--hpx:ini=hpx.parcel.tcp.enable=1 --hpx:threads=2 --hpx:localities=2
--hpx:node=1
Process 1 failed with an unexpected error code of -6 (expected 0)
<end of output>
Test time =   6.13 sec
----------------------------------------------------------
Test Failed.
--
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/uncounted_symbol_to_remote_object_test
--hpx:ini=hpx.parcel.tcp.enable=1 --hpx:threads=2 --hpx:localities=2
--hpx:node=1
Process 1 failed with an unexpected error code of -6 (expected 0)
<end of output>
Test time =   6.24 sec
----------------------------------------------------------
Test Failed.
--
Base command is
"/mnt/orrl/cluster_sw/hpx/hpx/build/bin/migrate_component_test
--hpx:ini=hpx.parcel.mpi.enable=1 --hpx:ini=hpx.parcel.bootstrap=mpi
--hpx:threads=2 --hpx:localities=2"
Executing command: srun -K -n 2
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/migrate_component_test
--hpx:ini=hpx.parcel.mpi.enable=1 --hpx:ini=hpx.parcel.bootstrap=mpi
--hpx:threads=2 --hpx:localities=2
<end of output>
Test time = 1154.55 sec
----------------------------------------------------------
Test Failed.
--
Process 1 failed with an unexpected error code of -9 (expected 0)
Process 0 failed with an unexpected error code of -15 (expected 0)
<end of output>
Test time = 1002.93 sec
----------------------------------------------------------
Test Failed.
--
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/unordered_map_test
--hpx:ini=hpx.parcel.tcp.enable=1 --hpx:threads=2 --hpx:localities=2
--hpx:node=1
Process 1 failed with an unexpected error code of -6 (expected 0)
<end of output>
Test time =   0.34 sec
----------------------------------------------------------
Test Failed.
--
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/partitioned_vector_for_each_test
--hpx:ini=hpx.parcel.tcp.enable=1 --hpx:threads=4 --hpx:localities=2
--hpx:node=1
Process 1 failed with an unexpected error code of -6 (expected 0)
<end of output>
Test time =   0.34 sec
----------------------------------------------------------
Test Failed.
--
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/partitioned_vector_reduce_test
--hpx:ini=hpx.parcel.tcp.enable=1 --hpx:threads=4 --hpx:localities=2
--hpx:node=1
Process 1 failed with an unexpected error code of -6 (expected 0)
<end of output>
Test time =   0.26 sec
----------------------------------------------------------
Test Failed.
--
Base command is
"/mnt/orrl/cluster_sw/hpx/hpx/build/bin/partitioned_vector_find_test
--hpx:ini=hpx.parcel.mpi.enable=1 --hpx:ini=hpx.parcel.bootstrap=mpi
--hpx:threads=4 --hpx:localities=2"
Executing command: srun -K -n 2
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/partitioned_vector_find_test
--hpx:ini=hpx.parcel.mpi.enable=1 --hpx:ini=hpx.parcel.bootstrap=mpi
--hpx:threads=4 --hpx:localities=2
<end of output>
Test time =   1.22 sec
----------------------------------------------------------
Test Failed.
--
Base command is
"/mnt/orrl/cluster_sw/hpx/hpx/build/bin/apex_action_count_test
--hpx:threads=1 --hpx:localities=1"
Executing command:
/mnt/orrl/cluster_sw/hpx/hpx/build/bin/apex_action_count_test
--hpx:threads=1 --hpx:localities=1 --hpx:node=0
<end of output>
Test time =   0.11 sec
----------------------------------------------------------
Test Failed.

**Comment by Geof23** [comment]
Hi @hkaiser, thanks for the info.

Can you be more specific with what you've fixed and what are expected failures?

I suppose I'm most concerned about the migrated component, partitioned vector and unordered map tests . . .

**Comment by hkaiser** [comment]
> I suppose I'm most concerned about the migrated component, partitioned vector and unordered map tests . 

Right, those are the ones we have not seen failing before.

**Comment by Geof23** [comment]
Oh, well, good to narrow it down.

If you have any news you may also contact me at Geof.sawaya@oculus.com

**Comment by sithhell** [comment]
@Geof23 since you mentioned it's an interesting and new piece of hardware, I wouldn't be surprised if you uncovered some obscure bugs. First thing I'd like to know is if this hardware has more than 64 cores (including logical cores), that might explain unexpected behavior unless you configure everything with `HPX_WITH_MAX_CPU_COUNT=512` (or similar).

**Comment by Geof23** [comment]
Hi Thomas -- yes, it is 80 logical cores.   I also set:

HPX_WITH_MAX_CPU_COUNT:STRING=80
HPX_WITH_MORE_THAN_64_THREADS:BOOL=TRUE

**Comment by sithhell** [comment]
Hmmm, would have been too easy ... Really hard to tell what's going on then. Would be interesting to rerun one of the failing tests in debug mode and see where they actually fail.
One thing that I noticed when skimming through the test log is that MPI complains about not being able to preallocate some buffers. What might actually help is to rebuild everything (with a clean build directory) without a special allocator: `cmake -DHPX_WITH_MALLOC=system ...`

**Comment by Geof23** [comment]
Hi Thomas

. Would be interesting to rerun one of the failing tests in debug mode and
see where they actually fail.

> What might actually help is to rebuild everything (with a clean build
> directory) without a special allocator: cmake -DHPX_WITH_MALLOC=system ...
>
> —
>

I’m game.  I’ll let you know what happens on both counts.

>
Best — Geof

>
>

**Comment by Geof23** [comment]
Thomas, a quick question: is there a 'normal' way to configure the tests to
run with Slurm?

So what I've done is used a stream editor to modify all the
CTestTestfile.cmake's to insert 'srun'.

**Comment by sithhell** [comment]
sorry for the late reply.

The normal way is to set the environment variable HPXRUN_RUNWRAPPER to srun. The tests are executed using a python script. By setting the runwrapper to srun, you'll get what you want. We usually execute our tests inside of something like a 'salloc -n2 -N2' job.

**Comment by Geof23** [comment]
Hi Thomas — great, thanks for the info

**Comment by Geof23** [comment]
Oh, so just a reaction to your comment: when you run the tests inside an
'salloc' session, does it then exec with mpiexec/mpirun?

I can't do that because my MPI is integrated with SLURM and doesn't provide
those.

**Comment by sithhell** [comment]
Oh, in that case, we need to adapt the runscript. It is generated during the cmake step. So you'd need to change it somehow (not exactly sure how though) here: https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/templates/hpxrun.py.in#L65-L75
The MPIEXEC and friends come out of CMake's FindMPI.cmake script ... what value does it have for you?
