### ISSUE TITLE
hwloc 2.0 breaks topo class and cannot be used

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3181]
We need to put in a cmake check for the hwloc version and give the user a warning or error if they try to use hwloc 2.0 with HPX.

(The topology of numa/memory and cores changes with hwloc 2 and it breaks the way we assign cores/etc).

**Comment by biddisco** [comment]
NB. This issue duplicates #3161

**Comment by hkaiser** [comment]
This is a duplicate for #3161

**Comment by biddisco** [comment]
The fix applied to #3161 only solved the building and not the execution of HPX with hwloc 2

**Comment by hkaiser** [comment]
This was fixed by merging #3225
