### ISSUE TITLE
init_globally throwing a run-time error

### ISSUE THREAD

**Issue by NK-Nikunj** [STEllAR-GROUP/hpx#3208]
## Expected Behavior

Should run properly

## Actual Behavior

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  hpx::resource::get_partitioner() can be called only after the resource 
           partitioner has been allowed to parse the command line options.
Aborted (core dumped)
```

**Comment by msimberg** [comment]
This seems to happen only in release mode.

I had a very similar issue (either release or debug throwing that error, and the other not, but I don't remember if it was the same way around) trying to make an HPX-enabled library, which in the end was related to me not linking to HPX correctly. It may not be the same, but could be related (I will look into this next week).

**Comment by hkaiser** [comment]
FWIW, we use a similar global initialization scheme to enable HPX in a Python environment and have not seen any issues recently (see: https://github.com/STEllAR-GROUP/phylanx/blob/master/python/src/init_hpx.cpp)
