### ISSUE TITLE
Broken documentation building process

### ISSUE THREAD

**Issue by Anushi1998** [STEllAR-GROUP/hpx#3217]
The link to fibonacci.cpp in [docs](https://stellar-group.github.io/hpx/docs/html/hpx.html#hpx.tutorial.examples.fibonacci.setup) should be pointing to [this](https://github.com/STEllAR-GROUP/hpx/blob/master/examples/quickstart/fibonacci.cpp) code but it is pointing to a wrong [code](https://stellar-group.github.io/hpx/docs/html/code/examples/quickstart/fibonacci.cpp)

**Comment by hkaiser** [comment]
@Anushi1998 would you be able to create a PR fixing this?

**Comment by Anushi1998** [comment]
Yes @hkaiser

**Comment by Anushi1998** [comment]
I am extremely sorry I could not complete it but is it needed any further if we are moving towards sphinx?
Moreover, I have noticed that this line is faulty https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/HPX_UpdateGitDocs.cmake#L42. I don't understand how Rostam is able to build docs successfully if it uses it because it returned an error in my system :(

**Comment by msimberg** [comment]
Closing because of move to sphinx.
