### ISSUE TITLE
HPX link error on Cori

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#3219]
## Expected Behavior

To build HPX.

## Actual Behavior

On linking libhpx.so, I get:

CMakeFiles/hpx.dir/util/serialize_exception.cpp.o: In function `void hpx::serialization::load<hpx::serialization::input_archive>(hpx::serialization::input_archive&, std::__exception_ptr::exception_ptr&, unsigned int)':
serialize_exception.cpp:(.text._ZN3hpx13serialization4loadINS0_13input_archiveEEEvRT_RNSt15__exception_ptr13exception_ptrEj[_ZN3hpx13serialization4loadINS0_13input_archiveEEEvRT_RNSt15__exception_ptr13exception_ptrEj]+0xdc3): undefined reference to `std::__exception_ptr::exception_ptr hpx::detail::construct_exception<std::logic_error>(std::logic_error const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long, unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
serialize_exception.cpp:(.text._ZN3hpx13serialization4loadINS0_13input_archiveEEEvRT_RNSt15__exception_ptr13exception_ptrEj[_ZN3hpx13serialization4loadINS0_13input_archiveEEEvRT_RNSt15__exception_ptr13exception_ptrEj]+0x1078): undefined reference to `std::__exception_ptr::exception_ptr hpx::detail::construct_exception<std::runtime_error>(std::runtime_error const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long, unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

## Specifications

On Cori using Haswell nodes, compiling with Intel 18.0.1 (gcc 6.3 is loaded with it), boost 1.64, building the current commit of HPX with the following:

cmake -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc -DCMAKE_BUILD_TYPE=release -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCELPORT_MPI_MULTITHREADED=ON  -DCMAKE_INSTALL_PREFIX=. -DHPX_WITH_TESTS=OFF -DBOOST_ROOT=/home/dmarce1/local/boost -DHPX_WITH_EXAMPLES=OFF -DHPX_WITH_MALLOC=custom -DHPX_WITH_PARCELPORT_LIBFABRIC=OFF -DCMAKE_INSTALL_PREFIX=/global/homes/d/dmarce1/local/hpx ../hpx

**Comment by hkaiser** [comment]
@G-071 do you see similar effects for your builds on Cori?

**Comment by dmarce1** [comment]
When I try to run on more than one node using Haswell nodes and GCC, I get a crash:

+ srun -u -n 2 -N 2 octotiger --hpx:threads=32 -Ihpx.parcel.bootstrap=mpi --hpx:localities 2 -Problem=moving_star -Max_level=3 -Odt=0.3 -Stoptime=0.2 -Xscale=20.0 -Omega=0.1 --hpx:bind=none -Stopstep=9
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
nid00540:SCM:8ce9:aab3a000: 127205250 us(127205250 us!!!):  open_hca: failed to init cr pipe - Connection timed out
nid00488:SCM:a533:aab3a000: 127229427 us(127229427 us!!!):  open_hca: failed to init cr pipe - Connection timed out
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
srun: error: nid00540: task 1: Segmentation fault
srun: Terminating job step 10768547.1
slurmstepd: error: *** STEP 10768547.1 ON nid00488 CANCELLED AT 2018-03-08T08:38:37 ***
srun: error: nid00488: task 0: Terminated
srun: Force Terminated job step 10768547.1

I was trying to see if the same thing happens in Intel.

**Comment by G-071** [comment]
Which commit of Octotiger are you currently using? Do you use the fix in the pull request STEllAR-GROUP/octotiger#63 which I opened earlier this week?

**Comment by dmarce1** [comment]
I am using afef65c6aa09785ff33b01ca8254b25a98f08faf, which is from before the new FMM kernels.

**Comment by hkaiser** [comment]
@dmarce1, @G-071 Can this be closed now?

**Comment by G-071** [comment]
I do not think so (unless @dmarce1 has some news about it). 

If I understood correctly, the crash @dmarce1 got in Octotiger is unrelated the one I fixed in  STEllAR-GROUP/octotiger#63 since it predates the new FMM kernels! If that problem persists we should open an issue in the Octotiger repository about it!

But the HPX link error reported here appears to be a whole other issue anyway! I have never encountered the same problem, but I have not tried compiling HPX with the intel compiler, yet!

**Comment by dmarce1** [comment]
I retried with gcc 6.3 and the mentioned fixes above, and still get a time-out error. This is on the haswell cores.
