### ISSUE TITLE
GSoC 2018 Project Ideas

### ISSUE THREAD

**Issue by Anushi1998** [STEllAR-GROUP/hpx#3220]
"Re-Implementation of `hpx::util::unwrapped` " project is in both list (See [here](https://github.com/STEllAR-GROUP/hpx/wiki/GSoC-2018-Project-Ideas#vanguard-project-ideas) and point 4 in Table of Contents)

I think the classification of projects should be only at one place to avoid confusion :)

**Comment by hkaiser** [comment]
The original project listed was already assigned as a GSoC project last year. A lot was achieved but we still need to change some of our facilities (like `when_all` and `when_any`) to actually take advantage of the created unwrapping facilities. This would definitely still be a possible task for GSoC.

**Comment by Anushi1998** [comment]
Yes Sure @hkaiser , but don't you think it should be only in one list?
These three projects I have figured out are not common to both

- Re-Implementation of hpx::util::unwrapped
- Parallel Algorithms for HPX
- Graphical and Terminal User Interface for Scimitar

**Comment by hkaiser** [comment]
This can be closed now. Please reopen, if necessary.
