### ISSUE TITLE
cmake macro add_hpx_executable() is not adding "_component" suffix to COMPONENT_DEPENDENCIES option.

### ISSUE THREAD

**Issue by Jakub-Golinowski** [STEllAR-GROUP/hpx#3227]
## Expected Behaviour

cmake macro add_hpx_executable() has an option COMPONENT_DEPENDENCIES. Expected behaviour is that the "_component" suffix will be added automatically to the value following the COMPONENT_DEPENDENCIES option.

## Actual Behaviour
the "_component" suffix is not added automatically and <component_name> needs to contain the suffix. The concrete example follows below.

## Steps to Reproduce the Problem
Follow the tutorial in documentation: [(link to the tutorial)](https://stellar-group.github.io/hpx/docs/html/hpx.html#hpx.manual.build_system.using_hpx.using_hpx_cmake)
Use the following files: [(link to files)](https://github.com/STEllAR-GROUP/hpx/tree/master/examples/hello_world_component)
According to the tutorial the CMakeLists.txt should look as follows:
```
# Require a recent version of cmake
cmake_minimum_required(VERSION 2.8.4 FATAL_ERROR)

# This project is C++ based.
project(hello_world_component CXX)

# Instruct cmake to find the HPX settings
find_package(HPX)

#build your application using HPX
add_hpx_component(hello_world_component
    SOURCES hello_world_component.cpp
    HEADERS hello_world_component.hpp
    COMPONENT_DEPENDENCIES iostreams)

#build your application using HPX
add_hpx_executable(hello_world
    ESSENTIAL
    SOURCES hello_world_client.cpp
    COMPONENT_DEPENDENCIES hello_world)
```

building using cmake (as described in tutorial) yields the following linking error:
```
[100%] Linking CXX executable hello_world
/usr/bin/ld: cannot find -lhpx_hello_world
collect2: error: ld returned 1 exit status
CMakeFiles/hello_world_exe.dir/build.make:111: recipe for target 'hello_world' failed
make[2]: *** [hello_world] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/hello_world_exe.dir/all' failed
make[1]: *** [CMakeFiles/hello_world_exe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

In order to prevent this error I modified add_hpx_executable() in CMakeLists.txt file:
From: 
```
add_hpx_executable(hello_world
    ESSENTIAL
    SOURCES hello_world_client.cpp
    COMPONENT_DEPENDENCIES hello_world)
```
To (adding "_component" suffix to the COMPONENT_DEPENDENCIES option):
```
add_hpx_executable(hello_world
    ESSENTIAL
    SOURCES hello_world_client.cpp
    COMPONENT_DEPENDENCIES hello_world_component)

```
## Specifications
  - HPX Version: 1.1.0 (built from master branch)
  - Compiler: gcc 5.4
  - OS: Ubuntu 16.04

**Comment by msimberg** [comment]
It looks like the documentation is out of date/wrong on this one.

The "problem" is that `add_hpx_executable` and `add_hpx_component` add `_exe` and `_component` suffixes, respectively, to the targets. When you specify `COMPONENT_DEPENDENCIES` the `_component` suffix is also added automatically to what you pass in as an argument (except for things like `iostreams`...). If you specify `DEPENDENCIES` the whole name has to be given. The confusing part is that it's perfectly valid to do `add_hpx_component(hello_world ...)` and `add_hpx_executable(hello_world ...)` as the two calls create two separate targets (neither of which is named `hello_world`).

I'll update the documentation to explain this.

**Comment by biddisco** [comment]
> The confusing part is that it's perfectly valid to do add_hpx_component(hello_world ...) and add_hpx_executable(hello_world ...) as the two calls create two separate targets (neither of which is named hello_world)

It really is about time we changed this so that the _exe and _component suffixes are removed. They are confusing and pointless and only cause problems without solving any.

**Comment by msimberg** [comment]
I'm indifferent about the suffixes, and can see both sides of the argument. Anyone else have strong opinions on either keeping or removing the suffixes?

**Comment by hkaiser** [comment]
I'm indifferent as well. Both ways works for me.

**Comment by biddisco** [comment]
Since everyone else is indifferent, then I'll up my vote to "I feel very strongly that adding `_exe` and `_component` is confusing, annoying and pointless" I'd like to see the behaviour removed.

As to the original issue - if `hpx_add_component` no longer adds `_component` to the target name, then the user will manually say `hpx_add_component(hello_world_component ...)` and when they add it as a dependency, they should also say  `COMPONENT_DEPENDENCIES hello_world_component` because they might equally well say `hpx_add_component(hello_world_thingy ...)` and `COMPONENT_DEPENDENCIES hello_world_thingy`.  The tricky part is making users know which components are available and which are useful.

**Comment by biddisco** [comment]
Didn't realize this issue had been closed.

**Comment by hkaiser** [comment]
This was closed accidentally

**Comment by hkaiser** [comment]
> As to the original issue - if hpx_add_component no longer adds _component to the target name, then the user will manually say hpx_add_component(hello_world_component ...) and when they add it as a dependency, they should also say COMPONENT_DEPENDENCIES hello_world_component because they might equally well say hpx_add_component(hello_world_thingy ...) and COMPONENT_DEPENDENCIES hello_world_thingy. The tricky part is making users know which components are available and which are useful.

If we removed the `component` suffix we don't need the `COMPONENT_DEPENDENCIES` anymore. All it does is to dispatch to `DEPENDENCIES` while adding the suffix, iirc.
