### ISSUE TITLE
Parent thread reference incorrect

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#3252]
If `HPX_HAVE_THREAD_PARENT_REFERENCE` is defined (`HPX_WITH_THREAD_DEBUG_INFO=On`) every HPX should hold a correct reference to its creating parent thread. This is reportedly not always the case and requires some investigation.

**Comment by khuck** [comment]
@hkaiser I may have found a clue - I had to handle the case where rebind_base() is called.  I think I handle that case correctly now.  It is in the apex_refactoring_fix_rebind branch, which hasn't been pushed yet, as I am still testing.

**Comment by hkaiser** [comment]
@khuck can this be closed now?

**Comment by khuck** [comment]
@hkaiser this is related to the issue with annotations, and I think we are way past this problem.  Yes, it can be closed.
