### ISSUE TITLE
Links to source code in documentation are broken

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3258]
For example on [this page](http://stellar.cct.lsu.edu/files/hpx-1.1.0/html/header/hpx/components/component_storage/migrate_from_storage_hpp.html), clicking "Header <hpx/components/component_storage/migrate_from_storage.hpp>" leads to a page which does not exist. It is pointing at http://stellar.cct.lsu.edu/files/hpx-1.1.0/html//boost//hpx/components/component_storage/migrate_from_storage.hpp.

For 1.0.0 it points to http://stellar.cct.lsu.edu/files/hpx-1.0.0/html/hpx/components/component_storage/migrate_from_storage.hpp, different but also non-existent.

This is "nice to have", i.e. not very important.

**Comment by hkaiser** [comment]
We should be able to update this even after the release. I have no idea however where the `boost` part in the generated url comes from.

**Comment by hkaiser** [comment]
FWIW, the links miss a `code` part, i.e. this works:

http://stellar.cct.lsu.edu/files/hpx-1.1.0/html/code/hpx/components/component_storage/migrate_from_storage.hpp

**Comment by hkaiser** [comment]
@msimberg #3262 should fix this. I also updated the online docs for V1.1 using a similar patch.

**Comment by msimberg** [comment]
@hkaiser very nice, thanks a lot!
