### ISSUE TITLE
Possible move to Sphinx for documentation

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3264]
This issue is meant to collect feedback on the **appearance** of our current documentation. For content see #3263.

I am aware that this is a very subjective topic, so my hope is to find out:
- what people like
- if someone has had good/bad experiences with Sphinx
- if someone has experience with other tools than Sphinx, or
- if this is a waste of time.

In my opinion, the current documentation is difficult to read because of:
- small text (yes, one can zoom, but I think the default should be larger)
- lines fill the full width of the window (I prefer shorter lines for readability, only very rarely do I prefer wide lines in order to have more content on the screen)
- difficult to navigate (the search and permanent toc tree on the left are very nice [here](https://docs.readthedocs.io/en/latest/))

One option would be to move to Sphinx + Doxygen. This would give us:
- nice themes to choose from (easily customizable), which address the problems above
- familiar markup for many with restructuredtext
- possibility to host on readthedocs (this might not work out, readthedocs has doxygen installed but seems to assume a concrete Doxyfile, need to check if they have CMake installed)
  - automatically build docs from master/version tags
  - can browse different versions of the documentation
- ability to host ourselves as well
- something that is not boostbook/quickbook

The downsides:
- Sphinx does something weird with certain templates, may be related to macros (but hopefully possible to fix)
- requires converting the current .qbk files to restructured text, can maybe be automated to some extent but has to be worth the effort
- boostbook/quickbook is very powerful

Some examples of readthedocs documentation:
- [readthedocs documentation](https://docs.readthedocs.io/en/latest/)
- [the bootstrap theme](http://ryan-roemer.github.io/sphinx-bootstrap-theme/index.html)
- [pybind11 docs](http://pybind11.readthedocs.io/en/stable/index.html) and their [API reference page](http://pybind11.readthedocs.io/en/stable/reference.html)

Example screenshot of HPX API reference section (with a weird template) 
![hpx-sphinx](https://user-images.githubusercontent.com/42977/37908261-f713ffa0-3107-11e8-9549-f4d42b0f2a4d.png)

---

A much simpler option would be to simply change the css of the current documentation and get some of the improvements in readability.

**Comment by msimberg** [comment]
Some interesting links off IRC provided by @hkaiser and @zao:

- good looking doxygen documentation: [http://mcss.mosra.cz/doxygen/](http://mcss.mosra.cz/doxygen/)
- Boost.Build documentation using asciidoc: [https://grafikrobot.github.io/b2doc/](https://grafikrobot.github.io/b2doc/)
- old-style but more readable Boost.Build documentation: [https://rawgit.com/grafikrobot/b2doc/90a793a12c675059e32ad4b4c77b7d84c2f1ab54/index.html](https://rawgit.com/grafikrobot/b2doc/90a793a12c675059e32ad4b4c77b7d84c2f1ab54/index.html)

**Comment by msimberg** [comment]
Sphinx template problems can be worked around (it's related to macro expansion and happens with boostbook as well, boostbook shows `unspecified` instead).

I've uploaded a small example of HPX documentation with Sphinx (without content, only a few namespaces for the reference): [http://stellar.cct.lsu.edu/files/docs-playground/sphinx/html/index.html](http://stellar.cct.lsu.edu/files/docs-playground/sphinx/html/index.html).

I've also uploaded a version of our boostbook documentation with changed CSS: [http://stellar.cct.lsu.edu/files/docs-playground/boostbook/html/index.html](http://stellar.cct.lsu.edu/files/docs-playground/boostbook/html/index.html). It also contains some rearranging of the sections (more on that in #3263).

**Comment by sithhell** [comment]
The new boostbook css is broken on my phone. I very much like the Sphinx
mockup though!

Mikael Simberg <notifications@github.com> schrieb am Mo., 9. Apr. 2018
16:26:

**Comment by msimberg** [comment]
@sithhell thanks for checking! What does broken mean to you? I admit I didn't test it extensively, just wanted to try something out that looks a bit nicer.

**Comment by NK-Nikunj** [comment]
@msimberg sphinx templates looks pleasing to the eye. It should encourage the users to explore topics and sub-topics in an efficient manner.

**Comment by msimberg** [comment]
Ok, so I finally started converting boostbook to sphinx. You can see the progress on [readthedocs](https://hpx.readthedocs.io/en/sphinx/) and on [this branch](https://github.com/msimberg/hpx/tree/sphinx). Expect lots of things to be wonky for a while. I'm converting existing content first and will then start adding some new sections.

If someone feels like helping out with the conversion let me know.

**Comment by NK-Nikunj** [comment]
@msimberg I could help with some conversion. Also I could help with documentation. I have a few ideas and content for beginners to get them on track.

**Comment by msimberg** [comment]
@NK-Nikunj thanks! I think it's easiest if we coordinate on IRC (I'm M-ms), I'm not sure yet what the best way to split up the work is yet. Whatever new sections you would like to add can most likely be added without much coordination. What do you have in mind?

**Comment by Anushi1998** [comment]
I would also suggest to include existing youtube video links (as far as I know they do not exist in previous documentation) in the documentation so that someone directly jumping on docs without exploring repositories in STEllAR-GROUP could be benefited as well.

**Comment by msimberg** [comment]
@Anushi1998 Including links to videos is a very good idea. Thanks! We could also link to some of the explanatory blog posts on the stellar blog (although it would be better to just have that material directly in the documentation).

**Comment by msimberg** [comment]
Closing this since the sphinx branch was merged.
