### ISSUE TITLE
Error when compiling CUDA examples

### ISSUE THREAD

**Issue by KofToZ** [STEllAR-GROUP/hpx#3270]
When compiling data_copy.cu got the following error in optional.hpp

/usr/local/include/hpx/util/optional.hpp(244): error:
statement may not appear in a constexpr function

/usr/local/include/hpx/util/optional.hpp(246): error: a
constexpr function must contain exactly one return
statement
 
2 errors detected in the compilation of
"/tmp/tmpxft_00002044_00000000-4_data_copy.cpp4.ii".
CMake Error at
cuda_copy_exe_generated_data_copy.cu.o.cmake:279
(message):
   Error generating file

/build/CMakeFiles/cuda_copy_exe.dir//
./cuda_copy_exe_generated_data_copy.cu.o

  - HPX Version: HPX 1.1.0
  - Platform (compiler, OS): cmake on ubuntu 18.4

**Comment by msimberg** [comment]
Hi @KofToZ, I believe this was just fixed on master (#3268). Would you mind trying that out?

**Comment by KofToZ** [comment]
Thanks, the error seems to be fixed now, but the example still doesn't compile. Now it gives a new error:

nvcc fatal   : 'true -gencode arch=compute_50,code=sm_50': 
expected true or false
