### ISSUE TITLE
CircleCI does not upload generated docker image any more

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#3272]
The new CircleCI V2 scripts do not upload the generated docker image anymore as some of the parallel algorithm tests fail to compile (OOM problems?). This causes all kind of problems for projects depending on the latest HPX master features.

Would it be possible to upload the docker file whenever the core libraries compile successfully (at least until the issue with the parallel algorithms has been resolved)?

**Comment by msimberg** [comment]
Sorry about that (and yes, looks like OOM problems). Had a quick look and it looks like it should be possible (the upload is a regular step in the workflow like any other). Will try to change it tomorrow.

**Comment by hkaiser** [comment]
@msimberg I started working on this by splitting up the failing tests into smaller ones (see https://github.com/STEllAR-GROUP/hpx/tree/fixing_3272). This seems to resolve things as well.

**Comment by hkaiser** [comment]
@sithhell Thanks!
