### ISSUE TITLE
possible compilation error when "using namespace std;" is defined before including "hpx" headers files 

### ISSUE THREAD

**Issue by mtaillefumier** [STEllAR-GROUP/hpx#3285]
a compilation error may occur when "using namespace std;" is defined before including hpx header files. I can only reproduce this error with my code though and have no very simple test code where the error appears. 

## Expected Behavior

I expected the compilation not to fail.

## Actual Behavior

g++ returns this 

```
hpx/runtime/components/memory_block.hpp: In member function ‘hpx::components::access_memory_block_proxy<T>& hpx::components::access_memory_block_proxy<T>::operator=(const target_type&)’:
include/hpx/runtime/components/memory_block.hpp:185:20: error: invalid use of ‘class std::set<typename std::remove_const<_Tp>::type>’
             block_.template set<target_type>(rhs);
```
if we have this in an header file:

```
using namespace std;
#include <hpx/config.hpp>
#include <hpx/hpx.hpp>
```
removing the using namespace std; works fine. John suggested that it could be a clash between the std::set function and the set function defined in the class. the compiler try to resolve std::set before searching the set function in the class.

## Steps to Reproduce the Problem

Difficult to reproduce with a very simple code. Seems to be related to my code.

## Specifications

  - HPX Version: 1.2 (git from 04/13)
  - Platform (compiler, OS): power 8 linux 3.10.0 
  - gcc : 6.4.0
  - boost : 1.66.0

Mathieu

**Comment by hkaiser** [comment]
@mtaillefumier I'm not sure how to fix this if you can't provide some code reproducing it. Does it help if you rename that `set` function?

**Comment by hkaiser** [comment]
Besides, I'd strongly suggest _not_ to use any `using namespace ...;` in any header file (at least not at global scope).

**Comment by mtaillefumier** [comment]
Renaming the function would work unless it is a function defined in the std library. Actually the only clean way to fix this problem is to remove the "using namespace std;" from the code. 

I honestly do not know if it is actually an issue (I consider that I made a programming error) with hpx or g++ being a bit too naive with templates. I will try to have a very simple code reproducing the error.
