### ISSUE TITLE
Crash with APEX when running Phylanx lra_csv with > 1 thread

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#3297]
## Expected Behavior

I don't expect it to crash.

## Actual Behavior

HPX is crashing in the rebind_task method, when APEX is setting a new task wrapper for the re-used thread_data object.  The parent_thread_id_ 's m_apex_data member is corrupted. 

## Steps to Reproduce the Problem

Configure HPX with these additional APEX settings:
```
-DHPX_WITH_APEX=TRUE \
-DAPEX_WITH_ACTIVEHARMONY=TRUE \
-DACTIVEHARMONY_ROOT=/usr/local/activeharmony/4.6 \
-DAPEX_WITH_OTF2=TRUE -DOTF2_ROOT=/usr/local/otf2/2.1 \
-DAPEX_WITH_PAPI=TRUE -DPAPI_ROOT=/usr/local/papi/5.5.0/ \
-DHPX_WITH_APEX_NO_UPDATE=TRUE
```
...then build the Phylanx software and run the lra_csv example with more than 1 HPX worker thread.  Higher thread counts will crash more reliably, and consistently with >4 threads.

## Specifications

HPX master, Apple Clang++ 9.1.0 (Xcode), OSX 10.13.4

**Comment by biddisco** [comment]
@khuck I'm getting problems with the code after the recent merge. Specifically there's an 
`assert(wrapper);` call in update_task that is being triggered. I can comment it out and all seems well until it hangs on shutdown. Didn't get a chance to diagnose it.
Reopening this issue for now.
