### ISSUE TITLE
No warning when mixing debug/release builds

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3322]
## Expected Behavior
When a user builds their own test program against an installed HPX, they frequently do not realize that they are compiling in debug/release mode against an HPX in another mode

The HPXConfig.cmake should print a warning like the one we do in the tutorials
```
#--------------------------------------------------
# Check we are using the same build type as HPX
#--------------------------------------------------
if (NOT "${HPX_BUILD_TYPE}" STREQUAL "${CMAKE_BUILD_TYPE}")
  message(WARNING "CMAKE_BUILD_TYPE does not match ${HPX_BUILD_TYPE} :\n"
    "this project uses ${CMAKE_BUILD_TYPE}, hpx uses ${HPX_BUILD_TYPE}\n"
    "Please add -DCMAKE_BUILD_TYPE=${HPX_BUILD_TYPE} to your cmake command"
  )
endif()
```
This would be a useful addition and solve many problems caused by erroneous configuration

**Comment by hkaiser** [comment]
This would work only on systems where multi-target build systems are not supported. So we have to be careful with non-conditionally adding this to our setup.

**Comment by biddisco** [comment]
I should fix this.

**Comment by albestro** [comment]
@hkaiser I'd like to find a way to fix this issue.

For what concerns single-vs-multiple configurations generators, I would split this check based on [GENERATOR_IS_MULTI_CONFIG](https://cmake.org/cmake/help/v3.16/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html).

Here I'm assuming to work with the default set of build types: Debug, Release, RelWithDebInfo, MinSizeRel.
We may also evaluate to add an option to disable this check (I may not be a fan of this).

### Single-configuration generator
I would propose to keep this check output as a `WARNING` message. This would not restrict any combination, but it would highlight that there is a mismatch. Useful if a user is not doing anything strange, simply ignorable if someone knows what he/she is doing.

I would use @biddisco code snippet. We can decide to use the exact match policy, or to go for a more "semantic" one, in which it alerts if Debug is going to be mixed with one of the other ones (Release, ReleaseWithDebInfo, MinSizeRel).

### Multi-configuration generator
We may decide to provide or not a check for this kind of generators.

In case yes, we can limit [CMAKE_CONFIGURATION_TYPES](https://cmake.org/cmake/help/v3.16/variable/CMAKE_CONFIGURATION_TYPES.html#variable:CMAKE_CONFIGURATION_TYPES), but it seems to restrictive if we allow just exact matching, so we should go for the "semantic" policy.

**Comment by biddisco** [comment]
I think it'd be fine to simply use
```
#--------------------------------------------------
# Check we are using the same build type as HPX
#--------------------------------------------------
if (NOT GENERATOR_IS_MULTI_CONFIG AND 
    NOT "${HPX_BUILD_TYPE}" STREQUAL "${CMAKE_BUILD_TYPE}")
  message(WARNING "CMAKE_BUILD_TYPE does not match ${HPX_BUILD_TYPE} :\n"
    "this project uses ${CMAKE_BUILD_TYPE}, hpx uses ${HPX_BUILD_TYPE}\n"
    "Please add -DCMAKE_BUILD_TYPE=${HPX_BUILD_TYPE} to your cmake command"
  )
endif()
```
That would give a good enough warning on the machines that matter most you us. Visual Studio handles things pretty well in it's own way when building deb/rel stuff from dependent projects.

**Comment by hkaiser** [comment]
Thanks @biddisco, this looks like a viable solution. See also #4205 for a corresponding patch.

**Comment by albestro** [comment]
Thanks @hkaiser for the patch!
