### ISSUE TITLE
AGAS migrates components prematurely

### ISSUE THREAD

**Issue by bremerm31** [STEllAR-GROUP/hpx#3325]
## Expected Behavior

When migrating a component whose action itself returns a future, the component should be migrated after the future of the action returns.

## Actual Behavior

Currently, it seems that the component gets migrated as soon as the action returns. Thus, the future of the action will continue to compute on the original locality.

## Steps to Reproduce the Problem

As a test case, I have modified the `migrate_component` unit test from the library. See https://github.com/bremerm31/hpx_mwe/blob/v0.1/src/migrate_component.cpp

Now `busy_work` has been futurized, and the `busy_work_impl` function will also increment `data_` by one. Thus, after `busy_work` has `executed data_` should be 43. However, since migration will occur before `busy_work` returns `data_` is evaluated as 42, causing the error to be thrown.

One workaround discussed with @hkaiser was manually pinning the component. This is shown via comments on L47-L48 in https://github.com/bremerm31/hpx_mwe/blob/v0.1/src/migrate_component.cpp#L47 . If these are uncommented, the test works as expected.

## Specifications

  - HPX Version: https://github.com/STEllAR-GROUP/hpx/commit/f6ce7ea37472dba57ed20964d7dea27a781fbce0
  - Compiler
```
[max@walikar dgswemv2]$ g++ --version
g++ (GCC) 6.1.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
  - OS
```
[max@walikar dgswemv2]$ cat /etc/*-release
CentOS Linux release 7.4.1708 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core) 
CentOS Linux release 7.4.1708 (Core)
```

**Comment by hkaiser** [comment]
FWIW, I'm currently looking into this and will have a PR soon.
