### ISSUE TITLE
setting command line options/flags from init cfg is not obvious

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3339]
## Steps to Reproduce the Problem
Try using 
```
std::vector<std::string> cfg = {
    "hpx.os_threads=2",
    "hpx.bind=balanced",
    "hpx.print-bind"
};
```
hpx.print-bind is not accepted as a valid config entry. I'm not sure why not. Is there a difference between those with values and those without?

Clearly there is a special syntax, because on the command line one says
`--hpx:threads=2` but in the cfg, one says `hpx.os_threads=2`, it's not obvious why they should be different. Why can one not just put command line options in the cfg?

**Comment by biddisco** [comment]
Just to clarify. I have never used the cfg={...} method of setting options, but a user tried the above and it does not work.

**Comment by hkaiser** [comment]
> Why can one not just put command line options in the cfg?

That is indeed a good question. This might be the easiest solution to get out of the naming inconsistencies between command line and configuration settings.

**Comment by bcumming** [comment]
I am the guilty user.
Both the `hpx.bind=balanced` and `hpx.print-bind` strings produced errors.

**Comment by hkaiser** [comment]
@bcumming Yes, the configuration settings have evolved over time independently from the command line options and a) mostly have different names, and b) are not 100% overlapping (i.e. there are settings on both sides that are not supported on the other). This situation is bad and will require some cleanup. 

As said, simply exposing the command line options as possible configuration keys may be a solution to resolve this without disrupting existing codes. In your case this would be:
```
std::vector<std::string> cfg = {
    "--hpx:threads=2",
    "--hpx:bind=balanced",
    "--hpx:print-bind"
};
```
Over time we then could phase out the old configuration key names.

**Comment by biddisco** [comment]
> Over time we then could phase out the old configuration key names.

That would be great. 

... and BTW, you are awesome for addressing this so quickly. Thanks
