### ISSUE TITLE
undefined reference to `__atomic_load_16'

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#3342]
## Expected Behavior

I expected to build HPX.

## Actual Behavior

libhpx failed to build and I got a bunch of  "undefined reference to `__atomic_load_16'" errors.

## Steps to Reproduce the Problem

These are the build options I used:

cmake -DCMAKE_BUILD_TYPE=release    \                                                                                                                      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON                                            \
      -DHPX_WITH_PARCELPORT_MPI=ON                                                  \
      -DHPX_WITH_PARCELPORT_MPI_MULTITHREADED=ON                                    \
      -DHPX_WITH_DATAPAR_VC=ON                                                      \
      -DHPX_WITH_DATAPAR_VC_NO_LIBRARY=ON                                           \
      -DVc_ROOT="$HOME/local/vc"                                                    \
      -DCMAKE_INSTALL_PREFIX=.                                                      \
      -DHPX_WITH_TESTS=OFF                                                          \
      -DHPX_WITH_EXAMPLES=OFF            \      
      -DHPX_WITH_MALLOC=tcmalloc                          \                                                                                              
      -DCMAKE_INSTALL_PREFIX="$HOME/local/hpx"                                   \
      -DCMAKE_CXX_COMPILER="mpic++" \
      -DCMAKE_C_COMPILER="mpicc" \
      ../hpx

I also tried adding 
      -DCMAKE_CXX_FLAGS="-march=native -latomic" \
      -DCMAKE_C_FLAGS="-march=native -latomic \

## Specifications

... Please describe your environment

  - HPX Version: be53f75d1d903ef5b0fb3a0bb7bbc05dd78b946c
  - Platform (compiler, OS):
    Ubuntu 18, g++ 7.3, Boost 1.65.1

**Comment by hkaiser** [comment]
... or `-DCMAKE_SHARED_LINKER_FLAGS=-latomic` for that matter.

**Comment by dmarce1** [comment]
I get the same errors. I tried both.

**Comment by dmarce1** [comment]
I retried everything with boost 1.67 and it built correctly. I'm not sure if this is a problem with boost 1.65 or HPX.

**Comment by hkaiser** [comment]
Ok, thanks for letting us know. We'll assume for this to be a Boost problem, then.

**Comment by w1397800** [comment]
> -DCMAKE_EXE_LINKER_FLAGS=-latomic

it works! thank you!

**Comment by hkaiser** [comment]
> > -DCMAKE_EXE_LINKER_FLAGS=-latomic
> 
> it works! thank you!

@w1397800 What Boost version are you working with.

**Comment by soul-coder-heap** [comment]
> The linker probably misses an `-latomic`. Please try adding `-DCMAKE_EXE_LINKER_FLAGS=-latomic`.

it's  resolve my trouble!thank you very much!
