### ISSUE TITLE
HPX runtime hangs after multiple (~thousands) start-stop sequences

### ISSUE THREAD

**Issue by Jakub-Golinowski** [STEllAR-GROUP/hpx#3358]
## Expected Behavior

It is expected that the HPX runtime can be started and stopped as many times as one wishes without risk of the application hanging.

## Actual Behavior

After a few thousand (observed between 1k - 9k) start-stop sequences  the HPX runtime hangs.

## Steps to Reproduce the Problem

I have written a simple HPX application that starts HPX runtime, performs a parallel count-up and stops the runtime in a loop for 50k times . After around 1k-9k start-stop sequences the application hangs.

Link to the application: https://github.com/Jakub-Golinowski/opencv_hpx_backend/tree/master/hpx_start_stop

## Specifications

  - HPX Version:  built from master branch as seen in this fork: https://github.com/Jakub-Golinowski/hpx
  - Platform (compiler, OS): Linux Ubuntu 16.04, gcc 5.4.0

**Comment by msimberg** [comment]
Thanks @Jakub-Golinowski. I can reproduce this on latest master as well. It looks like the notify for `stop_condition` happens before this wait: https://github.com/STEllAR-GROUP/hpx/blob/3481317b19fdcee8c6682ad08aab6c57899bfdd9/src/runtime/components/server/runtime_support_server.cpp#L931, causing it to hang. It shouldn't be possible but clearly it is...
