### ISSUE TITLE
Segmentation fault when passing component id as parameter

### ISSUE THREAD

**Issue by hrasadi** [STEllAR-GROUP/hpx#3360]
## Expected Behavior

Basically, What I want to do is to keep the client side instance of a component as instance variable of a regular C++ class and call its actions. I tried to keep the value of component ID and later reconstruct the client instance but every possible combination I have tested leads to a segmentation fault at runtime.

## Actual Behavior

Here is a stack trace of where the operation fails inside the HPX code:

```
#0  0x000000000041df50 in boost::intrusive_ptr<hpx::naming::detail::id_type_impl>::swap(boost::intrusive_ptr<hpx::naming::detail::id_type_impl>&) ()
#1  0x000000000041bd34 in boost::intrusive_ptr<hpx::naming::detail::id_type_impl>::operator=(boost::intrusive_ptr<hpx::naming::detail::id_type_impl> const&) ()
#2  0x00000000004175a8 in hpx::naming::id_type::operator=(hpx::naming::id_type&&) ()
// My application call hierarchy continues...
```

## Steps to Reproduce the Problem

I am using a design similar to this:

```
class container {
public:
  container() {
    this->id = hpx::new_<Component>(hpx::find_here()).get();
  }
  do_something() {
    client c(this->id); // SEGMENTATION FAULT
    c.action();
  }
private:
  hpx::naming::id_type id;
}

```

Any ideas?

## Specifications
  - HPX Version: 1.1.0
  - Platform (compiler, OS): GCC 8.0.1 / Linux / ARM

**Comment by hkaiser** [comment]
@hrasadi This should work without issues (AFAICS). Could you prepare a minimally complete test case that reproduces your issue, please?

**Comment by hrasadi** [comment]
OK. In the effort to create a minimal test case I identified a memory problem in my code that was the root cause of the problem. Therefore, I will close this issue. Sorry for the false alarm :)
