### ISSUE TITLE
Floating point bug in hpx/runtime/threads/policies/scheduler_base.hpp

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#3395]
## Expected Behavior
Octo-tiger to run

## Actual Behavior
Floating point exception causes crash.

When running octo-tiger I get a floating point crash within HPX sometimes. I've traced it to line 138 of hpx/runtime/threads/policies/scheduler_base.hpp. The offending call is std::pow(2.0,double(wait_count_)). When wait_count is large enough, this causes an overflow. In particular, I got the error when wait_count_=1033. Seems like wait_count should never get that high, so I'm not sure what's going on here. 

## Steps to Reproduce the Problem

The only way I have found to consistently reproduce it is to run octo-tiger with a specific start up file (q=0.7) on queenbee. It crashes when reading the startup file. When I set HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=OFF the problem goes away. I have seen the bug randomly occur in other conditions. 

## Specifications

  - HPX Version: master
  - Platform (compiler, OS): gcc, linux

**Comment by hkaiser** [comment]
@dmarce1 does it happen here: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/policies/scheduler_base.hpp#L137? If yes, what values do the involved variables have?

**Comment by msimberg** [comment]
@dmarce1 would you mind trying this branch: https://github.com/msimberg/hpx/tree/fix-exponential-backoff? My fix should work for you, but I'm not sure if it would fail on exotic hardware... 

Roughly how many cores are you running on? And how long does it take for it to fail? Are most cores idle before or while reading the startup file?

**Comment by dmarce1** [comment]
hkaiser - yes that's the place. all I know for sure is wait_count_ = 1033

msimberg - 20 cores on 100 nodes. It fails maybe 2 minutes into reading the startup checkpoint, and yes there should be a lot of idle cores when reading the checkpoint. I will give the fix a try.

**Comment by dmarce1** [comment]
msimberg -The branch you linked me to appears to fix the problem.
