### ISSUE TITLE
Ensure parent_task pointer when child task is created and child/parent are on same locality

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#3437]
Also discussed in [pull request 3432](https://github.com/STEllAR-GROUP/hpx/pull/3432)

## Expected Behavior

When tracking parent/child dependencies in distributed runs with APEX, if the parent and child localities aren't the same, we don't expect to be able to track dependencies (currently).  However, if parent and child are the same, we should be able to track dependencies.

## Actual Behavior

Some parent tasks disappear (are destroyed) before the child task is created (they are registered, then the parent exits, then the child is created).  That means we can't dereference the parent_task pointer to get the APEX data pointer (with the APEX GUID and type of the parent task).  This results in a seg fault.

## Steps to Reproduce the Problem

1. Configure with APEX, using these additional cmake flags and then compile HPX:

```
-DHPX_WITH_APEX=TRUE \
-DHPX_WITH_APEX_TAG=develop \
-DHPX_WITH_APEX_NO_UPDATE=FALSE \
-DAPEX_WITH_ACTIVEHARMONY=FALSE \
-DAPEX_WITH_OTF2=FALSE \
-DHPX_WITH_PARCELPORT_MPI=ON \
```

2. Run any example with mpirun, even just fibonacci:

```
mpirun -np 4 ./bin/fibonacci
```

## Specifications

  - HPX Version: current master
  - Platform (compiler, OS): all, all

**Comment by hkaiser** [comment]
This can be closed as #3432 was merged.
