### ISSUE TITLE
HPX no longer builds on IBM POWER8

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#3438]
## Expected Behavior

POWER 8 builds with Clang 5.0 used to work, until recently.
I think the last (?) commit that compiled on POWER8 was 085cbc672de93376a8a0577ed79a3fae71c35257.  

## Actual Behavior

After the batch of commits around 5 days ago (see http://ktau.nic.uoregon.edu:8020/#/builders/2/builds/179, changes), POWER8 builds of HPX have failed, because of "unsupported platform":

```
[  3%] Building CXX object tools/CMakeFiles/cpu_features_exe.dir/cpu_features.cpp.o
cd /home/users/khuck/src/phylanx/tools/buildbot/build-centaur-ppc64le-Linux-clang/hpx-Release/tools && /usr/local/packages/llvm/5.0.0-ppc64le/bin/clang++  -DHPX_APPLICATION_EXPORTS -DHPX_APPLICATION_NAME=cpu_features_exe -DHPX_APPLICATION_STRING=\"cpu_features_exe\" -DHPX_PREFIX=\"/home/users/khuck/src/phylanx/tools/buildbot/build-centaur-ppc64le-Linux-clang/hpx-Release\" -D_GNU_SOURCE -I/home/users/khuck/src/phylanx/tools/buildbot/src/hpx -isystem /home/users/khuck/src/phylanx/tools/buildbot/build-centaur-ppc64le-Linux-clang/boost-1.65.0/include -I/usr/local/packages/hwloc/1.8/include -I/home/users/khuck/src/phylanx/tools/buildbot/src/hpx/apex/src/apex -I/home/users/khuck/src/phylanx/tools/buildbot/build-centaur-ppc64le-Linux-clang/hpx-Release  -fPIC -pthread -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Werror=return-type -Wno-cast-align -O3 -DNDEBUG   -std=c++17 -o CMakeFiles/cpu_features_exe.dir/cpu_features.cpp.o -c /home/users/khuck/src/phylanx/tools/buildbot/src/hpx/tools/cpu_features.cpp
In file included from /home/users/khuck/src/phylanx/tools/buildbot/src/hpx/tools/cpu_features.cpp:18:
/home/users/khuck/src/phylanx/tools/buildbot/src/hpx/hpx/util/hardware/cpuid.hpp:88:6: error: Unsupported
      platform.
    #error Unsupported platform.
     ^
```

## Steps to Reproduce the Problem

  1. On a POWER8 platform, configure HPX with (or equivalent):

```
cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/home/users/khuck/src/phylanx/tools/buildbot/build-centaur-ppc64le-Linux-clang/boost-1.65.0 -DTCMALLOC_ROOT=/usr/local/packages/gperftools/2.5 -DHPX_WITH_MALLOC=tcmalloc -DHWLOC_ROOT= -DCMAKE_INSTALL_PREFIX=. -DHPX_WITH_THREAD_IDLE_RATES=ON -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCEL_COALESCING=OFF -DHPX_WITH_TOOLS=ON -DHPX_WITH_APEX=TRUE -DAPEX_WITH_ACTIVEHARMONY=TRUE -DACTIVEHARMONY_ROOT=/usr/local/packages/activeharmony/4.6.0-ppc64le -DAPEX_WITH_OTF2=TRUE -DOTF2_ROOT=/usr/local/packages/otf2/2.0-ppc64le -DAPEX_WITH_PAPI=TRUE -DPAPI_ROOT=/usr/local/packages/papi/5.5.1 -DHPX_WITH_APEX_NO_UPDATE=TRUE -DHPX_WITH_APEX_TAG=develop -DHWLOC_ROOT=/usr/local/packages/hwloc/1.8 -DHPX_WITH_RDTSCP=OFF -DHPX_WITH_DEPRECATION_WARNINGS=Off -DHPX_WITH_MAX_CPU_COUNT=160 /home/users/khuck/src/phylanx/tools/buildbot/src/hpx
```

## Specifications

... Please describe your environment

  - HPX Version: current master
  - Platform (compiler, OS):  POWER8 linux, using Clang 5.0

**Comment by hkaiser** [comment]
@khuck I'm sure that this code was not touched in a long time. @sithhell did you see these errors when compiling things for Power8?

**Comment by biddisco** [comment]
I compiled HPX with clang a couple of weeks ago on power - I built clang from source so it was a recent one. I had test fails and eventually gave up and compiled GCC instead. You may recall I replaced all memory orderings with sequentially consistent to see if it was a race caused by the C++ memory model bug on power.

**Comment by biddisco** [comment]
NB. I cannot remember if I had to make any tweaks to get everything compiling ok.

**Comment by hkaiser** [comment]
@biddisco IIRC, you switched to gcc and all was well. Clang was causing strange problems in the parallel algorithms.

**Comment by sithhell** [comment]
I think that bug is genuine. The TU being compiled leading to that error (https://github.com/STEllAR-GROUP/hpx/blob/master/tools/cpu_features.cpp) is not part of HPX core and was never written with anything else than X86 in mind. I guess the right thing to do here would be to disable this tool (which isn't used anywhere, IIRC) in cmake when compiling for anything but x86. I am surprised that you said it worked with older commits.

**Comment by khuck** [comment]
It turns out that this is related to my own patch.  I removed the "APEX_HAVE_HPX" macro from hpx/config.h because it was defined in the main APEX CMakeLists.hpx file (to tell the compiler to include hpx/config.h) which generated lots of warnings of duplicate macro definitions.  The problem is that because there are circular dependencies between HPX and APEX, there is HPX code that includes APEX headers, and those need the macro defined - but by defining it in CMakeLists.hpx it is only defined when APEX .cpp files are compiled (i.e. the source for libapex.so).  I have a fix for this in APEX, no change to HPX is required - I am testing it this afternoon.  As to why this is only triggered on POWER8 with Clang, I don't know... the solution is to use two macros, the current one defined in hpx/config.h and another to tell APEX to include hpx/config.h when necessary.

I will close the current bug, because it is only tripped when configuring HPX with APEX, and because of the problem with APEX_HAVE_HPX not getting defined for HPX headers that include apex_api.hpp.
