### ISSUE TITLE
mpi initialization in slurm environment

### ISSUE THREAD

**Issue by kleinhenz** [STEllAR-GROUP/hpx#3447]
## Expected/Actual Behavior

I am running an hpx code that just uses the hpx parallel algorithms and contains no internode parallelism in a slurm environment. When I execute the code in a script submitted via `sbatch` I need to use `srun` otherwise the code fails with the following error. 

```
Thu Sep  6 14:25:15 2018: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Thu Sep  6 14:25:15 2018: [unset]:_pmi_init:_pmi_alps_init returned -1
[Thu Sep  6 14:25:15 2018] [c3-0c2s0n3] Fatal error in MPI_Init: Other MPI error, error stack:
MPIR_Init_thread(537):
MPID_Init(246).......: channel initialization failed
MPID_Init(647).......:  PMI2 init failed: 1
/var/spool/slurmd/job14660706/slurm_script: line 13: 31070 Aborted                 ./build/main
```

I would expect that if an hpx executable is invoked directly without `srun` it shouldn't attempt to initialize an mpi environment and should just run on the node on which it is invoked, especially if `SLURM_NNODES=1`. Additionally, this behavior seems to be inconsistent between batch and interactive slurm environments. In an interactive slurm environment obtained via `salloc` I am able to invoke the program directly without any error. I'm not exactly sure what the expected behavior should be here. It isn't a huge deal but it is not ideal to have to use `srun` for single node programs with short runtimes that are invoked a lot. 

## Steps to Reproduce the Problem

This can be reproduced on cori with a simple hello world app. 

main.cpp:
```
#include <hpx/hpx_init.hpp>
#include <hpx/include/iostreams.hpp>

int hpx_main()
{
    hpx::cout << "hello world" << hpx::endl;
    return hpx::finalize();
}

int main(int argc, char* argv[])
{
    // Initialize and run HPX.
    return hpx::init(argc, argv);
}
```

run.job:
```
#!/usr/bin/env bash

#SBATCH --constraint=haswell
#SBATCH --nodes=1
#SBATCH --qos=debug
#SBATCH --time=0:10:00

# error
#./build/main

# no error
srun ./build/main
```

## Specifications

  - HPX Version: master (1458fcc0c1f58135a6f3563701b784eb96838cf0)
  - Platform: gcc 7.1.0 on cori haswell

**Comment by biddisco** [comment]
Your first solution is to compile HPX with `HPX_WITH_PARCELPORT_MPI=OFF` and `HPX_WITH_PARCELPORT_TCP=ON` another is to disable networking completely using `HPX_WITH_NETWORKING=OFF`. I'm not sure that I care enough about single node MPI jobs to fix the slurm environment to handle this, but if someone else wants to submit a patch ... :)

**Comment by kleinhenz** [comment]
This executable is one part of a larger application that does require mpi networking so that solution isn't really viable. It's not a big deal, I just found it surprising since outside of the slurm batch environment hpx applications seem to be perfectly happy to be invoked directly.

**Comment by hkaiser** [comment]
Could you please post the environment the SLURM job is launched in? I don't know too much of how SLURM launches jobs, but I may be able to have a look and to fix the issue you're describing.

**Comment by biddisco** [comment]
The fix ought to be very easy, just look in slurm environment, see if num nodes==1, and if so, skip `MPI_init` and `MPI_finalize`

**Comment by biddisco** [comment]
and make sure the parcelport doesn't try to send anything!
