### ISSUE TITLE
hpx::lcos::promise loses performance over time

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#3449]
## Expected Behavior

I expect the performance of hpx::lcos::promise to not depend on how long the hpx application has been running.

## Actual Behavior

As an hpx application runs, hpx::lcos::promise loses performance while hpx::lcos::local::promise does not.

## Steps to Reproduce the Problem

Use the code here:
https://gist.github.com/dmarce1/e33b0f374f29007a5744e255f3fe3167

Compile with:
g++ bug.cpp `pkg-config --cflags --libs hpx_application`

Execute with: 
./a.out

A file called output.txt will be produced with timings for hpx::lcos::local::promise in the 2nd column and hpx::lcos::promise in the third. 

When I plot each of these, I get the following output:

![local](https://user-images.githubusercontent.com/568063/46362087-f7099700-c634-11e8-808e-29eb59e73a67.png)

![global](https://user-images.githubusercontent.com/568063/46362106-04268600-c635-11e8-9b43-10fae933cfd7.png)

The first plot shows that the performance of hpx::lcos::local::promise tends to average about the same over time, while the performance of hpx::lcos::promise degrades over time.

 
## Specifications

  - HPX Version: 66223eb565321291f471b2e72653f2fd4e84de86
  - Platform (compiler, OS): gcc 7.3.0 Ubuntu 18.04.1

**Comment by hkaiser** [comment]
This is an interesting effect. Thanks for reporting!

**Comment by hkaiser** [comment]
@dmarce1 the code you referenced looks to be incomplete (https://gist.github.com/dmarce1/e33b0f374f29007a5744e255f3fe3167). Could you recheck, please?
