### ISSUE TITLE
CMake configuration shows a minor and inconsequential failure to create a symlink

### ISSUE THREAD

**Issue by jayeshbadwaik** [STEllAR-GROUP/hpx#3462]
## Expected Behavior

When running cmake, the output should be clean without any errors.

## Actual Behavior

Instead, we get a error saying `failed to create symbolic link '/home/jayesh/build/hpx/share/hpx': No such file or directory` which can be seen in the full output [here](https://gist.github.com/jayeshbadwaik/005cf0c5426a91fe1995e37be9f3dc8b). This happens because the parent directory of the target directory does not yet exist. Ultimately, the error is not fatal and the install continues correctly. However, it is annoying.

The fix is minor as shown [here](https://github.com/jayeshbadwaik/hpx/commit/e1c7ab4e953ab60bcc68dda2110a1d2682e608aa).  

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. `git clone git@github.com:STEllAR-GROUP/hpx.git`
  2. `mkdir build && cd build`
  3. `cmake ../hpx`

## Specifications
  - HPX Version: master (git commit: 61e7a441e4a)
  - Platform (compiler, OS): ArchLinux, gcc-8.2

**Comment by hkaiser** [comment]
@jayeshbadwaik Please go ahead and create a pull request against this repository. We'd be happy to accept it. Thanks!
