### ISSUE TITLE
HPX fails to link if the MPI parcelport is enabled

### ISSUE THREAD

**Issue by chinz07** [STEllAR-GROUP/hpx#3475]
## Expected Behavior

HPX should link successfully.

## Actual Behavior

Linking HPX fails with the following linker errors:

```
/usr/bin/ld: CMakeFiles/hpx.dir/version.cpp.o: in function `MPI::Op::Init(void (*)(void const*, void*, int, MPI::Datatype const&), bool)':
version.cpp:(.text._ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb[_ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb]+0x19): undefined reference to `ompi_mpi_cxx_op_intercept'
/usr/bin/ld: CMakeFiles/hpx.dir/version.cpp.o: in function `MPI::Intracomm::Clone() const':
version.cpp:(.text._ZNK3MPI9Intracomm5CloneEv[_ZNK3MPI9Intracomm5CloneEv]+0x3f): undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: CMakeFiles/hpx.dir/version.cpp.o: in function `MPI::Graphcomm::Clone() const':
version.cpp:(.text._ZNK3MPI9Graphcomm5CloneEv[_ZNK3MPI9Graphcomm5CloneEv]+0x38): undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: CMakeFiles/hpx.dir/version.cpp.o: in function `MPI::Cartcomm::Sub(bool const*) const':
version.cpp:(.text._ZNK3MPI8Cartcomm3SubEPKb[_ZNK3MPI8Cartcomm3SubEPKb]+0xa4): undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: CMakeFiles/hpx.dir/version.cpp.o: in function `MPI::Intracomm::Create_graph(int, int const*, int const*, bool) const':
version.cpp:(.text._ZNK3MPI9Intracomm12Create_graphEiPKiS2_b[_ZNK3MPI9Intracomm12Create_graphEiPKiS2_b]+0x3b): undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: CMakeFiles/hpx.dir/version.cpp.o: in function `MPI::Cartcomm::Clone() const':
version.cpp:(.text._ZNK3MPI8Cartcomm5CloneEv[_ZNK3MPI8Cartcomm5CloneEv]+0x38): undefined reference to `MPI::Comm::Comm()'
/usr/bin/ld: CMakeFiles/hpx.dir/version.cpp.o:version.cpp:(.text._ZNK3MPI9Intracomm11Create_cartEiPKiPKbb[_ZNK3MPI9Intracomm11Create_cartEiPKiPKbb]+0xae): more undefined references to `MPI::Comm::Comm()' follow
/usr/bin/ld: CMakeFiles/hpx.dir/version.cpp.o:(.data.rel.ro._ZTVN3MPI8DatatypeE[_ZTVN3MPI8DatatypeE]+0x78): undefined reference to `MPI::Datatype::Free()'
/usr/bin/ld: CMakeFiles/hpx.dir/version.cpp.o:(.data.rel.ro._ZTVN3MPI3WinE[_ZTVN3MPI3WinE]+0x48): undefined reference to `MPI::Win::Free()'

```

## Steps to Reproduce the Problem

Compile HPX with CMake >= 3.10 and OpenMPI with HPX_WITH_PARCELPORT_MPI enabled.

## Specifications

  - HPX Version: 1.2.0 (commit: e7d1ae4c5ba91b841fd2fa7fed99b712d0270cfe)
  - Platform (compiler, OS): Arch Linux (GCC 8.2.1, OpenMPI 3.1.2, CMake 3.12.2)

I have a, rather ugly, workaround for the linker errors. If the issue should be fixed immediately I could submit a PR containing the workaround. Alternatively, I am currently working on a proper fix. The root cause seems to be a problem with the scope of several CMake variables, exacerbated by the use of macros. It should be possible to get rid of both the macros and most of variables by using modern CMake targets and user-defined target properties. I have made good experiences using this approach in my current project.

**Comment by biddisco** [comment]
What a coincidence - look at #3474 and the issue it refers to.

**Comment by chinz07** [comment]
@biddisco Yes. A proper fix might make more sense as part of a larger modernization effort. I will submit my workaround as a PR so we can hopefully fix this issue before releasing HPX 1.2.0.

**Comment by biddisco** [comment]
Incidentally - Did you try the flags mentioned in #3444 and #3439 before submitting your patch?
-DMPI_CXX_SKIP_MPICXX etc

**Comment by chinz07** [comment]
No, I haven't. I have now tested the flags on Arch Linux and Ubuntu 18.04 using OpenMPI. Adding -DOMPI_SKIP_MPICXX=1 to the compiler flags does indeed fix the issue. Adding -DMPI_CXX_SKIP_MPICXX=ON to the CMake command line does not for some reason. Maybe I am using it incorrectly.

These flags also introduce a huge problem if I am not mistaken. If HPX ever includes mpi.h as part of a public header and the user also uses the MPI C++ interface, setting, for example, OMPI_SKIP_MPICXX will most likely break the code. HPX disables the C++ interfaces which is part of mpi.h to fix the linker issues. Afterwards the user code includes mpi.h to obtain the C++ interface. At this point the header guards of mpi.h kick in and the C++ interface will not be included and the user code breaks. I have not tested this scenario yet but this might be problematic.

The MPI find module does avoid this pitfall by always including any C++-specific library if the **C++-aware** C interface (CXX vs. MPICXX) has been requested. In this case the C++ interface is always available.

**Comment by chinz07** [comment]
'hpx/plugins/parcelport/mpi/mpi_environment.hpp' is not a public header? That would be unfortunate. The older parts of the codes I maintain still use raw MPI in conjunction with HPX for the newer algorithms. As these codes are ancient and do contain F77 it is pretty much impossible to port them to HPX. Currently I use HPX's mpi_environment as a bridge between the old and the new code.

Anyway! If mpi.h is never exposed I agree that disabling the (deprecated) C++ interface is a better fix.

If the header files of the MPI parcelport are not public it might be a good idea to exclude them from the installation. I will look into that during the build system modernization.

**Comment by biddisco** [comment]
I'm not sure we have a definitive list of what is and isn't part of the public API that should be installed as part of the  headers. My suspicion is that we install virtually everything - largely because includes pull in things that they maybe shouldn't and it's too big a job to clean it all up and make it perfect - we try our best to use `xxx_fwd.hpp` files where we can to minimize the #include pollution.

**Comment by hkaiser** [comment]
Is this still an issue (after merging #3485)?

**Comment by biddisco** [comment]
if we just set `MPI_CXX_SKIP_MPICXX` before calling `find_package(MPI)` (see https://cmake.org/cmake/help/v3.12/module/FindMPI.html) does the problem go away?

If not and you still have the bug, then please feel free to submit whatever fix you think best.

**Comment by chinz07** [comment]
Yes. Disabling the C++ interface via MPI_CXX_SKIP_MPICXX does resolve the problem. The only caveat is that you have to be really careful which CMake variables you use. The predefined targets use an incorrect combination of settings in this specific case and are thus unusable.

I have also tested if this setup allows to use HPX in conjunction with MPI's C++ bindings as part of an external project. Fortunately, this does work as long as the external project is set up to link against MPI explicitly.

Since you seem to prefer this solution, I will submit a PR implementing this fix. Afterwards the PR for my alternative fix (#3477) can be closed.

**Comment by justwagle** [comment]
This still fails for me with the latest master.  
Here is a buildlog: 
https://gist.github.com/justwagle/0a86fca9abf829137c4a2b679cc33d2e

I would greatly appreciate if someone would point me to what I am doing wrong.

Thanks

**Comment by chinz07** [comment]
@justwagle Could you please try to set `MPI_CXX_SKIP_MPICXX` to `True` on the command-line?

Depending on the version of CMake `MPI_CXX_SKIP_MPICXX` is unfortunately either a normal variable or a cache variable. Currently, we only set it automatically if it is a normal variable. I will try to find a better solution.

**Comment by justwagle** [comment]
@chinz07 I tried adding  ` -DMPI_CXX_SKIP_MPICXX=True ` to my hpx build script which resulted in the following error:
```
-- Found TCMalloc: /opt/mn/gperftools/2.7/lib/libtcmalloc_minimal.so  
-- Using tcmalloc allocator.
-- Found Hwloc: /usr/lib64/libhwloc.so  
-- Found Git: /opt/eb/software/git/2.8.3/bin/git (found version "2.8.3") 
-- GIT commit is 4970f98d0219d3f6405a13f6f1b18889774a95cd.
-- Found MPI_C: /usr/lib64/openmpi/lib/libmpi.so (found version "3.0") 
-- Found MPI_CXX: /usr/lib64/openmpi/lib/libmpi_cxx.so (found version "3.0") 
-- Found MPI: TRUE (found version "3.0")  
CMake Error at plugins/parcelport/mpi/CMakeLists.txt:33 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".


-- Configuring incomplete, errors occurred!
See also "/home/bwagle/Packages/testit/libs/hpx/Release/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
```
The full build log can be found in the following gist:
https://gist.github.com/justwagle/b982fc49f575b60b7a7910b0b511aead

A little googling tells me that  "add_compile_definitions" is something that was merged into cmake about 6 months ago. The cmake version that I have , 3.10.2 is not able to understand the new command.

**Comment by chinz07** [comment]
@justwagle Thank you for the feedback. You are right that we can not use `add_compile_definitions` since it was only introduced as part of CMake 3.11. PR #3541 should resolve both issues. Could you please try it out?

**Comment by justwagle** [comment]
@chinz07 PR #3541 worked for me, thanks a lot.
