### ISSUE TITLE
Improve error message when HPX_WITH_MAX_CPU_COUNT is too low for given system

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3482]
Currently HPX has to be configured with a big enough `HPX_WITH_MAX_CPU_COUNT` for a given system. If it's set incorrectly the user will be presented with error messages that have no relation to the original problem.

We could either consider changing the bitsets to be fully dynamic (performance problems?) to avoid the variable altogether or try to detect at runtime if it's set inappropriately and give a helpful error message to the user.

**Comment by hkaiser** [comment]
@diehlpk FWIW, if you add for instance 'Fixes #3482' to the description of your PR, GitHub will auto-close this ticket once the PR is merged.
