### ISSUE TITLE
Error while building HPX with CUDA

### ISSUE THREAD

**Issue by schwarzschild-radius** [STEllAR-GROUP/hpx#3545]
## Expected Behavior

Built all target

## Actual Behavior

The build fails with the following error:

    [ 68%] Building NVCC (Device) object examples/compute/cuda/CMakeFiles/data_copy_exe.dir/data_copy_exe_generated_data_copy.cu.o
		cd /home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir && /usr/local/bin/cmake -E make_directory /home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir//.
		cd /home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir && /usr/local/bin/cmake -D verbose:BOOL=1 -D build_configuration:STRING=Release -D generated_file:STRING=/home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir//./data_copy_exe_generated_data_copy.cu.o -D generated_cubin_file:STRING=/home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir//./data_copy_exe_generated_data_copy.cu.o.cubin.txt -P /home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir//data_copy_exe_generated_data_copy.cu.o.Release.cmake
		-- Removing /home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir//./data_copy_exe_generated_data_copy.cu.o
		/usr/local/bin/cmake -E remove /home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir//./data_copy_exe_generated_data_copy.cu.o
		-- Generating dependency file: /home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir//data_copy_exe_generated_data_copy.cu.o.NVCC-depend
		/usr/local/cuda-9.2/bin/nvcc -M -D__CUDACC__ /home/amcsgpu/PK/Experiments/hpx/examples/compute/cuda/data_copy.cu -o /home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir//data_copy_exe_generated_data_copy.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 -DHPX_APPLICATION_NAME=data_copy_exe -DHPX_APPLICATION_STRING=\"data_copy_exe\" -DHPX_PREFIX=\"/usr/local\" -DHPX_APPLICATION_EXPORTS -D_GNU_SOURCE -DHPX_DISABLE_ASSERTS -DBOOST_DISABLE_ASSERTS -Xcompiler ,\"-O3\",\"-DNDEBUG\" -w -gencode=arch=compute_20,code=sm_20 -std=c++17 --expt-relaxed-constexpr --expt-extended-lambda --default-stream per-thread -lcudadevrt -rdc=true -DNVCC -I/usr/local/cuda-9.2/include -I/home/amcsgpu/PK/Experiments/hpx -I/usr/include -I/home/amcsgpu/PK/Experiments/hpx/build -I/home/amcsgpu/PK/Experiments/hpx/tests -I/home/amcsgpu/PK/Experiments/hpx/examples
		nvcc fatal   : Value 'c++17' is not defined for option 'std'
		CMake Error at data_copy_exe_generated_data_copy.cu.o.Release.cmake:219 (message):
		  Error generating
		  /home/amcsgpu/PK/Experiments/hpx/build/examples/compute/cuda/CMakeFiles/data_copy_exe.dir//./data_copy_exe_generated_data_copy.cu.o

		examples/compute/cuda/CMakeFiles/data_copy_exe.dir/build.make:63: recipe for target 'examples/compute/cuda/CMakeFiles/data_copy_exe.dir/data_copy_exe_generated_data_copy.cu.o' failed
		make[2]: *** [examples/compute/cuda/CMakeFiles/data_copy_exe.dir/data_copy_exe_generated_data_copy.cu.o] Error 1
		make[2]: Leaving directory '/home/amcsgpu/PK/Experiments/hpx/build'
		CMakeFiles/Makefile2:64287: recipe for target 'examples/compute/cuda/CMakeFiles/data_copy_exe.dir/all' failed
		make[1]: *** [examples/compute/cuda/CMakeFiles/data_copy_exe.dir/all] Error 2

## Steps to Reproduce the Problem

cmake -DHPX_WITH_CUDA=ON && make

## Specifications

  - CUDA: 9.2
  - gcc: 5.4
  - HPX Version: latest master
  - Platform (compiler, OS): Ubuntu 16.04 LTS

**Comment by msimberg** [comment]
Thanks for the report. I think this error specifically is a CUDA/`nvcc` limitation. Even though gcc 5.4 should support `-std=c++17`, I think CUDA 9.2 still doesn't (feel free to correct me here). Can you verify by compiling a standalone test program directly with `nvcc -std=c++17`?

On the other hand this sounds like something our feature checks should catch and downgrade you to C++11/14 automatically. You can also explicitly set `-DHPX_WITH_CXX11` or `-DHPX_WITH_CXX14` when you configure HPX to force C++11/14.

Unfortunately, once you get past this you will most likely hit some real compilation errors as our CUDA support is in need of some love. If you let us know what problems you get after that and what you're aiming to do we can try to prioritize fixing it.

**Comment by pradeepisro** [comment]
nvcc in cuda-9.2 does not support c++17. When try `ccmake ..` to set options, the c++ standard is set to c++ 17 automatically but when I set with `cmake .. -DHPX_WITH_CUDA=ON` the standard is automatically detected as c++11. It is either during cmake curses it is automatically configured to c++17 and cached then while setting HPX_WITH_CUDA, the C++ standard is taken from cache. Is there a way to overwrite cache when the option is updated.

**Comment by msimberg** [comment]
Yes, some variables related to the C++ standard are cached (I think it might be due to the feature checks being relatively expensive). In general, try to avoid reconfiguring options that might affect compiler flags (until we have a better solution).

I think `_NV_ANON_NAMESPACE` is just something that `nvcc` inserts as a placeholder for anonymous namespaces. The real problem might be related to [this](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#const-variables) and [this](https://github.com/STEllAR-GROUP/hpx/blob/411a9651e0a91e588790e4cb14241a5a15b49089/hpx/parallel/executors/execution_parameters_fwd.hpp#L486-L506). But I'm not sure what the solution looks like...
