### ISSUE TITLE
1>e:\000work\hpx\src\throw_exception.cpp(54): error C2440: '<function-style-cast>': cannot convert from 'boost::system::error_code' to 'hpx::exception'

### ISSUE THREAD

**Issue by alanthie** [STEllAR-GROUP/hpx#3550]
1>e:\000work\hpx\src\throw_exception.cpp(54): error C2440: '<function-style-cast>': cannot convert from 'boost::system::error_code' to 'hpx::exception'

boost 1.69

hpx::exception(ec), // boost::system::**error_code** ec
vs
explicit exception(boost::system::**system_error** const& e);

**Comment by alanthie** [comment]
Workaround fixes (windows):

hpx:
In std::exception_ptr get_exception()
1-hpx::exception(boost::system::system_error(ec)),

In default_write_handler()
   hpx::detail::get_exception(    hpx::exception(boost::system::system_error(ec)) ,

2- boost:
In struct allocator_traits
**#undef max**
    static size_type max_size(const A&) BOOST_NOEXCEPT {
        return std::numeric_limits<size_type>::max() / sizeof(value_type);

**Comment by msimberg** [comment]
@K-ballo do you know what this might be about? 1.69 is not out yet so it may be a bug in Boost, or we have to deal with it once 1.69 actually is out.

**Comment by K-ballo** [comment]
> @K-ballo do you know what this might be about?

Boost 1.69 went ahead and implemented [LWG3162](https://cplusplus.github.io/LWG/issue3162). We'll need a constructor from `error_code` to make this conversion explicit.

**Comment by hkaiser** [comment]
The second workaround listed above (adding `#undef max`) is caused by Boost violating their own guidelines.

**Comment by hkaiser** [comment]
> Boost 1.69 went ahead and implemented LWG3162. We'll need a constructor from error_code to make this conversion explicit.

@K-ballo Boost made the conversion constructor explicit. Do you suggest for us to add an implicit constructor `exception(boost::system::error_code const&)` to compensate?

**Comment by hkaiser** [comment]
See #3558 for a possible fix. @alanthie could you please check whether this fixes your issue? Also, please report the `#undef` issue to the Boost mailing list.

**Comment by K-ballo** [comment]
> @K-ballo Do you suggest for us to add an implicit constructor `exception(boost::system::error_code const&)` to compensate?

Our constructor should be `explicit`, just as the current constructor from `boost::system::system_error` is.
