### ISSUE TITLE
Apex integration with HPX not working properly

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3560]
## Expected Behavior
Nice plots of tasks

## Actual Behavior
All the tasks have the same `parallel::execution::post` name.
I am using the RAII style apex wrapper with `profiler::TaskProfiler tp(taskname, "Trailing Matrix");` that wraps an `hpx::util::annotate_function apex_profiler;` and is instantiated at the start of the task.
Note that is differs from the lambda style `annotated_function` by setting the name of the task _inside_ the task, whereas the lambda version does it on creation on the task.

I attempted to attach a screen shot of vampir, but it doesn't seem to work.

hoping @khuck knows what's wrong

**Comment by biddisco** [comment]
![screenshot_20181120_145856](https://user-images.githubusercontent.com/941548/48778560-d9bc8500-ecd5-11e8-99a7-4e645c0fa18b.jpeg)

**Comment by biddisco** [comment]
Each of the purple bars above is actually many tasks (see the one with the shading slightly lighter that has been highlighted)

**Comment by biddisco** [comment]
Looking at the code I wondered
https://github.com/STEllAR-GROUP/hpx/blob/457670e0581fe03ee4b4b4b12b0a757eff445307/hpx/runtime/threads/thread_data.hpp#L302-L303
Should this function return `description_` and not `value`?

**Comment by biddisco** [comment]
@khuck The problem sees to be around here ... 
https://github.com/khuck/xpress-apex/blob/c4ab0b07ffa6f524866b4694a3c7c19f9f4c1140/src/apex/apex.cpp#L1103-L1115
I can see as I step through the code that when I set a new task description, the original wrapper->id has name"parallel::execution::post" and the new description is "HP Fact. Diag Block 0". Apex looks for the name in it's internal task map, does not find it and returns a new ID. This gets added to the alias of the task, but the name of the task does not change.

**Comment by hkaiser** [comment]
> Looking at the code I wondered
https://github.com/STEllAR-GROUP/hpx/blob/457670e0581fe03ee4b4b4b12b0a757eff445307/hpx/runtime/threads/thread_data.hpp#L302-L303
Should this function return `description_` and not `value`?

No, the function should return the previous description value.

**Comment by biddisco** [comment]
> No, the function should return the previous description value.

OK. Seems very odd though.
https://github.com/STEllAR-GROUP/hpx/blob/653a61d078a64c24746fb36065701508e5ee1f70/hpx/util/annotated_function.hpp#L75-L86
in that snippet, what we do is annotate a function with a name, set the task description to the new name and initialize the desc_ object with the old desc data returned from that function, then pass the old data to apex. I guess if apex is tracking it, then it knows what to do, but it looks most strange to my eyes. I guess I'm reading things wrongly.

**Comment by biddisco** [comment]
I'm giving up on this. AFAICT we end up with an apex object for the task that is names parallel::post and has a list of aliases of length N, where N is the number of task types in my code (roughly). Then apes just dumps out the OTF2 files with the same name for every task.
I tried rolling apex back by a few months and tried rolling back some changes to annotate function, but I can't make the old stuff work.

**Comment by hkaiser** [comment]
@biddisco I think this has been fixed recently (see: #3624). Please reopen, if needed.

**Comment by biddisco** [comment]
Has anyone tested this and confirmed that it does in fact work?
We're running our cholesky code and not seeing task names as expected.
We're using the RAII version `hpx::util::annotate_function` and not the lambda style wrapper `hpx::util::annotated_function` and perhaps this one was not checked. Is there a test anywhere that we can run to see if the basic functionality is ok? (I'm debugging this via someone else's build)

**Comment by hkaiser** [comment]
@khuck any comments?

**Comment by biddisco** [comment]
I just tested on my local build with hpx master and apex develop branch from today. I'm sorry to say that there are still no task names
![image](https://user-images.githubusercontent.com/941548/56840128-265c4b80-6886-11e9-9ed3-ab4f5fc1d7d2.png)

**Comment by biddisco** [comment]
I just tried with latest master, and the head of the develop branch of apex and am seeing what looks like the correct task names appear in vampir plots. I will do further tests tomorrow to confirm if all is fixed and working as expected. Thanks

**Comment by biddisco** [comment]
![image](https://user-images.githubusercontent.com/941548/60182278-54c5bb00-9824-11e9-93b1-57fc6b7cc67b.png)
```
    hpx::util::annotate_function apex_profiler("Outside null_function");
    // start the clock
    high_resolution_timer walltime;
    {
        hpx::threads::executors::limiting_executor<Executor> signal_exec(
            exec, tasks, tasks + 1000);
        for (std::uint64_t i = 0; i < count; ++i) {
            hpx::apply(signal_exec, [&](){
                hpx::util::annotate_function apex_profiler("inside null_function");
                null_function();
                sanity_check--;
            });
        }
    }
```
This code snippet is interesting. I see 10,000 calls to OUTER null_function, instead of the expected 10,000 calls to the INSIDE null function.

Something is working, but only partially.

**Comment by biddisco** [comment]
This is the future overhead test, modified with a few annotated function calls. This version might need one line commented out as I was experimenting with an overload to parallel::execution::post  that accepts an annotated function object as the first `Ts...` after the executor and takes the task description from that .
```
//  Copyright (c) 2018 Mikael Simberg
//  Copyright (c) 2011 Bryce Adelstein-Lelbach
//
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// TODO: Update

#include <hpx/hpx_init.hpp>
#include <hpx/lcos/wait_each.hpp>
#include <hpx/runtime/actions/plain_action.hpp>
#include <hpx/runtime/actions/continuation.hpp>
#include <hpx/util/format.hpp>
#include <hpx/util/high_resolution_timer.hpp>
#include <hpx/include/apply.hpp>
#include <hpx/include/async.hpp>
#include <hpx/include/iostreams.hpp>
#include <hpx/include/threads.hpp>
#include <hpx/util/yield_while.hpp>
#include <hpx/util/lightweight_test.hpp>
#include <hpx/util/annotated_function.hpp>

#include <hpx/include/parallel_execution.hpp>
#include <hpx/lcos/local/sliding_semaphore.hpp>
#include <hpx/runtime/threads/executors/limiting_executor.hpp>
#include <hpx/runtime/threads/executors/pool_executor.hpp>

#include <array>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <vector>

using boost::program_options::variables_map;
using boost::program_options::options_description;
using boost::program_options::value;

using hpx::init;
using hpx::finalize;

using hpx::find_here;
using hpx::naming::id_type;

using hpx::future;
using hpx::async;
using hpx::apply;
using hpx::lcos::wait_each;

using hpx::util::high_resolution_timer;

using std::cout;
using std::flush;

///////////////////////////////////////////////////////////////////////////////
void print_stats(const char* title, const char* wait, const char* exec,
    std::int64_t count, double duration, bool csv)
{
    double us = 1e6*duration/count;
    if (csv)
        hpx::util::format_to(cout,
            "{1},{2},{3},{4},{5},{6},\n",
           count, title, duration, us) << flush;
    else
        hpx::util::format_to(cout,
            "invoked {1}, futures {:10} {:15} {:20} in \t{5} seconds \t: "
            "{6} us per future \n",
            count, title, wait, exec, duration, us) << flush;

    // CDash graph plotting
    //hpx::util::print_cdash_timing(title, duration);
}

const char* ExecName(const hpx::parallel::execution::parallel_executor& exec)
{
    return "parallel_executor";
}
const char* ExecName(const hpx::parallel::execution::default_executor& exec)
{
    return "default_executor";
}

///////////////////////////////////////////////////////////////////////////////
// we use globals here to prevent the delay from being optimized away
double global_scratch = 0;
std::uint64_t num_iterations = 0;

///////////////////////////////////////////////////////////////////////////////
double null_function()
{
    //hpx::util::annotate_function apex_profiler("null_function");
    std::this_thread::sleep_for(std::chrono::microseconds(500));

    if (num_iterations > 0)
    {
        const int array_size = 4096;
        std::array<double, array_size> dummy;
        for (std::uint64_t i = 0; i < num_iterations; ++i)
        {
            for (std::uint64_t j = 0; j < array_size; ++j)
            {
                dummy[j] = 1.0 / (2.0 * i * j + 1.0);
            }
        }
        return dummy[0];
    }
    return 0.0;
}

HPX_PLAIN_ACTION(null_function, null_action)

struct scratcher
{
    void operator()(future<double> r) const
    {
        global_scratch += r.get();
    }
};

// Time async action execution using wait each on futures vector
void measure_action_futures_wait_each(std::uint64_t count, bool csv)
{
    const id_type here = find_here();
    std::vector<future<double> > futures;
    futures.reserve(count);

    // start the clock
    high_resolution_timer walltime;
    for (std::uint64_t i = 0; i < count; ++i)
        futures.push_back(async<null_action>(here));
    wait_each(scratcher(), futures);

    // stop the clock
    const double duration = walltime.elapsed();
    print_stats("Actions", "WaitEach", "no-executor", count, duration, csv);
}

// Time async action execution using wait each on futures vector
void measure_action_futures_wait_all(std::uint64_t count, bool csv)
{
    const id_type here = find_here();
    std::vector<future<double> > futures;
    futures.reserve(count);

    // start the clock
    high_resolution_timer walltime;
    for (std::uint64_t i = 0; i < count; ++i)
        futures.push_back(async<null_action>(here));
    wait_all(futures);

    // stop the clock
    const double duration = walltime.elapsed();
    print_stats("Actions", "WaitAll", "no-executor", count, duration, csv);
}

// Time async execution using wait each on futures vector
template <typename Executor>
void measure_function_futures_wait_each(
    std::uint64_t count, bool csv, Executor& exec)
{
    std::vector<future<double> > futures;
    futures.reserve(count);

    // start the clock
    high_resolution_timer walltime;
    for (std::uint64_t i = 0; i < count; ++i)
        futures.push_back(async(exec, &null_function));
    wait_each(scratcher(), futures);

    // stop the clock
    const double duration = walltime.elapsed();
    print_stats("async", "WaitEach", ExecName(exec), count, duration, csv);
}

template <typename Executor>
void measure_function_futures_wait_all(
    std::uint64_t count, bool csv, Executor& exec)
{
    std::vector<future<double> > futures;
    futures.reserve(count);

    // start the clock
    high_resolution_timer walltime;
    for (std::uint64_t i = 0; i < count; ++i)
        futures.push_back(async(exec, &null_function));
    wait_all(futures);

    const double duration = walltime.elapsed();
    print_stats("async", "WaitAll", ExecName(exec), count, duration, csv);
}

template <typename Executor>
void measure_function_futures_thread_count(
    std::uint64_t count, bool csv, Executor& exec)
{
    std::vector<future<double> > futures;
    futures.reserve(count);

    std::atomic<std::uint64_t> sanity_check(count);
    auto this_pool = hpx::this_thread::get_pool();

    // start the clock
    high_resolution_timer walltime;
    for (std::uint64_t i = 0; i < count; ++i) {
        hpx::apply(exec,
            [&sanity_check]() {
               null_function();
               sanity_check--;
            }
        );
    }

    // Yield until there is only this and background threads left.
    hpx::util::yield_while(
        [&sanity_check]()
        {
            return (sanity_check > 0);
        });

    // stop the clock
    const double duration = walltime.elapsed();

    if (sanity_check != 0)
    {
        int count = this_pool->get_thread_count_unknown(std::size_t(-1), false);
        throw std::runtime_error(
            "This test is faulty " + std::to_string(count));
    }

    print_stats("apply", "ThreadCount", ExecName(exec), count, duration, csv);
}

template <typename Executor>
void measure_function_futures_limiting_executor(
    std::uint64_t count, bool csv, Executor exec)
{
    using namespace hpx::parallel::execution;
    std::uint64_t const num_threads = hpx::get_num_worker_threads();
    std::uint64_t const tasks = num_threads*2000;
    std::atomic<std::uint64_t> sanity_check(count);

    hpx::util::annotate_function apex_profiler("Outside null_function");
    // start the clock
    high_resolution_timer walltime;
    {
        hpx::threads::executors::limiting_executor<Executor> signal_exec(
            exec, tasks, tasks + 1000);
        for (std::uint64_t i = 0; i < count; ++i) {
            hpx::apply(signal_exec,
     //                  hpx::util::annotate_function("template null_function"),
                [&](){
                    hpx::util::annotate_function apex_profiler("inside null_function");
                    null_function();
                    sanity_check--;
                }
            );
        }
    }

    if (sanity_check!=0) {
        throw std::runtime_error(
            "This test is faulty " + std::to_string(sanity_check));
    }

    // stop the clock
    const double duration = walltime.elapsed();
    print_stats("apply", "limiting-Exec", ExecName(exec), count, duration, csv);
}

template <typename Executor>
void measure_function_futures_sliding_semaphore(
    std::uint64_t count, bool csv, Executor& exec)
{
    std::vector<future<double> > futures;
    futures.reserve(count);

    // start the clock
    high_resolution_timer walltime;
    const int sem_count = 5000;
    hpx::lcos::local::sliding_semaphore sem(sem_count);
    for (std::uint64_t i = 0; i < count; ++i) {
        hpx::async(exec, [i,&sem](){
            null_function();
            sem.signal(i);
        });
        sem.wait(i);
    }
    sem.wait(count);

    // stop the clock
    const double duration = walltime.elapsed();
    print_stats("Apply", "Sliding-Sem", ExecName(exec), count, duration, csv);
}

///////////////////////////////////////////////////////////////////////////////
int hpx_main(variables_map& vm)
{
    {
        num_iterations = vm["delay-iterations"].as<std::uint64_t>();

        const std::uint64_t count = vm["futures"].as<std::uint64_t>();
        bool csv = vm.count("csv") != 0;
        if (HPX_UNLIKELY(0 == count))
            throw std::logic_error("error: count of 0 futures specified\n");
        const int nl = 1;

        hpx::parallel::execution::default_executor def;
        hpx::parallel::execution::parallel_executor par;

        for (int i=0; i<nl; i++) {
            measure_action_futures_wait_each(count, csv);
            measure_action_futures_wait_all(count, csv);
            measure_function_futures_wait_each(count, csv, def);
            measure_function_futures_wait_each(count, csv, par);
            measure_function_futures_wait_all(count, csv, def);
            measure_function_futures_wait_all(count, csv, par);
            measure_function_futures_thread_count(count, csv, def);
            measure_function_futures_thread_count(count, csv, par);
            measure_function_futures_limiting_executor(count, csv, def);
            measure_function_futures_limiting_executor(count, csv, par);
            measure_function_futures_sliding_semaphore(count, csv, def);
        }
    }

    return hpx::finalize();
}

///////////////////////////////////////////////////////////////////////////////
int main(
    int argc
  , char* argv[]
    )
{
    // Configure application-specific options.
    options_description cmdline("usage: " HPX_APPLICATION_STRING " [options]");

    cmdline.add_options()
        ( "futures"
        , value<std::uint64_t>()->default_value(500000)
        , "number of futures to invoke")

        ( "delay-iterations"
        , value<std::uint64_t>()->default_value(0)
        , "number of iterations in the delay loop")

        ( "csv"
        , "output results as csv (format: count,duration)")
        ;

    // Initialize and run HPX.
    return init(cmdline, argc, argv);
}
```

**Comment by biddisco** [comment]
So I had a go at specializing the executor async/apply dispatch to allow a task name to be passed through and then eventually used as the task name instead of parallel_execution::post which would have made things much easier, but it looks like I would have to make a lot of changes to executor API's to add a specialization for the task name in many places and it's a bit nasty/messy with the proliferation of customization points etc.
I'm hoping @khuck gets a moment to look at this. I was hoping to use apex in the course next week, but without task names, it won't be a very interesting demo.

**Comment by biddisco** [comment]
I'm closing this because #4257 addressed the main problem. We have at least a functional wrapper type for apex annotation even if we cannot use the inline RAII approach.

**Comment by biddisco** [comment]
It turns out things are still not quite working correctly. Using the scheduler_priority_check test with some new tweaks, I am creating tasks with a well defined number of invocations
```
Tasks NP  : 1000
Tasks HP  : 500
Launch    : 1
Launch HP : 10
```
when apex generates the OTF - vampir displays 
![Screenshot from 2020-01-08 10-39-26](https://user-images.githubusercontent.com/941548/71967537-cc2ccc00-3203-11ea-9e22-b0fc66c6d9e1.png)
Which is clearly incorrect. The trend appeas to be that for every task that we use the `annotated_function` wrapper, we get two tasks in vampir - _most of the time_.
It does not happen for every single task, but enough of the time that we see approximately double the number of total tasks, and the average time calculations for the tasks in vampir are all wrong.
Looking at this image below, you can see the Launch task is split into two and many of the other tasks that are visible are also split into two. usually the first part of the task is very short and the second part much more like the actual task.
![Screenshot from 2020-01-08 10-47-15](https://user-images.githubusercontent.com/941548/71967949-612fc500-3204-11ea-869a-0991828faf2c.png)

**Comment by hkaiser** [comment]
@biddisco could it be that we missed to pass through the `annotation` during thread creation everywhere? There seems to be at least one spot we forgot to fix: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/lcos/local/futures_factory.hpp#L134.

**Comment by biddisco** [comment]
That is certainly a mistake/bug - but would it not just leave the task "unknown" or default name?
I'll look through all the places and try fixing them to see if the problem goes away.

**Comment by khuck** [comment]
@biddisco @hkaiser That's because of a last-minute change I made in APEX to handle annotated_functions.  Remember, annotated_functions are annotated _AFTER_ the task is started.  So, I stop the timer with the previous name, and start a new timer with the new name.  Currently, when `apex::update_task()` is called, APEX stops the current timer if it exists, and starts a new one.  If you don't want that behavior, I can change it, but the traces won't be accurate then, either.  See https://github.com/khuck/xpress-apex/commit/346c66bd04ca510bf52d4f6d071474babf10ed81 if you want to revert the change and see the effect.

**Comment by khuck** [comment]
@biddisco ...follow up - if you have the option, you should use `annotate_function()` instead

**Comment by biddisco** [comment]
```
            auto f3 = hpx::async(NP_executor,
                hpx::util::annotated_function(
                    [&, np_m]() {
                        np_task_count++;
                        dec_counter dec(count_down);
                        dummy_task("NP task", std::size_t(np_m));
                    },
                    "NP task"));
```
I'm using it like this - it passes the annotation name into the thread creation and there is no reason for the name to be changed after the fact - the name should be correct at the time the task is first instantiated.

**Comment by khuck** [comment]
@biddisco you're right, I got them reversed.  sorry about that.

Try commenting out this line: https://github.com/STEllAR-GROUP/hpx/blob/d1c61defbf279c09af1c3a727b0e4e8bc5bea175/hpx/util/annotated_function.hpp#L140 - that is probably causing the `apex::update_task()` to happen.  Does that help?

**Comment by biddisco** [comment]
that fixes it. I see the correct task counts and no dodgy extra mini-tasks. Thanks

**Comment by hkaiser** [comment]
@biddisco, @khuck ok, makes sense now. Thanks!
