### ISSUE TITLE
Update HPX to work with the latest VC version

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#3570]
## Expected Behavior

HPX should compile using VC

## Actual Behavior

HPX has some issues with internal changes of VC

## Steps to Reproduce the Problem

  1.  git clone VC master
  1.  Compile HPX with VC

## Specifications

  - HPX Version: master
  - Platform (compiler, OS): fedora 28

**Comment by diehlpk** [comment]
@hkaiser This is the bug, we talked about in the meeting this morning.

**Comment by hkaiser** [comment]
@diehlpk Vc master is under heavy development and I think we should stick to the latest released version (V1.4.1, see https://github.com/VcDevel/Vc/releases/tag/1.4.1). Alternatively we could use the V1.4 branch in the main repo. I will make sure HPX compiles ok using this branch.

**Comment by diehlpk** [comment]
@hkaiser Sure, I am fine with 1.4.1. I will add an ticket to octotiger.
