### ISSUE TITLE
Merge openSUSE reproducible patch

### ISSUE THREAD

**Issue by junghans** [STEllAR-GROUP/hpx#3575]
https://bugzilla.novell.com/show_bug.cgi?id=1100677
patch here:
https://build.opensuse.org/request/show/653867

maybe needs an CMake option.

/cc @bmwiedemann

**Comment by hkaiser** [comment]
@diehlpk would you be able to take care of this?

**Comment by diehlpk** [comment]
@hkaiser Yes

**Comment by bmwiedemann** [comment]
btw, there is also similar detection for `rdtsc` but it is available on all CPUs since the first Pentiums (~25y), so I think the cmake logic can be simplified by assuming it is always there.

Oh and it is "openSUSE" - nearly everyone gets the caps wrong.

**Comment by junghans** [comment]
@diehlpk, do have an account on https://build.opensuse.org/, there are more requests coming in: https://build.opensuse.org/request/show/655994

**Comment by diehlpk** [comment]
@junghans No, but sure I can create one.

**Comment by junghans** [comment]
@diehlpk go ahead an let me know your username.

**Comment by diehlpk** [comment]
@junghans my username is diehlpk

**Comment by diehlpk** [comment]
We have the option `HPX_WITH_BUILD_DISTRIBUTION`, which disables the check for rdtscp. This option needs to be to turned on for future releases of HPX packages.

**Comment by sithhell** [comment]
I'm not a fan of merging this particular patch. While I see the issue with cross compilation, rdtscd should just be turned of when building the rpms. Using rdtscd is an optimization, which we shouldn't just throw away.

**Comment by junghans** [comment]
Huh, https://build.opensuse.org/user/show/diehlpk isn't working yet...

**Comment by diehlpk** [comment]
@sithhell This is what we exactlt intent do do, just do not use rdtscp when building deb or rpm packages of hpx.

**Comment by diehlpk** [comment]
> Huh, https://build.opensuse.org/user/show/diehlpk isn't working yet...

it might take some time until my account is activated. I could login and verify my e-mail address at least.

**Comment by junghans** [comment]
Can you branch https://build.opensuse.org/package/show/science:HPC/hpx?

**Comment by diehlpk** [comment]
> Can you branch https://build.opensuse.org/package/show/science:HPC/hpx?

Yes, Could log in and home:diehlpk:branches:science:HPC > hpx

**Comment by junghans** [comment]
On science:HPC/hpx: Added user diehlpk with role maintainer

**Comment by bmwiedemann** [comment]
@sithhell when I played with rdtsc, it was a lot faster than rdtscp (because it does not drain the execution pipeline), so I wonder where the optimization is. Maybe the added cpuid instruction takes some time and also drains the pipeline... but then how often do you call the timestamp / tick_counter / scheduling_loop functions?
