### ISSUE TITLE
Fedora and openSUSE instructions missing on "Distribution Packages" page

### ISSUE THREAD

**Issue by junghans** [STEllAR-GROUP/hpx#3583]
http://stellar.cct.lsu.edu/downloads/distribution-packages/ should include a Fedora section:
```
dnf install hpx
```
and a openSUSE section
```
zypper install hpx
```

Also the gentoo package has been updated in https://github.com/gentoo/gentoo/commit/5c46ec87475d02e0de1f0fd1df85d7e364359959 and the user can install different version using:
```
emerge =hpx-<VERSION>
```
with `0.9.99`, `1.0.0`, `1.1.0`, `1.2.0` and `9999` (master) being available for `VERSION`.

**Comment by diehlpk** [comment]
@aserio Can you please take care of this?

**Comment by msimberg** [comment]
I've just updated the page (stellar-group.org as well).

**Comment by junghans** [comment]
@msimberg, One more nitpick, the `layman -a science` part isn't needed anymore for the master version on Gentoo!

**Comment by msimberg** [comment]
Thanks @junghans for the nitpick! Fixed.
