### ISSUE TITLE
HPX won't compile on POWER8 with Clang 7

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#3587]
## Expected Behavior

I expect HPX to compile

## Actual Behavior

I am getting this error:
```
In file included from /home/users/khuck/src/phylanx/tools/buildbot/src/hpx/tools/cpu_features.cpp:18:
/home/users/khuck/src/phylanx/tools/buildbot/src/hpx/hpx/util/hardware/cpuid.hpp:88:6: error: Unsupported
      platform.
    #error Unsupported platform.
     ^
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1.```cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/home/users/khuck/src/phylanx/tools/buildbot/build-centaur-ppc64le-Linux-clang/boost-1.65.1_avx -DTCMALLOC_ROOT=/usr/local/packages/gperftools/2.5 -DHPX_WITH_MALLOC=tcmalloc -DHWLOC_ROOT= -DCMAKE_INSTALL_PREFIX=. -DHPX_WITH_THREAD_IDLE_RATES=ON -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCEL_COALESCING=OFF -DHPX_WITH_TOOLS=ON -DHPX_WITH_STACKOVERFLOW_DETECTION_DEFAULT=ON -DHWLOC_ROOT=/usr/local/packages/hwloc/1.11.11 -DHPX_WITH_RDTSCP=OFF -DHPX_WITH_DEPRECATION_WARNINGS=Off -DHPX_WITH_MAX_CPU_COUNT=160 /home/users/khuck/src/phylanx/tools/buildbot/src/hpx```
  1.compile
  1.

## Specifications

... Please describe your environment

  - HPX Version: current master
  - Platform (compiler, OS): Clang 7.0.0 with gcc 6.3 on POWER8

**Comment by khuck** [comment]
this was a broken compiler issue.

**Comment by biddisco** [comment]
How did you determine that it was a compiler fault?
