### ISSUE TITLE
include could not find load file: HPX_Utils.cmake

### ISSUE THREAD

**Issue by junghans** [STEllAR-GROUP/hpx#3589]
On Fedora 29:
```bash
dnf install hpx-openmpi-devel
module load mpi/openmpi-x86_64
```

Create a `CMakeLists.txt` with:
```cmake
cmake_minimum_required(3.1)
find_package(HPX)
```
now run:
```bash
cmake .
```

one gets:
``` 
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  cmake_minimum_required called with unknown argument "3.1".


CMake Error at /usr/lib64/openmpi/lib/cmake/HPX/HPXMacros.cmake:8 (include):
  include could not find load file:

    HPX_Utils.cmake
Call Stack (most recent call first):
  /usr/lib64/openmpi/lib/cmake/HPX/HPXConfig.cmake:13 (include)
  CMakeLists.txt:2 (find_package)


CMake Error at /usr/lib64/openmpi/lib/cmake/HPX/HPXMacros.cmake:70 (include):
  include could not find load file:

    HPX_SetupAllocator
Call Stack (most recent call first):
  /usr/lib64/openmpi/lib/cmake/HPX/HPXConfig.cmake:73 (hpx_setup_allocator)
  CMakeLists.txt:2 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/hpx/CMakeFiles/CMakeOutput.log".
```

Looking at `/usr/lib64/openmpi/lib/cmake/HPX/HPXMacros.cmake` it seems the hard-coded `CMAKE_MODULE_PATH` in there is wrong. It is set to `/usr/lib/cmake/HPX` instead of `/usr/lib64/openmpi/lib/cmake/HPX`.

**Comment by junghans** [comment]
I added a fix in https://github.com/STEllAR-GROUP/hpx/pull/3555/commits/c527cf4f9faac332a53ba7abba1c18645db5984b (part of #3555).

**Comment by grantrostig** [comment]
I get a similar, but different error.  
Note that I do have c-lang on my system, but don't get the works check for "c"??
Also I get another earlier error on: HPX_Utils
Here is output:
+++++++++++++++++++++++++++++
[grostig@fx8150-grostig-com build]$ cmake -DCMAKE_PREFIX_PATH=/path/to/hpx/installation ..
-- The CXX compiler identification is GNU 8.2.1
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/lib64/cmake/HPX/HPXMacros.cmake:8 (include):
  include could not find load file:

    HPX_Utils
Call Stack (most recent call first):
  /usr/lib64/cmake/HPX/HPXConfig.cmake:13 (include)
  CMakeLists.txt:3 (find_package)


-- The C compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at /usr/lib64/cmake/HPX/HPXMacros.cmake:70 (include):
  include could not find load file:

    HPX_SetupAllocator
Call Stack (most recent call first):
  /usr/lib64/cmake/HPX/HPXConfig.cmake:73 (hpx_setup_allocator)
  CMakeLists.txt:3 (find_package)


CMake Error at CMakeLists.txt:4 (add_hpx_executable):
  Unknown CMake command "add_hpx_executable".


-- Configuring incomplete, errors occurred!
See also "/home/grostig/src/hpx/helloworld_cmake/build/CMakeFiles/CMakeOutput.log".
+++++++++++++++++++++++++++++++

**Comment by grantrostig** [comment]
@msimberg Note: I'm updating a similar, but different error on this issue.  I'm not sure it should remain closed until my problem is verified.

Also I have attached more detailed log file:
[CMakeOutput.log](https://github.com/STEllAR-GROUP/hpx/files/2842513/CMakeOutput.log)

**Comment by grantrostig** [comment]
Also note that since the other user mentioned a openmpi directory I did install openmpi on my system.  Not sure if that is a required package or not.  It did create that directory, but didn't change my error.

**Comment by msimberg** [comment]
@grantrostig I'm pretty sure you're seeing the same error, and this has been fixed on master. If you don't manage to get past this on master please let us know and we can reopen this.

We're still figuring out what to do with the 1.2.0 package on Fedora which doesn't include the fix on master.

MPI is an optional dependency for HPX (and as far as I know if you install `hpx-openmpi*` packages on Fedora you'll get MPI installed as well). You can ignore MPI for your purposes right now.

**Comment by tdauth** [comment]
Same error on Fedora 29, please add an updated RPM.

**Comment by msimberg** [comment]
@tdauth we're working on a patch release, please stay tuned.
