### ISSUE TITLE
Make share() a rval ref-qualified member function

### ISSUE THREAD

**Issue by Ignition** [STEllAR-GROUP/hpx#3597]
In my opinion, `shared_future<T> future::share()` should be rvalue reference qualified. This would prevent subtle bugs since compilers/static analysers can warn the developer about use after move. This would remove runtime bugs.

Hence the signature should be `shared_future<T> future::share() &&`

This would turn `auto sf = f.share();` into `auto sf = std::move(f).share();` which isn't as clean but safer code.

**Comment by Ignition** [comment]
I know this makes it code quite ugly but also the same applies IMO to `then` and `get`

**Comment by hkaiser** [comment]
@Ignition thanks for this suggestion. Yes, we have discussed this in the past but have decided to go with what was  proposed by the Concurrency TS where `share()` is not ref-qualified. The same applies to `when_all` and friends that consume the futures passed as arguments (even if those are not rvalues).

For now I'd suggest we leave things as is (to avoid breaking code). What do others think?
