### ISSUE TITLE
Missleading error message on power pc for rdtsc and rdtscp

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#3601]
## Expected Behavior

We might should disable this checks for powerpc, because rdtsc ad rdtscp are not available there.

## Actual Behavior

```
-- Performing Test HPX_WITH_RDTSC - Failed
-- Performing Test HPX_WITH_RDTSCP - Failed
-- Neither rdtsc nor rdtscp is available  some performance counters may report incorrect results
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. Run CMake von PowerPC

## Specifications

... Please describe your environment

  - HPX Version: Not important
  - Platform (compiler, OS): Power8

**Comment by hkaiser** [comment]
Could we add some PPC specific implementation of this (see: https://stackoverflow.com/questions/5883124/whats-the-equivalent-of-rdtsc-opcode-for-ppc)? I'm sure people want to see performance measurement results on this platform as well.

**Comment by diehlpk** [comment]
@hkaiser I will have a look into it.

**Comment by hkaiser** [comment]
@diehlpk please see #3649 for a possible fix. 

Also please note that we do already have PPC support for taking timestamps (see: https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/util/hardware/timestamp.hpp#L36-L37). This currently falls back to `clock_gettime`, so it could be improved by using some low-level assembly instead, possibly the ones described here: https://stackoverflow.com/a/53039372/269943:

If you work with gcc use the following:
```
std::uint64_t rdtsc()
{
    std::uint64_t rval;
    __asm__ __volatile__("mfspr %%r3, 268": "=r" (rval));
    return rval;
}
```
For clang:
```
std::uint64_t rdtsc() 
{
    // _mm_lfence();  // optionally wait for earlier insns to retire before reading the clock
    return __builtin_readcyclecounter();
}
```
