### ISSUE TITLE
executor_parameters timeout with gcc <= 7 and Debug mode

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3609]
The `executor_parameters` test times out with gcc version 7 and down (Boost 1.66 and down) in Debug mode. However, I can't reproduce this, so I'm just opening this for the record in case someone else is able to reproduce it. Example failure: http://rostam.cct.lsu.edu/builders/hpx_gcc_5_boost_1_62_centos_x86_64_debug/builds/190.

**Comment by hkaiser** [comment]
@msimberg I think this is a more general problem not (only) related to this particular test. On CircleCI we're seeing occasional hangs with varous tests as well.

**Comment by msimberg** [comment]
I think it's both. There is a more general problem, but if you have a look at buildbot you'll see that `executor_parameters` is definitely problematic. But maybe you're saying that it could be the same underlying cause, and `executor_parameters` just happens to trigger it more reliably?

**Comment by msimberg** [comment]
Closing this since it seems to have been fixed by something in the meantime.
