### ISSUE TITLE
False sharing of scheduling counters

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3612]
Scheduling counters are currently stored by type in vectors for all threads (https://github.com/STEllAR-GROUP/hpx/blob/30706cbf1e390e3d6cd420c2871ddd4982ce11bc/hpx/runtime/threads/detail/scheduled_thread_pool.hpp#L319-L377). This leads to false sharing between threads updating the counters. Especially the idle and busy loop counts are read and written frequently and lead to unnecessary stalls. The counters should instead be stored padded/aligned with all counters for one thread contiguously.

**Comment by hkaiser** [comment]
Excellent catch!

**Comment by msimberg** [comment]
Probably a (small) part of the behaviour in #3452.

**Comment by hkaiser** [comment]
@msimberg the required changes are simple but invasive. I'll try to have a look.
