### ISSUE TITLE
hpx::parallel::transform_reduce with non const reference as lambda parameter

### ISSUE THREAD

**Issue by arkantos493** [STEllAR-GROUP/hpx#3651]
## Expected Behavior

`hpx::parallel::transform_reduce` should compile with non const reference parameter in lambda function as convert operation.

## Actual Behavior

See: [https://stackoverflow.com/questions/54504021/hpx-transform-reduce/54508775#54508775](https://stackoverflow.com/questions/54504021/hpx-transform-reduce/54508775#54508775)
`hpx::parallel::transform_reduce` doesn't compile with the following error message:
```
hpx.cpp: In function ‘int main()’:
hpx.cpp:24:74: error: no matching function for call to ‘transform_reduce(const hpx::parallel::execution::parallel_policy&, std::vector<A>::iterator, std::vector<A>::iterator, double, main()::<lambda(double, double)>, main()::<lambda(A&)>)’
                       [](A& a_ref) -> double { return a_ref.residual(); });

(note:   template argument deduction/substitution failed)
```

## Steps to Reproduce the Problem

```
#include <hpx/hpx_main.hpp>
#include <hpx/hpx.hpp>
#include <hpx/include/parallel_transform_reduce.hpp>
#include <hpx/include/iostreams.hpp>

#include <vector>

class A {
public:
  double residual() const {
    // Calculate actual local residual
    double i = 1.0;
    return i;
  }
};

int main() {

  std::vector<A> vec(300);
  double res = hpx::parallel::transform_reduce(hpx::parallel::execution::par,        
                      vec.begin(), vec.end(),
                      0.,
                      [](double a, double b) -> double { return a + b; },
                      [](A& a_ref) -> double { return a_ref.residual(); });   // (1)

  hpx::cout << "residual: " << res << hpx::endl;

  return 0;
}
```
If you change (1) to 
`[](const A& a_ref) -> double { return a_ref.residual(); }` or
`[](A a_ref) -> double { return a_ref.residual(); }` or
`[](A* a_ref) -> double { return a_ref->residual(); }`
it compiles.

## Specifications

  - HPX Version: 1.2
  - Platform (compiler, OS): Linux MINT 18.3

**Comment by hkaiser** [comment]
N4687 (the last draft of C++17) says in 29.8.5 [transform.reduce]: "Neither unary_op nor binary_op shall invalidate subranges, or modify elements in the range [first, last]." 

I will investigate why it is possible not possible to accept the element by reference, but I'd assume that's to avoid modifying it.

**Comment by arkantos493** [comment]
If you are not allowed to modify the elements why can you pass a normal pointer with compilation error?

**Comment by hkaiser** [comment]
> If you are not allowed to modify the elements why can you pass a normal pointer without compilation error?

@arkantos493: that's a good question that needs investigation. Would it be sensible to allow a reduce operation on a sequence of pointers (their values)? I guess not. 

The answer for now probably would be: we didn't think about plain pointers when implementing the algorithm :/
