### ISSUE TITLE
Exception handling appears to be broken

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#3654]
## Expected Behavior

Running the test suite with address sanitizer correctly

## Actual Behavior

When running tests which make use of exceptions, they fail with a "stack buffer underflow". When disabling these tests, everything is fine.

## Steps to Reproduce the Problem

Run, for example, the `suspend_pool` test with address sanitizer.

**Comment by hkaiser** [comment]
@sithhell was this fixed by #3662?

**Comment by hkaiser** [comment]
@sithhell is this still a problem?
