### ISSUE TITLE
Generate PDF again from documention (with Sphinx)

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3670]
There was a request to have PDF documentation for printing. I'll try to get to this soon.

(I've also closed the previous PDF issue: #332.)

**Comment by grantrostig** [comment]
Much appreciated for those of us who read from paper, not flickering computer screens. :+1:

**Comment by hkaiser** [comment]
> I've also closed the previous PDF issue: #332.

Must have been the oldest still open ticket we've had ...

**Comment by msimberg** [comment]
@grantrostig I've managed to build a PDF of our documentation, albeit with quite a few warnings (and ignored errors). The [output](https://github.com/STEllAR-GROUP/hpx/files/2865193/HPX.pdf) does look reasonable to me though. Does this look useful to you? I'd like to avoid going down the rabbit hole of trying to fix latex build errors unless needed. I'm afraid I'd never come out of it again.

If this looks useful I'd enable it but without any guarantees that it will work in the future. I might also enable building single-page html documentation, and a man page (would anyone use that?). They would essentially come for free.

**Comment by hkaiser** [comment]
@msimberg that looks very nice! single-page html would be great, but I don't think man pages are of any value nowadays.

**Comment by grantrostig** [comment]
@msimberg , I will print and review the content (part of it) in the next few days.  Thank you.

@hkaiser , @msimberg , I _definitely_ want the man pages, both in print on paper sometimes, and via the command line always.

Man pages are the only complete and correct (if not too terse) documentation in a world of failed attempts at alternate documentation systems on the command line.  Man pages has been serving Unix programmers for 20+ years, may they live forever (as a last resort when at the shell prompt. :)

**Comment by msimberg** [comment]
@grantrostig thanks for having a look. Note that the manpages would just be exactly the same content as in the html or pdf documentation. Probably too verbose if anything.

**Comment by grantrostig** [comment]
@msimberg , well the PDF document is very nice and I have found no "formatting" problems at all yet.   But it is not a set of "man pages".

The important "boost" c++ library for instance does not offer man pages for programming libraries.  But the gcc compiler does for its "executable commands", such as the compile "gcc" or "g++".

Perhaps that would be a standard to eventually implement for binaries such as "hpxcc"?  Not a high priority though.

**Comment by msimberg** [comment]
> @msimberg , well the PDF document is very nice and I have found no "formatting" problems at all yet. But it is not a set of "man pages".

No objections there. It's very much a least effort manpage. 

> The important "boost" c++ library for instance does not offer man pages for programming libraries. But the gcc compiler does for its "executable commands", such as the compile "gcc" or "g++".
> 
> Perhaps that would be a standard to eventually implement and create man pages for file formats (if any) and for binaries such as "hpxcc"? Not a high priority though in my opinion.

Yes, that would definitely be nice, but you know how it is with time and priorities. I think this is low priority also for us.
