### ISSUE TITLE
HPX package install documentation has wrong or incomplete package names/info for fedora

### ISSUE THREAD

**Issue by grantrostig** [STEllAR-GROUP/hpx#3675]
## Expected Behavior

http://stellar-group.org/libraries/hpx/downloads/
`

Version | Url/Install Command
-- | --
Version 1.2.0 | dnf install hpx

`
Presumably one could start writing programs having installed this, and only this.  Yes I do see that it technically says "binaries".  Note there is a similar page which someone gave me a link to but I can't now find after 20 minutes of searching github.io docs.

## Actual Behavior

... The above command does not install the headers, which one might assume, the user would want if they are installing the binary packages for the purposes of writing programs.  I suggest that both hpx and hpx-devel be mentioned on both pages that exist somewhere.

## Steps to Reproduce the Problem

go to the webpage

## Specifications

... Please describe your environment

  - HPX Version: 1.2.0
  - Platform (compiler, OS): fedora

**Comment by diehlpk** [comment]
@grantrostig The nice things for open source software, you can contribute. I like to encourage you to do a pull request and show us how to like to have the documentation. It is somehow difficult for me, as the one who generated these packages and has more insights, to document it in such a way a newcomer understands it.

**Comment by grantrostig** [comment]
@diehlpk , do you know where that second page is?  It was mentioned in some HPX chat but I can't find it.

**Comment by diehlpk** [comment]
@grantrostig I updated the documentation and mentioned the three sub packages, how to list all of them, and how to show more details about a specific package. Please let us know if this is sufficient or if you would expect more details on this specific page.

**Comment by grantrostig** [comment]
@diehlpk , Looks good.  I do seem to recall another page mentioning dnf for fedora, but I can't find it.  I wonder if the other distributions would need similar handling.  Anyway I can't verify, so I'd say this is confirmed fixed.

**Comment by msimberg** [comment]
@grantrostig did you perhaps end up on [this](http://stellar.cct.lsu.edu/downloads/distribution-packages/) page? Unfortunately for various reasons we need both of these pages. @diehlpk would you mind adding the same text to that page?

**Comment by grantrostig** [comment]
@msimberg , wow, you are excellent at following up!  Yes, that is it. :)  I'm not sure why I could not find it.

**Comment by grantrostig** [comment]
@msimberg , I investigated why I could not find it and wrote up an issue on the matter here:
https://github.com/STEllAR-GROUP/hpx/issues/3689

**Comment by grantrostig** [comment]
NOT FIXED FULLY
@diehlpk , as it turns out, @msimberg , found the second page where your good edits are also needed.  Can you also make the changes there, or should I create another issue for that page?

Here is the page in question: 
http://stellar.cct.lsu.edu/get-hpx/distribution-packages/

**Comment by diehlpk** [comment]
@grantrostig There is no need for a new ticket, I will update it soon. Right now, fixing the fedora hpx-devel compilation issues has a higher priority.
