### ISSUE TITLE
Incorrect and inconsistent website structure http://stellar.cct.lsu.edu/downloads/

### ISSUE THREAD

**Issue by grantrostig** [STEllAR-GROUP/hpx#3689]
## Expected Behavior

The main navigation bar has links and dropdowns for some of the links.  If one goes to the main link, not one of the dropdown links, then: there should be a page that lists all the links of the dropdown links.  This is the overwhelming convention of websites like this, and in most cases this is done on this HPX website, however not always.  This variance cost me about 1 hour of time searching and failing to find.  Goggle also could not find the page, perhaps another issue.

## Actual Behavior

When you go to http://stellar.cct.lsu.edu/downloads/, it lists the source downloads and _not_ the two or three links that I would expect.

There are three main topics:
1) Released source distributions
2) Github link
3) Packaged distributions.

To be fair the github could be considered in the same category at "Source Downloads", and it is mentioned in the text.  Also the link to the packaged distributions is mentitoned in the text, but I didn't see that notation.

## Steps to Reproduce the Problem

Go to http://stellar.cct.lsu.edu and "hover" over "Downloads"

Then click on the "Downloads" link.

Compare this to the same procedure for "Projects" which works correctly and you will see the large difference.

Also compare this to "Events" which is also broken in a similar, perhaps worse way than "Downloads", because it does give a list of 8 events, but if you go the overview "Events" link, it only shows three of the eight (undeniably an error).

Then there is the "About" link which follows yet another convention.

While the errors/inconsitencies are not earth shaking, I suggest that the website be carefully examined for consistency and clarity of operation.

## Specifications

  - HPX Version: master
  - Platform (compiler, OS): fedora29 firefox

**Comment by aserio** [comment]
I have made a few changes to the cct.lsu.edu website in response to this ticket:

* I have made a new page called "HPX Downloads" this page redirects to the original "Downloads" page. I think this is necessary to preserve links that we currently have to this page while still maintaining the convention mentioned in this ticket.
* I have added a page called "HPX GitHub Repository" which redirects to our GitHub page.
* I have updated the "Events" page to reflect all of the events we have created pages for.
* I have changed the link text from "here" to "GitHub repository" to be more descriptive.

Please let me know if this has addressed your concerns in this ticket.

**Comment by grantrostig** [comment]
@aserio , thank you, yes it is better, but still not "consistent".  You could preserve links and make it consistent by modifying the top menu link and going to a summary of links as is the common practice.

Also, the about page has not been fixed/"made consistent"

Also the fact that "contact us" wraps to the next line is not "attractive" in either firefox or chrome on win10 (and probably linux too) ;)

On the other hand, I guess the website is "good enough".  Depends on how good an impressions the HPX project wants to make.

**Comment by aserio** [comment]
@grantrostig I have made some more changes to make the website more consistent including edits to the "Downloads" Menu and the "About" menu. Do these solve the issues reported by the ticket?

As far as the menu wrapping, I have no idea how to begin to address that issue. I agree that this "attractiveness" issue is not worth the time to fix it.

**Comment by grantrostig** [comment]
@aserio , you slightly/subtly misunderstood me.  Actually I was saying it would be desirable to fix the "contact us" to demonstrate the quality of the HPX project.  "Good enough" means, not very good, but passes anyway.  So the website passes.  That's adequate, but not excellent. ;)

Yes the changes you made do fully address the primary reason for this "issue".  Thank you.  

Who is supposed to close the issue?  Me?

**Comment by aserio** [comment]
I can do it  :)

**Comment by grantrostig** [comment]
Confirmed closed.
