### ISSUE TITLE
C++11 `constexpr` support is now required

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#3696]
By adding:
https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/threads/topology.hpp#L444-L451

we now require C++11 `constexpr` support and should be able to get rid of `HPX_CONSTEXPR`, `HPX_CONSTEXPR_OR_CONST` and `HPX_STATIC_CONSTEXPR` macros.

**Comment by hkaiser** [comment]
Good catch! Should we turn that into a macro (optionally) instead? There is still NVCC having trouble with this, IIRC.

**Comment by sithhell** [comment]
I don't see problems with constexpr on nvcc or cuda-clang

**Comment by msimberg** [comment]
Closing since #4017 was merged.
