### ISSUE TITLE
Add shift_left and shift_right algorithms

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#3706]
P0769 was accepted for C++20 (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0769r2.pdf). This adds the `shift_left` and `shift_right` algorithms. We should implement those as part of our parallel algorithm module (see #1141).

See also for an exemplar (sequential) implementation of those here: https://github.com/danra/shift_proposal.

**Comment by rbyshko** [comment]
We had a communication over the irc today. I'll grab this task. Thanks.

**Comment by tapaswenipathak** [comment]
Hi @hkaiser, @rbyshko: interested in fixing algorithms ticket, can I PR?

**Comment by hkaiser** [comment]
@tapaswenipathak sure, any contributions are welcome! There is no need to ask. Just make sure nobody else is working on things before.

**Comment by stmatengss** [comment]
Hi @hkaiser, I would like to make contributions to implement `shift_left` and `shift_right` algorithms.

**Comment by hkaiser** [comment]
> I would like to make contributions to implement shift_left and shift_right algorithms.

@stmatengss Sure, those are not too difficult, I think. However, those will require some thinking to be parallelized. I'd start with looking at how `rotate` is implemented. These seem to be similar.

**Comment by Shubhupatel** [comment]
Hi @hkaiser, Interested in working on this issue.

**Comment by hkaiser** [comment]
> Hi @hkaiser, Interested in working on this issue.

Perfect, please feel free! See my comment above.

**Comment by Jedi18** [comment]
Should we add range(and sentinel) overloads for these as well?

**Comment by hkaiser** [comment]
> Should we add range(and sentinel) overloads for these as well?

Yep, good idea. See how it's specified for rotate: http://eel.is/c++draft/alg.rotate

**Comment by Jedi18** [comment]
Ok thanks!
