### ISSUE TITLE
interested to contribute to the organisation 

### ISSUE THREAD

**Issue by Yashwanth711** [STEllAR-GROUP/hpx#3717]
Hello Everyone, my name is Yashwanth. I am a third year Undergraduate from IIT Bhubaneswar. I am proficient in C++,Python. I have experience in working  with Machine Learning algorithms. I am planning to apply for GSoc19 with your organisation. I need help to get started .so,please assign me some task/subgoal to start contributing and work along with you.

**Comment by hkaiser** [comment]
This ticket system is not meant to be used for GSoC discussions but for feature requests, bug reports, and pull requests. Please see our [Hints for Successful Proposals](https://github.com/STEllAR-GROUP/hpx/wiki/Hints-for-Successful-Proposals) to get more information about how to discuss GSoC topics and to generally get in contact.
