### ISSUE TITLE
Please make the python executable configurable through cmake

### ISSUE THREAD

**Issue by yurivict** [STEllAR-GROUP/hpx#3718]
On FreeBSD several versions of python can be installed at the same time, with different executable names.

**Comment by hkaiser** [comment]
@yurivict In general, HPX does not require any specific python executable to be built. We only install a python script `hpx_run.py` that can be helpful for running HPX applications. This script should be compatible with any Python version, so I don't think we need to make the Python executable configurable as this script will be used by the user in the end.

**Comment by yurivict** [comment]
But you embed a specific executable name ```python```, and this fails.

**Comment by hkaiser** [comment]
@yurivict Fair enough.

**Comment by msimberg** [comment]
I think we have some old Python 2-style print statements hanging around, but otherwise nothing that would still require Python 2 (AFAIK). This should be a straightforward change if someone feels like having a go at this. And I don't think we need to support Python 2 anymore. It's time to let it go...

**Comment by hkaiser** [comment]
@msimberg it shouldn't be a problem to change the code such it is compatible with any Python version.

**Comment by diehlpk** [comment]
@hkaiser @msimberg pr #3761 provides the changes such that our scripts run with python3 on Fedora 29.

**Comment by msimberg** [comment]
The question is: is there a need for the user to actually change the python executable, or is it enough that it works with both Python 2 and 3 and the user doesn't care which? @yurivict I'm guessing in your case it was actually the latter, and not that you necessarily need to be able to set the Python executable?

**Comment by yurivict** [comment]
> is there a need for the user to actually change the python executable

The package should always work with a specific version of the python executable. Reasons: 1. predictability 2. you might not be able to guess what the executable is.

This is why there should be a configuration variable for it.

**Comment by msimberg** [comment]
@yurivict does #3803 do what you had in mind?

**Comment by msimberg** [comment]
@yurivict I'm closing this now that #3803 has been merged. Please reopen if needed.
