### ISSUE TITLE
pkg-config produces invalid output:  -l-pthread

### ISSUE THREAD

**Issue by yurivict** [STEllAR-GROUP/hpx#3719]
```
$ pkg-config --cflags --libs hpx_application
-std=c++17 -I/usr/local/include -I/usr/local/include/hpx/external -DHPX_APPLICATION_EXPORTS -DHPX_ENABLE_ASSERT_HANDLER -std=c++17 -L/usr/local/lib /usr/local/lib/libhpx_init.a /usr/local/lib/libhpx.so -lrt /usr/local/lib/libboost_context.so /usr/local/lib/libboost_thread.so -l-pthread /usr/local/lib/libboost_chrono.so /usr/local/lib/libboost_atomic.so /usr/local/lib/libboost_filesystem.so /usr/local/lib/libboost_program_options.so /usr/local/lib/libboost_regex.so /usr/local/lib/libboost_system.so /usr/local/lib/libboost_date_time.so /usr/lib/libpthread.so /usr/local/lib/libboost_context.so /usr/local/lib/libboost_thread.so -l-pthread /usr/local/lib/libboost_chrono.so /usr/local/lib/libboost_atomic.so /usr/local/lib/libboost_filesystem.so /usr/local/lib/libboost_program_options.so /usr/local/lib/libboost_regex.so /usr/local/lib/libboost_system.so /usr/local/lib/libboost_date_time.so /usr/local/lib/libhwloc.so 
```

OS: FreeBSD

**Comment by msimberg** [comment]
@yurivict `pkg-config` is working correctly for me on linux, but that's not FreeBSD, so this could be CMake treating flags differently on different platforms. Could you try changing `-pthread` on this line: https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/HPX_SetupBoost.cmake#L80 to either `pthread` or `-lpthread` and see what happens? Considering you have `/usr/lib/libpthread.so` in there as well, I'm guessing this line is working: https://github.com/STEllAR-GROUP/hpx/blob/master/CMakeLists.txt#L1254.

**Comment by msimberg** [comment]
@yurivict would you mind posting your compiler, cmake, and boost versions here as well?

**Comment by yurivict** [comment]
clang-6.0.1
cmake-3.14.1
boost-1.70

**Comment by msimberg** [comment]
Thanks @yurivict. Oddly enough we're getting now `-l-lpthread` on some configurations on rostam as well (http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_64_centos_x86_64_debug/builds/287/steps/build_unit_tests/logs/stdio) after #3629. This needs to be sorted out before the release.
