### ISSUE TITLE
faced a building error 

### ISSUE THREAD

**Issue by Yashwanth711** [STEllAR-GROUP/hpx#3721]
i faced error while building the hpx 

can anyone help.

make[2]: *** [examples/resource_partitioner/CMakeFiles/async_customization.dir/build.make:63: examples/resource_partitioner/CMakeFiles/async_customization.dir/async_customization.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:63035: examples/resource_partitioner/CMakeFiles/async_customization.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

  - HPX Version:latest 
  - Platform (compiler, OS):ubuntu18.04

**Comment by biddisco** [comment]
You have not included the actual error message, but I suspect that you have built the current master branch and there is a known problem with this test. You can ignore it for the time being and try using `make -k ...` where `-k` tells make to ignore errors and continue building the rest.
