### ISSUE TITLE
Unable to debug parcelport on a single node

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#3738]
Working on my laptop, I am getting an empty list of parcelports and concomitant segfaults from my rdma code when it attempts to obtain the rdma memory registration handler from the parcelport.

Could it be that recently a patch was applied that disabled initialization of the parcelport when running on a single node? If that is the case, could someone please point me to the code responsible so that I can temporarily re-enable it for my local build for testing purposes.

**Comment by hkaiser** [comment]
@biddisco just use the command line option `--hpx:expect-connecting-localities` which will have the side effect of not disabling the parcelport.

**Comment by biddisco** [comment]
Thanks. That's just what I needed
