### ISSUE TITLE
"hello_world" distributed job with HPX - Ubuntu 18.04 : how to?

### ISSUE THREAD

**Issue by marcoippolito** [STEllAR-GROUP/hpx#3741]
After git-cloning the latest hpx stable release, building and installing it,
I tested the single-node execution of a simple example:

    marco@pc01:~/CplusplusGoodCodeExamples/hpxExamples/quickstart$ g++ -std=c++17
    fibonacci.cpp -ofibonacci `pkg-config --cflags --libs hpx_application` 
    -lhpx_iostreams -DHPX_APPLICATION_NAME=fibonacci
    marco@pc01:~/CplusplusGoodCodeExamples/hpxExamples/quickstart$ ./fibonacci
    fibonacci(10) == 55
    elapsed time: 0.002001 [s]

    riccardo@riccardo-HP-Laptop-15-da0xxx:~/hpx/examples/quickstart$ g++ 
    -std=c++17  fibonacci.cpp -ofibonacci `pkg-config --cflags --libs    
    hpx_application` -lhpx_iostreams -DHPX_APPLICATION_NAME=fibonacci
    riccardo@riccardo-HP-Laptop-15-da0xxx:~/hpx/examples/quickstart$ ./fibonacci
    fibonacci(10) == 55
    elapsed time: 0.004149 [s]

I'm now trying to run my very first "hello_world" [distributed](https://stellar-group.github.io/hpx/docs/sphinx/latest/html/_downloads/hello_world.cpp) job with HPX between the PC, with Ubuntu 18.04.01 Server Edition, and a laptop, with Ubuntu 18.04.02 Desktop, which are already connected in a micro-cluster-like (mpich is functioning).

I installed in both nodes also slurm-wlm, whose /etc/slurm-llnl/slurm.conf files
I attached here (called them in a discernable way : slurm_pc0.conf, slurm_riccardohp.conf) : [slurm_pc0.conf][1] , [slurm_riccardohp.conf][2]

I've put in a shared directory /mirror:

    riccardo@riccardo-HP-Laptop-15-da0xxx:~$ df -h
    192.168.1.7:/mirror           371G   23G  333G   7% /mirror

the executable hello_world.

Simply executing it in the pc, this is the output:

    marco@pc01:/mirror$ ./hello_world
    hello world from OS-thread 0 on locality 0
    hello world from OS-thread 1 on locality 0
    hello world from OS-thread 3 on locality 0
    hello world from OS-thread 2 on locality 0

Following the indications found here: [hpx-minimal-two-node-example-set-up-StackOverFlow][3],

I run the hello_world in the shared directory 
in pc:

    marco@pc01:/mirror$ ./hello_world --hpx:localities=2 
    --hpx:agas=192.168.1.7:7910 --hpx:hpx=192.168.1.7:7910

but when running in the laptop:

    riccardo@riccardo-HP-Laptop-15-da0xxx:/mirror$ ./hello_world --hpx:agas=192.168.1.7:7910 
    --hpx:hpx=192.168.1.5:7910 --hpx:worker
    ./hello_world: symbol lookup error: ./hello_world: undefined symbol:   
    _ZN3hpx23hpx_check_version_1u_3uE

What am I missing? What am I doing wrong?
Looking forward to your kind help.
Marco

  [1]: https://drive.google.com/open?id=1_PG5942WLRSvVWqEkMY0I2bbdv-yEOec
  [2]: https://drive.google.com/open?id=1wdqOCa-E-6bdl_WE3WCNwaAEfRScrzJf
  [3]: https://stackoverflow.com/questions/35367816/hpx-minimal-two-node-example-set-up

**Comment by hkaiser** [comment]
I'd say you have two version of HPX on your system (Debug/Release?) and you build against one, but try to run using the other.

**Comment by marcoippolito** [comment]
Hi Hartmut,

I wiped out the previous installations both in the pc and in the laptop, and downloaded and installed in both of them [stellar.cct.lsu.edu/files/hpx_1.2.1.zip](url)

Now the "stand-alone-node" - mode seems working:
for the pc:

    marco@pc01:/mirror$ ./hello_world --hpx:localities=2 --hpx:agas=192.168.1.7:7910    
    --hpx:hpx=192.168.1.7:7910
    hello world from OS-thread 0 on locality 0
    hello world from OS-thread 2 on locality 0
    hello world from OS-thread 3 on locality 0
    hello world from OS-thread 1 on locality 0
    hello world from OS-thread 3 on locality 0
    hello world from OS-thread 2 on locality 0
    hello world from OS-thread 1 on locality 0
    hello world from OS-thread 0 on locality 0

and for the laptop:

    riccardo@riccardo-HP-Laptop-15-da0xxx:/mirror$ ./hello_world --hpx:agas=192.168.1.7:7910     
    --hpx:hpx=192.168.1.5:7910 --hpx:worker
    hello world from OS-thread 0 on locality 1
    hello world from OS-thread 1 on locality 1
    hello world from OS-thread 1 on locality 1
    hello world from OS-thread 0 on locality 1

But what are the missing steps needed to make the program print the hello world message out  on every OS-thread on every locality, like in the example [https://stellar-group.github.io/hpx/docs/sphinx/latest/html/examples/hello_world.html](url)    ?
    hello world from OS-thread 1 on locality 0
    hello world from OS-thread 1 on locality 1
    hello world from OS-thread 0 on locality 0
    hello world from OS-thread 0 on locality 1

**Comment by hkaiser** [comment]
> So, it seems that HPX V1.2.1 in laptop and HPX V1.2.1 in the pc are linked in some way, but they execute the hello_world example in "stand-alone" mode: am I correct or wrong?

Not sure of that. The laptop reports 'locality 1', while the pc reports 'locality 0' - this is what I would expect. However I'm surprised that not all of the output ends up on the pc. I also don't understand why both localities print things twice. I will investigate this over the weekend.

**Comment by marcoippolito** [comment]
Could it be a problem of non-correct installation and or configuration of slurm? I'm going to read slurm's docs in order to check if it could be the case

**Comment by hkaiser** [comment]
> Could it be a problem of non-correct installation and or configuration of slurm?

@marcoippolito AFAICS you have not been using SLURM to launch the hello_world application. So I don't think it could be causing issues in this case.

**Comment by marcoippolito** [comment]
@hkaiser May be both localities print things twice because they print the same things independently of each other? How to check if both localities are correctly linked and synchronized?

**Comment by hkaiser** [comment]
@marcoippolito I didn't get back yet as I was not able to reproduce what you're seeing. What do you see if you run hello_world twice on the same node, like:
```
./hello_world --hpx:localities=2 --hpx:node=0 --hpx:threads=1 &
./hello_world --hpx:node=1 --hpx:threads=1 
```
?

**Comment by marcoippolito** [comment]
This is the output in the master-node 'pc':

    marco@pc01:/mirror$ ./hello_world --hpx:localities=2 --hpx:node=0 --hpx:threads=1 & ./hello_world 
    --hpx:node=1 --hpx:threads=1
    [1] 17248
    hello world from OS-thread 0 on locality 1
    hello world from OS-thread 0 on locality 0
    [1]+  Done                    ./hello_world --hpx:localities=2 --hpx:node=0 --hpx:threads=1
    marco@pc01:/mirror$

**Comment by hkaiser** [comment]
@marcoippolito so in this case all is well and as expected. There is internally no difference to running two localities on the same node (using the TCP loopback) and running it on two physical nodes (over the actual network). Therefor, I'm not sure what's wrong in your case :/

**Comment by marcoippolito** [comment]
So... something related to the actual network configuration, or even the physical network itself, that could interfere with the synchronization between pc and laptop?
