### ISSUE TITLE
When compiling undefined reference to `hpx::hpx_check_version_1_2' HPX V1.2.1, Ubuntu 18.04.01 Server Edition

### ISSUE THREAD

**Issue by marcoippolito** [STEllAR-GROUP/hpx#3757]
After almost two weeks of total inactivity with HPX, today I tried to compile, exactly as I did before, the fibonacci example, but unexpectedly I got this error message:

    marco@pc01:~/hpx_1.2.1/examples/quickstart$ g++ -std=c++17 fibonacci.cpp -ofibonacci `pkg-config 
    --cflags --libs hpx_application` -lhpx_iostreams -DHPX_APPLICATION_NAME=fibonacci
    /tmp/cchqp2S2.o: In function `(anonymous namespace)::check_hpx_version()':
    fibonacci.cpp:(.text+0x1a): undefined reference to `hpx::hpx_check_version_1_2'
    collect2: error: ld returned 1 exit status

HPX Version: HPX V1.2.1
Ubuntu 18.04.01 Server Edition
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)

I did the same with the laptop where I installed two weeks ago the same HPX V1.2.1 and which has Ubuntu 18.04.02 Desktop : 

    riccardo@riccardo-HP-Laptop-15-da0xxx:~/hpx_1.2.1/examples/quickstart$ g++ -std=c++17 
    fibonacci.cpp -ofibonacci `pkg-config --cflags --libs hpx_application` -lhpx_iostreams 
    -DHPX_APPLICATION_NAME=fibonacci
    riccardo@riccardo-HP-Laptop-15-da0xxx:~/hpx_1.2.1/examples/quickstart$ ./fibonacci
    fibonacci(10) == 55
    elapsed time: 0.005578 [s]

So there must be something that occured during these two weeks of total inactivity with HPX in the PC with Ubuntu 18.04.01 Server Edition.
What it could be happen? 
Looking forward to your kind help.
Marco

**Comment by hkaiser** [comment]
My suspicion would be that you compile against one version of HPX but run against a different one (perhaps a Debug/Release mismatch, or some stale binaries lying around, etc.)

**Comment by marcoippolito** [comment]
I was going to write that I re-installed again HPX V1.2.1 on the pc with Ubuntu 18.04.01 Server Edition and now it works as before. So thanks for your reply. I close this issue.
