### ISSUE TITLE
dataflow doesn't convert `future<future<T>>` to `future<T>`

### ISSUE THREAD

**Issue by rasolca** [STEllAR-GROUP/hpx#3758]
## Expected Behavior

I expect `dataflow` to return `future<T>` instead of `future<future<T>>` as `.then` does.

## Actual Behavior

`dataflow` doesn't convert `future<future<T>>` to `future<T>`.

## Steps to Reproduce the Problem

The problem can be reproduced compiling this simple example:
```
#include "hpx/hpx.hpp"
#include "hpx/hpx_main.hpp"

auto test(hpx::future<int>&& fut){
  return hpx::make_ready_future(std::make_pair(1,2));
}

int main() {

  hpx::future<int> fut = hpx::make_ready_future(1);

  hpx::split_future(fut.then(test));

  hpx::split_future(hpx::dataflow(test, fut));
  // doesn't work. dataflow returns a hpx::lcos::future<hpx::lcos::future<std::pair<int,int>>>

  hpx::finalize();
  return 0;
}
```

## Specifications

  - HPX Version: tested following commits:
       * e1929422a75aac8b58eed98e4db5479ddf107f8c
       * f2d4615ca1442921de8cc5989c235c86670df46d (current master)
  - Platform (compiler, OS): independent (tested on linux and OSX)

**Comment by hkaiser** [comment]
@rasolca We generally don't do the collapsing of futures returned from the asynchronous providers (`async`, `dataflow` etc.). Instead, we allow for collapsing futures by exposing an (implicit) converting constructor for `hpx::future<hpx::future<T>>` --> `hpx::future<T>`. 

For this reason I'd expect the following to work:
```
#include "hpx/hpx.hpp"
#include "hpx/hpx_main.hpp"

auto test(hpx::future<int>&& fut){
  return hpx::make_ready_future(std::make_pair(1,2));
}

int main() {

  hpx::future<int> fut = hpx::make_ready_future(1);
  hpx::split_future(fut.then(test));

  hpx::future<std::pair<int, int>> f = hpx::dataflow(test, fut);
  hpx::split_future(std::move(f));

  hpx::finalize();
  return 0;
}
```

**Comment by biddisco** [comment]
That works. Thanks @hkaiser - I should have thought of that.

**Comment by hkaiser** [comment]
@biddisco great! I'll close this then, please reopen, if necessary.
