### ISSUE TITLE
Barrier Hangs When Locality Zero not included

### ISSUE THREAD

**Issue by folshost** [STEllAR-GROUP/hpx#3792]
## Expected Behavior

A barrier should register successfully when being executed by localities 1 and 2 (from {0,1,2})

## Actual Behavior

The barrier hangs, apparently on register_lock.

```
//  Copyright (c) 2019 Weile Wei
//  Copyright (c) 2019 Maxwell Reeser
//  Copyright (c) 2019 Hartmut Kaiser
//
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#include <hpx/hpx.hpp>
#include <hpx/hpx_init.hpp>
#include <hpx/include/iostreams.hpp>
#include <hpx/lcos/barrier.hpp>
#include <hpx/runtime/components/component_factory.hpp>

void run_barrier_test(std::vector<size_t> locs)
{
    if (std::find(locs.begin(), locs.end(), hpx::get_locality_id()) == locs.end())
        return;

    std::string barrier_name = 
        "/loc_list/barrier" + std::to_string(locs[0]) + std::to_string(locs[1]);
    hpx::lcos::barrier b(barrier_name, locs.size(), hpx::get_locality_id());
    b.wait();
}

int hpx_main() 
{
    std::cout << "Hello world from locality " << hpx::get_locality_id() << std::endl;
    std::vector<size_t> locs_0{ 0, 1 };
    run_barrier_test(locs_0);
    std::vector<size_t> locs_1{ 0, 2 };
    run_barrier_test(locs_1);
    std::vector<size_t> locs_2{ 1, 2 };
    run_barrier_test(locs_2);
    return hpx::finalize();
}

int main(int argc, char *argv[]) { return hpx::init(argc, argv); }
```

Run the above code in Visual Studio with three localities with command line arguments "--hpx:localities=3 --hpx:node={0-2} --hpx:run-hpx-main --hpx:threads=1" with the appropriate value for --hpx:node specified for each locality. The first two runs of run_barrier_test will complete successfully, while the third will hang.

  - HPX Version: Most recent on github
  - Platform (compiler, OS): running on Windows 64-bit, with vcpkg for libraries, in VS2017

**Comment by folshost** [comment]
@sithhell can you please take a look at this?

**Comment by sithhell** [comment]
Thanks for the testcase, I'll have a look ASAP.

**Comment by sithhell** [comment]
Please see #3794 for a possible solution.

**Comment by folshost** [comment]
Thanks Thomas! This is great, and fixed my problem. Both of your solutions worked perfectly.
