### ISSUE TITLE
local_dataflow_boost_small_vector fails to build with Boost 1.70

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3808]
Build logs from [rostam](http://rostam.cct.lsu.edu/builders/hpx_gcc_8_boost_1_70_centos_x86_64_release/builds/0/steps/build_unit_tests/logs/stdio). I'm guessing this has to do with the default `Allocator` for `small_vector` being `void` in 1.70 (see [here](https://www.boost.org/doc/libs/1_70_0/doc/html/boost/container/small_vector.html)). I'm hoping those more knowledgeable will find the fix trivial...

**Comment by hkaiser** [comment]
How much more incompatible can one make a container? Grrr.

**Comment by msimberg** [comment]
I opened another issue (#3871) to keep track of the actual issue that caused this.
