### ISSUE TITLE
Source groups are not created for files in modules

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#3810]
The new module-oriented cmake scripts do not properly place the files into source groups. This prevents the header files from showing up in the generated VS solution files. The source files are all placed into the same root solution folder. That will greatly reduce usability as eventually most of the files will be placed into the same solution folder...

**Comment by hkaiser** [comment]
@msimberg I really would like to have this fixed before the release.

**Comment by msimberg** [comment]
@hkaiser absolutely. I'll need your help to make sure it's correct though. I'm going to open a PR soon (this weekend) with some consistency changes to the modules and a `config` module. That'll be the last one for the release so that we have enough time to sort out things like this.
