### ISSUE TITLE
HPX_INCLUDE_DIRS contains non-existent directory

### ISSUE THREAD

**Issue by jjwilke** [STEllAR-GROUP/hpx#3817]
Working on Kokkos+HPX. In `HPXConfig.cmake`, the following appears in the list of HPX_INCLUDE_DIRS, but it doesn't actually get installed or created.
````
/Users/jjwilke/Programs/install/hpx/include/hpx/external
````
from
````
set(HPX_INCLUDE_DIRS "/Users/jjwilke/Programs/install/hpx/include;/Users/jjwilke/Programs/install/hpx/include/hpx/external;/opt/local/include;/Users/jjwilke/Programs/spack/opt/spack/darwin-highsierra-x86_64/clang-10.0.0-apple/hwloc-2.0.2-jwtizf4qjcn7gh2p2eho5vbrldqg6mbj/include")
````
This actually doesn't cause errors (well, warnings) until I build a kokkos-dependent project. 
````
  Imported target "kokkos" includes non-existent path

    "/Users/jjwilke/Programs/install/hpx/include/hpx/external"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
````
Configure still succeeds, but it would be better not to have the warning

**Comment by msimberg** [comment]
Thanks for the report! The external directory is only installed for Xeon Phi, but the list of include directories always contain it. We should easily be able to conditionally excludeit from the list.

**Comment by jjwilke** [comment]
Okay, I sort of lied. Configure succeeds, but the build fails. CMake quits adding include directories when it encounters a bad directory (apparently). This causes kokkos-dependent builds to fail because only a subset of the directories get added.  Pretty strange behavior from cmake, actually.
