### ISSUE TITLE
Build error with msvc 19 caused by SFINAE and C++17

### ISSUE THREAD

**Issue by zeFresk** [STEllAR-GROUP/hpx#3841]
## Expected Behavior

Simple compilation

## Actual Behavior

I'm getting build errors with the latest version of msvc.
The errors are linked to SFINAE and the message is the following :

> C:\vcpkg\buildtrees\hpx\src\1.2.1-e94e8e19db\hpx\util\detail\pack_traversal_async_impl.hpp(448): error C2955: 'hpx::util::always_void': use of class template requires template argument list
C:\vcpkg\buildtrees\hpx\src\1.2.1-e94e8e19db\hpx\util\always_void.hpp(13): note: see declaration of 'hpx::util::always_void'

## Steps to Reproduce the Problem

Download Visual Studio 2019. Install Boost 1.69, hwloc 1.11

  1. Download Visual Studio 2019
  2. Install Boost 1.69 and hwloc 1.11
  3. Try compiling hpx 

I think this is due to decltype using a pointer to a temporary value as a parameter but I don't know how to fix it without breaking SFINAE.

## Specifications

  - HPX Version: 1.2.1
  - Platform (compiler, OS): MSVC 19, Windows 10
  - I'm using vcpkg but I tried compiling everything by myself before, same problem and errors.

**Comment by hkaiser** [comment]
This looks like a MSVC bug to me :/ We'll have to find a workaround....

**Comment by msimberg** [comment]
@zeFresk this should be fixed in latest master by (#3764). Would you be able to try that out? We're also just in the process of releasing 1.3.0 which will include that fix. That should be out in a few weeks.

**Comment by zeFresk** [comment]
I tried a lot of things by myself but none of them worked :(
Looking further on SO I found out msvc was known for having trouble dealing with decltype + variadic templates...
Do you think a workaround is possible or should I wait for Microsoft to fix this bug ?

**Comment by zeFresk** [comment]
@msimberg patch is working. I built the debug variant successfully and the release one is on the way.
Thank you very much for responding that quickly !

**Comment by msimberg** [comment]
@zeFresk great to hear!

**Comment by hkaiser** [comment]
@zeFresk Things compile for me on HPX top of master. Could you please try again using the current version?
