### ISSUE TITLE
Remove lva member from thread_init_data

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3848]
Currently `thread_init_data` contains a `hpx::naming::address_type` member. It's as far as I can see always set to 0 and unused in the schedulers on top of that. I'd like to remove it as it creates an unnecessary dependency on the naming header in the schedulers. The `topology` class also takes an `address_type` as an argument in one function, where `void*` would probably do just as well.

So, before I remove it, what was the original intention of the `lva` member and `HPX_WITH_THREAD_TARGET_ADDRESS`? It seems like whatever it was meant to do could be done with one or more of these:
1. Use the scheduling hints that we now have in place.
2. Replace the use of `address_type` with `void *`.
3. Define a local address type somewhere close to the `topology` class.

**Comment by hkaiser** [comment]
IIRC, the original intention was a) to be able to make scheduling decisions based on the target address of the operation, and b) to be able to extract the function name from its address (e.g. in APEX) using debugging information as a postprocessing step. Both uses have apparently been superseded by other means. Thus, I don't see a reason not to remove this now. We can always add it back if needed.

Alternatively we could turn that into a `void*` or a `size_t`.

**Comment by msimberg** [comment]
Thanks. I think the use case makes sense, but let's add it back when it's clear how to do it (and that it will be used).

**Comment by msimberg** [comment]
This has already been removed during modularization.
