### ISSUE TITLE
Selected processor does not support 'yield' in ARM mode

### ISSUE THREAD

**Issue by doraemon96** [STEllAR-GROUP/hpx#3861]
## Explanation
Trying to `make` hpx for my Raspberry Pi 3b+ (ARMv7l) it throws an error of:
`/tmp/ccplVcGc.s:1123 : Error: selected processor does not support 'yield' in ARM mode`

## Build info

_DEVICE =>_ Raspberry Pi 3b+ with ARMv7l 
_OS >=_ Running Raspbian 9 (Stretch)
_COMPILERS_ => gcc/g++/c++ version 6.3.0 , cmake version 3.7.2
_DEPENDENCIES =>_
Hpx downloaded from git (checkout 1.2.1)
Boost libraries (built from source) version 1.69.0
Hwloc libraries (from aptitude repository)
_CMAKE COMMAND =>_ (tried lots of combinations) `cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/home/pi/boost_1_69_0 -DHPX_WITH_CXX11=ON -DHPX_WITH_MALLOC=jemalloc ../hpx`

## Already tried
-DCMAKE_CROSSCOMPILING -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DHPX_WITH_GENERIC_COROUTINES=ON
(following [the cmake toolchain example for crosscompilation](https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/toolchains/ARM-gcc.cmake))

## Extra info
I believe the error could be located in [the HPX_SMT_PAUSE definition for ARM](https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/config/compiler_fence.hpp#L36) directive, and maybe a solution could be found in [this boost issue](https://github.com/boostorg/fiber/issues/110) but I'm currently unavailable to fix it.

**Comment by msimberg** [comment]
@diehlpk @biddisco did either of you ever bump into something like this?

**Comment by biddisco** [comment]
I had a look at the fiber implementation and we can certainly copy that. I haven't had that problem, but I've not tested the pi3 for some time, so I'd need to have a look when I get home. My x-Compile tool chain is certainly not working without some maintenance as I've not touched it in ages.

**Comment by doraemon96** [comment]
I will try to build 1.3.0-rc1 this weekend as maybe this merge: <https://github.com/STEllAR-GROUP/hpx/pull/3591> can solve some problems. Also upgrading cmake to 3.14.4 (because before 3.12 it cannot detect boost_context well). Will keep you updated

**Comment by biddisco** [comment]
Did anything come of this? has anyone tested on Raspberry Pi recently. I have a pi 4 at home and might try a build, but need to setup a toolchain for it (which might be a job for the christmas break).

**Comment by x86r** [comment]
For future folks viewing - try below. Solved the same error for me on another project: 
`export CXXFLAG="-march=native -mcpu=native"`

**Comment by x37v** [comment]
> CXXFLAG="-march=native -mcpu=native"

shouldn't it be `CXXFLAGS` plural?
