### ISSUE TITLE
GSOD Applicant 2019

### ISSUE THREAD

**Issue by Dhiraj240** [STEllAR-GROUP/hpx#3881]
@parsa @msimberg If I am not wrong you both are the mentors for the project "Write tutorials based on existing tutorials presentation material".
I am interested in the project for adding the [tutorials](https://github.com/STEllAR-GROUP/tutorials/tree/master/cscs2017) in the HPX documentation.

Since last 1 year, I am contributing to open source and following are the things I would like to share:
1. Appointed as a mentor for [Google Summer of Code 2019](https://summerofcode.withgoogle.com/organizations/5544218626359296/?sp-page=2#6027575485267968).
2. Appointed as [Google Code-In 2018 mentor](https://drive.google.com/file/d/0B2RtT3skwlZraDRjSzdmUDJBV2xPY3BrcDBhY29oWnRVVkpB/view?usp=sharing) for coala organisation where I had reviewed and contributed code in python.
3. Part of [coala developers group](https://github.com/orgs/coala/teams/coala-developers/members?utf8=%E2%9C%93&query=dhiraj240).
4. Part of [Public Lab mentors group](https://github.com/orgs/publiclab/teams/mentors/members?utf8=%E2%9C%93&query=dhiraj) and [Soc mentors group](https://github.com/orgs/publiclab/teams/soc/members?utf8=%E2%9C%93&query=dhiraj).
You can check my GitHub profile for more opensource contribution related things.
Now, talking about the project should I directly start sending PRs for this project from now by opening relevant issues? 
Also, I would like to work on current development issues to get familiar with the code base and do documentation side by side.
Is it necessary to ask before working on existing issues and also for the recent ones which I am going to open?
Can you share any communication channel for the project discussion? or can we talk about this issue as the discussion area?
I have started working on proposal too.

**Comment by Dhiraj240** [comment]
@hkaiser Sir, can you provide the answers for this?

**Comment by hkaiser** [comment]
@Dhiraj240 you can find various possible ways to communicate with the team here: https://github.com/STEllAR-GROUP/hpx/blob/master/.github/SUPPORT.md.

> Now, talking about the project should I directly start sending PRs for this project from now by opening relevant issues?

If you address a ticket it might be advisable to leave a note on it that you are planning to work on it. Otherwise, if you know what you would like to change, create a PR and let us discuss things there. You don't need to ask for permission, this is an open source project. Everybody interested is welcome to contribute.

**Comment by Dhiraj240** [comment]
@parsa 
@msimberg I had applied for GSoD yesterday and apologizes for a late submission. I had initial development here https://github.com/Dhiraj240/hpx_example May I know what all is needed from your side? Also i used my gmail id as dhiraj.8.sharma@gmail.com
Please look at my recent [blog](https://medium.com/beatbluewhalechallenge/iot-to-help-patients-with-alzheimers-and-dementia-c72385f9b286)

**Comment by diehlpk** [comment]
@Dhiraj240 Google will review all applications and decides who can participate the program. So there is nothing needed from our side right now.

**Comment by hkaiser** [comment]
Closing this as the decision for a GSoD student for HPX has been made.
