### ISSUE TITLE
Assertion failure in set_thread_state.hpp line 219

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#3884]
## Expected Behavior

Expect Octo-Tiger rotating_star test problem to run without crashing

## Actual Behavior

During the initial grid setup Octo-Tiger crashes with an assertion failure on line 219 of set_thread_state.hpp

## Steps to Reproduce the Problem

Run the rotating_star test problem of Octo-Tiger on one locality. Most of the time the output ends on a seg fault without the actual assertion failure message printing.

## Specifications

HPX: Debug build of 2d244e1e27c6e014189a6cd59c474643b31fad4b
Octo-Tiger: Debug build of  187d2ab44e3888a5d141967b72ccf6c21b3fca1a
Ubuntu 18.04
GCC 7.3
Boost 1.65.1
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by hkaiser** [comment]
@dmarce1 could you please post the generated error message?

**Comment by dmarce1** [comment]
update- I'm unable to reproduce it on my work machine.

**Comment by hkaiser** [comment]
@dmarce1 I know we have seen this on CircleCI before. Any clue on how to reproduce this would be much appreciated.
