### ISSUE TITLE
hpx.ini not working

### ISSUE THREAD

**Issue by McKillroy** [STEllAR-GROUP/hpx#3890]
## Expected Behavior
Loading my setting from hpx.ini

## Actual Behavior

Ignoring the settings or - if forced to load hpx.ini with 
--hpx:ini=hpx.ini
crashing in the MSVC runtime with a call to abort()

## Steps to Reproduce the Problem

1. Debug build of my app
2. hpx.ini like this:

```
[hpx.logging]
# level = ${HPX_LOGLEVEL:0} ## uses HPX_LOGLEVEL env var and defaults to 0
# level = ${HPX_LOGLEVEL:4} ## uses HPX_LOGLEVEL env var and defaults to 0
level = 4
#destination = ${HPX_LOGDESTINATION:console}
destination = file(hpx.log)
#destination = file(hpx.log)
format = ${HPX_LOGFORMAT:(T%locality%/%hpxthread%.%hpxphase%/%hpxcomponent%) P%parentloc%/%hpxparent%.%hpxparentphase% %time%($hh:$mm.$ss.$mili) [%idx%]|\\n}

```

3a. starting the app = no logging
3b. starting the app with --hpx:ini=hpx.ini causing a call to abort() in the runtime
"Debug Error!
Program: ....
abort() has been called
etc. yadda yadda

Please describe your environment
Windows 10, MSVC 2017
- HPX Version: 1.3.0

**Comment by McKillroy** [comment]
Addendum: seems I had a syntax error with using 
--hpx:ini=hpx.ini 
instead of 
--hpx:config=hpx.ini 
however - isn't hpx supposed to read the ini automagically in the first place? 
Thanks hkaiser for the fix of my command line error.

Still - I leave the issue open for 2 reasons:

1. Command line errors should report why they want to crash instead of just exploding, like "unknown option" or sth.
2. Why isn't the app reading hpx.ini automatically? I guess that's supposed to be the default.

**Comment by hkaiser** [comment]
@McKillroy `--hpx:ini=<...>` interprets its argument verbatim as a configuration entry, `--hpx:config=<...>` interprets its argument as a file name assuming the file contains one or more configuration settings. The former should not make HPX crash on an invalid argument, however. This needs fixing.

**Comment by McKillroy** [comment]
I made another test today and looked deeper into the documentation. 
It seems I was misreading something: The file to be read automagically in the apps working directory is .hpx.ini and not hpx.ini
Renaming my config from hpx.ini to .hpx.ini  made it work and load the logging parameters as expected and hpx.log was finally created.
Dots are so tiny and easy to overlook ;) . . .
So - of my 2 reasons above only one remains.
I could also crash the app by starting it with --hpx:config instead of --hpx:config=hpx.ini - it seems as if there might be a general problem with the handling of bogus command line parameters.

**Comment by hkaiser** [comment]
@McKillroy please see #3900, that should fix the issues you reported.

**Comment by McKillroy** [comment]
Works all nicely now - thanks a lot ! :)
