### ISSUE TITLE
GSoD'19 Applicant

### ISSUE THREAD

**Issue by tapaswenipathak** [STEllAR-GROUP/hpx#3896]
Hi folks,

I am GSoD'19 applicant. I fixed few GSoD'19 tasks, I was suggested that I should read the existing documentation and suggest fixes. I then worked on fixing tickets labelled as docs https://github.com/STEllAR-GROUP/hpx/labels/category%3A%20documentation.

PR's and tickets that I worked on closing-

- https://github.com/STEllAR-GROUP/hpx/issues/3002
- https://github.com/STEllAR-GROUP/hpx/issues/2140
- https://github.com/STEllAR-GROUP/hpx/pull/3887
- https://github.com/STEllAR-GROUP/hpx/pull/3886
- https://github.com/STEllAR-GROUP/hpx/pull/3885
- https://github.com/STEllAR-GROUP/hpx/pull/3882
- https://github.com/STEllAR-GROUP/hpx/pull/3855
- https://github.com/STEllAR-GROUP/hpx/pull/3854
- https://github.com/STEllAR-GROUP/hpx/pull/3853 
- https://github.com/STEllAR-GROUP/hpx/issues/2590

I will be using this ticket in the application. Please let me know if you have any more suggestions and I can add fixes. Thanks, Tapasweni.

**Comment by hkaiser** [comment]
Closing this as the decision for a GSoD student for HPX has been made.
