### ISSUE TITLE
I recommend publishing a version that does not depend on the boost library

### ISSUE THREAD

**Issue by libaineu2004** [STEllAR-GROUP/hpx#3912]
## Expected Behavior

Hpx is a good project but boost library is a part of huge framework which is too hard to use partially.I recommend publishing a version that does not depend on the boost library.

In this way, Hpx will be more advantageous and attractive.

Thank you！

**Comment by hkaiser** [comment]
@libaineu2004 This is the general direction we are working in: at least removing link-time dependencies on Boost. The task however is not a small one and requires a lot of effort. Would you be interested in helping with this?

**Comment by kshitij12345** [comment]
@hkaiser I would be interested in helping. However would need some guidance for the same.

Thank You.

**Comment by hkaiser** [comment]
@kshitij12345 Great! @K-ballo has a list of Boost headers #included throughout HPX (you could regenerate that yourself easily, however). That should give you an idea what Boost library is used where and how often. Then it's up to you to decide which one you'd like to work on replacing... You might want to join our IRC channel to directly discuss things (see here for details: https://github.com/STEllAR-GROUP/hpx/blob/master/.github/SUPPORT.md)

**Comment by K-ballo** [comment]
> @K-ballo has a list of Boost headers #included throughout HPX

A couple months old: https://gist.github.com/K-ballo/7b551d71487bdf34d0b25aa034e399a5

**Comment by kshitij12345** [comment]
Thank You for the fast response. 
Will join the IRC channel and try to get started by this weekend.

**Comment by msimberg** [comment]
I suggest we keep the discussion in #3440.
