### ISSUE TITLE
HPX compiler match too strict?

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#3935]
## Expected Behavior

Do we really need the compiler to match as precise as we check? Would it be sufficient to just check for the major version? So HPX compiled with gcc 9.0.1 and the application compiled with 9.0.2 or 9.1.1 should be fine? 

## Actual Behavior
```

CMake Error at /usr/lib64/cmake/HPX/HPX_Message.cmake:43 (message):
  ERROR: Compilers do not match.  In order to compile HPX application it is
  recommended to use the same compiler as you did for HPX.
  HPX_CXX_COMPILER=/usr/bin/c++, CMAKE_CXX_COMPILER=/usr/bin/c++.
  HPX_CXX_COMPILER_ID=GNU, CMAKE_CXX_COMPILER_ID=GNU.
  HPX_CXX_COMPILER_VERSION=9.0.1, CMAKE_CXX_COMPILER_VERSION=9.1.1.  To
  disable this message set HPX_IGNORE_COMPILER_COMPATIBILITY to On.
Call Stack (most recent call first):
  /usr/lib64/cmake/HPX/HPXMacros.cmake:30 (hpx_error)
  /usr/lib64/cmake/HPX/HPXConfig.cmake:67 (hpx_check_compiler_compatibility)
  CMakeLists.txt:20 (find_package)
```

**Comment by hkaiser** [comment]
We decided to go for the strict match to be sure the user is aware of any differences. As the message suggests you can always confirm to have read the message by explicitly setting `HPX_IGNORE_COMPILER_COMPATIBILITY=On` while invoking cmake.

**Comment by diehlpk** [comment]
Ok, so I have to add `HPX_IGNORE_COMPILER_COMPATIBILITY=On` to the Fedora package, since they update their compilers and do not recompile all packages if it is just a minor update. It is the second time that the Fedora hpx package shows this error message.

**Comment by hkaiser** [comment]
@diehlpk: Let's change our code such that we can disable a full check from inside HPX's build-system (no user settings needed). I'd rather leave what we have by default, however. This would allow for you to set some flag in the Fedora rpm that would disable a full version check whenever somebody uses HPX.

**Comment by diehlpk** [comment]
We have the option `HPX_WITH_BUILD_DISTRIBUTION` already and I will add a check to the compiler flag using this flag.
