### ISSUE TITLE
CMake error for APEX install target

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#3941]
## Expected Behavior

cmake to complete without error code

## Actual Behavior

cmake returns an install target error:
```bash
-- Configuring done
CMake Error: install(EXPORT "HPXTargets" ...) includes target "apex" which requires target "hpx_cache" that is not in the export set.
-- Generating done
```
see http://ktau.nic.uoregon.edu:8020/#/builders/7/builds/302

## Steps to Reproduce the Problem

  1. `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBOOST_ROOT=/home/users/khuck/src/hpx/boost_delphi_1.65.1 -DTCMALLOC_ROOT=/usr/local/packages/gperftools/git-gcc7 -DHPX_WITH_MALLOC=tcmalloc -DCMAKE_INSTALL_PREFIX=. -DHPX_WITH_THREAD_IDLE_RATES=OFF -DHPX_WITH_PARCELPORT_MPI=OFF -DHPX_WITH_PARCEL_COALESCING=OFF -DHPX_WITH_TOOLS=OFF -DHPX_WITH_STACKOVERFLOW_DETECTION_DEFAULT=OFF -DHPX_WITH_APEX=TRUE -DAPEX_WITH_ACTIVEHARMONY=FALSE -DAPEX_WITH_OTF2=FALSE -DAPEX_WITH_PAPI=FALSE -DHPX_WITH_APEX_NO_UPDATE=TRUE -DHPX_WITH_APEX_TAG=develop -DBFD_ROOT=/usr/local/packages/binutils/2.27 -DAPEX_WITH_BFD=TRUE -DHPX_WITH_MAX_CPU_COUNT=72 /home/users/khuck/src/hpx`

## Specifications

... Please describe your environment

  - HPX Version:  current master
  - Platform (compiler, OS):  linux, gcc 7.1, cmake 3.9.3

**Comment by hkaiser** [comment]
@khuck please see #3942 for a possible fix. Please verify.

**Comment by khuck** [comment]
Yes, this fixes it.  I updated APEX and updated the version tag for v2.1.4.
