### ISSUE TITLE
Require C++14

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3944]
Officially all our supported compilers have full C++14 support. The open question has always been `nvcc`, particularly on Windows. Could those who use Windows and/or `nvcc` let me know if there have been any corner cases where you've been forced to go down to C++11 because C++14 wasn't fully supported.

HPX also doesn't currently compile in C++11 mode (https://cdash.cscs.ch/viewBuildError.php?buildid=56536). I take the blame for that because the CI wasn't running properly. Nevertheless, I think it's time to require C++14 because it's clearly something people already want to use (see the errors above, and @biddisco's eagerness to use newer features in the guided executor). We'd also be able to drop a big bunch of feature checks from the CMake configuration.

Related: #3696.

**Comment by hkaiser** [comment]
@msimberg not to throw a stick into your wheel, but we just managed to convince our FLeCSI people not to use gcc 4.8 for their testing environment anymore …

Also, the above error is clearly my fault, I will provide a fix for this asap.

**Comment by msimberg** [comment]
Argh, I know this is going to be a tough one. How much closer to the present did you manage to get them?

**Comment by hkaiser** [comment]
> How much closer to the present did you manage to get them?

We should be fine now in any case, I think.
