### ISSUE TITLE
Improving Documentation 

### ISSUE THREAD

**Issue by McKillroy** [STEllAR-GROUP/hpx#4016]
Since I was asked in IRC to do so, here are three attempts of mine to document some basic recipes:

https://gitlab.com/snippets/1821389
https://gitlab.com/snippets/1822983
https://gitlab.com/snippets/1828131

Maybe they are helpful for people working on HPX Documentation.
Cheers
~Chris

**Comment by McKillroy** [comment]
Since the bot marked it as "stale":

Basically this is ~sortof deprecated by the following attempt of mine to create some additional documentation outside of this repo that may be used later:
https://github.com/McKillroy/hpx_snippets
It's rendered here:
https://mckillroy.github.io/hpx_snippets/
The snippets mentioned above are in "Section 6 : A collection of HPX Recipes, HowTos and Drafts" of that repo
Use at will ...

**Comment by msimberg** [comment]
@McKillroy would you be happy with us linking to your GitHub pages in the additional material section in our docs: https://hpx-docs.stellar-group.org/latest/html/additional_material.html?

**Comment by McKillroy** [comment]
@msimberg No problem with that, but I am not sure the quality is sufficient - it also might be outdated.
