### ISSUE TITLE
Simple hello world fails to launch correctly

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/hpx#4032]
## Expected Behavior

From this example code:

```
#include <hpx/hpx_init.hpp>
int hpx_main(int argc, char* argv[]) {
	printf( "Hello World!\n");
	return hpx::finalize();
}
int main(int argc, char* argv[]) {
	hpx::init(argc, argv);
}
```

I expect there to be one instance of hpx_main called and the output to be:
```
Hello World!
```
## Actual Behavior

When run with mpirun -np 2, the output is 
```
Hello World!
Hello World!
```
## Steps to Reproduce the Problem

I compiled the above code using cmake file:
```
project(hello CXX)
find_package(HPX REQUIRED NO_CMAKE_PACKAGE_REGISTRY)

add_hpx_executable(
  hello
  DEPENDENCIES
  SOURCES
    main.cpp
)
```

and executed it with mpirun -np 2 ./hello

## Specifications

... Please describe your environment

  - HPX Version: Top of master
  - Platform (compiler, OS): GNU 8.2 Ubuntu 18.04

**Comment by hkaiser** [comment]
@dmarce1 Was HPX built with MPI enabled?

**Comment by dmarce1** [comment]
Yes

**Comment by hkaiser** [comment]
Please see #4035 for a possible solution and let us know if this fixes your issue.

**Comment by dmarce1** [comment]
This fixes it. Thanks.
