### ISSUE TITLE
segmented containers: remote segment access

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/hpx#4033]
## Expected Behavior

For a segmented container distributed across multiple locales, I would like to access a full segment of data hosted on a remote locale. This would enable the ability to efficiently implement distributed sorting and counting algorithms (bitonic, etc). [reference](http://ac.informatik.uni-freiburg.de/teaching/ss_13/netalg/lectures/chapter4.pdf)

## Actual Behavior

Feature does not currently exist.

## Steps to Reproduce the Problem

N/A

## Specifications

N/A

**Comment by msimberg** [comment]
Without knowing too much about our distributed containers or your needs, I thought our coarrays give you access to remote segments. Have you had a look at them? https://stellar-group.github.io/hpx/docs/sphinx/branches/master/html/manual/writing_distributed_hpx_applications.html?highlight=coarray#c-co-arrays

**Comment by ct-clmsn** [comment]
@msimberg do hpx::coarrays require an spmd block or could I use them in a non-spmd program? My goal is to implement a couple of distributed sorting algorithms over hpx::partitioned_vectors; if the coarrays provide segmented access, then I'll switch to a coarray implementation.

**Comment by hkaiser** [comment]
@ct-clmsn: FWIW, here is a paper describing the coarray implementation: https://dl.acm.org/citation.cfm?doid=2935323.2935332. And yes, coarrays can/should be used in an SPMD context.

**Comment by tapaswenipathak** [comment]
Hi folks: Can I PR or is the ticket for internal folks?

**Comment by ct-clmsn** [comment]
@hkaiser Thank you! I'll review it ASAP. @msimberg The immediate utility for this feature would be implementing distributed sorting algorithms. @tapaswenipathak if you can implement this feature, that would be awesome.
