### ISSUE TITLE
Deprecate hpxcxx compiler wrapper

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4048]
Opening this to see what the opinion is on the wrapper script `hpxcxx`. In my opinion compiler wrappers like these add little convenience but add magic and annoying-to-debug errors. I can see how others might feel the opposite way.

@stevenrbrandt @sithhell @Finomnis (since you've contributed to the script).

**Comment by sithhell** [comment]
I have no hard feelings removing it.

**Comment by stevenrbrandt** [comment]
I do object. I use it fairly regularly since I'm not good with cmake. When I created it, I designed it to print out exactly what it was doing to make it "less magic."

**Comment by Finomnis** [comment]
I wasn't really involved, my name is just there because I touched it during bugfixing, and I didnt work on hpx since 5 years. Nonetheless, my opinion is that if hpx has good CMake integration, a script like this shouldnt be necessary.

**Comment by msimberg** [comment]
@stevenrbrandt thanks for the input! That's exactly what I was looking for. I'll gently ask: is this something you think is essential to have in the HPX repo (as opposed to something you would keep track of yourself)? If *no-one* had said they find it useful I would've gone ahead and deprecated it, but since you do find it useful I'm not going to push this much further (I'll happily close this without further action).

**Comment by hkaiser** [comment]
We should add some documentation if the script should stay in the distribution. 
@stevenrbrandt: would you be willing to create some?

**Comment by stevenrbrandt** [comment]
I would.

**Comment by msimberg** [comment]
I've opened an issue for documenting `hpxcxx` instead: #4063.
