### ISSUE TITLE
Document hpxcxx compiler wrapper

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4063]

**Comment by MukundVaradarajan** [comment]
I would like to work on this issue, is it still open? can someone please locate the corresponding wrapper/script?

**Comment by hkaiser** [comment]
@MukundVaradarajan That's definitely available, still. Thanks!

**Comment by msimberg** [comment]
This is the corresponding script: https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/templates/hpxcxx.in, and it could do with at least a mention somewhere in the documentation.

**Comment by MukundVaradarajan** [comment]
Correct me if I am wrong, this is for building a hpx application/component using hpxcxx command. Bear with me as I am new to this, how does "@<value>@" work in the script? (eg: "@CMAKE_CXX_COMPILER@")

**Comment by MukundVaradarajan** [comment]
It would be really great if I could get a headstart on this script and where it fits...

**Comment by hkaiser** [comment]
Things like `@CMAKE_CXX_COMPILER@` are replaced during configuration of the project (by cmake) with the correspondingly named cmake variable. For hpxcxx this happens here: 
- https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/HPX_GeneratePackage.cmake#L56-L58
- https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/HPX_GeneratePackage.cmake#L64-L66

(i.e. once for the build directory and once for the installed version of HPX). Please the cmake documentation for details (https://cmake.org/cmake/help/v3.16/command/configure_file.html).

**Comment by MukundVaradarajan** [comment]
I have got an idea of how the script works now, how do I put in the documentation?

**Comment by MukundVaradarajan** [comment]
@msimberg @hkaiser can you help me out please? I am new to this so sorry for the disturbance

**Comment by hkaiser** [comment]
@MukundVaradarajan this is a question for @stevenrbrandt, he created the script.

**Comment by stevenrbrandt** [comment]
@MukundVaradarajan minusc is just a way to refer to the option "-c". It's passed to the compiler when making a .o file instead of an executable.

**Comment by msimberg** [comment]
@MukundVaradarajan I'd put it in `docs/sphinx/manual/creating_hpx_projects.rst` for now. A short overview of what the script does (it's a compiler wrapper) and how to invoke it would be enough. We may eventually want to create a separate section for tools like `hpxcxx` and `hpxrun` (which is also not documented). We can easily move the `hpxcxx` section once we have more than one tool documented.

**Comment by MukundVaradarajan** [comment]
Do I need to create a branch for this change?

**Comment by msimberg** [comment]
@MukundVaradarajan yes, please follow the usual process of creating a pull request (i.e. fork, branch, and open PR). Are you comfortable/familiar with how to do that?

**Comment by MukundVaradarajan** [comment]
@msimberg Yes. Also, is it okay to append this documentation at the end of the file or is it to be inserted somewhere in the middle? (Sorry if I am asking too many questions for a simple thing)

**Comment by stevenrbrandt** [comment]
@msimberg I would normally expect documentation inside a program to be at the top. Opinions @hkaiser ?

**Comment by MukundVaradarajan** [comment]
@stevenrbrandt I was asking whether the docs for `hpxcxx.in` should be appended or inserted in `creating_hpx_projects.rst`, and not within `hpxcxx.in` file itself. So my question now would be:
1. Which file to add the docs? (within `hpxcxx.in` or `creating_hpx_projects.rst`)
2. Where in the file? (Append in the end or insert somewhere in the middle, in case the docs have to be updated in `creating_hpx_projects.rst`, and in case it is `hpxcxx.in` I guess adding the docs in the beginnning should be ok)

**Comment by hkaiser** [comment]
> @stevenrbrandt I was asking whether the docs for hpxcxx.in should be appended or inserted in creating_hpx_projects.rst, and not within hpxcxx.in file itself. So my question now would be:
> 
> Which file to add the docs? (within hpxcxx.in or creating_hpx_projects.rst)
> Where in the file? (Append in the end or insert somewhere in the middle, in case the docs have to be updated in creating_hpx_projects.rst, and in case it is hpxcxx.in I guess adding the docs in the beginnning should be ok)

@MukundVaradarajan if you had to decide, what would you suggest?

**Comment by MukundVaradarajan** [comment]
@hkaiser I would suggest the docs be added to `creating_hpx_projects.rst` file wherever you find it fitting (I haven't gotten to this part yet)

**Comment by hkaiser** [comment]
> I would suggest the docs be added to creating_hpx_projects.rst file

@MukundVaradarajan sounds good to me ;-)

**Comment by MukundVaradarajan** [comment]
@hkaiser @msimberg  I've put up a pull request at https://github.com/STEllAR-GROUP/hpx/pull/4414 
Kindly check whether anything needs changes.

**Comment by stevenrbrandt** [comment]
Looks like the PR associated with this ticket was merged.
