### ISSUE TITLE
Add SPDX identifier to all files

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#4100]
Software Package Data Exchange® (SPDX®) is an open standard for communicating software bill of material information (including components, licenses, copyrights, and security references). See https://spdx.org/ for more information.

We should start adding the SPDX license identifier to our files:
```
// SPDX-License-Identifier: BSL-1.0
```
(prefixed with the appropriate comment tag depending on the filetype.

This can probably be done with a script and is a one-time change. We should also change the inspect license check to verify the existance of this tag in each file.

**Comment by aurianer** [comment]
Does this replace the `Distributed under the Boost Software License, Version 1.0` or is it a further tag ?

**Comment by hkaiser** [comment]
IIUC, it's another, machine readable tag.
