### ISSUE TITLE
Bound tasks

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#4101]
In my latest work on the scheduler, I have introduced a 'bound task' which is done to enable me to launch tasks that are never stolen from one thread to another. This kind of thing is needed for first touch of numa domains (for example) and another use case is things like
```
#pragma omp parallel for schedule(static,1) num_threads(8)
```
where threads are mapped statically to cores. This can now be done with my scheduler.
The cost is that each core now maintains a new queue of bound tasks, in addition to high/normal/low priority tasks.

However, this also introduces a slight problem. I cheated, by adding a new priority of `thread_priority_bound` to complement high/low priority tasks. But this is not optimal and a better way of doing it is to have the `thread_schedule_hint` structure carry a flag that indicates thread or numa domain and a bound tag in it.
This in itself is not a problem and can be easily added, however it makes sense when doing this to also move the thread priority to the schedule_hint structure at the same time, and then expose the structure via executor params so that we can create an executor for cores/numa domain, high/low priority and bound tasks using a single type. We could/should also put stacksize into the same struct so that we have a `thread_schedule_param` object with flags for all of them. an enum would work for most.
 
Problem. I currently treat bound tasks as high priority, but it is conceivable that we might want a bound task of a different priority, this would require more and more queues as we introduce more and more options. Not a great solution. Since we use lifo or fifo and don't have a (lockfree) priority based queue, it will not be simple to add more and more options.

Does anyone have other suggestions for changes along these lines that can make life easier?

**Comment by hkaiser** [comment]
Doesn't libCDS have a lock-free priority queue?

**Comment by biddisco** [comment]
Integrating libCDS is a big job in its own right - we don't really have the manpower to consider that at the time being.

**Comment by biddisco** [comment]
closing this because #4249 adds this support, but the topic should be revisited as we move to a better way of combining scheduler params, executor params, launch policies and task information
