### ISSUE TITLE
Initializing runtime without entry point function and command line arguments

### ISSUE THREAD

**Issue by severinstrobl** [STEllAR-GROUP/hpx#4107]
While trying to integrate HPX into an existing simulation framework, I ran into the issue of initializing the runtime while providing neither an entry point function nor command line arguments. Due to the specifics of our framework at the point where HPX should be initialized I cannot access argc/argv, as the corresponding code is located in a module loaded dynamically at runtime. Additionally, it is necessary to suspend/resume the runtime in our application.

Following the example in the [corresponding section of the manual](https://stellar-group.github.io/hpx/docs/sphinx/latest/html/manual/starting_the_hpx_runtime.html#suspending-and-resuming-the-hpx-runtime), I could not find an overload for `hpx::start()` or `hpx::init()` which allows me to initialize the runtime as described above while ideally passing the configuration to HPX via a vector of strings.

**Comment by msimberg** [comment]
Thanks @severinstrobl, this may just be an oversight on our part, but should be easy enough to add. I'll try to get to this next week. If you'd like to have a go at it the overloads would be missing from `hpx/hpx_init.hpp` and `hpx/hpx_start.hpp`.

**Comment by hkaiser** [comment]
We do have such an overload for `hpx::init` and `hpx::start`:
- https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/hpx_init.hpp#L539-L540
- https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/hpx_start.hpp#L550-L551

The vector can contain either configuration settings or verbatim command line options. For instance:
```
{
    std::vector<std::string> cfg = {
        "--hpx:threads=1",
        "--hpx:print-bind"
    };
    hpx::init(cfg);
}
```

**Comment by msimberg** [comment]
If I understood @severinstrobl correctly he's looking for an overload for `nullptr_t`  (no entry point) and a configuration vector, which is actually missing. I don't remember now if we support passing in `0` and `nullptr`, for `argc` and `argv`, respectively, but that might either already work or be something we could add as well.

**Comment by severinstrobl** [comment]
Exactly, I did not want to pass an entry point. Passing `0` / `nullptr` for `argc` / `argv` to start is prevented by an assertion: https://github.com/STEllAR-GROUP/hpx/blob/8f9678cae0b4e5902582e4f88855d69634beeb57/hpx/hpx_start_impl.hpp#L361

**Comment by hkaiser** [comment]
@severinstrobl So IIUC, you are asking for an initialization function that explicitly inhibits running a startup-function but still allows to pass in configuration strings and command line options through a `vector<string>`:
```
{
    std::vector<std::string> cfg = {
        "--hpx:threads=1",
        "--hpx:print-bind"
    };
    hpx::init(nullptr, cfg);
}
```
Is that correct?

**Comment by severinstrobl** [comment]
@hkaiser If I'm not misinterpreting the docs I think for what I'm trying to do I need an overload of `hpx::start`, rather than `hpx::init`.
While this works for my test case, there seems to be an (unrelated?) issue with `--hpx:print-bind`: When I provide this option via the configuration vector, it seems to be ignored.

**Comment by hkaiser** [comment]
> If I'm not misinterpreting the docs I think for what I'm trying to do I need an overload of hpx::start, rather than hpx::init.

Sure. I'd add overloads for both functions anyways.

> there seems to be an (unrelated?) issue with --hpx:print-bind: When I provide this option via the configuration vector, it seems to be ignored.

This is definitely unrelated, I'll look into this.
