### ISSUE TITLE
dependency chaining error with APEX

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#4115]
## Expected Behavior

HPX builds

## Actual Behavior

APEX now depends on the new collectives module, but this dependency chain failure is within HPX.  Because the barrier_node.cpp file uses an annotated function, it pulls in APEX headers, which pull in other HPX headers, causing the collectives module to depend on the hardware module.

See http://omega.nic.uoregon.edu:8020/#/builders/5/builds/4 for details (the collectives dependency error has been fixed)

## Steps to Reproduce the Problem

  1.  cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBOOST_ROOT=/home/users/khuck/src/hpx/boost_delphi_1.65.1 -DTCMALLOC_ROOT=/usr/local/packages/gperftools/git-gcc7 -DHPX_WITH_MALLOC=tcmalloc -DCMAKE_INSTALL_PREFIX=. -DHPX_WITH_THREAD_IDLE_RATES=ON -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCEL_COALESCING=ON -DHPX_WITH_TOOLS=ON -DHPX_WITH_STACKOVERFLOW_DETECTION_DEFAULT=OFF -DHPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=OFF -DHPX_WITH_APEX=TRUE -DAPEX_WITH_ACTIVEHARMONY=TRUE -DACTIVEHARMONY_ROOT=/usr/local/packages/activeharmony/4.6.0-gcc -DAPEX_WITH_OTF2=TRUE -DOTF2_ROOT=/usr/local/packages/otf2-2.1 -DAPEX_WITH_PAPI=TRUE -DPAPI_ROOT=/usr/local/packages/papi/papi/5.7.0 -DHPX_WITH_APEX_NO_UPDATE=TRUE -DHPX_WITH_APEX_TAG=develop -DAPEX_WITH_BFD=TRUE -DBFD_ROOT=/usr/local/packages/binutils/2.27 -DHPX_WITH_MAX_CPU_COUNT=72 /home/users/khuck/src/hpx
  1.  make
  1.

## Specifications

  - HPX Version: stable
  - Platform (compiler, OS): GCC on Linux

**Comment by msimberg** [comment]
@khuck is the problem gone after 118bf2e1ce81ef585f32511f54b123a157e91903 (merged yesterday)? Our pycicle builder with APEX is now happy again.

**Comment by khuck** [comment]
@msimberg yes, all good!

**Comment by msimberg** [comment]
Fixed by #4093.
