### ISSUE TITLE
static_chunk_size is not obeyed in scan algorithms

### ISSUE THREAD

**Issue by jefftrull** [STEllAR-GROUP/hpx#4118]
## Expected Behavior

I assumed that supplying an execution policy with a fixed chunk size would result in each individual task working on a "chunk" of that size from the input.

## Actual Behavior

Each individual task has a size that is a function of the overall input size and the number of threads. The static chunk size does not appear to affect it.

## Steps to Reproduce the Problem

  1. Build the attached code with HPX master
  1. Run under gdb with a breakpoint at [the size extraction](https://github.com/STEllAR-GROUP/hpx/blob/162c0bd3c728b8fe562babd02af5f158240014ac/libs/algorithms/include/hpx/parallel/util/scan_partitioner.hpp#L133)
  1. Print `size` and observe it is not the static_chunk_size (50000)

## Specifications

  - HPX Version: master from git
  - Platform (compiler, OS): gcc 8.3.0, Ubuntu 19.04

**Comment by jefftrull** [comment]
```c++
// reproducing chunk size issue
// Jeff Trull
#include <random>

#include <hpx/hpx_init.hpp>
#include <hpx/hpx.hpp>
#include <hpx/include/parallel_numeric.hpp>
#include <hpx/include/parallel_algorithm.hpp>

int main(int argc, char* argv[])
{
    // By default this should run on all available cores
    std::vector<std::string> const cfg = {
        "hpx.os_threads=2"
    };

    // Initialize and run HPX
    return hpx::init(argc, argv, cfg);
}

int hpx_main(int argc, char **argv)
{
    using namespace hpx::parallel;
    using namespace hpx::util;

    // create a fixed chunk size to be used in the algorithm
    execution::static_chunk_size fixed(50000);
    // this does not seem to be obeyed!
    auto ex = execution::par.with(fixed);

    // run the below with a breakpoint at scan_partitioner.hpp:133 where each chunk is extracted
    // I find that the size of each chunk is a function of the data size and the number of threads
    // but not the "fixed" chunk size I supplied

    // create and fill random vector of desired size
    std::random_device rnd_device;
    std::mt19937 mersenne_engine{rnd_device()};
    std::uniform_int_distribution<int> dist{1, 20};

    std::size_t sz = 16777216;

    std::vector<int> data(sz);
    std::generate(data.begin(), data.end(),
                  [&]() { return dist(mersenne_engine); });

    std::vector<int> result(sz + 1);

    exclusive_scan(ex, data.begin(), data.end(), result.begin(), 0);

    return hpx::finalize();
}
```

**Comment by jefftrull** [comment]
I did some experiments and I have a theory: perhaps another (undocumented?) executor parameter is involved here: `maximal_number_of_chunks`. If I follow the pattern [in this test](https://github.com/STEllAR-GROUP/hpx/blob/162c0bd3c728b8fe562babd02af5f158240014ac/tests/performance/local/future_overhead.cpp#L299-L314) it looks like my chunk size is obeyed.

If this is by design I'm OK with closing this (though maybe some additional docs are in order)

**Comment by hkaiser** [comment]
The issue is that currently there is no way for the algorithm to see whether the chunk-size was preset by the user or if the chunk-size was derived from falling back to the number of cores and the number of elements in the range. For this reason, the chunk-size returned from your execution parameter object (the `50000`) is corrected such that it allows to go with the given (default) number of chunks (which is calculated by default based on the number of cores available). 

In general I would like to do something about this, but I think I would need some time to think this through.
