### ISSUE TITLE
Local runtime entry-points

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4127]
Opening this to discuss how to expose a "local runtime" to users.

I have two main criteria:
1. The current `hpx::init/start` etc. overloads should work unchanged with the headers they require now.
2. The local and distributed runtimes can be enabled (not running) in the same build (to avoid increasing the number of different configurations there are).

For this to work I'd propose to add new headers (`hpx/local/hpx_init.hpp`? `hpx/hpx_init_local.hpp`? not sure how `hpx/hpx_main.hpp` will work out) and overloads of `hpx::init` perhaps taking an additional tag type as a first argument. The goal would be reuse as much of the init infrastructure as possible, but without having to pull in any distributed headers when using the local runtime.

I'd like to hear ideas for other approaches for this, or if this is overkill in the first place.

**Comment by hkaiser** [comment]
@msimberg Could we extend (and reuse) `hpx::runtime_mode` (https://github.com/STEllAR-GROUP/hpx/blob/master/hpx/runtime/runtime_mode.hpp#L21-L31) for this?

**Comment by msimberg** [comment]
I think semantically it would work very well (`runtime_mode_local`?). Thinking about this a bit more I realize point 2 above is most likely unnecessary (and unnecessarily complicated). Point 1 I'd still like to keep and using the runtime mode fits quite well with that (users would have to explicitly ask for the local runtime).

**Comment by hkaiser** [comment]
`runtime_mode_local` sounds fine to me. We might however want to add more overloads for `hpx::init`/`hpx::start` that make it more convenient to specify this. But this might be another issue - reworking those overloads....

**Comment by msimberg** [comment]
Yep, the overloads are relevant but can quite easily be handled separately.

**Comment by hkaiser** [comment]
Another question: how would this functionality be different from what we already have today, namely that networking is not enabled silently if we can detect that the runtime is used locally only? Would `runtime_mode_local` enforce this behavior or do you plan to do additional things in this case?

**Comment by msimberg** [comment]
My intention with this option is to make the choice explicit, but you're right that there isn't a big functional difference. The main difference is that `runtime_mode_local` would pick the local runtime in #4091 which would not even support using actions and components locally. There may be a small speedup in startup even compared to when networking is automatically disabled due to not having to set any of AGAS etc. up. It could be that keeping this choice implicit through compile-time options will be easier in the end though. Thanks @hkaiser for the good questions!

**Comment by hkaiser** [comment]
Let's keep this open, added `pinned` label.

**Comment by msimberg** [comment]
I think #4646 closes this.
