### ISSUE TITLE
parallel fill leaves elements unfilled

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/hpx#4132]
## Expected Behavior
The parallel fill should fill all elements of the vector passed to it

## Actual Behavior
Seems like a power of 2 smaller than the array is filled

## Steps to Reproduce the Problem

Compile and run the following code:
```
#include <hpx/hpx.hpp>
#include <hpx/include/parallel_fill.hpp>
#include <hpx/include/compute.hpp>
#include <hpx/include/parallel_executors.hpp>
#include <hpx/hpx_main.hpp>

void prvec(std::vector<float> v){
    for(auto i : v)
      std::cout << i << " ";
    std::cout << std::endl;

};

hpx::compute::host::block_executor<> getexec(){
    auto host_targets = hpx::compute::host::get_local_targets();
    typedef hpx::compute::host::block_executor<> executor_type;
    decltype(host_targets) v;
    for(auto host : host_targets) {
        if(v.size() == 4)
            break;
        v.push_back(host);
    }
    executor_type exec(v);
    return exec;

};

void fill_example(){
    auto exec = getexec();
    std::vector<float> vd;
    for(int i=0;i<5;i++) vd.push_back(1.f);
    prvec(vd);
    hpx::parallel::fill(hpx::parallel::execution::par.on(exec),vd.begin(),vd.end(),2.0f);
    prvec(vd);
};

int main(int argc, char **argv) {
    fill_example();
    return 0;
}
```
... Please describe your environment

  - HPX Version: top of master
  - Platform (compiler, OS): gcc 9.2.1

**Comment by stevenrbrandt** [comment]
Note this error is seen on Melete05 running 4 threads (out of a possible 40). If I run with all threads, the error goes away.

**Comment by hkaiser** [comment]
This is most likely a problem with the `hpx::compute::host::block_executor<>` type.

**Comment by msimberg** [comment]
@hkaiser Yep, it's definitely the `block_executor`. It seems to assume that `shape.size()` is nicely divisible by the number of executors in the `block_executors`. I can try to fix this unless you already have something going?

**Comment by hkaiser** [comment]
@msimberg I have not looked into this yet. Any help is very much appreciated. The simplest solution would be to throw an exception if preconditions are violated.

**Comment by msimberg** [comment]
@stevenrbrandt would you mind testing #4133 to see if it fixes the problem for you?

**Comment by stevenrbrandt** [comment]
@msimberg @hkaiser I'll try it as soon as I get the chance.
