### ISSUE TITLE
Use object libraries for modules

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4135]
We should consider using [object libraries](https://cmake.org/cmake/help/latest/command/add_library.html#object-libraries) for creating `libhpx` out of the modules. This should be significantly cleaner and may let us avoid the `force_linking` mechanisms. However, we would need CMake 3.12 for this (object libraries exist before that, but are somewhat crippled). I'm tentatively adding this to next year's release, when I think we could reasonably bump the minimum CMake version to 3.12 or higher.

**Comment by hkaiser** [comment]
Sounds good to me! Good thinking.

**Comment by hkaiser** [comment]
Keeping this open.... (adding `pinned` label).
