### ISSUE TITLE
cacheline_data delivers poor perfomance with C++17 compared to C++14

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#4148]
## Expected Behavior

When running programs compiled with either C++17 or C++14 should have roughly the same performance.

## Actual Behavior

Programs compiled with C++17 are significantly slower. While investigating, it turns out that this is the culprit:
https://github.com/STEllAR-GROUP/hpx/blob/master/libs/concurrency/include/hpx/concurrency/cache_line_data.hpp#L46-L64

This has been verified by performing the following isolated benchmark:
clang: http://quick-bench.com/tn0AzNrQpe3t5gczE8pAJu1N5PI
gcc: http://quick-bench.com/SvM8Otk9FvU96uElajGEMAfw7mI

**Comment by sithhell** [comment]
While fixing this issue, this needs to be addressed as well:
http://quick-bench.com/PkunktMrNXhZ5pdOusj9s9MRQ7c

as in, the generated constructor also initializes the padding data

**Comment by biddisco** [comment]
Nice test. Disturbing result. Bug in the compilers? Seems odd that both gcc and clang are showing it in c++17 mode.

**Comment by sithhell** [comment]
It looks like malloc is just bad when requesting aligned memory... at least that's what the profiler is telling me. So more a malloc bug. Do we know which allocator was in use when the problem was reported first?

**Comment by hkaiser** [comment]
@sithhell we were using tcmalloc for this.

**Comment by msimberg** [comment]
Do we know enough about the behaviour here? Should we maybe revert back to using manual padding instead of alignas for the release until we understand the problem better?

**Comment by hkaiser** [comment]
@msimberg yes, I was planning to suggest doing exactly that - roll things back to manual alignment.

**Comment by hkaiser** [comment]
This has been fixed by merging #4235
