### ISSUE TITLE
It should be possible to call find_package(HPX) multiple times

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4161]
https://github.com/STEllAR-GROUP/tutorials uses a project structure with the main project calling `find_package(HPX)` and subprojects also calling `find_package(HPX)`, which leads to errors because of e.g. `hpx::boost` being created twice (https://circleci.com/gh/STEllAR-GROUP/tutorials/121).

I think this is a reasonable use-case to support. @aurianer what do you think? This should be as easy as
```
if(TARGET hpx::boost)
 ...
  add_library(hpx:boost INTERFACE IMPORTED)
  ...
endif()
```

**Comment by aurianer** [comment]
yep totally !
