### ISSUE TITLE
HPX can't build on OSX

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#4187]
## Expected Behavior

normal build

## Actual Behavior

On Apple OSX, std::at_quick_exit() is not defined on OSX even when -std=c++11 is used

```
In file included from /Users/khuck/src/hpx/hpx/hpx_init.hpp:804,
                 from /Users/khuck/src/hpx/src/hpx_main_argc_argv.cpp:7:
/Users/khuck/src/hpx/hpx/hpx_init_impl.hpp: In function 'int hpx::init(hpx::util::function_nonser<int(boost::program_options::variables_map&)>&, const hpx::program_options::options_description&, int, char**, const std::vector<std::__cxx11::basic_string<char> >&, hpx::startup_function_type, hpx::shutdown_function_type, hpx::runtime_mode)':
/Users/khuck/src/hpx/hpx/hpx_init_impl.hpp:79:14: error: 'at_quick_exit' is not a member of 'std'
   79 |         std::at_quick_exit(detail::on_exit);
      |              ^~~~~~~~~~~~~
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1.  Configure HPX on OSX with GCC 8+ or Clang 8+ or built-in clang

## Specifications

... Please describe your environment

  - HPX Version:  current master
  - Platform (compiler, OS):  GCC or Clang on Apple OSX Catalina

**Comment by msimberg** [comment]
@khuck would you mind trying #4189 out? It seems like this just isn't available on macOS.

**Comment by khuck** [comment]
Closing, as this is fixed
