### ISSUE TITLE
Refactor APEX to eliminate circular dependency

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#4199]
The HPX build keeps breaking because CI doesn't test with APEX and because there's a circular dependency between APEX and HPX. This proposed fix will eliminate the dependency, and will be the first step in making APEX a module.
 
The plan:

I think that making the APEX calls using a callback interface is the best
approach.  There are 11 API calls that are currently used, and one object
type.

The object type already has a configurable definition (when APEX isn't
used, it is just defined as a void*).

The complicated bit will be the apex_task_wrapper object, which is a smart
pointer inside the hpx::threads::thread_data object, but I am sure there's
a work around.

I'll start a branch and change the existing APEX calls to callbacks, and
then figure out the required registration interface.

The apex.hpp and apex.cpp files will be replaced with external_timer.hpp and (if necessary) external_timer.cpp, which will define the hpx::util::external_timer class.  The class will provide a callback interface so that APEX can register with HPX at startup.  HPX will make timer calls to `hpx::util::external_timer::start()` instead of `apex::start()`, for example.  The internal HPX smart pointer will change to a generic base class that APEX can extend to implement the task_wrapper object, and an hpx_thread will maintain a `std::shared_ptr<hpx::util::external_timer::task_wrapper>` object instead of `std::shared_ptr<apex::task_wrapper>`.

**Comment by hkaiser** [comment]
@khuck to store the registered callback in other places we have used either a `std::vector<hpx::util::unique_function_nonser>` (where more than one callback might be registered) or simply a `hpx::util::unique_function_nonser` (where exactly one callback is expected). This seems  a bit on the heavy side (especially for the timer callbacks from inside the scheduler). 

For now we expect just one 'callback' to be registered for those, namely the APEX timer handlers. I think we should go for a simple `void(*f)()` (with a different signature, if needed) to store the function pointers. This should avoid unnecessary overheads.

All the other 'callbacks' into APEX could be handled with a (most likely single) unique function as overheads are not as critical in those places. But function pointer would do as well (depending on whether your actual handlers are plain functions).

> The internal HPX smart pointer will change to a generic base class that APEX can extend to implement the task_wrapper object, and an hpx_thread will maintain a `std::shared_ptr<hpx::util::external_timer::task_wrapper>` object instead of `std::shared_ptr<apex::task_wrapper>`.

Wouldn't a `std::unique_ptr` be sufficient? The `thread_data` objects are non-copyable anyways.

**Comment by khuck** [comment]
@hkaiser Do you have a recommended pattern example for this?  I was just going to define a single object with static function pointers in it, so only one registration was necessary...

As for the shared/unique difference - I admit I don't understand the difference between the two... I'll look into it.

**Comment by hkaiser** [comment]
> I was just going to define a single object with static function pointers in it, so only one registration was necessary...

I'd like to suggest not to tie all callbacks into the same object as that would create unnecessary couplings between the various modules we have/will create. Could you post the list of callbacks you need here to discuss how we could group them?

> As for the shared/unique difference - I admit I don't understand the difference between the two... I'll look into it.

`shared_ptr` exposes shared ownership (hence the name), while `unique_ptr` is uniquely responsible for managing the memory it refers to. Thus `unique_ptr` has much less overhead (no atomic reference count etc.) which is sufficient as we never going to create a copy of it (the surrounding object - `thread_data` is non-copyable by design).

**Comment by khuck** [comment]
@hkaiser here are the functions I know I need so far (changing shared_ptr to unique_ptr of course) along with dummy implementations:

```c++
static uint64_t init(const std::string &thread_name,
    const uint64_t comm_rank, const uint64_t comm_size) { return 0ULL; };
static void finalize(void) {};
static void register_thread(const std::string &name) {};
static std::shared_ptr<task_wrapper> new_task(
    const std::string &name, const uint64_t task_id,
    const std::shared_ptr<task_wrapper> parent_task) {return nullptr; }; 
static std::shared_ptr<task_wrapper> new_task(
    uintptr_t address, const uint64_t task_id,
    const std::shared_ptr<task_wrapper> parent_task) {return nullptr; }; 
static void sample_value(const std::string &name, double value) {};
static void send (uint64_t tag, uint64_t size, uint64_t target) {}; 
static void recv (uint64_t tag, uint64_t size,
    uint64_t source_rank, uint64_t source_thread) {};
static std::shared_ptr<task_wrapper> update_task(
    std::shared_ptr<task_wrapper> wrapper, const std::string &name) {return nullptr; }; 
static std::shared_ptr<task_wrapper> update_task(
    std::shared_ptr<task_wrapper> wrapper, uintptr_t address) {return nullptr; }; 
static void start(std::shared_ptr<task_wrapper> task_wrapper_ptr) {};
static void stop(std::shared_ptr<task_wrapper> task_wrapper_ptr) {};
static void yield(std::shared_ptr<task_wrapper> task_wrapper_ptr) {};
```

The reason I thought I would wrap them in an object is so that for each and every call we wouldn't have to check if the function pointer is null first.  If you know a better design pattern, I am all ears...

**Comment by hkaiser** [comment]
> The reason I thought I would wrap them in an object is so that for each and every call we wouldn't have to check if the function pointer is null first. If you know a better design pattern, I am all ears...

Sure. All I'm suggesting is not to have one object bundling all of the callbacks but perhaps split this into three/four different ones:

- global init/finalize
- thread related functions
- functions related to performance counters
- functions related to parcels

Besides it wouldn't make any difference in terms of checking for `nullptr`, as even if the functions are bundled we would need to check whether some object was registered for a set of callbacks or not anyways.

**Comment by khuck** [comment]
@hkaiser it's mostly done, but I am having some trouble linking components when porting to other systems.  Here's a simple example... `libhpx_unorderedd.so` won't link on linux, because the included headers include annotated_function.hpp, which includes my new header external_timer.hpp, which declares the function pointer variables that are defined/instantiated in the implementation file external_timer.cpp.  libhpx_unorderedd.dylib links fine on apple OSX with clang 9, but won't link on linux with gcc 7.3.  The verbose link with the error I am getting is:

```bash
[ 84%] Linking CXX shared library ../../../lib/libhpx_unorderedd.so
cd /dev/shm/khuck/hpx/build/components/containers/unordered && /storage/packages/cmake/3.15.4/bin/cmake -E cmake_link_script CMakeFiles/unordered_component.dir/link.txt --verbose=1
/packages/gcc/7.3.0/bin/c++ -fPIC -g  -Wl,-z,defs -fvisibility=hidden -shared -Wl,-soname,libhpx_unorderedd.so.1 -o ../../../lib/libhpx_unorderedd.so.1.4.0 CMakeFiles/unordered_component.dir/src/partition_unordered_map_component.cpp.o -Wl,-rpath,/dev/shm/khuck/hpx/build/lib:/home/users/khuck/src/hpx/boost_cyclops_1.65.1/lib:/usr/local/packages/gperftools/2.5/lib:::: ../../../lib/libhpxd.so.1.4.0 /home/users/khuck/src/hpx/boost_cyclops_1.65.1/lib/libboost_system.so -lpthread /home/users/khuck/src/hpx/boost_cyclops_1.65.1/lib/libboost_program_options.so /home/users/khuck/src/hpx/boost_cyclops_1.65.1/lib/libboost_filesystem.so /usr/local/packages/gperftools/2.5/lib/libtcmalloc_minimal.so /usr/lib64/libhwloc.so -latomic -ldl -lrt 
CMakeFiles/unordered_component.dir/src/partition_unordered_map_component.cpp.o:(.toc+0x48): undefined reference to `hpx::util::external_timer::update_task_string_function[abi:cxx11]'
CMakeFiles/unordered_component.dir/src/partition_unordered_map_component.cpp.o:(.toc+0x50): undefined reference to `hpx::util::external_timer::update_task_address_function'
collect2: error: ld returned 1 exit status
make[3]: *** [lib/libhpx_unorderedd.so.1.4.0] Error 1
```

In OSX, that file linked just fine even though that symbol is undefined:

```bash
khuck@kevinmacbookair:~/src/hpx/build/lib$ nm libhpx_unorderedd.dylib | grep update_task
000000000002a990 T __ZN3hpx4util14external_timer11update_taskENSt3__110shared_ptrINS1_12task_wrapperEEERKNS0_18thread_descriptionE
                 U __ZN3hpx4util14external_timer27update_task_string_functionE
                 U __ZN3hpx4util14external_timer28update_task_address_functionE
```

Is there some annotation I can put on these functions to allow linking of shared object libraries with undefined symbols?

**Comment by khuck** [comment]
@hkaiser update: I was able to get it to link by making those symbols weak, but I am not sure that's the best solution...

**Comment by khuck** [comment]
@hkaiser ok, I've spent most of the day fighting with cmake to get everything to link, but I am just now realizing it won't work without help. Here's the current situation:

HPX doesn't have any calls to APEX any more.  However...that means when the libhpx_apex.a library is included in libhpx.so, nothing gets pulled in, even with the -whole-archive linker flags.  As a consequence, nothing gets linked with libhpx_apex.a.  any ideas?  It worked on OSX with clang, but on the much more relevant linux with gcc, it isn't working...

**Comment by hkaiser** [comment]
> HPX doesn't have any calls to APEX any more. However...that means when the libhpx_apex.a library is included in libhpx.so, nothing gets pulled in, even with the -whole-archive linker flags. As a consequence, nothing gets linked with libhpx_apex.a. any ideas? It worked on OSX with clang, but on the much more relevant linux with gcc, it isn't working...

There are at least two solutions to this, I think:
- insert a call to the APEX initialization somewhere in hpx_init.cpp (this could be the function that registers your callbacks); we do similar things for other callbacks here: https://github.com/STEllAR-GROUP/hpx/blob/master/src/hpx_init.cpp#L587-L605
- do what #4135 describes, but I have no experience with that

I think the first suggestion would be the way to go for now as you need to register the callbacks in some way anyways.

**Comment by khuck** [comment]
@hkaiser actually, I stumbled across a solution.  Hopefully will have this finished soon.  When do you plan to release?

**Comment by msimberg** [comment]
@khuck I'll tag a release candidate tomorrow, but we'll wait with the final release until after SC (mid-December most probably).

**Comment by khuck** [comment]
@hkaiser @msimberg OK, I think I am done, and all my tests work both in HPX with/without APEX, and APEX with/without HPX.  I'm going to make a pull request once all my buildbot tests pass now that I have merged into develop on the APEX side.
