### ISSUE TITLE
Make HPX install relocatable

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4228]
There are currently certain hardcoded installation paths in HPX. It would be nice to be able to move the installation freely, but the hardcoded paths prevent that. This is not high priority but considered best practice for CMake packages.

**Comment by hkaiser** [comment]
Note that because of limitations of certain platforms (linux included) we compile the location of the executable into the binary... This might put a stick into this wheel.

**Comment by sithhell** [comment]
We already have a cmake option to turn of the install rpath setting: `HPX_FULL_RPATH`. This currently defaults to `ON` on linux and `OFF` on windows and macos.
