### ISSUE TITLE
Clients of HPX 1.4.0-rc2 with APEX ar not linked to libhpx-apex

### ISSUE THREAD

**Issue by kordejong** [STEllAR-GROUP/hpx#4273]
## Expected Behavior

When using a build of HPX with support for APEX I expect it to be possible to generate a trace without having to instrument my code.

```
# Expected: a trace is printed
APEX_SCREEN_OUTPUT=1 ./fibonacci
```

## Actual Behavior

Without calling an APEX function from my code my program is not linked to libhpx-apex and no trace is generated. When I do call an APEX function, my program is linked to libhpx-apex and a trace can be generated. The same behavior can be seen with the HPX examples, like with fibonacci. No trace can be generated from it. apex_fibonacci can generate a trace.

```
# Actual: no trace is printed
APEX_SCREEN_OUTPUT=1 ./fibonacci
```

## Steps to Reproduce the Problem

I have  a project for testing building different HPX variants (build type, features, ...). With this project I verify whether building HPX works as advertised on my platforms, without being distracted by client code.

  1. git clone https://github.com/kordejong/hello_hpx.git
  1. Edit `rel_with_deb_info.sh`: comment all rebuild commands except for the one for the apex variant. This script shows the arguments passed to CMake.
  1. Run the script. It will build HPX in a temp location (see `build_common.sh`)
  1. Run `APEX_SCREEN_OUTPUT=1 ./fibonacci` in the build directory (`/tmp/hello_hpx/RelWithDebInfo-apex/build/_deps/hpx-build/bin`). Also, `ldd fibonacci` shows that the program is not linked to libhpx_apex.

## Specifications

  - HPX Version: 1.4.0-rc2
  - Platform (compiler, OS): Kubuntu 18.04, gcc-7
  - Subet of the output of CMake configure of HPX: [hpx-configure.txt](https://github.com/STEllAR-GROUP/hpx/files/3954926/hpx-configure.txt)
  - Output of `fibonacci --hpx:info`: [hpx-info.txt](https://github.com/STEllAR-GROUP/hpx/files/3954912/hpx-info.txt)

**Comment by msimberg** [comment]
Would you mind trying to build HPX the "plain" way, i.e. without fetchcontent so that we can rule out any local differences in the environment? I just gave it a try and the examples are definitely linked to `libhpx_apex.so`, and I get the following output:
```
> APEX_SCREEN_OUTPUT=1 ./bin/fibonacci 
fibonacci(10) == 55
elapsed time: 0.136594 [s]

Elapsed time: 0.302601 seconds
Cores detected: 20
Worker Threads observed: 20
Available CPU time: 6.05202 seconds

Counter                                   : #samples | minimum |    mean  |  maximum |  stddev 
------------------------------------------------------------------------------------------------
                    1 Minute Load average :        1      5.610      5.610      5.610      0.000   
------------------------------------------------------------------------------------------------

Timer                                                : #calls  |    mean  |   total  |  % total  
------------------------------------------------------------------------------------------------
            broadcast_call_shutdown_functions_action :        2      0.000      0.001      0.009
                      call_shutdown_functions_action :        2      0.002      0.004      0.074
                                    fibonacci_action :      174      0.010      1.682     27.796
   hpx::parallel::execution::parallel_executor::post :        2      0.000      0.000      0.001
                                            hpx_main :        2      0.000      0.001      0.015
                              load_components_action :        1      0.008      0.008      0.138
                                            pre_main :        2      0.000      0.000      0.002
                   primary_namespace_colocate_action :        2      0.000      0.001      0.009
                                          run_helper :        1      0.021      0.021      0.350
                                 shutdown_all_action :        2      0.001      0.002      0.035
                                           APEX Idle :                          4.331     71.570
------------------------------------------------------------------------------------------------
                                        Total timers : 190
```
Is this the output you expect to see when you say trace?

**Comment by kordejong** [comment]
Good suggestion! Yes, your output is what I am expecting to see. I just rebuilt HPX with this script:

```
set -e

# Clone repo and checkout rc
git clone $HOME/development/repository/hpx
cd hpx
git checkout 1e3cfa0  # 1.4.0-rc2
cd ..

# Configure project
mkdir build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DHPX_WITH_APEX:BOOL=ON \
    -DHPX_WITH_APEX_TAG:STRING=develop \
    -DHPX_WITH_EXAMPLES:BOOL=ON \
    -S hpx -B build

# Build project
cmake --build build
```

I still get the same result though:
```
$ APEX_SCREEN_OUTPUT=1 ./fibonacci
fibonacci(10) == 55
elapsed time: 0.001289 [s]
$ ldd ./fibonacci | grep apex
$ ldd ./apex_fibonacci | grep apex
        libhpx_apex.so.1 => /tmp/meh/build/apex/src/apex/libhpx_apex.so.1 (0x00007f0af3f92000)
```

BTW, I use CMake 3.15.4

**Comment by msimberg** [comment]
I'm a bit stumped. I thought perhaps the build type could affect whether it gets linked or not, but that doesn't seem to be the case.

So just to make sure, you should have this line in `src/CMakeLists.txt`: https://github.com/STEllAR-GROUP/hpx/blob/45c26afc73f3fa7c2b0b3ded6584df60e2f82d55/src/CMakeLists.txt#L286. Could you also do a verbose build? If `libxhpx_apex.so` is not in there something is really strange. My linker line looks like this:
```
/apps/daint/UES/simbergm/local/gcc-9.1.0/bin/g++  -fdiagnostics-color=always -nostdinc++ -I/apps/daint/UES/simbergm/local/gcc-9.1.0/include/c++/9.1.0 -I/apps/daint/UES/simbergm/local/gcc-9.1.0/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/apps/daint/UES/simbergm/local/gcc-9.1.0/include/c++/9.1.0/x86_64-pc-linux-gnu -L/apps/daint/UES/simbergm/local/gcc-9.1.0/lib64 -Wl,-rpath,/apps/daint/UES/simbergm/local/gcc-9.1.0/lib64 -O3 -DNDEBUG  -L/apps/daint/UES/simbergm/local/gcc-9.1.0/lib64 -Wl,-z,defs -fvisibility=hidden examples/quickstart/CMakeFiles/fibonacci.dir/fibonacci.cpp.o  -o bin/fibonacci  -Wl,-rpath,/apps/daint/UES/simbergm/src/hpx/build/gcc-9-apex/lib:/apps/daint/UES/simbergm/src/hpx/build/gcc-9-apex/apex/src/apex:/apps/daint/UES/simbergm/local/boost-1.70.0-gcc-9.1.0-c++17-debug/lib:/apps/daint/UES/simbergm/local/hwloc-2.0.4-gcc-9.1.0/lib: lib/libhpx_init.a lib/libhpx_wrap.a lib/libhpx.so.1.4.0 apex/src/apex/libhpx_apex.so.1.4.0 -lpthread /apps/daint/UES/simbergm/local/boost-1.70.0-gcc-9.1.0-c++17-debug/lib/libboost_program_options.so /apps/daint/UES/simbergm/local/hwloc-2.0.4-gcc-9.1.0/lib/libhwloc.so -latomic -ldl -lrt -Wl,-wrap=main
```

On a slightly unrelated note, I seem to have tagged the wrong commit for `rc2`, but even that wrong commit should have the latest APEX fixes. Just to be sure you could try latest master though.

**Comment by kordejong** [comment]
Yes, I have the same line in `hpx/src/CMakeLists.txt`. This is the link line on my machine:

```
/usr/bin/g++-7  -O2 -g -DNDEBUG   -Wl,-z,defs -fvisibility=hidden CMakeFiles/fibonacci.dir/fibonacci.cpp.o  -o ../../bin/fibonacci -Wl,-rpath,/tmp/meh/build/lib:/tmp/meh/build/apex/src/apex: ../../lib/libhpx_init.a ../../lib/libhpx_wrap.a ../../lib/libhpx.so.1.4.0 ../../apex/src/apex/libhpx_apex.so.1.4.0 /usr/lib/x86_64-linux-gnu/libboost_system.so -lpthread /usr/lib/x86_64-linux-gnu/libboost_program_options.so /usr/lib/x86_64-linux-gnu/libboost_filesystem.so /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so /usr/lib/x86_64-linux-gnu/libhwloc.so -latomic -ldl -lrt -Wl,-wrap=main
```

APEX is in there, but it isn't actually linked. This is with the 1.4.0-rc2 tagged commit. I will start a build with the latest commit in master.

**Comment by kordejong** [comment]
I get the same results when building the last commit in master (45c26afc73f) and not passing HPX_WITH_APEX_TAG=develop.

**Comment by msimberg** [comment]
I'm struggling to think of any useful suggestions. For completeness, what's your linker (probably `ld --version`)? @hkaiser, @biddisco, @sithhell, @khuck, @aurianer any ideas?

**Comment by kordejong** [comment]
```
$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.30
```

**Comment by msimberg** [comment]
We all have the same order of `libhpx` and `libhpx_apex`... 

@kordejong could you try wrapping `../../apex/src/apex/libhpx_apex.so.1.4.0` like this: `-Wl,-no-as-needed ../../apex/src/apex/libhpx_apex.so.1.4.0 -Wl,-as-needed` (I think; the `-no-as-needed` flag is the important part that needs to come before `libhpx_apex`). I'd do it manually just by copying the link line but if you know where to put that in our CMake config go for that.

**Comment by kordejong** [comment]
Yes, your suggestion did the trick! Now fibonacci is linked to libhpx_apex and I can make it report profile/trace information to the screen. I also (only) tried reordering the libraries on the link line, putting the apex lib before the hpx ones, but that did not make a difference. So you are right, wrapping the apex lib with `-Wl,-no-as-needed` and `-Wl,-as-needed` works.

It seems that the behavior of the linker differs with respect to handling libraries that are not needed to satisfy symbols(?).

**Comment by msimberg** [comment]
Excellent, thanks for your patience and for testing this! I'll try to convince CMake to add those flags for the release.

**Comment by msimberg** [comment]
@kordejong please see #4275.
