### ISSUE TITLE
Build Issues with CMake 3.14.4

### ISSUE THREAD

**Issue by aserio** [STEllAR-GROUP/hpx#4278]
## Expected Behavior

CMake should be able to build HPX without needing PkgConfig

## Actual Behavior

Received this error when building HPX in Visual Studio on Windows:

> Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
> CMake Error at tests/unit/resource/CMakeLists.txt:19 (if):
>   if given arguments:
> 
>     "GREATER" "11"
> 
>   Unknown arguments specified
>   Configuring incomplete, errors occurred!

Configuration:
-DCMAKE_RELEASE_TYPE=Debug
-DCMAKE_TOOLCHAIN_FILE=C:\path_to_my_vc\vcpkg.cmake
-HPX_WITH_DOCUMENTATION=On

## Specifications

... Please describe your environment

  - HPX Version: Master
  - Platform (compiler, OS): Windows

**Comment by msimberg** [comment]
Excellent catch, thanks @aserio! I think pkgconfig is a red herring. `HPX_CXX_STANDARD` is not set on Windows when the standard is auto-detected. I think I'll simply disable that test on Windows for now as it doesn't seem to be quite right anyway. After the release the C++ standard check will go away anyway and we can enable it cleanly again.

**Comment by msimberg** [comment]
@aserio would you mind trying out #3279?

**Comment by aserio** [comment]
@msimberg I have good news and I have bad news :D
Good news: CMmake configures and generates without errors!

Bad news: When building core I get these errors:

> >------ Build started: Project: hpx, Configuration: Debug x64 ------
1>throw_exception.cpp
1>parcelhandler.cpp
1>c:\users\adria\git\hpx\src\throw_exception.cpp(54): error C2440: '<function-style-cast>': cannot convert from 'boost::system::error_code' to 'hpx::exception'
1>c:\users\adria\git\hpx\src\throw_exception.cpp(54): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead
1>c:\users\adria\git\hpx\src\runtime\parcelset\parcelhandler.cpp(721): error C2440: '<function-style-cast>': cannot convert from 'const boost::system::error_code' to 'hpx::exception'
1>c:\users\adria\git\hpx\src\runtime\parcelset\parcelhandler.cpp(721): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>Done building project "hpx.vcxproj" -- FAILED.
2>------ Build started: Project: unordered_component, Configuration: Debug x64 ------
3>------ Build started: Project: iostreams_component, Configuration: Debug x64 ------
4>------ Build started: Project: memory_component, Configuration: Debug x64 ------
5>------ Build started: Project: parcel_coalescing_lib, Configuration: Debug x64 ------
2>LINK : fatal error LNK1104: cannot open file '..\..\..\..\Debug\lib\hpxd.lib'
2>Done building project "unordered_component.vcxproj" -- FAILED.
6>------ Build started: Project: component_storage_component, Configuration: Debug x64 ------
3>LINK : fatal error LNK1104: cannot open file '..\..\..\Debug\lib\hpxd.lib'
6>LINK : fatal error LNK1104: cannot open file '..\..\..\Debug\lib\hpx_unorderedd.lib'
6>Done building project "component_storage_component.vcxproj" -- FAILED.
3>Done building project "iostreams_component.vcxproj" -- FAILED.
7>------ Build started: Project: partitioned_vector_component, Configuration: Debug x64 ------
8>------ Build started: Project: process_component, Configuration: Debug x64 ------
4>LINK : fatal error LNK1104: cannot open file '..\..\..\..\Debug\lib\hpxd.lib'
4>Done building project "memory_component.vcxproj" -- FAILED.
7>LINK : fatal error LNK1104: cannot open file '..\..\..\..\Debug\lib\hpxd.lib'
8>LINK : fatal error LNK1104: cannot open file '..\..\..\Debug\lib\hpxd.lib'
8>Done building project "process_component.vcxproj" -- FAILED.
7>Done building project "partitioned_vector_component.vcxproj" -- FAILED.
5>LINK : fatal error LNK1104: cannot open file 'Debug\lib\hpxd.lib'
5>Done building project "parcel_coalescing_lib.vcxproj" -- FAILED.
========== Build: 0 succeeded, 8 failed, 2 up-to-date, 0 skipped ==========

Should I create a separate ticket?

**Comment by msimberg** [comment]
@aserio yes please!

**Comment by aserio** [comment]
Created new ticket Issue #4282 to address compilation issues. Closing this ticket as the CMake issue has been resolved on the release branch with PR #4279

**Comment by aserio** [comment]
I'm sorry @msimberg I screwed this up. I did not properly set up the release branch on my machine. I am still seeing the error on release. I have attached the full error below:

> Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.18362.
CMake version: 3.14.4
HPX version: 1.4.0
No vectorization library configured
Native TLS is enabled.
Nice threadlevel is disabled.
Stack traces are enabled.
Compiling with the native toolset
C++ mode used: C++
Performing Test HPX_WITH_CXX11_ALIAS_TEMPLATES - pre-set to TRUE
Performing Test HPX_WITH_CXX11_ALIGNAS - pre-set to TRUE
Performing Test HPX_WITH_CXX11_AUTO - pre-set to TRUE
Performing Test HPX_WITH_CXX11_CONSTEXPR - pre-set to TRUE
Performing Test HPX_WITH_CXX11_DECLTYPE - pre-set to TRUE
Performing Test HPX_WITH_CXX11_SFINAE_EXPRESSION - pre-set to TRUE
Performing Test HPX_WITH_CXX11_DEFAULTED_FUNCTIONS - pre-set to TRUE
Performing Test HPX_WITH_CXX11_DELETED_FUNCTIONS - pre-set to TRUE
Performing Test HPX_WITH_CXX11_EXPLICIT_CONVERSION_OPERATORS - pre-set to TRUE
Performing Test HPX_WITH_CXX11_EXPLICIT_VARIADIC_TEMPLATES - pre-set to TRUE
Performing Test HPX_WITH_CXX11_EXTENDED_FRIEND_DECLARATIONS - pre-set to TRUE
Performing Test HPX_WITH_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS - pre-set to TRUE
Performing Test HPX_WITH_CXX11_INLINE_NAMESPACES - pre-set to TRUE
Performing Test HPX_WITH_CXX11_LAMBDAS - pre-set to TRUE
Performing Test HPX_WITH_CXX11_NOEXCEPT - pre-set to TRUE
Performing Test HPX_WITH_CXX11_NULLPTR - pre-set to TRUE
Performing Test HPX_WITH_CXX11_NSDMI - pre-set to TRUE
Performing Test HPX_WITH_CXX11_RANGE_BASED_FOR - pre-set to TRUE
Performing Test HPX_WITH_CXX11_RVALUE_REFERENCES - pre-set to TRUE
Performing Test HPX_WITH_CXX11_SCOPED_ENUMS - pre-set to TRUE
Performing Test HPX_WITH_CXX11_STATIC_ASSERT - pre-set to TRUE
Performing Test HPX_WITH_CXX11_VARIADIC_MACROS - pre-set to TRUE
Performing Test HPX_WITH_CXX11_VARIADIC_TEMPLATES - pre-set to TRUE
Performing Test HPX_WITH_CXX11_OVERRIDE - pre-set to TRUE
Performing Test HPX_WITH_CXX11_ARRAY - pre-set to TRUE
Performing Test HPX_WITH_CXX11_ATOMIC - pre-set to TRUE
Performing Test HPX_WITH_CXX11_ATOMIC_128BIT - pre-set to TRUE
Performing Test HPX_WITH_CXX11_CHRONO - pre-set to TRUE
Performing Test HPX_WITH_CXX11_CSTDINT - pre-set to TRUE
Performing Test HPX_WITH_CXX11_EXCEPTION_PTR - pre-set to TRUE
Performing Test HPX_WITH_CXX11_FORWARD_LIST - pre-set to TRUE
Performing Test HPX_WITH_CXX11_STD_INITIALIZER_LIST - pre-set to TRUE
Performing Test HPX_WITH_CXX11_IS_BIND_EXPRESSION - pre-set to TRUE
Performing Test HPX_WITH_CXX11_IS_PLACEHOLDER - pre-set to TRUE
Performing Test HPX_WITH_CXX11_IS_TRIVIALLY_COPYABLE - pre-set to TRUE
Performing Test HPX_WITH_CXX11_LOCK_GUARD - pre-set to TRUE
Performing Test HPX_WITH_CXX11_STD_QUICK_EXIT - pre-set to TRUE
Performing Test HPX_WITH_CXX11_RANDOM - pre-set to TRUE
Performing Test HPX_WITH_CXX11_RANGE_ACCESS - pre-set to TRUE
Performing Test HPX_WITH_CXX11_REFERENCE_WRAPPER - pre-set to TRUE
Performing Test HPX_WITH_CXX11_REGEX - pre-set to TRUE
Performing Test HPX_WITH_CXX11_SHARED_PTR - pre-set to TRUE
Performing Test HPX_WITH_CXX11_SHARED_PTR_LWG3018 - pre-set to TRUE
Performing Test HPX_WITH_CXX11_SHUFFLE - pre-set to TRUE
Performing Test HPX_WITH_CXX11_THREAD - pre-set to TRUE
Performing Test HPX_WITH_CXX11_TO_STRING - pre-set to TRUE
Performing Test HPX_WITH_CXX11_UNIQUE_LOCK - pre-set to TRUE
Performing Test HPX_WITH_CXX11_UNIQUE_PTR - pre-set to TRUE
Performing Test HPX_WITH_CXX11_UNORDERED_MAP - pre-set to TRUE
Performing Test HPX_WITH_CXX11_UNORDERED_SET - pre-set to TRUE
Performing Test HPX_WITH_CXX11_THREAD_LOCAL - pre-set to TRUE
Performing Test HPX_WITH_CXX11_NORETURN_ATTRIBUTE - Failed
Performing Test HPX_WITH_CXX17_NOEXCEPT_FUNCTIONS_AS_NONTYPE_TEMPLATE_ARGUMENTS - Failed
Performing Test HPX_WITH_MM_PREFETCH - pre-set to TRUE
Performing Test HPX_WITH_STABLE_INPLACE_MERGE - pre-set to TRUE
Performing Test HPX_WITH_UNISTD_H - Failed
Architecture detected: x86_64
Boost version: 1.70.0
Boost version: 1.70.0
Using system allocator.
GIT commit is 7112d99df945d57919ccc5507ee981b0efe9e18f.

> Configuring modules:
> 
>   Module configuration summary (affinity):
>     HPX_AFFINITY_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_AFFINITY_WITH_DEPRECATION_WARNINGS=ON
>     HPX_AFFINITY_WITH_TESTS=ON
> 
>   Module configuration summary (algorithms):
>     HPX_ALGORITHMS_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_ALGORITHMS_WITH_TESTS=ON
> 
>   Module configuration summary (allocator_support):
>     HPX_ALLOCATOR_SUPPORT_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_ALLOCATOR_SUPPORT_WITH_DEPRECATION_WARNINGS=ON
>     HPX_ALLOCATOR_SUPPORT_WITH_TESTS=ON
> 
>   Module configuration summary (assertion):
>     HPX_ASSERTION_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_ASSERTION_WITH_DEPRECATION_WARNINGS=ON
>     HPX_ASSERTION_WITH_TESTS=ON
> 
>   Module configuration summary (basic_execution):
>     HPX_BASIC_EXECUTION_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_BASIC_EXECUTION_WITH_DEPRECATION_WARNINGS=ON
>     HPX_BASIC_EXECUTION_WITH_TESTS=ON
> 
>   Module configuration summary (batch_environments):
>     HPX_BATCH_ENVIRONMENTS_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_BATCH_ENVIRONMENTS_WITH_DEPRECATION_WARNINGS=ON
>     HPX_BATCH_ENVIRONMENTS_WITH_TESTS=ON
> 
>   Module configuration summary (cache):
>     HPX_CACHE_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_CACHE_WITH_DEPRECATION_WARNINGS=ON
>     HPX_CACHE_WITH_TESTS=ON
> 
>   Module configuration summary (checkpoint):
>     HPX_CHECKPOINT_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_CHECKPOINT_WITH_DEPRECATION_WARNINGS=ON
>     HPX_CHECKPOINT_WITH_TESTS=ON
> 
>   Module configuration summary (collectives):
>     HPX_COLLECTIVES_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_COLLECTIVES_WITH_DEPRECATION_WARNINGS=ON
>     HPX_COLLECTIVES_WITH_TESTS=ON
> 
>   Module configuration summary (compute):
>     HPX_COMPUTE_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_COMPUTE_WITH_TESTS=ON
> 
>   Module configuration summary (compute_cuda):
>     HPX_COMPUTE_CUDA_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_COMPUTE_CUDA_WITH_TESTS=ON
> 
>   Module configuration summary (compute_cuda):
>     HPX_COMPUTE_CUDA_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_COMPUTE_CUDA_WITH_TESTS=ON
> 
>   Module configuration summary (concepts):
>     HPX_CONCEPTS_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_CONCEPTS_WITH_DEPRECATION_WARNINGS=ON
>     HPX_CONCEPTS_WITH_TESTS=ON
> 
>   Module configuration summary (concurrency):
>     HPX_CONCURRENCY_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_CONCURRENCY_WITH_DEPRECATION_WARNINGS=ON
>     HPX_CONCURRENCY_WITH_TESTS=ON
> 
>   Module configuration summary (config):
>     HPX_CONFIG_WITH_COMPATIBILITY_HEADERS=OFF
>     HPX_CONFIG_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_CONFIG_WITH_TESTS=ON
> 
>   Module configuration summary (coroutines):
>     HPX_COROUTINES_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_COROUTINES_WITH_DEPRECATION_WARNINGS=ON
>     HPX_COROUTINES_WITH_TESTS=ON
> 
>   Module configuration summary (datastructures):
>     HPX_DATASTRUCTURES_WITH_ADAPT_STD_TUPLE=ON
>     HPX_DATASTRUCTURES_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_DATASTRUCTURES_WITH_DEPRECATION_WARNINGS=ON
>     HPX_DATASTRUCTURES_WITH_TESTS=ON
> 
>   Module configuration summary (debugging):
>     HPX_DEBUGGING_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_DEBUGGING_WITH_DEPRECATION_WARNINGS=ON
>     HPX_DEBUGGING_WITH_TESTS=ON
> 
>   Module configuration summary (errors):
>     HPX_ERRORS_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_ERRORS_WITH_DEPRECATION_WARNINGS=ON
>     HPX_ERRORS_WITH_TESTS=ON
> 
>   Module configuration summary (execution):
>     HPX_EXECUTION_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_EXECUTION_WITH_TESTS=ON
> 
>   Module configuration summary (filesystem):
>     HPX_FILESYSTEM_WITH_BOOST_FILESYSTEM_COMPATIBILITY=ON
>     HPX_FILESYSTEM_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_FILESYSTEM_WITH_TESTS=ON
> 
>   Module configuration summary (format):
>     HPX_FORMAT_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_FORMAT_WITH_DEPRECATION_WARNINGS=ON
>     HPX_FORMAT_WITH_TESTS=ON
> 
>   Module configuration summary (functional):
>     HPX_FUNCTIONAL_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_FUNCTIONAL_WITH_DEPRECATION_WARNINGS=ON
>     HPX_FUNCTIONAL_WITH_TESTS=ON
> 
>   Module configuration summary (hardware):
>     HPX_HARDWARE_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_HARDWARE_WITH_DEPRECATION_WARNINGS=ON
>     HPX_HARDWARE_WITH_TESTS=ON
> 
>   Module configuration summary (hashing):
>     HPX_HASHING_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_HASHING_WITH_DEPRECATION_WARNINGS=ON
>     HPX_HASHING_WITH_TESTS=ON
> 
>   Module configuration summary (iterator_support):
>     HPX_ITERATOR_SUPPORT_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_ITERATOR_SUPPORT_WITH_DEPRECATION_WARNINGS=ON
>     HPX_ITERATOR_SUPPORT_WITH_TESTS=ON
> 
>   Module configuration summary (local_lcos):
>     HPX_LOCAL_LCOS_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_LOCAL_LCOS_WITH_DEPRECATION_WARNINGS=ON
>     HPX_LOCAL_LCOS_WITH_TESTS=ON
> 
>   Module configuration summary (logging):
>     HPX_LOGGING_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_LOGGING_WITH_DEPRECATION_WARNINGS=ON
>     HPX_LOGGING_WITH_TESTS=ON
> 
>   Module configuration summary (memory):
>     HPX_MEMORY_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_MEMORY_WITH_TESTS=ON
> 
>   Module configuration summary (plugin):
>     HPX_PLUGIN_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_PLUGIN_WITH_DEPRECATION_WARNINGS=ON
>     HPX_PLUGIN_WITH_TESTS=ON
> 
>   Module configuration summary (preprocessor):
>     HPX_PREPROCESSOR_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_PREPROCESSOR_WITH_DEPRECATION_WARNINGS=ON
>     HPX_PREPROCESSOR_WITH_TESTS=ON
> 
>   Module configuration summary (program_options):
>     HPX_PROGRAM_OPTIONS_WITH_BOOST_PROGRAM_OPTIONS_COMPATIBILITY=ON
>     HPX_PROGRAM_OPTIONS_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_PROGRAM_OPTIONS_WITH_TESTS=ON
> 
>   Module configuration summary (resiliency):
>     HPX_RESILIENCY_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_RESILIENCY_WITH_TESTS=ON
> 
>   Module configuration summary (resource_partitioner):
>     HPX_RESOURCE_PARTITIONER_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_RESOURCE_PARTITIONER_WITH_DEPRECATION_WARNINGS=ON
>     HPX_RESOURCE_PARTITIONER_WITH_TESTS=ON
> 
>   Module configuration summary (segmented_algorithms):
>     HPX_SEGMENTED_ALGORITHMS_WITH_DEPRECATION_WARNINGS=OFF
>     HPX_SEGMENTED_ALGORITHMS_WITH_TESTS=ON
> 
>   Module configuration summary (serialization):
>     HPX_SERIALIZATION_WITH_BOOST_TYPES=ON
>     HPX_SERIALIZATION_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_SERIALIZATION_WITH_DEPRECATION_WARNINGS=ON
>     HPX_SERIALIZATION_WITH_TESTS=ON
> 
>   Module configuration summary (static_reinit):
>     HPX_STATIC_REINIT_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_STATIC_REINIT_WITH_DEPRECATION_WARNINGS=ON
>     HPX_STATIC_REINIT_WITH_TESTS=ON
> 
>   Module configuration summary (statistics):
>     HPX_STATISTICS_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_STATISTICS_WITH_DEPRECATION_WARNINGS=ON
>     HPX_STATISTICS_WITH_TESTS=ON
> 
>   Module configuration summary (synchronization):
>     HPX_SYNCHRONIZATION_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_SYNCHRONIZATION_WITH_DEPRECATION_WARNINGS=ON
>     HPX_SYNCHRONIZATION_WITH_TESTS=ON
> 
>   Module configuration summary (testing):
>     HPX_TESTING_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_TESTING_WITH_DEPRECATION_WARNINGS=ON
>     HPX_TESTING_WITH_TESTS=ON
> 
>   Module configuration summary (thread_support):
>     HPX_THREAD_SUPPORT_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_THREAD_SUPPORT_WITH_DEPRECATION_WARNINGS=ON
>     HPX_THREAD_SUPPORT_WITH_TESTS=ON
> 
>   Module configuration summary (threadmanager):
>     HPX_THREADMANAGER_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_THREADMANAGER_WITH_DEPRECATION_WARNINGS=ON
>     HPX_THREADMANAGER_WITH_TESTS=ON
> 
>   Module configuration summary (timing):
>     HPX_TIMING_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_TIMING_WITH_DEPRECATION_WARNINGS=ON
>     HPX_TIMING_WITH_TESTS=ON
> 
>   Module configuration summary (topology):
>     HPX_TOPOLOGY_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_TOPOLOGY_WITH_DEPRECATION_WARNINGS=ON
>     HPX_TOPOLOGY_WITH_TESTS=ON
> 
>   Module configuration summary (type_support):
>     HPX_TYPE_SUPPORT_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_TYPE_SUPPORT_WITH_DEPRECATION_WARNINGS=ON
>     HPX_TYPE_SUPPORT_WITH_TESTS=ON
> 
>   Module configuration summary (util):
>     HPX_UTIL_WITH_COMPATIBILITY_HEADERS=ON
>     HPX_UTIL_WITH_DEPRECATION_WARNINGS=ON
>     HPX_UTIL_WITH_TESTS=ON
> 
> Configuring components:
>   component_storage
>   containers
>   iostreams
>   performance_counters
>   process
> Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
> CMake Error at tests/unit/resource/CMakeLists.txt:21 (if):
>   if given arguments:
> 
>     "NOT" "MSVC" "AND" "GREATER" "11"
> 
>   Unknown arguments specified
> 
> 
> Configuring incomplete, errors occurred!
> See also "C:/Users/adria/Git/hpx/build-release/CMakeFiles/CMakeOutput.log".
> See also "C:/Users/adria/Git/hpx/build-release/CMakeFiles/CMakeError.log".

**Comment by msimberg** [comment]
Ah, my bad. I've just pushed to a commit to the release branch that hopefully fixes it. Could you give it a try again?

**Comment by aserio** [comment]
@msimberg  your changes work! Interesting thing to note, it still reports that it cannot find PkgConfig but it now does not interrupt the build:

> Configuring components:
  component_storage
  containers
  iostreams
  performance_counters
  process
>Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
>Creating Doxyfile: C:/Users/adria/Git/hpx/build-release/docs/hpx_autodoc.doxy

Complies and runs hello_world as well.

Thanks.

**Comment by msimberg** [comment]
We always try to find pkgconfig but don't require it, so the warning is harmless. However, if it's never needed (or available) on Windows we could just not look for it there.

**Comment by hkaiser** [comment]
@msimberg pkgconfig is never needed on Windows when using the native toolchain (MSVC).
