### ISSUE TITLE
Build Issues with Release on Windows

### ISSUE THREAD

**Issue by aserio** [STEllAR-GROUP/hpx#4282]
When building HPX Core on the current release branch(7112d99) I receive the following error:

> ------ Build started: Project: hpx, Configuration: Debug x64 ------
1>throw_exception.cpp
1>parcelhandler.cpp
1>c:\users\adria\git\hpx\src\throw_exception.cpp(54): error C2440: '': cannot convert from 'boost::system::error_code' to 'hpx::exception'
1>c:\users\adria\git\hpx\src\throw_exception.cpp(54): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>The use of BOOST_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_BYTE instead
1>c:\users\adria\git\hpx\src\runtime\parcelset\parcelhandler.cpp(721): error C2440: '': cannot convert from 'const boost::system::error_code' to 'hpx::exception'
1>c:\users\adria\git\hpx\src\runtime\parcelset\parcelhandler.cpp(721): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>Done building project "hpx.vcxproj" -- FAILED.
2>------ Build started: Project: unordered_component, Configuration: Debug x64 ------
3>------ Build started: Project: iostreams_component, Configuration: Debug x64 ------
4>------ Build started: Project: memory_component, Configuration: Debug x64 ------
5>------ Build started: Project: parcel_coalescing_lib, Configuration: Debug x64 ------
2>LINK : fatal error LNK1104: cannot open file '........\Debug\lib\hpxd.lib'
2>Done building project "unordered_component.vcxproj" -- FAILED.
6>------ Build started: Project: component_storage_component, Configuration: Debug x64 ------
3>LINK : fatal error LNK1104: cannot open file '......\Debug\lib\hpxd.lib'
6>LINK : fatal error LNK1104: cannot open file '......\Debug\lib\hpx_unorderedd.lib'
6>Done building project "component_storage_component.vcxproj" -- FAILED.
3>Done building project "iostreams_component.vcxproj" -- FAILED.
7>------ Build started: Project: partitioned_vector_component, Configuration: Debug x64 ------
8>------ Build started: Project: process_component, Configuration: Debug x64 ------
4>LINK : fatal error LNK1104: cannot open file '........\Debug\lib\hpxd.lib'
4>Done building project "memory_component.vcxproj" -- FAILED.
7>LINK : fatal error LNK1104: cannot open file '........\Debug\lib\hpxd.lib'
8>LINK : fatal error LNK1104: cannot open file '......\Debug\lib\hpxd.lib'
8>Done building project "process_component.vcxproj" -- FAILED.
7>Done building project "partitioned_vector_component.vcxproj" -- FAILED.
5>LINK : fatal error LNK1104: cannot open file 'Debug\lib\hpxd.lib'
5>Done building project "parcel_coalescing_lib.vcxproj" -- FAILED.
========== Build: 0 succeeded, 8 failed, 2 up-to-date, 0 skipped ==========

It mostly looks like some header issues due to the refactor.

## Specifications

  - Platform (compiler, OS): Windows, Visual Studio 2017

**Comment by msimberg** [comment]
I'm confused as to why it fails for you but not on any of our CI builds... but could you try adding `hpx/errors/exception.hpp` to this list: https://github.com/STEllAR-GROUP/hpx/blob/2216d7f2134f74ee000f837f2ec0adb824538ab8/libs/errors/CMakeLists.txt#L12-L19?

**Comment by msimberg** [comment]
I won't be around much in the next few hours. @hkaiser, @K-ballo would you mind having a look if the above doesn't resolve the problem?

**Comment by K-ballo** [comment]
That sounds a lot like a very very old issue having to do with Boost making their `error_code` conversions explicit.

**Comment by aserio** [comment]
@msimberg and @K-ballo I just realized this is a problem with my set up. @K-ballo you are right on target. Sorry for the noise!
