### ISSUE TITLE
CMake inserting unwanted quote characters

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#4286]
## Expected Behavior

MPI Configurations should work fine.

## Actual Behavior

When the MPI library has more than one flag defined, the MPI flags are added to CXX_FLAGS with quotes around them.  For example, the openmpi build I am using defines `MPI_CXX_COMPILE_OPTIONS=-fexceptions;-pthread`. When that gets added to the CXX_FLAGS, it is added with quotes (and fails to compile).  For example, `plugins/parcelport/mpi/CMakeFiles/parcelport_mpi.dir/flags.make` looks like this:

```
CXX_FLAGS = -fPIC -O3 -DNDEBUG -fPIC   -std=c++17 "-fexceptions -pthread" -pthread -Wall -Wextra -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-sign-promo -Wno-attributes -Wno-cast-align -Wno-unused-parameter -Wformat=2 -Wno-format-nonliteral -Winit-self -Wdouble-promotion -Wcast-qual -Wcast-align -Werror=trampolines -Werror=parentheses -Werror=reorder -Werror=return-type -Werror=sequence-point -Werror=uninitialized -Werror=format -Werror=missing-braces -Werror=sign-compare -fdiagnostics-show-option -Werror=vla -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Wno-sync-nand -Wno-delete-non-virtual-dtor -fvisibility=hidden
```

Which generates this compiler error:

```
g++: error: unrecognized command line option '-fexceptions -pthread'; did you mean '-fexceptions'?
make[3]: *** [plugins/parcelport/mpi/CMakeFiles/parcelport_mpi.dir/mpi_environment.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

## Steps to Reproduce the Problem

  1.  Configure HPX with MPI enabled, ideally one with more than one compiler flag.  For example, in openmpi, you can change the pkgconfig files to have: `Cflags: -I${includedir}     -fexceptions -pthread`
  1.  After configuring HPX, see that the flags have quotes around them, i.e. in `src/CMakeFiles/hpx.dir/flags.make` or `plugins/parcelport/mpi/CMakeFiles/parcelport_mpi.dir/flags.make`

## Specifications

... Please describe your environment

  - HPX Version:  current master
  - Platform (compiler, OS):  linux, x86_64, gcc 7.3

**Comment by khuck** [comment]
...I think this extra flag is coming because OpenMPI is built with C++ exception support.

**Comment by msimberg** [comment]
What version of CMake are you using? And did you actually mean `MPI_CXX_COMPILE_FLAGS`? We are still using the (deprecated) `MPI_CXX_COMPILE_FLAGS` variable, and not `MPI_CXX_COMPILE_OPTIONS` when setting up the `hpx::mpi` target. I tried manually setting `INTERFACE_COMPILE_OPTIONS` to `"-pthread;-fexceptions"` here: https://github.com/STEllAR-GROUP/hpx/blob/fe37ef4c7fd6f35ae96dacf1841ecb39c629e301/cmake/HPX_SetupMPI.cmake#L50, but it expands correctly to two separate options. As far as I can tell that's the only place where we get the MPI flags.

**Comment by khuck** [comment]
I did mean MPI_CXX_COMPILE_FLAGS, yes.  I am using OpenMPI built by Spack, which enables C++ exception support by default.  I'll try testing it some more.

**Comment by diehlpk** [comment]
Hi, 

it seems that some similar error appears at another place when compiling HPX with mpich [0] on Fedora. However, using openmpi, does not show this error. I think it is might relate to a newer CMake version, since this error did not appear a few months ago on Fedora's build system. 

[0] https://kojipkgs.fedoraproject.org//work/tasks/1001/47271001/build.log

**Comment by khuck** [comment]
I was able to work around the problem by building openmpi without --enable-cxx-exceptions.  With that flag, the pkgconfig file defines Cflags values, and CMake 15 is putting quotes around them.
