### ISSUE TITLE
1d_stencil_7 does not seem to scale well

### ISSUE THREAD

**Issue by kordejong** [STEllAR-GROUP/hpx#4302]
## Expected Behavior

I expected the `1d_stencil_7` example to scale well over threads in a single node. When adding workers to a constant size problem, I expect the run time to decrease. Ideally proportionally.

## Actual Behavior

It does not seem to scale well (strong scaling). Output on a cluster node:

```
# Localities,OS_Threads,Execution_Time_sec,Points_per_Partition,Partitions,Time_Steps
# 1,     1,     4.274528498, 10000,                1000,                 100
# 1,     2,     2.865365903, 10000,                1000,                 100
# 1,     4,     2.256500222, 10000,                1000,                 100
# 1,     8,     1.992941052, 10000,                1000,                 100
# 1,     16,    1.916695974, 10000,                1000,                 100
# 1,     32,    3.198471846, 10000,                1000,                 100
```

After a drop in the execution time, it even increases. In an experiment I ran, the parallel efficiency drops to well below 20%.

## Steps to Reproduce the Problem

  1. Build release build of HPX, with examples
  1. Download the attached [shell script](https://github.com/STEllAR-GROUP/hpx/files/4045605/run_stencil.txt). Edit it for the location of the HPX examples and possibly the number of workers
  1. Run the shell script. It will print execution times for different numbers of threads.

## Specifications

  - HPX Version: upcoming 1.4.0, commit d1c61de
  - Platform (compiler, OS): gcc-7.2.0, CentOS 7, node with two AMD EPYC 7451 24-Core Processors and 256 GB memory
  - [output of --hpx:dump-config](https://github.com/STEllAR-GROUP/hpx/files/4045554/dump-config.txt)
  - [output of --hpx:info](https://github.com/STEllAR-GROUP/hpx/files/4045556/info.txt)

## Notes and questions

- I spent quite some time trying to get my own programs to scale well and, so far, I have not been successful. Therefore I turned to the HPX examples to see whether they scale well.
- Is stencil_7 supposed to scale well?
- If so, what could be possible reasons when it doesn't yet?

**Comment by hkaiser** [comment]
@kordejong I wouldn't expect stencil_7 to scale in any way ;-) It was not optimized. OTOH, stencil_8 has seen a bit of polishing (despite the fact that it is just an example), so I might suggest you use that one for your experiments.

**Comment by kordejong** [comment]
I see, thank you. I focused on `stencil_7` because my own algorithms take a similar approach.

**Comment by hkaiser** [comment]
@kordejong algorithmically all the stencil examples are very similar, you should be fine with looking at stencil_8, I think.

**Comment by msimberg** [comment]
Just to add some generic advice: you should almost always have a way to control the chunk/task/partition size for your algorithm (as has been done in the 1d stencil examples), and then set the chunk size as large as you can without limiting your available parallelism. For example, our parallel algorithms typically create a number of tasks around 4 times the number of cores available.

**Comment by kordejong** [comment]
Thank you @msimberg. A little background: The first step I do when testing my algorithms for scalability is to test which partition size gives the best performance. Using this partition size I perform strong and weak scaling experiments. So, indeed, I have a way to vary the task size.

I am very interested in any other info about obtaining good scalability when using HPX. I am now a happy user of the API, but am in great need of good scalable results ;-). Currently I focus on the memory allocator. My programs allocate and deallocate many buffers of the same size. `stencil_8` contains an example of a caching allocator, which is likely also useful in my case.

Pointers to good scaling HPX examples / applications or topics to look into are very much appreciated.

**Comment by hkaiser** [comment]
@kordejong can we close this now?

**Comment by kordejong** [comment]
@hkaiser sure, fine with me
