### ISSUE TITLE
ld: error: duplicate symbol: freebsd_environ

### ISSUE THREAD

**Issue by yurivict** [STEllAR-GROUP/hpx#4307]
https://github.com/STEllAR-GROUP/hpx/blob/master/libs/errors/src/exception.cpp#L40

https://github.com/STEllAR-GROUP/hpx/blob/master/src/custom_exception_info.cpp#L51

Version 1.4.0

**Comment by msimberg** [comment]
Thanks @yurivict, very good catch! That's easy enough to fix. I'm wondering though, would you happen to have experience with BSD CI services that you could recommend? This is unfortunately going to be an eternal battle unless we have CI that tests (some) BSDs.

**Comment by yurivict** [comment]
1. CirrusCI supports FreeBSD: https://cirrus-ci.org/guide/supported-computing-services/#freebsd-support
2. Jenkins supports FreeBSD, and can be run in a VM.

I don't have personal experience with these though.
