### ISSUE TITLE
Possible V1.4.1

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#4319]
This is a collection of PRs that should be considered if we decided to prepare a V1.4.1 release of HPX:

(please keep this list sorted)

- #4357: Adding missing #includes to fix gcc V10 linker problems
- #4353: Skip MPI_Finalize if MPI_Init is not called from HPX
- #4343: Give a hard error if IO counters are enabled on non-Linux systems
- #4337: Installing pdb files on Windows
- #4335: Adding capability to buildsystem to use an installed version of HPX
- #4322: Undefine VT1 and VT2 after boost includes
- #4315: Forcing exported symbols from composable_guard to be linked into core library
- #4310: Remove environment handling from exception.cpp

Please add more as we go or if you think certain patches should go into a point release

**Comment by msimberg** [comment]
For #4312 we actually need #4304 as well, or neither of them. I'd say we only need to keep compatibility headers for changes between releases, not for every change that happens between releases.

**Comment by hkaiser** [comment]
@msimberg excellent catch! I'll add it to the list (which is growing way too fast...).

**Comment by hkaiser** [comment]
This can be closed now as V1.4.1 was released
