### ISSUE TITLE
Const-correctness error in assignment operator of compute::vector

### ISSUE THREAD

**Issue by PrimeF** [STEllAR-GROUP/hpx#4323]
## Expected Behavior

The compute vector assigns another compute vector.

## Actual Behavior

A const-correctness error is thrown, when assigning a compute vector to another compute vector.

## Steps to Reproduce the Problem

  1. Initialize two compute vectors
  2. Assign one to the other

## Specifications

  - HPX Version: 1.4.0
  - Platform (compiler, OS): GCC 9.2.0, CentOS

## Fix suggestions

As suggested by @K-ballo: vector::op= should be copying over other.alloc and operating with that instead

A quick fix working for me is:

```
vector& operator=(vector const& other)
        {
            if (this == &other)
                return *this;

            allocator_type tmpAlloc = other.alloc_;
            
            pointer data =
                alloc_traits::allocate(tmpAlloc, other.capacity_);
            hpx::parallel::util::copy(other.begin(), other.end(),
                iterator(data, 0, alloc_traits::target(tmpAlloc)));

            if (data_ != nullptr)
            {
                alloc_traits::bulk_destroy(alloc_, data_, size_);
                alloc_traits::deallocate(alloc_, data_, capacity_);
            }

            size_ = other.size_;
            capacity_ = other.capacity_;
            alloc_ = other.alloc_;
            data_ = std::move(data);

            return *this;
        }
```

**Comment by hkaiser** [comment]
@PrimeF Thanks for reporting! Would you mind creating a PR for this?

**Comment by PrimeF** [comment]
Sure, I will do one!
