### ISSUE TITLE
HPX Debug and RelWithDebinfo builds on Windows not installing .pdb files.

### ISSUE THREAD

**Issue by McKillroy** [STEllAR-GROUP/hpx#4334]
## Expected Behavior

debug info files (`.pdb`) should be installed

## Actual Behavior

not installing (on windows)

## Specifications
Using the following CMake Command from a master file (superbuild)
```
ExternalProject_Add(hpx 
    PREFIX ${HPX_BUILD_DIR}
    #GIT_REPOSITORY "https://github.com/STEllAR-GROUP/hpx.git"
    GIT_TAG        ${HPX_TAG}
    SOURCE_DIR     ${HPX_SOURCE_DIRECTORY}
    GIT_SHALLOW    TRUE
    GIT_PROGRESS   TRUE
    ## Everything CMake related goes here:
    CMAKE_ARGS
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
     ... etc pp
)
```

  - HPX Version: 1.4.0
  - Platform (compiler, OS): MSVC 2019 on Windows 10 (both latest)

**Comment by McKillroy** [comment]
You can try the following testcase (adjust directories)

`cmake_minimum_required(VERSION 3.15)

project(HPX)

include(ExternalProject)

## SETUP
# Build
SET(CMAKE_BUILD_TYPE Debug)
SET(CMAKE_VERBOSE_MAKEFILE ON)

#Deps Boost
SET(BOOST_ROOT "C:/__A/Arc_Sb/_INSTALL/boost/boost-1.72.0/Debug")
SET(BOOST_LIBRARYDIR "C:/__A/Arc_Sb/_INSTALL/boost/boost-1.72.0/Debug/lib")
SET(BOOST_INCLUDEDIR "C:/__A/Arc_Sb/_INSTALL/boost/boost-1.72.0/Debug/include")
SET(Boost_NO_BOOST_CMAKE ON)
SET(Boost_NO_SYSTEM_PATHS ON)

# Deps hwloc
SET(HWLOC_ROOT "C:/__A/Arc_Sb/_INSTALL/hwloc/2.1.0/Release")
SET(HWLOC_LIBRARY "C:/__A/Arc_Sb/_INSTALL/hwloc/2.1.0/Release/lib/libhwloc.lib")
SET(HWLOC_INCLUDE_DIR "C:/__A/Arc_Sb/_INSTALL/hwloc/2.1.0/Release/include/hwloc")

# HPX
SET(HPX_TAG "1.4.0")
SET(HPX_SOURCE_DIRECTORY "download/hpx/${HPX_TAG}")
SET(HPX_BUILD_DIR        "build/${CMAKE_BUILD_TYPE}")
SET(HPX_INSTALL_DIR      "install/hpx/${HPX_TAG}/${CMAKE_BUILD_TYPE}")
SET(BUILD_SHARED_LIBS ON)
SET(HPX_WITH_TESTS ON)


## RUN
ExternalProject_Add(hpx 
    PREFIX ${HPX_BUILD_DIR}
    GIT_REPOSITORY "https://github.com/STEllAR-GROUP/hpx.git"
    GIT_TAG        ${HPX_TAG}
    SOURCE_DIR     ${HPX_SOURCE_DIRECTORY}
    GIT_SHALLOW    TRUE
    GIT_PROGRESS   TRUE
    ## Everything CMake related goes here:
    CMAKE_ARGS
        
        -DCMAKE_INSTALL_PREFIX=./install

        -DHPX_WITH_EXAMPLES=OFF

        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DCMAKE_INSTALL_PREFIX=${HPX_INSTALL_DIR}
        
        -DBUILD_SHARED_LIBS=${HPX_BUILD_SHARED_LIBS}
        -DHPX_WITH_TESTS=ON

        -DBoost_NO_SYSTEM_PATHS=${Boost_NO_SYSTEM_PATHS}
        -DBOOST_ROOT=${BOOST_ROOT}
        -DBOOST_LIBRARYDIR=${BOOST_LIBRARYDIR}
        -DBOOST_INCLUDEDIR=${BOOST_INCLUDEDIR}
        -DBoost_NO_BOOST_CMAKE=${Boost_NO_BOOST_CMAKE}
        
        -DHWLOC_ROOT=${HWLOC_INSTALL_ROOT}
        -DHWLOC_LIBRARY=${HWLOC_LIBRARY}
        -DHWLOC_INCLUDE_DIR=${HWLOC_INCLUDE_DIR}       
        -DHWLOC_INCLUDE_DIR=${HWLOC_INCLUDE_DIR}       
)`

**Comment by hkaiser** [comment]
@McKillroy please see #4334 for a possible fix

**Comment by McKillroy** [comment]
Seems #4337 fixes it. I tried with a Debug build and hpxd.pdb got installed.
