### ISSUE TITLE
Move gh-pages branch out of hpx repo

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4345]
We've collected quite a bit of bloat in the git repo due to the `gh-pages` branch. About 90% of the size of the repo comes from `gh-pages` commits (170 MB cloned without `gh-pages`, about 1.7 GB with it).

I suggest we start a new repo `hpx-docs` which will get the automatically built docs, and we delete the existing `gh-pages` branch (except for the last commit so that we don't break links, plus possibly some appropriate forwarding pages).

Alternatively, if we don't care about history (we can after all in principle recreate the `gh-pages` history from this repo) we can just force push a single commit to the `gh-pages` branch. This avoids breaking any links.

Any preferences?

We could actually get the repo down to way under 100 MB if we rewrite history. There are some old commits with some sort of generated source files and at least one rar archive (over 100 MB). I'd only do this as a last resort though as it forces everyone to reset their local branches (maybe for HPX 2?).

**Comment by hkaiser** [comment]
Doesn't GitHub.io pull everything from this branch?

**Comment by sithhell** [comment]
We can tell the GitHub page generator to look elsewhere. I support this move as well as rewriting history.

**Comment by msimberg** [comment]
The GitHub pages are repo specific, so we'd end up with docs under `stellar-group.github.io/hpx-docs` instead of `stellar-group.github.io/hpx`. We can still keep an almost empty `gh-pages` branch here which redirects to `hpx-docs`. The second alternative doesn't change any URLs.

**Comment by msimberg** [comment]
I've now moved the documentation to the `hpx-docs` repo. It still has the full history that we had here on the `gh-pages` branch. Here I've kept one commit on the `gh-pages` branch to keep links working. I'm closing this now but please reopen if you find problems with broken links etc.
