### ISSUE TITLE
`--hpx:use-process-mask` option throw an exception on OS X

### ISSUE THREAD

**Issue by albestro** [STEllAR-GROUP/hpx#4349]
## Expected Behavior

I'm aware of the impossibility to do CPU binding on OS X, but usually requesting a binding on this kind of platform does not result in an error.

## Actual Behavior

The following exception is thrown
`hpx::init: hpx::exception caught: hwloc_get_cpubind failed: HPX(kernel_error)`

## Steps to Reproduce the Problem

Specifying the `--hpx:use-process-mask` option results in the exception.

No special code is needed to test it, even just the following one is enough:
```cpp
#include <hpx/hpx_init.hpp>

int hpx_main(int argc, char **argv) {
  return hpx::finalize();
}

int main(int argc, char **argv) {
  auto ret_code = hpx::init(hpx_main, argc, argv);

  return ret_code;
}
```

## Specifications

  - HPX Version: 1.4.0
  - Platform (compiler, OS): clang on OSX

**Comment by msimberg** [comment]
Thanks @albestro. This should simply be disabled on macOS. Would you even prefer a warning or error (proper error message, not an hwloc error message) if `--hpx:use-process-mask` is given on macOS?

**Comment by albestro** [comment]
I think it would be preferable to have neither error nor warning message as other binding options do.

**Comment by biddisco** [comment]
not even something like "Warning: thread binding not available on platform <xxx>"

**Comment by albestro** [comment]
I agree with you that it would be nice, but I'm not sure that it is the common rule for other options not supported in HPX.

In general, I would say that we should get a coherent behavior, otherwise if an option prints a warning message and others don't, I may suppose that the other ones are supported.

**Comment by biddisco** [comment]
I would suggest that all the `hpx:bind` related operations report a message of the kind "Warning: Thread binding is not supported on platform \<xxx\>, binding options have been ignored"
(A single message for all in that category to keep it simple).
