### ISSUE TITLE
Rewrite history to remove unneeded binary files

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4367]

**Comment by hkaiser** [comment]
Wouldn't this invalidate all links to specific commits etc.?

**Comment by msimberg** [comment]
It would, which is why we're definitely not doing it right now. This is very much a destructive operation but something we should at least consider for a potential 2.0.0 release.

**Comment by hkaiser** [comment]
> It would, which is why we're definitely not doing it right now. This is very much a destructive operation but something we should at least consider for a potential 2.0.0 release.

Wouldn't all older tickets here point into nowhere in this case as well? Frankly, I'm not sure if this is worth the trouble.

**Comment by biddisco** [comment]
> 
> 
> > It would, which is why we're definitely not doing it right now. This is very much a destructive operation but something we should at least consider for a potential 2.0.0 release.
> 
> Wouldn't all older tickets here point into nowhere in this case as well? Frankly, I'm not sure if this is worth the trouble.

Good point. I hadn't thought about the github issues and suchlike.
