### ISSUE TITLE
Missing headers in release tags

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#4394]
Many header files are missing from the recent tags (1.4.0, 1.4.1-rc1, etc.). For instance `https://github.com/STEllAR-GROUP/hpx/tree/master/libs/execution/include_compatibility/hpx` is missing from 1.4.0 (see: https://github.com/STEllAR-GROUP/hpx/tree/1.4.0/libs/execution).

@msimberg: I don't know how this can happen in the first place but this should be fixed before the point release.

**Comment by msimberg** [comment]
@hkaiser are you sure they're actually needed? If I remember correctly we just didn't move them yet at that point because we expected them to move around a few times. Are there others that seem to be missing?

**Comment by hkaiser** [comment]
@msimberg well, they have to be in the release, no? I'm not sure if others are missing.

**Comment by msimberg** [comment]
My point is that if they're not actually moved (they did of course move to the module, but the include paths stayed the same) there's no need for compatibility headers (in the release). I'll check that the paths are actually unchanged though.

**Comment by hkaiser** [comment]
The include compatibility headers for the execution module were added back in November, shouldn't they be part of the V1.4.x release?

**Comment by hkaiser** [comment]
Those header files forward for instance `<hpx/parallel/executor/parallel_executor.hpp>` to `<hpx/execution/executor/parallel_executor.hpp>`. Any application that is using `<hpx/parallel/executor/parallel_executor.hpp>` would break without them.

**Comment by msimberg** [comment]
https://github.com/STEllAR-GROUP/hpx/pull/4247 does indeed have commits from November but it wasn't merged until after the 1.4.0 release (Jan 17).

**Comment by hkaiser** [comment]
Ok, I start to understand what's going on. Thanks for the explanations. I'll close this for now.
