### ISSUE TITLE
transform_compute_cuda test broken

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#4406]
According to this plot, the test started failing at the end of january. It passed the master build on jan 30th, but failed on feb 1st

Could I ask people to check their contributions that were merged around this time to see if one of them might be responsible.

![image](https://user-images.githubusercontent.com/941548/75248716-f860d400-57d4-11ea-896d-85c7f1b6cdeb.png)

**Comment by msimberg** [comment]
I suspect the Piz Daint update, and not a commit on our side.
