### ISSUE TITLE
Performance degradation observer while upgrading from 1.3.0 to 1.4.0/1.4.1

### ISSUE THREAD

**Issue by venartas** [STEllAR-GROUP/hpx#4410]
## Expected Behavior

No performance degradation while upgrading HPX

## Actual Behavior

About 10% overall application performance slowdown observed after an upgrade. It was observed that the number of minor page faults increased by order of magnitude (10-20x) that is probably caused by false sharing problem. 
Different versions of gcc compiler (6.2/9.2), c++ standard 14/17 and different compiler clang were tried. All resulting in the same performance degradation. 
Also, principal data structures were alligned using c++ alignas with no effect on performance. 

## Specifications
[hpx_1.3.0_version_gcc_6.2.txt](https://github.com/STEllAR-GROUP/hpx/files/4261836/hpx_1.3.0_version_gcc_6.2.txt)
[hpx_1.3.0_info_gcc_6.2.txt](https://github.com/STEllAR-GROUP/hpx/files/4261842/hpx_1.3.0_info_gcc_6.2.txt)
[hpx_1.4.1_info_gcc_6.2.txt](https://github.com/STEllAR-GROUP/hpx/files/4261837/hpx_1.4.1_info_gcc_6.2.txt)
[hpx_1.4.1_info_gcc_9.2.txt](https://github.com/STEllAR-GROUP/hpx/files/4261838/hpx_1.4.1_info_gcc_9.2.txt)
[hpx_1.4.1_version_gcc_6.2.txt](https://github.com/STEllAR-GROUP/hpx/files/4261840/hpx_1.4.1_version_gcc_6.2.txt)
[hpx_1.4.1_version_gcc_9.2.txt](https://github.com/STEllAR-GROUP/hpx/files/4261841/hpx_1.4.1_version_gcc_9.2.txt)

... Please describe your environment

  - HPX Version: 1.4.0
  - Platform (compiler, OS): Ubuntu 16.04, gcc 6.2, c++14

**Comment by hkaiser** [comment]
@venartas Thanks for reporting this! Since we have no way of testing against your application, would you be able to do a git bisect to pinpoint the changes causing the issue? 

I know this is asking a lot. However, since there are not more than a couple of hundred commits since V1.3 this should not take more than a handful of recompilation attempts. Any help you could give would be highly appreciated.

**Comment by biddisco** [comment]
Looking at some of the test timings on the dashboard, I'd probably want to look around the start of Feb for a possible change. I seem to recall that I posted another image a few days ago indicating that a cuda test started failing around that time. The only commit that looked to me like it might be responsible was a merge of @K-ballo 's tuple changes I think - but I only briefly skimmed the commits.

![image](https://user-images.githubusercontent.com/941548/75457327-a6f34900-597c-11ea-9503-fb55d3f1e6f0.png)

**Comment by biddisco** [comment]
Note that our system went down for maintenance on 29/01/2020 and was offline for a few days - and so the change in performance on the plot above might be due to a system update/upgrade.

**Comment by venartas** [comment]
some hints about our app:
- **single node** app (build with networking ON)
- hpx parallel looping constructs: **for_each**, **transform** and **reduce** using **auto_chunk_size**; **transform_reduce** and **reduce** using **seq** policy
- **futures** with **wait_all**
- some asynchronous operations using **futures** invokes **nested parallelism** (loop constructs mentioned above)
- parallel synchronisation: **spinlock**

some Intel vtune profiling results (csv) for hpx 1.3.0 & 1.4.1:
[intel_vtune_profiling_results.zip](https://github.com/STEllAR-GROUP/hpx/files/4268317/intel_vtune_profiling_results.zip)

**Comment by venartas** [comment]
Hi @hkaiser, the "guilty" commit is 336b57d - "Merge pull request #4119 from STEllAR-GROUP/fixing_411"

**Comment by hkaiser** [comment]
@venartas Thank you for investing the time to find out. I will definitely have a look to see what we can do to rectify things.

**Comment by hkaiser** [comment]
@venartas what parallel algorithms is your application using?

**Comment by venartas** [comment]
@hkaiser **for_each**, **transform** and **reduce** using **auto_chunk_size** with **par** policy  that consist around 90% parallelism in our app and remainder is **futures** with **wait_all** that can invoke nested parallelism using mentioned parallel loops. Maybe some information can be infered from attached vtune profiling info?

**Comment by venartas** [comment]
@hkaiser tested with **dynamic_chunk_size** (instead of **auto_chunk_size**) using **par** and number of minor page errors dropped back to normal (7-8x less), so performance degrades only if **auto_chunk_size** is used.

**Comment by hkaiser** [comment]
From the information you gave us and the commit you identified to cause your issues, I think that only the `reduce` algorithm performance has decreased as the commit in question does not impact the others.

Now, `auto_chunk_size` is a policy that runs about 1% of the iterations sequentially before deciding on how to chunk up the algorithm's work (we have lately added ways of controlling the number of iterations to execute before making the decision, but that's after V1.4.1 only). I can see how this doesn't work well with `reduce`. 

For now as a workaround, I would suggest for you to use `static_chunk_size` (i.e. the default) for the `reduce` algorithm. The issue itself will need some detailed investigation. I'm not sure how long it may take to come up with a proper solution, however.

**Comment by msimberg** [comment]
@venartas have you had a chance to check the performance on 1.5.X? Does the performance degradation still only happen with `auto_chunk_size`?

**Comment by venartas** [comment]
@msimberg Tried with HPX1.5.1; Ubuntu 18.04.5 LTS; clang 9.0.0; c++17; boost-1.71.0.  No performance degradation is observed anymore.

**Comment by msimberg** [comment]
> @msimberg Tried with HPX1.5.1; Ubuntu 18.04.5 LTS; clang 9.0.0; c++17; boost-1.71.0. No performance degradation is observed anymore.

Thanks @venartas for reporting back. That's very good to hear! I'll close this issue in that case.
