### ISSUE TITLE
Add serialization support for std::variant and std::tuple

### ISSUE THREAD

**Issue by McKillroy** [STEllAR-GROUP/hpx#4416]
Feature request for completion and I actually need it:
Please add official HPX serialization support for std::variant and std::tuple

**Comment by hkaiser** [comment]
@McKillroy I'm not sure is this really should be part of the library itself as these data types are not use by HPX. But we could easily create those utilities and upload them somewhere. What do others think?

**Comment by McKillroy** [comment]
I think standard, non-exotic types should be supported as much as you can afford it. 
I consider HPX a possible quasi standard for distributed parallel computing with C++. 
I'm not aware of any other library which is that standard compliant, easy to use 
(though I'm choking every other day, but that's due to me being still a n00b) and 
really addressing the underlying problems you hit in writing parallel applications.
Because of that, I think HPX should behave as if it were a part of the standard library 
and that implies support for all standard types, even in infrastructure subsystems like serialization.
