### ISSUE TITLE
Function descriptions not supported in distributed

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#4429]
## Expected Behavior

When using HPX with APEX, typically function descriptions are used to hold annotate_function() annotated_function() and action descriptions.  

## Actual Behavior

When executing in distributed mode, only locality 0 has valid thread descriptions, and tasks aren't annotated correctly.  Most end up as `<unknown>`.

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1.  Configure HPX for distributed execution, and with APEX enabled
  1.  Run a distributed example (any will do), with the environment variable APEX_CSV_OUTPUT=1
  1.  At the end of execution, apex.0.csv will have accurate results, but apex.1.csv will not

## Specifications

... Please describe your environment

  - HPX Version:  current master
  - Platform (compiler, OS):  all

**Comment by khuck** [comment]
@hkaiser @biddisco FYI

**Comment by hkaiser** [comment]
I think this has been resolved by #4257. Please reopen if necessary.
