### ISSUE TITLE
[macOS] Execution fails with: client_base has no valid shared state

### ISSUE THREAD

**Issue by brakmic** [STEllAR-GROUP/hpx#4471]
## Expected Behavior

Want to compile & run hello_world.cpp on macOS Catalina 10.15.4

## Actual Behavior

After a successful compilation of hello_world (without any warnings) the execution fails with:
```shell
libc++abi.dylib: terminating with uncaught exception of type hpx::detail::exception_with_info<hpx::exception>: this client_base has no valid shared state: HPX(no_state)
fish: './hello_world' terminated by signal SIGABRT (Abort)
```
## Steps to Reproduce the Problem

1. Clone & install HPX by following the [tutorial](https://stellar-group.github.io/hpx-docs/latest/html/manual/building_hpx.html#how-to-install-hpx-on-os-x-mac).
2. Try to compile the [hello-world-code](https://stellar-group.github.io/hpx-docs/latest/html/manual/creating_hpx_projects.html) from the tutorial.
3. Use following settings (your paths will be different):

```shell
clang+ -o hello_world hello_world.cpp -DHPX_APPLICATION_NAME=hello_world -I/Users/brakmic/hpx/include -I/usr/local/include -I/usr/local/opt/hwloc/include -L$HOME/hpx/lib -L/usr/local/lib -lhpx -lhpx_iostreams
```

## Specifications

  - HPX Version: current HEAD 9e5e05cb2754b704ecd542b5c31adbbbf7e47313 
  - Platform (compiler, OS): AppleClang 11.0.3.11030032, macOS Catalina 10.15.4, hwloc 2.1.0

**Comment by msimberg** [comment]
@brakmic would you be able to try the latest master? Also, if you're able to get a longer stacktrace with gdb/lldb that could also be helpful.
