### ISSUE TITLE
Add vcpkg installation instructions

### ISSUE THREAD

**Issue by NancyLi1013** [STEllAR-GROUP/hpx#4473]
`hpx `is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `hpx `and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `hpx `, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.
Note: Currently only support dynamic build on Windows.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/hpx/portfile.cmake). We try to keep the library maintained as close as possible to the original library.

I'm trying to add vcpkg installation instructions but I couldn't find the related docs in code item except for on `Wiki `page.

Could you please help add the following contents to this port?

```
Installing and building hpx via vcpkg

You can download and install hpx using the [vcpkg](https://github.com/Microsoft/vcpkg) dependency manager:

      git clone https://github.com/Microsoft/vcpkg.git
      cd vcpkg
      ./bootstrap-vcpkg.sh
      ./vcpkg integrate install
      vcpkg install hpx

The hpx port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg) on the vcpkg repository.
```
The similar pull request like this lz4/lz4#825.

Thanks,
Nancy

**Comment by hkaiser** [comment]
@NancyLi1013 I think the documentation snippet you have in mind could be added to https://github.com/STEllAR-GROUP/hpx/blob/master/docs/sphinx/quickstart.rst in the 'Building HPX' section.

**Comment by NancyLi1013** [comment]
Hi @hkaiser 
Thanks for your suggestions.
I will try to add it later.

**Comment by NancyLi1013** [comment]
@hkaiser 
I submitted the PR #4481 to add this.
Could you please help review this PR?

**Comment by NancyLi1013** [comment]
Since the instructions have been added to the document.
I close this issue now.
Thanks again for your help and support.

**Comment by hkaiser** [comment]
@NancyLi1013 thanks again for your contribution!
