### ISSUE TITLE
Include only top-level module headers

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4488]
I think this is something we should do at least in examples, and probably tests. Internally I don't think it matters too much. This can happen once all modules are in place of course. Making the top-level module headers the "public" set of includes (we can't stop users from including other files...) protects users at least a bit from internal reshuffling in modules. The potential downside is increased compile times for users.

**Comment by hkaiser** [comment]
Here is a (possibly incomplete list):
- [ ] `hpx/algorithm.hpp`
- [ ] `hpx/any.hpp`
- [ ] `hpx/barrier.hpp`
- [ ] `hpx/chrono.hpp`
- [ ] `hpx/condition_variable.hpp`
- [ ] `hpx/exception.hpp`
- [ ] `hpx/execution.hpp`
- [ ] `hpx/future.hpp`
- [ ] `hpx/iostream.hpp`
- [ ] `hpx/latch.hpp`
- [ ] `hpx/memory.hpp`
- [ ] `hpx/mutex.hpp`
- [ ] `hpx/numeric.hpp`
- [ ] `hpx/optional.hpp`
- [ ] `hpx/semaphore.hpp`
- [ ] `hpx/shared_mutex.hpp`
- [ ] `hpx/system_error.hpp`
- [ ] `hpx/thread.hpp`
- [ ] `hpx/tuple.hpp`

**Comment by aurianer** [comment]
For now, I just did a script that is replacing the specific modules headers by the respective main header, but some of the headers you listed above are not in the list of module names and threrefore are not replaced for now.
@hkaiser how did you built this list ? To know if there is a logic behind or if I have to do those changes manually

**Comment by hkaiser** [comment]
> how did you built this list ? To know if there is a logic behind or if I have to do those changes manually

I went through the standard and listed all that have corresponding headers making sense in our context.

**Comment by msimberg** [comment]
I've been doing this on tests/examples that I touch otherwise, but not at a larger scale. I still think it's a good thing to do, especially in examples, to show users which headers are recommended to include. Internally we've definitely moved back from including module headers more specific headers.
