### ISSUE TITLE
Polymorphic executor

### ISSUE THREAD

**Issue by teonnik** [STEllAR-GROUP/hpx#4489]
I'm using two different executors `hpx::mpi::executor` (from John's branch) and `hpx::threads::executors::pool_executor` in my code. It would be great if I could toggle between the two dynamically. In other words, I'm looking for a `std::function` equivalent for executors.

Another use of a polymorphic executor for me is to reduce compile times. A function accepting a single polymorphic executor can be (potentially) instantiated only once instead of multiple times with different executor types.

**Comment by hkaiser** [comment]
@teonnik The issue with adding a polymorphic executor is that you 

- either would have to know the signature of the function(s) you plan to schedule using the executor ahead of time
- or limit the polymorphic executor to be non-variadic (i.e. scheduling nullary functions only)

The first might be inconvenient (if you have more than one function signature), the second is quite limiting and makes user code unnecessarily complex. Which of the options would you prefer?

**Comment by teonnik** [comment]
> either would have to know the signature of the function(s) you plan to schedule using the executor ahead of time

If I understand things correctly, this will essentially give me the same control `std::function` gives me: I have know the signature ahead of time. I'd be happy with that option.

**Comment by hkaiser** [comment]
> If  I understand things correctly, std::function already requires that I know the signature of the function ahead of time, so that won't be too much of an issue for me. I'd be happy with that option.

@teonnik yes, if you have just functions of one single signature, then the result would be equivalent to `std::function`. However we might want to cover the cases where the user has more than one single signature. But I guess in that case the user could fall back to a polymorphic executor that supports nullary functions, i.e. something like `polymorphic_executor<void()>` and handle the arguments (and the return type) himself.

I don't think implementing such an executor would be hard. Not sure when I'd be able to get to it, however.

**Comment by hkaiser** [comment]
@teonnik I have started to implement this in #4514, please try things out and comment
