### ISSUE TITLE
Add anchor links to table rows in documentation

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4495]
Try to add anchor links to table rows in documentation (specifically for performance counters, to allow linking to specific counters).

Just opening this as a reminder for myself. Someone knowledgable in sphinx and restructuredtext can feel free to do it as well.

**Comment by msimberg** [comment]
@hkaiser it look like the only built-in way to get those little chain anchors (the ones that pop up next to headings) is on headings, tables, and figures. Just plain anchors are possible to insert anywhere (with `.. _anchor_name:`, like for headings). There at least three options:

1. Just add plain anchors. If one wants to link to a specific table row one has to know the anchor name and append it to the url.
2. (Ab?)use headings. Make each performance counter a subsection, and rearrange the counter information so it's not in a table (the tables never really formatted very well because of the wide content in some of the columns). This gives the nicest usability, but maybe won't look as pretty.
3. Go diving in the guts of sphinx and try to add a way to have both the anchor link and a clickable link show up in the table row. I'm pretty sure this is doable with extensions (like we do with e.g. cppreference links; those are custom roles), but I wouldn't know how to do it right now.

**Comment by hkaiser** [comment]
@msimberg have you seen this: https://stackoverflow.com/a/30989921/269943?

**Comment by msimberg** [comment]
> @msimberg have you seen this: https://stackoverflow.com/a/30989921/269943?

Yep, that's essentially 1. on the list above, and now that you link to it I see it in a completely different light :D (custom anchors and `:ref` is what we use for all other internal links...) so I present to you:

4. Just add plain anchors and add a link to the anchor right after the anchor. Without more sphinx-fu it would involve quite a lot of duplication (first declaring the anchor and then linking to the anchor with the same name), but it's doable. I'll leave it to you to decide what to put in the text (I guess it could be any unicode, so the same chain icon that's on the headings would probably work; it just wouldn't hide itself).

**Comment by NinaPacifier** [comment]
@msimberg  I am new to open-source contribution. Can I work on this issue??

**Comment by hkaiser** [comment]
> @msimberg I am new to open-source contribution. Can I work on this issue??

Absolutely, please go ahead! Thanks!

**Comment by CH-ND-N** [comment]
@msimberg I am interested to work on this issue. please assig this to me.

**Comment by shahwezahmad** [comment]
@hkaiser  @msimberg   i  want work in this issue please assign me 
i  am newbie in open source contribution

**Comment by msimberg** [comment]
@CH-ND-N I'm assuming you're not actively working on this at the moment? @shahwezahmad please feel free to just work on this even without me assigning you to it, I don't think anyone else is working on this right now. Let us know on IRC if you need any help with it.

**Comment by shahwezahmad** [comment]
I am new in open source field

**Comment by shahwezahmad** [comment]
ok thankyou

**Comment by PratyushD35** [comment]
@msimberg  I want to work on this and also I am new to this . Please guide.

**Comment by aurianer** [comment]
@PratyushD35 I think you can start by building the documentation using CMake with [those options](https://github.com/STEllAR-GROUP/hpx/blob/master/.circleci/config.yml#L228-L229) (see [building documentation](https://hpx-docs.stellar-group.org/branches/master/html/contributing/documentation.html#building-documentation)) and then join our [libera.chat channel](https://matrix.to/#/#ste||ar:libera.chat) to ask questions if you encounter any problems ;)
