### ISSUE TITLE
User-polling introduced by MPI futures module should be more generally usable

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#4507]
Currently, the MPI futures module introduces a global user-polling function that is being invoked from the scheduler. This works as long as no other code sets such a function. We should find a better way of injecting user code into the scheduler loop.

**Comment by msimberg** [comment]
I'd say this is fixed, at least for the original intent of having both MPI and CUDA polling enabled at the same time. @biddisco, @hkaiser would you still like to keep this open?

**Comment by hkaiser** [comment]
> I'd say this is fixed, at least for the original intent of having both MPI and CUDA polling enabled at the same time. @biddisco, @hkaiser would you still like to keep this open?

I'm fine with closing this unless proven to be broken...
