### ISSUE TITLE
Deprecate HPX_WITH_DEFAULT_TARGETS

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4509]
I'm trying to understand the purpose of `HPX_WITH_DEFAULT_TARGETS`. If `HPX_WITH_DEFAULT_TARGETS` is `OFF` nothing gets built with e.g. plain `make` or `make all` (unless I've missed some target that is unconditionally built). What was the original use case for this option? Is it still valid? Does it have something to do with Visual Studio?

**Comment by hkaiser** [comment]
@msimberg I don't remember, sorry. It has nothing to do with Visual Studio, however.

**Comment by msimberg** [comment]
This was already removed.
