### ISSUE TITLE
HPXConfig.cmake contains ill-formed paths when library paths use backslashes

### ISSUE THREAD

**Issue by zao** [STEllAR-GROUP/hpx#4513]
## Expected Behavior

`find_package(HPX REQUIRED)` should work.

## Actual Behavior

`HPXConfig.cmake` contains statements like `set(HPX_HWLOC_ROOT "C:\local\hwloc-win64-build-2.1.0")` resulting in the following when used:
```
1> [CMake] CMake Error at C:/stellar/inst-hpx-stable-release/lib/cmake/HPX/HPXConfig.cmake:79 (set):
1> [CMake]   Syntax error in cmake code at
1> [CMake] 
1> [CMake]     C:/stellar/inst-hpx-stable-release/lib/cmake/HPX/HPXConfig.cmake:79
1> [CMake] 
1> [CMake]   when parsing string
1> [CMake] 
1> [CMake]     C:\local\hwloc-win64-build-2.1.0
1> [CMake] 
1> [CMake]   Invalid character escape '\l'.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:8 (find_package)
```

## Steps to Reproduce the Problem

  1. Build HPX with a command line like `cmake ..\hpx -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_INSTALL_PREFIX=C:\stellar\inst-hpx-stable-release -DHWLOC_ROOT=C:\local\hwloc-win64-build-2.1.0 -DHPX_WITH_TESTS=OFF -DHPX_WITH_EXAMPLES=OFF`
  1. Use `find_package(HPX REQUIRED)` in a project.
  1. Run `cmake ..\demo-hpx -G "Visual Studio 16 2019" -A x64 -DHPX_ROOT=C:\stellar\inst-hpx-stable-release`

## Specifications

... Please describe your environment

  - HPX Version: stable tag (e7090becdafd73ebcea5bc010976676188d1ffac)
  - Platform (compiler, OS): Windows 10, VS 2019 x64 command prompt, CMake 3.17.0

**Comment by aurianer** [comment]
Just a question about this issue, I'm wondering about the developers who use Windows linux subsystem, if we simply replace the backslashes by slashes, it would conflict with this other prompt I believe

**Comment by aurianer** [comment]
Is this working for you @zao ? Let's see if the platform variable I used is the right one
