### ISSUE TITLE
Test for counting_iterator fails for seed `1586836359`

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#4517]
See: https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/2928/workflows/7513cc05-cd89-4d95-89db-cf3527989d00/jobs/178631

**Comment by msimberg** [comment]
I don't believe this has been explicitly fixed, but I also haven't seen this fail again. @hkaiser do you still see this every now and then?

**Comment by hkaiser** [comment]
> I don't believe this has been explicitly fixed, but I also haven't seen this fail again. @hkaiser do you still see this every now and then?

I have not seen it again. However, since the test relies on the random seed to generate the data, it's highly unlikely for it to be run using the same seed.

**Comment by msimberg** [comment]
> > I don't believe this has been explicitly fixed, but I also haven't seen this fail again. @hkaiser do you still see this every now and then?
> 
> I have not seen it again. However, since the test relies on the random seed to generate the data, it's highly unlikely for it to be run using the same seed.

That's a very good point, didn't think about that. Let's keep this open then. I'll see if I can reproduce this with the same seed.
