### ISSUE TITLE
Build of PR #4311 (git tag 9955e8e) fails

### ISSUE THREAD

**Issue by kordejong** [STEllAR-GROUP/hpx#4523]
## Expected Behavior

Build succeeds.

## Actual Behavior

Build fails.

```
/tmp/hello_hpx/Debug-default/build/_deps/hpx-src/libs/version/src/version.cpp:11:10: fatal error: hpx/config/config_strings.hpp: No such file or directory
 #include <hpx/config/config_strings.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                        
compilation terminated.
```

## Steps to Reproduce the Problem

  1. `git clone https://github.com/kordejong/hello_hpx.git`
  1. `cd hello_hpx`
  1. `bash ./debug_build.sh`

## Specifications

... Please describe your environment

  - HPX Version: 1.4.1 + APEX fixes
  - Platform (compiler, OS): gcc-7, Kubuntu 18.04

**Comment by kordejong** [comment]
Full build output: [debug_build.txt](https://github.com/STEllAR-GROUP/hpx/files/4481723/debug_build.txt)

The build of HPX is triggered by CMake's FetchContent (see bottom of hello_hpx's CMakeLists.txt).

**Comment by msimberg** [comment]
I'm guessing this has to do with some include path being relative to your root build directory rather than HPX's root directory. I'll try to to look at this later this week. In the meantime, would you mind triggering a build without `FetchContent`? That would help us determine if it's really a problem with that particular setup or a general problem.

**Comment by kordejong** [comment]
A build without `FetchContent` succeeds.

**Comment by kordejong** [comment]
Oops, correction. I used the wrong commit for the previous build. Commit #9955e8e actually fails. I am attaching the log.
[classic_build.txt](https://github.com/STEllAR-GROUP/hpx/files/4484978/classic_build.txt)

**Comment by kordejong** [comment]
Building this commit from the command line fails for a different reason (C++ logic) than building this commit using CMake's `FetchContent` (CMake logic).

**Comment by msimberg** [comment]
Thanks @kordejong, that failure with the "normal" build is expected (it's what's still keeping that PR from going in). Building your fetchcontent repo now...
