### ISSUE TITLE
API for checking if pool with a given name exists

### ISSUE THREAD

**Issue by teonnik** [STEllAR-GROUP/hpx#4535]
Currently we have this in our code to check if a pool with a given name exists:

```
  hpx::threads::scheduled_executor executor_mpi;
  try {
    executor_mpi = pool_executor("mpi", hpx::threads::thread_priority_high);
  }
  catch (...) {
    executor_mpi = pool_executor("default", hpx::threads::thread_priority_high);
  }
```
Since v1.5, `scheduled_executor` is no longer a base class for `pool_executor` so the above doesn't work. We are unable to replace `pool_executor` with `scheduled_executor` above because `pool_executor` doesn't have a default constructor.

Would it be possible to implement an API to query whether a pool with a given name exists? The existing exceptions mechanism will not work for us.

**Comment by msimberg** [comment]
We can add both by the way: an API to check if the pool exists, and a default constructor for `pool_executor`.

For the record, `thread_pool_executor` is the base class for `pool_executor`. The former takes a `thread_pool_base` and the latter takes a thread pool name (it's just a convenience wrapper around the former). `thread_pool_base` does have a default constructor.
