### ISSUE TITLE
Move thread creation parameters into a struct

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4542]
This is about all the overloads of `register_thread`, `futures_factory`, `async_launch_policy_dispatch` etc. that take among other things a scheduling hint, priority, and stack size. This new struct is not quite `thread_init_data` because we do the conversion from any function to the thread function type, as well as converting an enum stack size to the real stack size. We could perhaps merge `thread_init_data` and this new struct.

I've already started some of this cleanup but wanted to open this issue to see if others have objections or better ideas. I would like to use this new struct everywhere and remove the overloads taking individual arguments. In my opinion the only overloads that might deserve a compatibility option are the `register_thread` overloads.

**Comment by hkaiser** [comment]
@msimberg yes, let's merge the structures.
