### ISSUE TITLE
Less verbose exception output

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4546]
I'm frequently frustrated by the hundreds of lines of output that happens when an exception occurs and the list of environment variables is long (typical in a slurm/easybuild environment). Does anyone else find this annoying?

I think we could do one of two things:
1. Add an "exception verbosity" configuration option, which would default to the current behaviour. Then I could just stick an `hpx.ini` file into my home directory with a lower verbosity.
2. Remove the environment variables and configuration options from the exception output, and add a command line option to print the configuration (just like `--hpx:version` and `--hpx:dump-config`). The environment variables one can anyway get with `env`. We could then recommend in the issue template that people provide the output of `--hpx:version`, `--hpx:dump-config`, `--hpx:dump-the-the-other-config`, and `env`.

Thoughts?

**Comment by hkaiser** [comment]
@msimberg The initial rationale behind having all that information in the exception output was to have as much of the environmental information available in cases of sudden and unexpected failures (which are mostly non-reproducible). I would agree to generally reduce this along the lines of what you are suggesting, however I would like to have an option controlling that behavior. In CI environments the printed information has helped me many times to narrow down the issue.

**Comment by msimberg** [comment]
Yep, perfectly understandable. I was thinking of the second option for cases where it's easy enough to collect all that information after the fact manually, but the first option would allow exactly your use case. Whether we change the default verbosity is another question (we can easily make it verbose in CI). I'm happy if I have a knob to turn down the verbosity for myself though. I'll have a go at adding an option for this.

**Comment by msimberg** [comment]
Fixed by #4552.
