### ISSUE TITLE
hpx_wrap not found

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/hpx#4556]
## Expected Behavior

Get my application complies and link correctly

## Actual Behavior
```
[100%] Linking CXX executable main_dca
/usr/bin/ld: cannot find -lhpx_wrap
collect2: error: ld returned 1 exit status
make[2]: *** [applications/dca/main_dca] Error 1
make[1]: *** [applications/dca/CMakeFiles/main_dca.dir/all] Error 2
make: *** [all] Error 2
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. trying branch fixing_4539
  2. CMake:
 ```
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE                                      \
            -DHPX_WITH_GENERIC_CONTEXT_COROUTINES=OFF                           \
            -DBOOST_ROOT=$BOOST_PATH                                            \
            -DHPX_WITH_CXX17=ON                                                 \
            -DCMAKE_CXX_FLAGS=$CXXFLAGS                                         \
            -DHWLOC_ROOT=$HWLOC_PATH                                            \
            -DJEMALLOC_ROOT=$JEMALLOC_PATH                                      \
            -DHPX_WITH_MALLOC=JEMALLOC                                          \
            -DHPX_WITH_HWLOC=ON                                                 \
            -DHPX_WITH_NETWORKING=OFF                                   \
            -DHPX_MPI_WITH_FUTURES=ON                                           \
            -DHPX_WITH_PARCELPORT_MPI=OFF                                       \
            -DHPX_WITH_PARCELPORT_TCP=OFF                                       \
            -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH                                \
            -DHPX_WITH_EXAMPLES=ON                                         \
            -DHPX_WITH_TOOLS=OFF                                                \
            -DHPX_WITH_TESTS=OFF                                                \
            -DHPX_WITH_TESTS_BENCHMARKS=OFF                             \
            -DHPX_WITH_TESTS_REGRESSIONS=OFF                            \
            -DHPX_WITH_TESTS_UNIT=OFF                                   \
            -DHPX_WITH_MAX_CPU_COUNT=168                                        \
            -DHPX_WITH_CUDA=OFF                                                 \
            -DHPX_WITH_LOGGING=OFF                                              \
            -Wdev                                                               \
```

## Specifications

... Please describe your environment

  - HPX Version:
  - Platform (compiler, OS): gcc/8.1.1, Power9

**Comment by weilewei** [comment]
After adding -DHPX_WITH_DYNAMIC_HPX_MAIN=OFF in HPX cmake still doesn't help, the same error occurs again, unfortunately.. @hkaiser

**Comment by msimberg** [comment]
@weilewei could you show hos you link against HPX in your CMake configuration? Since the mpi branch was merged pretty recently there shouldn't even be a libhpx_wrap.a in your lib directory. Could you check that that's the case?

**Comment by hkaiser** [comment]
> After adding -DHPX_WITH_DYNAMIC_HPX_MAIN=OFF in HPX cmake still doesn't help, the same error occurs again, unfortunately.. @hkaiser . However, one example application with hpx mpi future can be compiled and linked correctly, but not for my main_dca application. Not sure why.

That tells me that -- after we changed HPX's build system -- the way you link DCA++ against HPX does not work anymore. We have to either make it work again (for what we would have to know how you currently link DCA++ - as @msimberg requested), or you will have to change the DCA++ build system to rely on the new CMake targets we expose in the new HPX build system (@msimberg do we have that already somewhere documented?)

**Comment by weilewei** [comment]
@hkaiser @msimberg if I commented out this line where links to hpx_wrap, then main_dca gets compiled. https://github.com/STEllAR-GROUP/DCA/blob/a0ea6a4daf4e029e84f3a085b13d3f37b8782f79/src/parallel/hpx/CMakeLists.txt#L18 I believe for HPX 1.4.1 (available model on Summit) still uses hpx_wrap, but latest branch does not?

**Comment by hkaiser** [comment]
> @hkaiser @msimberg if I commented out this line where links to hpx_wrap, then main_dca gets compiled with HPX branch fixing_4539. https://github.com/STEllAR-GROUP/DCA/blob/a0ea6a4daf4e029e84f3a085b13d3f37b8782f79/src/parallel/hpx/CMakeLists.txt#L18 I believe for HPX 1.4.1 (available model on Summit) still uses hpx_wrap, but latest branch does not?

@weilewei yes, we have changed our build system - a lot! Please just add `HPX::hpx` (and `HPX::hpx_init`) as a dependency to DCA++ (use `target_link_libraries(parallel_hpx HPX::hpx_init HPX::hpx)` for this).

**Comment by hkaiser** [comment]
@weilewei in order for your build system to function with older HPX versions as well, you can check whether the target `HPX::hpx` exists:
```
if(TARGET HPX::hpx)
  target_link_libraries(parallel_hpx HPX::hpx_init HPX::hpx)
else()
  # do whatever you did before
endif()

**Comment by msimberg** [comment]
We have [this](https://stellar-group.github.io/hpx-docs/branches/master/html/manual/creating_hpx_projects.html#using-hpx-targets) which will be in the next release. However, please do *not* link to `HPX::hpx_init` explicitly (I'll change the namespace to make it clear). Linking to `HPX::hpx` is enough.

A bit of context: linking explicitly to `hpx_wrap` was never supported. In 1.4.1 and earlier you could either:
- Link to `HPX_LIBRARIES` for anything that needed HPX functionality, and link to `HPX_LINK_LIBRARIES` for executables that needed HPX functionality.

or

- Use the macros `hpx_setup_target`, `add_hpx_executable`, and `add_hpx_library`. `hpx_setup_target` has to be called with an executable to get it to link to `hpx_wrap`.

With current master and the next release those rules are slightly relaxed, and you can instead link to `HPX::hpx` which will be the recommended way to link to HPX. The two older methods are not immediately going away and will keep working for now.

@weilewei where do you start the HPX runtime in DCA++? It's not clear to me that you would even need to link to `hpx_wrap`.

**Comment by weilewei** [comment]
@msimberg @hkaiser thanks for all the recommendations, which helps me construct a project that uses HPX. @msimberg `hpx_wrap` is written by @biddisco in that CMakeLists.txt, and I wasn't aware of this "advanced functionality :-)" until this break... Yea, anyways, but I will use the correct syntax in the application then, thanks!

**Comment by weilewei** [comment]
After using `target_link_libraries(parallel_hpx PUBLIC HPX::hpx)` and removing `#target_link_libraries(parallel_hpx PRIVATE hpx_wrap)`, the compilation error goes away. This problem seems go away now. Thanks!
