### ISSUE TITLE
Annoying warning when compiling - pls suppress or fix it.

### ISSUE THREAD

**Issue by McKillroy** [STEllAR-GROUP/hpx#4569]
## Expected Behavior

no warning

## Actual Behavior

getting the following warning over and over again:
....  include\hpx\threading\jthread.hpp(258): warning C4267: 'return': conversion from 'size_t' to 'unsigned int', possible loss of data 

## Steps to Reproduce the Problem

compile with MSVC, enabling jemalloc

## Specifications

  - HPX Version: stable : c5b1812e0d414c33a9068d101075e2aab9afeb6d
  - Windows 10, MSVC latest 2019

**Comment by K-ballo** [comment]
https://github.com/STEllAR-GROUP/hpx/blob/2b91d44d2ec5ea05065e51833517056e92512a1e/libs/threading/include/hpx/threading/jthread.hpp#L255-L259

`hpx::threads::hardware_concurrency` ought to return `unsigned int` rather than `std::size_t`.

**Comment by hkaiser** [comment]
@McKillroy please see #4574 for a fix. Thanks!
