### ISSUE TITLE
Add high-level documentation to new modules

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4571]
This is a reminder to go through all the newly added modules and add high-level documentation before the next release.

**Comment by hkaiser** [comment]
Here is the list of current modules for our reference:
 - [ ] affinity
 - [ ] algorithms
 - [ ] allocator_support
 - [ ] asio
 - [ ] assertion
 - [ ] async
 - [ ] async_base
 - [ ] async_combinators
 - [ ] basic_execution
 - [ ] batch_environments
 - [ ] cache
 - [ ] checkpoint
 - [ ] collectives
 - [ ] command_line_handling
 - [ ] compute
 - [ ] compute_cuda
 - [ ] concepts
 - [ ] concurrency
 - [ ] config
 - [ ] coroutines
 - [ ] datastructures
 - [ ] debugging
 - [ ] distributed_executors
 - [ ] errors
 - [ ] execution
 - [ ] filesystem
 - [ ] format
 - [ ] functional
 - [ ] hardware
 - [ ] hashing
 - [ ] include
 - [ ] io_service
 - [ ] iterator_support
 - [ ] local_async
 - [ ] local_lcos
 - [ ] logging
 - [ ] memory
 - [ ] mpi
 - [ ] naming_base
 - [ ] pack_traversal
 - [ ] performance_counters
 - [ ] plugin
 - [ ] prefix
 - [ ] preprocessor
 - [ ] program_options
 - [ ] resiliency
 - [ ] resource_partitioner
 - [ ] runtime_configuration
 - [ ] schedulers
 - [ ] segmented_algorithms
 - [ ] serialization
 - [ ] static_reinit
 - [ ] statistics
 - [ ] string_util
 - [ ] synchronization
 - [ ] testing
 - [ ] thread_executors
 - [ ] thread_pools
 - [ ] thread_support
 - [ ] threading
 - [ ] threading_base
 - [ ] threadmanager
 - [ ] timing
 - [ ] topology
 - [ ] type_support
 - [ ] util
 - [ ] version
