### ISSUE TITLE
Default value for HPX_WITH_THREAD_BACKTRACE_DEPTH

### ISSUE THREAD

**Issue by teonnik** [STEllAR-GROUP/hpx#4578]
In HPX v1.4.1 the default value of `HPX_WITH_THREAD_BACKTRACE_DEPTH` seems to be 5.  @msimberg told me that the new default on master is 20. Would it be possible to bump that to 100 (or some value larger than 20) as 20 might be insufficient in some cases in DLAF?

**Comment by hkaiser** [comment]
We should make this a runtime-configurable value, if possible.

**Comment by msimberg** [comment]
I think we can close this now that #4584 is merged.
