### ISSUE TITLE
Stacktrace does not resolve all function addresses

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4580]
Reported by @teonnik.

The following program:

```
#include <iostream>
#include <hpx/util/backtrace/backtrace.hpp>

void func_1() {
  std::cout << hpx::util::backtrace(10).trace() << '\n';
}

void func_2() {
  func_1();
}

void func_3() {
  func_2();
}

int main(int argc, char** argv) {
  func_3();
}
```

prints this on Linux (HPX 1.4.1, debug mode):

```
0x7f01548e476f  : hpx::util::stack_trace::trace(void**, unsigned long) + 0x1f in /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/clang-9.0.1/hpx-1.4.1-nc2aslhhrq563cbat6lyrlpvo7enfxt7/lib/libhpxd.so.1
0x55b814cfc44b  : hpx::util::backtrace::backtrace(unsigned long) + 0x9b in ./testy
0x55b814cfc2ca  : ??? + 0x55b814cfc2ca in ./testy
0x55b814cfc379  : ??? + 0x55b814cfc379 in ./testy
0x55b814cfc389  : ??? + 0x55b814cfc389 in ./testy
0x55b814cfc3a4  : ??? + 0x55b814cfc3a4 in ./testy
0x7f014bba8023  : __libc_start_main + 0xf3 in /usr/lib/libc.so.6
0x55b814cfc1ce  : ??? + 0x55b814cfc1ce in ./testy
```

I'm also not able to get function names to show up. Does someone else get stacktraces with full information? Does someone remember if this has worked before? It looks like it may only be resolving things from shared libraries.

**Comment by hkaiser** [comment]
This looks like if your application was not built using Debug or the symbols were stripped. Could you check, please?

**Comment by teonnik** [comment]
The application above was built with debug symbols:
```
/usr/bin/clang++  
  -DBOOST_ALL_NO_LIB 
  -DDEBUG -DHPX_DEBUG 
  -DHPX_ENABLE_ASSERT_HANDLER 
  -D_DEBUG 
  -isystem /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/clang-9.0.1/hpx-1.4.1-nc2aslhhrq563cbat6lyrlpvo7enfxt7/include 
  -isystem /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/clang-9.0.1/boost-1.72.0-o7fixw6tzfguvn3mccmlhvi5wopjkdrd/include 
  -isystem /home/teonnik/software/spack/opt/spack/linux-arch-broadwell/clang-9.0.1/hwloc-2.1.0-e6hb3gwsov5stt74v6mo4gmvt2347zsl/include  
  -g   
  -std=c++14 -o CMakeFiles/backtrace.dir/backtrace.cpp.o 
  -c /home/teonnik/code/sandbox/hpx/backtrace.cpp
```

`objdump --syms backtrace | grep debug` outputs:

```
0000000000000000 l    d  .debug_info    0000000000000000              .debug_info
0000000000000000 l    d  .debug_abbrev  0000000000000000              .debug_abbrev
0000000000000000 l    d  .debug_line    0000000000000000              .debug_line
0000000000000000 l    d  .debug_str     0000000000000000              .debug_str
0000000000000000 l    d  .debug_macinfo 0000000000000000              .debug_macinfo
0000000000000000 l    d  .debug_ranges  0000000000000000              .debug_ranges
```

HPX was also built using Debug.

**Comment by msimberg** [comment]
The same happens elsewhere as well apparently, but I never reacted on it: https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/3119/workflows/9220d1a8-f0ec-437b-afe2-49d2c552043f/jobs/183016/steps. Same on pycicle.

**Comment by hkaiser** [comment]
This could be the result of either executing this code:
https://github.com/STEllAR-GROUP/hpx/blob/master/libs/debugging/src/backtrace.cpp#L172
(if `dladdr` fails) or this code:
https://github.com/STEllAR-GROUP/hpx/blob/master/libs/debugging/src/backtrace.cpp#L193
(if libdl returned incomplete information).

From the documentation (http://man7.org/linux/man-pages/man3/dladdr.3.html) one could imply that `dladdr()` only works on shared objects, not on executables. I don't know work around this, if true.

**Comment by hkaiser** [comment]
I found this: https://github.com/att/ast/issues/460#issuecomment-379588389, which explains how to manually walk the symbol table in an ELF executable. Could somebody try this, please? This isn't anything I could easily do on my Windows setup.
