### ISSUE TITLE
Rename modules

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4594]
Choosing `async` as the name for a module was not the best idea (because of potential conflicts between the namespace `hpx::async` and the real `hpx::async`).

I'd rename it `distributed_async`. Other ideas or preferences?

Modules that need to be renamed:

- [x] `local_async` (#4689)
- [x] `async` (#4689)
- [x] `mpi` (#4689)
- [x] `cuda_support` (#4385)
- [x] `local_lcos` (#4740)
- [x] `basic_execution` (#4740)

**Comment by hkaiser** [comment]
In the light of our recent discussion to rename the mpi and cuda future modules to `async_mpi` and `async_cuda` I'd suggest to rename this one to `async_distributed` - even more as we already have `async_local`.

**Comment by msimberg** [comment]
> In the light of our recent discussion to rename the mpi and cuda future modules to `async_mpi` and `async_cuda` I'd suggest to rename this one to `async_distributed` - even more as we already have `async_local`.

Good point. It is `local_async` at the moment though, so I'll rename that one as well. I can go and rename all of them once we have the CUDA PR in as well. Were there others (`async_base`, `async_local`, `async_distributed`, `async_mpi`, and `async_cuda`)?

**Comment by hkaiser** [comment]
@msimberg thanks. In the end it does not matter how we name the modules. It would be (slightly) preferable to name them consistently, however.

**Comment by msimberg** [comment]
All the renamings have been done.
