### ISSUE TITLE
Fully document hpx_wrap behaviour and targets

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4619]
Before I forget:

- Document all three targets `HPX::hpx`, `HPX::hpx_no_wrap_main`, and `HPX::wrap_main`
- Add troubleshooting entry for the common error messages resulting from not using the targets above correctly

**Comment by hkaiser** [comment]
> Add troubleshooting entry for the common error messages resulting from not using the targets above correctly

Are there ways to diagnose problems at configuration time?

**Comment by msimberg** [comment]
> > Add troubleshooting entry for the common error messages resulting from not using the targets above correctly
> 
> Are there ways to diagnose problems at configuration time?

I don't think so but will add it if I come up with something. Most likely having a way to do that implies having a way to do the linking correctly in the first place, in which case we don't need the troubleshooting section for that.
