### ISSUE TITLE
compatibility headers are not very useful

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#4637]
Going through some of my older projects and updating them to work with hpx master gives messages/errors such as these

```
In file included from /home/biddisco/src/martycam/capturethread.h:15,
                 from /home/biddisco/src/martycam/capturethread.cpp:1:
/home/biddisco/src/hpx/libs/execution/include_compatibility/hpx/parallel/execution.hpp:18:2: warning: #warning "The header hpx/parallel/execution.hpp is deprecated,     please include hpx/execution/execution.hpp instead" [-Wcpp]
   18 | #warning "The header hpx/parallel/execution.hpp is deprecated, \
      |  ^~~~~~~
In file included from /home/biddisco/src/martycam/capturethread.h:16,
                 from /home/biddisco/src/martycam/capturethread.cpp:1:
/home/biddisco/src/hpx/libs/executors/include_compatibility/hpx/parallel/executors/pool_executor.hpp:19:2: warning: #warning "The header hpx/parallel/executors/pool_executor.hpp is deprecated,     please include hpx/executors/pool_executor.hpp instead" [-Wcpp]
   19 | #warning "The header hpx/parallel/executors/pool_executor.hpp is deprecated, \
      |  ^~~~~~~
In file included from /home/biddisco/src/martycam/capturethread.cpp:1:
/home/biddisco/src/martycam/capturethread.h:32:32: error: ‘hpx::threads::executors’ has not been declared
   32 |                  hpx::threads::executors::pool_executor exec,
      |                                ^~~~~~~~~
/home/biddisco/src/martycam/capturethread.h:99:17: error: ‘executors’ in namespace ‘hpx::threads’ does not name a type; did you mean ‘executor’?
   99 |   hpx::threads::executors::pool_executor executor;
      |                 ^~~~~~~~~
      |                 executor
/home/biddisco/src/martycam/capturethread.cpp:59:44: error: ‘hpx::threads::executors’ has not been declared
   59 |                              hpx::threads::executors::pool_executor exec,
```
It's nice that the warning tells me that `hpx/parallel/executors/pool_executor.hpp` is deprecated, but even if I fix this, I still get
```
/home/biddisco/src/martycam/capturethread.h:32:32: error: ‘hpx::threads::executors’ has not been declared
   32 |                  hpx::threads::executors::pool_executor exec,
      |                                ^~~~~~~~~
/home/biddisco/src/martycam/capturethread.h:99:17: error: ‘executors’ in namespace ‘hpx::threads’ does not name a type; did you mean ‘executor’?
   99 |   hpx::threads::executors::pool_executor executor;
```
and I have to grep the hpx source code to see which namespace the pool executor is in. It seems like a lot of effort has been put in to create these forwarding headers, but they don't really save much time since I still have to change all my code anyway.

**Comment by biddisco** [comment]
likewise
```
/home/biddisco/src/hpx/libs/functional/include_compatibility/hpx/util/bind.hpp:18:2: warning: #warning "The header hpx/util/bind.hpp is deprecated,     please include hpx/functional/bind.hpp instead" [-Wcpp]
   18 | #warning "The header hpx/util/bind.hpp is deprecated, \
      |  ^~~~~~~
/home/biddisco/src/martycam/main.cpp:7:10: fatal error: hpx/include/iostreams.hpp: No such file or directory
    7 | #include <hpx/include/iostreams.hpp>
```
changing the bind header is nice, but I still have to grep for iostreams anyway.

After modularization is complete, and files move around reasonably little - I can see how these headers might be useful, but with such a massive disruption in the code base from pre to post modularization - it would have saved considerable work to introduce them only post-modularization.

We never gave a guarantee that files would not move in previous versions (ie. prior to these changes). If we are giving guarantees now, then we can add compatibility support, but I believe that this was introduced one version too early.

**Comment by msimberg** [comment]
That suggestion to include `hpx/executors/pool_executor.hpp` instead of `hpx is not quite right. Could you help us get it right? I think if you want to keep on using `hpx::threads::executors::pool_executor` the right include would be `hpx/thread_executors/pool_executor.hpp`. Does that work for you? The new `pool_executor` is not 100% compatible with the old one because it's not a `thread_executor` anymore.

The `iostreams` error seems to be completely unrelated to bind or headers moving around?

The bind warning does raise another point. We probably shouldn't suggest `hpx/functional/bind.hpp` but just `hpx/functional.hpp` (in general we should suggest the headers that we agree on in #4626).

**Comment by biddisco** [comment]
**I don't need help fixing my old code.**

I'm merely trying to  point out that I do not believe the compatibility headers are useful yet.

In a similar vein ... this ...
```
In file included from /home/biddisco/src/martycam/webcam_test/hpx_opencv_webcam.cpp:10:
/home/biddisco/src/martycam/webcam_test/system_characteristics.hpp:11:10: fatal error: hpx/runtime_impl.hpp: No such file or directory
   11 | #include <hpx/runtime_impl.hpp>
```
and this
```
/home/biddisco/src/martycam/webcam_test/system_characteristics.hpp: In function ‘void print_system_characteristics()’:
/home/biddisco/src/martycam/webcam_test/system_characteristics.hpp:43:31: error: ‘class hpx::threads::threadmanager’ has no member named ‘get_worker_thread_num’
   43 |               << thrd_manager.get_worker_thread_num() << "\n\n";
```
and this
```
/home/biddisco/src/martycam/webcam_test/system_characteristics.hpp: In function ‘void print_system_characteristics()’:
/home/biddisco/src/martycam/webcam_test/system_characteristics.hpp:37:55: error: ‘class hpx::runtime’ has no member named ‘get_thread_name’; did you mean ‘get_thread_mapper’?
   37 |               << "called by thread named     " << rt->get_thread_name()
```
```
/home/biddisco/src/martycam/webcam_test/system_characteristics.hpp:43:31: error: ‘class hpx::threads::threadmanager’ has no member named ‘get_worker_thread_num’
   43 |               << thrd_manager.get_worker_thread_num() << "\n\n";
      |                               ^~~~~~~~~~~~~~~~~~~~~
```
are not solved by the compatibility layer - and these take much more time to track down and fix than the header changes.

**Comment by biddisco** [comment]
NB. And I still have dozens and dozens more errors to go through.

**Comment by biddisco** [comment]
> That suggestion to include `hpx/executors/pool_executor.hpp` instead of `hpx/parallel/executors/pool_executor.hpp` is not quite right. Could you help us get it right?

No! 
I do not believe the compatibility layer is useful when going from a completely unstructured HPX (ie the old one), to a new modularized and better structured HPX. The time spent getting that layer right is too excessive and not worth the effort.

Once the modularization is complete - Then I think the layer will prove useful, because changes in locations of utilities and functions will be better structured and more traceable/trackable/predictable. And only now are we giving users any kind of guarantee of API support.

**Comment by biddisco** [comment]
I would like the retract my "No!" in the previous comment.

I don't want to help fix the compatibility layer - not because it's a waste of time right now, but because **_I have no idea where everything is any more anyway_**.

**Comment by msimberg** [comment]
I think we mostly agree. We will not get everything right with the compatibility headers, but they do work for a majority of cases (which is why I would like to have for example the executor headers working correctly) and I think it's worth it to keep them for that. That runtime functionality you're relying on is definitely meant to be internal functionality (there's `hpx::get_thread_name`, `hpx::get_os_thread_count`), but this just shows the problem we have from not specifying our API and what headers are ok for users to include. You most likely want `hpx/runtime_fwd.hpp` for that functionality.

**Comment by biddisco** [comment]
I've now finished converting my old application (and the HPX backend for OpenCV) so that they run with the latest HPX. Last night and this morning, I probably spent about 3 hours on it. 

3 hours is a PITA but in the grand scheme of things, it's not a lot of time to convert a complex QT GUI application that uses HPX tasks for processing/rendering and has an OpenCV image processing pipeline that also uses the HPX backend. There are very few applications out there using HPX and 3 hours on each is probably still less than the time it would/does take to maintain/create the right compatibility layers for the old HPX.

**Comment by hkaiser** [comment]
> The bind warning does raise another point. We probably shouldn't suggest hpx/functional/bind.hpp but just hpx/functional.hpp (in general we should suggest the headers that we agree on in #4626).

Excellent point!
