### ISSUE TITLE
Thread stacksize not properly set

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#4648]
Did you have a case where `stacksize` still was `thread_stacksize_current` at this point? I would rather put an assert in the first if after `stacksize` has been updated as this shouldn't happen. A created HPX thread should always have one of the actual sizes (small, medium, ...), and a non-HPX thread should return the default which is the small stacksize at the moment.

_Originally posted by @msimberg in https://github.com/STEllAR-GROUP/hpx/pull/4644_

**Comment by msimberg** [comment]
Reopening as a reminder to look at https://cdash.cscs.ch//testDetails.php?test=21992139&build=109075.
