### ISSUE TITLE
thread descriptions are broken...again

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#4650]
## Expected Behavior

The `util::thread_description` constructor uses the `traits::get_function_annotation<F>::call(f);` value to get an annotation, if it exists.  The default behavior used to be to return a `nullptr`, which would then be overridden by the `altname` value, if there was one.

## Actual Behavior

Unfortunately, the new behavior is to return the string `"<anonymous>"`.  Which then overrides whatever annotation is passed in to the `util::thread_description` constructor as `altname`.  See these lines:
https://github.com/STEllAR-GROUP/hpx/blob/9b9392a24c3406237fae4f04c68a2081c1e04ae8/libs/threading_base/include/hpx/threading_base/thread_description.hpp#L85-L89
and
https://github.com/STEllAR-GROUP/hpx/blob/9b9392a24c3406237fae4f04c68a2081c1e04ae8/libs/functional/include/hpx/functional/traits/get_function_annotation.hpp#L20-L24

I tried changing `traits::get_function_annotation<F>::call(f);` to return `nullptr`, but other code now depends on a valid string value. ☹️ 

I can hack a check for `"<anonymous>"`, but that doesn't "make the common case fast". I am open to other ideas...

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. Configure HPX with APEX support
  1. `export APEX_SCREEN_OUTPUT=1` to see the APEX measurements after execution
  1. Run any example, but examples.quickstart.fibonacci_futures_distributed will reproduce it.

## Specifications

... Please describe your environment

  - HPX Version:  current master
  - Platform (compiler, OS):  gcc 7.3, RHEL linux

**Comment by khuck** [comment]
Quick update - if I change the return from `traits::get_function_annotation<F>::call(f);` back to nullptr, then things _do_ work.  I'll do some more testing, then probably do a pull request.

**Comment by hkaiser** [comment]
@khuck I'm now able to reproduce this and will try to find a remedy.

**Comment by khuck** [comment]
> @khuck I'm now able to reproduce this and will try to find a remedy.

Did you intend to add this to #4652?

**Comment by hkaiser** [comment]
@khuck I will fix #4652 separately.
