### ISSUE TITLE
MPI initialization broken when networking off

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#4662]
Unfortunately, changes were made in PR #4540 to initialization, that broke MPI when networking was enabled, then they were broken again in #4644 for applications that do not use networking. Attempting to run MPI enabled code that uses HPX results in
```
hpx::init: exception caught: Invalid runtime mode specified
```
on all ranks != 0

Unfortunately #4540 was merged before it was ready (and broke local changes I was working on for initialization). #4644 was not tested properly before being merged. I still have a number of changes I would like to make to the MPI support and I would appreciate if others would synchronize with me before merging any more MPI related fixes.

**Comment by hkaiser** [comment]
@biddisco: How do you run MPI jobs? What errors do you see? Is latest master still broken for you?

**Comment by hkaiser** [comment]
> #4644 was not tested properly before being merged.

What tests failed after merging this?

**Comment by biddisco** [comment]
Yes. Latest master is broken. No tests failed. What I mean is that the PR was submitted and merged within a day and I didn't have a chance to actually test it on real applications that don't use hpx networking. Unfortunately, our mpi_async tests are incorrectly setup and run only on N=1 ranks (something I will also fix in the PR when I push the fix).
