### ISSUE TITLE
Error running Quickstart tests on OS X

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#4674]
## Expected Behavior

On other platforms, `ctest -V -R tests.examples.quickstart` runs fine. On OS X, the 1d_wave_equation (and others) test will fail because of the `-Ihpx.stacks.use_guard_pages=0` argument.

## Actual Behavior

```
khuck@Kevins-MacBook-Air hpx % /Users/khuck/src/hpx/build/bin/1d_wave_equation -t 8 -Ihpx.stacks.use_guard_pages=0
hpx::init: hpx::exception caught: Attempt to initialize unknown entry:  <command line definitions>: line 1 (offending entry: hpx.stacks.use_guard_pages=0): HPX(no_success)
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. `spack install --only dependencies hpx`
  1. 
```
cmake \
-DCMAKE_CXX_COMPILER=`which g++` \
-DCMAKE_C_COMPILER=`which gcc` \
-DCMAKE_BUILD_TYPE=Debug \
-DBOOST_ROOT=`spack location -i boost` \
-DTCMALLOC_ROOT=`spack location -i gperftools` \
-DHPX_WITH_MALLOC=tcmalloc \
-DHWLOC_ROOT=`spack location -i hwloc` \
-DCMAKE_INSTALL_PREFIX=../install \
-DHPX_WITH_THREAD_IDLE_RATES=ON \
-DHPX_WITH_PARCELPORT_MPI=OFF \
-DHPX_WITH_TOOLS=ON \
-DHPX_WITH_TESTS=ON \
-DHPX_WITH_EXAMPLES=ON \
-DHPX_WITH_APEX=TRUE \
-DHPX_WITH_APEX_TAG=develop \
-DAPEX_WITH_ACTIVEHARMONY=FALSE \
-DAPEX_WITH_OTF2=TRUE \
-DOTF2_ROOT=`spack location -i otf2` \
-DAPEX_WITH_PAPI=FALSE \
..
```

  1. `make -j8 -l8 tests.examples.quickstart`
  1. `ctest -V -R tests.examples.quickstart.1d_wave_equation`

## Specifications

... Please describe your environment

  - HPX Version:  current master
  - Platform (compiler, OS):  Apple Clang 11.0.3 on OS X 10.15.4

**Comment by hkaiser** [comment]
Writing this as `--hpx:ini=hpx.stacks.use_guard_pages!=0` (note the exclamation mark) will avoid this issue on platforms that don't support guard pages.
