### ISSUE TITLE
Suggestion to fix and enhance the thread_mapper API

### ISSUE THREAD

**Issue by McKillroy** [STEllAR-GROUP/hpx#4691]
The thread_mapper (`hpx::util::thread_mapper`) currently offers some limited
thread access functionality. It maintains a list of threads whose count you 
can get with the `get_thread_count()` member function.
You may then use indices 0 to count-1 and use (amongst others) these member functions:
```c++
long int get_thread_id(std::uint32_t tix) const;              // Returns -1  on Windows and is unusable there
std::string const& get_thread_label(std::uint32_t tix) const; // Get thread label from -index
std::uint32_t get_thread_index(std::string const&) const;     // Get thread index from -label
```

I would like to suggest to add a struct to the API which contains useful thread information:

```c++
struct os_thread_info {
    std::thread::id const  id;       // Portable type of the threads id on the system.
    std::string const      label;    // Label of the thread as before
    thread_type const      type;     // Enum class of threads type, like "worker", "timer", "io", ...    
    size_t                 userdata; // Thread Data, like in the case of tasks, could be size_t, void*, whatever.
}
```
The structure would be accessible by `os_thread_info& get_info(std::uint32_t tix)`
with an overload like `os_thread_info& get_info(std::thread::id id)`

Reasons:

1. The retrieval of thread IDs on Windows is not working.
2. The thread IDs being used are not C++ Standard conformant
3. There is currently no standardized way to associate data with an OS thread. 
E.g. one might use an object pool or allocator local to a thread to avoid contention.
(We are currently doing this for a pool of reusable Lua States and have one pool per OS thread)
4. After initial setup read access should be safe from any thread.

I'm sure there are many more possible improvements, but this is my first wish for this API.

Ideas? Suggestions?

**Comment by hkaiser** [comment]
This structure also seems to cause quite some compile time overhead (as reported by @K-ballo). Another good reason to overhaul the `thread_mapper` ...
