### ISSUE TITLE
Rename HPX_MPI_WITH_FUTURES option

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4712]
Especially after #4689, but also otherwise, the `HPX_MPI_WITH_FUTURES` option doesn't really fit other naming schemes. It's written as if it's an option for the (old) `mpi` module, but what it does is enable the whole module.

I would rename it as a "top-level" option: `HPX_WITH_MPI_FUTURES` or `HPX_WITH_ASYNC_MPI` to decouple it a bit from the module itself (just like the CUDA options). If someone likes to have it be tied to whether or not the module itself is enabled I would go for maybe `HPX_WITH_MODULE_ASYNC_MPI`, but I don't like this since we wouldn't have it for every module.

**Comment by hkaiser** [comment]
I have to admit that initially I asked for this variable to be named as if it was a module-specific configuration option. I start to like `HPX_WITH_ASYNC_MPI` more than `HPX_ASYNC_MPI_WITH_FUTURES`.

**Comment by biddisco** [comment]
I will be renaming the mpi futures module to async_mpi in #4385 so I shall take care of this in that PR.
I prefer `HPX_WITH_ASYNC_MPI`

**Comment by biddisco** [comment]
Please ignore that comment, the module is already renamed, I'm rebasing onto it and fixing all the other cmake problems, but I will take care of this cmake option too

**Comment by msimberg** [comment]
Should we go with `HPX_WITH_ASYNC_MPI`? @biddisco will you be changing this in #4663?

**Comment by msimberg** [comment]
This has been fixed by #4663.
