### ISSUE TITLE
build error using boost 1.73.0

### ISSUE THREAD

**Issue by albestro** [STEllAR-GROUP/hpx#4728]
## Expected Behavior

It should build correctly (it works with boost 1.72.0).

## Actual Behavior

It does not build (see [build-error.log](https://github.com/STEllAR-GROUP/hpx/files/4746515/build-error.log))

## Steps to Reproduce the Problem

It is a very classic build setup, mainly I've just disabled EXAMPLES, TESTS, NETWORKING.

## Specifications

  - HPX Version: 1.4.1 (tested also with 1.4.0)
  - Platform (compiler, OS): GCC 8.3.0 on Linux

**Comment by hkaiser** [comment]
This problem was already solved on master. Would you need to have it fixed on V1.4.1 as well?

**Comment by albestro** [comment]
Ah ok, sorry I didn't test with `master`. I've tried right now and it fails, but with another error (#4723). However, if this problem has been already fixed, it's ok for me leaving it as it is.

Thanks!

**Comment by msimberg** [comment]
Yep, #4723 is fixed in #4727. Thanks for reporting in any case!
