### ISSUE TITLE
Memory leak when using dataflow icw components

### ISSUE THREAD

**Issue by kordejong** [STEllAR-GROUP/hpx#4746]
## Expected Behavior

Constant (more or less) amount of memory used.

## Actual Behavior

Fast increase of memory usage, depending on number of component clients involved in dataflow.

## Steps to Reproduce the Problem

I can reproduce the issue I see with my code with the `1d_stencil_7.cpp` distributed with HPX.

  1. Apply fix #4731 
  1. Update code so `heat_part` action depends on a few partitions more instead of the 2 directly neighboring partitions (see diff below)
  1. Run the exe using multiple localities (see script below)

## Specifications

  - HPX Version: 1.4.1
  - Platform (compiler, OS): gcc-7, Kubuntu 18.04

## Futher remarks
Some things I learned when hunting for the source of the leak the past week:

- Memory usage does not increase when using a single locality. There seems to be a dependency on the layer handling the transport of component clients.
- The component clients passed into the action do not have to actually be used at the target locality for the memory usage to increase. The issue is visible even when just copying the middle partition and not touching the other ones.
- The amount of memory used by the process is *much* larger than expected and increases fast
- The amount of memory used increases faster with the number of partitions passed into the action
- Memory usage does not increase when calling the action synchronously
- I used the sliding semaphore in my own code to throttle the generation of tasks, but this had no effect. That is why I think there is a leak somewhere. Also, waiting for partitions to become ready in each iteration (`wait_all`) has no effect on increased memory usage over time.

I am very happy to provide more info or do additional testing. My project depends very much on a fix for this issue. It would be great if I could somehow get things going without the increased memory usage killing the process. A local hack is fine ;-)

## Diff for `1d_stencil_7.cpp`
The relevant thing that changed is the number of partitions passed into the action. They are not actually used. Passing more neighboring partitions increases the memory usage over time, a lot.
```diff
diff --git a/examples/1d_stencil/1d_stencil_7.cpp b/examples/1d_stencil/1d_stencil_7.cpp
index 1e9672f0ffb..7a798eae2f1 100644
--- a/examples/1d_stencil/1d_stencil_7.cpp
+++ b/examples/1d_stencil/1d_stencil_7.cpp
@@ -33,10 +33,10 @@ double dx = 1.;     // grid spacing
 
 inline std::size_t idx(std::size_t i, int dir, std::size_t size)
 {
-    if(i == 0 && dir == -1)
-        return size-1;
-    if(i == size-1 && dir == +1)
-        return 0;
+    if(dir < 0 && std::abs(dir) > i)
+        return size-(std::abs(dir) - i);
+    if((i + dir) >= size)
+        return (i + dir) - size
 
     HPX_ASSERT((i + dir) < size);
 
@@ -45,7 +45,7 @@ inline std::size_t idx(std::size_t i, int dir, std::size_t size)
 
 inline std::size_t locidx(std::size_t i, std::size_t np, std::size_t nl)
 {
-    return i / (np/nl);
+    return static_cast<std::size_t>(std::floor(i / ((double)np/nl)));
 }
 
 ///////////////////////////////////////////////////////////////////////////////
@@ -258,8 +258,11 @@ struct stepper
     //[stepper_7
     // The partitioned operator, it invokes the heat operator above on all elements
     // of a partition.
-    static partition heat_part(partition const& left,
-        partition const& middle, partition const& right)
+    static partition heat_part(
+        partition const& left3, partition const& left2, partition const& left,
+        partition const& middle,
+        partition const& right, partition const& right2, partition const& right3
+        )
     {
         using hpx::dataflow;
         using hpx::util::unwrapping;
@@ -354,11 +357,16 @@ stepper::space stepper::do_work(std::size_t np, std::size_t nx, std::size_t nt)
             using hpx::util::placeholders::_1;
             using hpx::util::placeholders::_2;
             using hpx::util::placeholders::_3;
-            auto Op = hpx::util::bind(act, localities[locidx(i, np, nl)], _1, _2, _3);
+            using hpx::util::placeholders::_4;
+            using hpx::util::placeholders::_5;
+            using hpx::util::placeholders::_6;
+            using hpx::util::placeholders::_7;
+            auto Op = hpx::util::bind(act, localities[locidx(i, np, nl)], _1, _2, _3, _4, _5, _6, _7);
             next[i] = dataflow(
                     hpx::launch::async, Op,
-                    current[idx(i, -1, np)], current[i], current[idx(i, +1, np)]
-                );
+                    current[idx(i, -3, np)], current[idx(i, -2, np)], current[idx(i, -1, np)],
+                    current[i],
+                    current[idx(i, +1, np)], current[idx(i, +2, np)], current[idx(i, +3, np)]);
         }
     }
 
```

## Script to reproduce
This is what I used. The process runs out of memory on a node with 256 GiB. The nodes I use have 8 Numa nodes, having 6 real cores each. I run a single task per Numa node. Each of these use 6 OS threads.

```
#!/usr/bin/env bash
set -e


# → Update this path to local conventions
install_prefix=$LUE_OBJECTS/_deps/hpx-build


nr_threads_per_locality=6
nr_localities=8

nr_partitions=5625
partition_size=160000
nr_time_steps=500


# Submit job to SLURM scheduler
sbatch --job-name heat_ring  << END_OF_SLURM_SCRIPT
#!/usr/bin/env bash
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=12
#SBATCH --cores-per-socket=6
#SBATCH --partition=allq


set -e

module purge
module load opt/all
module load userspace/all
module load gcc/7.2.0
module load boost/gcc72/1.65.1
module load mpich/gcc72/mlnx/3.2.1
module load libraries/papi/5.7.0

srun --ntasks $nr_localities --kill-on-bad-exit --mpi=pmi2 \
    $install_prefix/bin/1d_stencil_7 \
        --hpx:ini="hpx.parcel.mpi.enable=1" \
        --hpx:ini="hpx.os_threads=$nr_threads_per_locality" --hpx:bind="thread:0-5=core:0-5.pu:0" \
        --hpx:print-bind  \
        --no-header \
        --np=$nr_partitions \
        --nx=$partition_size \
        --nt=$nr_time_steps
END_OF_SLURM_SCRIPT
```

**Comment by msimberg** [comment]
@hkaiser, @sithhell is there any way to get more info on garbage collection of components (performance counters, when garbage collection runs)? Is it possible that partitions for older iterations are kept alive too long by some of the user code in the example, or that garbage collection is delayed for some reason? The main loop does quite eagerly unroll the loop, so that could also be a problem. @kordejong where did you put the sliding semaphore when you tried that out?

**Comment by kordejong** [comment]
> @kordejong where did you put the sliding semaphore when you tried that out?

It is in my own code, in the loop iterating of the time steps: https://github.com/pcraster/lue/blob/f2ec7aa30c3e2b73f3ef6554f00487a6a6546458/source/framework/benchmark/src/benchmark_model.cpp#L179 I took inspiration from `1d_stencil_4_throttle.cpp`.

WRT garbage collection, I already use `hpx.agas.max_pending_refcnt_requests!=400` to get rid of lingering components servers faster than by default (4048). This has helped me to keep the overall memory usage of the processes much lower. The issue I report here is about a continuously increasing amount of memory.

To me the core of the problem seems to be that when asynchronously calling an action passing in component clients on localities that are not the same as the current one, memory is leaked. The amount leaked scales with the number of component clients passed along as arguments. The action itself does not need to use the component clients. Just creating a single new partition and returning the component client instance is enough. Replacing the asynchronous call to a synchronous one solves the issue, as does working on a single locality.

On a 1D ring with two neighboring partition clients the issue is visible, but small. It increases fast with the number of neighboring partition clients passed (see diff above). In my code I use a 2D array with 8 neighbors, in which case it takes a few seconds for the process to allocate all memory.

For ease of reproducing the issue on a local machine I can try to reproduce the issue with hpxrun, if that is useful.

**Comment by hkaiser** [comment]
This sounds like we don't properly release references to the objects that are passed as arguments. I'll try to have a look to understand what's wrong.

**Comment by kordejong** [comment]
I managed to create an alternative repro case that, I think, shows the same issue I described above, but now with a smaller problem on a single node, and using `hpxrun.py.` The repro script I used now is this one:

```
#!/usr/bin/env bash
set -e

# → Update this path to local conventions
install_prefix=$LUE_OBJECTS/_deps/hpx-build

nr_threads_per_locality=2
nr_localities=2

nr_partitions=500
partition_size=16000
nr_time_steps=5000

$install_prefix/bin/hpxrun.py --localities=$nr_localities --thread=$nr_threads_per_locality \
    $install_prefix/bin/1d_stencil_7 -- --np=$nr_partitions --nx=$partition_size --nt=$nr_time_steps
```

The bare problem size, excluding overheads of the partitioning and tasks, is 0.12 GB (2 arrays of 500 * 16000 elements of 8 bytes). The original `1d_stencil_7` uses about 2.18 GB. The patched program uses more than 20 GB before I had to kill it. Memory usage was still increasing. Both programs perform the same calculations. The only difference is the number of partition clients passed into the action (3 vs 5).

(BTW: I noticed that somehow a semicolon is missing from the diff above. Line 39 in the new file should read `return (i + dir) - size;`.)

**Comment by kordejong** [comment]
When trying to reproduce using a Debug build, I was bitten by #4732. I mention it for the case the issues are related.

**Comment by kordejong** [comment]
Unless I am mistaken, this issue is not resolved yet, is it?

**Comment by hkaiser** [comment]
I'll reopen the ticket which was closed automatically while merging #4784.

**Comment by kordejong** [comment]
(Comment per request of @hkaiser )
This issue is tagged for the 1.5.0 release. It would be great if it indeed somehow got fixed by that time. The increase in memory usage prevents my software to handle relatively large and/or long running distributed simulations, which is the purpose of my project.

**Comment by hkaiser** [comment]
I recompiled all of HPX and the 1d_stencil_7 application using a leak detector (VLD, see: https://kinddragon.github.io/vld/). I've had nothing but good experiences with it in the past.

Here is the produced output:
```
Visual Leak Detector read settings from: D:\Devel\vld\vld.ini
Visual Leak Detector Version 2.5.1 installed.
Localities,OS_Threads,Execution_Time_sec,Points_per_Partition,Partitions,Time_Steps
2,     2,     137.3560201, 1600,                 500,                  50
No memory leaks detected.
Visual Leak Detector is now exiting.
```
The options I used were: `--np=500 --nx=1600 --nt=50 --hpx:threads=1` on two localities. 

I will try to apply your patch above and repeat the experiment (the results show here are based from the vanilla 1d_stencil_7 code.

**Comment by hkaiser** [comment]
The patched version produces the same output (essentially):
```
Visual Leak Detector read settings from: D:\Devel\vld\vld.ini
Visual Leak Detector Version 2.5.1 installed.
Localities,OS_Threads,Execution_Time_sec,Points_per_Partition,Partitions,Time_Steps
2,     2,     176.6102474, 1600,                 500,                  50
No memory leaks detected.
Visual Leak Detector is now exiting.
```
I'm not sure what to do next...

**Comment by kordejong** [comment]
Thanks for looking into this! Interesting. Then I guess memory leak is not the right way to describe the problem. I had another go at reproducing it.

Given a problem size (see my repro script of June 24):
- Using one locality with four threads works fine. Memory usage is constant, around 1.9G.
- Using two localities with two threads each does not work fine. Memory usage by one of the localities is relatively low and constant (1.4G). This locality has the lowest process ID (not sure if that is relevant). Memory usage by the other locality is constantly increasing. In the end it becomes 19G, at which point the process completes. When using more time steps, the process will most probably run out of memory.
- Using four localities with one thread each also does not work fine. Again, memory usage by one of the localities is relatively low and constant (1.4G, lowest PID). Memory usage by the other three localities is constantly increasing. In the end it becomes around 4G, 6G, and 8G each.

I use this command to trace memory usage of the processes:
`watch "smem -k -t -P 1d_stencil_7 | grep development"`

My hypothesis / guess given these results is that on the root locality (lowest PID?), all is fine and that the other localities use increasingly more memory. This seems (only) related to receiving component client instances. The more instances received, the faster memory usage increases.

Maybe memory isn't leaked, but it does seem it is released too late. Note that the problem size I use is only 0.12G.

Can you reproduce my findings on your platform too? You may want to use the parameters I used in my repro script. I selected them because the memory usage increases fast. I noticed you used different ones in your tests.

**Comment by hkaiser** [comment]
So far I can confirm that the memory requirements for the two localities I ran is different indeed (this needs a separate investigation). The overall memory cap however is relatively constant for both localities. I will try to do another experiment using your settings, however.

**Comment by hkaiser** [comment]
@kordejong May I suggest to augment the 1d_stencil_7 example with some code that limits the size of the generated execution tree? The easiest would be to employ a sliding_semaphore as demonstrated in 1d_stencil_8 here https://github.com/STEllAR-GROUP/hpx/blob/master/examples/1d_stencil/1d_stencil_8.cpp#L558
and here: https://github.com/STEllAR-GROUP/hpx/blob/master/examples/1d_stencil/1d_stencil_8.cpp#L609-L621. The memory requirements could be caused by the amount of look-ahead that is inherent to the unlimited execution tree generation.

**Comment by kordejong** [comment]
I tried this before (in my own code, see above), but I now added the semaphore code to the example code, as you suggested. I used a max tree depth of 3 and performed the same experiments as yesterday (1 locality with 4 threads, 2 with 2, 4 with 1) and in each case the effect the throttling had was only visible on one of the localities. Its memory use was lower. The other localities (if any) used an increasing amount of memory, like in the case without the throttling.

| Experiment | Nr localities | Nr threads | Memory usage |
| --- | --- | --- | --- |
| 1 | 1 | 4 | constant |
| 2 | 2 | 2 | constant on one locality, constantly increasing on the other |
| 3 | 4 | 1 | constant on one locality, constantly increasing on the others |

It seems the increase in memory usage is not related to the depth of the execution tree.

Can you reproduce the same behaviour with the patched example code as I am seeing?

To enable you to review whether I did the right thing, I show the patch again:

```
diff --git a/examples/1d_stencil/1d_stencil_7.cpp b/examples/1d_stencil/1d_stencil_7.cpp
index 1e9672f0ffb..c13f417e136 100644
--- a/examples/1d_stencil/1d_stencil_7.cpp
+++ b/examples/1d_stencil/1d_stencil_7.cpp
@@ -33,10 +33,10 @@ double dx = 1.;     // grid spacing
 
 inline std::size_t idx(std::size_t i, int dir, std::size_t size)
 {
-    if(i == 0 && dir == -1)
-        return size-1;
-    if(i == size-1 && dir == +1)
-        return 0;
+    if(dir < 0 && std::abs(dir) > i)
+        return size-(std::abs(dir) - i);
+    if((i + dir) >= size)
+        return (i + dir) - size;
 
     HPX_ASSERT((i + dir) < size);
 
@@ -45,7 +45,7 @@ inline std::size_t idx(std::size_t i, int dir, std::size_t size)
 
 inline std::size_t locidx(std::size_t i, std::size_t np, std::size_t nl)
 {
-    return i / (np/nl);
+    return (i * nl) / np;
 }
 
 ///////////////////////////////////////////////////////////////////////////////
@@ -258,8 +258,11 @@ struct stepper
     //[stepper_7
     // The partitioned operator, it invokes the heat operator above on all elements
     // of a partition.
-    static partition heat_part(partition const& left,
-        partition const& middle, partition const& right)
+    static partition heat_part(
+        partition const& left3, partition const& left2, partition const& left,
+        partition const& middle,
+        partition const& right, partition const& right2, partition const& right3
+        )
     {
         using hpx::dataflow;
         using hpx::util::unwrapping;
@@ -342,6 +345,10 @@ stepper::space stepper::do_work(std::size_t np, std::size_t nx, std::size_t nt)
     for (std::size_t i = 0; i != np; ++i)
         U[0][i] = partition(localities[locidx(i, np, nl)], nx, double(i));
 
+    // limit depth of dependency tree
+    std::uint64_t const nd{3};
+    hpx::lcos::local::sliding_semaphore sem(nd);
+
     heat_part_action act;
     for (std::size_t t = 0; t != nt; ++t)
     {
@@ -354,12 +361,33 @@ stepper::space stepper::do_work(std::size_t np, std::size_t nx, std::size_t nt)
             using hpx::util::placeholders::_1;
             using hpx::util::placeholders::_2;
             using hpx::util::placeholders::_3;
-            auto Op = hpx::util::bind(act, localities[locidx(i, np, nl)], _1, _2, _3);
+            using hpx::util::placeholders::_4;
+            using hpx::util::placeholders::_5;
+            using hpx::util::placeholders::_6;
+            using hpx::util::placeholders::_7;
+            auto Op = hpx::util::bind(act, localities[locidx(i, np, nl)], _1, _2, _3, _4, _5, _6, _7);
             next[i] = dataflow(
                     hpx::launch::async, Op,
-                    current[idx(i, -1, np)], current[i], current[idx(i, +1, np)]
-                );
+                    current[idx(i, -3, np)], current[idx(i, -2, np)], current[idx(i, -1, np)],
+                    current[i],
+                    current[idx(i, +1, np)], current[idx(i, +2, np)], current[idx(i, +3, np)]);
+        }
+
+        // every nd time steps, attach additional continuation which will
+        // trigger the semaphore once computation has reached this point
+        if ((t % nd) == 0)
+        {
+            next[0].then(
+                [&sem, t](partition &&)
+                {
+                    // inform semaphore about new lower limit
+                    sem.signal(t);
+                });
         }
+
+        // suspend if the tree has become too deep, the continuation above
+        // will resume this thread once the computation has caught up
+        sem.wait(t);
     }
 
     // Return the solution at time-step 'nt'.
```

**Comment by hkaiser** [comment]
@kordejong Thanks for testing. I have a couple of additional questions:

- What parcel-port do you use (TCP?, MPI?)
- Is the problem reproducible with the plain (non-patched 1d_stencil_7 as well?
- Is the problem reproducible with other applications (e.g. 1d_stencil_8)?
- Could you please remove the parcel-coalescing plugin (should be in `<install_prefix>/libs/hpx`) and rerun to see if the problem persists?
- Is #4732 still a problem for you?

**Comment by kordejong** [comment]
>     * What parcel-port do you use (TCP?, MPI?)

Both. I can reproduce the issue on a cluster using the MPI parcelport and on my desktop using `hpxrun.py` and the TCP parcelport.

>     * Is the problem reproducible with the plain (non-patched 1d_stencil_7 as well?

Not sure. The problem scales with the number of component clients passed into the action. In the original example three are passed. In the patched version 7 are passed. In my own code 9 are passed. I think the memory is increasing in the original version of the example as well, but it doesn't become a problem because the amount of memory used is much smaller.

>     * Is the problem reproducible with other applications (e.g. 1d_stencil_8)?

No. I patched `1d_stencil_8` to make it pass more partitions to the action, and could not reproduce the problem. This version takes less memory (also without limiting the tree depth) on all localities, and this amount does not increase.
 
>     * Could you please remove the parcel-coalescing plugin (should be in `<install_prefix>/libs/hpx`) and rerun to see if the problem persists?

This does not make a difference.

>     * Is #4732 still a problem for you?

Yes, running the original version of `1d_stencil_7` in Debug mode crashes after a while, due to the assertion. My own code crashes as well.

BTW, I still use version 1.4.1, not master.

**Comment by hkaiser** [comment]
> BTW, I still use version 1.4.1, not master.

Have you tried doing all the above experiments using HPX master? It's where we have fixed the memory problem after all (see #4784). I'd expect that the problem you reported in #4732 would be solved.

**Comment by kordejong** [comment]
I will do the experiments with master tomorrow. I tested #4784 before and didn't notice an improvement wrt this issue (#4746). I wasn't aware of a relation between #4784 and #4732, so I will test that too.

**Comment by kordejong** [comment]
I used today's master, git tag 57f2f7671b9

- #4732 is still an issue with today's master and the above experiment, without patching `1d_stencil_7`. 2 localities with 2 threads each.
- When patching `1d_stencil_7` to pass a few more partitions to the action, memory increases as described above. To me it seems all of the above is still an issue with the current sources.

This is a screenshot of a graph showing the load per core and the increasing memory usage. At the end I killed the process.
![image](https://user-images.githubusercontent.com/1824314/87034910-da769780-c1e8-11ea-9ae0-489c7fed87f6.png)

**Comment by kordejong** [comment]
I tried with both the system allocator and tcmalloc. This made no difference.

**Comment by kordejong** [comment]
Some additional observations:
- I cannot reproduce the issue in Debug mode. The process is much slower then, of course. Maybe there is some time-dependent cleanup logic involved?
- Passing a low value for `hpx.agas.max_pending_refcnt_requests` does not seem to have any effect (release build again). Not sure if that is a silly thing to try, but mentioning it anyway.

**Comment by hkaiser** [comment]
> * I cannot reproduce the issue in Debug mode.

This makes even less sense now. :/

**Comment by kordejong** [comment]
Can you reproduce the issue (with patched stencil example, release build, parameters as mentioned above) on your platform?
