### ISSUE TITLE
License file name

### ISSUE THREAD

**Issue by davidbeckingsale** [STEllAR-GROUP/hpx#4763]
@diehlpk - is there a specific reason the license filename is `LICENSE_0_1.txt`, rather than the standard `LICENSE`?

cc https://github.com/openjournals/joss-reviews/issues/2352

**Comment by diehlpk** [comment]
@msimberg Can you answer this questions, since you are the master of documentation?

**Comment by hkaiser** [comment]
@davidbeckingsale it's the standard way to reference the Boost Software License (see https://www.boost.org/users/license.html)
