### ISSUE TITLE
Block executor does not work with --hpx:bind=none

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4772]
The resource partitioner returns empty pu masks if `--hpx:bind=none` is given on the command line, and the block executor ends up not having any threads to run tasks on. This could be fixed either by returning full machine masks instead of empty masks with `none`, or have the block executor handle empty masks separately. This is low priority for me, but if someone encounters this issue and wants it fixed please comment here.

**Comment by hkaiser** [comment]
FWIW, I had assumed that `--hpx:bind=none` already returns full masks. Otherwise not just the block executor should fail.

**Comment by msimberg** [comment]
That would make sense, but I think we have special handling for empty masks. Making it use the full machine mask instead would probably simplify some of the resource partitioner code.
