### ISSUE TITLE
transform_inclusive_scan tries to implicitly convert between types, instead of using the provided `conv` function

### ISSUE THREAD

**Issue by LiliumAtratum** [STEllAR-GROUP/hpx#4786]
## Expected Behavior

I am trying to use `hpx::parallel::transform_inclusive_scan`, taking a sequence of `T` as input, and producing a sequence of `R` as output. I provide a binary operator R+R->R, as well as a conversion function T->R. 
I expected that lack of the optional `init` argument cause the function to simply call the default constructor of type `R` where needed. Or alternatively, completely avoid calling the binary operator with `init` (which is possible, but needs some extra if-s and may be bad for performance).
When `init` is given, it works as intended.

## Actual Behavior

In the scenario, without the `init` argument, hpx tries to convert T to R through implicit conversion. When such conversion is impossible it leads to a compile error.

## Steps to Reproduce the Problem

Example code:

```
#include <hpx/hpx_main.hpp>
#include <hpx/include/iostreams.hpp>
#include <hpx/parallel/algorithms/transform_inclusive_scan.hpp>

struct Integer {
    int integer;
    Integer()
        : integer(0) {
    }
    explicit Integer(int i)
        : integer(i) {
    }
};

int main(int argc, char *argv[]) {
    std::vector<int> test{1, 10, 100, 1000};
    std::vector<Integer> output(test.size());
    auto pol    = hpx::parallel::execution::par(hpx::parallel::execution::task);
    auto result = hpx::parallel::transform_inclusive_scan(
                      pol, test.cbegin(), test.cend(), output.begin(),
                      [](Integer acc, Integer xs) -> Integer {
                          return Integer{acc.integer + xs.integer};
                      },
                      [](int el) -> Integer { return Integer{el}; }/*, Integer{0}*/)
                      .get();
    for(auto el : output) {
        hpx::cout << el.integer << hpx::endl;
    }
    return 0;
}
```

## Specifications

Versions:
  HPX: V1.5.0-trunk (AGAS: V3.0), Git: unknown
  Boost: V1.72.0
  Hwloc: V1.11.0

Compiling with MSVC 2019, v.16.5.2 on Windows 10 x64

**Comment by hkaiser** [comment]
I'm able to reproduce your issue. There was indeed an invocation of the `unary_op` missing in the implementation of our `transform_include_scan` (also `transform_exclusive_scan`) which is now fixed here: #4788.

However, even then your code does not compile as in the absence of an initial value, the `binary_op` is supposed to return `decltype(*first)` (or something convertible to it), i.e. in your case `int` (see http://eel.is/c++draft/transform.inclusive.scan). That also means, that your output iterator has to accept an `int` (or something convertible to an `int`) as well. You would still need to update your code to something like:
```
    std::vector<int> test{1, 10, 100, 1000};
    std::vector<int> output(test.size());

    auto pol = hpx::parallel::execution::par(hpx::parallel::execution::task);
    auto result = hpx::parallel::transform_inclusive_scan(
        pol, test.cbegin(), test.cend(), output.begin(),
        [](Integer acc, Integer xs) -> int { return acc.integer + xs.integer; },
        [](int el) -> Integer { return Integer{el}; });
    result.get();
```

**Comment by hkaiser** [comment]
I looked into this some more and was able to identify another problem with `transform_inclusive_scan` (which I will fix shortly). 

However from reading the spec a bit more (and as usual things are not as clear-cut as one would wish), I believe that the `unary_op` should also return something that is convertible to `decltype(*first)`. 

The specification of `GENERALIZED_­NONCOMMUTATIVE_­SUM` (see: http://eel.is/c++draft/numeric.ops#numerics.defns) states (under pt. 1) that `GENERALIZED_­NONCOMMUTATIVE_­SUM(op, a1, ..., aN)` is evaluating to `a1` if `N == 1`. At the same time, `transform_exclusive_scan` is defined for each element `K` to perform (see: http://eel.is/c++draft/transform.inclusive.scan#4.2):
```
GENERALIZED_­NONCOMMUTATIVE_­SUM(
    binary_­op,
    unary_­op(*(first + 0)), unary_­op(*(first + 1)), ..., unary_­op(*(first + K)))
```
IOW, in case of `K == 0` this is reduced to:
```
GENERALIZED_­NONCOMMUTATIVE_­SUM(
    binary_­op,
    unary_­op(*(first + 0)))
```
which will evaluate to `unary_­op(*(first + 0))`. That means that both, `binary_op` and `unary_op` should return something convertible to the same type as otherwise the type of the first element would be different from the type for all others.

That said, I believe your use case above is ill-formed to begin with as there is no conversion path from your `Integer` type to `int`. If you need the data type conversion you will have to specify the initial value `Integer{0}` to define the type that should be used for accumulation. In this case both, `unary_op` and `binary_op` should return a type convertible to `Integer` and things would compile (as they do).

**Comment by LiliumAtratum** [comment]
For comparison, the following C++17 code compiles on MSVC 2019 and clang++-10:
```
#include <numeric>
#include <vector>
#include <iostream>

struct Integer {
    int integer;
    Integer()
        : integer(0) {
    }
    explicit Integer(int i)
        : integer(i) {
    }
};

int main(int argc, char *argv[]) {
    std::vector<int> test{1, 10, 100, 1000};
    std::vector<Integer> output(test.size());
    auto result = std::transform_inclusive_scan(
        test.cbegin(), test.cend(), output.begin(),
        [](Integer acc, Integer xs) -> Integer { return Integer{acc.integer + xs.integer}; },
        [](int el) -> Integer { return Integer{el}; } /*, Integer{0}*/);
    for(auto el : output) {
        std::cout << el.integer << std::endl;
    }
    return 0;
}
```

it seems to be some disagreement between the standard and what the compilers actually do? (I admit, it *is* hard to read the standard)

Putting standard aside - my intuition suggests that once I provided how to transform from source type `int` to destination type `Integer`, the algorithm does not need anything else to succeed. In particular, any transformation backwards to `int`, in more complex scenarios, may be even impossible to achieve.
In particular, I would expect that it suffices if both `unary_op` and `binary_op` to return the destination type (`Integer`).

**Comment by LiliumAtratum** [comment]
The standard you quoted: http://eel.is/c++draft/transform.inclusive.scan seems to be broken:
25.10.10.1 reads "Let U be the value type of decltype(first)". That would imply that U is of type `InputIterator` and suddently `binary_op` should return something convertible to an iterator.
Personally, I don't think it's just a star missing. I would expect U to be of type `decltype(unary_op(*first))` instead, and then everything would make sense to me: `unary_op` returns something convertible to `U` and so does `binary_op`.

**Comment by hkaiser** [comment]
> I would expect U to be of type decltype(unary_op(*first))

@LiliumAtratum Yes, this is a typo.

**Comment by hkaiser** [comment]
> Putting standard aside - my intuition suggests that once I provided how to transform from source type int to destination type Integer, the algorithm does not need anything else to succeed. In particular, any transformation backwards to int, in more complex scenarios, may be even impossible to achieve.

In the absense of an initial value, the internal accumulator type is to be derived from `decltype(*first)` which implies that both operators need to return something convertible to this. What you said above is true as long as you provide an initial value that will be used to derive the accumulator type the scan algorithm operates on.

**Comment by hkaiser** [comment]
> > Putting standard aside - my intuition suggests that once I provided how to transform from source type int to destination type Integer, the algorithm does not need anything else to succeed. In particular, any transformation backwards to int, in more complex scenarios, may be even impossible to achieve.
> 
> In the absense of an initial value, the internal accumulator type is to be derived from decltype(*first) which implies that both operators need to return something convertible to this. What you said above is true as long as you provide an initial value that will be used to derive the accumulator type the scan algorithm operates on.

FWIW, I can make this work after all. I'm just not sure what's right here, the standard or the MSVC and clang implementations. I guess we should go with the real implementations. @K-ballo what's your take?

**Comment by LiliumAtratum** [comment]
> 
> 
> > Putting standard aside - my intuition suggests that once I provided how to transform from source type int to destination type Integer, the algorithm does not need anything else to succeed. In particular, any transformation backwards to int, in more complex scenarios, may be even impossible to achieve.
> 
> In the absense of an initial value, the internal accumulator type is to be derived from `decltype(*first)` which implies that both operators need to return something convertible to this. What you said above is true as long as you provide an initial value that will be used to derive the accumulator type the scan algorithm operates on.

The internal accumulator type can be derived as `U=decltype(unary_op(*first))` and then, naturally `binary_op` needs to be able to take (U,U) and return U (or something convertible). This way it can work even if `init` is not provided.

You might need to add some `std::remove_cv` here and there, but that's detail.

**Comment by hkaiser** [comment]
@LiliumAtratum as @K-ballo noticed, the standard says that "U should be the **value type** of decltype(first)". That does not explain why msvc and clang compile the code you provided. It makes more sense that we thought, however.

**Comment by LiliumAtratum** [comment]
@hkaiser Yes, I misunderstood that phrase.
Still, I think U should be `decltype(unary_op(*first))` instead.
It doesn't matter if unary_op doesn't change the type, but it matters when it does change it.

**Comment by hkaiser** [comment]
> @hkaiser Yes, I misunderstood that phrase.
> Still, I think U should be decltype(unary_op(*first)) instead.
> It doesn't matter if unary_op doesn't change the type, but it matters when it does change it.

Yes, that's what we discussed on irc as well. The PR (#4788) will fix this.

**Comment by K-ballo** [comment]
> Still, I think U should be `decltype(unary_op(*first))` instead.

@LiliumAtratum Would you please submit a standard library issue (https://isocpp.org/std/submit-issue) reporting this? The constraint in question was introduced by [P0574R1](https://wg21.link/p0574r1).

**Comment by hkaiser** [comment]
@LiliumAtratum does #4788 fix your issues?

**Comment by K-ballo** [comment]
@LiliumAtratum LWG is expecting that issue report. Let me know if don't plan to submit it, so that someone else may take care of it.

**Comment by LiliumAtratum** [comment]
@K-ballo Please do report it. I had some issues submitting it there, and frankly I am a bit intimidated by that whole machinery there. Also, I am not a "language lawyer".

**Comment by K-ballo** [comment]
https://cplusplus.github.io/LWG/issue3463
