### ISSUE TITLE
Spack package & HPX_WITH_GENERIC_CONTEXT_COROUTINES

### ISSUE THREAD

**Issue by albestro** [STEllAR-GROUP/hpx#4829]
I've opened this issue because I'd like offering myself for fixing a minor issue in the `hpx` spack package.

The problem is about `HPX_WITH_GENERIC_CONTEXT_COROUTINES` option and the dependency with the boost component `context`. In particular, I'm facing this problem on my `APPLE` laptop.

It looks pretty simple and clear what happens, but I'd like to ask you how you prefer to manage this.

The problem is a "missing link" between the spack package and the CMake configuration. In fact, the spack package adds a dependency to `boost` without requiring the `context` component. Legit. But, in this CMake snippets of code we see that the dependency to boost it is automatically added for some platforms (`APPLE`, `BLUEGENEQ`, `ARM`, but not for `BGION`).

https://github.com/STEllAR-GROUP/hpx/blob/5eb4b72750bd5f6972524e64072f70575493189f/CMakeLists.txt#L1656-L1672

https://github.com/STEllAR-GROUP/hpx/blob/5eb4b72750bd5f6972524e64072f70575493189f/cmake/toolchains/ARM-gcc.cmake#L15-L18

https://github.com/STEllAR-GROUP/hpx/blob/5eb4b72750bd5f6972524e64072f70575493189f/cmake/toolchains/BGION-gcc.cmake#L54-L58

This results in a problem installing using spack, because it builds the dependency `boost~context`, so without context component, but then while configuring HPX CMake will automatically switch and look for it in case the platform is one of the aforementioned.

I just quickly tried on my macOS machine and `HPX_WITH_GENERIC_CONTEXT_COROUTINES=ON` seems mandatory, otherwise I get 

```bash
hpx/libs/coroutines/include/hpx/coroutines/detail/context_impl.hpp:145:2: error: No default_context_impl available for this system
#error No default_context_impl available for this system
```

Do we want/have to mirror the CMake mechanism in the spack package, so adding the dependency to `boost+context` for specified platforms?

Thanks in advance for any feedback!

**Comment by msimberg** [comment]
@albestro thanks a lot for volunteering to do this! What you suggest makes a lot of sense. We could even go one step further and just require Boost.Context already at the CMake level instead of leaving the error to compile time but that's separate from the spack configuration. As far as I remember pretty much any platform except Linux on x86 and Windows requires Boost.Context. So we can force it as a dependency on platforms that require it, but it should also be possible to optionally enable it on platforms that have another implementation as well.

**Comment by albestro** [comment]
I've started working on this here https://github.com/albestro/spack/tree/fix_hpx_coroutines_dep

Main changes are (see https://github.com/spack/spack/commit/743a456e520f338f6559894e83c003084ffbd6ee):
- add variant `generic_coroutines` that controls the CMake option `HPX_WITH_GENERIC_CONTEXT_COROUTINES`
- `hpx~generic_coroutines` depends on `boost+context`
- when `platform=darwin`, `hpx` depends on `boost+context` and it conflicts with `+generic_coroutines`

In the current implementation by default `generic_coroutines=False`, but I'm looking for a solution to set its default value according to the `platform`.

Moreover, currently I just wrote the constraints for macOS, for which I know the right value for the platform in spack, i.e. `platform=darwin`, and I can test it works as expected.

I was not able to figure out a way to get the dual constraint (e.g. "all platforms except linux and windows"), so once we know the additional platforms that do not support `generic_coroutines`, we should extend the spack package copying what it has been done for `darwin`.

**Comment by albestro** [comment]
https://github.com/spack/spack/compare/develop...albestro:fix_hpx_coroutines_dep

Now the default value for the `generic_coroutines` variant depends on the platform:
- On `linux` it is `False`, so the spec is defaulted to `hpx~generic_coroutines`;
- On other platforms it is `True`, so the spec is defaulted to `hpx+generic_coroutines` and the dependency with `boost` is added.

I'm not experienced with `sys` python module, for the moment I just stick to the simple [`sys.platfrom`](https://docs.python.org/3/library/sys.html?highlight=sys%20platform#sys.platform) way (it should be possible to do more advanced tests, e.g. architecture, ...).
AFAICU for this part we may add `win32` to get `False` as default value.

**Comment by hkaiser** [comment]
> * On other platforms it is `True`

On Windows it should be `False` as well. (not sure if Spack works on windows, though).

**Comment by hkaiser** [comment]
This can be closed now as the changes were merged to Spack (https://github.com/spack/spack/pull/17654)

**Comment by hkaiser** [comment]
@albestro Thanks again for pushing this forward!
