### ISSUE TITLE
Undefined reference to main build error when HPX_WITH_DYNAMIC_HPX_MAIN=OFF

### ISSUE THREAD

**Issue by scheherzade** [STEllAR-GROUP/hpx#4880]
## Expected Behavior

I had been using HPX 1.3.0 for my [Blazemark](https://bitbucket.org/blaze-lib/blaze/wiki/Blazemark)(benchmark suite for Blaze) experiments but when I updated HPX I wasn't able to build a benchmark in Blazemark anymore.
I had always built HPX with `-DHPX_WITH_DYNAMIC_HPX_MAIN=OFF` for these runs. If I don't specify this flag and link the benchmark with hpx_wrap I am able to build it with the updated HPX, but I get an error when hpx is built with `-DHPX_WITH_DYNAMIC_HPX_MAIN=OFF` .

## Actual Behavior

I get this error message when I try to build `dmatdmatadd` benchmark from Blazemark.
```
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)

```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.
  1. ```git clone git@bitbucket.org:blaze-lib/blaze.git```
  2. ```cd blazemark```
  3. change [Configfile](https://bitbucket.org/blaze-lib/blaze/src/master/blazemark/Configfile) as follows:
```
# Compiler selection
# This variable specifies the compiler used for the compilation of all benchmarks.
CXX=clang++

# Special compiler flags
# This variable specifies the compiler flags used for the compilation of all benchmarks.
CXXFLAGS="-O3 -std=c++17 -stdlib=libc++ -DNDEBUG -march=native -fpermissive -DBLAZE_USE_HPX_THREADS"

# Special include directives
# This variable can be used to specify special/additional include-related compiler directives.
INCLUDE_DIRECTIVES="-isystem  /home/sshirzad/lib/hpx/hpx_release_clang/include/"

# Special library directives
# This variable can be used to specify special/additional library-related compiler directives.
LIBRARY_DIRECTIVES="-L/home/sshirzad/lib/hpx/hpx_release_clang/lib64 -lhpx -rdynamic /home/sshirzad/lib/hpx/hpx_release_clang/lib64/libhpx_init.a -ldl -lrt -L/opt/apps/clang6/boost/1.68.0-clang6/release/lib -lboost_system -lboost_program_options -pthread"

```
  4. ```./configure Configfile```
  5. ```make dmatdmatadd```

## Specifications

  - HPX Version: master
  - Platform (compiler, OS): clang 6.0.1, linux (marvin node on Rostam)

**Comment by hkaiser** [comment]
@scheherzade Does it help if you add `/home/sshirzad/lib/hpx/hpx_release_clang/lib64/libhpx_wrap.a` as an additional library right after `libhpx_init.a`?

**Comment by scheherzade** [comment]
@hkaiser now I get this error:
```
/home/sshirzad/lib/hpx/hpx_release_clang/lib64/libhpx_wrap.a(main.cpp.o): In function `hpx::init(int, char**, hpx::init_params const&)':
main.cpp:(.text._ZN3hpx4initEiPPcRKNS_11init_paramsE[_ZN3hpx4initEiPPcRKNS_11init_paramsE]+0x4c): undefined reference to `hpx_main(boost::program_options::variables_map&)'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by NK-Nikunj** [comment]
@scheherzade from the looks of it, I think it is due to incorrect linking order. @biddisco and @justwagle have faced issues similar to this in the past.  I'll try to reproduce and come to you.

**Comment by NK-Nikunj** [comment]
@scheherzade as I suspected, it is due incorrect linking order. You need to link to `libhpx_wrap.a` right before `libhpx_init.a`. That should link it just fine. It should look similar to the following:

```
LIBRARY_DIRECTIVES="-L/home/sshirzad/lib/hpx/hpx_release_clang/lib64 -lhpx -rdynamic /home/sshirzad/lib/hpx/hpx_release_clang/lib64/libhpx_wrap.a /home/sshirzad/lib/hpx/hpx_release_clang/lib64/libhpx_init.a -ldl -lrt -L/opt/apps/clang6/boost/1.68.0-clang6/release/lib -lboost_system -lboost_program_options -pthread"
```

@hkaiser iirc I made sure that `libhpx_wrap` is generated only when HPX_WITH_DYNAMIC_MAIN is set to On. From the looks of cmake structure in hpx/wrap, I can see that the default implementation is also a part of it now (triggered when HPX_WITH_DYNAMIC_MAIN is set to Off). That's why it is always necessary to link to `libhpx_wrap.a`. Was this change made recently to the build system? Also, it seems that this change has made builds that set HPX_WITH_DYNAMIC_MAIN as off to throw that vexing link time error. A simple fix for now is to make sure to always link to `libhpx_wrap.a` while building an executable.

**Comment by scheherzade** [comment]
@NK-Nikunj Yes that solved the problem, thanks!

**Comment by hkaiser** [comment]
> I made sure that `libhpx_wrap` is generated only when HPX_WITH_DYNAMIC_MAIN is set to On. From the looks of cmake structure in hpx/wrap, I can see that the default implementation is also a part of it now (triggered when HPX_WITH_DYNAMIC_MAIN is set to Off). That's why it is always necessary to link to `libhpx_wrap.a`. Was this change made recently to the build system? Also, it seems that this change has made builds that set HPX_WITH_DYNAMIC_MAIN as off to throw that vexing link time error. A simple fix for now is to make sure to always link to `libhpx_wrap.a` while building an executable.

@NK-Nikunj I think that linking with `libhpx_wrap.a` should be harmless if `HPX_WITH_DYNAMIC_MAIN=Off`, is it?

**Comment by NK-Nikunj** [comment]
@hkaiser yes, it is indeed harmless. But since we've added default implementation in `libhpx_wrap.a` (https://github.com/STEllAR-GROUP/hpx/blob/master/wrap/CMakeLists.txt#L49-L52), we are now required to always link to it.

**Comment by hkaiser** [comment]
> @hkaiser yes, it is indeed harmless. But since we've added default implementation in `libhpx_wrap.a` (https://github.com/STEllAR-GROUP/hpx/blob/master/wrap/CMakeLists.txt#L49-L52), we are now required to always link to it.

I'll leave this to @msimberg to decide. From what I can see this is not a problem.

**Comment by msimberg** [comment]
I'd say we (I) should fix this. It's a mistake by me that the default main implementation is now in `libhpx_wrap`; I don't think I had any good reason to move it there in the first place. I'll have a look at this. @scheherzade thanks for reporting this! If you can, I'd recommend you move away from manually specifying what to link against and instead use the pkgconfig files or the CMake targets.
