### ISSUE TITLE
A future bound to an action executing on a different locality doesn't capture exception state

### ISSUE THREAD

**Issue by NK-Nikunj** [STEllAR-GROUP/hpx#4886]
## Expected Behavior
Not sure if this is supposed to be an expected behavior. Exception should be handled by the future?

## Actual Behavior
An action that throws on the other locality does not return its exception state to the future. i.e. `f.has_exception()` doesn't work on that future.

## Steps to Reproduce the Problem

```
#include <hpx/hpx_main.hpp>
#include <hpx/include/future.hpp>
#include <hpx/modules/async_local.hpp>
#include <hpx/modules/async_distributed.hpp>
#include <hpx/modules/actions.hpp>
#include <hpx/actions_base/plain_action.hpp>
#include <hpx/hpx.hpp>

#include <exception>

int thrower() {
    std::cout << hpx::get_locality_id() << std::endl;
    throw std::exception();
}
HPX_PLAIN_ACTION(thrower, thrower_action);

int main()
{
    hpx::id_type to_call = hpx::find_here();
    std::vector<hpx::id_type> locales = hpx::find_all_localities();

    std::cout << hpx::get_locality_id() << std::endl;

    for (auto const& id: locales) {
        if (id != to_call) {
            to_call = ids;
            break;
        }
    }

    thrower_action ac;
    hpx::future<int> f = hpx::async(ac, to_call);

    hpx::future<void> g = f.then(hpx::launch::sync, [](hpx::future<int>&& f) {
        if (f.has_exception())
            std::cout << "exception caught!\n";
    });

    g.get();

    return 0;
}
```

The above code doesn't execute to completion. It logs error as an unhandled exception. `{what}: std::exception: HPX(unhandled_exception)`

**Comment by hkaiser** [comment]
Is this specific to remote operation ?

**Comment by NK-Nikunj** [comment]
Yes, it occurs when the action is on another locality. In the example code, I invoke action on locality 1 and the future that is bound to that action is on locality 0. If they're on same localities, no errors come up. When they're on different localities, unhandled exception error is returned by HPX.
