### ISSUE TITLE
HPX MPI Parcelport initialization issue

### ISSUE THREAD

**Issue by NK-Nikunj** [STEllAR-GROUP/hpx#4891]
## Expected Behavior

HPX binaries should execute properly.

## Actual Behavior

HPX fails to initialize properly and seg faults. Here is the debug output: https://gist.github.com/NK-Nikunj/5b0e5005133c3ae11b73a4baeb65ce9b

## Steps to Reproduce the Problem

I use the base configuration from rostam and load OpenMPI module. Following is the list of modules loaded:

```
ngupta@rostam0:~/src/hpx/build-debug/bin(distributed_resiliency)$ module list

Currently Loaded Modules:
  1) gcc/9.3.0   2) boost/1.73.0-release   3) papi/6.0.0   4) git/2.25.1   5) python/3.8.2   6) cmake/3.16.4   7) ucx/1.7.0   8) pmix/3.1.5   9) hwloc/2.2.0  10) Rostam2  11) openmpi/4.0.3
```

I install HPX using the following cmake command:

```
cmake -DCMAKE_BUILD_TYPE=Debug -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCELPORT_TCP=OFF -DCMAKE_INSTALL_PREFIX=$HOME/install/hpx-mpi ..
```

**Comment by msimberg** [comment]
@NK-Nikunj could you try to step through this code: https://github.com/STEllAR-GROUP/hpx/blob/19e64319ab33b494d749a3776d1d91266ced04fb/src/runtime/agas/addressing_service.cpp#L168-L169 and specifically the `get_bootstrap_parcelport` function to check what conditions there fail. It looks like for some reason there is not bootstrap parcelport selected.

**Comment by msimberg** [comment]
A `--hpx:dump-config` might also be helpful.

**Comment by NK-Nikunj** [comment]
@msimberg how do I debug a distributed application using gdb (can it even do so?). Also `--hpx:dump-config` does not create a debug dump.

**Comment by msimberg** [comment]
Only by manually starting each locality with gdb. In the worst case with print statements... but you can also try to reproduce it with a single node:

```
salloc -p medusa -N 1
srun --pty bash
./1d_stencil_8 --hpx:expect-connecting-localities
```
(`--hpx:expect-connecting-localities` should ensure that networking is actually initialized, even with only one node)

**Comment by hkaiser** [comment]
@NK-Nikunj I'm not able to reproduce this when running using mpirun (not SLURM, however). For me the parcelports get initialized properly for all localities. Could you please try adding 
```
--hpx:ini=hpx.parcel.mpi.enable!=1 --hpx:ini=hpx.parcel.bootstrap!=mpi
``` 
to the command line? 

FWIW, `--hpx:list-parcel-ports` should list all active parcelports, also `--hpx:debug-clp` should be verbose about what's picked up from the SLURM environment.

**Comment by NK-Nikunj** [comment]
@hkaiser I can confirm that using mpirun does not reproduce the error. With mpirun, I see that the parcelport is initialized properly. With srun, it seg faults without giving any output.

**Comment by biddisco** [comment]
> Only by manually starting each locality with gdb.

if using ssh, make sure you enable x11 forwarding, then

```
mpiexec -n 2 xterm -e gdb --args my_programm --hpx:threads=4 etc etc
```
or
```
srun --x11 -n 2 xterm -e gdb --args my_program --hpx:threads=4 etc etc
```

**Comment by hkaiser** [comment]
> @hkaiser I can confirm that using mpirun does not reproduce the error. With mpirun, I see that the parcelport is initialized properly. With srun, it seg faults without giving any output.

Have you tried forcefully enabling the MPI parcelport (`--hpx:ini=hpx.parcel.mpi.enable!=1 --hpx:ini=hpx.parcel.bootstrap!=mpi`)?

**Comment by NK-Nikunj** [comment]
Yes, I did. It still resulted in a seg fault. I'm looking into gdb right now. I'll come back with my findings.

**Comment by hkaiser** [comment]
All of this looks to me like a problem with initializing the MPI parcelport in cases where SLURM or other batch environments are being used to launch the localities. We seem to disable the MPI parcelport in this case, even if it is force-enabled using configuration settings on the command line.  

SLURM usually knows about MPI (see https://slurm.schedmd.com/mpi_guide.html) and initializes the environment for the launched jobs. @NK-Nikunj please verify that this is actually happening on rostam (your log linked above suggests otherwise...).

**Comment by sithhell** [comment]
The support needs to be enabled in both ways: in slurm and the mpi
implementation.
As a workaround, using mpirun inside a slurm works just as fine. It's only
a matter how the processes are started etc.

Hartmut Kaiser <notifications@github.com> schrieb am Mi., 12. Aug. 2020,
15:38:

**Comment by msimberg** [comment]
@NK-Nikunj any update on this issue? Did you resolve it, find a workaround, or just move on with other things?

**Comment by NK-Nikunj** [comment]
@msimberg I moved on for the time being. I'll get back to it early September.

**Comment by hkaiser** [comment]
@NK-Nikunj has this been resolved?

**Comment by NK-Nikunj** [comment]
@hkaiser I tried recently, it still is not resolved. I was able to get rid of the warnings, but it randomly shuts off when using MPI. TCP works fine though.
