### ISSUE TITLE
Compiler warning, deprecated header used by HPX itself

### ISSUE THREAD

**Issue by kordejong** [STEllAR-GROUP/hpx#4897]
## Expected Behavior

Compile without warning about use of deprecated header.

## Actual Behavior

Compiler warns about use of deprecated header. Minor issue I guess. Reporting anyway.

```
/tmp/hello_hpx-fetch_content/RelWithDebInfo-apex/build/_deps/hpx-src/libs/lcos_local/include_compatibility/hpx/local_lcos/composable_guard.hpp:19:2: warning: #warning "The header hpx/local_lcos/composable_guard.hpp is deprecated,     please include hpx/lcos_local/composable_guard.hpp instead"
[-Wcpp]
/tmp/hello_hpx-fetch_content/RelWithDebInfo-apex/build/_deps/hpx-src/libs/runtime_local/include_compatibility/hpx/util/interval_timer.hpp:18:2: warning: #warning "The header hpx/util/interval_timer.hpp is deprecated,     please include hpx/modules/runtime_local.hpp instead" [-Wcpp]
```

It seems compatibility headers are including each other.

## Steps to Reproduce the Problem

I used this configuration:
```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DHELLO_HPX_REPOSITORY_CACHE:PATH=/home/kor/development/repository -DHPX_WITH_APEX:BOOL=ON -DAPEX_WITH_OTF2:BOOL=ON -DHELLO_HPX_BUILD_OTF2:BOOL=ON -DHPX_WITH_EXAMPLES:BOOL=ON -DHPX_WITH_MALLOC:STRING=tcmalloc -DHPX_WITH_HWLOC:BOOL=ON -S /home/kor/development/project/hello_hpx -B /tmp/hello_hpx-fetch_content/RelWithDebInfo-apex/build`
cmake --build /tmp/hello_hpx-fetch_content/RelWithDebInfo-apex/build
```
(See also: https://github.com/kordejong/hello_hpx)

## Specifications

  - HPX Version: 1.5.0-rc1
  - Platform (compiler, OS): Linux, gcc-7

**Comment by msimberg** [comment]
Thanks @kordejong for reporting! I think this actually comes from APEX. The APEX tag will still be updated before the final release, so we'll make sure that these are not included anymore at that point.

**Comment by kordejong** [comment]
Hi @msimberg . You are right. I noticed I forgot to add the source of the modules triggering the warning. These are indeed APEX modules. Other builds, without using APEX build without deprecation warnings.

**Comment by kordejong** [comment]
BTW, I get some other warnings as well, when using HPX. These are triggered by GCC's `-Wunused-parameter`. Are these useful to report, or is that maybe work in progress?

**Comment by msimberg** [comment]
Please do post those as well. We might have a gap in our testing configurations that you've hit.

**Comment by kordejong** [comment]
[hpx_warnings.txt](https://github.com/STEllAR-GROUP/hpx/files/5083832/hpx_warnings.txt)

These are the warnings I get when building HPX 1.5.0-rc1 and my project.

**Comment by hkaiser** [comment]
Thanks, I'll take care of those.
