### ISSUE TITLE
Adding JOSS status badge to README

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#4900]
Can we add the JOSS status badge to the Readme.rst where we have the circle-ci and all other badges?

[![status](https://joss.theoj.org/papers/022e5917b95517dff20cd3742ab95eca/status.svg)](https://joss.theoj.org/papers/022e5917b95517dff20cd3742ab95eca)

After acceptance the badge will point to the paper.

**Comment by hkaiser** [comment]
Done.
