### ISSUE TITLE
HPX CMake targets not available when using FetchContent

### ISSUE THREAD

**Issue by kordejong** [STEllAR-GROUP/hpx#4913]
## Expected Behavior

When using CMake's `FetchContent` module to incorporate HPX in my project, I expect to be able to use the HPX targets.

## Actual Behavior

HPX CMake targets are not available:

```
CMake Error at CMakeLists.txt:96 (add_executable):
  Target "my_hpx_program" links to target "HPX::hpx" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:96 (add_executable):
  Target "my_hpx_program" links to target "HPX::wrap_main" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:96 (add_executable):
  Target "my_hpx_program" links to target "HPX::iostreams_component" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

## Steps to Reproduce the Problem

  1. Use CMake FetchContent to incorporate HPX in project
  1. Configure project, use HPX targets as described in manual

See `CMakeLists.txt` at https://github.com/kordejong/hello_hpx As a repro case, execute the first command in `debug_build.sh`, for example (comment out everything after line 8).

## Specifications

  - HPX Version: 1.5.0-rc2
  - Platform (compiler, OS): gcc-7, Linux

## Remarks
- I noticed a typo in the manual: https://hpx-docs.stellar-group.org/branches/release/html/quickstart.html#hello-world The include of iostream.hpp should be `hpx/distributed/iostream.hpp`, I think
- Besides the HPX CMake targets not being available, the `iostream.hpp` header is not available in `hpx/distributed/iostream.hpp`, but in `hpx/iostream.hpp`. Maybe some copying is done (only) at installation time?
- I am assuming I can use HPX as advertised by using CMake's FetchContent instead of installing HPX. This can be done in principle, I think. See also https://cmake.org/cmake/help/git-stage/module/FetchContent.html#examples It is mentioned there that the targets are available, after `FetchContent_MakeAvailable`.

**Comment by msimberg** [comment]
I *think* all is as it should here. Can you use the HPX targets without the `HPX::` namespace? I'm pretty sure fetchcontent doesn't use the namespaces we set when exporting targets, but I'm far from an expert on this. If that's the case this is something to take up with the CMake developers (or maybe there are other ways to clone another project inside the project and use its CMake config files).

`hpx/iostream.hpp` is correct, but we can certainly add `hpx/distributed/iostream.hpp` as well. We had a bit of an internal misunderstanding earlier and moved `hpx/distributed/iostream.hpp` to `hpx/iostreams.hpp`. The `hpx/x.hpp` headers will always be there and they will pull in both local and distributed headers where applicable.

We will add `hpx/distributed/x.hpp` "where it makes sense". In this case it would probably make sense to add that version as well for iostream. Do you have a preference as a user?

**Comment by kordejong** [comment]
Yes, the build starts fine without the `HPX::` namespace. Thanks, good suggestion!

It seems possible to export the namespace of targets as well. Here is an example I found: https://gitlab.com/CLIUtils/modern-cmake/-/blob/master/examples/fetch/CMakeLists.txt (haven't checked it). If I run into more info I will let you know.

Wrt location of `iostream.hpp`: I have no preference because I have no clear idea yet of the rationale of the location of HPX headers. I am in favor of everything that makes my use of HPX correspond with what is documented. `hpx/iostream.hpp` is fine with me. I will update my code.

**Comment by kordejong** [comment]
I think something like this would make HPX targets available from the HPX namespace when HPX is used as a subproject in other projects:

```
add_library(HPX::hpx ALIAS hpx)
# ... etc for other targets
```

**Comment by msimberg** [comment]
That's a very good suggestion, thanks! I think doing that would indeed make sense, and would at the same time potentially simplify (a bit) some of our internal CMake. I'll have a go at this.

As for the header, we'll stick to just that one header then (it's going to be there in any case), and potentially add more in the future.
