### ISSUE TITLE
Codespell report for "HPX" (on fossies.org) 

### ISSUE THREAD

**Issue by jschleus** [STEllAR-GROUP/hpx#4940]
The FOSS server https://fossies.org - since today also supporting "HPX" - offers a feature named "Source code misspelling reports":

 https://fossies.org/features.html#codespell

Such reports are normally only generated on request, but since I found in the tarball a file named `tools/.codespell_whitelist` as Fossies administrator I couldn't help forcing  nevertheless such a  [codespell](https://github.com/codespell-project/codespell) analysis for the new "HPX" release :

 https://fossies.org/linux/misc/hpx/codespell.html

That version-independent (not linked) URL should redirect always to the last report (if available), so currently to

 https://fossies.org/linux/misc/hpx-1.5.0.tar.gz/codespell.html

Ok, unsurprisingly only very few  misspellings and typos were found.

**Comment by hkaiser** [comment]
This is great! Thanks! @jschleus: what can we do in the future to get this kind of report before releasing things?

**Comment by jschleus** [comment]
@hkaiser: ... asking such a question ;-)

So there is now a similar and continuously updated report for the GitHub "master" version of "HPX" implemented which is available within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines:

 https://fossies.org/linux/test/hpx/codespell.html

That version independent URL hopefully always redirects to the report for the latest "master" version identified by the short commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The refresh rate is currently half-hourly.

By the way, just for information there exist also three supplemental pages showing some used [codespell configuration details](https://fossies.org/linux/test/hpx/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/test/hpx/codespell_fps.html) and an [misspelling history](https://fossies.org/linux/test/hpx/codespell_hist.html) (log).

**Comment by hkaiser** [comment]
@jschleus Nice, many thanks!

**Comment by jschleus** [comment]
Not important but just a reminder, since a new release candidate was tagged: On the web page

https://fossies.org/linux/test/hpx/codespell.html

are still some misspellings listed.

If there are false positives or misspellings that are not worth correcting, or are not correctable at all (e.g. in old "whats_new_xxx.rst" files), let me know.

**Comment by msimberg** [comment]
@jschleus thanks! It looks like at least some of those should indeed be fixed, I'll have a go at them. There may be some that we'll choose not to fix.

**Comment by hkaiser** [comment]
@msimberg let me take care of this.
