### ISSUE TITLE
1.5.0 breaks w/out CUDA: Error evaluating generator expression: $<COMPILE_LANG_AND_ID:CUDA,NVIDIA>

### ISSUE THREAD

**Issue by yurivict** [STEllAR-GROUP/hpx#4942]
```
-- Configuring done
CMake Error at cmake/HPX_GeneratePackageUtils.cmake:365 (file):
  Error evaluating generator expression:

    $<COMPILE_LANG_AND_ID:CUDA,NVIDIA>

  $<COMPILE_LANG_AND_ID:lang,id> may only be used with binary targets to
  specify include directories, compile definitions, and compile options.  It
  may not be used with the add_custom_command, add_custom_target, or
  file(GENERATE) commands.
Call Stack (most recent call first):
  cmake/HPX_GeneratePackage.cmake:83 (hpx_generate_pkgconfig_from_target)
  CMakeLists.txt:2629 (include)


CMake Error at cmake/HPX_GeneratePackageUtils.cmake:365 (file):
  Error evaluating generator expression:

    $<COMPILE_LANG_AND_ID:CUDA,NVIDIA>

  $<COMPILE_LANG_AND_ID:lang,id> may only be used with binary targets to
  specify include directories, compile definitions, and compile options.  It
  may not be used with the add_custom_command, add_custom_target, or
  file(GENERATE) commands.
Call Stack (most recent call first):
  cmake/HPX_GeneratePackage.cmake:83 (hpx_generate_pkgconfig_from_target)
  CMakeLists.txt:2629 (include)
```

OS: FreeBSD 12.1
clang-9

**Comment by msimberg** [comment]
@yurivict could you please post how you've configured HPX, including CMake version? That generator expression does not look like somthing we use internally in HPX.

**Comment by yurivict** [comment]
cmake is invoked:
```
cmake -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_EXE_LINKER_FLAGS:STRING="  -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING="  -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING="  -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DHPX_WITH_GENERIC_CONTEXT_COROUTINES:BOOL=ON -DHPX_WITH_EXAMPLES:BOOL=OFF -DHPX_WITH_TESTS:BOOL=OFF -GNinja -DPython_ADDITIONAL_VERSIONS=3.7 -DBOOST_PYTHON_SUFFIX:STRING=37
```

cmake-3.18.1

**Comment by msimberg** [comment]
Hmm, could be that some CMake module has changed in 3.18. Are you able to try with other CMake versions? I'm mostly guessing here since it's hard to tell where that would be coming from. Maybe even grepping the CMake modules for that expression could help (it's usually in something like `<prefix>/share/cmake-<version>/Modules`).

**Comment by yurivict** [comment]
Now I am trying cmake-3.19.4 with the current rev. 2ec0f88 and it still breaks.

Are you able to build with cmake-3.19.4?

**Comment by msimberg** [comment]
We test with 3.17, but I also regularly use 3.18, 3.19, and 3.20 without problems. This really seems like something from the CMake install. There's also a relevant discussion here https://github.com/STEllAR-GROUP/hpx/pull/5283#issuecomment-830083016. These generator expressions tend to be problematic for the pkgconfig file generation (CMake 3.20 would apparently give us a way to work around this, but that's a bit too recent).

@yurivict did you try grepping for that in the CMake directory?

**Comment by msimberg** [comment]
@yurivict FYI, I've just merged #5330 which doesn't fix the problem itself but gives you a way to work around it by setting `HPX_WITH_PKGCONFIG=OFF` (assuming you don't need pkgconfig support of course...).

**Comment by yurivict** [comment]
Adding ```-DECAL_BUILD_VERSION="5.8.9"``` doesn't fix the problem with number of arguments.

**Comment by msimberg** [comment]
> Adding `-DECAL_BUILD_VERSION="5.8.9"` doesn't fix the problem with number of arguments.

@yurivict I'm sorry, I'm not sure I see the relevance to this issue, could you please explain? Did you comment in the correct issue?

**Comment by yurivict** [comment]
Sorry, wrong issue. My bad.
