### ISSUE TITLE
Crash when not enabling TCP parcelport

### ISSUE THREAD

**Issue by kordejong** [STEllAR-GROUP/hpx#4949]
## Expected Behavior

- An error message explaining why things are not OK for the runtime
- Explanation in manual which parcelport to enable
- A CMake configuration error if this specific configuration is not supported

## Actual Behavior

Crash at startup of runtime. See [crash.txt](https://github.com/STEllAR-GROUP/hpx/files/5187096/crash.txt)

## Steps to Reproduce the Problem

  1. Configure HPX with MPI parcelport on and TCP parcelport off
  1. Start a run with multiple localities. I use `hpx::init`.

## Specifications

  - HPX Version: 1.5.0
  - Platform (compiler, OS): gcc 10.2.0, openmpi 4.0.4

## Remarks
- I was under the (possibly wrong) impression that when the MPI parcelport is turned on, the TCP parcelport is not necessary. When building with both MPI and TCP parcelports enabled, my program executes fine.
- When using a Debug build, the following assertions fails: `src/runtime/agas/big_boot_barrier.cpp:240`, `HPX_ASSERT(pp);`

**Comment by msimberg** [comment]
Thanks @kordejong, this should most likely not happen. We'll look into it (we have some related changes that need to be done as well, which may automatically take care of this: #4924).

**Comment by msimberg** [comment]
@kordejong while working on #4924 I could not reproduce your issue (neither with or without those changes, so my environment is likely different enough). I'm guessing #4924 doesn't fix things for you, but just in case, have you tried latest master? Do you explicitly pass any options to the application to enable or disable the MPI parcelport? How do you launch your applications (slurm, hpxrun, mpiexec)?

**Comment by kordejong** [comment]
I had a second look and this may well be a false negative, possibly because of a wrong set of command line arguments. I built HPX again with the above settings (tcp off, mpi on) and my tests succeed (hpxrun with the right arguments). It is probably OK to close this ticket. If I run into a crash again, even when using the wrong command line arguments, I will report again.

**Comment by hkaiser** [comment]
> I had a second look and this may well be a false negative, possibly because of a wrong set of command line arguments. I built HPX again with the above settings (tcp off, mpi on) and my tests succeed (hpxrun with the right arguments). It is probably OK to close this ticket. If I run into a crash again, even when using the wrong command line arguments, I will report again.

@kordejong Do you remember what command line arguments you were using that caused things to fail?

**Comment by kordejong** [comment]
@hkaiser No, not anymore unfortunately. But I plan to do similar scaling runs as I did some months ago. In case things go wrong I will report again. I now know tcp is not strictly required when mpi networking is turned on, so I will keep the tcp networking setting off when building HPX.

**Comment by kordejong** [comment]
This is still an issue. I am using 1.6.0 now. If I turn on `HPX_WITH_PARCELPORT_MPI` and turn off `HPX_WITH_PARCELPORT_TCP` the HPX job crashes when using more than one locality. My command line is very simple:

```
nr_nodes=2
nr_localities_per_node=8
nr_cores_per_locality=6

srun -N $nr_nodes -n $nr_localities_per_node -c $nr_cores_per_locality python my_script.py
```

This crashes (same assertion as above). When I build with `HPX_WITH_PARCELPORT_TCP` turned on, all is well.

I am happy to provide more details.

**Comment by kordejong** [comment]
Using the help from @hkaiser (mailinglist, different but related issue), I now know this issue is due to my srun not enabling MPI correctly / at all. When using mpirun all is well. Sorry for the noise.
