### ISSUE TITLE
HPX build failures with APEX enabled

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#4961]
## Expected Behavior

HPX builds

## Actual Behavior

HPX fails to build: http://omega.nic.uoregon.edu:8020/#/builders/5/builds/252
Some change checked in ~5 days ago has broken the build (see "changes" tab from above link)

## Steps to Reproduce the Problem

Configure HPX with APEX enabled.

  1. See http://omega.nic.uoregon.edu:8020/#/builders/5/builds/252
  1. 
  1.

## Specifications

... Please describe your environment

  - HPX Version: current master
  - Platform (compiler, OS): linux, gcc 7.3

**Comment by stevenrbrandt** [comment]
I've seen this problem, too.
