### ISSUE TITLE
Change feature test macros to expand to zero/one

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#4978]
This also requires to change all checks for a particular feature from
```
#if defined(HPX_HAVE_FOO)
// ...
#endif
```
to:
```
#if HPX_HAVE_FOO
// ...
#endif
```
This would allow to enable/disable certain capabilities in projects that depend on a pre-built HPX.

**Comment by msimberg** [comment]
Are there specific ones that you have in mind except things like the deprecation warnings? Some options we don't want(/"allow") users to change...

**Comment by hkaiser** [comment]
The specific one I ran into the other day was `HPX_HAVE_BUILTIN_INTEGER_PACK` that was detected as being available while building HPX but then later failed in a cling setting. However, I think you're right. The chance of breaking the ABI is very high and it's too risky to allow dependent projects to control the feature macros. I guess we should at least make sure that a user can forcefully disable certain features while building HPX, then (if its not already possible). I guess setting `-DHPX_WITH_BUILTIN_INTEGER_PACK=Off` at HPX configure time should prevent it from even feature tested.

**Comment by hkaiser** [comment]
> Setting `-DHPX_WITH_BUILTIN_INTEGER_PACK=Off` at HPX configure time should prevent it from even feature tested.

This seems to work as expected. I'm going to close this ticket as we have a way around the issues we were seeing.

**Comment by msimberg** [comment]
> The specific one I ran into the other day was `HPX_HAVE_BUILTIN_INTEGER_PACK` that was detected as being available while building HPX but then later failed in a cling setting. However, I think you're right. The chance of breaking the ABI is very high and it's too risky to allow dependent projects to control the feature macros. I guess we should at least make sure that a user can forcefully disable certain features while building HPX, then (if its not already possible). Setting `-DHPX_WITH_BUILTIN_INTEGER_PACK=Off` at HPX configure time should prevent it from even feature tested.

> > Setting `-DHPX_WITH_BUILTIN_INTEGER_PACK=Off` at HPX configure time should prevent it from even feature tested.
> 
> This seems to work as expected. I'm going to close this ticket as we have a way around the issues we were seeing.

Very good! Yes, I wouldn't want to recommend users to do this in the general, but turning those off should in most cases be safe. Turning them explicitly on is of course asking for trouble...
