### ISSUE TITLE
Potential 1.5.1 patch release

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4983]
The following could be included in 1.5.1:
- #4981 (plus a change in the Windows builders to test with C++17)
- #4972 
- #4974
- #4963
- #4946
- #4944

**Comment by msimberg** [comment]
Thanks @hkaiser for updating the list! I think we should go with the minimum non-breaking changes. The `parallel_executor` change is not 100% compatible so I'd prefer to leave that for 1.6.0 (and some release candidates). This way we can get the patch release out quickly and not have to worry about what exactly could or should be included.

**Comment by hkaiser** [comment]
> Thanks @hkaiser for updating the list! I think we should go with the minimum non-breaking changes. The `parallel_executor` change is not 100% compatible so I'd prefer to leave that for 1.6.0 (and some release candidates). This way we can get the patch release out quickly and not have to worry about what exactly could or should be included.

Fair point. I was not aware that the change is not fully backwards compatible. Let's not have it then.

**Comment by aurianer** [comment]
Adding #4939, #4941, #4951, #4982

**Comment by hkaiser** [comment]
@aurianer @khuck mentioned that he would like to add a new APEX tag. Is that still possible?

**Comment by aurianer** [comment]
So I already tag the release yesterday so that's actually not really possible as it notifies everyone who is watching the repo, also I believe our policy for patch releases (which fix only compilation/bug issues) is not to update the external libraries tags that's why I didn't ask, what do you think?
What does the tag include? In case it is really important I can still force push but I would like to avoid it since it notifies people a second time ^^'

**Comment by hkaiser** [comment]
> So I already tagged the release yesterday so that's actually not really possible as it notifies everyone who is watching the repo, also I believe our policy for patch releases (which fix only compilation/bug issues) is not to update the external libraries tags that's why I didn't ask, what do you think?
> What changes does the tag include? In case it is really important I can still force push but I would like to avoid it since it notifies people a second time ^^'

@khuck what do you say?

**Comment by khuck** [comment]
@aurianer @hkaiser It's not that critical.  At configuration time it can be overridden, so it doesn't have to go in to the release.

**Comment by aurianer** [comment]
Okay then I'll announce the release once ci have passed, the update of the tag went well btw
@khuck In case you change your mind and you need it in, we can still do a 1.5.2 release :)
