### ISSUE TITLE
New fundamentals module

### ISSUE THREAD

**Issue by K-ballo** [STEllAR-GROUP/hpx#4984]
This is a proposal for a new `fundamentals` module, consisting of fundamental language support utilities we rely on to implement everything else. It would have no dependencies other than `config`.

My suggestion for the initial content of this module are:

- `HPX_CONCEPT_REQUIRES/ASSERT`, ideally to be replaced by `requires` in some future.

- `HPX_NON_COPYABLE`, although I'd prefer to see this removed entirely (comes from a file called `emulate_deleted.hpp`, we don't need to emulate it anymore)

- `HPX_CAPTURE_FORWARD/HPX_CAPTURE_MOVE`, already deprecated.

- `HPX_INVOKE[_R]`, but not `util::invoke[_r]`.

- Range support: `begin`, `end`, possibly `size` and `empty`. These were initially implemented to circumvent some deficiencies in implementations of `std::begin/end`, it may be possible to use those by now in which case we can drop ours.

- `always_void`, consider adding `void_t` and using it instead.

- `decay`, this has been long deprecated (long before we had a deprecation attribute) and should have been phased out entirely by now. It was initially implemented in pre-11 times because `boost::decay` did not agree with proposed `std::decay`. 

- `decay_unwrap/unwrap_reference`, although these should be reconsidered now that the standard library is no longer giving `std::reference_wrapper` special status when it comes to deduction.

- _detection-idiom_? We shouldn't be using this in our implementations (and looks like we aren't). Alternatively, we should be using it everywhere in place of traditional SFINAE, and then it would belong in this module.

- `wrap_int`, but consider replacing it with a more explicit approach (like `priority<N>` tags).

- `lazy_conditional/lazy_enable_if`, ideally remove these entirely.

- `pack` utilities.

- `member_pack`?  I'm undecided... We should be using it whenever we need to hold a pack as a member, ideally to be replaced by plain `Ts ms...;` in some future. If adopted, it would be considered "built in", and serialization support would move to the `serialization` module.

- `void_guard`.

**Comment by K-ballo** [comment]
- `HPX_UNUSED`, possibly migrated to an attribute based implementation when available.

**Comment by hkaiser** [comment]
Should we add the `tag_invoke` facilities here as well?

**Comment by K-ballo** [comment]
> Should we add the `tag_invoke` facilities here as well?

Probably? The idea was to add facilities entirely dedicated to implement HPX itself (not for user consumption), with no other dependencies outside of this module (ideally no interdependencies either).
