### ISSUE TITLE
hpx::lcos::barrier() results in deadlock

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#5002]
## Expected Behavior

According to the documentation, using `hpx::lcos::barrier("barrier_name")` without specifying the number of localities or the rank should assume all the localities, and the current locality as the rank.

## Actual Behavior

Deadlock.

A similar problem is true for `gather_here()` and `broadcast_to()` - it requires at least the locality count to compile/work correctly.

## Steps to Reproduce the Problem

The Phylanx project is using HPX, and in a distributed run, APEX is using HPX collectives to do event unification at the end of execution.  

  1.  Configure HPX with MPI support and APEX enabled
  1.  Configure Phylanx
  1.  Run a Phylanx distributed example with the environment variable `APEX_OTF2=1` set.  It won't deadlock with the current code, but if these lines are changed to use default argument values, it will deadlock:
https://github.com/khuck/xpress-apex/blob/f666086dc469f48c220997d1b6b121e01d3c3afc/src/apex/otf2_listener.cpp#L1453
https://github.com/khuck/xpress-apex/blob/f666086dc469f48c220997d1b6b121e01d3c3afc/src/apex/otf2_listener.cpp#L1588

## Specifications

... Please describe your environment

  - HPX Version: current master
  - Platform (compiler, OS):  linux GCC 7

h/t @stevenrbrandt

**Comment by hkaiser** [comment]
This has been resolved by switching to the C++20 barrier implementation.

**Comment by gonidelis** [comment]
@hkaiser  Thanks!
