### ISSUE TITLE
Refactor Dataflow LCO to work with futures

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#504]
The dataflow LCO currently doesn't integrate very well with the rest of hpx futures. In order to efficiently use the dataflow LCO it needs to be rewritten in terms hpx::future. That means:
  1. Arguments are futures, not dataflow_base
  2. dataflow_base needs to completely vanish

During this refactoring #319 should be covered.

**Comment by hkaiser** [comment]
The only performance counter which seems to be useful in the context of the new `dataflow()` function would be to count how often it was invoked. If we create this performance counter we probably want to implement similar counters for other API functions as well. For this reason I'd say, let's go ahead with removing the dataflow component now and open a separate ticket for creating performance counters exposing the number of invocations for various API functions.
