### ISSUE TITLE
Adding HPX to task-bench

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#5062]
One question at the SC panel was, if we can add HPX to

- https://github.com/StanfordLegion/task-bench
- https://www.computer.org/csdl/pds/api/csdl/proceedings/download-article/1oeOToMWZBC/pdf

**Comment by msimberg** [comment]
Thanks for bumping this @diehlpk! We already have https://github.com/STEllAR-GROUP/hpx/issues/4274 so I'm going to close this one. I have marked the previous issue as high priority though. I had a quick look at the existing implementations and it looks like it wouldn't be a huge amount of work to add implementations using HPX. Now if only we could find a motivated student to do this... I think this is something we could look at at CSCS as well.
