### ISSUE TITLE
PAPI performance counters not available

### ISSUE THREAD

**Issue by JAPPinto** [STEllAR-GROUP/hpx#5105]
## Expected Behavior

I built HPX with the flag `-DHPX_WITH_PAPI:BOOL=ON` enabled. The lib/hpx subdirectory contains libhpx_papi_counters.so, libhpx_papi_counters.so.1 and libhpx_papi_counters.so.1.6.

When running an HPX application with the option `--hpx:papi-event-info=all` I should get a list of PAPI performance counters.

## Actual Behavior

Instead of a list of PAPI performance counters I get

`runtime_support::load_components: command line processing: unrecognised option '--hpx:papi-event-info=all`

If I use the option `--hpx:list-counters` the list does not include any PAPI performance counter.

## Steps to Reproduce the Problem

In the HPX build directory
1. cmake -DTCMALLOC_ROOT=/home/z/gperftools/ -DHPX_WITH_PAPI:BOOL=ON -DPAPI_ROOT=/home/z/papi/src ..
2. make papi_counters_component
3. make install

In the HPX application directory
1. cmake -DHPX_DIR=/home/z/hpx/build/lib/cmake/HPX/  ..
2. make 
3. ./program --hpx:papi-event-info=all

## Specifications

  - HPX Version: 1.5.1 
  - Platform : Linux

## Other information

ldd libhpx_papi_counters.so output:
https://gist.github.com/JAPPinto/9acc353711fff4781455c3341101819b

--hpx:debug-hpx-log=<filename> output:
https://gist.github.com/JAPPinto/b3e6fff5d9d9fc03d2a979e8f00bb279

--hpx:dump-config output:
https://gist.github.com/JAPPinto/a00c1e2c34cc0836e994f13e7c94a05b

papi component path:
/home/z/hpx/build/components/performance_counters/papi (should be under /home/z/hpx/build/lib/hpx)

output of cmake when building application:
https://gist.github.com/JAPPinto/aa62408501d2bd659439eb881d1a6c0c

output of cmake when building hpx:
https://gist.github.com/JAPPinto/e55ff9eeafa7fe22749cb621536c6813

## Remarks:

Copying the executable into the directory `/home/z/hpx/build/bin` and launching it from there worked.

**Comment by msimberg** [comment]
Does the same happen if you actually install HPX and build your application against the installed version? Currently you're building against the build directory which should also work but finding out if it only fails in that case would help us rule out some options.

**Comment by JAPPinto** [comment]
No. With the installed version it works as expected.

**Comment by msimberg** [comment]
Sorry @JAPPinto for not being more responsive here. Is this still an issue for you?

**Comment by JAPPinto** [comment]
No @msimberg, it is no longer an issue.
