### ISSUE TITLE
Tests don't get built

### ISSUE THREAD

**Issue by yurivict** [STEllAR-GROUP/hpx#5110]
First, I configure with ```HPX_WITH_EXAMPLES=OFF HPX_WITH_TESTS=OFF``` and build.

Then I reconfigure with ```HPX_WITH_EXAMPLES=OFF HPX_WITH_TESTS=ON HPX_WITH_TESTS_UNIT=ON``` and build.

After this all tests fail because of missing (not built) executables.

What is wrong?

hpx-1.2.1
FreeBSD 12.2

**Comment by sudo-panda** [comment]
To build and run tests you need to execute `make tests && make test` in the `build` folder(or wherever you ran `cmake`) as mentioned in the documentation here: https://hpx-docs.stellar-group.org/latest/html/contributing/testing_hpx.html#running-tests-manually

**Comment by yurivict** [comment]
```make tests && make test``` fails the same way.

I think this is related to me first building with ```HPX_WITH_EXAMPLES=OFF HPX_WITH_TESTS=OFF```.

**Comment by msimberg** [comment]
@yurivict could you provide the exact sequence of commands you ran together with the output? Is it possible that you only did `HPX_WITH_TESTS=ON` but left `HPX_WITH_TESTS_UNIT=OFF`?

**Comment by yurivict** [comment]
For the port build these cmake arguments are used:
```
-DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_EXE_LINKER_FLAGS:STRING="  -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING="  -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING="  -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DHPX_WITH_GENERIC_CONTEXT_COROUTINES:BOOL=ON -DHPX_WITH_EXAMPLES:BOOL=OFF -DHPX_WITH_TESTS:BOOL=OFF -GNinja -DPython_ADDITIONAL_VERSIONS=3.7 -DBOOST_PYTHON_SUFFIX:STRING=37
```

Then it is built with ninja.

Then for tests it is reconfigured by appending these arguments to the above cmake arguments:
```
-DHPX_WITH_TESTS:BOOL=ON -DHPX_WITH_TESTS_UNIT:BOOL=ON
```

Normally cmake is able to reconfigure with a new set of arguments. But in case of ```hpx``` tests aren't built.

**Comment by msimberg** [comment]
It's hard to say what could be going wrong without more context. Does this only happen in the port build or also when building manually? Does it happen with 1.5.1 (1.2.1 is rather old and we're unlikely to make any further changes to it)?
