### ISSUE TITLE
Tests fail to build with binary_filter plugins enabled

### ISSUE THREAD

**Issue by HungWoeiNeoh** [STEllAR-GROUP/hpx#5111]
## Problem Description
I was trying to build the tests with a HPX installation that has the `binary_filter` plugins enabled. I enabled `bzip2`, `snappy` and `zlib` support in the `cmake` configuration step. The HPX build and installation steps were successful.

## Expected Behavior
The tests would build properly when I run
```
make -j8 tests
```

## Failure 1
The command above fails on the target `put_parcels_with_coalescing_test` with the following output:

```
Scanning dependencies of target put_parcels_with_coalescing_test
[ 88%] Building CXX object tests/unit/parcelset/CMakeFiles/put_parcels_test.dir/put_parcels.cpp.o
[ 88%] Building CXX object tests/unit/parcelset/CMakeFiles/put_parcels_with_coalescing_test.dir/put_parcels_with_coalescing.cpp.o
In file included from /workspace/hpx/tests/unit/parcelset/put_parcels_with_compression.cpp:14:0:
/workspace/hpx/libs/full/include/include/hpx/include/compression_registration.hpp:12:10: fatal error: hpx/plugins/binary_filter/bzip2_serialization_filter_registration.hpp: No such file or directory
 #include <hpx/plugins/binary_filter/bzip2_serialization_filter_registration.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
tests/unit/parcelset/CMakeFiles/put_parcels_with_compression_test.dir/build.make:81: recipe for target 'tests/unit/parcelset/CMakeFiles/put_parcels_with_compression_test.dir/put_parcels_with_compression.cpp.o' failed
make[3]: *** [tests/unit/parcelset/CMakeFiles/put_parcels_with_compression_test.dir/put_parcels_with_compression.cpp.o] Error 1
CMakeFiles/Makefile2:88608: recipe for target 'tests/unit/parcelset/CMakeFiles/put_parcels_with_compression_test.dir/all' failed
make[2]: *** [tests/unit/parcelset/CMakeFiles/put_parcels_with_compression_test.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

## Initial Investigation
I noticed from the `make install` step that the header files for the `binary_filter` plugins are not installed, even though the `libhpx_compression_<library_name>.so` shared libraries are built. The directory `/usr/local/include/hpx/plugins` has the subdirectories `parcel` and `parcelport` but does not have the subdirectory `binary_filter`. Not sure if this is the reason tests are failing to build.

## Failure 2
What I tried to fix this was to manually create the directory `/usr/local/include/hpx/plugins/binary_filter` and manually copy all the header files into that directory. However, I came across a new error on the target `function_serialization_728_test` with the following output:

```
[ 37%] Linking CXX executable ../../../../../bin/function_serialization_728_test
CMakeFiles/function_serialization_728_test.dir/function_serialization_728.cpp.o: In function `hpx::serialization::detail::register_class_name<hpx::plugins::compression::zlib_serialization_filter, void>::factory_function()':
function_serialization_728.cpp:(.text._ZN3hpx13serialization6detail19register_class_nameINS_7plugins11compression25zlib_serialization_filterEvE16factory_functionEv[_ZN3hpx13serialization6detail19register_class_nameINS_7plugins11compression25zlib_serialization_filterEvE16factory_functionEv]+0x6d): undefined reference to `hpx::plugins::compression::detail::zlib_compdecomp::zlib_compdecomp(bool, boost::iostreams::zlib_params const&)'
collect2: error: ld returned 1 exit status
libs/core/functional/tests/regressions/CMakeFiles/function_serialization_728_test.dir/build.make:120: recipe for target 'bin/function_serialization_728_test' failed
make[3]: *** [bin/function_serialization_728_test] Error 1
CMakeFiles/Makefile2:24032: recipe for target 'libs/core/functional/tests/regressions/CMakeFiles/function_serialization_728_test.dir/all' failed
make[2]: *** [libs/core/functional/tests/regressions/CMakeFiles/function_serialization_728_test.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```
This looks like a linker error, and I don't really know why this is happening or how to fix this

## Source of Problem
The source of the issue is with the `binary_filter` plugins. I disabled the compression plugins and rebuilt and reinstalled HPX, and the tests build successfully.

## Steps to Reproduce This Problem
1. Install dependencies. Install BZip2, Snappy and ZLib
2. Run the `cmake` command in the specifications section below
3. Run
```
make -j8 && make -j8 install
```
4. Run
```
make -j8 tests
```

## Specifications
- HPX Version: Tried this on both the 1.5.1 stable release and the master branch
- Platform (compiler, OS): GCC 7.5.0 on Ubuntu 18.04
- Exact `cmake` command
```
cmake -DCMAKE_BUILD_TYPE=Release \
        -DHPX_WITH_COMPRESSION_BZIP2=ON \
        -DHPX_WITH_COMPRESSION_SNAPPY=ON \
        -DHPX_WITH_COMPRESSION_ZLIB=ON \
        -DHPX_WITH_CUDA=ON \
        -DHPX_WITH_GOOGLE_PERFTOOLS=ON \
        -DHPX_WITH_SANITIZERS=ON \
        -DHPX_WITH_VALGRIND=ON \
        ../hpx-1.5.1
```

**Comment by hkaiser** [comment]
This should have been resolved by #5725. Sorry it took so long.
