### ISSUE TITLE
libatomic problems causing unexpected fails

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#5112]
Applications may crash on startup with the following message
```
terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
  what():  big_boot_barrier has not been created yet: HPX(internal_server_error)
```
upon investigation, it turns out that the following exception is being thrown during initialization/startup
https://github.com/STEllAR-GROUP/hpx/blob/1527f3ba8055f795f701ddf89368f4a24199f79e/libs/full/threadmanager/src/threadmanager.cpp#L322-L329

which in turn causes the runtime destructor to be called, but the runtime has not yet started, so it throws the error that we actually see about the big boot barrier not being started. So the first exception needs to be caught somewhere and displayed, before the stack unwinds and throws the second.

Looking deeper, the problem is being caused by the following check failing during cmake configuration. 
```
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - not found
```
which in turn means that `HPX_WITH_CXX11_ATOMIC_128BIT` is not set. If I manually run the cmake feature check withoout linking libatomic, we see link errors
```
oryx2:~/build/hpx-master$ g++ ~/src/hpx/cmake/tests/cxx11_std_atomic_128bit.cpp
/usr/bin/ld: /tmp/ccduIFup.o: in function `std::atomic<uint128_type>::store(uint128_type, std::memory_order)':
cxx11_std_atomic_128bit.cpp:(.text._ZNSt6atomicI12uint128_typeE5storeES0_St12memory_order[_ZNSt6atomicI12uint128_typeE5storeES0_St12memory_order]+0x66): undefined reference to `__atomic_store_16'
/usr/bin/ld: /tmp/ccduIFup.o: in function `std::atomic<uint128_type>::load(std::memory_order) const':
cxx11_std_atomic_128bit.cpp:(.text._ZNKSt6atomicI12uint128_typeE4loadESt12memory_order[_ZNKSt6atomicI12uint128_typeE4loadESt12memory_order]+0x40): undefined reference to `__atomic_load_16'
collect2: error: ld returned 1 exit status
```
but if I add `-latomic` all is well.
```
oryx2:~/build/hpx-master$ g++ ~/src/hpx/cmake/tests/cxx11_std_atomic_128bit.cpp -latomic
oryx2:~/build/hpx-master$ <links correctly>
```

I have only run into this problem on my new laptop using gcc 10.2.0  

I'm not quite sure what the correct fix for the atomic problem is.

**Comment by msimberg** [comment]
I opened #5113 for the threadmanager issue.

Do you find that symbol in libatomic if you check manually? I think we have that check there because libatomic isn't even always a separate library so we have to check that it's there in the first place.

**Comment by biddisco** [comment]
I made a small test based on the LLVM atomics cmake detection code and get this
```
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Success
-- Performing Test HAVE_CXX_ATOMICS128_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS128_WITHOUT_LIB - Failed
```
so it appears as expected, that **with my compiler** `-latomic` is not needed for 32/64 bit operations, but is needed for 128 bit operations. Out tests do something different and I wonder if I should just replace them with the LLVM versions.

**Comment by msimberg** [comment]
I think that's normal. The question is why `check_library_exists(atomic __atomic_fetch_add_4 "" HPX_HAVE_LIBATOMIC)` fails. Either it's not finding libatomic at all, or it's not finding `__atomic_fetch_add_4` in there. Is it possible that libatomic only has the 128 bit versions since the rest are not needed? Does libatomic have `__atomic_fetch_add_16` but not `__atomic_fetch_add_4`?

**Comment by biddisco** [comment]
The checks we implement end up setting `HPX_CXX11_STD_ATOMIC_LIBRARIES` to `atomic` - but as far as I can see, not only are the tests not working, but the variable `HPX_CXX11_STD_ATOMIC_LIBRARIES` is never actually used anywhere!

**Comment by msimberg** [comment]
@biddisco libatomic is added here if it's available: https://github.com/STEllAR-GROUP/hpx/blob/598104732c7decfde49e9bf40429ccf724705087/CMakeLists.txt#L1788.

**Comment by biddisco** [comment]
> @biddisco libatomic is added here if it's available:
> 
> https://github.com/STEllAR-GROUP/hpx/blob/598104732c7decfde49e9bf40429ccf724705087/CMakeLists.txt#L1788
> .

Aha. very good. Then I should modify my PR to replace that with
```
if (HPX_CXX11_STD_ATOMIC_LIBRARIES)
 target_link_libraries(hpx_base_libraries INTERFACE ${HPX_CXX11_STD_ATOMIC_LIBRARIES})
endif()
```
