### ISSUE TITLE
Lock held while suspending

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#5118]
@stevenrbrandt reported a 'lock being held' error in Phylanx here: https://github.com/STEllAR-GROUP/phylanx/issues/1307.

**Comment by msimberg** [comment]
https://github.com/STEllAR-GROUP/hpx/pull/5117#issuecomment-767518636 looks like another case of the same lock being held. However, there's no obvious lock being held (or not ignored) at that point in HPX...

**Comment by hkaiser** [comment]
> [#5117 (comment)](https://github.com/STEllAR-GROUP/hpx/pull/5117#issuecomment-767518636) looks like another case of the same lock being held. However, there's no obvious lock being held (or not ignored) at that point in HPX...

Yes, I tried to look into this and was not able to spot anything either :/

**Comment by hkaiser** [comment]
Closing this as 'won't fix' as Phylanx is not being actively developed anymore.
