### ISSUE TITLE
Use std::string for task annotations

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#5126]
Currently we use `char const*` strings for task annotations. This makes it impossible to use dynamically generated tasked names because the strings might be gone by the time they are used.

The main reason I can see for not using `std::string`s is to avoid dynamic allocation for task descriptions and annotations. However, I would guess that this is insignificant compared to overheads caused by having to e.g. log task data in the first place, and other overheads related to our tasks. @khuck does your experience tell us that we should in fact stick to C-style static strings for the annotations or do you see no problem with starting to use `std::string`.

@khuck a somewhat related question that came as a request from a user: what facilities does APEX have for storing metadata related to tasks and to write these to OTF2 files? It's related to this issue in the sense that one might want to write metadata to the task name dynamically, but if there were a separate place to put that metadata it might be more ergonomic than having to stick it in the task name. If there is such a facility in APEX it's of course another question if and how to expose that to users.

**Comment by hkaiser** [comment]
@msimberg the rationale to use `char const*` for the task description is indeed to avoid allocations. Instead of changing that to generally use `std::string`, I'd rather have a facility that allows to manage a `std::string` as a description for a particular task externally in such a way that it keeps the description alive as long as needed.

**Comment by khuck** [comment]
Hmm...if you want optional _per task_ metadata, that would be somewhat straightforward but would require some API changes.  Are you thinking of a map of key/value pairs of strings?  Or a `std::list< std::pair<std::string,std::string> >`?  Currently with every HPX thread we generate and store a GUID for that task, and the GUID of its parent (if known).  Those are stored in OTF2 traces as attributes on the timer.  So if the timer has additional attributes, we would just add them.

But like I said, that would require an update to `apex::new_task()`, likely to add an optional argument to this call: http://www.nic.uoregon.edu/~khuck/apex_docs/doc/html/namespaceapex.html#aaab84a4343c5ceaccfc8459eac56bd7c

**Comment by khuck** [comment]
@msimberg ...I forgot to address the main point - I think all code paths construct a `std::string` almost immediately from the  `char const* name` string.  So why can't it be generated?  Are you concerned a temporary will get destroyed before that could happen?

**Comment by khuck** [comment]
...oh, I stand corrected - inside of HPX, the thread_description stays as a `char const *`:
https://github.com/STEllAR-GROUP/hpx/blob/0b6df0d6adeed861776c990c1e236cc4a8413b32/libs/core/threading_base/include/hpx/threading_base/thread_description.hpp#L41

However, APEX will make a string out of it almost immediately.  Other tools (ITT, for example) would be vulnerable to corruption if the string went away.

**Comment by msimberg** [comment]
@hkaiser I suppose `annotated_function` could work exactly for that purpose. It doesn't have to be `std::string` all the way down, even though from what @khuck says it might not make a difference.

@khuck yes, the problem is indeed that temporaries go away before the annotations go over to APEX, so this is a problem entirely in HPX. As for the metadata, that sounds about like what could be useful. I'll let @albestro comment on whether that would be enough or not. However, I think just allowing dynamically generated names will get us much further already.

**Comment by albestro** [comment]
Thank you all for considering this issue.

I'm working with a library based on HPX and it would be nice to have in the toolbox a tracing/profiling that allows to identify tasks of a specific group or even individually. This eases the debugging and the identification of problems like wrong dependencies or other problems related to scheduling (e.g. priorities).

Currently, `annotated_function` allows specifying the name of the task and my first try was to embed some very basic info in it, e.g. `send_col` or `task_1_3`. Unfortunately, they required to be STATIC strings (and I trivially got random characters as result).

I don't know the OTF2 file format, but with this problem in mind, I see that the OTF2 viewer contemplates also other fields/metadata, e.g. group or type. But, as already said by @msimberg, I agree that just allowing for dynamic strings would represents a very big step forward that will help a lot.

**Comment by hkaiser** [comment]
> @hkaiser I suppose `annotated_function` could work exactly for that purpose. It doesn't have to be `std::string` all the way down, even though from what @khuck says it might not make a difference.

I agree - something like `annotated_function` would be perfect for this (if we can make sure the pointer is stable). And yes, it may not make a difference if APEX is involved. 

We made the decision to use a plain `char const*` in the thread data back in the day for good reasons. This avoids allocations and avoids locking when accessing the thread description. I think we should leave it that way there. 

Alternatively, we could have a global (sigh) map for those strings either as a supported facility or in user code to achieve similar effects. However storing the string on the stack of the thread itself might be the easiest and least impactful solution.
