### ISSUE TITLE
Searching for HPX-Application to generate work on multiple Nodes

### ISSUE THREAD

**Issue by leonfse** [STEllAR-GROUP/hpx#5143]
Hello, I am looking for an open source HPX-Application, which I can use to generate work on multiple Nodes, in order to analyse the performance of said application.

Any ideas, suggestions and experiences are very welcome,
Leon

**Comment by AmosLewis** [comment]
Any hpx + cuda + multiple nodes example?

**Comment by hkaiser** [comment]
> Any hpx + cuda + multiple nodes example?

HPX distributed work and CUDA are orthogonal and unrelated. You should be able to combine these two easily.

**Comment by leonfse** [comment]
For me HPX without any other Libraries would be most fitting.
Can any of the Examples in this GitHub Repository put multiple Nodes to work?

**Comment by msimberg** [comment]
@leonfse I suppose the 1D stencil examples in `examples/1d_stencil` would be one (simple) option. I think starting from `1d_stencil_5` they are distributed. https://github.com/STEllAR-GROUP/tutorials/tree/master/examples/03_stencil also contains a 2D stencil example, although it may need some tweaking to make it work again with the latest version of HPX.
