### ISSUE TITLE
Wrong results with parallel reduce 

### ISSUE THREAD

**Issue by dhinf** [STEllAR-GROUP/hpx#5147]
## Expected Behavior
While the sequential version of reduce has the correct result, the parallel version doesn't. Maybe I'm missing something, but the parallel reduce version of the standard library does it correct.

## Actual Behavior

The result outputs of the reference sum and the reduce algorithm with  different  executers are as following: 
sum ref: 40425
sum_hpx_reduce_seq: 40425
sum_hpx_reduce_par: 121989585
sum_hpx_reduce_par_future: 121989585

## Steps to Reproduce the Problem

```c++
#include <hpx/hpx.hpp>
#include <hpx/hpx_start.hpp>
#include <hpx/hpx_suspend.hpp>

#include <iostream>
#include <vector>

constexpr long SIZE = 50;

int main(int argc, char* argv[])
{
  std::vector<long> test_vec(SIZE);

  long sum_ref = 0;

  for(long i = 0; i < test_vec.size(); ++i) {
    test_vec[i] = i;
  }

  for(const auto& elem : test_vec) {
    sum_ref += elem * elem;
  }

  hpx::start(nullptr, argc, argv);

  auto sum_red = hpx::reduce(hpx::execution::seq,test_vec.begin(), test_vec.end(), long(0),
      [](const long& a, const long& b) { return a + b * b; });

  auto sum_hpx_red = hpx::reduce(hpx::execution::par,test_vec.begin(), test_vec.end(), long(0),
      [](const long& a, const long& b) { return a + b * b; });

  auto sum_hpx_red_future = hpx::reduce(
      hpx::execution::par(hpx::execution::task),test_vec.begin(), test_vec.end(), long(0),
      [](const long& a, const long& b) { return a + b * b; });

  std::cout << "sum ref: " << sum_ref << "\n"
            << "sum_hpx_reduce_seq: " << sum_red << "\n"
            << "sum_hpx_reduce_par: " << sum_hpx_red << "\n"
            << "sum_hpx_reduce_par_future: " << sum_hpx_red_future.get() << "\n"
            << std::endl;

  hpx::apply([](){hpx::finalize();});
  hpx::stop();

  return 0;
}
```

## Specifications

happens with HPX 1.5.1 and the current master e6a757ff58d9af9ebb42112b1944df809ca6ddf2
Arch Linux
gcc 10.2.0

compiled with:
hpxcxx  --exe=reduce reduce.cpp

**Comment by msimberg** [comment]
This is not a bug. Quoting [cppreference](https://en.cppreference.com/w/cpp/algorithm/reduce): "The behavior is non-deterministic if binary_op is not associative or not commutative." `a + b * b` is neither of those.

The reason for this restriction is that when the algorithm runs in parallel the reduction is done first on parts of the input on different worker threads, and the partial results from each worker thread are then combined in a second step.

What you want to use in this case is `hpx::transform_reduce`, or even better `hpx::ranges::transform_reduce`:

```
hpx::ranges::transform_reduce(
    hpx::execution::par, test_vec, long(0),
    [](const long a, const long b) { return a + b; },
    [](const long a) { return a * a; });
```

This gives the expected result also when using the `par` policy.

**Comment by dhinf** [comment]
thx @msimberg . I found my mistake ("The behavior is non-deterministic if binary_op is not associative or not commutative." a + b * b) shortly before  i went to bed yesterday. And you were faster then me to point it out today. So thanks for the fast response. For bigger number the standard library shows undef. behavior too.
