### ISSUE TITLE
Separate the datapar algorithms 

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#5157]
Currently, our parallel algorithms support being used with the `datapar` execution policy. This is a remnant of an older standardization proposal. This implementation is currently tightly entangled with the implementation of the parallel base algorithms.  

We should do two things:

- separate the datapar implementations and expose them through separate algorithm specializations (based on the `tag_invoke` customization point mechanism we have implemented)
- adapt the implementation to support (and rely on) the data-parallel Types introduced by [N4755](https://wg21.link/n4755), section 9, this implies removing `datapar` as it is today,

This work could also go hand-in-hand with #2271.

**Comment by toktarev** [comment]
I've started working on this issue

**Comment by hkaiser** [comment]
@toktarev Please coordinate with @srinivasyadav18 as he is looking into related tasks.

**Comment by toktarev** [comment]
Do we really need to "separate the datapar implementations" if we are going to "removing datapar as it is today" ?
