### ISSUE TITLE
Performance counter module not loading

### ISSUE THREAD

**Issue by JAPPinto** [STEllAR-GROUP/hpx#5216]
## Expected Behavior

I was trying to implement a full performance counter, based on this example https://github.com/STEllAR-GROUP/hpx/tree/master/examples/performance_counters/sine.

I started by replacing all the occurrences of sine in the  code and in the file names. In principle the example should still work after these changes.

## Actual Behavior

Instead, the new counter was not recognized, meaning that the module was not loaded.

Copying the generated counter module to $(hpx_root)/lib/hpx and changing the file name from libexample.so to libhpx_example.so (in order to match the format of the other files in the folder) works.

## Steps to Reproduce the Problem

HPX was installed with:
1. `cmake -DHPX_WITH_PAPI:BOOL=ON`
2. `make install`

Steps for the problem itself:
1. Copied the example in `examples/performance_counters/sine` to a project external to HPX 
1. Replaced "sine" with "example" in CMakeLists.txt, source code and file names.
2. Using the flag --example resulted in `runtime_support::load_components: command line processing: unrecognised option '--example'`
4. Not using any flag resulted in ` unknown counter type /example/immediate/explicit: HPX(bad_parameter)`

## Specifications

  - HPX Version: 1.5.1 
  - Platform : Linux (Mint 20)

**Comment by aurianer** [comment]
As suggested in the IRC chat, can you try removing the two `INTERNAL_FLAGS` in the corresponding CMakeLists.txt? :)

**Comment by aurianer** [comment]
Actually it should have no incidence on the library name sorry

**Comment by aurianer** [comment]
@hkaiser any ideas? I'm not too familiar with the papi counters

**Comment by hkaiser** [comment]
> @hkaiser any ideas? I'm not too familiar with the performance counters

This is a general problem with loading plugin modules under certain circumstances. I'll try to investigate this in more detail.
