### ISSUE TITLE
Build and link errors with ittnotify enabled

### ISSUE THREAD

**Issue by dhinf** [STEllAR-GROUP/hpx#5222]
## Expected Behavior

I tried to build hpx with the flags -DHPX_WITH_ITTNOTIFY=ON -DAMPLIFIER_ROOT=/opt/intel-ittapi/inst

I used https://github.com/intel/ittapi for the amplifier.

## Actual Behavior and Steps to Reproduce the Problem

1. missing include error -> it seems the cmake environment doesn't sets the include path
```zsh
/opt/hpx/src/hpx-1.6.0/libs/core/itt_notify/src/itt_notify.cpp:15:10: fatal error: ittnotify.h: No such file or directory
   15 | #include <ittnotify.h>
```
   -> solved by setting CPATH

2. compile error:
```zsh
   /opt/hpx/src/hpx-1.6.0/libs/core/itt_notify/src/itt_notify.cpp: In constructor 'hpx::util::itt::thread_domain::thread_domain()':
   /opt/hpx/src/hpx-1.6.0/libs/core/itt_notify/src/itt_notify.cpp:267:9: error: class 'hpx::util::itt::thread_domain' does not have any field  named 'domain_'
267 |       : domain_()
```
   -> fixed by replacing : domain_() with domain()   //calling now default constructor instead of base class member

3. link error Linking CXX shared library ../lib/libhpx_core.so , same problem as 1.
   -> fixed with manual linking

4. compile error: 
```zsh
In file included from /opt/hpx/src/hpx-1.6.0/libs/full/actions_base/include/hpx/actions_base/component_action.hpp:12,
                 from /opt/hpx/src/hpx-1.6.0/libs/full/agas/include/hpx/agas/server/primary_namespace.hpp:16,
                 from /opt/hpx/src/hpx-1.6.0/libs/full/agas/src/primary_namespace.cpp:12:
/opt/hpx/src/hpx-1.6.0/libs/full/actions_base/include/hpx/actions_base/basic_action.hpp:49:10: fatal error: hpx/concurrency/itt_notify.hpp: No such file or directory
   49 | #include <hpx/concurrency/itt_notify.hpp>
```

## Specifications

... Please describe your environment

  - HPX Version: 1.6.0 and current master 09ec51f07a59c89b614806f9ceee17d057cb35e7
  - Platform (compiler, OS): Arch Linux
  - Compiler: gcc 10.2.0

**Comment by hkaiser** [comment]
@dhinf yes, that's what I would expect to happen. The build system support we have only supports the Intel Amplifier tool. I'll try to have a look into making it more generic. If you want, please feel free to try modifying the build system yourself. The detection is done here: https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/FindAmplifier.cmake. You might even be able to make it work by setting the `AMPLIFIER_ROOT` cmake variable.

**Comment by dhinf** [comment]
The include and library path was correctly found in the config phase. That's, why I expected that the paths are used in the build process.

**Comment by hkaiser** [comment]
@dhinf FWIW, I have the issue reproduced locally. We don't test for this regularly (which we probably should do), which caused the problems you're seeing. I will create a PR soon.

**Comment by dhinf** [comment]
The only reason I found the bug was because you suggested in issue #5124 to use ittapi. :)
Thanks for fix. Hopefully, we are able to get enough information via ittnotify to instrument hpx applications with Score-P.

**Comment by hkaiser** [comment]
@dhinf see #5223 for a possible fix, please let us know if this works as expected. Generally, the ITTNotify support should be considered experimental, so please let us know if something is not quite right or if you would like to have more pieces of HPX instrumented.

**Comment by dhinf** [comment]
@hkaiser Thanks for the fix.
