### ISSUE TITLE
Annotation using hpx::util::annotated_function not working

### ISSUE THREAD

**Issue by severinstrobl** [STEllAR-GROUP/hpx#5232]
## Expected Behavior

Annotating a function using `hpx::util::annotated_function` should have the same effect as using `hpx::util::annotate_function` inside of the function.

## Actual Behavior

Annotation via `hpx::util::annotated_function` does not seem to work at all, the information is lost at some point and not passed on to the instrumentation framework APEX.

## Steps to Reproduce the Problem

An example using the two methods to annotate a lambda function and the respective output is available [here](https://gist.github.com/severinstrobl/23db96ccf205684e5d4145c8847cb166).

## Specifications

  - HPX Version: 1.6.0
  - Platform (compiler, OS): GCC 10.2.0, Linux
  - HPX Configuration:
  ```shell
-DHPX_WITH_CXX14:BOOL=ON -DHPX_WITH_MALLOC:STRING=system -DHPX_WITH_CUDA:BOOL=OFF -DHPX_WITH_TOOLS:BOOL=OFF -DHPX_WITH_EXAMPLES:BOOL=OFF -DHPX_WITH_ASYNC_MPI:BOOL=ON -DHPX_WITH_ASYNC_CUDA:BOOL=OFF -DHPX_WITH_TESTS:BOOL=OFF -DHPX_WITH_NETWORKING:BOOL=ON -DHPX_WITH_PARCELPORT_TCP:BOOL=OFF -DHPX_WITH_PARCELPORT_MPI:BOOL=ON -DHPX_WITH_MAX_CPU_COUNT:STRING=64 -DHPX_WITH_GENERIC_CONTEXT_COROUTINES:BOOL=OFF -DHPX_WITH_BOOST_ALL_DYNAMIC_LINK:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DHPX_DATASTRUCTURES_WITH_ADAPT_STD_TUPLE:BOOL=OFF -DHPX_WITH_VALGRIND:BOOL=OFF -DHPX_WITH_APEX:BOOL=ON -DHPX_WITH_GOOGLE_PERFTOOLS:BOOL=OFF -DHPX_WITH_PAPI:BOOL=OFF -DAPEX_WITH_OTF2:BOOL=ON
  ```

**Comment by msimberg** [comment]
I suspect it may be the newly added projection (which defaults to the identity projection) that hides the annotation. I'll put a PR in a bit for you to try out.

**Comment by severinstrobl** [comment]
Let me know if there is anything on my end I can do to help with that.
