### ISSUE TITLE
HPX fails to build on ppc64le

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/hpx#5246]
## Expected Behavior

building

## Actual Behavior

The build fails with:

```
[ 19%] Linking CXX shared library ../lib/libhpx_cored.so
../lib/libhpx_coroutinesd.a(context_base.cpp.o):(.toc+0x18): undefined reference to `hpx::threads::coroutines::detail::posix::ucontext_context_impl_base::default_stack_size'
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libhpx_cored.so] Error 1
make[1]: *** [libs/CMakeFiles/hpx_core.dir/all] Error 2
make: *** [all] Error 2
```

## Steps to Reproduce the Problem

  1.  Using current master
  1.  `cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local/packages/hpx/2021-03-17/install -DHPX_WITH_MALLOC=tcmalloc -DHPX_WITH_THREAD_IDLE_RATES=ON -DHPX_WITH_PARCELPORT_MPI=ON -DHPX_WITH_PARCEL_COALESCING=ON -DHPX_WITH_TOOLS=OFF -DHPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=OFF -DHPX_WITH_APEX=TRUE -DHPX_WITH_APEX_NO_UPDATE=TRUE -DAPEX_WITH_ACTIVEHARMONY=TRUE -DAPEX_WITH_CUDA=TRUE -DAPEX_WITH_OTF2=TRUE -DAPEX_WITH_PAPI=TRUE -DAPEX_WITH_BFD=TRUE -DBOOST_ROOT=/home/users/khuck/src/hpx/boost_ppc64le_1.73.0 -DTCMALLOC_ROOT=/usr/local/packages/gperftools/2.5 -DACTIVEHARMONY_ROOT=/usr/local/packages/activeharmony/4.6.0-ppc64le -DOTF2_ROOT=/usr/local/packages/otf2/2.1-ppc64le -DPAPI_ROOT=/usr/local/packages/papi/5.7.0 -DHPX_WITH_APEX_TAG=develop -DBFD_ROOT=/usr/local/packages/binutils/2.25 -DLM_SENSORS_ROOT=/usr -DHPX_WITH_MAX_CPU_COUNT=160 /scratch/khuck/hpx/src`
  1.  make

## Specifications

... Please describe your environment

  - HPX Version:  current master
  - Platform (compiler, OS):  ppc64le on POWER9, using gcc 7.3, openmpi 4.0 and cuda 10.1, and cmake 3.19.6

**Comment by hkaiser** [comment]
@khuck this variable is defined here: https://github.com/STEllAR-GROUP/hpx/blob/master/libs/core/coroutines/src/detail/posix_utility.cpp. Could you please add a:
```
      ... || defined(__ppc__) || defined(__ppc) || defined(__powerpc__) \\
          || defined(_ARCH_COM) || defined(_ARCH_PWR) || defined(_ARCH_PPC)  \\
          || defined(_M_MPPC) || defined(_M_PPC)
```
(or similar) to the `#if` condition to see if that fixes your issue?

**Comment by khuck** [comment]
@hkaiser that fixed it for one file, but then the next failure was:

```
[ 19%] Linking CXX shared library ../lib/libhpx_cored.so
../lib/libhpx_coroutinesd.a(context_base.cpp.o):(.toc+0x18): undefined reference to `hpx::threads::coroutines::detail::posix::ucontext_context_impl_base::default_stack_size'
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libhpx_cored.so] Error 1
make[1]: *** [libs/CMakeFiles/hpx_core.dir/all] Error 2
make: *** [all] Error 2
```
and that happened even with a change to context_impl.hpp. (although I don't know if I changed it correctly)

**Comment by khuck** [comment]
@hkaiser I do get a ton of these warnings now:
```
/scratch/khuck/hpx/src/libs/core/coroutines/include/hpx/coroutines/detail/context_posix.hpp:286:21:warning: unused parameter ‘signum’ [-Wunused-parameter]
                 int signum, siginfo_t* infoptr, void* ctxptr)
                     ^~~~~~
```
...which I addressed with `HPX_UNUSED(signum);`

**Comment by hkaiser** [comment]
@khuck sorry it took so long to get back. Could you give us a patch (or a PR) reflecting your changes, please?

**Comment by khuck** [comment]
Actually, I think it works now because Patrick has been building on Summit.  I will double check but I don't think it's still a problem.
