### ISSUE TITLE
Allow triggering the output of OS thread affinity from configuration settings

### ISSUE THREAD

**Issue by severinstrobl** [STEllAR-GROUP/hpx#5257]
When initializing HPX solely via `hpx::init_params.cfg` it seems to not be possible to trigger certain functionality such as printing the OS thread affinity information. I found no way to pass the equivalent of the command line switch `--hpx:print-bind` using the configuration object, am I missing something here?

## Specifications

  - HPX Version: 1.6.0
  - Platform (compiler, OS): GCC 10.2.0, Linux

**Comment by hkaiser** [comment]
Wouldn't this work:
```
int hpx_main(int argc, char* argv[])
{
    return hpx::finalize();
}

int main(int argc, char* argv[])
{
    std::vector<std::string> cfg = {"--hpx:print-bind" };
    hpx::init_params params;
    params.cfg = std::move(cfg);
    return hpx::init(argc, argv, params);
}
```

**Comment by severinstrobl** [comment]
No, that seems to be just ignored, unless I'm doing something silly here. I think the problem might be that only the actual command line is taken into account [here](https://github.com/STEllAR-GROUP/hpx/blob/76a2ba5b266008be5e0d5a13e17ae0950099dde2/libs/full/runtime_distributed/src/server/runtime_support_server.cpp#L1049)?

**Comment by hkaiser** [comment]
> No, that seems to be just ignored, unless I'm doing something silly here. I think the problem might be that only the actual command line is taken into account [here](https://github.com/STEllAR-GROUP/hpx/blob/76a2ba5b266008be5e0d5a13e17ae0950099dde2/libs/full/runtime_distributed/src/server/runtime_support_server.cpp#L1049)?

Indeed, excellent catch!

**Comment by hkaiser** [comment]
@severinstrobl please have a look at #5259 to verify it fixes your problem

**Comment by severinstrobl** [comment]
@hkaiser That does it, thanks for looking into this so quickly.

One more related question: How can one determine the correct way to pass the various options as configuration options? As an example: Many examples use `hpx.run_hpx_main!=1`, which seems to correspond to passing `--hpx:run-hpx-main` via the command line, but I cannot find that in the [docs](https://hpx-docs.stellar-group.org/latest/html/manual/launching_and_configuring_hpx_applications.html#the-hpx-ini-file-format). And for `--hpx:print-bind` and friends there does not seem to be a corresponding mapping.

**Comment by hkaiser** [comment]
> @hkaiser That does it, thanks for looking into this so quickly.
> 
> One more related question: How can one determine the correct way to pass the various options as configuration options? As an example: Many examples use `hpx.run_hpx_main!=1`, which seems to correspond to passing `--hpx:run-hpx-main` via the command line, but I cannot find that in the [docs](https://hpx-docs.stellar-group.org/latest/html/manual/launching_and_configuring_hpx_applications.html#the-hpx-ini-file-format). And for `--hpx:print-bind` and friends there does not seem to be a corresponding mapping.

There is no direct correspondence and no consistent mapping. This has grown historically. The easiest way is to always use the command line options, those will be mapped properly to the corresponding configuration settings.

**Comment by severinstrobl** [comment]
Whenever possible this is what I do. I do have an application where HPX is used in a Python-wrapped library, there I use the configuration directly. So I'll just stick to trial-and-error in this case :grin:

**Comment by hkaiser** [comment]
> Whenever possible this is what I do. I do have an application where HPX is used in a Python-wrapped library, there I use the configuration directly. So I'll just stick to trial-and-error in this case 😁

Please feel free to share any useful information for the docs. We always welcome PRs for the docs ;-)
