### ISSUE TITLE
Add support for known failures and warning count/comparisons to hpx_run_tests.py

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/hpx#528]
hpx_run_test.py should support:
- [x] Tests that are expected to fail (it may already do this)
- [ ] Tests that are currently known to fail
- [x] Some mechanism for counting failures/comparing failures

**Comment by msimberg** [comment]
Is this still relevant?

**Comment by sithhell** [comment]
I think we can safely close this at the moment for not being relevant any more.
