### ISSUE TITLE
command-line config error selecting parcelport when using wrap_main

### ISSUE THREAD

**Issue by biddisco** [STEllAR-GROUP/hpx#5296]
I noticed an odd bug when testing the libfabric parcelport

When testing to make sure that the correct parcelport is selected and used, I compiled hpx with tcp/mpi/libfabric all present, then use the following command line that has `enable` libfabric but `disable` tcp and mpi and I set the `bootstrap` parcelport to be libfabric
```
bin/hello_world_distributed --hpx:threads=1 -Ihpx.parcel.bootstrap=libfabric -Ihpx.parcel.libfabric.enable=1 -Ihpx.parcel.tcp.enable=0 -Ihpx.parcel.mpi.enable=0 -Ihpx.parcel.message_handlers=0 --hpx:node=0 --hpx:localities=2
```
This combination of commandline flags works in the tests I'm developing, but I noticed that when using `hello_world_distributed` I get an exception because the bootstrap parcelport is being set to tcp (the default is used internally and returned from `get_bootstrap_parcelport`).

If I add `--hpx:ini=hpx.parcel.bootstrap=libfabric` to the commandline, then the behaviour is restored to normal
```
bin/hello_world_distributed --hpx:threads=1 --hpx:ini=hpx.parcel.bootstrap=libfabric -Ihpx.parcel.bootstrap=libfabric -Ihpx.parcel.libfabric.enable=1 -Ihpx.parcel.tcp.enable=0 -Ihpx.parcel.mpi.enable=0 -Ihpx.parcel.message_handlers=0 --hpx:node=0 --hpx:localities=2
```
and it runs as expected. The difference between `hello_world_distributed` and the other tests I'm working on is that it uses `wrap_main` and does not have a regular `int main` entry point containing `hpx::init`. Something must be different in the init phase of command line handling when using the wrap main feature. I have not investigated further.

**Comment by hkaiser** [comment]
Could you please construct the smallest possible example that reproduces your issue?

**Comment by biddisco** [comment]
The problem seems to be that the runtime ignores `-Ihpx.parcel.bootstrap=libfabric` but honours `--hpx:ini=hpx.parcel.bootstrap=libfabric` when using wrap_main, but when using hpx::init by hand, it works fine with `-Ihpx.parcel.bootstrap=libfabric`
