### ISSUE TITLE
Rename P2220 property CPOs?

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#5345]
Related to #5341.

https://wg21.link/p2220 proposes to use `tag_invoke` for properties. One of the naming conventions it uses to require a property on something is `make_with_x`. This can unfortunately be quite verbose. E.g.:
```
// p1393
auto new_exec = require(exec, hint);
// p2220
auto new_exec = make_with_hint(exec, hint);
```
The difference is bigger when using prefer:
```
// p1393
auto new_exec = prefer(exec, hint);
// p2220
auto new_exec = prefer(make_with_hint, exec, hint);
```

This is very much a bikeshedding topic, and it's possible that renaming these properties won't make much of a difference, but it's worth at least considering. The only alternatives I can think of at the moment are:
- Drop the `make_` prefix to get e.g. `prefer(with_hint, exec, hint)`
- Use `add` as a prefix, e.g. `prefer(add_hint, exec, hint)`

Renaming is more of a partial fix though. Using `tag_invoke` is inherently more verbose than the P1393 approach. Or?

**Comment by hkaiser** [comment]
> * Drop the `make_` prefix to get e.g. `prefer(with_hint, exec, hint)`

FWIW, I'd prefer this option.

> Renaming is more of a partial fix though. Using `tag_invoke` is inherently more verbose than the P1393 approach. Or?

Right, no way around that, I guess. p1393 puts the main burden on implementers enabling a slightly less verbose interface. OTOH, p2220 puts the onus on the user by requiring a slightly more verbose formulation (the advantage is the much simpler implementation of `prefer` and a less complicated set of API functions related to properties).
