### ISSUE TITLE
Build fails with error "Cannot open include file asio/io_context.hpp"

### ISSUE THREAD

**Issue by Jedi18** [STEllAR-GROUP/hpx#5404]
CMake configuration for generating the visual studio solution could not find ASIO_INCLUDE_DIR . Had to manually add it.

Asio include headers work if `#include <boost/asio/io_context.hpp>` is used instead of `#include <asio/io_context.hpp>` which is how they are used in all the files.

## Expected Behavior
Build succeeds.

## Actual Behavior
Build fails with these messages:
```
85>main.cpp
85>C:\Users\targe\Documents\hpx\libs\core\io_service\include\hpx\io_service\io_service_pool.hpp(18,10): fatal error C1083: Cannot open include file: 'asio/io_context.hpp': No such file or directory (compiling source file C:\Users\targe\Documents\hpx\init\src\hpx_main_argc_argv.cpp)
85>C:\Users\targe\Documents\hpx\libs\core\io_service\include\hpx\io_service\io_service_pool.hpp(18,10): fatal error C1083: Cannot open include file: 'asio/io_context.hpp': No such file or directory (compiling source file C:\Users\targe\Documents\hpx\init\src\hpx_main.cpp)
85>C:\Users\targe\Documents\hpx\libs\core\io_service\include\hpx\io_service\io_service_pool.hpp(18,10): fatal error C1083: Cannot open include file: 'asio/io_context.hpp': No such file or directory (compiling source file C:\Users\targe\Documents\hpx\init\src\hpx_user_main.cpp)
85>C:\Users\targe\Documents\hpx\libs\core\io_service\include\hpx\io_service\io_service_pool.hpp(18,10): fatal error C1083: Cannot open include file: 'asio/io_context.hpp': No such file or directory (compiling source file C:\Users\targe\Documents\hpx\init\src\hpx_main_variables_map.cpp)
85>C:\Users\targe\Documents\hpx\libs\core\io_service\include\hpx\io_service\io_service_pool.hpp(18,10): fatal error C1083: Cannot open include file: 'asio/io_context.hpp': No such file or directory (compiling source file C:\Users\targe\Documents\hpx\init\src\main.cpp)
85>C:\Users\targe\Documents\hpx\libs\core\io_service\include\hpx\io_service\io_service_pool.hpp(18,10): fatal error C1083: Cannot open include file: 'asio/io_context.hpp': No such file or directory (compiling source file C:\Users\targe\Documents\hpx\init\src\hpx_user_main_argc_argv.cpp)
85>Done building project "hpx_init.vcxproj" -- FAILED.
```
## Specifications
HPX Version: Built from the master
Platform : VC2019, Windows

**Comment by msimberg** [comment]
Where do you have Asio installed? Do you specify ASIO_ROOT, and if yes where do you point it to? Could you also post the out from the cmake configuration? Note that earlier Asio was not searched for, it was always fetched by HPX so it would always be "found". If you want to fetch it automatically you'd need to set HPX_WITH_FETCH_ASIO=ON.

**Comment by Jedi18** [comment]
Isn't asio installed with boost? I dind't specify ASIO_ROOT but specified ASIO_INCLUDE_DIR to the boost/asio folder.

Anyway on building it successfully on an older commit, when I came back to it and tried it again the cmake configuration worked without needing to specify the asio path. However I still get the include errors when trying to build it.

CMake config output (now that it is able to detect asio at boost/asio)
https://gist.github.com/Jedi18/4c977267ad09bc3e614b6b931d64603a

Should it not point to the boost/asio folder but instead be fetched by HPX to work correctly?

**Comment by msimberg** [comment]
Oh boy, this is a fun one to explain... There's Boost.Asio, and there's https://github.com/chriskohlhoff/asio/. They're the same, but different (i.e. not interchangeable). #5158 changed to use the standalone Asio over Boost.Asio, but indeed Boost.Asio is still available because we still depend on Boost otherwise in a few places (i.e. we add the include paths implicitly for Boost.Asio, but we don't include anything from Boost.Asio). The move to the standalone Asio might've made more sense once we're Boost-free otherwise (hindsight...), but it's a bit late for that now.

I recommend you simply set `-DHPX_WITH_FETCH_ASIO=ON` unless you can get the standalone Asio from vcpkg or similar?

**Comment by Jedi18** [comment]
Thanks, that explains everything. Yeah it's working with -DHPX_WITH_FETCH_ASIO=ON (I wasn't setting it properly before, turns out you need to press the configure button twice in cmake gui when adding a new argument)

**Comment by Spongman** [comment]
Is there a way to have HPX use the asio that comes with boost? My codebase already makes heavy use of boost/asio, imports the asio namespace globally and refactoring it to use a different version of the same library is a complete pain.

**Comment by hkaiser** [comment]
> Is there a way to have HPX use the asio that comes with boost? My codebase already makes heavy use of boost/asio, imports the asio namespace globally and refactoring it to use a different version of the same library is a complete pain.

You should be able to use Boost.Asio and Asio at the same time - in principle. However this certainly might not be feasible if your codebase globally imports `boost::asio`. In HPX, we have no way to use Boost.Asio anymore, we have replaced it with Asio unconditionally.
