### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by kordejong** [STEllAR-GROUP/hpx#5412]
## Expected Behavior

Build without link error.

## Actual Behavior

When using HPX CMake targets it seems pthread is not in the list of libs to link against.

## Steps to Reproduce the Problem

  1. Configure HPX without any arguments.
  1. Compile a simple Hello World program
  1. Link against hpx, wrap_main, iostreams_component

## Specifications

  - HPX Version: 1.7.0-rc2
  - Platform (compiler, OS): gcc / linux (kubuntu 20.04)

It seems relevant that the libasio-dev package is used to provide asio. When configuring HPX with `HPX_WITH_FETCH_ASIO=ON` all is well.

When passing `pthread` to CMake's `target_link_libraries` (in addition to HPX' targets), the link error is gone.

**Comment by msimberg** [comment]
@kordejong would you mind trying the following:

- Adding `-DTHREADS_PREFER_PTHREAD_FLAG=TRUE`, and separately
- The above together with commenting out the two lines here: https://github.com/STEllAR-GROUP/hpx/blob/dad2180c2c8dd93fcfec0aa89a4d479925deb126/CMakeLists.txt#L1733-L1734

If neither of these work, I'll try to put together a workaround. I have a hunch about where to put those flags.

**Comment by kordejong** [comment]
Adding`-DPTHREAD_PREFER_PTHREAD_FLAG=TRUE` resulted in the same link error.

Adding`-DPTHREAD_PREFER_PTHREAD_FLAG=TRUE` and commenting out the two lines in `hpx/CMakeLists.txt` resulted in a CMake configure error:

```
-- Configuring done
CMake Error at /tmp/hello_hpx-fetch_content/Debug-default/build/_deps/hpx-src/cmake/HPX_GeneratePackageUtils.cmake:368 (file):
  Error evaluating generator expression:

    $<COMPILE_LANG_AND_ID:CUDA,NVIDIA>

  $<COMPILE_LANG_AND_ID:lang,id> may only be used with binary targets to
  specify include directories, compile definitions, and compile options.  It
  may not be used with the add_custom_command, add_custom_target, or
  file(GENERATE) commands.
Call Stack (most recent call first):
  /tmp/hello_hpx-fetch_content/Debug-default/build/_deps/hpx-src/cmake/HPX_GeneratePackage.cmake:145 (hpx_generate_pkgconfig_from_target)
  /tmp/hello_hpx-fetch_content/Debug-default/build/_deps/hpx-src/CMakeLists.txt:2533 (include)
```

**Comment by msimberg** [comment]
Interesting... thanks for checking. Could I ask you to please try one last thing? Do things work if you set `-DHPX_WITH_PKGCONFIG=OFF`?

**Comment by kordejong** [comment]
Only setting `-DHPX_WITH_PKGCONFIG=OFF` also results in the link error during link of the hello world application.

**Comment by kordejong** [comment]
Success! I tried all of your edits at the same time:
- Comment out the two lines in the `hpx/CMakeLists.txt` file
- Passing `HPX_WITH_PKGCONFIG=OFF`
- Pass `-DTHREADS_PREFER_PTHREAD_FLAG=TRUE`
Now the build succeeds.

**Comment by msimberg** [comment]
@kordejong thanks for checking again. That's very good to hear. Would it be sufficient for use case if we apply the two first fixes, and leave you to turn off pkgconfig support? We have an open issue for that exact issue here: https://github.com/STEllAR-GROUP/hpx/issues/4942. However, we don't have a fix in the works and it's relatively low priority for us. We may remove pkgconfig support in the future.

**Comment by kordejong** [comment]
Sure, that is fine with me. Note however that this link issue pops up with an almost completely default HPX build on a popular Linux distribution. More people may run into this issue. If I understand correctly, with your proposed fixes I would have to either
- Pass `-DHPX_WITH_PKGCONFIG=OFF` to CMake, or
- Pass `HPX_WITH_FETCH_ASIO=ON`

**Comment by msimberg** [comment]
> Sure, that is fine with me. Note however that this link issue pops up with an almost completely default HPX build on a popular Linux distribution. More people may run into this issue. If I understand correctly, with your proposed fixes I would have to either
> 
>     * Pass `-DHPX_WITH_PKGCONFIG=OFF` to CMake, or
> 
>     * Pass `HPX_WITH_FETCH_ASIO=ON`

Yes, fair point. I think long term we anyway want to turn off pkgconfig support at least by default. Not sure what others think about this. Too sudden to do it for 1.7.0?

**Comment by hkaiser** [comment]
> Too sudden to do it for 1.7.0?

Disable support for pkgconfig now (without removing it) is ok, I think. only very few people use it.
