### ISSUE TITLE
Deprecation warning in HPX' own header

### ISSUE THREAD

**Issue by kordejong** [STEllAR-GROUP/hpx#5419]
## Expected Behavior

Compile without warnings.

## Actual Behavior

Compiler warning:

```
_deps/hpx-build/libs/full/async_distributed/include_compatibility/hpx/lcos/promise.hpp:21:2: warning: #warning "The header hpx/lcos/promise.hpp is deprecated, " "please include hpx/include/async.hpp instead" "To disable this warning, please define HPX_HAVE_DEPRECATION_WARNINGS=0."
```

## Steps to Reproduce the Problem

Build HPX with gcc and warning flag `-Wcpp`.

## Specifications

  - HPX Version: 1.7.0-rc2
  - Platform (compiler, OS): gcc, Linux

**Comment by msimberg** [comment]
Hmm, does the warning tell you what file included `hpx/lcos/promise.hpp`?

**Comment by kordejong** [comment]
Good question. My own... Sorry for the noise. I will drink some more coffee now.

**Comment by msimberg** [comment]
No problem! I did get a bit worried since we test for this...

**Comment by kordejong** [comment]
> No problem! I did get a bit worried since we test for this...

And the testing pays off! I am very happy HPX builds as cleanly as it does.
