### ISSUE TITLE
hpx.dll built with vcpkg got functions pointing to the same location

### ISSUE THREAD

**Issue by jjyyxx** [STEllAR-GROUP/hpx#5478]
The problem arises when experimenting with `1d_stencil_6.cpp`, running with only one locality is fine, but with more than one locality (thus needs serialization) AND in release mode (some optimization happens), the program throws at location
https://github.com/STEllAR-GROUP/hpx/blob/76a2ba5b266008be5e0d5a13e17ae0950099dde2/libs/full/naming/src/credit_handling.cpp#L495-L502

I am just getting started with hpx. I found this exception weird (checkpoint-related functions are never used and do not even have function address due to no template instantiation) and debugged a bit, I found that multiple no-op functions pointing to the same location, which may cause the problem. However, I'm not confident it's an issue caused by hpx library or cmake or vcpkg port or msvc compiler.

## Expected Behavior

`hpx::serialization::detail::extra_archive_data_helper<hpx::serialization::detail::preprocess_gid_types>::id(void)` and `hpx::serialization::detail::extra_archive_data_helper<hpx::util::checkpointing_tag>::id(void)` should have different address. Otherwise, it will break `id_ == id` checking in `hpx::serialization::detail::extra_archive_data_node::get()`.

https://github.com/STEllAR-GROUP/hpx/blob/76a2ba5b266008be5e0d5a13e17ae0950099dde2/libs/core/serialization/include/hpx/serialization/detail/extra_archive_data.hpp#L117-L136

## Actual Behavior

A bunch of functions got same address, including two mentioned above.

Part of hpx.dll exports with same address (using IDA), ordinal 5311 and 5312 are the two functions mentioned above.
![image](https://user-images.githubusercontent.com/13808089/127488610-aca9eacc-f8a5-4fe2-838b-b81be7b75f2d.png)

## Steps to Reproduce the Problem

  1. Get vcpkg and install hpx with `vcpkg install hpx`
  2. Check function address in hpx.dll (with a Disassembler or print with iostream)

## Specifications

  - HPX Version: 1.7.0
  - Compiler: MSVC cl 16.10.2+857e5a733
  - OS: Windows 10 19043.1110
  - Arch: amd64

**Comment by hkaiser** [comment]
Could you please try using `1d_stencil_8`, I remember other people having problems with stencil_6 before. 

For the function addresses: I believe that this is an optimization applied by the linker based on the fact that both of those functions are empty. The linker doesn't know that we rely on the addresses of the functions to be different. We should change this code to rely on a variable's address instead. For those, the standard guarantees uniqueness of their addresses. I'll see what I can do.

**Comment by jjyyxx** [comment]
Interestingly, while `1d_stencil_6` breaks on the node 0 side and node 1 keeps waiting, in `1d_stencil_8`, both sides break with the invalid_status exception mentioned above. I think this break is unavoidable as long as some kind of serialization is involved. I guess it relates to MSVC (some specific version or some flags), or others would have discovered this issue before.

**Comment by jjyyxx** [comment]
MSVC document says:
> Because /OPT:ICF can cause the same address to be assigned to different functions or read-only data members (that is, const variables when compiled by using /Gy), it can break a program that depends on unique addresses for functions or read-only data members. For more information, see /Gy (Enable Function-Level Linking).

[/OPT](https://docs.microsoft.com/en-us/cpp/build/reference/opt-optimizations) and [/Gy](https://docs.microsoft.com/en-us/cpp/build/reference/gy-enable-function-level-linking) flags may relate to this issue. However, adjusting these flags may have negative impact on binary size or something? Maybe use variable address works better? I'm not sure

(However, building HPX once takes a long time, and I did not try it out yet)

**Comment by hkaiser** [comment]
@ijyyxx Thanks again for diagnosing and reporting the issue. #5482 provides a possible fix. Would you be able to verify whether the patch solves the issue for you?
