### ISSUE TITLE
Compiling with g++11 on Mac OS fails with mixing std::error_code and boost::error_code

### ISSUE THREAD

**Issue by FunMiles** [STEllAR-GROUP/hpx#5483]
## Expected Behavior

HPX should compile without error

## Actual Behavior

The compilation fails in `connection_handler_tcp.cpp`

> [ 55%] Building CXX object plugins/parcelport/tcp/CMakeFiles/parcelport_tcp.dir/connection_handler_tcp.cpp.o
In file included from /Users/michel/Development/OpenSource/HPX/hpx/plugins/parcelport/tcp/connection_handler_tcp.cpp:1:
/Users/michel/Development/OpenSource/HPX/hpx/libs/core/config/include/hpx/config/detail/compat_error_code.hpp: In destructor 'hpx::compat_error_code::~compat_error_code()':
/Users/michel/Development/OpenSource/HPX/hpx/libs/core/config/include/hpx/config/detail/compat_error_code.hpp:34:19: error: no match for 'operator=' (operand types are 'std::error_code' and 'boost::system::error_code')
   34 |             _ec = _compat;
      |                   ^~~~~~~
In file included from /usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/bits/ios_base.h:46,
                 from /usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/ios:42,
                 from /usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/ostream:38,
                 from /usr/local/include/boost/system/detail/error_code.hpp:21,
                 from /usr/local/include/boost/system/error_code.hpp:13,
                 from /Users/michel/Development/OpenSource/HPX/hpx/libs/core/config/include/hpx/config/detail/compat_error_code.hpp:14,
                 from /Users/michel/Development/OpenSource/HPX/hpx/plugins/parcelport/tcp/connection_handler_tcp.cpp:1:
/usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/system_error:209:7: note: candidate: 'template<class _ErrorCodeEnum> typename std::enable_if<std::is_error_code_enum<_Tp>::value, std::error_code&>::type std::error_code::operator=(_ErrorCodeEnum)'
  209 |       operator=(_ErrorCodeEnum __e) noexcept
      |       ^~~~~~~~
/usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/system_error:209:7: note:   template argument deduction/substitution failed:
/usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/system_error: In substitution of 'template<class _ErrorCodeEnum> typename std::enable_if<std::is_error_code_enum<_Tp>::value, std::error_code&>::type std::error_code::operator=(_ErrorCodeEnum) [with _ErrorCodeEnum = boost::system::error_code]':
/Users/michel/Development/OpenSource/HPX/hpx/libs/core/config/include/hpx/config/detail/compat_error_code.hpp:34:19:   required from here
/usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/system_error:209:7: error: no type named 'type' in 'struct std::enable_if<false, std::error_code&>'
/usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/system_error:180:9: note: candidate: 'constexpr std::error_code& std::error_code::operator=(const std::error_code&)'
  180 |   class error_code
      |         ^~~~~~~~~~
/usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/system_error:180:9: note:   no known conversion for argument 1 from boost::system::error_code' to 'const std::error_code&'
/usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/system_error:180:9: note: candidate: 'constexpr std::error_code& std::error_code::operator=(std::error_code&&)'
/usr/local/Cellar/gcc/11.1.0_1/include/c++/11.1.0/system_error:180:9: note:   no known conversion for argument 1 from boost::system::error_code' to 'std::error_code&&'
make[2]: *** [plugins/parcelport/tcp/CMakeFiles/parcelport_tcp.dir/connection_handler_tcp.cpp.o] Error 1
make[1]: *** [plugins/parcelport/tcp/CMakeFiles/parcelport_tcp.dir/all] Error 2
make: *** [all] Error 2

## Steps to Reproduce the Problem

  1. Install g++11 with `brew install gcc` or update to the latest version with `brew upgrade gcc`
  1. Run `CXX=g++11 cmake <path to hpx>`

## Specifications

  - HPX Version: 1.7.0 (git HEAD, commit  b2bc3480abd269c49439ff4c999cf2f95d5c1936)
  - Platform (compiler, OS): Mac OS 11.5; g++11 from homebrew.

**Comment by msimberg** [comment]
Please see https://github.com/STEllAR-GROUP/hpx/issues/5442. This is a mix of a macOS and Boost issue and you'll likely have to wait for the yet to be released Boost 1.77.

**Comment by FunMiles** [comment]
> Please see #5442. This is a mix of a macOS and Boost issue and you'll likely have to wait for the yet to be released Boost 1.77 (unless you're willing to use master/develop of Boost of course, or apply patches yourself).

Thanks, @msimberg I had missed that issue in the list of existing one (I guess I must have only looked at the opened ones. Maybe leaving issues that are not yet fully resolved open would avoid this type of duplication?).

From reading the discussion the boost::error_code is still in HPX only because of boost::file_system but the full 1.7 HPX should get rid of that requirement as C++17 with std::filesystem will be required. Is that right?

**Comment by msimberg** [comment]
> From reading the discussion the boost::error_code is still in HPX only because of boost::file_system but the full 1.7 HPX should get rid of that requirement as C++17 with std::filesystem will be required. Is that right?

That's correct. I can even give that a go right away since we merged the C++17 branch. It looks like Apple Clang is at least detecting filesystem and it seems to be compiling as well. I've no clue about GCC on macOS again. Do you happen to know if your GCC 11/libstc++ on macOS supports filesystem fully?

**Comment by msimberg** [comment]
See #5491 for an attempt at removing all traces of `boost::system::error_code`.

**Comment by FunMiles** [comment]
> > From reading the discussion the boost::error_code is still in HPX only because of boost::file_system but the full 1.7 HPX should get rid of that requirement as C++17 with std::filesystem will be required. Is that right?
> 
> That's correct. I can even give that a go right away since we merged the C++17 branch. It looks like Apple Clang is at least detecting filesystem and it seems to be compiling as well. I've no clue about GCC on macOS again. Do you happen to know if your GCC 11/libstc++ on macOS supports filesystem fully?

I had tested filesystem on MacOS/Clang early on when it was not yet fully supported. More recently, I've noticed they implement everything I needed and have fully integrated std::filesystem in my codes. I will check with g++11 and report back.

**Comment by FunMiles** [comment]
Reporting back, on MacOS, g++11 as installed by `homebrew` implements all the features of std::filesystem I use in my codes.
