### ISSUE TITLE
Uniform syntax for enums should be implemented

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/hpx#55]
**[reported by blelbach]** *[Trac time Wed Aug 10 15:30:33 2011]* Currently, some of our older enums (such as the one for thread state, and error
codes) use a different syntax than our newer enums. Our newer enums always
prefix the enum name, e.g.

```
    enum foo {
        foo_bar,
        foo_buzz
    };
```

Our older enums generally take the form of:

```
    enum foo_enum {
        bar,
        buzz,
    };
```

We should pick a style, bite the bullet and update all the enums to that style.

**Comment by hkaiser** [comment]
I think this can be closed now as the Boost scoped enum emulation has been replaced by C++11 strongly typed enums (see #2050).
