### ISSUE TITLE
Use contiguous index queue in bulk execution to reduce number of spawned tasks

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#5503]
The fork-join executor uses `contiguous_index_queue` as a lightweight queue for work stealing between the worker threads working on items in the current bulk parallel region. We could use the queue also in `execution::bulk` for `thread_pool_scheduler` and `parallel_executor`. This allows work stealing to still happen but removes the need for "hierarchical scheduling" since only one task per worker thread is needed.

**Comment by msimberg** [comment]
This is now in use in `thread_pool_scheduler` (#5531).

**Comment by hkaiser** [comment]
I think we can close this as #5531 provides a means of using the index queue as needed.
