### ISSUE TITLE
Possible race condition in helper thread / hpx::cout

### ISSUE THREAD

**Issue by antoniupop** [STEllAR-GROUP/hpx#5561]
## Expected Behavior

Program makes progress / does not hang

## Actual Behavior

Program hangs.

## Steps to Reproduce the Problem

The issue is likely the way hpx::cout functions on helper threads. Initially this looked like an issue with (de)serialization, but it seems that was only the way to get user code to be executed on a helper thread. In the following, we force explicit de-serialization which is done on the helper of hte remote node. Any use of hpx::cout there will make the program hang. Replacing hpx::cout by std::cout makes it work again.

```
struct NonImplicitlySerializable
{
  std::uint64_t data;
  NonImplicitlySerializable() {}
  NonImplicitlySerializable(std::uint64_t data) : data(data) {}
  NonImplicitlySerializable(const NonImplicitlySerializable &nis) : data (nis.data) {}

  friend class hpx::serialization::access;
  template <class Archive>
  void load(Archive &ar, const unsigned int version)
  {
    hpx::cout << hpx::endl;
    ar & data;
  }

  template <class Archive>
  void save(Archive &ar, const unsigned int version) const
  {
    ar & data;
  }

  HPX_SERIALIZATION_SPLIT_MEMBER()
};
```
Attached is a very slightly modifier version of fibonacci_futures_distributed.cpp from the HPX 1.7.1 examples that reproduces the issue. 
[fibonacci_futures_distributed.cpp.txt](https://github.com/STEllAR-GROUP/hpx/files/7171026/fibonacci_futures_distributed.cpp.txt)

## Specifications

  - HPX Version: 1.7.1
  - Platform (compiler, OS): ubuntu-20.04 / gcc-10.3.0
  - Manifests from 2 nodes.

**Comment by antoniupop** [comment]
Looks like it is indeed a race - the program will run to completion sporadically.

**Comment by hkaiser** [comment]
We have two PRs pending that address shutdown issues (amongst other things in `hpx::cout`): #5546, #5549. Once these are merged, could you please try again if those solve your issues?

**Comment by antoniupop** [comment]
Sure, will do.

**Comment by hkaiser** [comment]
@antoniupop I believe the mentioned PRs have been merged. Could you please try again to see if that resolves your issue?

**Comment by antoniupop** [comment]
Hi Hartmut,

Thanks, I've now tried and the behaviour has changed in that the linker does not accept the code with the printing within the load function of the serializer anymore. This is probably better, but I think the error is rather difficult to parse (even when knowing what the issue is quite precisely :)
Once the print is removed from load, all compiles, links and executes as expected.
Below the linker error I am getting.


`Scanning dependencies of target fibonacci_futures_distributed
[ 92%] Building CXX object examples/quickstart/CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o
/shared/hpx/examples/quickstart/fibonacci_futures_distributed.cpp: In instantiation of 'void NonImplicitlySerializable::load(Archive&, unsigned int) [with Archive = hpx::serialization::input_archive]':
/shared/hpx/examples/quickstart/fibonacci_futures_distributed.cpp:131:3:   required from here
/shared/hpx/examples/quickstart/fibonacci_futures_distributed.cpp:115:45: warning: unused parameter 'version' [-Wunused-parameter]
  115 |   void load(Archive &ar, const unsigned int version)
      |                          ~~~~~~~~~~~~~~~~~~~^~~~~~~
/shared/hpx/examples/quickstart/fibonacci_futures_distributed.cpp: In instantiation of 'void NonImplicitlySerializable::save(Archive&, unsigned int) const [with Archive = hpx::serialization::output_archive]':
/shared/hpx/examples/quickstart/fibonacci_futures_distributed.cpp:131:3:   required from here
/shared/hpx/examples/quickstart/fibonacci_futures_distributed.cpp:124:45: warning: unused parameter 'version' [-Wunused-parameter]
  124 |   void save(Archive &ar, const unsigned int version) const
      |                          ~~~~~~~~~~~~~~~~~~~^~~~~~~
[ 92%] Linking CXX executable ../../bin/fibonacci_futures_distributed
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: warning: relocation against `_ZTVN3hpx7actions15transfer_actionINS_9iostreams6server13output_stream17write_sync_actionEEE' in read-only section `.text._ZN3hpx7actions6detail15register_actionINS_9iostreams6server13output_stream17write_sync_actionEE6createEv[_ZN3hpx7actions6detail15register_actionINS_9iostreams6server13output_stream17write_sync_actionEE6createEv]'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `hpx::actions::transfer_base_action<hpx::iostreams::server::output_stream::write_sync_action>::get_action_name() const':
fibonacci_futures_distributed.cpp:(.text._ZNK3hpx7actions20transfer_base_actionINS_9iostreams6server13output_stream17write_sync_actionEE15get_action_nameEv[_ZNK3hpx7actions20transfer_base_actionINS_9iostreams6server13output_stream17write_sync_actionEE15get_action_nameEv]+0x5): undefined reference to `char const* hpx::actions::detail::get_action_name<hpx::iostreams::server::output_stream::write_sync_action>()'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `hpx::actions::transfer_base_action<hpx::iostreams::server::output_stream::write_sync_action>::get_action_id() const':
fibonacci_futures_distributed.cpp:(.text._ZNK3hpx7actions20transfer_base_actionINS_9iostreams6server13output_stream17write_sync_actionEE13get_action_idEv[_ZNK3hpx7actions20transfer_base_actionINS_9iostreams6server13output_stream17write_sync_actionEE13get_action_idEv]+0x41): undefined reference to `char const* hpx::actions::detail::get_action_name<hpx::iostreams::server::output_stream::write_sync_action>()'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `hpx::actions::transfer_base_action<hpx::iostreams::server::output_stream::write_sync_action>::get_component_type() const':
fibonacci_futures_distributed.cpp:(.text._ZNK3hpx7actions20transfer_base_actionINS_9iostreams6server13output_stream17write_sync_actionEE18get_component_typeEv[_ZNK3hpx7actions20transfer_base_actionINS_9iostreams6server13output_stream17write_sync_actionEE18get_component_typeEv]+0x5): undefined reference to `hpx::traits::component_type_database<hpx::iostreams::server::output_stream, void>::get()'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `hpx::actions::detail::register_action<hpx::iostreams::server::output_stream::write_sync_action>::create()':
fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions6detail15register_actionINS_9iostreams6server13output_stream17write_sync_actionEE6createEv[_ZN3hpx7actions6detail15register_actionINS_9iostreams6server13output_stream17write_sync_actionEE6createEv]+0xe1): undefined reference to `vtable for hpx::actions::transfer_action<hpx::iostreams::server::output_stream::write_sync_action>'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `hpx::actions::detail::register_action<hpx::iostreams::server::output_stream::write_sync_action>::create_cont()':
fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions6detail15register_actionINS_9iostreams6server13output_stream17write_sync_actionEE11create_contEv[_ZN3hpx7actions6detail15register_actionINS_9iostreams6server13output_stream17write_sync_actionEE11create_contEv]+0xdc): undefined reference to `vtable for hpx::actions::transfer_continuation_action<hpx::iostreams::server::output_stream::write_sync_action>'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `hpx::lcos::local::detail::task_object<void, hpx::util::detail::deferred<hpx::detail::action_invoker<hpx::iostreams::server::output_stream::write_sync_action>, hpx::util::pack_c<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul>, unsigned long, int, unsigned int, unsigned long, hpx::iostreams::detail::buffer>, void, hpx::lcos::detail::task_base<void> >::do_run()':
fibonacci_futures_distributed.cpp:(.text._ZN3hpx4lcos5local6detail11task_objectIvNS_4util6detail8deferredINS_6detail14action_invokerINS_9iostreams6server13output_stream17write_sync_actionEEENS4_6pack_cImJLm0ELm1ELm2ELm3ELm4EEEEJmijmNS9_6detail6bufferEEEEvNS0_6detail9task_baseIvEEE6do_runEv[_ZN3hpx4lcos5local6detail11task_objectIvNS_4util6detail8deferredINS_6detail14action_invokerINS_9iostreams6server13output_stream17write_sync_actionEEENS4_6pack_cImJLm0ELm1ELm2ELm3ELm4EEEEJmijmNS9_6detail6bufferEEEEvNS0_6detail9task_baseIvEEE6do_runEv]+0x5d): undefined reference to `hpx::iostreams::server::output_stream::write_sync(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&)'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `hpx::lcos::future<hpx::traits::extract_action<hpx::iostreams::server::output_stream::write_sync_action, void>::type::local_result_type> hpx::detail::async_local_impl<hpx::iostreams::server::output_stream::write_sync_action, unsigned int, unsigned long, hpx::iostreams::detail::buffer&>(hpx::launch, hpx::naming::id_type const&, hpx::naming::address&, std::pair<bool, hpx::components::pinned_ptr>&, unsigned int&&, unsigned long&&, hpx::iostreams::detail::buffer&) [clone .isra.0]':
fibonacci_futures_distributed.cpp:(.text._ZN3hpx6detail16async_local_implINS_9iostreams6server13output_stream17write_sync_actionEJjmRNS2_6detail6bufferEEEENS_4lcos6futureINS_6traits14extract_actionIT_vE4type17local_result_typeEEENS_6launchERKNS_6naming7id_typeERNSJ_7addressERSt4pairIbNS_10components10pinned_ptrEEDpOT0_.isra.0[_ZN3hpx6detail10async_implINS_9iostreams6server13output_stream17write_sync_actionERKNS0_12async_policyEJjmRNS2_6detail6bufferEEEENS_4lcos6futureINS_6traits14extract_actionIT_vE4type17local_result_typeEEEOT0_RKNS_6naming7id_typeEDpOT1_]+0x49f): undefined reference to `char const* hpx::actions::detail::get_action_name<hpx::iostreams::server::output_stream::write_sync_action>()'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx6detail16async_local_implINS_9iostreams6server13output_stream17write_sync_actionEJjmRNS2_6detail6bufferEEEENS_4lcos6futureINS_6traits14extract_actionIT_vE4type17local_result_typeEEENS_6launchERKNS_6naming7id_typeERNSJ_7addressERSt4pairIbNS_10components10pinned_ptrEEDpOT0_.isra.0[_ZN3hpx6detail10async_implINS_9iostreams6server13output_stream17write_sync_actionERKNS0_12async_policyEJjmRNS2_6detail6bufferEEEENS_4lcos6futureINS_6traits14extract_actionIT_vE4type17local_result_typeEEEOT0_RKNS_6naming7id_typeEDpOT1_]+0x5b0): undefined reference to `hpx::iostreams::server::output_stream::write_sync(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&)'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `void hpx::parcelset::put_parcel_cb<hpx::util::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>, hpx::actions::typed_continuation<void, hpx::util::unused_type>, hpx::iostreams::server::output_stream::write_sync_action&, hpx::threads::thread_priority&, unsigned int, unsigned long, hpx::iostreams::detail::buffer&>(hpx::util::function<void (std::error_code const&, hpx::parcelset::parcel const&), false>&&, hpx::naming::id_type const&, hpx::naming::address&&, hpx::actions::typed_continuation<void, hpx::util::unused_type>&&, hpx::iostreams::server::output_stream::write_sync_action&, hpx::threads::thread_priority&, unsigned int&&, unsigned long&&, hpx::iostreams::detail::buffer&) [clone .isra.0]':
fibonacci_futures_distributed.cpp:(.text._ZN3hpx9parcelset13put_parcel_cbINS_4util8functionIFvRKSt10error_codeRKNS0_6parcelEELb0EEEJNS_7actions18typed_continuationIvNS2_11unused_typeEEERNS_9iostreams6server13output_stream17write_sync_actionERNS_7threads15thread_priorityEjmRNSG_6detail6bufferEEEEvOT_RKNS_6naming7id_typeEONST_7addressEDpOT0_.isra.0[_ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_]+0xd0): undefined reference to `vtable for hpx::actions::transfer_continuation_action<hpx::iostreams::server::output_stream::write_sync_action>'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `void hpx::lcos::packaged_action<hpx::iostreams::server::output_stream::write_sync_action, void, false>::do_apply<unsigned int, unsigned long, hpx::iostreams::detail::buffer&>(hpx::naming::address&&, hpx::naming::id_type const&, hpx::threads::thread_priority, unsigned int&&, unsigned long&&, hpx::iostreams::detail::buffer&)':
fibonacci_futures_distributed.cpp:(.text._ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_[_ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_]+0x732): undefined reference to `char const* hpx::actions::detail::get_action_name<hpx::iostreams::server::output_stream::write_sync_action>()'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_[_ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_]+0x8b0): undefined reference to `char const* hpx::actions::detail::get_action_name<hpx::iostreams::server::output_stream::write_sync_action>()'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_[_ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_]+0x957): undefined reference to `hpx::iostreams::server::output_stream::write_sync(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&)'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_[_ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_]+0x991): undefined reference to `hpx::traits::component_type_database<hpx::iostreams::server::output_stream, void>::get()'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_[_ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_]+0xa84): undefined reference to `char const* hpx::actions::detail::get_action_name<hpx::iostreams::server::output_stream::write_sync_action>()'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_[_ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_]+0xb2b): undefined reference to `hpx::iostreams::server::output_stream::write_sync(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&)'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_[_ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_]+0xb61): undefined reference to `hpx::traits::component_type_database<hpx::iostreams::server::output_stream, void>::get()'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_[_ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_]+0xc2c): undefined reference to `char const* hpx::actions::detail::get_action_name<hpx::iostreams::server::output_stream::write_sync_action>()'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_[_ZN3hpx4lcos15packaged_actionINS_9iostreams6server13output_stream17write_sync_actionEvLb0EE8do_applyIJjmRNS2_6detail6bufferEEEEvONS_6naming7addressERKNSB_7id_typeENS_7threads15thread_priorityEDpOT_]+0xcc8): undefined reference to `char const* hpx::actions::detail::get_action_name<hpx::iostreams::server::output_stream::write_sync_action>()'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `hpx::actions::transfer_continuation_action<fibonacci_future_action>::load(hpx::serialization::input_archive&)':
fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE[_ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE]+0x18): undefined reference to `hpx::cout'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE[_ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE]+0x79): undefined reference to `hpx::cout'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE[_ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE]+0x80): undefined reference to `hpx::cout'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE[_ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE]+0xaf): undefined reference to `hpx::cout'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE[_ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE]+0x154): undefined reference to `hpx::cout'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o:fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE[_ZN3hpx7actions28transfer_continuation_actionI23fibonacci_future_actionE4loadERNS_13serialization13input_archiveE]+0x17f): more undefined references to `hpx::cout' follow
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `hpx::actions::detail::register_action<hpx::iostreams::server::output_stream::write_sync_action>::register_action()':
fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions6detail15register_actionINS_9iostreams6server13output_stream17write_sync_actionEEC2Ev[_ZN3hpx7actions6detail15register_actionINS_9iostreams6server13output_stream17write_sync_actionEEC5Ev]+0x2e): undefined reference to `char const* hpx::actions::detail::get_action_name<hpx::iostreams::server::output_stream::write_sync_action>()'
/usr/bin/ld: CMakeFiles/fibonacci_futures_distributed.dir/fibonacci_futures_distributed.cpp.o: in function `std::pair<hpx::threads::thread_schedule_state, hpx::threads::thread_id> hpx::actions::detail::continuation_thread_function<hpx::iostreams::server::output_stream::write_sync_action>::operator()<hpx::threads::thread_restart_state, void>(hpx::threads::thread_restart_state)':
fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions6detail28continuation_thread_functionINS_9iostreams6server13output_stream17write_sync_actionEEclINS_7threads20thread_restart_stateEvEESt4pairINS9_21thread_schedule_stateENS9_9thread_idEET_[_ZN3hpx7actions6detail28continuation_thread_functionINS_9iostreams6server13output_stream17write_sync_actionEEclINS_7threads20thread_restart_stateEvEESt4pairINS9_21thread_schedule_stateENS9_9thread_idEET_]+0x126): undefined reference to `char const* hpx::actions::detail::get_action_name<hpx::iostreams::server::output_stream::write_sync_action>()'
/usr/bin/ld: fibonacci_futures_distributed.cpp:(.text._ZN3hpx7actions6detail28continuation_thread_functionINS_9iostreams6server13output_stream17write_sync_actionEEclINS_7threads20thread_restart_stateEvEESt4pairINS9_21thread_schedule_stateENS9_9thread_idEET_[_ZN3hpx7actions6detail28continuation_thread_functionINS_9iostreams6server13output_stream17write_sync_actionEEclINS_7threads20thread_restart_stateEvEESt4pairINS9_21thread_schedule_stateENS9_9thread_idEET_]+0x25e): undefined reference to `hpx::iostreams::server::output_stream::write_sync(unsigned int, unsigned long, hpx::iostreams::detail::buffer const&)'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make[2]: *** [examples/quickstart/CMakeFiles/fibonacci_futures_distributed.dir/build.make:109: bin/fibonacci_futures_distributed] Error 1
make[1]: *** [CMakeFiles/Makefile2:173111: examples/quickstart/CMakeFiles/fibonacci_futures_distributed.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
root@slurmctld:/shared/hpx/build#  `

**Comment by hkaiser** [comment]
Uhh, that's unexpected and completely unrelated. I'll investigate. Thanks!

**Comment by hkaiser** [comment]
@antoniupop we're preparing the next release (V1.8) now. Would you mind verifying whether your issue has been resolved?

**Comment by antoniupop** [comment]
Thanks - I'll check ASAP.

**Comment by antoniupop** [comment]
This is indeed fixed, and by now tested on many cases - apologies for not closing sooner.
