### ISSUE TITLE
can't build simple example: "Cannot use the dummy implementation of future_then_dispatch"

### ISSUE THREAD

**Issue by Spongman** [STEllAR-GROUP/hpx#5566]
hpx 1.7.0, 1.7.1
gcc 10.2
boost 1.71
CentOS 7

```
#include <hpx/modules/futures.hpp>

int main()
{
	hpx::make_ready_future(false)
	.then([](auto inner) {
		return inner.get();
	})
	.get();
}
```

```
$ gcc --std=c++17 a.cpp
In file included from /opt/hpx/include/hpx/modules/futures.hpp:14,
                 from a.cpp:1:
/opt/hpx/include/hpx/futures/future.hpp: In instantiation of ‘static decltype(auto) hpx::lcos::detail::future_then_dispatch<Future, FD, Enable>::call(Future&&, T0&&, F&&) [with T0 = main()::<lambda(auto:20)>; F = hpx::error_code&; Future = hpx::lcos::future<bool>; FD = main()::<lambda(auto:20)>; Enable = void]’:
/opt/hpx/include/hpx/futures/future.hpp:781:74:   required by substitution of ‘template<class F, class T0> static decltype (hpx::lcos::detail::future_base<hpx::lcos::future<bool>, bool>::future_then_dispatch<typename std::decay<_Tp2>::type>::call(std::move(fut), forward<T0>(t0), forward<F>(f))) hpx::lcos::detail::future_base<hpx::lcos::future<bool>, bool>::then<F, T0>(hpx::lcos::future<bool>&&, T0&&, F&&, hpx::error_code&) [with F = hpx::error_code&; T0 = main()::<lambda(auto:20)>]’
/opt/hpx/include/hpx/futures/future.hpp:1114:35:   required from ‘decltype(auto) hpx::lcos::future<R>::then(F&&, hpx::error_code&) [with F = main()::<lambda(auto:20)>; R = bool]’
a.cpp:8:3:   required from here
/opt/hpx/include/hpx/futures/future.hpp:437:42: error: static assertion failed: Cannot use the                     dummy implementation of future_then_dispatch, please use                     one of the template specialization.
  437 |             static_assert(sizeof(Future) == 0, "Cannot use the \
      |                           ~~~~~~~~~~~~~~~^~~~
/opt/hpx/include/hpx/futures/future.hpp: In instantiation of ‘static decltype(auto) hpx::lcos::detail::future_then_dispatch<Future, FD, Enable>::call(Future&&, F&&) [with F = main()::<lambda(auto:20)>; Future = hpx::lcos::future<bool>; FD = main()::<lambda(auto:20)>; Enable = void]’:
/opt/hpx/include/hpx/futures/future.hpp:760:73:   required by substitution of ‘template<class F> static decltype (hpx::lcos::detail::future_base<hpx::lcos::future<bool>, bool>::future_then_dispatch<typename std::decay<_Tp>::type>::call(std::move(fut), forward<F>(f))) hpx::lcos::detail::future_base<hpx::lcos::future<bool>, bool>::then<F>(hpx::lcos::future<bool>&&, F&&, hpx::error_code&) [with F = main()::<lambda(auto:20)>]’
/opt/hpx/include/hpx/futures/future.hpp:1114:35:   required from ‘decltype(auto) hpx::lcos::future<R>::then(F&&, hpx::error_code&) [with F = main()::<lambda(auto:20)>; R = bool]’
a.cpp:8:3:   required from here
/opt/hpx/include/hpx/futures/future.hpp:427:42: error: static assertion failed: Cannot use the                     dummy implementation of future_then_dispatch, please use                     one of the template specialization.
  427 |             static_assert(sizeof(Future) == 0, "Cannot use the \
      |                           ~~~~~~~~~~~~~~~^~~~
a.cpp: In function ‘int main()’:
a.cpp:6:7: error: invalid use of ‘void’
    5 |  hpx::make_ready_future(false)
      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    6 |  .then([](auto inner) {
      |  ~~~~~^~~~~~~~~~~~~~~~~
    7 |   return inner.get();
      |   ~~~~~~~~~~~~~~~~~~~
    8 |  })
      |  ~~   
```

**Comment by msimberg** [comment]
You'll need to include either `hpx/future.hpp` or `hpx/local/future.hpp` (the latter is enough if you're not planning on using distributed functionality). Could you try again with that and see if the error goes away?

The `hpx/modules/<modulename>.hpp` headers are really intended for internal use. We mention that here: https://hpx-docs.stellar-group.org/latest/html/libs/parallelism/futures/api.html#futures (very vaguely I realize now; it could be a lot more explicit about it). If you have any suggestions on how and where to communicate this we'd greatly appreciate it. Also, if you did check the manual it might be helpful to know which pages you checked as they might be good candidates for places to mention this.

The guaranteed public API and headers are listed here: https://hpx-docs.stellar-group.org/latest/html/api/public_api.html#public-api.

Ping @dimitraka. This might be something for you to look at as well.

**Comment by msimberg** [comment]
I should add that the example is not going to run as is, but I suppose you might be aware of that already. You'll need to either include `hpx/wrap_main.hpp` and link with `HPX::wrap_main` (the CMake target, we make no guarantees about library names etc. if you're compiling and linking manually like that), or start the runtime explicitly with `hpx::init`. See https://hpx-docs.stellar-group.org/latest/html/manual/starting_the_hpx_runtime.html for more details.

**Comment by Spongman** [comment]
thanks, i'll try that.

btw: i searched for 'future' top-left on the docs page (https://hpx-docs.stellar-group.org/latest/html/index.html), clicked the 1st link 'futures' (https://hpx-docs.stellar-group.org/latest/html/libs/parallelism/futures/docs/index.html?highlight=future), then the 'API Reference' link (https://hpx-docs.stellar-group.org/latest/html/libs/parallelism/futures/api.html#modules-futures-api):

> The contents of this module can be included with the header hpx/modules/futures.hpp.

**Comment by msimberg** [comment]
I don't blame you at all for not reading further. We have lots of room to improve there. This feedback is very helpful, thanks!
