### ISSUE TITLE
[User input needed] Remove (CUDA) compute functionality?

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#5647]
The CUDA builds are currently broken again (or rather the tests fail). The CUDA compute functionality (not the low-level futures integration) has been in maintenance mode for quite some time and is unlikely to see improvements in the future. We've kept it alive in case there are users relying on it. We have two options for the 1.8.0 release:

- Fix it again.
- Just remove it finally.

The latter seems even more appealing if we consider we are not planning to make further improvements to it.

If any users happen to see this, and you're relying on the CUDA functionality, please let us know which parts of it, and how important it is for your use cases.

I'm marking this for 1.8.0 as we should do one or the other before 1.8.0.

**Comment by hkaiser** [comment]
Let's remove it. I'm not aware of anybody using it.
