### ISSUE TITLE
Remove tuple/pair specializations for local_algorithm_result and friends

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#5652]
Historically, we have had specializations for `local_algorithm_result` (module `algorithms`) and `algorithm_result_helper` (module `segmented_algorithms`) for `std::pair` and `hpx::tuple` that are not needed anymore now that the refactoring of our algorithms has been completed. For the same reason, we also don't need the `tagged`, `tagged_pair`, and `tagged_tuple` data structures anymore.

All of those can be removed now.

**Comment by Jedi18** [comment]
@hkaiser It looks like we still use tagged_tuple in partition_copy, I can't recall if I forgot to change it or if it was due to some other reason. Also sort_by_key uses tagged_pair. Should I go ahead and change them?

**Comment by hkaiser** [comment]
> @hkaiser It looks like we still use tagged_tuple in partition_copy, I can't recall if I forgot to change it or if it was due to some other reason. Also sort_by_key uses tagged_pair. Should I go ahead and change them?

Yes, I think we should go ahead and apply changes such that the two algorithms are consistent with everything else.
