### ISSUE TITLE
Info and issue about libfabric+infiniband+hpx without using MPI 

### ISSUE THREAD

**Issue by calzycc** [STEllAR-GROUP/hpx#5665]
So far, I configured HPX to use MPI for the communication between different localities on infiniband network and everything works fine 
`-DHPX_WITH_NETWORKING=ON -DMPI_CXX_COMPILER=mpicxx -DHPX_WITH_PARCELPORT_MPI=ON`

Now, I was wondering if HPX currently supports communication between different localities without using MPI and still on low latency infiniband network.
I tried to use libfabric as followings:
`-DHPX_WITH_NETWORKING=ON -DHPX_WITH_PARCELPORT_LIBFABRIC=ON `

and I got the following compilation error:
`fatal error: hpx/runtime.hpp: No such file or directory
 #include <hpx/runtime.hpp>`

  - HPX Version: 1.7.1
  - Platform (compiler, OS): Centos 7 - HPC cluster with infiniband network

Thanks a lot for helping.

**Comment by hkaiser** [comment]
The infiniband parcelport is currently non-functional (and we should remove it), sorry.

**Comment by msimberg** [comment]
This is about the libfabric parcelport. It is indeed currently non-functional on master. @biddisco is the maintainer of the libfabric parcelport and has been working on updating it but is currently busy with other work. If you're interested it may be possible to try out the branch where this work is happening, but we'll need to hear from @biddisco for more details about this.

**Comment by calzycc** [comment]
@msimberg, @hkaiser thanks a lot for your fast replies. Before requesting the branch @msimberg mentioned, I would like to ask you if you know if the use of HPX using MPI for the communication between localities can outperfom some MPI standard applications and somehow HPX using libfabric might provide additional speed up over using HPX + MPI.

**Comment by hkaiser** [comment]
> @msimberg, @hkaiser thanks a lot for your fast replies. Before requesting the branch @msimberg mentioned, I would like to ask you if you know if the use of HPX using MPI for the communication between localities can outperfom some MPI standard applications 

Only if you can utilize the asynchrony introduced by HPX (i.e. hide the communication latencies behind parallel work).

> and somehow HPX using libfabric might provide additional speed up over using HPX + MPI.

In the past we have seen significant speedup when using the libfabric networking compared to using the MPI parcelport: https://dl.acm.org/doi/pdf/10.1145/3295500.3356221. .
