### ISSUE TITLE
Kokkos compilation fails when using both HPX and CUDA execution spaces with gcc 9.3.0

### ISSUE THREAD

**Issue by G-071** [STEllAR-GROUP/hpx#5692]
During the compilation of Kokkos, I get the following error during the compilation of Kokkos_Core.cpp (and other cpp files for that matter):
```
.../build/hpx/include/asio/execution/allocator.hpp(94): internal error: assertion failed at: "decls.c", line 18210 in add_src_seq_end_of_variable_if_needed

1 catastrophic error detected in the compilation of ".../src/kokkos/core/src/impl/Kokkos_Core.cpp".
Compilation aborted.
```

The error only seems to occur when ```Kokkos_ENABLE_CUDA``` is used together with ```Kokkos_ENABLE_HPX``` - compilation works when either HPX or CUDA is disabled.

I have been using:
- nvcc_wrapper + gcc 9.3.0
- Kokkos with the newest HPX PR (msimberg/kokkos@c8e42baa44cdb13bf26532cff69502db43efed4b)
- HPX master (70ef8024c7e5a7f7de018eb88bfe446ba83d48e5)
- HPX is compiled with ```HPX_WITH_FETCH_ASIO=ON```

**Comment by msimberg** [comment]
This seems to be an issue with Asio + nvcc from Asio 1.17.0 onwards in C++17 mode. I don't have a workaround at the moment other than using Asio 1.16.1 or older.

**Comment by msimberg** [comment]
It seems like nvcc compiles this again correctly starting with CUDA 11.3. I'm going to close this without a workaround in HPX as using either Asio 1.16.1 or CUDA >= 11.3 are both quite simple workarounds and doing the same in HPX is slightly more complicated as it may need ifdefing out large parts of the Asio use in HPX.
