### ISSUE TITLE
Parcelport options result in segfaults

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#5695]
## Expected Behavior

Running the code with options like `-Ihpx.parcel.tcp.enable=0 ` and `-Ihpx.parcel.mpi.enable=1  ` whould work.

## Actual Behavior

Adding these options and the working code fails

```
Fri Dec  3 09:17:29 PST 2021
srun: error: nid001813: tasks 1-3: Segmentation fault
srun: launch/slurm: _step_signal: Terminating StepId=822550.0
slurmstepd: error: *** STEP 822550.0 ON nid001813 CANCELLED AT 2021-12-03T17:17:29 ***
srun: error: nid001813: task 0: Terminated
srun: Force Terminated StepId=822550.0
srun: error: nid001813: tasks 1-3: Segmentation fault
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. Run code with and without options

## Specifications

  - HPX Version: 1.7.1
  - Platform (compiler, OS): 
```
Currently Loaded Modules:
  1) craype-x86-rome         4) perftools-base/21.10.0                      7) cray-pmi-lib/6.0.14        10) darshan/3.2.1    (io)  13) cray-libsci/21.08.1.2 (math)  16) cray-mpich/8.1.10 (mpi)
  2) libfabric/1.11.0.4.79   5) xpmem/2.2.40-7.0.1.0_3.1__g1d7a24d.shasta   8) cuda/11.3.0         (g,c)  11) craype/2.7.11    (c)   14) PrgEnv-gnu/8.2.0      (cpe)
  3) craype-network-ofi      6) cray-pmi/6.0.14                             9) xalt/2.10.2                12) cray-dsmml/0.2.2       15) gcc/9.3.0             (c)

```

**Comment by hkaiser** [comment]
@diehlpk could you please give us the actual output generated by HPX on the failing nodes?

**Comment by diehlpk** [comment]
@hkaiser The above error is all we have, There is nothing more in my slurm output file.

**Comment by diehlpk** [comment]
@hkaiser Even more interesting is, if I compile HPX without the TCP parcelport and only the MPI parcelport, the code segfaults on startup
```

Thu Dec  9 10:04:08 PST 2021
srun: error: nid002173: tasks 1-3: Segmentation fault
srun: launch/slurm: _step_signal: Terminating StepId=833186.0
slurmstepd: error: *** STEP 833186.0 ON nid002173 CANCELLED AT 2021-12-09T18:04:09 ***
srun: error: nid002173: task 0: Terminated
srun: Force Terminated StepId=833186.0
```

**Comment by hkaiser** [comment]
@diehlpk is this still a problem?

**Comment by diehlpk** [comment]
@hkaiser I will test It next week. I am doing the scaling runs for the upcoming paper and do not want to change my working build.

**Comment by diehlpk** [comment]
@hkaiser that is fixed, and the ticket can be closed.
