### ISSUE TITLE
Broken APEX Docs link

### ISSUE THREAD

**Issue by gonidelis** [STEllAR-GROUP/hpx#5698]
Came across a broken link which shoul be redirecting to APEX HPX docs.

It is the last link in the bottom right here:

https://hpx-docs.stellar-group.org/latest/html/manual/optimizing_hpx_applications.html#apex-integration

We probably want to redirect here.

http://uo-oaciss.github.io/apex/

**Comment by msimberg** [comment]
It's been updated on master: https://hpx-docs.stellar-group.org/branches/master/html/manual/optimizing_hpx_applications.html#apex-integration.

**Comment by gonidelis** [comment]
@msimberg  Thanks!
