### ISSUE TITLE
hpx::for_loop executes without checking start and end bounds

### ISSUE THREAD

**Issue by NanmiaoWu** [STEllAR-GROUP/hpx#5735]
## Expected Behavior

... For a hpx::for_loop(execution_policy, start_idx, end_idx, lambda_func), when start_idx is larger or equal to end_idx, hpx::for_loop should not be called.

## Actual Behavior

... hpx::for_loop was called and cannot exit.

## Steps to Reproduce the Problem
example code:
```
#include "hpx/hpx.hpp"
#include "hpx/hpx_init.hpp"

int hpx_main(int argc, char *argv[]) 
{
    int start_idx = 2;
    int end_idx = 1; 

    std::cout << "there \n";
    hpx::for_loop(hpx::execution::par, start_idx, end_idx, [&](int point) {
        std::cout << "Hey! point " << point << " is called \n";
    });    

    std::cout << "finish \n";
    return hpx::finalize();
}

int main(int argc, char* argv[])
{
    // Initialize and run HPX, this example requires to run hpx_main on all
    // localities
    std::vector<std::string> const cfg = {
        "hpx.run_hpx_main!=1",
        "--hpx:ini=hpx.commandline.allow_unknown!=1",
        "--hpx:ini=hpx.commandline.aliasing!=0"
    };
    hpx::init_params init_args;
    init_args.cfg = cfg;  
    
    return hpx::init(argc, argv, init_args);
}
```

output (hangs):
```
(base) nanmiao@jojo:~/Documents/task_project/src/stellar-task-bench/hpx/build_Debug$ myrun -np 1 ./bin/test_hpx_for_loop 
there 
^C(base) nanmiao@jojo:~/Documents/task_project/src/stellar-task-bench/hpx/build_Debug$ 
```

## Specifications

... Please describe your environment

  - HPX Version: 1.8.0 
  - Platform (compiler, OS): gcc7.5.0, ubuntu

**Comment by Deepak-suresh14** [comment]
Hello, I would like to work on this issue if no one is already working on it.

**Comment by hkaiser** [comment]
@deepaksuresh1411 please, give it a go. Let us know if you have questions.

**Comment by deepaksuresh1411** [comment]
@hkaiser  Sure

**Comment by deepaksuresh1411** [comment]
I went through the `loop.hpp` ,`forloop.hpp` and still could not find it. Probably I'm missing something in the code.

**Comment by hkaiser** [comment]
> @hkaiser I was trying to find the error through debugging with gdb. But, unfortunately I could not find any accurate solution for it . For some values of `start_idx` and `end_idx` compilation is getting stuck with parallel execution policies ,

I'm not sure I understand how for some values of the arguments the compilation of for_llop could fail. Please explain.

> but for sequential its at least running the loops. So, if you can share anything about the error more like where I can find it specifically.

Solving this is a bit tricky. currently `for_loop()` assumes to be equivalent to `for(size_t i = begin; i != end; ++i)` which is correct for unsigned values and iterators but causes issues for signed integrals. FOr this reason I think we should simply add a check that will be executed for signed integral arguments only and which returns immediately if `begin >= end`. This check could be added here: https://github.com/STEllAR-GROUP/hpx/blob/master/libs/core/algorithms/include/hpx/parallel/algorithms/for_loop.hpp#L1148

**Comment by deepaksuresh1411** [comment]
The values I was talking about were related to parallel and sequential. Both should atleast start the execution in loops but parallel doesn't do that. So, I thought I have solve both differently/separately.

**Comment by deepaksuresh1411** [comment]
@hkaiser Please have a look at this.
<img width="914" alt="Screenshot 2022-02-08 111527" src="https://user-images.githubusercontent.com/73689713/152926097-6142c91a-551d-43d2-ab07-01e6bcab31dd.png">

**Comment by deepaksuresh1411** [comment]
Now it is giving the desired output for both par and seq. Should I commit changes, let me know

**Comment by hkaiser** [comment]
> @hkaiser Please have a look at this. <img alt="Screenshot 2022-02-08 111527" width="914" src="https://user-images.githubusercontent.com/73689713/152926097-6142c91a-551d-43d2-ab07-01e6bcab31dd.png">

Yes, this is the change we need. However we should apply it only in the case if both, `first` and `last`, are signed integers:
```
    if constexpr (std::is_integral_v<B> && std::is_signed_v<B> &&
        std::is_integral_v<E> && std::is_signed_v<E>)
    {
        if (first >= last) 
            return util::detail::algorithm_result<ExPolicy>::get();
    }
```

**Comment by hkaiser** [comment]
> Thank you so much @hkaiser , I will create a pull request for the same.

Thanks @deepaksuresh1411. Please also add a test confirming your fix.

**Comment by deepaksuresh1411** [comment]
@hkaiser  did u mean the unit test or I have to mention the output of any random for_loop function.

**Comment by hkaiser** [comment]
> @hkaiser did u mean the unit test or I have to mention the output of any random for_loop function.

I meant a unit test verifying the fix is valid. Please add it here: https://github.com/STEllAR-GROUP/hpx/tree/master/libs/core/algorithms/tests/regressions

**Comment by deepaksuresh1411** [comment]
@hkaiser  oh! ok I'll add it,  thank you

**Comment by deepaksuresh1411** [comment]
@hkaiser sorry for asking again, I was trying to write the unit test, but I have very less knowledge of writing unit tests. It would be nice if you can tell me more about how to write tests. Or should I demonstrate an example using `for_loop` function.

**Comment by hkaiser** [comment]
> @hkaiser sorry for asking again, I was trying to write the unit test, but I have very less knowledge of writing unit tests. It would be nice if you can tell me more about how to write tests. Or should I demonstrate an example using `for_loop` function.

A unit test is a small piece of code that will fail without the fix but will pass after applying it. I'd start with creating a smallest possible reproducing use case (a for_loop that hangs) and use this as the unit test. These tests are usually 20-30 lines of code or less.

**Comment by deepaksuresh1411** [comment]
@hkaiser  got it , thanks :)

**Comment by NK-Nikunj** [comment]
@hkaiser @deepaksuresh1411 I believe it will be better to warn the user of the scenario and then return instead of simply returning. This way we safely return from the for loop and provide the user with a warning for debugging help.

**Comment by deepaksuresh1411** [comment]
@NK-Nikunj  yeah even I thought of that .Some how I left that,  Should I make adjustments ?

**Comment by NK-Nikunj** [comment]
@deepaksuresh1411 I've added a request change on your PR. You can use that for reference.

**Comment by deepaksuresh1411** [comment]
@NK-Nikunj  sure

**Comment by deepaksuresh1411** [comment]
@NK-Nikunj  I am not sure how to use this `LOG_DEBUG_MSG` function. How can I initialize it , is there any particular way to call the function.  I searched a lot but couldn't make it. It would be nice if you can guide me through this.
Thanks.

**Comment by hkaiser** [comment]
> @hkaiser @deepaksuresh1411 I believe it will be better to warn the user of the scenario and then return instead of simply returning. This way we safely return from the for loop and provide the user with a warning for debugging help.

Well, if you have a loop like `for(int i = 42; i < 0; ++i) ...` you wouldn't expect to see a warning, would you?

**Comment by deepaksuresh1411** [comment]
> > @hkaiser @deepaksuresh1411 I believe it will be better to warn the user of the scenario and then return instead of simply returning. This way we safely return from the for loop and provide the user with a warning for debugging help.
> 
> Well, if you have a loop like `for(int i = 42; i < 0; ++i) ...` you wouldn't expect to see a warning, would you?

There should be a warning ,If  I'm not wrong  `i` expects value less than zero.

**Comment by hkaiser** [comment]
> > > @hkaiser @deepaksuresh1411 I believe it will be better to warn the user of the scenario and then return instead of simply returning. This way we safely return from the for loop and provide the user with a warning for debugging help.
> > 
> > 
> > Well, if you have a loop like `for(int i = 42; i < 0; ++i) ...` you wouldn't expect to see a warning, would you?
> 
> There should be a warning ,If I'm not wrong `i` expects value less than zero.

Hmmm, since we don't see a warning when using the plain `for()`, I don't think we should start issuing warnings for the `for_loop()`. The goal of fixing this issue is to avoid wrong iteration bounds when using signed integers. We can't do the same when using unsigned integers as the user might have intended overflowing the iteration bounds. Thus, issuing a warning might not be what's expected in all cases after all.
