### ISSUE TITLE
HPX_WITH_FETCH_ASIO not working on Ookami

### ISSUE THREAD

**Issue by NK-Nikunj** [STEllAR-GROUP/hpx#5744]
## Expected Behavior

Cmake should be able to fetch Asio and build it.

## Actual Behavior

See: https://gist.github.com/NK-Nikunj/9ee34206131f4e673b583197ff614032

## Steps to Reproduce the Problem

Use the cmake command:
```
cmake -DCMAKE_PREFIX_PATH=$HOME/install/boost -DCMAKE_INSTALL_PREFIX=$HOME/install/hpx -DCMAKE_BUILD_TYPE=Release -DHPX_WITH_CXX_STANDARD=20 -DHPX_WITH_MALLOC=system -DHPX_WITH_GENERIC_CONTEXT_COROUTINES=ON -DHPX_WITH_FETCH_ASIO=ON ..
```

## Specifications

Please describe your environment

  - HPX Version: master (09376be)
  - Platform (compiler, OS): Compiler - GCC 11.2, Cmake version - 3.22, Boost version - 1.78, Hwloc version - 2.4, OS - CentOS Linux release 8.1.1911

**Comment by hkaiser** [comment]
@NK-Nikunj would you have any clues for what is happening? We're just using cmake's FetchContent, so I wouldn't know what could possibly be wrong. Also, I know that @diehlpk has already built HPX on Ookami, he might have an idea.

**Comment by diehlpk** [comment]
It was working for me, and I am not sure what is going on.

You might want to try to build in 

` /lustre/projects/diehl-group`

since we do not have much space in the user folders

**Comment by NK-Nikunj** [comment]
@diehlpk I'm building on `scratch/<username>` which has no quotas whatsoever. @hkaiser I haven't looked into the issue yet. Just wanted to put it out that I was having an issue.
I was able to reproduce @srinivasyadav18 's build issue as well with GCC 11.2. That's a `#include` error somewhere that's testing for only x86 architectures leading to the build errors. I'm working on a fix (which should be trivial based on what I observed).

**Comment by NK-Nikunj** [comment]
@diehlpk what HPX commit and C++ compiler are you using when building HPX on Ookami?

**Comment by hkaiser** [comment]
> @diehlpk I'm building on `scratch/<username>` which has no quotas whatsoever. @hkaiser I haven't looked into the issue yet. Just wanted to put it out that I was having an issue. I was able to reproduce @srinivasyadav18 's build issue as well with GCC 11.2. That's a `#include` error somewhere that's testing for only x86 architectures leading to the build errors. I'm working on a fix (which should be trivial based on what I observed).

@NK-Nikunj is this the fix you need: https://github.com/STEllAR-GROUP/hpx/pull/5742?

**Comment by diehlpk** [comment]
@NK-Nikunj we use armclang, since HPX does not compile with the official Fusitju compiler. I think we only compiled HPX 1,6 and HPX 1.7.1 for Octo-Tiger.

**Comment by srinivasyadav18** [comment]
> @srinivasyadav18 told me about HPX hanging on basic hello world examples. I couldn't reproduce those at my ends so I've asked him for examples he ran. I will update you once I'm able to reproduce them.

Thanks @NK-Nikunj for solving the issue, things are sorted now! I could finally now run **HPX** on **ookami**.
