### ISSUE TITLE
distributed::channel.regsiter_as terminates the active task.

### ISSUE THREAD

**Issue by John98Zakaria** [STEllAR-GROUP/hpx#5871]
## Expected Behavior

Registering a distributed channel shouldn't terminate the whole task.
The print statements should run.

## Actual Behavior
`    
hpx::cout <<"will register" << std::endl;
channel.register_as(comm_id); // task magically ends here
hpx::cout <<"registered" <<hpx::flush;
channel.set(5);
hpx::cout <<"set value" <<hpx::flush;
`

When running gdb on a single node, it exists the function without executing the print statements after registration.
when running using mpirun -n 2 ./programm a deadlock occurs as rank:0 is unable to register the channel.
So rank:1 keeps waiting in a deadlock.
,

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.
I have attached the code as txt to keep it concise.

[code.txt](https://github.com/STEllAR-GROUP/hpx/files/8588795/code.txt)

When compiling and running on a single node, by simpling calling ./program and using a debugger it crashes when registering the channel.

## Specifications

{config}:
Core library:
  HPX_AGAS_LOCAL_CACHE_SIZE=4096
  HPX_HAVE_MALLOC=jemalloc
  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_PREFIX (configured)=
  HPX_PREFIX=/home/jn98zk/cpp_stuff/hpx-1.7.1/build/installation

  HPX_FILESYSTEM_WITH_BOOST_FILESYSTEM_COMPATIBILITY=OFF
  HPX_ITERATOR_SUPPORT_WITH_BOOST_ITERATOR_TRAVERSAL_TAG_COMPATIBILITY=OFF
  HPX_WITH_AGAS_DUMP_REFCNT_ENTRIES=OFF
  HPX_WITH_APEX=OFF
  HPX_WITH_ASYNC_MPI=OFF
  HPX_WITH_ATTACH_DEBUGGER_ON_TEST_FAILURE=OFF
  HPX_WITH_AUTOMATIC_SERIALIZATION_REGISTRATION=ON
  HPX_WITH_COROUTINE_COUNTERS=OFF
  HPX_WITH_DISTRIBUTED_RUNTIME=ON
  HPX_WITH_DYNAMIC_HPX_MAIN=ON
  HPX_WITH_GOOGLE_PERFTOOLS=OFF
  HPX_WITH_IO_COUNTERS=ON
  HPX_WITH_IO_POOL=ON
  HPX_WITH_ITTNOTIFY=OFF
  HPX_WITH_LOGGING=ON
  HPX_WITH_NETWORKING=ON
  HPX_WITH_PAPI=OFF
  HPX_WITH_PARALLEL_TESTS_BIND_NONE=OFF
  HPX_WITH_PARCELPORT_ACTION_COUNTERS=OFF
  HPX_WITH_PARCELPORT_LIBFABRIC=OFF
  HPX_WITH_PARCELPORT_MPI=ON
  HPX_WITH_PARCELPORT_MPI_MULTITHREADED=ON
  HPX_WITH_PARCELPORT_TCP=ON
  HPX_WITH_PARCEL_COALESCING=ON
  HPX_WITH_PARCEL_PROFILING=OFF
  HPX_WITH_SANITIZERS=OFF
  HPX_WITH_SCHEDULER_LOCAL_STORAGE=OFF
  HPX_WITH_SPINLOCK_DEADLOCK_DETECTION=ON
  HPX_WITH_STACKTRACES=ON
  HPX_WITH_STACKTRACES_DEMANGLE_SYMBOLS=ON
  HPX_WITH_STACKTRACES_STATIC_SYMBOLS=OFF
  HPX_WITH_TESTS_DEBUG_LOG=OFF
  HPX_WITH_THREAD_BACKTRACE_ON_SUSPENSION=OFF
  HPX_WITH_THREAD_CREATION_AND_CLEANUP_RATES=OFF
  HPX_WITH_THREAD_CUMULATIVE_COUNTS=ON
  HPX_WITH_THREAD_DEBUG_INFO=OFF
  HPX_WITH_THREAD_DESCRIPTION_FULL=OFF
  HPX_WITH_THREAD_GUARD_PAGE=ON
  HPX_WITH_THREAD_IDLE_RATES=OFF
  HPX_WITH_THREAD_LOCAL_STORAGE=OFF
  HPX_WITH_THREAD_MANAGER_IDLE_BACKOFF=ON
  HPX_WITH_THREAD_QUEUE_WAITTIME=OFF
  HPX_WITH_THREAD_STACK_MMAP=ON
  HPX_WITH_THREAD_STEALING_COUNTS=OFF
  HPX_WITH_THREAD_TARGET_ADDRESS=OFF
  HPX_WITH_TIMER_POOL=ON
  HPX_WITH_TUPLE_RVALUE_SWAP=ON
  HPX_WITH_VALGRIND=OFF
  HPX_WITH_VERIFY_LOCKS=OFF
  HPX_WITH_VERIFY_LOCKS_BACKTRACE=OFF
  HPX_WITH_VERIFY_LOCKS_GLOBALLY=OFF

Module coroutines:
  HPX_COROUTINES_WITH_SWAP_CONTEXT_EMULATION=OFF

Module datastructures:
  HPX_DATASTRUCTURES_WITH_ADAPT_STD_TUPLE=ON

Module serialization:
  HPX_SERIALIZATION_WITH_ALL_TYPES_ARE_BITWISE_SERIALIZABLE=OFF
  HPX_SERIALIZATION_WITH_BOOST_TYPES=ON

Module topology:
  HPX_TOPOLOGY_WITH_ADDITIONAL_HWLOC_TESTING=OFF

{version}: V1.7.1 (AGAS: V3.0), Git: unknown
{boost}: V1.79.0
{build-type}: release
{date}: Apr 29 2022 00:21:13
{platform}: linux
{compiler}: GNU C++ version 11.1.0
{stdlib}: GNU libstdc++ version 20210427

**Comment by hkaiser** [comment]
Thanks for this report. Would you be able to provide a small self-contained example that exposes the issue?

**Comment by John98Zakaria** [comment]
I tried to reduce it to its core components

If you run this code simply by invoking ./run_code -> Termination after calling channel.regsiter_as();
If you run  using mpirun -n 4 ./run_code -> deadlock as the rank0 dies directly after registration;

`#include <hpx/channel.hpp>
#include <hpx/iostream.hpp>
#include <hpx/barrier.hpp>
#include <hpx/wrap_main.hpp>

HPX_REGISTER_CHANNEL(int)

void do_communication(){
    auto my_rank = hpx::get_locality_id();
    hpx::cout<<"started" << my_rank << hpx::flush;
    auto comm_id = "very_own_comm";
    hpx::distributed::channel<int> channel;
    if(my_rank== 0){
        hpx::cout <<"will register" << std::endl;
        channel.register_as(comm_id).get();
        hpx::cout <<"registered" <<hpx::flush;
        channel.set(5);
        hpx::cout <<"set value" <<hpx::flush;
    }
    else{
        hpx::cout<<"Trying to connect" <<hpx::flush;
        channel.connect_to(comm_id);
        hpx::cout<<"Trying to get value" <<hpx::flush;
        auto value = channel.get().get();
        hpx::cout << "fertig" << value +1;

    }
    hpx::cout<<my_rank << "Done" <<hpx::flush;
}

HPX_PLAIN_ACTION(do_communication);




int main(int argc, char* argv[]){
    do_communication_action act;
    std::vector<hpx::future<void>> futures;
    for (const auto &locality: hpx::find_all_localities()) {
        futures.emplace_back(hpx::async(act,locality));
    }

    hpx::wait_all(futures);
    hpx::finalize();
    hpx::cout <<"Main Done";

    return 0;
}
`

**Comment by John98Zakaria** [comment]
I found the issue !

`
hpx::distributed::channel<int> channel;  // crashes as channel is not bound to any locality;
hpx::distributed::channel<int> channel(hpx::findhere()); // Channel has a locality thus can be registerd
channel.register_as("name")
`

However, the error was not rethrown by  hpx::wait_all(futures) as it eats away the futures.

**Comment by hkaiser** [comment]
> I found the issue !
> 
> `hpx::distributed::channel<int> channel; // crashes as channel is not bound to any locality; hpx::distributed::channel<int> channel(hpx::findhere()); // Channel has a locality thus can be registerd channel.register_as("name")`
> 
> However, the error was not rethrown by hpx::wait_all(futures) as it eats away the futures.

Thanks! This has been resolved recently. `wait_all` now rethrows exceptions (starting V1.8) - too many people have stumbled over this issue.
