### ISSUE TITLE
Problems with HPX serialization as a standalone feature. Testcase provided.

### ISSUE THREAD

**Issue by McKillroy** [STEllAR-GROUP/hpx#5892]
## Expected Behavior

Not really expected, but rather hoped for: Compile correctly.

## Actual Behavior

Inclusion of hpx/serialization.hpp causes compile errors

## Steps to Reproduce the Problem

Use the provided testcase and read its readme.md.

## Specifications

Windows, MSVC 17.2.1
HPX Version: 1.7.1

[vcpkg.zip](https://github.com/STEllAR-GROUP/hpx/files/8738998/vcpkg.zip)

**Comment by hkaiser** [comment]
Compiling your test case:
```
#include <chrono>
#include <iostream>
#include <memory>
#include <thread>

#include <hpx/serialization.hpp>

void run()
{
    std::cout << "Hello from thread." << std::endl;
    // Let's be very patient ....
    std::this_thread::sleep_until(                                     //
        (std::chrono::time_point<std::chrono::system_clock>::max)()    //
    );
    std::cout << "Bye from thread." << std::endl;
}

int main()
{
    std::cout << "Program START" << std::endl;
    auto t = std::make_unique<std::thread>(std::thread(run));
    t->join();
    std::cout << "Program DONE" << std::endl;
}
```
against an installed version of HPX works just fine for me (HPX is not in vcpkg, though). I'm not sure what happens for you. Could you give us the precompiled file, please?

**Comment by McKillroy** [comment]
This is the output when compiling:
```
>------ Build All started: Project: HPX Serialization Explodes App, Configuration: Debug ------
  [1/2] Building CXX object src\CMakeFiles\testcase.dir\testcase.cpp.obj
  FAILED: src/CMakeFiles/testcase.dir/testcase.cpp.obj 
  C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1432~1.313\bin\Hostx64\x64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DHPX_APPLICATION_EXPORTS -DHPX_APPLICATION_NAME_DEFAULT=testcase -DHPX_PREFIX_DEFAULT="\"C:/Arcanima/MIN_CASES/HPX Serialization Explodes App/_out/build/Debug/vcpkg_installed/x64-windows\"" -I"C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\src\.." -external:I "C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\_out\build\Debug\vcpkg_installed\x64-windows\include" -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd /RTC1 -Zc:inline -Zc:throwingNew -Zc:rvalueCast -Zc:strictStrings -Zc:__cplusplus -GR -MP -bigobj /showIncludes /Fosrc\CMakeFiles\testcase.dir\testcase.cpp.obj /Fdsrc\CMakeFiles\testcase.dir\ /FS -c "C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\src\testcase.cpp"
C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\src\testcase.cpp(12): warning C4003: not enough arguments for function-like macro invocation 'max'
C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\src\testcase.cpp(12): error C2589: '(': illegal token on right side of '::'
C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\src\testcase.cpp(12): error C2144: syntax error: 'unknown-type' should be preceded by ')'
C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\src\testcase.cpp(11): error C2660: 'std::this_thread::sleep_until': function does not take 0 arguments
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\thread(183): note: see declaration of 'std::this_thread::sleep_until'
C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\src\testcase.cpp(12): error C2144: syntax error: 'unknown-type' should be preceded by ';'
C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\src\testcase.cpp(12): error C2059: syntax error: ')'
C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\src\testcase.cpp(12): error C2059: syntax error: ')'
C:\Arcanima\MIN_CASES\HPX Serialization Explodes App\src\testcase.cpp(13): error C2059: syntax error: ')'
  ninja: build stopped: subcommand failed.

Build All failed.
```
Not sure what you mean with precompiled files. The entire folder with pulled in dependencies is like 4 GB (Boost, hwlox, everything).
If you install vcpkg, adjust the vcpkg path in CMakePresets.json and open the project folder in Visual Studio it should automatically use vcpkg manifest mode and preoduce the result.
The attached file is the HPX folder in "include" in the build folder. 
[hpx.zip](https://github.com/STEllAR-GROUP/hpx/files/8748964/hpx.zip)

**Comment by McKillroy** [comment]
The error seems to come from the "max" macro definition in "minwindef.h".
I'm not sure how this gets pulled in - but it comes from the inclusion of "serialization.hpp".
If I put a simple "#undef max" in front of the offending line it compiles again.
But I guess in a program using the "max" macro it would not compile anymore.
Seems macros are evil again :(

**Comment by hkaiser** [comment]
@McKillroy ahh, this is because the MSVC libraries have an ancient macro definition `#define max(a, b) ...` that gets in the way. There are two solutions: a) add the preprocessor constant `NOMINMAX` to your compilation environment, or b) do what I have done in the example above and prevent `max` from being expanded as a macro: `(std::chrono::time_point<std::chrono::system_clock>::max)()` (note the additional pair of parenthesis).

**Comment by McKillroy** [comment]
@hkaiser: That worked. Thanks a lot !
