### ISSUE TITLE
Name clash between memory module and memory component

### ISSUE THREAD

**Issue by Neumann-A** [STEllAR-GROUP/hpx#5898]
https://github.com/STEllAR-GROUP/hpx/blob/5ac13348b63d3f768d1155b202522258a12f96f1/cmake/HPX_AddComponent.cmake#L306

creates a name clash on windows creating a component target (components/performance_counters/memory) with build output `hpx_memory.lib` which is already used be the module `hpx_memory` 

https://github.com/STEllAR-GROUP/hpx/blob/5ac13348b63d3f768d1155b202522258a12f96f1/components/performance_counters/memory/CMakeLists.txt#L28

https://github.com/STEllAR-GROUP/hpx/blob/5ac13348b63d3f768d1155b202522258a12f96f1/libs/core/memory/CMakeLists.txt#L24

**Comment by hkaiser** [comment]
The memory counters use the CMake target name `memory_component`. I have not seen any name clashes here.

**Comment by Neumann-A** [comment]
>  target name

It is not the target name but the output name / output path which clashes on windows. The target name is different but the output is the same which make ninja throw up with telling me that there are two rules to create `<some_base_path>/hpx_memory(d).lib`.
Seems to only happen if you try to build static libs (HPX_WITH_STATIC_LINKING ON and BUILD_SHARED_LIBS OFF) on windows which doesn't really seems to be supported (Maybe configure should catch that.).

**Comment by hkaiser** [comment]
> Seems to only happen if you try to build static libs (HPX_WITH_STATIC_LINKING ON and BUILD_SHARED_LIBS OFF) on windows which doesn't really seems to be supported (Maybe configure should catch that.).

Ahh, we don't test this. Historically, the MSVC linker was not able to link everything as the static libraries for the core library were too large. We have not tried ever since ;-)

**Comment by Neumann-A** [comment]
> Historically

When was that? When the x86 toolchain was still the default? (Could have switched to the x64 toolchain) I mean hpx is probably not larger than vtk with vtk-m and python bindings enabled.

**Comment by hkaiser** [comment]
> > Historically
> 
> When was that? When the x86 toolchain was still the default? (Could have switched to the x64 toolchain) I mean hpx is probably not larger than vtk with vtk-m and python bindings enabled.

Yes, could have been. I just have not tried (or even cared) to link statically. Any help you may give would be highly appreciated.

**Comment by hkaiser** [comment]
I'll change the target names.
