### ISSUE TITLE
HPX 1.8.0 and Blaze issues

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#5958]
## Expected Behavior

Blaze and HPX should work

## Actual Behavior

We got many issues with deprecated namespaces for the executors and for_loop.

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1. Build HPX 1.8.0
  1. Build a application using blaze's hpx backend.

## Specifications

  - HPX Version: 1.8.0 or master
  - Platform (compiler, OS): Not important

**Comment by gonidelis** [comment]
@diehlpk Could you confirm?

**Comment by diehlpk** [comment]
Yes, I made a pull request to Blaze a while ago.

**Comment by diehlpk** [comment]
I never tested it with 1.9.0, but the ticket can be closed.

**Comment by gonidelis** [comment]
@diehlpk 1.9.0 has not been published yet.
