### ISSUE TITLE
cxx17_aligned_new.cpp on msvc fails due to wrong pragma directive

### ISSUE THREAD

**Issue by birsoyo** [STEllAR-GROUP/hpx#6108]
The pragma directive trying to force warning 4316 be an error is not correct.
It currently reads `#pragma warning(enable:  4316)`

It should read `#pragma warning(error:  4316)`. i.e. ~`enable`~ should be changed to `error`.

It fails the check due to above error not what cxx17_aligned_new trying to check.

**Comment by hkaiser** [comment]
Thanks for reporting this issue! Would you mind creating a PR for this?
