### ISSUE TITLE
Octotiger multi-node performance drops significantly after recent changes

### ISSUE THREAD

**Issue by JiakunYan** [STEllAR-GROUP/hpx#6141]
@hkaiser  After I rebased my branch to the newest master branch, I found the multi-node performance of octotiger drops almost 100% for both MPI and LCI parcelports. I profiled it with perf. The result showed the hpx runtime spent a large amount of time (~30%) inside `hpx::agas::server::primary_namespace::resolve_gid`. Do you know what could be the reason for it?

**Comment by hkaiser** [comment]
@JiakunYan I don't know what could have caused it. Would you by any chance be able to bisect this issue to find out which commit caused the regression?

**Comment by JiakunYan** [comment]
The problem disappeared. I cannot reproduce the issue even if I went back to the original commit. Let's ignore it at this moment.
