### ISSUE TITLE
hpxcxx does not work if HPX_WITH_PKGCONFIG=OFF

### ISSUE THREAD

**Issue by jtsylve** [STEllAR-GROUP/hpx#6156]
`hpxcxx` depends on the generation of `pkgconfig` directory to locate HPX.  If `HPX_WITH_PKGCONFIG` is set to off (which for some reason is the default on macOS), `hpxcxx` will not be able to locate HPX. 

If `HPX_WITH_PKGCONFIG` is not enabled, `hpxcxx` should not be generated.

**Comment by hkaiser** [comment]
@stevenrbrandt could you take care of this, please?
