### ISSUE TITLE
HPX_WITH_DATAPAR_BACKEND=EVE causes compile errors with C++17

### ISSUE THREAD

**Issue by jtsylve** [STEllAR-GROUP/hpx#6164]
EVE requires C++20 to compile and thus is not compatible with HPX when using the `HPX_WITH_CXX_STANDARD=17` setting.  This is especially problematic given that `HPX_WITH_CXX_STANDARD=17` is the default and provides the best binary compatibility for applications that use HPX and may be compiled with newer standards.   This combination causes compiler errors when building HPX.  The `HPX_WITH_DATAPAR_BACKEND=EVE` option should be disabled when the C++ standard is set to a value < 20.

## Steps to Reproduce the Problem

Attempt to configure and build hpx with both the `HPX_WITH_CXX_STANDARD=17` and  `HPX_WITH_DATAPAR_BACKEND=EVE` options

## Specifications

... Please describe your environment

  - HPX Version: 1.8.1
  - Platform (compiler, OS): any

**Comment by hkaiser** [comment]
Excellent catch! Thanks! @srinivasyadav18 I guess this one is for you to fix ;-)

**Comment by AkashS20** [comment]
Hi, I would like to contribute to this. I'm new to open source so if you could please guide me on solving this,
it will be of great help.

**Comment by hkaiser** [comment]
> Hi, I would like to contribute to this. I'm new to open source so if you could please guide me on solving this, it will be of great help.

Sure, that'd be great! Please let us know if you need any additional information.

**Comment by PoroCoco** [comment]
What should the desired behavior be for this case ? I currently implemented a fatal_error that stops the Cmake generation if we're using both  ``HPX_WITH_DATAPAR_BACKEND=EVE`` and ``HPX_WITH_CXX_STANDARD`` < 20 .

**Comment by hkaiser** [comment]
> What should the desired behavior be for this case ? I currently implemented a fatal_error using hpx_error that stops the Cmake generation if we're using both `HPX_WITH_DATAPAR_BACKEND=EVE` and `HPX_WITH_CXX_STANDARD` < 20 .

What errors do you see, could you be a bit more explanatory, please?

**Comment by hkaiser** [comment]
> What should the desired behavior be for this case ? I currently implemented a fatal_error using hpx_error that stops the Cmake generation if we're using both `HPX_WITH_DATAPAR_BACKEND=EVE` and `HPX_WITH_CXX_STANDARD` < 20 .

Yes, I think it's the best we can do to circumvent it from happening. I'd use our existing `hpx_error()` macro for this, btw.
