### ISSUE TITLE
Release Tag Name Request

### ISSUE THREAD

**Issue by jtsylve** [STEllAR-GROUP/hpx#6171]
This is a bit of an odd request, but going forward, when making a release, would it be possible to use Github's default convention of creating a tag that starts with "v".  For example instead of the tag being `1.9.0` it would be `v1.9.0`.  The reason for the request is to better support [CPM](https://github.com/cpm-cmake/CPM.cmake).

I'm currently attempting to add HPX as a source code dependency using's CPM's versioning support as follows:

```
CPMAddPackage(
    NAME hpx
    GITHUB_REPOSITORY STEllAR-GROUP/hpx
    VERSION 1.8.1
)
```

This fails, because CPM looks for a version tag using the standard `v###` convention.

**Comment by hkaiser** [comment]
That's an odd default, but sure - we can definitely do that. 

@gonidelis could you take a note to use this naming scheme from now on? We also may need to slightly modify our release scripts for that, possibly add a new bash variable here: https://github.com/STEllAR-GROUP/hpx/blob/cb5c6ffa7f9b8453a1f796e0c9ec03c7dc710179/tools/roll_release.sh#L18-L21

**Comment by gonidelis** [comment]
@jtsylve @hkaiser definately! Thanks for noticing. Will take care of it.

**Comment by gonidelis** [comment]
@hkaiser this should do the trick I think

https://github.com/STEllAR-GROUP/hpx/pull/6138/commits/ab36ed860474bb99c39f775f41fcdc88ac966319

Will verify it with rc-1.

**Comment by gonidelis** [comment]
If you query tags on Github I think this should be fixed now. @jtsylve thanks.
