### ISSUE TITLE
Broken Links to the Documentation page in readme.rst

### ISSUE THREAD

**Issue by matrixbot123** [STEllAR-GROUP/hpx#6214]
## Expected Behavior

the links are broken in readme.rst in libs/core and libs/full 
![image](https://user-images.githubusercontent.com/32158555/228435638-c3fc08ee-7f25-4d72-8fe9-5ef4dfc221b6.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/32158555/228435723-590b6ac1-7d6c-4445-8e08-49a95ea12a4e.png)

## Steps to Reproduce the Problem
you can just observe it by going through the readme.rst in lib folders

## Fix
just have to update the specific paths

**Comment by hkaiser** [comment]
@dimitraka Would you have the time to have a look, please?

**Comment by dimitraka** [comment]
> @dimitraka Would you have the time to have a look, please?

Sure, I will take a look!

**Comment by hkaiser** [comment]
I think this has been resolved now. Closing.
