### ISSUE TITLE
Startup barrier issue & hangs on shutdown

### ISSUE THREAD

**Issue by Pansysk75** [STEllAR-GROUP/hpx#6245]
## Issue: 
Distributed HPX runtime hanging on shutdown, likely caused by the pre-main barriers not having completed properly.

## How to reproduce:

I manage to reproduce it by running the following empty program on 2 processes on my computer 
(launched with `--hpx:threads=4 --hpx:localities=2 --hpx:node=0` 
and `--hpx:threads=4 --hpx:localities=2 --hpx:node=1` respectively):
```
#include <hpx/hpx_main.hpp>

int main()
{
    return 0;
}
```

## Configuration:
HPX Version: Current master branch
Compiler: MSVC 14.35

## Debug Logs
@hkaiser Here's the debug logs, which also include the address of the barrier object on barrier_node::wait and barrier_node::set_event calls. Let me know if you meant sth else.

[debug_log_node0.txt](https://github.com/STEllAR-GROUP/hpx/files/11500979/debug_log_node0.txt)
[debug_log_node1.txt](https://github.com/STEllAR-GROUP/hpx/files/11500978/debug_log_node1.txt)

Also this comment from #6236 still applies:
https://github.com/STEllAR-GROUP/hpx/pull/6236#issuecomment-1544667250

**Comment by Pansysk75** [comment]
After examining closer, it seems that the thread that is waiting on this condition variable never completes:
https://github.com/STEllAR-GROUP/hpx/blob/bbd69d71442f5aba60000b87401aa57e414274db/libs/core/synchronization/include/hpx/synchronization/barrier.hpp#L223
https://github.com/STEllAR-GROUP/hpx/blob/bbd69d71442f5aba60000b87401aa57e414274db/libs/core/synchronization/include/hpx/synchronization/barrier.hpp#L157

I observe that the thread enters "pending" state when the condition variable gets triggered with notify_all().
But then, before it gets to enter "running" state and terminate gracefully, post_main runs (because my program is empty, so post_main runs immediately after pre_main), and the barrier gets reset (through barrier::detach()).

If this is the case, this shouldn't be a real issue for hpx programs that actually contain any work.
But it remains that the barrier shouldn't be reset when some thread is waiting on that condition variable.

**Comment by hkaiser** [comment]
@Pansysk75 thank you, this is very helpful. I will try to do something about this.

**Comment by hkaiser** [comment]
@Pansysk75 could you please try #6251 to see if that resolves the issue?

**Comment by Pansysk75** [comment]
> @Pansysk75 could you please try #6251 to see if that resolves the issue?

@hkaiser yup, seems to resolve the issue, nice!
