### ISSUE TITLE
Problems using the hpx.stacks:use_guard_pages parameter

### ISSUE THREAD

**Issue by G-071** [STEllAR-GROUP/hpx#6288]
To run larger scenarios with Octo-Tiger on a single node, we usually have to add the parameter ```--hpx.stacks:use_guard_pages=0```. Recently (not quite sure when this started to happen), passing this parameter caused an issue within Octo-Tiger though:

```
terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::unknown_option>'
  what():  unrecognised option '--hpx.stacks:use_guard_pages=0'
```
Note, that this error is thrown when Octo-Tiger itself is parsing its CLI parameters (well after hpx::init). 

Simply adding the parameter to the Octo-Tiger command used to work without any issue! Has something recently changed regarding the HPX CLI parameters, which might cause this one to be forwarded to Octo-Tiger somehow?

**Comment by hkaiser** [comment]
The option should be `--hpx:ini=hpx.stacks.use_guard_pages!=0`. Did the option you list ever work before?

**Comment by G-071** [comment]
Ah, a typo sneaked into the original issue text - I meant ```-Ihpx.stacks.use_guard_pages=0```. Same issue though!

This flag is actually recommended by the exception HPX throws in case use_guard_pages=0 is required (but not set):
```
{what}: mmap() failed to allocate thread stack due to insufficient resources, increase /proc/sys/vm/max_map_count or add -Ihpx.stacks.use_guard_pages=0 to the command line: HPX(unhandled_exception)
```
I believe it's this exception [here](https://github.com/STEllAR-GROUP/hpx/blob/7ad876c4d79aab119097bb413a8f175936fbb5d6/libs/core/coroutines/include/hpx/coroutines/detail/posix_utility.hpp#L107).
If memory serves, that flag used to work, as the common scenario was to hit this exception with certain octotiger configurations and add the flag afterwards to fix it! It has been a while since I needed it though.

That being said, the flag you gave me works as intended! It is probably best to change the text for the exception accordingly, as adding this flag on-demand after hitting the exception will probably remain a common scenario.
