### ISSUE TITLE
Zero-copy receive optimization disabled the invocation of direct actions

### ISSUE THREAD

**Issue by JiakunYan** [STEllAR-GROUP/hpx#6291]
This is a note for what we discussed this week.

Enabling zero-copy receive optimization will disable all direct actions. It should be fixed.

I pasted the related code below
```
    template <typename Parcelport, typename Buffer>
    std::vector<parcelset::parcel> decode_message_with_chunks(
        serialization::input_archive& archive, [[maybe_unused]] Parcelport& pp,
        [[maybe_unused]] Buffer& buffer, std::size_t parcel_count,
        std::size_t num_thread = -1)
    {
           ........
                    else if (deferred_schedule || allow_zero_copy_receive)
                    {
                        // store parcel if needed
                        deferred_parcels.emplace_back(HPX_MOVE(p));
                    }
```
https://github.com/STEllAR-GROUP/hpx/blob/8a949a755414f5e908caeb4c03e1ba635e110b4f/libs/full/parcelset/include/hpx/parcelset/decode_parcels.hpp#L354

**Comment by vivekd01** [comment]
template <typename Parcelport, typename Buffer>
std::vector<parcelset::parcel> decode_message_with_chunks(
    serialization::input_archive& archive, Parcelport& pp,
    Buffer& buffer, std::size_t parcel_count,
    std::size_t num_thread = -1)
{
    // ...
    else if (deferred_schedule || allow_zero_copy_receive)
    {
        // store parcel if needed
        deferred_parcels.push_back(std::move(p));
    }
    // ...
}

**Comment by vivekd01** [comment]
implementation and usage of the deferred_parcels container to ensure it is defined correctly and use appropriately.

**Comment by hkaiser** [comment]
After some analysis of the code - direct actions are still supported, even with zero-copy support on the receiver being enabled. I'll close this ticket.
