### ISSUE TITLE
Update config for coroutines on ARM

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#6298]
@eugeneswalker would you be able to try #38812? This is a missing conflict in the package. @hkaiser I think you can also update the ifdefs in HPX to fall back to the posix implementation as an alternative to Boost.Context. If and when you update those in HPX we can add an upper bound for the version in the conflict.

_Originally posted by @msimberg in https://github.com/spack/spack/issues/38796#issuecomment-1628469565_

**Comment by hkaiser** [comment]
This has been fixed.

**Comment by felixguendling** [comment]
Are there plans to officially support ARM officially as a platform? As ARM became more and more relevant in all areas, including servers/cloud, this would make hpx more interesting.

The documentation does not list ARM as supported:
https://github.com/STEllAR-GROUP/hpx/blob/master/docs/sphinx/manual/prerequisites.rst?plain=1#L20-L29
