### ISSUE TITLE
Log hpx threads on forced shutdown

### ISSUE THREAD

**Issue by Pansysk75** [STEllAR-GROUP/hpx#6329]
When an HPX process hangs (usually because some hpx thread hasn't terminated properly), the process is often killed with a termination signal.
In such cases, logging information about any alive hpx threads would really help me in debugging, especially when an issue is hard to reproduce locally.

@hkaiser I can certainly add this if you also think it makes sense, only could you please point me to where exit signals are handled? Thanks!

**Comment by hkaiser** [comment]
@Pansysk75 Thanks! The termination handlers are here: https://github.com/STEllAR-GROUP/hpx/blob/bc993dd15b9252908e0b30b9ed5efd830cf99909/libs/core/runtime_local/src/runtime_local.cpp#L65-L174

**Comment by Pansysk75** [comment]
Issue closed by merging of PR https://github.com/STEllAR-GROUP/hpx/pull/6340
