### ISSUE TITLE
Single page documentation is broken

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/hpx#6355]
## Expected Behavior

There are also available a [PDF](https://hpx-docs.stellar-group.org/pdf/HPX.pdf) version of this documentation as well as a [Single HTML Page](https://hpx-docs.stellar-group.org/singlehtml/index.h).

The link (https://hpx-docs.stellar-group.org/singlehtml/index.h) to the single HTML Page should work.

## Actual Behavior

The link results in a 404 page not found.

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  1.  Click on the link
 

## Specifications

... Please describe your environment

  - HPX Version: Master documentation
  - Platform (compiler, OS): NA

**Comment by hkaiser** [comment]
@dimitraka would you be able to find out what's going on here?

**Comment by hkaiser** [comment]
This has been fixed by #6360
