### ISSUE TITLE
[Feature] Install dependencies using CMake

### ISSUE THREAD

**Issue by SAtacker** [STEllAR-GROUP/hpx#6392]
## Expected Behavior

- Follow https://github.com/SAtacker/hpx-template cmake fetch content to download hwloc and boost dependencies depending upon the platform. 

- Allow user to have configurable behaviors i.e. system can find boost which is already existing. Enable users to fetch content boost and hwloc using`HPX_WITH_FETCH_BOOST=ON` and `HPX_WITH_FETCH_HWLOC=ON`

- Add tests for the same

CC @Shanmukh-C

**Comment by vrnimje** [comment]
Hello @SAtacker , is this issue open for anyone to work on, or only Shanmukh-C is supposed to work on it?
I have decent experience with CMakeLists.txt
And for testing out options, I created a clone of your repository: https://github.com/vrnimje/hpx-temp/tree/cmake
and tested out some workflows as well: https://github.com/vrnimje/hpx-temp/actions

**Comment by SAtacker** [comment]
> Hello @SAtacker , is this issue open for anyone to work on, or only Shanmukh-C is supposed to work on it? I have decent experience with CMakeLists.txt And for testing out options, I created a clone of your repository: https://github.com/vrnimje/hpx-temp/tree/cmake and tested out some workflows as well: https://github.com/vrnimje/hpx-temp/actions

Yes, you can definitely work on this! Seems like you have already looked into it. 
(We have plenty of things to work on so you folks don’t have to worry)
What’s your id for discord on the IRC for STE||AR Group?

**Comment by vrnimje** [comment]
> Yes, you can definitely work on this! Seems like you have already looked into it. (We have plenty of things to work on so you folks don’t have to worry) What’s your id for discord on the IRC for STE||AR Group?

Thanks for the confirmation. Will get started with working on the issue right away. Just had a couple of queries:
1. Changes should be made in the main [`CMakeLists.txt`](https://github.com/STEllAR-GROUP/hpx/blob/master/CMakeLists.txt) of this repository, right?
2. Do `tests` (mentioned in 3rd pt. of the issue), mean workflow build tests?

And here is my Discord ID: `verve0304`

**Comment by SAtacker** [comment]
> Changes should be made in the main [CMakeLists.txt](https://github.com/STEllAR-GROUP/hpx/blob/master/CMakeLists.txt) of this repository, right?

You'll have to figure that out yourself. But yeah, some of the mechanism can also be found in https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/HPX_SetupBoost.cmake , use your best judgement and make reasonable code changes.

> Do tests (mentioned in 3rd pt. of the issue), mean workflow build tests?

Yes, there are a few workflows in https://github.com/STEllAR-GROUP/hpx/tree/master/.github/workflows you can add your newly added cmake variable options as a separate test case(s) and try to compile and verify.

**Comment by vrnimje** [comment]
Update:
I have added the `HPX_WITH_FETCH_HWLOC` option [here](https://github.com/vrnimje/hpx-fork/tree/cmake_options), and is working perfectly for Linux and MacOS. Test for [Linux](https://github.com/vrnimje/hpx-fork/actions/workflows/linux_debug_fetch_hwloc.yml) & [MacOS](https://github.com/vrnimje/hpx-fork/actions/workflows/macos_debug_fetch_hwloc.yml)

In Windows, it builds correctly but the tests fail: [Workflow run](https://github.com/vrnimje/hpx-fork/actions/runs/7068859561)

**Comment by SAtacker** [comment]
> Update: I have added the `HPX_WITH_FETCH_HWLOC` option [here](https://github.com/vrnimje/hpx-fork/tree/cmake_options), and is working perfectly for Linux and MacOS. Test for [Linux](https://github.com/vrnimje/hpx-fork/actions/workflows/linux_debug_fetch_hwloc.yml) & [MacOS](https://github.com/vrnimje/hpx-fork/actions/workflows/macos_debug_fetch_hwloc.yml)
> 
> In Windows, it builds correctly but the tests fail: [Workflow run](https://github.com/vrnimje/hpx-fork/actions/runs/7068859561)

Could please you make a PR ?

**Comment by vrnimje** [comment]
Hello @SAtacker , I have tried adding the `HPX_WITH_FETCH_BOOST` option, and it is compiling for Linux and Windows, but in macOS the `find_package` call is not able to find Boost.Context [here](https://github.com/vrnimje/hpx-fork/actions/runs/7310280916/job/19918736333#step:4:143)

Here are the modifications I have made: [`HPX_SetupBoost.cmake`](https://github.com/vrnimje/hpx-fork/blob/boost_fetch/cmake/HPX_SetupBoost.cmake#L119-L169)

Can you please take a look? Should I open a PR?

**Comment by SAtacker** [comment]
> Hello @SAtacker , I have tried adding the `HPX_WITH_FETCH_BOOST` option, and it is compiling for Linux and Windows, but in macOS the `find_package` call is not able to find Boost.Context [here](https://github.com/vrnimje/hpx-fork/actions/runs/7310280916/job/19918736333#step:4:143)
> 
> Here are the modifications I have made: [`HPX_SetupBoost.cmake`](https://github.com/vrnimje/hpx-fork/blob/boost_fetch/cmake/HPX_SetupBoost.cmake#L119-L169)
> 
> Can you please take a look? Should I open a PR?

https://github.com/vrnimje/hpx-fork/blob/48d422f5b2f1eee6dd2497f728e0383fc70fbe5d/cmake/HPX_SetupBoost.cmake#L152 you have downloaded boost 1.84 and trying to find 1.81 which is one problem but not necessary to cause the error. https://github.com/SAtacker/hpx-template/blob/main/CMakeLists.txt works for macOS too. I have not included find_package(Boost) in my cmakelists

**Comment by vrnimje** [comment]
> https://github.com/vrnimje/hpx-fork/blob/48d422f5b2f1eee6dd2497f728e0383fc70fbe5d/cmake/HPX_SetupBoost.cmake#L152 you have downloaded boost 1.84 and trying to find 1.81 which is one problem but not necessary to cause the error. https://github.com/SAtacker/hpx-template/blob/main/CMakeLists.txt works for macOS too. I have not included find_package(Boost) in my cmakelists

Thanks, turns out there was an unnecessary add_library call, before building Boost.

**Comment by vrnimje** [comment]
Update:
I have added the Boost Fetch option as well, and it is building successfully for [Linux](https://github.com/vrnimje/hpx-fork/actions/runs/7372253089/job/20060404597) and [Windows](https://github.com/vrnimje/hpx-fork/actions/runs/7372253088/job/20060404600)
In macOS, the `unit tests` fail to build, due to following [error](https://github.com/vrnimje/hpx-fork/actions/runs/7372253097/job/20060404632#step:6:784), but the main project builds successfully.

**Comment by SAtacker** [comment]
> Update: I have added the Boost Fetch option as well, and it is building successfully for [Linux](https://github.com/vrnimje/hpx-fork/actions/runs/7372253089/job/20060404597) and [Windows](https://github.com/vrnimje/hpx-fork/actions/runs/7372253088/job/20060404600) In macOS, the `unit tests` fail to build, due to following [error](https://github.com/vrnimje/hpx-fork/actions/runs/7372253097/job/20060404632#step:6:784), but the main project builds successfully.

Another random popin! Maybe try it on another macOS machine

**Comment by vrnimje** [comment]
Fixed the error...
It was occurring due to the Cmake Build type being set to `Release`, was supposed to be `Debug`
So now the build on macOS is [successful](https://github.com/vrnimje/hpx-fork/actions/runs/7393619943/job/20113818437)

**Comment by vrnimje** [comment]
Fixed the error
Caused due to cmake build type by default being set to Release
Just had to add `DCMAKE_BUILD_TYPE=Debug`

Builds on macOS successfully: [build](https://github.com/vrnimje/hpx-fork/actions/runs/7393619943/job/20113818437)

**Comment by vrnimje** [comment]
The `HPX_WITH_FETCH_BOOST` option is also implemented, so should we proceed with the PR?

**Comment by vrnimje** [comment]
@SAtacker The `HPX_WITH_FETCH_BOOST` option is also implemented, so should we proceed with the PR?

**Comment by SAtacker** [comment]
> @SAtacker The `HPX_WITH_FETCH_BOOST` option is also implemented, so should we proceed with the PR?

Yes, thanks!
