### ISSUE TITLE
Issue on page /manual/getting_hpx.html

### ISSUE THREAD

**Issue by younghojan** [STEllAR-GROUP/hpx#6446]
Hi there!
I cannot switch to the 1.9.1 branch because it doesn't exist. I see there are tags for v1.9.1 and v1.9.1-rc1 when I use `git tag` command. Should we modify https://hpx-docs.stellar-group.org/latest/html/manual/getting_hpx.html#:~:text=%24%20git%20checkout%201.9.1 to `git checkout v1.9.1`?

**Comment by hkaiser** [comment]
Yes, this should read `v1.9.1`. Thanks! @dimitraka Could you please update this page?

**Comment by dimitraka** [comment]
This is fixed in https://github.com/STEllAR-GROUP/hpx/pull/6450
