### ISSUE TITLE
.

### ISSUE THREAD

**Issue by SamruddhiNavale** [STEllAR-GROUP/hpx#6466]

**Comment by SamruddhiNavale** [comment]
Also, as you can tell I was here for GSOD 2024 and also interested to participate in Bug bounty program to contribute to Stellar as much as possible :)
Thank you!

**Comment by hkaiser** [comment]
I'm not even sure if there is a way to control access rights for the wiki on a page-by-page level.

**Comment by weshaan** [comment]
hmm, documentation in context: [Access permisions](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis)

**Comment by li7hui** [comment]
hpx will die

**Comment by SamruddhiNavale** [comment]
Hello, just closed the issue thinking it was invalid as the comments suggested.
