### ISSUE TITLE
Bullet points in quick start/installing HPX section in documentation incorrectly rendered

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#6586]
Going to https://hpx-docs.stellar-group.org/branches/master/html/quickstart.html#installing-hpx at the moment, the different options for installing HPX are rendered as
![2024-12-11-113813_769x829_scrot](https://github.com/user-attachments/assets/52b70448-a189-4d34-834a-6a7bcab67ece)

I'm guessing the `#. * * ... * *` isn't intentional?

**Comment by hkaiser** [comment]
@dimitraka could you have a look, please?
