### ISSUE TITLE
Implement ispc task interface

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#668]
ispc is a new experimental vectorizing (open source) compiler from intel based on LLVM and clang.
ispc is a C-like language with support for asynchronous tasks. The API  for tasks is documented and supposed to be provided by the users code. It would be very cool if we could provide a HPX implementation for that.
More information can be found here:
General: http://ispc.github.com/
Specific to the task API: http://ispc.github.com/ispc.html#task-parallelism-launch-and-sync-statements

**Comment by hkaiser** [comment]
@sithhell Can we close this? Will your implementation be made available somewhere?

**Comment by sithhell** [comment]
Am 01.05.2016 2:31 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>
> @sithhell Can we close this? Will your implementation be made available
somewhere?

Let's have it open until we actually have the implementation available.

**Comment by hkaiser** [comment]
This implementation has been finished and was merged with the main ispc repository (see: https://github.com/ispc/ispc/pull/1215).
