### ISSUE TITLE
Valgrind

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/hpx#726]
It would be nice if HPX applications could be checked/debugged with valgrind. Can this be made to work?

**Comment by diehlpk** [comment]
Support for valgrind
I had a look and most of the errors are related to boost and they mention on their website that this is a known issue and you need compile boost with valgrind=on option.

> Running programs that switch stacks under valgrind causes problems. Property (b2 command-line) valgrind=on let valgrind treat the memory regions as stack space which suppresses the errors. Users must define BOOST_USE_VALGRIND before including any Boost.Context headers when linking against Boost binaries compiled with valgrind=on.

**Comment by hkaiser** [comment]
I think this can be closed as it has been shown to work. Feel free to reopen if needed.
