### ISSUE TITLE
Create more versatile ibverbs parcelport.

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#840]
While the exisiting parcelport based on the ibverbs rdma_cm API is working well, it is not generally usable with all fabrics providing RDMA support. In order to make HPX more widely usable on RDMA enabled networks, a parcelport using the uDAPL v2 API (http://www.datcollaborative.org/implement.html) should be created.

Another option would be not rely on rdma_cm. Relying on rdma_cm might lead to problems when the kernel drivers don't exist for a particular platform (this is true for the Xeon Phi)

**Comment by biddisco** [comment]
This work has been undertaken in #1401 - so when that one is closed, this one can be also

**Comment by msimberg** [comment]
@sithhell, @biddisco #1401 is now closed. Can this one be closed as well or has something changed?

**Comment by hkaiser** [comment]
@biddisco I don't think this should be closed as the IB parcel-port we have is not fully functional yet.

**Comment by biddisco** [comment]
ok

**Comment by biddisco** [comment]
Closing this because we have a functional but unmaintained verbs PP, now superseded by libfabric

**Comment by aserio** [comment]
@biddisco Is the libfabric parcelport now merged?

**Comment by biddisco** [comment]
The LF PP was merged 2 years ago. Some recent improvements of mine have not yet been.

**Comment by aserio** [comment]
@biddisco Ah, I thought you had merged it while I was out... Are you planning to merge your changes soon so that the LibFabrics parcelport can truly replace the ibverbs?

**Comment by biddisco** [comment]
I do not have time to work on the libfabric stuff at the moment. My branch contains a lot of commits that will probably require considerable cleaning up. In particular, I started work on `rdma_object<T>` and serialization of those objects - that work is not quite finished and ideally should be integrated into the `channel<T>` abstraction. (It also goes way beyond any 'standards conformance' criteria we currently have)

The main problem would be that it introduces a new type of `rdma_object` and `rdma_vector` that would not work with the current tcp parcelport and so they become 'conditional' - i.e. they can only be used when the LF PP is enabled and so code written to target the new features would not compile/run with the default TCP parcelport. To get this stuff working, I had to make changes in a lot of low level serialization and memory management code. I do not have the time to spend 'removing' those features but keeping the recent parcelport fixes.

Feel free to turn this text into a new issue - suggested title = "Merge SC19 libfabric parcelport fixes into master"

**Comment by aserio** [comment]
@biddisco Ok :)  can you put your current code on a branch so I can reference it?

**Comment by biddisco** [comment]
it's still here in the rdma_object branch - it has been for some time. https://github.com/STEllAR-GROUP/hpx/commits/rdma_object

**Comment by aserio** [comment]
Done! You can find the new ticket here: https://github.com/STEllAR-GROUP/hpx/issues/3969
