### ISSUE TITLE
Reduce compiler memory usage

### ISSUE THREAD

**Issue by eschnett** [STEllAR-GROUP/hpx#950]
Compiling HPX applications is slow, and I thus want to use "make -jN" with an N as large a possible (using e.g. the number of cores on the build node).

On Stampede, this fails; the compiler aborts with a segfault since it runs out of memory. Although the login nodes have 16 cores, I can use at most -j4 without running out of memory. Reducing the compiler's memory usage would also help improve build time.

**Comment by msimberg** [comment]
Bumping this as a reminder about the high memory use for compiling partitioned vector.
