### ISSUE TITLE
With SLURM, --hpx:threads=8 should not be necessary

### ISSUE THREAD

**Issue by eschnett** [STEllAR-GROUP/hpx#981]
I am starting my application on Stampede with the MPI parcelport. I submit my job with
```
#SBATCH -N 1 -n 2
```
and I use the command line options
```
ibrun ./bin/block_matrix --hpx:bind=balanced
```
This starts 2 localities with 16 threads each, over-subscribing the nodes. I need to add "--hpx:threads=8" to prevent this.

SLURM sets the environment variable
```
SLURM_TASKS_PER_NODE=2
```
from which HPX could deduce that each locality should use only half of the number of cores on this node by default.

**Comment by sithhell** [comment]
This has been fixed with 7a5f1b0
